#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("王楚钦")], [#age(24)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*3118*], [#delta(0)],
      [2], [#name("梁靖崑")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3004*], [#delta(3)],
      [3], [#name("樊振东")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2969*], [#delta(-1)],
      [4], [#name("马龙")], [#age(36)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2949*], [#delta(2)],
      [5], [#name("林诗栋")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2946*], [#delta(2)],
      [6], [#name("林高远")], [#age(29)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2918*], [#delta(-2)],
      [7], [#name("菲利克斯 勒布伦")], [#age(18)], [#assoc("FRA")], [#right], [#penhold], [#attack], [*2910*], [#delta(-4)],
      [8], [#name("雨果 卡尔德拉诺")], [#age(28)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2906*], [#delta(11)],
      [9], [#name("蒂姆 波尔")], [#age(43)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2893*], [#delta(2)],
      [10], [#name("张本智和")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2890*], [#delta(-2)],
      [11], [#name("林昀儒")], [#age(23)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2888*], [#delta(-2)],
      [12], [#name("周启豪")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2868*], [#delta(-2)],
      [13], [#name("西蒙 高兹")], [#age(30)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2805*], [#delta(18)],
      [14], [#name("特鲁斯 莫雷加德")], [#age(22)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2786*], [#delta(13)],
      [15], [#name("帕特里克 弗朗西斯卡")], [#age(32)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2786*], [#delta(34)],
      [16], [#name("卡纳克 贾哈")], [#age(24)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2785*], [#delta(4)],
      [17], [#name("徐瑛彬")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2783*], [#delta(4)],
      [18], [#name("达科 约奇克")], [#age(26)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2783*], [#delta(-3)],
      [19], [#name("户上隼辅")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2783*], [#delta(-7)],
      [20], [#name("赵大成")], [#age(22)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2777*], [#delta(12)],
      [21], [#name("基里尔 格拉西缅科")], [#age(28)], [#assoc("KAZ")], [#right], [#shakehand], [#attack], [*2772*], [#delta(-4)],
      [22], [#name("林钟勋")], [#age(27)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2771*], [#delta(-4)],
      [23], [#name("李尚洙")], [#age(34)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2768*], [#delta(-1)],
      [24], [#name("邱党")], [#age(28)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2765*], [#delta(0)],
      [25], [#name("马克斯 弗雷塔斯")], [#age(36)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2764*], [#delta(-12)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("张禹珍")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2758*], [#delta(-10)],
      [27], [#name("迪米特里 奥恰洛夫")], [#age(36)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2756*], [#delta(15)],
      [28], [#name("向鹏")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2752*], [#delta(1)],
      [29], [#name("篠塚大登")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2750*], [#delta(1)],
      [30], [#name("松岛辉空")], [#age(17)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2747*], [#delta(-5)],
      [31], [#name("黄镇廷")], [#age(33)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2744*], [#delta(-17)],
      [32], [#name("贝内迪克特 杜达")], [#age(30)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2744*], [#delta(12)],
      [33], [#name("ACHANTA Sharath")], [#age(42)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2738*], [#delta(115)],
      [34], [#name("乔纳森 格罗斯")], [#age(32)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2734*], [#delta(-11)],
      [35], [#name("克里斯坦 卡尔松")], [#age(33)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2732*], [#delta(22)],
      [36], [#name("斯蒂芬 门格尔")], [#age(36)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2732*], [#delta(-3)],
      [37], [#name("梁俨苧")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2730*], [#delta(-2)],
      [38], [#name("吴晙诚")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2730*], [#delta(-12)],
      [39], [#name("周恺")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2730*], [#delta(-3)],
      [40], [#name("吉村真晴")], [#age(31)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2729*], [#delta(30)],
      [41], [#name("刘丁硕")], [#age(26)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2724*], [#delta(-3)],
      [42], [#name("孙闻")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2722*], [#delta(-3)],
      [43], [#name("蒂亚戈 阿波罗尼亚")], [#age(38)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2701*], [#delta(-2)],
      [44], [#name("田中佑汰")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2700*], [#delta(-16)],
      [45], [#name("安德斯 林德")], [#age(26)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2695*], [#delta(-8)],
      [46], [#name("温瑞博")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2692*], [#delta(0)],
      [47], [#name("尼马 阿拉米安")], [#age(32)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2691*], [#delta(1)],
      [48], [#name("雅克布 迪亚斯")], [#age(29)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2687*], [#delta(-8)],
      [49], [#name("薛飞")], [#age(25)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2686*], [#delta(1)],
      [50], [#name("托米斯拉夫 普卡")], [#age(28)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2685*], [#delta(-16)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("安东 卡尔伯格")], [#age(27)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2681*], [#delta(-6)],
      [52], [#name("HABESOHN Daniel")], [#age(38)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2679*], [#delta(72)],
      [53], [#name("夸德里 阿鲁纳")], [#age(36)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2673*], [#delta(-10)],
      [54], [#name("艾利克斯 勒布伦")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2672*], [#delta(-3)],
      [55], [#name("庄智渊")], [#age(43)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2668*], [#delta(18)],
      [56], [#name("马蒂亚斯 法尔克")], [#age(33)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2668*], [#delta(16)],
      [57], [#name("奥维迪乌 伊奥内斯库")], [#age(35)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2666*], [#delta(45)],
      [58], [#name("丹羽孝希")], [#age(30)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2656*], [#delta(-4)],
      [59], [#name("冯翊新")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2655*], [#delta(38)],
      [60], [#name("BADOWSKI Marek")], [#age(27)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2655*], [#delta(-5)],
      [61], [#name("曾蓓勋")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2654*], [#delta(-5)],
      [62], [#name("LAKATOS Tamas")], [#age(29)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2649*], [#delta(-4)],
      [63], [#name("CASSIN Alexandre")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2649*], [#delta(-4)],
      [64], [#name("牛冠凯")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2645*], [#delta(-4)],
      [65], [#name("宇田幸矢")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2642*], [#delta(-18)],
      [66], [#name("诺沙迪 阿拉米扬")], [#age(33)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2637*], [#delta(-13)],
      [67], [#name("赵子豪")], [#age(27)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2623*], [#delta(-5)],
      [68], [#name("RANEFUR Elias")], [#age(28)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2621*], [#delta(-5)],
      [69], [#name("袁励岑")], [#age(24)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2621*], [#delta(-5)],
      [70], [#name("及川瑞基")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2620*], [#delta(-5)],
      [71], [#name("徐海东")], [#age(24)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2620*], [#delta(-5)],
      [72], [#name("GNANASEKARAN Sathiyan")], [#age(31)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2619*], [#delta(114)],
      [73], [#name("MUTTI Matteo")], [#age(24)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2618*], [#delta(-5)],
      [74], [#name("曹巍")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2617*], [#delta(-5)],
      [75], [#name("于子洋")], [#age(26)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2617*], [#delta(-4)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("阿尔瓦罗 罗布勒斯")], [#age(33)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2614*], [#delta(9)],
      [77], [#name("WALTHER Ricardo")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2613*], [#delta(-3)],
      [78], [#name("弗拉迪斯拉夫 乌尔苏")], [#age(23)], [#assoc("MDA")], [#left], [#shakehand], [#attack], [*2612*], [#delta(-3)],
      [79], [#name("BRODD Viktor")], [#age(34)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2612*], [#delta(-3)],
      [80], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(44)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2612*], [#delta(-28)],
      [81], [#name("卢文 菲鲁斯")], [#age(36)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2611*], [#delta(-14)],
      [82], [#name("陈垣宇")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2607*], [#delta(-4)],
      [83], [#name("PERSSON Jon")], [#age(38)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2607*], [#delta(-4)],
      [84], [#name("KULCZYCKI Samuel")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2606*], [#delta(-3)],
      [85], [#name("吉村和弘")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2603*], [#delta(-3)],
      [86], [#name("奥马尔 阿萨尔")], [#age(33)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2603*], [#delta(86)],
      [87], [#name("WOO Hyeonggyu")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2599*], [#delta(-4)],
      [88], [#name("朴圭贤")], [#age(19)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2598*], [#delta(-4)],
      [89], [#name("木造勇人")], [#age(25)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2596*], [#delta(-3)],
      [90], [#name("吉山僚一")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2595*], [#delta(-3)],
      [91], [#name("米洛什 雷德齐姆斯基")], [#age(18)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2595*], [#delta(23)],
      [92], [#name("ORT Kilian")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2594*], [#delta(-3)],
      [93], [#name("RASSENFOSSE Adrien")], [#age(21)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2589*], [#delta(-13)],
      [94], [#name("黄友政")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2585*], [#delta(9)],
      [95], [#name("MONTEIRO Joao")], [#age(41)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2584*], [#delta(-4)],
      [96], [#name("神巧也")], [#age(31)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2580*], [#delta(-2)],
      [97], [#name("GERALDO Joao")], [#age(29)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2578*], [#delta(-1)],
      [98], [#name("严升")], [#age(27)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2576*], [#delta(1)],
      [99], [#name("马金宝")], [#age(24)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2575*], [#delta(-6)],
      [100], [#name("AN Ji Song")], [#age(28)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2574*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("PICARD Vincent")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2573*], [#delta(0)],
      [102], [#name("陈建安")], [#age(33)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2571*], [#delta(2)],
      [103], [#name("凯 斯图姆珀")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2571*], [#delta(2)],
      [104], [#name("AIDA Satoshi")], [#age(31)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2570*], [#delta(2)],
      [105], [#name("爱德华 约内斯库")], [#age(20)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2570*], [#delta(-17)],
      [106], [#name("MARTINKO Jiri")], [#age(25)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2565*], [#delta(2)],
      [107], [#name("THAKKAR Manav")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2565*], [#delta(74)],
      [108], [#name("PANG Koen")], [#age(22)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2564*], [#delta(-47)],
      [109], [#name("廖振珽")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2563*], [#delta(0)],
      [110], [#name("安宰贤")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2560*], [#delta(-33)],
      [111], [#name("HWANG Minha")], [#age(25)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2560*], [#delta(0)],
      [112], [#name("PARK Chan-Hyeok")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2560*], [#delta(0)],
      [113], [#name("CHAN Baldwin")], [#age(20)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2560*], [#delta(78)],
      [114], [#name("高承睿")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2558*], [#delta(1)],
      [115], [#name("LEVENKO Andreas")], [#age(26)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2557*], [#delta(5)],
      [116], [#name("BARDET Lilian")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2557*], [#delta(3)],
      [117], [#name("卢卡 姆拉德诺维奇")], [#age(26)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2553*], [#delta(27)],
      [118], [#name("利亚姆 皮切福德")], [#age(31)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2553*], [#delta(-8)],
      [119], [#name("KOJIC Frane")], [#age(32)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2552*], [#delta(-2)],
      [120], [#name("MATSUYAMA Yuki")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2552*], [#delta(-2)],
      [121], [#name("罗伯特 加尔多斯")], [#age(45)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2549*], [#delta(8)],
      [122], [#name("KUMAR Nikhil")], [#age(21)], [#assoc("USA")], [#left], [#shakehand], [#attack], [*2548*], [#delta(0)],
      [123], [#name("ABDELAZIZ Youssef")], [#age(24)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2548*], [#delta(74)],
      [124], [#name("HACHARD Antoine")], [#age(30)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2545*], [#delta(-1)],
      [125], [#name("安德烈 加奇尼")], [#age(38)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2545*], [#delta(-35)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("ZELJKO Filip")], [#age(28)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2542*], [#delta(28)],
      [127], [#name("KOZUL Deni")], [#age(27)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2542*], [#delta(48)],
      [128], [#name("MOVILEANU Darius")], [#age(19)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2541*], [#delta(-21)],
      [129], [#name("JANCARIK Lubomir")], [#age(37)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2541*], [#delta(-37)],
      [130], [#name("王晨策")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2537*], [#delta(-4)],
      [131], [#name("朴康贤")], [#age(28)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2536*], [#delta(-4)],
      [132], [#name("赵胜敏")], [#age(26)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2536*], [#delta(-37)],
      [133], [#name("KUBIK Maciej")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2532*], [#delta(98)],
      [134], [#name("艾曼纽 莱贝松")], [#age(36)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2532*], [#delta(-4)],
      [135], [#name("DORR Esteban")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2530*], [#delta(-4)],
      [136], [#name("黄彦诚")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2530*], [#delta(-15)],
      [137], [#name("孙正")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2529*], [#delta(-4)],
      [138], [#name("滨田一辉")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2528*], [#delta(-4)],
      [139], [#name("PRYSHCHEPA Ievgen")], [#age(39)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2528*], [#delta(-4)],
      [140], [#name("LEVAJAC Dimitrije")], [#age(23)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2525*], [#delta(-42)],
      [141], [#name("SURAVAJJULA Snehit")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2523*], [#delta(-16)],
      [142], [#name("NOROOZI Afshin")], [#age(39)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2523*], [#delta(-6)],
      [143], [#name("刘夜泊")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2522*], [#delta(-6)],
      [144], [#name("LI Hsin-Yang")], [#age(24)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2517*], [#delta(-6)],
      [145], [#name("MENG Fanbo")], [#age(24)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2512*], [#delta(-6)],
      [146], [#name("ANDRAS Csaba")], [#age(22)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2512*], [#delta(-6)],
      [147], [#name("SEYFRIED Joe")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2510*], [#delta(-6)],
      [148], [#name("SONE Kakeru")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2509*], [#delta(-6)],
      [149], [#name("TSUBOI Yuma")], [#age(27)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2507*], [#delta(-6)],
      [150], [#name("JOUTI Eric")], [#age(30)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2505*], [#delta(44)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("特里斯坦 弗洛雷")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2505*], [#delta(-6)],
      [152], [#name("DE NODREST Leo")], [#age(24)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2504*], [#delta(-6)],
      [153], [#name("MAGDY Shady")], [#age(29)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2504*], [#delta(-6)],
      [154], [#name("YANG Tzu-Yi")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2501*], [#delta(-5)],
      [155], [#name("HAUG Borgar")], [#age(22)], [#assoc("NOR")], [#left], [#shakehand], [#attack], [*2501*], [#delta(-5)],
      [156], [#name("OUAICHE Stephane")], [#age(31)], [#assoc("ALG")], [#left], [#shakehand], [#attack], [*2501*], [NEW],
      [157], [#name("ROLLAND Jules")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2500*], [#delta(-4)],
      [158], [#name("CARVALHO Diogo")], [#age(32)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2499*], [#delta(-6)],
      [159], [#name("ISTRATE Andrei")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2499*], [#delta(10)],
      [160], [#name("SIPOS Rares")], [#age(24)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2497*], [#delta(-5)],
      [161], [#name("KANG Dongsoo")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2495*], [#delta(-5)],
      [162], [#name("LIANG Guodong")], [#age(21)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*2495*], [#delta(-5)],
      [163], [#name("塞德里克 纽廷克")], [#age(31)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2495*], [#delta(5)],
      [164], [#name("ALLEGRO Martin")], [#age(28)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2492*], [#delta(-36)],
      [165], [#name("PENG Wang-Wei")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2491*], [#delta(-7)],
      [166], [#name("郭勇")], [#age(18)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2489*], [#delta(-15)],
      [167], [#name("汪洋")], [#age(30)], [#assoc("SVK")], [#right], [#shakehand], [#defense], [*2489*], [#delta(-51)],
      [168], [#name("孙杨")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2488*], [#delta(44)],
      [169], [#name("REITSPIES David")], [#age(28)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2487*], [#delta(-10)],
      [170], [#name("KIM Daewoo")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2487*], [#delta(-10)],
      [171], [#name("SODERLUND Hampus")], [#age(30)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2485*], [#delta(-10)],
      [172], [#name("SAI Linwei")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2484*], [#delta(-10)],
      [173], [#name("LAM Siu Hang")], [#age(28)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2484*], [#delta(-41)],
      [174], [#name("NG Pak Nam")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2484*], [#delta(-10)],
      [175], [#name("KIM Donghyun")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2481*], [#delta(-5)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("HAGIHARA Keishi")], [#age(19)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2476*], [#delta(-3)],
      [177], [#name("OYEBODE John")], [#age(22)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2476*], [#delta(-3)],
      [178], [#name("WU Jiaji")], [#age(29)], [#assoc("DOM")], [#right], [#penhold], [#attack], [*2474*], [#delta(-1)],
      [179], [#name("DESCHAMPS Hugo")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2473*], [#delta(0)],
      [180], [#name("TSUBOI Gustavo")], [#age(39)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2472*], [#delta(0)],
      [181], [#name("SZUDI Adam")], [#age(28)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2469*], [#delta(1)],
      [182], [#name("SGOUROPOULOS Ioannis")], [#age(24)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2469*], [#delta(-6)],
      [183], [#name("HO Kwan Kit")], [#age(27)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2468*], [#delta(0)],
      [184], [#name("MEISSNER Cedric")], [#age(24)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2467*], [#delta(0)],
      [185], [#name("ISHIY Vitor")], [#age(29)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2467*], [#delta(-18)],
      [186], [#name("YEH Chih-Wei")], [#age(34)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2466*], [#delta(-1)],
      [187], [#name("BERTRAND Irvin")], [#age(24)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2462*], [#delta(1)],
      [188], [#name("ELBEIALI Mohamed")], [#age(36)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2461*], [#delta(15)],
      [189], [#name("REMBERT Bastien")], [#age(24)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2460*], [#delta(1)],
      [190], [#name("CHIRITA Iulian")], [#age(18)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2460*], [#delta(-3)],
      [191], [#name("PARK Gyeongtae")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2459*], [#delta(1)],
      [192], [#name("SHAH Manush")], [#age(23)], [#assoc("IND")], [#left], [#shakehand], [#attack], [*2458*], [#delta(-29)],
      [193], [#name("哈米特 德赛")], [#age(31)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2455*], [#delta(-80)],
      [194], [#name("COTON Flavien")], [#age(16)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2454*], [#delta(1)],
      [195], [#name("CIFUENTES Horacio")], [#age(26)], [#assoc("ARG")], [#right], [#shakehand], [#attack], [*2453*], [#delta(-17)],
      [196], [#name("KOLODZIEJCZYK Maciej")], [#age(23)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2453*], [#delta(-3)],
      [197], [#name("SHAMS Navid")], [#age(19)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2450*], [#delta(17)],
      [198], [#name("BOURRASSAUD Florian")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2449*], [#delta(-2)],
      [199], [#name("BOBOCICA Mihai")], [#age(38)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2447*], [#delta(-10)],
      [200], [#name("SUZUKI Hayate")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2444*], [#delta(-1)],
    )
  )
