#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("孙颖莎")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3172*], [#delta(0)],
      [2], [#name("王曼昱")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3059*], [#delta(0)],
      [3], [#name("陈梦")], [#age(30)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2981*], [#delta(1)],
      [4], [#name("陈幸同")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2932*], [#delta(-1)],
      [5], [#name("张本美和")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2910*], [#delta(11)],
      [6], [#name("早田希娜")], [#age(24)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2870*], [#delta(1)],
      [7], [#name("郑怡静")], [#age(32)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2861*], [#delta(2)],
      [8], [#name("平野美宇")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2855*], [#delta(-2)],
      [9], [#name("何卓佳")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2849*], [#delta(-1)],
      [10], [#name("蒯曼")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2839*], [#delta(2)],
      [11], [#name("伊藤美诚")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2839*], [#delta(-1)],
      [12], [#name("张瑞")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2838*], [#delta(-1)],
      [13], [#name("王艺迪")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2831*], [#delta(-8)],
      [14], [#name("桥本帆乃香")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2825*], [#delta(-1)],
      [15], [#name("钱天一")], [#age(24)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2825*], [#delta(-1)],
      [16], [#name("木原美悠")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2814*], [#delta(1)],
      [17], [#name("陈熠")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2808*], [#delta(1)],
      [18], [#name("石洵瑶")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2800*], [#delta(1)],
      [19], [#name("田志希")], [#age(32)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2790*], [#delta(-4)],
      [20], [#name("伯纳黛特 斯佐科斯")], [#age(29)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2780*], [#delta(0)],
      [21], [#name("大藤沙月")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2775*], [NEW],
      [22], [#name("范思琦")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2768*], [#delta(-1)],
      [23], [#name("石川佳纯")], [#age(31)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2758*], [#delta(-1)],
      [24], [#name("妮娜 米特兰姆")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2757*], [#delta(-1)],
      [25], [#name("阿德里安娜 迪亚兹")], [#age(24)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2753*], [#delta(8)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("安藤南")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2747*], [#delta(-2)],
      [27], [#name("刘炜珊")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2744*], [#delta(-2)],
      [28], [#name("韩莹")], [#age(41)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2741*], [#delta(-2)],
      [29], [#name("小盐遥菜")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2729*], [#delta(-1)],
      [30], [#name("李恩惠")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2728*], [#delta(43)],
      [31], [#name("长崎美柚")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2704*], [#delta(-1)],
      [32], [#name("边宋京")], [#age(23)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2701*], [#delta(-1)],
      [33], [#name("森樱")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2685*], [#delta(1)],
      [34], [#name("芝田沙季")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2684*], [#delta(-5)],
      [35], [#name("申裕斌")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2683*], [#delta(7)],
      [36], [#name("斯丽贾 阿库拉")], [#age(26)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2682*], [#delta(9)],
      [37], [#name("杨晓欣")], [#age(36)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2679*], [#delta(-2)],
      [38], [#name("吴洋晨")], [#age(22)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2677*], [#delta(-2)],
      [39], [#name("冯天薇")], [#age(38)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2671*], [#delta(-1)],
      [40], [#name("徐孝元")], [#age(37)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2663*], [#delta(-3)],
      [41], [#name("佐藤瞳")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2662*], [#delta(0)],
      [42], [#name("杜凯琹")], [#age(28)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2662*], [#delta(-2)],
      [43], [#name("玛妮卡 巴特拉")], [#age(29)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2660*], [#delta(7)],
      [44], [#name("普利西卡 帕瓦德")], [#age(20)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2655*], [#delta(0)],
      [45], [#name("朱芊曦")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2654*], [#delta(-13)],
      [46], [#name("杨屹韵")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2653*], [#delta(-3)],
      [47], [#name("韩菲儿")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2631*], [#delta(1)],
      [48], [#name("李雅可")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2629*], [#delta(1)],
      [49], [#name("覃予萱")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2627*], [#delta(2)],
      [50], [#name("横井咲樱")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2626*], [NEW],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("奥拉万 帕拉南")], [#age(27)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2625*], [#delta(18)],
      [52], [#name("范姝涵")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2625*], [#delta(0)],
      [53], [#name("袁嘉楠")], [#age(39)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2624*], [#delta(-7)],
      [54], [#name("朱成竹")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2623*], [#delta(66)],
      [55], [#name("索菲亚 波尔卡诺娃")], [#age(30)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2620*], [#delta(-28)],
      [56], [#name("朱思冰")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2619*], [#delta(-2)],
      [57], [#name("王晓彤")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2617*], [#delta(-2)],
      [58], [#name("布里特 伊尔兰德")], [#age(30)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2617*], [#delta(23)],
      [59], [#name("倪夏莲")], [#age(61)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2614*], [#delta(-3)],
      [60], [#name("李皓晴")], [#age(32)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2613*], [#delta(-13)],
      [61], [#name("徐奕")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2605*], [#delta(-4)],
      [62], [#name("郭雨涵")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2600*], [#delta(-4)],
      [63], [#name("WAN Yuan")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2591*], [#delta(49)],
      [64], [#name("艾希卡 穆克吉")], [#age(27)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2591*], [#delta(-3)],
      [65], [#name("肖瑶茜")], [#age(30)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2590*], [#delta(-26)],
      [66], [#name("齐菲")], [#age(24)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2588*], [#delta(-3)],
      [67], [#name("蒂娜 梅谢芙")], [#age(30)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2580*], [#delta(4)],
      [68], [#name("PESOTSKA Margaryta")], [#age(33)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2579*], [#delta(2)],
      [69], [#name("苏萨西尼 萨维塔布特")], [#age(30)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2578*], [#delta(-4)],
      [70], [#name("张墨")], [#age(35)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2566*], [#delta(25)],
      [71], [#name("安妮特 考夫曼")], [#age(18)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2565*], [#delta(5)],
      [72], [#name("萨比亚 温特")], [#age(32)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2565*], [#delta(15)],
      [73], [#name("曾尖")], [#age(28)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2564*], [#delta(19)],
      [74], [#name("高桥 布鲁娜")], [#age(24)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2563*], [#delta(5)],
      [75], [#name("LEE Daeun")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2563*], [#delta(65)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("邵杰妮")], [#age(30)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2560*], [#delta(4)],
      [77], [#name("李昱谆")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2558*], [#delta(20)],
      [78], [#name("刘杨子")], [#age(22)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2553*], [#delta(4)],
      [79], [#name("NOMURA Moe")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2552*], [#delta(5)],
      [80], [#name("崔孝珠")], [#age(26)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2551*], [#delta(-12)],
      [81], [#name("ZHANG Xiangyu")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2549*], [#delta(5)],
      [82], [#name("笹尾明日香")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2546*], [#delta(-4)],
      [83], [#name("PARK Gahyeon")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2545*], [#delta(68)],
      [84], [#name("克里斯蒂娜 卡尔伯格")], [#age(24)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2545*], [#delta(-7)],
      [85], [#name("梁夏银")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2544*], [#delta(-21)],
      [86], [#name("DRAGOMAN Andreea")], [#age(24)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2544*], [#delta(-27)],
      [87], [#name("ARAPOVIC Hana")], [#age(20)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2544*], [#delta(-4)],
      [88], [#name("陈沂芊")], [#age(22)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2538*], [#delta(-16)],
      [89], [#name("AKAE Kaho")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2535*], [#delta(1)],
      [90], [#name("SOO Wai Yam")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2535*], [#delta(-2)],
      [91], [#name("DIACONU Adina")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2534*], [#delta(-24)],
      [92], [#name("金琴英")], [#age(23)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2533*], [#delta(-3)],
      [93], [#name("金河英")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2533*], [#delta(9)],
      [94], [#name("张安")], [#age(28)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2523*], [#delta(-28)],
      [95], [#name("KIM Haeun")], [#age(27)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2517*], [NEW],
      [96], [#name("LIU Hsing-Yin")], [#age(37)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2515*], [#delta(-2)],
      [97], [#name("金娜英")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2514*], [#delta(-44)],
      [98], [#name("傅玉")], [#age(46)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2513*], [#delta(11)],
      [99], [#name("ZAHARIA Elena")], [#age(20)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2511*], [#delta(34)],
      [100], [#name("MENDE Rin")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2510*], [#delta(-4)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("伊丽莎白 萨玛拉")], [#age(35)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2509*], [#delta(-41)],
      [102], [#name("苏蒂尔塔 穆克吉")], [#age(29)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2509*], [#delta(-4)],
      [103], [#name("MATELOVA Hana")], [#age(34)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2508*], [#delta(-29)],
      [104], [#name("OJIO Yuna")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2506*], [#delta(-5)],
      [105], [#name("DE NUTTE Sarah")], [#age(32)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2504*], [#delta(-20)],
      [106], [#name("HUANG Yi-Hua")], [#age(40)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2502*], [#delta(0)],
      [107], [#name("GHORPADE Yashaswini")], [#age(20)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2501*], [#delta(58)],
      [108], [#name("纵歌曼")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2500*], [#delta(-7)],
      [109], [#name("王 艾米")], [#age(22)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2493*], [#delta(-5)],
      [110], [#name("CIOBANU Irina")], [#age(29)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2492*], [#delta(-5)],
      [111], [#name("BILENKO Tetyana")], [#age(41)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2490*], [#delta(-4)],
      [112], [#name("LI Yuqi")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2489*], [#delta(-2)],
      [113], [#name("杨蕙菁")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2488*], [#delta(-2)],
      [114], [#name("HUANG Yu-Chiao")], [#age(28)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2488*], [#delta(-21)],
      [115], [#name("BAJOR Natalia")], [#age(27)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2486*], [#delta(-40)],
      [116], [#name("李时温")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2485*], [#delta(-54)],
      [117], [#name("MADARASZ Dora")], [#age(31)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2480*], [#delta(-2)],
      [118], [#name("单晓娜")], [#age(41)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2478*], [#delta(-27)],
      [119], [#name("AOKI Sachi")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2476*], [#delta(-2)],
      [120], [#name("WANG Tianyi")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2469*], [#delta(1)],
      [121], [#name("KAMATH Archana")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2469*], [#delta(8)],
      [122], [#name("乔治娜 波塔")], [#age(39)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2468*], [#delta(-9)],
      [123], [#name("PICCOLIN Giorgia")], [#age(28)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2467*], [#delta(14)],
      [124], [#name("吴咏琳")], [#age(21)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2463*], [#delta(-16)],
      [125], [#name("RYU Hanna")], [#age(22)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2462*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("SER Lin Qian")], [#age(18)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2462*], [#delta(4)],
      [127], [#name("KIM Byeolnim")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2462*], [#delta(-2)],
      [128], [#name("陈思羽")], [#age(31)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2461*], [#delta(-25)],
      [129], [#name("PARTYKA Natalia")], [#age(35)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2460*], [#delta(-3)],
      [130], [#name("刘佳")], [#age(42)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2459*], [#delta(-2)],
      [131], [#name("CHENG Hsien-Tzu")], [#age(31)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2457*], [#delta(-7)],
      [132], [#name("WEGRZYN Katarzyna")], [#age(23)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2452*], [#delta(-32)],
      [133], [#name("CHA Su Yong")], [#age(24)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2451*], [#delta(-2)],
      [134], [#name("SUGASAWA Yukari")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2450*], [#delta(-2)],
      [135], [#name("MALOBABIC Ivana")], [#age(44)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2447*], [#delta(-13)],
      [136], [#name("SINGEORZAN Ioana")], [#age(20)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2440*], [#delta(-22)],
      [137], [#name("TAKAMORI Mao")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2439*], [#delta(-3)],
      [138], [#name("HO Tin-Tin")], [#age(26)], [#assoc("ENG")], [#right], [#penhold], [#attack], [*2437*], [#delta(-2)],
      [139], [#name("ZANG Xiaotong")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2437*], [#delta(-4)],
      [140], [#name("CHEN Ying-Chen")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2433*], [#delta(-2)],
      [141], [#name("PLAIAN Tania")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2431*], [#delta(21)],
      [142], [#name("GHOSH Swastika")], [#age(21)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2426*], [#delta(41)],
      [143], [#name("LENG Yutong")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2424*], [#delta(-1)],
      [144], [#name("TOLIOU Aikaterini")], [#age(29)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2423*], [#delta(-1)],
      [145], [#name("MATIUNINA Veronika")], [#age(18)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2421*], [#delta(-18)],
      [146], [#name("琳达 伯格斯特罗姆")], [#age(29)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2421*], [#delta(21)],
      [147], [#name("MANTZ Chantal")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2421*], [#delta(54)],
      [148], [#name("SAWETTABUT Jinnipa")], [#age(24)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2421*], [#delta(-1)],
      [149], [#name("LUTZ Camille")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2415*], [#delta(-10)],
      [150], [#name("MORET Rachel")], [#age(35)], [#assoc("SUI")], [#left], [#shakehand], [#attack], [*2415*], [#delta(-32)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("YOON Hyobin")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2415*], [#delta(-5)],
      [152], [#name("UESAWA Anne")], [#age(17)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2414*], [#delta(76)],
      [153], [#name("SURJAN Sabina")], [#age(24)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2414*], [#delta(-34)],
      [154], [#name("ALTINKAYA Sibel")], [#age(31)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2413*], [#delta(53)],
      [155], [#name("LUTZ Charlotte")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2411*], [#delta(15)],
      [156], [#name("汉娜 高达")], [#age(17)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2408*], [#delta(-40)],
      [157], [#name("BLASKOVA Zdena")], [#age(23)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2408*], [#delta(-13)],
      [158], [#name("SUNG Rachel")], [#age(20)], [#assoc("USA")], [#left], [#shakehand], [#attack], [*2407*], [#delta(-5)],
      [159], [#name("ROY Krittwika")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2407*], [#delta(-5)],
      [160], [#name("KUKULKOVA Tatiana")], [#age(24)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2406*], [#delta(-2)],
      [161], [#name("DING Yijie")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2404*], [#delta(-5)],
      [162], [#name("CHASSELIN Pauline")], [#age(27)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2402*], [#delta(-5)],
      [163], [#name("YEH Yi-Tian")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2400*], [#delta(-3)],
      [164], [#name("SU Pei-Ling")], [#age(24)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2399*], [#delta(-15)],
      [165], [#name("HUANG Yu-Wen")], [#age(28)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2398*], [#delta(-4)],
      [166], [#name("GRIESEL Mia")], [#age(18)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2396*], [#delta(-3)],
      [167], [#name("LUPULESKU Izabela")], [#age(25)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2395*], [#delta(-26)],
      [168], [#name("HAPONOVA Hanna")], [#age(39)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2394*], [#delta(-4)],
      [169], [#name("MOYLAND Sally")], [#age(17)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2392*], [#delta(-3)],
      [170], [#name("WONG Hoi Tung")], [#age(19)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2392*], [#delta(17)],
      [171], [#name("CHENG Pusyuan")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2390*], [#delta(-3)],
      [172], [#name("YAN Yutong")], [#age(16)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2389*], [#delta(-3)],
      [173], [#name("JI Eunchae")], [#age(28)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2388*], [#delta(-25)],
      [174], [#name("ZHOU Jingyi")], [#age(19)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2387*], [#delta(30)],
      [175], [#name("TAKEYA Misuzu")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2387*], [#delta(18)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("MIGOT Marie")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2384*], [#delta(-5)],
      [177], [#name("KIM Seongjin")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2383*], [#delta(-5)],
      [178], [#name("HURSEY Anna")], [#age(18)], [#assoc("WAL")], [#right], [#shakehand], [#attack], [*2383*], [#delta(-28)],
      [179], [#name("LAM Yee Lok")], [#age(28)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2381*], [#delta(-6)],
      [180], [#name("KUMAHARA Luca")], [#age(29)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2380*], [#delta(-6)],
      [181], [#name("BERGAND Filippa")], [#age(25)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2379*], [#delta(22)],
      [182], [#name("LOEUILLETTE Stephanie")], [#age(32)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2377*], [#delta(-23)],
      [183], [#name("BRATEYKO Solomiya")], [#age(25)], [#assoc("UKR")], [#left], [#shakehand], [#attack], [*2374*], [#delta(-31)],
      [184], [#name("YOO Siwoo")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2372*], [#delta(71)],
      [185], [#name("LEE Seungeun")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2372*], [#delta(-7)],
      [186], [#name("CHITALE Diya")], [#age(21)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2371*], [#delta(-7)],
      [187], [#name("RAKOVAC Lea")], [#age(28)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2369*], [#delta(5)],
      [188], [#name("NAGYVARADI Mercedes")], [#age(30)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2369*], [#delta(-8)],
      [189], [#name("SOLJA Amelie")], [#age(34)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2368*], [#delta(-7)],
      [190], [#name("GUISNEL Oceane")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2366*], [#delta(-14)],
      [191], [#name("ZHANG Wenjing")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#defense], [*2361*], [#delta(-5)],
      [192], [#name("ZARIF Audrey")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2361*], [#delta(31)],
      [193], [#name("CHEN Chi-Shiuan")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2359*], [#delta(-5)],
      [194], [#name("BALAZOVA Barbora")], [#age(32)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2359*], [#delta(-49)],
      [195], [#name("CHANG Li Sian Alice")], [#age(24)], [#assoc("MAS")], [#right], [#shakehand], [#defense], [*2358*], [#delta(-40)],
      [196], [#name("HUANG Hsin")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2357*], [#delta(-7)],
      [197], [#name("VIVARELLI Debora")], [#age(31)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2356*], [#delta(-22)],
      [198], [#name("LAY Jian Fang")], [#age(51)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2355*], [#delta(-13)],
      [199], [#name("YOO Yerin")], [#age(16)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2354*], [#delta(-18)],
      [200], [#name("MATOS Ines")], [#age(20)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2352*], [#delta(-6)],
    )
  )
