#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("马龙")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3068*], [#delta(0)],
      [2], [#name("许昕")], [#age(24)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*3041*], [#delta(0)],
      [3], [#name("樊振东")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2968*], [#delta(0)],
      [4], [#name("张继科")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2964*], [#delta(0)],
      [5], [#name("方博")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2857*], [#delta(0)],
      [6], [#name("王皓")], [#age(31)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2845*], [#delta(0)],
      [7], [#name("闫安")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2834*], [#delta(0)],
      [8], [#name("迪米特里 奥恰洛夫")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2827*], [#delta(0)],
      [9], [#name("水谷隼")], [#age(25)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2818*], [#delta(0)],
      [10], [#name("弗拉基米尔 萨姆索诺夫")], [#age(38)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2816*], [#delta(0)],
      [11], [#name("蒂姆 波尔")], [#age(33)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2803*], [#delta(0)],
      [12], [#name("周雨")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2780*], [#delta(0)],
      [13], [#name("马克斯 弗雷塔斯")], [#age(26)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2770*], [#delta(0)],
      [14], [#name("斯蒂芬 门格尔")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2762*], [#delta(0)],
      [15], [#name("CHO Eonrae")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2737*], [#delta(0)],
      [16], [#name("黄镇廷")], [#age(23)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2708*], [#delta(0)],
      [17], [#name("岸川圣也")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2707*], [#delta(0)],
      [18], [#name("斯特凡 菲格尔")], [#age(26)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2697*], [#delta(0)],
      [19], [#name("塩野真人")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2693*], [#delta(0)],
      [20], [#name("蒂亚戈 阿波罗尼亚")], [#age(28)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2691*], [#delta(0)],
      [21], [#name("米凯尔 梅兹")], [#age(33)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2687*], [#delta(0)],
      [22], [#name("庄智渊")], [#age(33)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2677*], [#delta(0)],
      [23], [#name("高宁")], [#age(32)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2674*], [#delta(0)],
      [24], [#name("ACHANTA Sharath")], [#age(32)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2661*], [#delta(0)],
      [25], [#name("帕特里克 鲍姆")], [#age(27)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2657*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("GERELL Par")], [#age(32)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2656*], [#delta(0)],
      [27], [#name("吉田海伟")], [#age(33)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2656*], [#delta(0)],
      [28], [#name("巴斯蒂安 斯蒂格")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2651*], [#delta(0)],
      [29], [#name("梁靖崑")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2651*], [#delta(0)],
      [30], [#name("ZHAN Jian")], [#age(32)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2641*], [#delta(0)],
      [31], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(34)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2641*], [#delta(0)],
      [32], [#name("丹尼尔 哈贝松")], [#age(28)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2638*], [#delta(0)],
      [33], [#name("卢文 菲鲁斯")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2633*], [#delta(1)],
      [34], [#name("郑荣植")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2632*], [#delta(1)],
      [35], [#name("LIU Yi")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2630*], [#delta(1)],
      [36], [#name("松平健太")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2626*], [#delta(1)],
      [37], [#name("阿德里安 克里桑")], [#age(34)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2621*], [#delta(1)],
      [38], [#name("周启豪")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2616*], [#delta(1)],
      [39], [#name("LI Ahmet")], [#age(23)], [#assoc("TUR")], [#left], [#shakehand], [#attack], [*2612*], [#delta(-6)],
      [40], [#name("汪洋")], [#age(20)], [#assoc("SVK")], [#right], [#shakehand], [#defense], [*2607*], [#delta(0)],
      [41], [#name("丁祥恩")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2607*], [#delta(0)],
      [42], [#name("朱世赫")], [#age(34)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2606*], [#delta(0)],
      [43], [#name("谭瑞午")], [#age(31)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2604*], [#delta(1)],
      [44], [#name("吉村真晴")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2604*], [#delta(1)],
      [45], [#name("森园政崇")], [#age(19)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2603*], [#delta(80)],
      [46], [#name("博扬 托基奇")], [#age(33)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2602*], [#delta(0)],
      [47], [#name("金赫峰")], [#age(29)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2601*], [#delta(0)],
      [48], [#name("金珉锡")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2601*], [#delta(0)],
      [49], [#name("帕特里克 弗朗西斯卡")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2600*], [#delta(0)],
      [50], [#name("艾曼纽 莱贝松")], [#age(26)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2599*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("亚历山大 希巴耶夫")], [#age(24)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2597*], [#delta(0)],
      [52], [#name("WANG Zengyi")], [#age(31)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2596*], [#delta(0)],
      [53], [#name("李廷佑")], [#age(30)], [#assoc("KOR")], [#left], [#penhold], [#attack], [*2595*], [#delta(0)],
      [54], [#name("西蒙 高兹")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2595*], [#delta(0)],
      [55], [#name("村松雄斗")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2595*], [#delta(12)],
      [56], [#name("罗伯特 加尔多斯")], [#age(35)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2588*], [#delta(-1)],
      [57], [#name("OYA Hidetoshi")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2584*], [#delta(0)],
      [58], [#name("吉田雅己")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2584*], [#delta(0)],
      [59], [#name("MONTEIRO Joao")], [#age(31)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2583*], [#delta(0)],
      [60], [#name("利亚姆 皮切福德")], [#age(21)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2583*], [#delta(0)],
      [61], [#name("陈建安")], [#age(23)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2580*], [#delta(-18)],
      [62], [#name("林高远")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2580*], [#delta(-1)],
      [63], [#name("雨果 卡尔德拉诺")], [#age(18)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2579*], [#delta(16)],
      [64], [#name("唐鹏")], [#age(33)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2578*], [#delta(-2)],
      [65], [#name("达米安 艾洛伊")], [#age(45)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2578*], [#delta(-2)],
      [66], [#name("KIM Junghoon")], [#age(32)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2577*], [#delta(-2)],
      [67], [#name("CHIANG Hung-Chieh")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2576*], [#delta(21)],
      [68], [#name("特里斯坦 弗洛雷")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2571*], [#delta(-3)],
      [69], [#name("DRINKHALL Paul")], [#age(24)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2570*], [#delta(145)],
      [70], [#name("尚坤")], [#age(24)], [#assoc("CHN")], [?], [?], [?], [*2570*], [#delta(-4)],
      [71], [#name("周恺")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2569*], [#delta(-3)],
      [72], [#name("德米特里 佩罗普科夫")], [#age(34)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2562*], [#delta(18)],
      [73], [#name("FLORAS Robert")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2561*], [#delta(-4)],
      [74], [#name("詹斯 伦德奎斯特")], [#age(35)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2559*], [#delta(-4)],
      [75], [#name("陈卫星")], [#age(42)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2558*], [#delta(-4)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("梁柱恩")], [#age(35)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2555*], [#delta(-4)],
      [77], [#name("里卡多 瓦尔特")], [#age(23)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2552*], [#delta(-4)],
      [78], [#name("基里尔 斯卡奇科夫")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2549*], [#delta(-4)],
      [79], [#name("TAKAKIWA Taku")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2548*], [#delta(-23)],
      [80], [#name("阿德里安 马特内")], [#age(27)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2548*], [#delta(-5)],
      [81], [#name("张一博")], [#age(29)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2547*], [#delta(-5)],
      [82], [#name("KONECNY Tomas")], [#age(29)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2547*], [#delta(-5)],
      [83], [#name("张禹珍")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2546*], [#delta(-5)],
      [84], [#name("KOSOWSKI Jakub")], [#age(32)], [#assoc("POL")], [?], [?], [?], [*2541*], [#delta(-4)],
      [85], [#name("张钰")], [#age(33)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2539*], [#delta(-4)],
      [86], [#name("卡林尼科斯 格林卡")], [#age(42)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2539*], [#delta(-4)],
      [87], [#name("LYU Xiang")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2538*], [#delta(-3)],
      [88], [#name("王臻")], [#age(29)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2536*], [#delta(-3)],
      [89], [#name("VLASOV Grigory")], [#age(30)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2534*], [#delta(-3)],
      [90], [#name("丹羽孝希")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2534*], [#delta(-3)],
      [91], [#name("奥马尔 阿萨尔")], [#age(23)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2532*], [#delta(-2)],
      [92], [#name("江天一")], [#age(26)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2528*], [#delta(-1)],
      [93], [#name("朴申赫")], [#age(21)], [#assoc("PRK")], [#left], [#penhold], [#attack], [*2527*], [#delta(-1)],
      [94], [#name("KEINATH Thomas")], [#age(37)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2527*], [#delta(-1)],
      [95], [#name("LI Hu")], [#age(26)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2522*], [#delta(0)],
      [96], [#name("李尚洙")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2521*], [#delta(0)],
      [97], [#name("PERSSON Jon")], [#age(28)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2521*], [#delta(25)],
      [98], [#name("STERNBERG Kasper")], [#age(25)], [#assoc("DEN")], [#right], [#shakehand], [#attack], [*2516*], [#delta(9)],
      [99], [#name("WEI Shihao")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2514*], [#delta(-2)],
      [100], [#name("安德烈 加奇尼")], [#age(28)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2507*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("寇磊")], [#age(27)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2506*], [#delta(-2)],
      [102], [#name("诺沙迪 阿拉米扬")], [#age(23)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2505*], [#delta(-2)],
      [103], [#name("上田仁")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2504*], [#delta(-2)],
      [104], [#name("VANG Bora")], [#age(27)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2504*], [#delta(5)],
      [105], [#name("ROBINOT Alexandre")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2502*], [#delta(48)],
      [106], [#name("CHENG Jingqi")], [#age(20)], [#assoc("CHN")], [?], [?], [?], [*2499*], [#delta(-4)],
      [107], [#name("MACHI Asuka")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2498*], [#delta(-4)],
      [108], [#name("GERALDO Joao")], [#age(19)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2497*], [#delta(-4)],
      [109], [#name("KIM Kyungmin")], [#age(25)], [#assoc("KOR")], [?], [?], [?], [*2493*], [#delta(-3)],
      [110], [#name("YANG Zi")], [#age(30)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2492*], [#delta(-27)],
      [111], [#name("TOSIC Roko")], [#age(35)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2488*], [#delta(-3)],
      [112], [#name("PISTEJ Lubomir")], [#age(30)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2484*], [#delta(-2)],
      [113], [#name("PLATONOV Pavel")], [#age(31)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2482*], [#delta(-2)],
      [114], [#name("贝内迪克特 杜达")], [#age(20)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2480*], [#delta(12)],
      [115], [#name("LORENTZ Romain")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2479*], [#delta(37)],
      [116], [#name("TSUBOI Gustavo")], [#age(29)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2478*], [#delta(-4)],
      [117], [#name("OBESLO Michal")], [#age(25)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2477*], [#delta(-3)],
      [118], [#name("让 米歇尔 赛弗")], [#age(45)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2476*], [#delta(-3)],
      [119], [#name("HIRANO Yuki")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2476*], [#delta(-3)],
      [120], [#name("DIDUKH Oleksandr")], [#age(32)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2475*], [#delta(-3)],
      [121], [#name("LIVENTSOV Alexey")], [#age(33)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2474*], [#delta(-3)],
      [122], [#name("PAPAGEORGIOU Konstantinos")], [#age(35)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2473*], [#delta(-2)],
      [123], [#name("SEO Hyundeok")], [#age(23)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2473*], [#delta(-2)],
      [124], [#name("KIM Donghyun")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2470*], [#delta(-1)],
      [125], [#name("MATSUDAIRA Kenji")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2466*], [#delta(-12)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("KIM Nam Chol")], [#age(26)], [#assoc("PRK")], [?], [?], [?], [*2465*], [#delta(-2)],
      [127], [#name("PATTANTYUS Adam")], [#age(36)], [#assoc("HUN")], [#right], [#shakehand], [#defense], [*2462*], [#delta(17)],
      [128], [#name("BOBOCICA Mihai")], [#age(28)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2461*], [#delta(84)],
      [129], [#name("GORAK Daniel")], [#age(31)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2461*], [#delta(-1)],
      [130], [#name("PETIOT Jeremy")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2460*], [#delta(-11)],
      [131], [#name("OVERSJO Mattias")], [#age(23)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2459*], [#delta(-1)],
      [132], [#name("何志文")], [#age(52)], [#assoc("ESP")], [#left], [#penhold], [#attack], [*2458*], [#delta(-38)],
      [133], [#name("LIN Ju")], [#age(35)], [#assoc("DOM")], [?], [?], [?], [*2458*], [#delta(-2)],
      [134], [#name("哈米特 德赛")], [#age(21)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2454*], [#delta(-29)],
      [135], [#name("KOSIBA Daniel")], [#age(23)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2452*], [#delta(-8)],
      [136], [#name("克里斯坦 卡尔松")], [#age(23)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2452*], [#delta(-2)],
      [137], [#name("约尔根 佩尔森")], [#age(48)], [#assoc("SWE")], [?], [?], [?], [*2448*], [#delta(-2)],
      [138], [#name("ANDERSSON Harald")], [#age(23)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2447*], [#delta(-2)],
      [139], [#name("KANG Dongsoo")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2447*], [#delta(-2)],
      [140], [#name("神巧也")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2447*], [#delta(-2)],
      [141], [#name("吴尚垠")], [#age(37)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2446*], [#delta(-2)],
      [142], [#name("奥维迪乌 伊奥内斯库")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2446*], [#delta(-2)],
      [143], [#name("HENZELL William")], [#age(32)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2444*], [#delta(3)],
      [144], [#name("MONTEIRO Thiago")], [#age(33)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2442*], [#delta(-3)],
      [145], [#name("CHEN Feng")], [#age(20)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2442*], [#delta(-3)],
      [146], [#name("JANCARIK Lubomir")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2442*], [#delta(-3)],
      [147], [#name("佐兰 普里莫拉克")], [#age(45)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2442*], [#delta(-18)],
      [148], [#name("LAKEEV Vasily")], [#age(30)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2440*], [#delta(-3)],
      [149], [#name("PAIKOV Mikhail")], [#age(25)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2439*], [#delta(-2)],
      [150], [#name("JEVTOVIC Marko")], [#age(27)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("夸德里 阿鲁纳")], [#age(26)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2435*], [#delta(22)],
      [152], [#name("FERTIKOWSKI Pawel")], [#age(24)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2435*], [#delta(-2)],
      [153], [#name("SALIFOU Abdel-Kader")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-21)],
      [154], [#name("ROBINOT Quentin")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2426*], [#delta(0)],
      [155], [#name("LEGOUT Christophe")], [#age(41)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2424*], [#delta(0)],
      [156], [#name("HIELSCHER Lars")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2423*], [#delta(0)],
      [157], [#name("马蒂亚斯 法尔克")], [#age(23)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2422*], [#delta(26)],
      [158], [#name("KOLAREK Tomislav")], [#age(26)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2421*], [#delta(-1)],
      [159], [#name("雅克布 迪亚斯")], [#age(19)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2419*], [#delta(-1)],
      [160], [#name("LIU Song")], [#age(42)], [#assoc("ARG")], [?], [?], [?], [*2417*], [#delta(-1)],
      [161], [#name("CIOTI Constantin")], [#age(31)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2417*], [#delta(-1)],
      [162], [#name("乔纳森 格罗斯")], [#age(22)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2416*], [#delta(-1)],
      [163], [#name("KATKOV Ivan")], [#age(30)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2415*], [#delta(-1)],
      [164], [#name("亚历山大 卡拉卡谢维奇")], [#age(39)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2412*], [#delta(-13)],
      [165], [#name("BAI He")], [#age(27)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2409*], [#delta(-2)],
      [166], [#name("BAGGALEY Andrew")], [#age(31)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2408*], [#delta(-2)],
      [167], [#name("阿列克谢 斯米尔诺夫")], [#age(37)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2408*], [#delta(-34)],
      [168], [#name("ANGLES Enzo")], [#age(19)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2405*], [#delta(-3)],
      [169], [#name("WU Zhikang")], [#age(20)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2405*], [#delta(-3)],
      [170], [#name("BRODD Viktor")], [#age(24)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2401*], [#delta(-3)],
      [171], [#name("AKERSTROM Fabian")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2399*], [#delta(-3)],
      [172], [#name("BURGIS Matiss")], [#age(25)], [#assoc("LAT")], [#right], [#shakehand], [#attack], [*2398*], [#delta(-3)],
      [173], [#name("KASAHARA Hiromitsu")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2398*], [#delta(-3)],
      [174], [#name("FUJIMOTO Kaito")], [#age(23)], [#assoc("JPN")], [?], [?], [?], [*2396*], [#delta(-3)],
      [175], [#name("MACHADO Carlos")], [#age(34)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2395*], [#delta(-26)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("YU Jiaqing")], [#age(22)], [#assoc("SGP")], [?], [?], [?], [*2395*], [#delta(-4)],
      [177], [#name("SEREDA Peter")], [#age(30)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2393*], [#delta(-3)],
      [178], [#name("BUROV Viacheslav")], [#age(29)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2393*], [#delta(72)],
      [179], [#name("NORDBERG Hampus")], [#age(27)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2392*], [#delta(5)],
      [180], [#name("于子洋")], [#age(16)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2391*], [#delta(-4)],
      [181], [#name("LASAN Sas")], [#age(43)], [#assoc("SLO")], [#right], [#shakehand], [#defense], [*2391*], [#delta(-4)],
      [182], [#name("KARUBE Ryusuke")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2390*], [#delta(-4)],
      [183], [#name("AKKUZU Can")], [#age(17)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2390*], [#delta(26)],
      [184], [#name("TREGLER Tomas")], [#age(24)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2389*], [#delta(100)],
      [185], [#name("CHTCHETININE Evgueni")], [#age(44)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2389*], [#delta(-5)],
      [186], [#name("KIM Minhyeok")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2387*], [#delta(-1)],
      [187], [#name("MIUCHI Kentaro")], [#age(25)], [#assoc("JPN")], [?], [?], [?], [*2387*], [#delta(-1)],
      [188], [#name("安东 卡尔伯格")], [#age(17)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2386*], [#delta(69)],
      [189], [#name("NEKHVEDOVICH Vitaly")], [#age(39)], [#assoc("BLR")], [?], [?], [?], [*2386*], [#delta(-2)],
      [190], [#name("MATSUMOTO Cazuo")], [#age(29)], [#assoc("BRA")], [#left], [#penhold], [#attack], [*2386*], [#delta(12)],
      [191], [#name("彼得 科贝尔")], [#age(43)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2384*], [#delta(-3)],
      [192], [#name("PARK Chan-Hyeok")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2384*], [#delta(-3)],
      [193], [#name("REITSPIES David")], [#age(18)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2383*], [#delta(37)],
      [194], [#name("尼马 阿拉米安")], [#age(22)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2383*], [#delta(-4)],
      [195], [#name("VRABLIK Jiri")], [#age(31)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2383*], [#delta(-4)],
      [196], [#name("SZOCS Hunor")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2382*], [#delta(-4)],
      [197], [#name("LAGOGIANNIS Konstantinos")], [#age(33)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2380*], [#delta(-4)],
      [198], [#name("MADRID Marcos")], [#age(28)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2379*], [#delta(12)],
      [199], [#name("HACHARD Antoine")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2379*], [#delta(83)],
      [200], [#name("STOYANOV Niagol")], [#age(27)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2378*], [#delta(65)],
    )
  )
