#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("马龙")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3042*], [#delta(0)],
      [2], [#name("许昕")], [#age(24)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*3033*], [#delta(2)],
      [3], [#name("张继科")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2964*], [#delta(-1)],
      [4], [#name("樊振东")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2950*], [#delta(-1)],
      [5], [#name("迪米特里 奥恰洛夫")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2880*], [#delta(0)],
      [6], [#name("弗拉基米尔 萨姆索诺夫")], [#age(38)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2860*], [#delta(1)],
      [7], [#name("方博")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2857*], [#delta(1)],
      [8], [#name("闫安")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2857*], [#delta(1)],
      [9], [#name("王皓")], [#age(31)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2856*], [#delta(-3)],
      [10], [#name("松平健太")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2788*], [#delta(0)],
      [11], [#name("金珉鉐")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2778*], [#delta(6)],
      [12], [#name("蒂姆 波尔")], [#age(33)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2767*], [#delta(-1)],
      [13], [#name("周雨")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2766*], [#delta(-1)],
      [14], [#name("水谷隼")], [#age(25)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2759*], [#delta(-1)],
      [15], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(34)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2725*], [#delta(-1)],
      [16], [#name("巴斯蒂安 斯特格")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2706*], [#delta(-1)],
      [17], [#name("米凯尔 梅兹")], [#age(33)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2702*], [#delta(-1)],
      [18], [#name("丹尼尔 哈贝松")], [#age(28)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2683*], [#delta(27)],
      [19], [#name("唐鹏")], [#age(33)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2681*], [#delta(2)],
      [20], [#name("庄智渊")], [#age(33)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2679*], [#delta(-1)],
      [21], [#name("塩野真人")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2678*], [#delta(-3)],
      [22], [#name("亚历山大 希巴耶夫")], [#age(24)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2676*], [#delta(0)],
      [23], [#name("马克斯 弗雷塔斯")], [#age(26)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2674*], [#delta(0)],
      [24], [#name("ZHAN Jian")], [#age(32)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2670*], [#delta(0)],
      [25], [#name("斯特凡 菲格尔")], [#age(26)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2663*], [#delta(-5)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("利亚姆 皮切福德")], [#age(21)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2662*], [#delta(-1)],
      [27], [#name("朱世赫")], [#age(34)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2660*], [#delta(-1)],
      [28], [#name("吉田海伟")], [#age(33)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2656*], [#delta(-1)],
      [29], [#name("西蒙 高兹")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2655*], [#delta(32)],
      [30], [#name("梁靖崑")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2653*], [#delta(-1)],
      [31], [#name("郑荣植")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2647*], [#delta(-1)],
      [32], [#name("汪洋")], [#age(20)], [#assoc("SVK")], [#right], [#shakehand], [#defense], [*2647*], [#delta(14)],
      [33], [#name("谭瑞午")], [#age(31)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2647*], [#delta(-2)],
      [34], [#name("梁柱恩")], [#age(35)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2633*], [#delta(-2)],
      [35], [#name("丹羽孝希")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2633*], [#delta(-7)],
      [36], [#name("林高远")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2632*], [#delta(-3)],
      [37], [#name("金赫峰")], [#age(29)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2632*], [#delta(-3)],
      [38], [#name("LIU Yi")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2630*], [#delta(-3)],
      [39], [#name("斯蒂芬 门格尔")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2628*], [#delta(53)],
      [40], [#name("卢文 菲鲁斯")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2615*], [#delta(-3)],
      [41], [#name("岸川圣也")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2612*], [#delta(-3)],
      [42], [#name("安德烈 加奇尼")], [#age(28)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2610*], [#delta(-3)],
      [43], [#name("金正勋")], [#age(32)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2610*], [#delta(-3)],
      [44], [#name("高木和卓")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2610*], [#delta(-8)],
      [45], [#name("蒂亚戈 阿波罗尼亚")], [#age(28)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2608*], [#delta(-4)],
      [46], [#name("博扬 托基奇")], [#age(33)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2605*], [#delta(-4)],
      [47], [#name("杨子")], [#age(30)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2601*], [#delta(-4)],
      [48], [#name("李尚洙")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2598*], [#delta(-4)],
      [49], [#name("李廷佑")], [#age(30)], [#assoc("KOR")], [#left], [#penhold], [#attack], [*2595*], [#delta(-2)],
      [50], [#name("王增羿")], [#age(31)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2595*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("赵彦来")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2594*], [#delta(-1)],
      [52], [#name("李虎")], [#age(26)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2590*], [#delta(1)],
      [53], [#name("帕特里克 鲍姆")], [#age(27)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2590*], [#delta(1)],
      [54], [#name("阿德里安 克里桑")], [#age(34)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2589*], [#delta(1)],
      [55], [#name("张一博")], [#age(29)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2588*], [#delta(-3)],
      [56], [#name("大矢英俊")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2584*], [#delta(0)],
      [57], [#name("沙拉特 阿昌塔")], [#age(32)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2582*], [#delta(0)],
      [58], [#name("吉田雅己")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2581*], [#delta(0)],
      [59], [#name("基里尔 斯卡奇科夫")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2580*], [#delta(0)],
      [60], [#name("张禹珍")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2577*], [#delta(0)],
      [61], [#name("高宁")], [#age(32)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2574*], [#delta(-12)],
      [62], [#name("帕特里克 弗朗西斯卡")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2570*], [#delta(27)],
      [63], [#name("尚坤")], [#age(24)], [#assoc("CHN")], [?], [?], [?], [*2570*], [#delta(-1)],
      [64], [#name("艾曼纽 莱贝松")], [#age(26)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2568*], [#delta(20)],
      [65], [#name("村松雄斗")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2567*], [#delta(-2)],
      [66], [#name("陈建安")], [#age(23)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2563*], [#delta(-2)],
      [67], [#name("何志文")], [#age(52)], [#assoc("ESP")], [#left], [#penhold], [#attack], [*2560*], [#delta(-2)],
      [68], [#name("阿列克谢 斯米尔诺夫")], [#age(37)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2558*], [#delta(-1)],
      [69], [#name("江宏杰")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2558*], [#delta(0)],
      [70], [#name("帕尔 格雷尔")], [#age(32)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2550*], [#delta(2)],
      [71], [#name("黄镇廷")], [#age(23)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2548*], [#delta(3)],
      [72], [#name("松平贤二")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2543*], [#delta(3)],
      [73], [#name("雅库布 科索夫斯基")], [#age(32)], [#assoc("POL")], [?], [?], [?], [*2541*], [#delta(6)],
      [74], [#name("李良夫")], [#age(23)], [#assoc("TUR")], [#left], [#shakehand], [#attack], [*2539*], [#delta(2)],
      [75], [#name("阿卜杜勒-卡德尔 萨利富")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2539*], [#delta(-9)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("卡林尼科斯 格林卡")], [#age(42)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2539*], [#delta(2)],
      [77], [#name("WU Zhikang")], [#age(20)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2538*], [#delta(33)],
      [78], [#name("王臻")], [#age(29)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2536*], [#delta(-1)],
      [79], [#name("德米特里 普罗科普科夫")], [#age(34)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2530*], [#delta(-28)],
      [80], [#name("达米安 埃洛伊")], [#age(45)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2528*], [#delta(0)],
      [81], [#name("罗伯特 弗洛拉斯")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2528*], [#delta(86)],
      [82], [#name("朴申赫")], [#age(21)], [#assoc("PRK")], [#left], [#penhold], [#attack], [*2527*], [#delta(-1)],
      [83], [#name("托马斯 凯纳特")], [#age(37)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2527*], [#delta(-1)],
      [84], [#name("丁祥恩")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2526*], [#delta(-1)],
      [85], [#name("帕维尔 普拉托诺夫")], [#age(31)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2526*], [#delta(0)],
      [86], [#name("奥马尔 阿萨尔")], [#age(23)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2522*], [#delta(0)],
      [87], [#name("托马斯 科涅茨尼")], [#age(29)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2521*], [#delta(-16)],
      [88], [#name("KATKOV Ivan")], [#age(30)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2518*], [#delta(6)],
      [89], [#name("格里戈里 弗拉索夫")], [#age(30)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2512*], [#delta(25)],
      [90], [#name("特里斯坦 弗洛雷")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2512*], [#delta(88)],
      [91], [#name("森园政崇")], [#age(19)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2510*], [#delta(-4)],
      [92], [#name("LORENTZ Romain")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2507*], [#delta(55)],
      [93], [#name("诺沙迪 阿拉米扬")], [#age(23)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2505*], [#delta(14)],
      [94], [#name("上田仁")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2504*], [#delta(-4)],
      [95], [#name("CHENG Jingqi")], [#age(20)], [#assoc("CHN")], [?], [?], [?], [*2499*], [#delta(0)],
      [96], [#name("町飞鸟")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2498*], [#delta(0)],
      [97], [#name("古斯塔沃 坪井")], [#age(29)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2495*], [#delta(0)],
      [98], [#name("卢博米尔 扬察里克")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2493*], [#delta(19)],
      [99], [#name("KIM Kyungmin")], [#age(25)], [#assoc("KOR")], [?], [?], [?], [*2493*], [#delta(-1)],
      [100], [#name("若昂 蒙泰罗")], [#age(31)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2493*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("徐贤德")], [#age(23)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2491*], [#delta(-1)],
      [102], [#name("VANG Bora")], [#age(27)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2491*], [#delta(-1)],
      [103], [#name("罗科 托西奇")], [#age(35)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2488*], [#delta(0)],
      [104], [#name("吴尚垠")], [#age(37)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2486*], [#delta(0)],
      [105], [#name("陈丰")], [#age(20)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2485*], [#delta(24)],
      [106], [#name("罗伯特 加尔多斯")], [#age(35)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2484*], [#delta(0)],
      [107], [#name("卢博米尔 皮斯特耶")], [#age(30)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2484*], [#delta(17)],
      [108], [#name("詹斯 伦德奎斯特")], [#age(35)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2482*], [#delta(0)],
      [109], [#name("阿德里安 马特内")], [#age(27)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2481*], [#delta(0)],
      [110], [#name("神巧也")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2479*], [#delta(1)],
      [111], [#name("AKERSTROM Fabian")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2479*], [#delta(-20)],
      [112], [#name("米哈尔 奥贝斯洛")], [#age(25)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2477*], [#delta(115)],
      [113], [#name("平野友树")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2476*], [#delta(0)],
      [114], [#name("康斯坦丁诺斯 帕帕乔治乌")], [#age(35)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2473*], [#delta(1)],
      [115], [#name("陈卫星")], [#age(42)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2467*], [#delta(1)],
      [116], [#name("吉村真晴")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2467*], [#delta(2)],
      [117], [#name("克里斯坦 卡尔松")], [#age(23)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2466*], [#delta(2)],
      [118], [#name("斯特凡 乌瓦切")], [#age(21)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2465*], [#delta(85)],
      [119], [#name("KIM Nam Chol")], [#age(26)], [#assoc("PRK")], [?], [?], [?], [*2465*], [#delta(1)],
      [120], [#name("托米斯拉夫 科拉雷克")], [#age(26)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2464*], [#delta(-18)],
      [121], [#name("乔恩 佩尔森")], [#age(28)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2461*], [#delta(-28)],
      [122], [#name("佐兰 普里莫拉克")], [#age(45)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2460*], [#delta(0)],
      [123], [#name("ANDERSSON Harald")], [#age(23)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2459*], [#delta(39)],
      [124], [#name("林聚")], [#age(35)], [#assoc("DOM")], [?], [?], [?], [*2458*], [#delta(-1)],
      [125], [#name("阿列克谢 利文佐夫")], [#age(33)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2456*], [#delta(-37)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("康斯坦丁 乔蒂")], [#age(31)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2455*], [#delta(-1)],
      [127], [#name("拉尔斯 希尔舍")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2455*], [#delta(-1)],
      [128], [#name("寇磊")], [#age(27)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2455*], [#delta(-1)],
      [129], [#name("亚历山大 迪杜赫")], [#age(32)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2450*], [#delta(118)],
      [130], [#name("江天一")], [#age(26)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2449*], [#delta(1)],
      [131], [#name("瓦西里 拉凯耶夫")], [#age(30)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2449*], [#delta(-3)],
      [132], [#name("约尔根 佩尔森")], [#age(48)], [#assoc("SWE")], [?], [?], [?], [*2448*], [#delta(0)],
      [133], [#name("达尼埃尔 科希鲍")], [#age(23)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2447*], [#delta(115)],
      [134], [#name("亚诺什 雅各布")], [#age(28)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2445*], [#delta(45)],
      [135], [#name("金东贤")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2442*], [#delta(-2)],
      [136], [#name("STERNBERG Kasper")], [#age(25)], [#assoc("DEN")], [#right], [#shakehand], [#attack], [*2440*], [#delta(0)],
      [137], [#name("威廉 亨泽尔")], [#age(32)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2440*], [#delta(1)],
      [138], [#name("克里斯托夫 勒古")], [#age(41)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2439*], [#delta(1)],
      [139], [#name("马尔科 耶夫托维奇")], [#age(27)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-34)],
      [140], [#name("卡洛斯 马查多")], [#age(34)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2437*], [#delta(0)],
      [141], [#name("丹尼尔 古拉克")], [#age(31)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2436*], [#delta(-29)],
      [142], [#name("周恺")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2436*], [#delta(-1)],
      [143], [#name("亚历山大 卡拉卡谢维奇")], [#age(39)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2435*], [#delta(-1)],
      [144], [#name("张钰")], [#age(33)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2434*], [#delta(-1)],
      [145], [#name("BROSSIER Benjamin")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-1)],
      [146], [#name("苏姆亚吉特 格霍什")], [#age(21)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2429*], [#delta(-11)],
      [147], [#name("里卡多 瓦尔特")], [#age(23)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2427*], [#delta(-2)],
      [148], [#name("吴志祺")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2427*], [#delta(-2)],
      [149], [#name("亚历山大 罗比诺")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2426*], [#delta(38)],
      [150], [#name("康坦 罗比诺特")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2426*], [#delta(-80)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("保罗 德林克霍尔")], [#age(24)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2423*], [#delta(-17)],
      [152], [#name("刘松")], [#age(42)], [#assoc("ARG")], [?], [?], [?], [*2420*], [#delta(0)],
      [153], [#name("雅库布 迪亚斯")], [#age(19)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2419*], [#delta(2)],
      [154], [#name("米哈伊尔 派科夫")], [#age(25)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2417*], [#delta(-5)],
      [155], [#name("穆罕默德 埃尔贝亚利")], [#age(26)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2416*], [#delta(2)],
      [156], [#name("恩佐 昂格勒")], [#age(19)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2416*], [#delta(44)],
      [157], [#name("弗拉内 科伊奇")], [#age(22)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2414*], [#delta(1)],
      [158], [#name("HUNG Tzu-Hsiang")], [#age(20)], [#assoc("TPE")], [#right], [#penhold], [#attack], [*2413*], [#delta(-85)],
      [159], [#name("KONG Lingxuan")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2413*], [#delta(0)],
      [160], [#name("OVERSJO Mattias")], [#age(23)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2413*], [#delta(-10)],
      [161], [#name("彼得 科贝尔")], [#age(43)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2411*], [#delta(-1)],
      [162], [#name("米哈伊 博博奇卡")], [#age(28)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2411*], [#delta(-32)],
      [163], [#name("BAI He")], [#age(27)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2409*], [#delta(-2)],
      [164], [#name("胡诺尔 斯佐科斯")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2409*], [#delta(-10)],
      [165], [#name("安德鲁 巴格利")], [#age(31)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2408*], [#delta(16)],
      [166], [#name("周启豪")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2405*], [#delta(-3)],
      [167], [#name("蒂亚戈 蒙泰罗")], [#age(33)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2405*], [#delta(-3)],
      [168], [#name("奥维迪乌 伊奥内斯库")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2405*], [#delta(7)],
      [169], [#name("伊日 维拉波里克")], [#age(31)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2404*], [#delta(-4)],
      [170], [#name("YU Jiaqing")], [#age(22)], [#assoc("SGP")], [?], [?], [?], [*2404*], [#delta(-4)],
      [171], [#name("亚当 帕塔纽什")], [#age(36)], [#assoc("HUN")], [#right], [#shakehand], [#defense], [*2404*], [#delta(-20)],
      [172], [#name("松本和雄")], [#age(29)], [#assoc("BRA")], [#left], [#penhold], [#attack], [*2403*], [#delta(-35)],
      [173], [#name("佐尔特 佩托")], [#age(27)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2402*], [#delta(19)],
      [174], [#name("BRODD Viktor")], [#age(24)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2400*], [#delta(-6)],
      [175], [#name("XIN Zhaoxu")], [#age(19)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2399*], [#delta(-6)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("马蒂斯 布尔吉斯")], [#age(25)], [#assoc("LAT")], [#right], [#shakehand], [#attack], [*2398*], [#delta(-6)],
      [177], [#name("笠原弘光")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2398*], [#delta(-6)],
      [178], [#name("夸德里 阿鲁纳")], [#age(26)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2397*], [#delta(-6)],
      [179], [#name("KOVAC Borna")], [#age(23)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2397*], [#delta(93)],
      [180], [#name("FUJIMOTO Kaito")], [#age(23)], [#assoc("JPN")], [?], [?], [?], [*2396*], [#delta(-6)],
      [181], [#name("彼得 塞雷达")], [#age(30)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2393*], [#delta(-5)],
      [182], [#name("佐尔坦 费杰科内斯")], [#age(36)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2393*], [#delta(-5)],
      [183], [#name("哈米特 德赛")], [#age(21)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2391*], [#delta(84)],
      [184], [#name("萨什 拉桑")], [#age(43)], [#assoc("SLO")], [#right], [#shakehand], [#defense], [*2391*], [#delta(-4)],
      [185], [#name("KARUBE Ryusuke")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2390*], [#delta(-3)],
      [186], [#name("叶夫根尼 齐特切蒂宁")], [#age(44)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2389*], [#delta(-3)],
      [187], [#name("LE BRETON Thomas")], [#age(22)], [#assoc("FRA")], [?], [?], [?], [*2388*], [#delta(-3)],
      [188], [#name("汉普斯 努德贝里")], [#age(27)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2388*], [#delta(-3)],
      [189], [#name("三内贤太郎")], [#age(25)], [#assoc("JPN")], [?], [?], [?], [*2387*], [#delta(-3)],
      [190], [#name("金民赫")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2387*], [#delta(17)],
      [191], [#name("NEKHVEDOVICH Vitaly")], [#age(39)], [#assoc("BLR")], [?], [?], [?], [*2386*], [#delta(-3)],
      [192], [#name("马克 杜兰")], [#age(28)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2386*], [#delta(-3)],
      [193], [#name("LAGOGIANNIS Konstantinos")], [#age(33)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2380*], [#delta(-2)],
      [194], [#name("贝内迪克特 杜达")], [#age(20)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2379*], [#delta(-41)],
      [195], [#name("罗宾 德沃斯")], [#age(20)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2375*], [#delta(75)],
      [196], [#name("尼马 阿拉米安")], [#age(22)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2374*], [#delta(2)],
      [197], [#name("KANG Donghoon")], [#age(27)], [#assoc("KOR")], [?], [?], [?], [*2373*], [#delta(-3)],
      [198], [#name("雅罗斯拉夫 扎穆登科")], [#age(26)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2371*], [#delta(-1)],
      [199], [#name("MUTTI Leonardo")], [#age(19)], [#assoc("ITA")], [#left], [#shakehand], [#attack], [*2369*], [#delta(-6)],
      [200], [#name("雨果 卡尔德拉诺")], [#age(18)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2368*], [#delta(-10)],
    )
  )
