#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("马龙")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3087*], [#delta(0)],
      [2], [#name("许昕")], [#age(24)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*3077*], [#delta(0)],
      [3], [#name("张继科")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3002*], [#delta(2)],
      [4], [#name("蒂姆 波尔")], [#age(33)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2948*], [#delta(0)],
      [5], [#name("樊振东")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2933*], [#delta(-2)],
      [6], [#name("方博")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2862*], [#delta(1)],
      [7], [#name("朱世赫")], [#age(34)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2853*], [#delta(7)],
      [8], [#name("水谷隼")], [#age(25)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2837*], [#delta(-2)],
      [9], [#name("王皓")], [#age(31)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2833*], [#delta(0)],
      [10], [#name("闫安")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2815*], [#delta(0)],
      [11], [#name("周雨")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2780*], [#delta(1)],
      [12], [#name("于子洋")], [#age(16)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2771*], [#delta(1)],
      [13], [#name("帕特里克 鲍姆")], [#age(27)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2762*], [#delta(4)],
      [14], [#name("安德烈 加奇尼")], [#age(28)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2750*], [#delta(4)],
      [15], [#name("弗拉基米尔 萨姆索诺夫")], [#age(38)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2747*], [#delta(4)],
      [16], [#name("蒂亚戈 阿波罗尼亚")], [#age(28)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2744*], [#delta(42)],
      [17], [#name("迪米特里 奥恰洛夫")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2730*], [#delta(-2)],
      [18], [#name("马克斯 弗雷塔斯")], [#age(26)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2726*], [#delta(-10)],
      [19], [#name("罗伯特 加尔多斯")], [#age(35)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2725*], [#delta(1)],
      [20], [#name("夸德里 阿鲁纳")], [#age(26)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2722*], [#delta(47)],
      [21], [#name("里卡多 瓦尔特")], [#age(23)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2701*], [#delta(1)],
      [22], [#name("卢文 菲鲁斯")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2698*], [#delta(1)],
      [23], [#name("李廷佑")], [#age(30)], [#assoc("KOR")], [#left], [#penhold], [#attack], [*2696*], [#delta(20)],
      [24], [#name("高宁")], [#age(32)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2685*], [#delta(-8)],
      [25], [#name("庄智渊")], [#age(33)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2680*], [#delta(-14)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("斯蒂芬 门格尔")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2677*], [#delta(-1)],
      [27], [#name("村松雄斗")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2666*], [#delta(8)],
      [28], [#name("森园政崇")], [#age(19)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2660*], [#delta(-2)],
      [29], [#name("丁祥恩")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2657*], [#delta(36)],
      [30], [#name("梁靖崑")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2651*], [#delta(-2)],
      [31], [#name("周恺")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2649*], [#delta(-2)],
      [32], [#name("利亚姆 皮切福德")], [#age(21)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2647*], [#delta(-2)],
      [33], [#name("塩野真人")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2641*], [#delta(-2)],
      [34], [#name("MONTEIRO Joao")], [#age(31)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2631*], [#delta(-2)],
      [35], [#name("汪洋")], [#age(20)], [#assoc("SVK")], [#right], [#shakehand], [#defense], [*2631*], [#delta(-2)],
      [36], [#name("巴斯蒂安 斯蒂格")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2630*], [#delta(-2)],
      [37], [#name("LIU Yi")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2630*], [#delta(-1)],
      [38], [#name("詹斯 伦德奎斯特")], [#age(35)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2630*], [#delta(-1)],
      [39], [#name("阿德里安 马特内")], [#age(27)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2629*], [#delta(60)],
      [40], [#name("唐鹏")], [#age(33)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2627*], [#delta(-16)],
      [41], [#name("吉田海伟")], [#age(33)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2626*], [#delta(-3)],
      [42], [#name("克里斯坦 卡尔松")], [#age(23)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2624*], [#delta(-3)],
      [43], [#name("GERELL Par")], [#age(32)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2624*], [#delta(-3)],
      [44], [#name("CHEN Feng")], [#age(20)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2623*], [#delta(66)],
      [45], [#name("上田仁")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2621*], [#delta(-3)],
      [46], [#name("朴申赫")], [#age(21)], [#assoc("PRK")], [#left], [#penhold], [#attack], [*2618*], [#delta(47)],
      [47], [#name("吉村真晴")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2617*], [#delta(-3)],
      [48], [#name("LYU Xiang")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2611*], [#delta(-3)],
      [49], [#name("斯特凡 菲格尔")], [#age(26)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2607*], [#delta(-3)],
      [50], [#name("MACHI Asuka")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2606*], [#delta(-3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("张禹珍")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2605*], [#delta(-3)],
      [52], [#name("丹羽孝希")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2604*], [#delta(-31)],
      [53], [#name("何志文")], [#age(52)], [#assoc("ESP")], [#left], [#penhold], [#attack], [*2604*], [#delta(-3)],
      [54], [#name("LI Hu")], [#age(26)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2599*], [#delta(62)],
      [55], [#name("VLASOV Grigory")], [#age(30)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2591*], [#delta(-4)],
      [56], [#name("CHO Eonrae")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2590*], [#delta(-3)],
      [57], [#name("帕特里克 弗朗西斯卡")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2590*], [#delta(-3)],
      [58], [#name("艾曼纽 莱贝松")], [#age(26)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2589*], [#delta(-3)],
      [59], [#name("STOYANOV Niagol")], [#age(27)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2586*], [#delta(-3)],
      [60], [#name("KOSIBA Daniel")], [#age(23)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2586*], [#delta(-3)],
      [61], [#name("丹尼尔 哈贝松")], [#age(28)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2584*], [#delta(-2)],
      [62], [#name("PERSSON Jon")], [#age(28)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2581*], [#delta(-2)],
      [63], [#name("林高远")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2580*], [#delta(-1)],
      [64], [#name("OYA Hidetoshi")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2578*], [#delta(-1)],
      [65], [#name("达米安 艾洛伊")], [#age(45)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2578*], [#delta(-1)],
      [66], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(34)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2578*], [#delta(-39)],
      [67], [#name("黄镇廷")], [#age(23)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2577*], [#delta(10)],
      [68], [#name("博扬 托基奇")], [#age(33)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2574*], [#delta(-2)],
      [69], [#name("KANG Dongsoo")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2571*], [#delta(-1)],
      [70], [#name("尚坤")], [#age(24)], [#assoc("CHN")], [?], [?], [?], [*2570*], [#delta(-1)],
      [71], [#name("CHIANG Hung-Chieh")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2569*], [#delta(-22)],
      [72], [#name("基里尔 斯卡奇科夫")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2568*], [#delta(-2)],
      [73], [#name("塞德里克 纽廷克")], [#age(21)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2567*], [#delta(-2)],
      [74], [#name("陈卫星")], [#age(42)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2567*], [#delta(-2)],
      [75], [#name("亚历山大 卡拉卡谢维奇")], [#age(39)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2565*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("吉田雅己")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2564*], [#delta(-2)],
      [77], [#name("HUANG Sheng-Sheng")], [#age(27)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2561*], [#delta(-36)],
      [78], [#name("陈建安")], [#age(23)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2560*], [#delta(123)],
      [79], [#name("阿列克谢 斯米尔诺夫")], [#age(37)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2559*], [#delta(-3)],
      [80], [#name("大岛祐哉")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2558*], [#delta(-2)],
      [81], [#name("奥马尔 阿萨尔")], [#age(23)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2550*], [#delta(-2)],
      [82], [#name("KIM Minhyeok")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2549*], [#delta(-2)],
      [83], [#name("WANG Zengyi")], [#age(31)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2546*], [#delta(0)],
      [84], [#name("阿德里安 克里桑")], [#age(34)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2545*], [#delta(-32)],
      [85], [#name("郑荣植")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2544*], [#delta(-1)],
      [86], [#name("GORAK Daniel")], [#age(31)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2535*], [#delta(0)],
      [87], [#name("松平健太")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2535*], [#delta(61)],
      [88], [#name("李尚洙")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2534*], [#delta(-1)],
      [89], [#name("OUAICHE Stephane")], [#age(21)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2531*], [#delta(0)],
      [90], [#name("王臻")], [#age(29)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2530*], [#delta(0)],
      [91], [#name("张一博")], [#age(29)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2529*], [#delta(0)],
      [92], [#name("KOSOWSKI Jakub")], [#age(32)], [#assoc("POL")], [?], [?], [?], [*2528*], [#delta(0)],
      [93], [#name("特里斯坦 弗洛雷")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2524*], [#delta(1)],
      [94], [#name("DRINKHALL Paul")], [#age(24)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2520*], [#delta(1)],
      [95], [#name("WU Zhikang")], [#age(20)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2520*], [#delta(1)],
      [96], [#name("卡林尼科斯 格林卡")], [#age(42)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2519*], [#delta(1)],
      [97], [#name("WEI Shihao")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2515*], [#delta(3)],
      [98], [#name("HO Kwan Kit")], [#age(17)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2514*], [#delta(3)],
      [99], [#name("ARVIDSSON Simon")], [#age(24)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2512*], [#delta(3)],
      [100], [#name("寇磊")], [#age(27)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2511*], [#delta(3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("LAKEEV Vasily")], [#age(30)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2510*], [#delta(3)],
      [102], [#name("BURGIS Matiss")], [#age(25)], [#assoc("LAT")], [#right], [#shakehand], [#attack], [*2510*], [#delta(3)],
      [103], [#name("西蒙 高兹")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2509*], [#delta(3)],
      [104], [#name("诺沙迪 阿拉米扬")], [#age(23)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2508*], [#delta(-6)],
      [105], [#name("金赫峰")], [#age(29)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2507*], [#delta(-17)],
      [106], [#name("LI Ahmet")], [#age(23)], [#assoc("TUR")], [#left], [#shakehand], [#attack], [*2506*], [#delta(1)],
      [107], [#name("REED Daniel")], [#age(25)], [#assoc("ENG")], [?], [?], [?], [*2506*], [#delta(1)],
      [108], [#name("赵胜敏")], [#age(16)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2506*], [#delta(1)],
      [109], [#name("ACHANTA Sharath")], [#age(32)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2501*], [#delta(-27)],
      [110], [#name("CHENG Jingqi")], [#age(20)], [#assoc("CHN")], [?], [?], [?], [*2499*], [#delta(1)],
      [111], [#name("TAKAKIWA Taku")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2499*], [#delta(1)],
      [112], [#name("ZHU Cheng")], [#age(17)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2498*], [#delta(1)],
      [113], [#name("PAIKOV Mikhail")], [#age(25)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2497*], [#delta(1)],
      [114], [#name("YANG Tzu-Yi")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2497*], [#delta(1)],
      [115], [#name("TAZOE Kenta")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2497*], [#delta(2)],
      [116], [#name("雨果 卡尔德拉诺")], [#age(18)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2496*], [#delta(2)],
      [117], [#name("雅克布 迪亚斯")], [#age(19)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2496*], [#delta(2)],
      [118], [#name("TSUBOI Yuma")], [#age(17)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2494*], [#delta(2)],
      [119], [#name("乔纳森 格罗斯")], [#age(22)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2493*], [#delta(2)],
      [120], [#name("JAKAB Janos")], [#age(28)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2492*], [#delta(3)],
      [121], [#name("LORENTZ Romain")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2490*], [#delta(3)],
      [122], [#name("廖振珽")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2489*], [#delta(3)],
      [123], [#name("TOSIC Roko")], [#age(35)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2488*], [#delta(3)],
      [124], [#name("江天一")], [#age(26)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2487*], [#delta(-43)],
      [125], [#name("谭瑞午")], [#age(31)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2484*], [#delta(2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("STERNBERG Kasper")], [#age(25)], [#assoc("DEN")], [#right], [#shakehand], [#attack], [*2484*], [#delta(3)],
      [127], [#name("奥维迪乌 伊奥内斯库")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2482*], [#delta(3)],
      [128], [#name("TAO Wenzhang")], [#age(20)], [#assoc("USA")], [#right], [#penhold], [#attack], [*2481*], [#delta(3)],
      [129], [#name("贝内德克 奥拉")], [#age(23)], [#assoc("FIN")], [#right], [#shakehand], [#attack], [*2481*], [#delta(3)],
      [130], [#name("贝内迪克特 杜达")], [#age(20)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2481*], [#delta(3)],
      [131], [#name("LIVENTSOV Alexey")], [#age(33)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2480*], [#delta(3)],
      [132], [#name("BOBOCICA Mihai")], [#age(28)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2479*], [#delta(3)],
      [133], [#name("刘丁硕")], [#age(16)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2479*], [#delta(3)],
      [134], [#name("PLATONOV Pavel")], [#age(31)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2478*], [#delta(3)],
      [135], [#name("KIM Donghyun")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2477*], [#delta(15)],
      [136], [#name("CHTCHETININE Evgueni")], [#age(44)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2476*], [#delta(2)],
      [137], [#name("HACHARD Antoine")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2471*], [#delta(3)],
      [138], [#name("MACHADO Carlos")], [#age(34)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2471*], [#delta(3)],
      [139], [#name("TSUBOI Gustavo")], [#age(29)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2470*], [#delta(3)],
      [140], [#name("金珉锡")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2468*], [#delta(3)],
      [141], [#name("DURANSPAHIC Admir")], [#age(27)], [#assoc("BIH")], [#right], [#shakehand], [#attack], [*2467*], [#delta(3)],
      [142], [#name("LASHIN Elsayed")], [#age(34)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2466*], [#delta(3)],
      [143], [#name("林钟勋")], [#age(17)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2466*], [#delta(3)],
      [144], [#name("PETO Zsolt")], [#age(27)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2466*], [#delta(3)],
      [145], [#name("薛飞")], [#age(15)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2465*], [#delta(4)],
      [146], [#name("YANG Heng-Wei")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2462*], [#delta(5)],
      [147], [#name("CHOE Il")], [#age(21)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2459*], [#delta(92)],
      [148], [#name("PISTEJ Lubomir")], [#age(30)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2456*], [#delta(4)],
      [149], [#name("JEVTOVIC Marko")], [#age(27)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2456*], [#delta(4)],
      [150], [#name("HIRANO Yuki")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2450*], [#delta(4)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("约尔根 佩尔森")], [#age(48)], [#assoc("SWE")], [?], [?], [?], [*2448*], [#delta(4)],
      [152], [#name("德米特里 佩罗普科夫")], [#age(34)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2448*], [#delta(4)],
      [153], [#name("吴尚垠")], [#age(37)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2446*], [#delta(4)],
      [154], [#name("KONECNY Tomas")], [#age(29)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2444*], [#delta(4)],
      [155], [#name("HIELSCHER Lars")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2443*], [#delta(4)],
      [156], [#name("佐兰 普里莫拉克")], [#age(45)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2442*], [#delta(4)],
      [157], [#name("MIUCHI Kentaro")], [#age(25)], [#assoc("JPN")], [?], [?], [?], [*2440*], [#delta(4)],
      [158], [#name("SAKAI Asuka")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2440*], [#delta(4)],
      [159], [#name("PARK Chan-Hyeok")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2439*], [#delta(4)],
      [160], [#name("WANG Tai-Wei")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2439*], [#delta(4)],
      [161], [#name("米凯尔 梅兹")], [#age(33)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2439*], [#delta(4)],
      [162], [#name("RYUZAKI Tonin")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2439*], [#delta(4)],
      [163], [#name("SODERLUND Hampus")], [#age(20)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2437*], [#delta(5)],
      [164], [#name("BUROV Viacheslav")], [#age(29)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2434*], [#delta(5)],
      [165], [#name("NOROOZI Afshin")], [#age(29)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2434*], [#delta(-26)],
      [166], [#name("JANCARIK Lubomir")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2434*], [#delta(4)],
      [167], [#name("KOLAREK Tomislav")], [#age(26)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2431*], [#delta(5)],
      [168], [#name("GERALDO Joao")], [#age(19)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2430*], [#delta(5)],
      [169], [#name("TREGLER Tomas")], [#age(24)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2429*], [#delta(5)],
      [170], [#name("让 米歇尔 赛弗")], [#age(45)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2428*], [#delta(5)],
      [171], [#name("HUNG Ka Tak")], [#age(16)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2426*], [#delta(5)],
      [172], [#name("WU Chih-Chi")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2425*], [#delta(5)],
      [173], [#name("亚历山大 希巴耶夫")], [#age(24)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2425*], [#delta(-98)],
      [174], [#name("LEGOUT Christophe")], [#age(41)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2424*], [#delta(4)],
      [175], [#name("AKKUZU Can")], [#age(17)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2423*], [#delta(-4)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("BROSSIER Benjamin")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2422*], [#delta(3)],
      [177], [#name("SAMBE Kohei")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2422*], [#delta(3)],
      [178], [#name("PATTANTYUS Adam")], [#age(36)], [#assoc("HUN")], [#right], [#shakehand], [#defense], [*2421*], [#delta(3)],
      [179], [#name("MATSUDAIRA Kenji")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2421*], [#delta(3)],
      [180], [#name("HENZELL William")], [#age(32)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2417*], [#delta(-95)],
      [181], [#name("GHOSH Soumyajit")], [#age(21)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2415*], [#delta(-59)],
      [182], [#name("马蒂亚斯 法尔克")], [#age(23)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2415*], [#delta(3)],
      [183], [#name("FILIMON Andrei")], [#age(37)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2415*], [#delta(3)],
      [184], [#name("BOULOUSSA Mehdi")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2415*], [#delta(3)],
      [185], [#name("SALEH Ahmed")], [#age(35)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2414*], [#delta(3)],
      [186], [#name("亚历山大 卡辛")], [#age(16)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2414*], [#delta(8)],
      [187], [#name("ROBINOT Alexandre")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2410*], [#delta(2)],
      [188], [#name("MADRID Marcos")], [#age(28)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2406*], [#delta(2)],
      [189], [#name("CIOTI Constantin")], [#age(31)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2406*], [#delta(2)],
      [190], [#name("ANGLES Enzo")], [#age(19)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2405*], [#delta(2)],
      [191], [#name("SALIFOU Abdel-Kader")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2405*], [#delta(2)],
      [192], [#name("哈米特 德赛")], [#age(21)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2403*], [#delta(-9)],
      [193], [#name("ARINOBU Taimu")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2403*], [#delta(2)],
      [194], [#name("SEREDA Peter")], [#age(30)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2401*], [#delta(2)],
      [195], [#name("KARUBE Ryusuke")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2401*], [#delta(2)],
      [196], [#name("神巧也")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2401*], [#delta(2)],
      [197], [#name("OBESLO Michal")], [#age(25)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2399*], [#delta(2)],
      [198], [#name("AKERSTROM Fabian")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2399*], [#delta(2)],
      [199], [#name("MONTEIRO Thiago")], [#age(33)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2398*], [#delta(3)],
      [200], [#name("KASAHARA Hiromitsu")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2398*], [#delta(3)],
    )
  )
