#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("李晓霞")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3029*], [#delta(1)],
      [2], [#name("丁宁")], [#age(24)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*3007*], [#delta(1)],
      [3], [#name("刘诗雯")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2972*], [#delta(-2)],
      [4], [#name("陈梦")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2962*], [#delta(1)],
      [5], [#name("武杨")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2956*], [#delta(-1)],
      [6], [#name("朱雨玲")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2890*], [#delta(2)],
      [7], [#name("冯亚兰")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2838*], [#delta(-1)],
      [8], [#name("文佳")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2792*], [#delta(-1)],
      [9], [#name("胡丽梅")], [#age(19)], [#assoc("CHN")], [#right], [#penhold], [#defense], [*2740*], [#delta(3)],
      [10], [#name("徐孝元")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2740*], [#delta(3)],
      [11], [#name("刘佳")], [#age(32)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2724*], [#delta(24)],
      [12], [#name("福原爱")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2720*], [#delta(-3)],
      [13], [#name("石川佳纯")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2715*], [#delta(8)],
      [14], [#name("冯天薇")], [#age(28)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2707*], [#delta(-3)],
      [15], [#name("木子")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2692*], [#delta(0)],
      [16], [#name("李芬")], [#age(38)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2688*], [#delta(-2)],
      [17], [#name("韩莹")], [#age(31)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2686*], [#delta(-7)],
      [18], [#name("维多利亚 帕芙洛维奇")], [#age(36)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2657*], [#delta(-1)],
      [19], [#name("李佼")], [#age(41)], [#assoc("NED")], [#left], [#penhold], [#attack], [*2657*], [#delta(9)],
      [20], [#name("顾玉婷")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2646*], [#delta(-1)],
      [21], [#name("佩特丽莎 索尔佳")], [#age(20)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2642*], [#delta(41)],
      [22], [#name("李倩")], [#age(28)], [#assoc("POL")], [#right], [#shakehand], [#defense], [*2638*], [#delta(-2)],
      [23], [#name("田志希")], [#age(22)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2637*], [#delta(-7)],
      [24], [#name("刘高阳")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2634*], [#delta(0)],
      [25], [#name("杜凯琹")], [#age(18)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2628*], [#delta(35)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("文炫晶")], [#age(30)], [#assoc("KOR")], [?], [?], [?], [*2626*], [#delta(-3)],
      [27], [#name("于梦雨")], [#age(25)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2624*], [#delta(-9)],
      [28], [#name("傅玉")], [#age(36)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2617*], [#delta(24)],
      [29], [#name("李明顺")], [#age(22)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2615*], [#delta(-3)],
      [30], [#name("沈燕飞")], [#age(35)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2615*], [#delta(-3)],
      [31], [#name("森田美咲")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2614*], [#delta(3)],
      [32], [#name("NG Wing Nam")], [#age(22)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2610*], [#delta(43)],
      [33], [#name("梁夏银")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2606*], [#delta(8)],
      [34], [#name("车晓曦")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2602*], [#delta(-3)],
      [35], [#name("张蔷")], [#age(20)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2601*], [#delta(-3)],
      [36], [#name("LI Xue")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#defense], [*2590*], [#delta(-11)],
      [37], [#name("石垣优香")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2585*], [#delta(3)],
      [38], [#name("姜华珺")], [#age(30)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2579*], [#delta(-16)],
      [39], [#name("石贺净")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2576*], [#delta(52)],
      [40], [#name("RI Mi Gyong")], [#age(24)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2575*], [#delta(3)],
      [41], [#name("LIN Ye")], [#age(18)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2575*], [#delta(-11)],
      [42], [#name("单晓娜")], [#age(31)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2571*], [#delta(-5)],
      [43], [#name("PARK Seonghye")], [#age(28)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2566*], [#delta(31)],
      [44], [#name("LEE I-Chen")], [#age(27)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2566*], [#delta(22)],
      [45], [#name("KIM Hye Song")], [#age(21)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2560*], [#delta(-1)],
      [46], [#name("李洁")], [#age(30)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2548*], [#delta(0)],
      [47], [#name("CHOI Moonyoung")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2543*], [#delta(0)],
      [48], [#name("YOON Sunae")], [#age(31)], [#assoc("KOR")], [?], [?], [?], [*2543*], [#delta(0)],
      [49], [#name("LANG Kristin")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2540*], [#delta(0)],
      [50], [#name("平野美宇")], [#age(14)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2538*], [#delta(36)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("KIM Jong")], [#age(25)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2537*], [#delta(-1)],
      [52], [#name("吴佳多")], [#age(37)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2533*], [#delta(-1)],
      [53], [#name("EKHOLM Matilda")], [#age(32)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2533*], [#delta(0)],
      [54], [#name("妮娜 米特兰姆")], [#age(18)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2533*], [#delta(0)],
      [55], [#name("XIAN Yifang")], [#age(37)], [#assoc("FRA")], [#right], [#shakehand], [#defense], [*2529*], [#delta(0)],
      [56], [#name("GU Ruochen")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2524*], [#delta(2)],
      [57], [#name("YOO Eunchong")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2523*], [#delta(97)],
      [58], [#name("金宋依")], [#age(20)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2519*], [#delta(3)],
      [59], [#name("MATSUZAWA Marina")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2515*], [#delta(5)],
      [60], [#name("伊丽莎白 萨玛拉")], [#age(25)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2515*], [#delta(-4)],
      [61], [#name("伯纳黛特 斯佐科斯")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2514*], [#delta(6)],
      [62], [#name("ABE Megumi")], [#age(28)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2512*], [#delta(7)],
      [63], [#name("VACENOVSKA Iveta")], [#age(28)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2509*], [#delta(24)],
      [64], [#name("PESOTSKA Margaryta")], [#age(23)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2508*], [#delta(-35)],
      [65], [#name("IACOB Camelia")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#defense], [*2507*], [#delta(5)],
      [66], [#name("侯美玲")], [#age(25)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2502*], [#delta(-33)],
      [67], [#name("萨比亚 温特")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2501*], [#delta(9)],
      [68], [#name("YAMANASHI Yuri")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2501*], [#delta(5)],
      [69], [#name("索菲亚 波尔卡诺娃")], [#age(20)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2498*], [#delta(-6)],
      [70], [#name("李皓晴")], [#age(22)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2489*], [#delta(-28)],
      [71], [#name("PARK Youngsook")], [#age(26)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2487*], [#delta(-35)],
      [72], [#name("浜本由惟")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2476*], [#delta(-13)],
      [73], [#name("平野早矢香")], [#age(29)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2475*], [#delta(-2)],
      [74], [#name("陈思羽")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2474*], [#delta(19)],
      [75], [#name("ODOROVA Eva")], [#age(35)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2468*], [#delta(5)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("SOLJA Amelie")], [#age(24)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2463*], [#delta(14)],
      [77], [#name("BALAZOVA Barbora")], [#age(22)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2462*], [#delta(4)],
      [78], [#name("PASKAUSKIENE Ruta")], [#age(37)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2461*], [#delta(4)],
      [79], [#name("LOVAS Petra")], [#age(34)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2460*], [#delta(4)],
      [80], [#name("HUANG Yi-Hua")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2458*], [#delta(-8)],
      [81], [#name("郑怡静")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2458*], [#delta(-3)],
      [82], [#name("伊莲 埃万坎")], [#age(31)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2457*], [#delta(-17)],
      [83], [#name("伊藤美诚")], [#age(14)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2455*], [#delta(1)],
      [84], [#name("TIKHOMIROVA Anna")], [#age(30)], [#assoc("RUS")], [?], [?], [?], [*2451*], [#delta(1)],
      [85], [#name("TASHIRO Saki")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2451*], [#delta(50)],
      [86], [#name("乔治娜 波塔")], [#age(29)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2451*], [#delta(-29)],
      [87], [#name("ONO Shiho")], [#age(27)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2450*], [#delta(1)],
      [88], [#name("倪夏莲")], [#age(51)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2448*], [#delta(1)],
      [89], [#name("若宫三纱子")], [#age(25)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2446*], [#delta(-21)],
      [90], [#name("DVORAK Galia")], [#age(26)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2444*], [#delta(2)],
      [91], [#name("STRBIKOVA Renata")], [#age(35)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2440*], [#delta(3)],
      [92], [#name("NONAKA Yuki")], [#age(29)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2438*], [#delta(-54)],
      [93], [#name("杨晓欣")], [#age(26)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2435*], [#delta(2)],
      [94], [#name("SAKAI Haruka")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2432*], [#delta(5)],
      [95], [#name("ZHOU Yihan")], [#age(20)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-16)],
      [96], [#name("PARTYKA Natalia")], [#age(25)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2429*], [#delta(17)],
      [97], [#name("李恩姬")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2427*], [#delta(0)],
      [98], [#name("LAY Jian Fang")], [#age(41)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2427*], [#delta(0)],
      [99], [#name("KOMWONG Nanthana")], [#age(34)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2424*], [#delta(1)],
      [100], [#name("PROKHOROVA Yulia")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2421*], [#delta(2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("GRZYBOWSKA-FRANC Katarzyna")], [#age(25)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2417*], [#delta(-24)],
      [102], [#name("帖雅娜")], [#age(35)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2416*], [#delta(2)],
      [103], [#name("BARTHEL Zhenqi")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2409*], [#delta(-2)],
      [104], [#name("KIM Mingyung")], [#age(22)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2409*], [#delta(58)],
      [105], [#name("HAPONOVA Hanna")], [#age(29)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2407*], [#delta(1)],
      [106], [#name("刘斐")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2406*], [NEW],
      [107], [#name("PENKAVOVA Katerina")], [#age(27)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2402*], [#delta(69)],
      [108], [#name("PERGEL Szandra")], [#age(26)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2402*], [#delta(0)],
      [109], [#name("ZHENG Shichang")], [#age(22)], [#assoc("CHN")], [?], [?], [?], [*2400*], [#delta(1)],
      [110], [#name("ZHU Chaohui")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2399*], [#delta(1)],
      [111], [#name("加藤美优")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2398*], [#delta(-2)],
      [112], [#name("陈幸同")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2397*], [#delta(0)],
      [113], [#name("张安")], [#age(18)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2392*], [#delta(1)],
      [114], [#name("GRUNDISCH Carole")], [#age(28)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2391*], [#delta(1)],
      [115], [#name("CHENG Hsien-Tzu")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2388*], [#delta(71)],
      [116], [#name("ZHENG Jiaqi")], [#age(26)], [#assoc("USA")], [?], [?], [?], [*2385*], [#delta(0)],
      [117], [#name("LI Qiangbing")], [#age(29)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2384*], [#delta(0)],
      [118], [#name("NEMOTO Riyo")], [#age(24)], [#assoc("JPN")], [?], [?], [?], [*2384*], [#delta(50)],
      [119], [#name("DODEAN Daniela")], [#age(26)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2382*], [#delta(-74)],
      [120], [#name("MATSUDAIRA Shiho")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2382*], [#delta(-17)],
      [121], [#name("LIN Chia-Hui")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2381*], [#delta(-25)],
      [122], [#name("SO Eka")], [#age(19)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2379*], [#delta(-4)],
      [123], [#name("张墨")], [#age(25)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2377*], [#delta(-4)],
      [124], [#name("王曼昱")], [#age(15)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2377*], [#delta(-4)],
      [125], [#name("JUNG Yumi")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2369*], [#delta(-3)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("BILENKO Tetyana")], [#age(31)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2365*], [#delta(-2)],
      [127], [#name("STEFANSKA Kinga")], [#age(34)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2363*], [#delta(-2)],
      [128], [#name("MAEDA Miyu")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2363*], [#delta(-2)],
      [129], [#name("RAMIREZ Sara")], [#age(27)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2362*], [#delta(-2)],
      [130], [#name("DRINKHALL Joanna")], [#age(27)], [#assoc("ENG")], [#right], [#shakehand], [#defense], [*2361*], [#delta(-1)],
      [131], [#name("NG Sock Khim")], [#age(30)], [#assoc("MAS")], [?], [?], [?], [*2361*], [#delta(-1)],
      [132], [#name("FUJII Yuko")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2361*], [#delta(-1)],
      [133], [#name("TIAN Yuan")], [#age(39)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2361*], [#delta(-1)],
      [134], [#name("KUSINSKA Klaudia")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2360*], [#delta(-1)],
      [135], [#name("DUBKOVA Elena")], [#age(23)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2359*], [#delta(-1)],
      [136], [#name("KANG Haneul")], [#age(19)], [#assoc("KOR")], [?], [?], [?], [*2358*], [#delta(0)],
      [137], [#name("MATELOVA Hana")], [#age(24)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2357*], [#delta(0)],
      [138], [#name("SIBLEY Kelly")], [#age(26)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2353*], [#delta(1)],
      [139], [#name("BOLLMEIER Nadine")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2351*], [#delta(1)],
      [140], [#name("李恩惠")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2350*], [#delta(1)],
      [141], [#name("AMBRUS Krisztina")], [#age(22)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2348*], [#delta(1)],
      [142], [#name("KRAVCHENKO Marina")], [#age(41)], [#assoc("ISR")], [#right], [#shakehand], [#attack], [*2347*], [#delta(2)],
      [143], [#name("NECULA Iulia")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2345*], [#delta(2)],
      [144], [#name("HSING Ariel")], [#age(19)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2342*], [#delta(3)],
      [145], [#name("SUZUKI Rika")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2342*], [#delta(3)],
      [146], [#name("KUMARESAN Shamini")], [#age(26)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2340*], [#delta(4)],
      [147], [#name("HAN Xing")], [#age(25)], [#assoc("CGO")], [?], [?], [?], [*2339*], [#delta(5)],
      [148], [#name("佐藤瞳")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2338*], [#delta(-41)],
      [149], [#name("GUSEVA Ekaterina")], [#age(18)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2338*], [#delta(2)],
      [150], [#name("DOLGIKH Maria")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2336*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("布里特 伊尔兰德")], [#age(20)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2334*], [#delta(4)],
      [152], [#name("MIKHAILOVA Polina")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2333*], [#delta(-14)],
      [153], [#name("NOSKOVA Yana")], [#age(20)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2332*], [#delta(-30)],
      [154], [#name("BIKBAEVA Anna")], [#age(20)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2331*], [#delta(24)],
      [155], [#name("ISHIKAWA Rira")], [#age(17)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2331*], [#delta(12)],
      [156], [#name("ERDELJI Anamaria")], [#age(29)], [#assoc("SRB")], [#right], [#shakehand], [#defense], [*2330*], [#delta(1)],
      [157], [#name("FEHER Gabriela")], [#age(26)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2329*], [#delta(2)],
      [158], [#name("CHO Hala")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2329*], [#delta(42)],
      [159], [#name("DOI Minami")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2328*], [#delta(1)],
      [160], [#name("KATO Chiaki")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2328*], [#delta(1)],
      [161], [#name("HWANG Jina")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2325*], [#delta(2)],
      [162], [#name("森樱")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2325*], [#delta(-19)],
      [163], [#name("USHIJIMA Seira")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2324*], [#delta(1)],
      [164], [#name("ZARIF Audrey")], [#age(16)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2323*], [#delta(-6)],
      [165], [#name("DIACONU Adina")], [#age(15)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2321*], [#delta(-19)],
      [166], [#name("DAS Mouma")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2320*], [#delta(0)],
      [167], [#name("CECHOVA Dana")], [#age(31)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2318*], [#delta(-14)],
      [168], [#name("TSUI Pao-Wen")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#defense], [*2316*], [#delta(2)],
      [169], [#name("PRIVALOVA Alexandra")], [#age(27)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2315*], [#delta(0)],
      [170], [#name("TODOROVIC Andrea")], [#age(22)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2315*], [#delta(1)],
      [171], [#name("HIRICI Cristina")], [#age(22)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2311*], [#delta(1)],
      [172], [#name("HSIUNG Nai-I")], [#age(24)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2310*], [#delta(1)],
      [173], [#name("ARLOUSKAYA Alina")], [#age(19)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2310*], [#delta(1)],
      [174], [#name("CHIU Ssu-Hua")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#defense], [*2308*], [#delta(1)],
      [175], [#name("KNEZEVIC Monika")], [#age(24)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2307*], [#delta(2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("KIM Minhee")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2305*], [#delta(-48)],
      [177], [#name("STEFANOVA Nikoleta")], [#age(30)], [#assoc("ITA")], [#left], [#shakehand], [#attack], [*2305*], [#delta(2)],
      [178], [#name("KHETKHUAN Tamolwan")], [#age(17)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2303*], [#delta(21)],
      [179], [#name("CHERNOVA Daria")], [#age(17)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2303*], [#delta(-14)],
      [180], [#name("BEH Lee Wei")], [#age(31)], [#assoc("MAS")], [#right], [#shakehand], [#attack], [*2301*], [#delta(-59)],
      [181], [#name("VUGRINEC Suncica")], [#age(27)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2301*], [#delta(-1)],
      [182], [#name("LEE Dasom")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2297*], [#delta(-26)],
      [183], [#name("玛妮卡 巴特拉")], [#age(19)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2292*], [#delta(-2)],
      [184], [#name("LIU Yu-Hsin")], [#age(21)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2292*], [#delta(-2)],
      [185], [#name("MORITA Ayane")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2288*], [#delta(44)],
      [186], [#name("SOO Wai Yam")], [#age(16)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2288*], [#delta(-3)],
      [187], [#name("VIVARELLI Debora")], [#age(21)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2285*], [#delta(-3)],
      [188], [#name("SONG Maeum")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2284*], [#delta(-3)],
      [189], [#name("CIOBANU Irina")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2283*], [#delta(-2)],
      [190], [#name("MADARASZ Dora")], [#age(21)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2280*], [#delta(-1)],
      [191], [#name("JO Yujin")], [#age(22)], [#assoc("KOR")], [?], [?], [?], [*2279*], [#delta(-1)],
      [192], [#name("艾希卡 穆克吉")], [#age(17)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2277*], [#delta(0)],
      [193], [#name("CHOI Jeongmin")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2277*], [#delta(0)],
      [194], [#name("PARK Joohyun")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2277*], [NEW],
      [195], [#name("MIAO Miao")], [#age(33)], [#assoc("AUS")], [?], [?], [?], [*2277*], [#delta(-1)],
      [196], [#name("GHATAK Poulomi")], [#age(31)], [#assoc("IND")], [?], [?], [?], [*2276*], [#delta(-1)],
      [197], [#name("邵杰妮")], [#age(20)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2276*], [#delta(-1)],
      [198], [#name("OWEN Naomi")], [#age(26)], [#assoc("WAL")], [?], [?], [?], [*2274*], [#delta(0)],
      [199], [#name("KUZMINA Elena")], [#age(25)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2271*], [#delta(-8)],
      [200], [#name("HUANG Yu-Wen")], [#age(18)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2270*], [#delta(1)],
    )
  )
