#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("丁宁")], [#age(24)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*3078*], [#delta(0)],
      [2], [#name("刘诗雯")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3021*], [#delta(0)],
      [3], [#name("武杨")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2975*], [#delta(0)],
      [4], [#name("李晓霞")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2957*], [#delta(0)],
      [5], [#name("陈梦")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2915*], [#delta(0)],
      [6], [#name("朱雨玲")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2885*], [#delta(0)],
      [7], [#name("冯天薇")], [#age(28)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2860*], [#delta(0)],
      [8], [#name("韩莹")], [#age(31)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2845*], [#delta(2)],
      [9], [#name("冯亚兰")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2837*], [#delta(-1)],
      [10], [#name("文佳")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2791*], [#delta(-1)],
      [11], [#name("胡丽梅")], [#age(19)], [#assoc("CHN")], [#right], [#penhold], [#defense], [*2740*], [#delta(1)],
      [12], [#name("李芬")], [#age(38)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2740*], [#delta(1)],
      [13], [#name("李明顺")], [#age(22)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2730*], [#delta(2)],
      [14], [#name("刘佳")], [#age(32)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2714*], [#delta(0)],
      [15], [#name("傅玉")], [#age(36)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2699*], [#delta(8)],
      [16], [#name("木子")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2691*], [#delta(0)],
      [17], [#name("佩特丽莎 索尔佳")], [#age(20)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2691*], [#delta(4)],
      [18], [#name("于梦雨")], [#age(25)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2691*], [#delta(-1)],
      [19], [#name("梁夏银")], [#age(20)], [#assoc("COR")], [#right], [#shakehand], [#attack], [*2689*], [#delta(-1)],
      [20], [#name("单晓娜")], [#age(31)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2679*], [#delta(7)],
      [21], [#name("福原爱")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2678*], [#delta(-1)],
      [22], [#name("石川佳纯")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2675*], [#delta(0)],
      [23], [#name("刘高阳")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2669*], [#delta(-4)],
      [24], [#name("李倩")], [#age(28)], [#assoc("POL")], [#right], [#shakehand], [#defense], [*2657*], [#delta(2)],
      [25], [#name("李美京")], [#age(24)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2649*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("顾玉婷")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2646*], [#delta(-1)],
      [27], [#name("李洁")], [#age(30)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2637*], [#delta(9)],
      [28], [#name("伊丽莎白 萨马拉")], [#age(25)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2636*], [#delta(-17)],
      [29], [#name("侯美玲")], [#age(25)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2632*], [#delta(47)],
      [30], [#name("王曼昱")], [#age(15)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2630*], [#delta(14)],
      [31], [#name("吴佳多")], [#age(37)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2628*], [#delta(-3)],
      [32], [#name("文炫晶")], [#age(30)], [#assoc("KOR")], [?], [?], [?], [*2626*], [#delta(-3)],
      [33], [#name("乔治娜 波塔")], [#age(29)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2624*], [#delta(27)],
      [34], [#name("李皓晴")], [#age(22)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2617*], [#delta(-3)],
      [35], [#name("索菲亚 波尔卡诺娃")], [#age(20)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2616*], [#delta(6)],
      [36], [#name("沈燕飞")], [#age(35)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2614*], [#delta(-4)],
      [37], [#name("陈幸同")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2614*], [#delta(17)],
      [38], [#name("陈思羽")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2613*], [#delta(-5)],
      [39], [#name("平野早矢香")], [#age(29)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2609*], [#delta(-5)],
      [40], [#name("吴颖岚")], [#age(22)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2608*], [#delta(-5)],
      [41], [#name("车晓曦")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2602*], [#delta(-3)],
      [42], [#name("张蔷")], [#age(20)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2601*], [#delta(-2)],
      [43], [#name("丹妮拉 多迪安")], [#age(26)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2599*], [#delta(-1)],
      [44], [#name("ABE Megumi")], [#age(28)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2596*], [#delta(24)],
      [45], [#name("杜凯琹")], [#age(18)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2591*], [#delta(3)],
      [46], [#name("徐孝元")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2587*], [#delta(-1)],
      [47], [#name("艾米丽 索尔佳")], [#age(24)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2572*], [#delta(-10)],
      [48], [#name("娜塔莉亚 帕尔蒂卡")], [#age(25)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2566*], [#delta(31)],
      [49], [#name("金慧星")], [#age(21)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2566*], [#delta(0)],
      [50], [#name("石垣优香")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2566*], [#delta(-20)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("倪夏莲")], [#age(51)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2564*], [#delta(61)],
      [52], [#name("林叶")], [#age(18)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2560*], [#delta(-2)],
      [53], [#name("伊雷妮 伊万坎")], [#age(31)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2558*], [#delta(3)],
      [54], [#name("田志希")], [#age(22)], [#assoc("COR")], [#left], [#shakehand], [#attack], [*2552*], [#delta(-1)],
      [55], [#name("陈可")], [#age(17)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2550*], [#delta(-4)],
      [56], [#name("佐藤瞳")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2547*], [#delta(-13)],
      [57], [#name("崔文渶")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2543*], [#delta(1)],
      [58], [#name("尹善爱")], [#age(31)], [#assoc("KOR")], [?], [?], [?], [*2542*], [#delta(1)],
      [59], [#name("卡塔日娜 格日博夫斯卡-弗朗茨")], [#age(25)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2542*], [#delta(15)],
      [60], [#name("ZHU Chaohui")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2541*], [#delta(63)],
      [61], [#name("克里斯汀 朗")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2539*], [#delta(0)],
      [62], [#name("杨晓欣")], [#age(26)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2539*], [#delta(0)],
      [63], [#name("玛蒂尔达 埃克霍尔姆")], [#age(32)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2536*], [#delta(18)],
      [64], [#name("森樱")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2531*], [#delta(-17)],
      [65], [#name("萨宾 温特")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2530*], [#delta(-19)],
      [66], [#name("维多利亚 帕夫洛维奇")], [#age(36)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2530*], [#delta(9)],
      [67], [#name("羡宜芳")], [#age(37)], [#assoc("FRA")], [#right], [#shakehand], [#defense], [*2529*], [#delta(0)],
      [68], [#name("伊韦塔 瓦切诺夫斯卡")], [#age(28)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2527*], [#delta(-2)],
      [69], [#name("李佼")], [#age(41)], [#assoc("NED")], [#left], [#penhold], [#attack], [*2527*], [#delta(-17)],
      [70], [#name("朴英淑")], [#age(26)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2525*], [#delta(-1)],
      [71], [#name("顾若辰")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2524*], [#delta(-1)],
      [72], [#name("姜华珺")], [#age(30)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2522*], [#delta(0)],
      [73], [#name("布里特 伊尔兰德")], [#age(20)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2522*], [#delta(13)],
      [74], [#name("伊藤美诚")], [#age(14)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2521*], [#delta(-3)],
      [75], [#name("金宋依")], [#age(20)], [#assoc("COR")], [#right], [#shakehand], [#defense], [*2518*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("前田美优")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2518*], [#delta(21)],
      [77], [#name("李雪")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#defense], [*2511*], [#delta(8)],
      [78], [#name("妮娜 米特兰姆")], [#age(18)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2510*], [#delta(-1)],
      [79], [#name("玛格丽塔 佩索茨卡")], [#age(23)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2510*], [#delta(4)],
      [80], [#name("平野美宇")], [#age(14)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2505*], [#delta(-15)],
      [81], [#name("巴尔博拉 巴拉佐娃")], [#age(22)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2505*], [#delta(59)],
      [82], [#name("周一涵")], [#age(20)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2504*], [#delta(-4)],
      [83], [#name("李依真")], [#age(27)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2500*], [#delta(-3)],
      [84], [#name("森园美咲")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2499*], [#delta(-29)],
      [85], [#name("若宫三纱子")], [#age(25)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2499*], [#delta(-28)],
      [86], [#name("李恩姬")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2497*], [#delta(-4)],
      [87], [#name("郑怡静")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2490*], [#delta(-3)],
      [88], [#name("伯纳黛特 斯佐科斯")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2490*], [#delta(21)],
      [89], [#name("宋惠佳")], [#age(19)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2489*], [#delta(30)],
      [90], [#name("藤井优子")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2482*], [#delta(-3)],
      [91], [#name("金仲")], [#age(25)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2477*], [#delta(-1)],
      [92], [#name("鲁塔 帕斯考斯基涅")], [#age(37)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2474*], [#delta(-53)],
      [93], [#name("卡梅利娅 雅各布")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#defense], [*2474*], [#delta(-5)],
      [94], [#name("KATO Kyoka")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2472*], [#delta(73)],
      [95], [#name("波琳娜 米哈伊洛娃")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2469*], [#delta(-32)],
      [96], [#name("朴晟惠")], [#age(28)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2468*], [#delta(-4)],
      [97], [#name("多拉 马达拉斯")], [#age(21)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2465*], [#delta(41)],
      [98], [#name("加布里埃拉 费赫尔")], [#age(26)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2461*], [#delta(70)],
      [99], [#name("松泽茉里奈")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2461*], [#delta(-5)],
      [100], [#name("孙祯琦")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2459*], [#delta(-4)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("张安")], [#age(18)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2454*], [#delta(-2)],
      [102], [#name("柳恩钟")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2451*], [#delta(-2)],
      [103], [#name("安娜 蒂克米罗娃")], [#age(30)], [#assoc("RUS")], [?], [?], [?], [*2451*], [#delta(-2)],
      [104], [#name("金玟耿")], [#age(22)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2448*], [#delta(-2)],
      [105], [#name("张墨")], [#age(25)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2446*], [#delta(9)],
      [106], [#name("帖雅娜")], [#age(35)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2445*], [#delta(-2)],
      [107], [#name("郑先知")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2445*], [#delta(-2)],
      [108], [#name("凯莉 西布利")], [#age(26)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2444*], [#delta(58)],
      [109], [#name("加藤美优")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2444*], [#delta(-11)],
      [110], [#name("小野思保")], [#age(27)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2442*], [#delta(-4)],
      [111], [#name("玛妮卡 巴特拉")], [#age(19)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2442*], [#delta(-4)],
      [112], [#name("佩特拉 洛瓦斯")], [#age(34)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2441*], [#delta(-17)],
      [113], [#name("雷娜塔 斯特尔比科娃")], [#age(35)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2439*], [#delta(-20)],
      [114], [#name("LEE Dasom")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2435*], [#delta(-3)],
      [115], [#name("莱娅 拉科瓦奇")], [#age(18)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2431*], [#delta(81)],
      [116], [#name("卡特琳娜 佩卡沃娃")], [#age(27)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2427*], [#delta(39)],
      [117], [#name("尤利娅 普罗霍罗娃")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2422*], [#delta(-4)],
      [118], [#name("卡罗尔 格伦迪施")], [#age(28)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2417*], [#delta(2)],
      [119], [#name("蒂娜 梅谢芙")], [#age(20)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2409*], [#delta(-3)],
      [120], [#name("亚历山德拉 普里瓦洛娃")], [#age(27)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2409*], [#delta(187)],
      [121], [#name("何卓佳")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2408*], [#delta(-18)],
      [122], [#name("尚塔尔 曼茨")], [#age(18)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2406*], [#delta(-5)],
      [123], [#name("刘斐")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2406*], [#delta(-5)],
      [124], [#name("玛丽亚 多尔吉赫")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2403*], [#delta(-9)],
      [125], [#name("松平志穗")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2400*], [#delta(-34)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("ZHENG Shichang")], [#age(22)], [#assoc("CHN")], [?], [?], [?], [*2400*], [#delta(-5)],
      [127], [#name("韩杏")], [#age(25)], [#assoc("CGO")], [?], [?], [?], [*2399*], [#delta(-5)],
      [128], [#name("SAKAI Haruka")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2397*], [#delta(-4)],
      [129], [#name("安娜玛丽亚 埃尔德利")], [#age(29)], [#assoc("SRB")], [#right], [#shakehand], [#defense], [*2395*], [#delta(51)],
      [130], [#name("达蒙万 克宽")], [#age(17)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2394*], [#delta(-5)],
      [131], [#name("亚娜 诺斯科娃")], [#age(20)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2394*], [#delta(-1)],
      [132], [#name("洪剑芳")], [#age(41)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2376*], [#delta(1)],
      [133], [#name("李嫱冰")], [#age(29)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2376*], [#delta(-6)],
      [134], [#name("LI Isabelle Siyun")], [#age(20)], [#assoc("SGP")], [#right], [#shakehand], [#defense], [*2375*], [#delta(2)],
      [135], [#name("田原")], [#age(39)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2374*], [#delta(-71)],
      [136], [#name("GALIC Alex")], [#age(20)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2374*], [#delta(134)],
      [137], [#name("早田希娜")], [#age(14)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2370*], [#delta(-5)],
      [138], [#name("李时温")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2369*], [#delta(7)],
      [139], [#name("郑有美")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2369*], [#delta(0)],
      [140], [#name("范思琦")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2365*], [#delta(6)],
      [141], [#name("CHO Hala")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2364*], [#delta(0)],
      [142], [#name("LI Chunli")], [#age(52)], [#assoc("NZL")], [#right], [#penhold], [#attack], [*2363*], [#delta(0)],
      [143], [#name("萨拉 拉米雷斯")], [#age(27)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2362*], [#delta(0)],
      [144], [#name("劳拉 加斯尼尔")], [#age(21)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2362*], [#delta(57)],
      [145], [#name("CHOI Jeongmin")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2360*], [#delta(-1)],
      [146], [#name("浜本由惟")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2358*], [#delta(1)],
      [147], [#name("素塔西尼 萨维塔布特")], [#age(20)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2357*], [#delta(1)],
      [148], [#name("MU Jingyu")], [#age(15)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2357*], [#delta(47)],
      [149], [#name("金加 斯特凡斯卡")], [#age(34)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2356*], [#delta(1)],
      [150], [#name("MATSUMOTO Yuki")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2354*], [#delta(-15)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("汉娜 马特洛娃")], [#age(24)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2353*], [#delta(6)],
      [152], [#name("ISHIZUKA Miwako")], [#age(27)], [#assoc("JPN")], [?], [?], [?], [*2351*], [#delta(221)],
      [153], [#name("汉娜 哈珀诺娃")], [#age(29)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2351*], [#delta(-24)],
      [154], [#name("KANG Haneul")], [#age(19)], [#assoc("KOR")], [?], [?], [?], [*2350*], [#delta(-5)],
      [155], [#name("安德里亚 托多罗维奇")], [#age(22)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2349*], [#delta(48)],
      [156], [#name("黄淑琴")], [#age(30)], [#assoc("MAS")], [?], [?], [?], [*2347*], [#delta(-4)],
      [157], [#name("SIKORSKA Magdalena")], [#age(28)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2347*], [#delta(75)],
      [158], [#name("CHEONG Cheng I")], [#age(26)], [#assoc("MAC")], [#right], [#shakehand], [#attack], [*2344*], [#delta(-4)],
      [159], [#name("高王")], [#age(34)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2343*], [#delta(-3)],
      [160], [#name("加利娅 德沃拉克")], [#age(26)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2343*], [#delta(-52)],
      [161], [#name("田代早纪")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2342*], [#delta(-35)],
      [162], [#name("黄怡桦")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2341*], [#delta(-4)],
      [163], [#name("西贝尔 阿尔滕卡亚")], [#age(21)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2340*], [#delta(70)],
      [164], [#name("TSUI Pao-Wen")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#defense], [*2338*], [#delta(-4)],
      [165], [#name("阿迪娜 迪亚科努")], [#age(15)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2338*], [#delta(-4)],
      [166], [#name("卢卡 熊原")], [#age(19)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2337*], [#delta(-7)],
      [167], [#name("纳迪娜 博尔迈尔")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2336*], [#delta(-5)],
      [168], [#name("ABE Airi")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2334*], [#delta(-5)],
      [169], [#name("刘馨尹")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2334*], [#delta(-4)],
      [170], [#name("YAMADA Jessica")], [#age(25)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2333*], [#delta(7)],
      [171], [#name("马莉薇")], [#age(31)], [#assoc("MAS")], [#right], [#shakehand], [#attack], [*2326*], [#delta(-2)],
      [172], [#name("HWANG Jina")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2325*], [#delta(-2)],
      [173], [#name("穆玛 达斯")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2320*], [#delta(0)],
      [174], [#name("波琳 沙斯兰")], [#age(17)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2319*], [#delta(0)],
      [175], [#name("叶莲娜 库兹米娜")], [#age(25)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2316*], [#delta(-24)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("桑德拉 佩尔格尔")], [#age(26)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2316*], [#delta(-12)],
      [177], [#name("伯纳德特 巴林特")], [#age(18)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2315*], [#delta(-1)],
      [178], [#name("亚迪拉 席尔瓦")], [#age(29)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2315*], [#delta(-50)],
      [179], [#name("利吉娅 席尔瓦")], [#age(33)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2314*], [#delta(5)],
      [180], [#name("PARK Seri")], [#age(17)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2314*], [#delta(-9)],
      [181], [#name("宋马音")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2313*], [#delta(-3)],
      [182], [#name("克里斯蒂娜 希里奇")], [#age(22)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2311*], [#delta(0)],
      [183], [#name("AMBRUS Krisztina")], [#age(22)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2311*], [#delta(2)],
      [184], [#name("达娜 切霍娃")], [#age(31)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2310*], [#delta(-1)],
      [185], [#name("伊娃 奥多罗娃")], [#age(35)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2310*], [#delta(3)],
      [186], [#name("伊琳娜 乔巴努")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2309*], [#delta(23)],
      [187], [#name("CHERNOVA Daria")], [#age(17)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2307*], [#delta(0)],
      [188], [#name("AMANO Yu")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2306*], [#delta(-2)],
      [189], [#name("尼科莱塔 斯特凡诺娃")], [#age(30)], [#assoc("ITA")], [#left], [#shakehand], [#attack], [*2304*], [#delta(0)],
      [190], [#name("KUSINSKA Klaudia")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2304*], [#delta(0)],
      [191], [#name("艾希卡 穆克吉")], [#age(17)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2301*], [#delta(3)],
      [192], [#name("尤利娅 内库拉")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2300*], [#delta(-1)],
      [193], [#name("LEE Seul")], [#age(18)], [#assoc("KOR")], [?], [?], [?], [*2297*], [#delta(4)],
      [194], [#name("NIWA Misato")], [#age(21)], [#assoc("JPN")], [?], [?], [?], [*2297*], [#delta(-1)],
      [195], [#name("CAREY Charlotte")], [#age(18)], [#assoc("GBR")], [#left], [#shakehand], [#attack], [*2295*], [#delta(150)],
      [196], [#name("DUBKOVA Elena")], [#age(23)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2295*], [#delta(-24)],
      [197], [#name("BIKBAEVA Anna")], [#age(20)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2294*], [#delta(1)],
      [198], [#name("特蒂亚娜 比连科")], [#age(31)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2293*], [#delta(-88)],
      [199], [#name("PFEFER Laura")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2292*], [#delta(-62)],
      [200], [#name("LIU Yu-Hsin")], [#age(21)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2291*], [#delta(0)],
    )
  )
