#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("樊振东")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3077*], [#delta(0)],
      [2], [#name("王楚钦")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*3070*], [#delta(0)],
      [3], [#name("马龙")], [#age(35)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3058*], [#delta(0)],
      [4], [#name("张本智和")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2960*], [#delta(0)],
      [5], [#name("梁靖崑")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2872*], [#delta(0)],
      [6], [#name("特鲁斯 莫雷加德")], [#age(21)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2867*], [#delta(0)],
      [7], [#name("雨果 卡尔德拉诺")], [#age(27)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2865*], [#delta(14)],
      [8], [#name("迪米特里 奥恰洛夫")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2854*], [#delta(-1)],
      [9], [#name("吉村真晴")], [#age(30)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2841*], [#delta(17)],
      [10], [#name("林钟勋")], [#age(26)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2831*], [#delta(-1)],
      [11], [#name("艾利克斯 勒布伦")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2814*], [#delta(0)],
      [12], [#name("林昀儒")], [#age(22)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2814*], [#delta(0)],
      [13], [#name("马蒂亚斯 法尔克")], [#age(32)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2808*], [#delta(-5)],
      [14], [#name("邱党")], [#age(27)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2806*], [#delta(-4)],
      [15], [#name("张禹珍")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2795*], [#delta(22)],
      [16], [#name("卡纳克 贾哈")], [#age(23)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2785*], [#delta(0)],
      [17], [#name("周恺")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2785*], [#delta(13)],
      [18], [#name("向鹏")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2784*], [#delta(6)],
      [19], [#name("达科 约奇克")], [#age(25)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2781*], [#delta(-2)],
      [20], [#name("黄镇廷")], [#age(32)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2777*], [#delta(-6)],
      [21], [#name("篠塚大登")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2774*], [#delta(-1)],
      [22], [#name("徐瑛彬")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2772*], [#delta(39)],
      [23], [#name("帕特里克 弗朗西斯卡")], [#age(31)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2768*], [#delta(-8)],
      [24], [#name("蒂姆 波尔")], [#age(42)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2763*], [#delta(-1)],
      [25], [#name("户上隼辅")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2763*], [#delta(-7)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("利亚姆 皮切福德")], [#age(30)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2752*], [#delta(3)],
      [27], [#name("赵胜敏")], [#age(25)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2748*], [#delta(11)],
      [28], [#name("菲利克斯 勒布伦")], [#age(17)], [#assoc("FRA")], [#right], [#penhold], [#attack], [*2746*], [#delta(-1)],
      [29], [#name("周启豪")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2740*], [#delta(-7)],
      [30], [#name("林诗栋")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2732*], [#delta(-2)],
      [31], [#name("林高远")], [#age(28)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2732*], [#delta(2)],
      [32], [#name("及川瑞基")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2720*], [#delta(0)],
      [33], [#name("薛飞")], [#age(24)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2718*], [#delta(-20)],
      [34], [#name("克里斯坦 卡尔松")], [#age(32)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2718*], [#delta(2)],
      [35], [#name("贝内迪克特 杜达")], [#age(29)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2713*], [#delta(-16)],
      [36], [#name("袁励岑")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2710*], [#delta(-5)],
      [37], [#name("庄智渊")], [#age(42)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2704*], [#delta(-12)],
      [38], [#name("马克斯 弗雷塔斯")], [#age(35)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2699*], [#delta(17)],
      [39], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(43)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2696*], [#delta(3)],
      [40], [#name("卢文 菲鲁斯")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2691*], [#delta(3)],
      [41], [#name("马雷克 巴多夫斯基")], [#age(26)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2688*], [#delta(5)],
      [42], [#name("沙拉特 阿昌塔")], [#age(41)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2685*], [#delta(25)],
      [43], [#name("蒂亚戈 阿波罗尼亚")], [#age(37)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2681*], [#delta(17)],
      [44], [#name("刘丁硕")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2679*], [#delta(4)],
      [45], [#name("安东 卡尔伯格")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2678*], [#delta(4)],
      [46], [#name("塞德里克 纽廷克")], [#age(30)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2676*], [#delta(-12)],
      [47], [#name("赵子豪")], [#age(26)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2676*], [#delta(-6)],
      [48], [#name("西蒙 高兹")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2671*], [#delta(33)],
      [49], [#name("奥维迪乌 伊奥内斯库")], [#age(34)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2670*], [#delta(-14)],
      [50], [#name("弗拉迪斯拉夫 乌尔苏")], [#age(22)], [#assoc("MDA")], [#left], [#shakehand], [#attack], [*2669*], [#delta(2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("徐海东")], [#age(23)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2669*], [#delta(20)],
      [52], [#name("李尚洙")], [#age(33)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2668*], [#delta(12)],
      [53], [#name("宇田幸矢")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2665*], [#delta(1)],
      [54], [#name("朴康贤")], [#age(27)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2661*], [#delta(3)],
      [55], [#name("木造勇人")], [#age(24)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2659*], [#delta(3)],
      [56], [#name("卢博米尔 皮斯特耶")], [#age(39)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2655*], [#delta(78)],
      [57], [#name("于子洋")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2654*], [#delta(-17)],
      [58], [#name("保罗 德林克霍尔")], [#age(33)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2652*], [#delta(-8)],
      [59], [#name("奥马尔 阿萨尔")], [#age(32)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2651*], [#delta(-3)],
      [60], [#name("康 阿库祖")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2649*], [#delta(-15)],
      [61], [#name("田中佑汰")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2649*], [#delta(-2)],
      [62], [#name("夸德里 阿鲁纳")], [#age(35)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2648*], [#delta(1)],
      [63], [#name("乔纳森 格罗斯")], [#age(31)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2641*], [#delta(-1)],
      [64], [#name("乔恩 佩尔森")], [#age(37)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2637*], [#delta(1)],
      [65], [#name("雅罗斯拉夫 扎穆登科")], [#age(35)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2636*], [#delta(25)],
      [66], [#name("SAI Linwei")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2636*], [#delta(0)],
      [67], [#name("汪洋")], [#age(29)], [#assoc("SVK")], [#right], [#shakehand], [#defense], [*2634*], [#delta(1)],
      [68], [#name("凯 斯图姆珀")], [#age(21)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2630*], [#delta(1)],
      [69], [#name("赵大成")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2630*], [#delta(-18)],
      [70], [#name("陈建安")], [#age(32)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2627*], [#delta(25)],
      [71], [#name("若昂 热拉尔多")], [#age(28)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2620*], [#delta(1)],
      [72], [#name("梁俨苧")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2620*], [#delta(-28)],
      [73], [#name("刘夜泊")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2619*], [#delta(-3)],
      [74], [#name("斯蒂芬 门格尔")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2612*], [#delta(-1)],
      [75], [#name("卢博米尔 扬察里克")], [#age(36)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2608*], [#delta(55)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("孙闻")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2604*], [#delta(-37)],
      [77], [#name("里卡多 瓦尔特")], [#age(32)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2604*], [#delta(15)],
      [78], [#name("雅库布 迪亚斯")], [#age(28)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2602*], [#delta(-3)],
      [79], [#name("冯翊新")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2602*], [#delta(4)],
      [80], [#name("亚历山大 卡辛")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2601*], [#delta(-4)],
      [81], [#name("牛冠凯")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2601*], [#delta(-4)],
      [82], [#name("朴灿赫")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2600*], [#delta(-4)],
      [83], [#name("安德烈 加奇尼")], [#age(37)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2595*], [#delta(-9)],
      [84], [#name("马切伊 库比克")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2595*], [#delta(-5)],
      [85], [#name("严升")], [#age(26)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2594*], [#delta(-5)],
      [86], [#name("郭勇")], [#age(17)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2592*], [#delta(52)],
      [87], [#name("丹尼尔 哈贝松")], [#age(37)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2591*], [#delta(-5)],
      [88], [#name("陈垣宇")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2588*], [#delta(-35)],
      [89], [#name("约安尼斯 斯古罗普洛斯")], [#age(23)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2582*], [#delta(-4)],
      [90], [#name("安宰贤")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2579*], [#delta(42)],
      [91], [#name("托米斯拉夫 普卡")], [#age(27)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2578*], [#delta(33)],
      [92], [#name("曾蓓勋")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2577*], [#delta(-3)],
      [93], [#name("安托万 阿沙尔")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2574*], [#delta(-2)],
      [94], [#name("孟凡博")], [#age(23)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2572*], [#delta(-8)],
      [95], [#name("曹巍")], [#age(24)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2571*], [#delta(-2)],
      [96], [#name("诺沙迪 阿拉米扬")], [#age(32)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2571*], [#delta(-49)],
      [97], [#name("姜东秀")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2569*], [#delta(-13)],
      [98], [#name("维托 石井")], [#age(28)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2569*], [#delta(65)],
      [99], [#name("基利安 奥尔特")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2562*], [#delta(-12)],
      [100], [#name("王臻")], [#age(38)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2560*], [#delta(-6)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("特里斯坦 弗洛雷")], [#age(28)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2558*], [#delta(-5)],
      [102], [#name("汤姆 贾维斯")], [#age(24)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2556*], [#delta(68)],
      [103], [#name("朱尔斯 罗兰")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2555*], [#delta(12)],
      [104], [#name("松山祐季")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2552*], [#delta(-5)],
      [105], [#name("罗伯特 加尔多斯")], [#age(44)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2547*], [#delta(8)],
      [106], [#name("英田理志")], [#age(30)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2546*], [#delta(-5)],
      [107], [#name("LIANG Guodong")], [#age(20)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*2545*], [#delta(-5)],
      [108], [#name("REITSPIES David")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2540*], [#delta(-5)],
      [109], [#name("亚当 苏迪")], [#age(27)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2538*], [#delta(-4)],
      [110], [#name("米洛什 雷德齐姆斯基")], [#age(17)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2534*], [#delta(26)],
      [111], [#name("吴家骥")], [#age(28)], [#assoc("DOM")], [#right], [#penhold], [#attack], [*2532*], [#delta(-5)],
      [112], [#name("沙提安 加纳纳塞卡兰")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2530*], [#delta(-24)],
      [113], [#name("德尼 科祖尔")], [#age(26)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2526*], [#delta(-16)],
      [114], [#name("力廉 巴德")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2526*], [#delta(-10)],
      [115], [#name("ZELJKO Filip")], [#age(27)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2525*], [#delta(-7)],
      [116], [#name("王晨策")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2524*], [#delta(-7)],
      [117], [#name("吴晙诚")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2523*], [#delta(-7)],
      [118], [#name("滨田一辉")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2520*], [#delta(-6)],
      [119], [#name("本斯 马约罗斯")], [#age(26)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2519*], [#delta(-5)],
      [120], [#name("莱奥 德诺德雷斯特")], [#age(23)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2518*], [#delta(41)],
      [121], [#name("基里尔 格拉西缅科")], [#age(27)], [#assoc("KAZ")], [#right], [#shakehand], [#attack], [*2518*], [#delta(-21)],
      [122], [#name("乔鲍 安德拉斯")], [#age(21)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2515*], [#delta(-6)],
      [123], [#name("吉村和弘")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2513*], [#delta(-6)],
      [124], [#name("神巧也")], [#age(30)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2512*], [#delta(-6)],
      [125], [#name("艾曼纽 莱贝松")], [#age(35)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2512*], [#delta(-14)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("何钧杰")], [#age(26)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2511*], [#delta(84)],
      [127], [#name("奥拉西奥 西富恩特斯")], [#age(25)], [#assoc("ARG")], [#right], [#shakehand], [#attack], [*2506*], [#delta(-7)],
      [128], [#name("马纳夫 塔卡尔")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2506*], [#delta(-9)],
      [129], [#name("尼马 阿拉米安")], [#age(31)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2506*], [#delta(19)],
      [130], [#name("古斯塔沃 坪井")], [#age(38)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2505*], [#delta(-8)],
      [131], [#name("马丁 阿莱格罗")], [#age(27)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2501*], [#delta(-8)],
      [132], [#name("若昂 蒙泰罗")], [#age(40)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2498*], [#delta(-5)],
      [133], [#name("安德斯 林德")], [#age(25)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2498*], [#delta(-7)],
      [134], [#name("LORENZO Santiago")], [#age(22)], [#assoc("ARG")], [#right], [#shakehand], [#attack], [*2492*], [#delta(-13)],
      [135], [#name("迪奥戈 卡瓦略")], [#age(31)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2492*], [#delta(-6)],
      [136], [#name("廖振珽")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2491*], [#delta(-1)],
      [137], [#name("哈米特 德赛")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2489*], [#delta(-39)],
      [138], [#name("伊尔万 贝特朗")], [#age(23)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2486*], [#delta(-5)],
      [139], [#name("阿尔瓦罗 罗布勒斯")], [#age(32)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2485*], [#delta(-32)],
      [140], [#name("萨穆埃尔 库尔奇茨基")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2482*], [#delta(-12)],
      [141], [#name("克里斯蒂安 普莱蒂亚")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2481*], [#delta(-10)],
      [142], [#name("达里乌斯 莫维莱亚努")], [#age(18)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2481*], [#delta(-17)],
      [143], [#name("金东贤")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2481*], [#delta(-6)],
      [144], [#name("YANG Tzu-Yi")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2480*], [NEW],
      [145], [#name("马塞洛 阿吉雷")], [#age(30)], [#assoc("PAR")], [#left], [#shakehand], [#attack], [*2478*], [#delta(14)],
      [146], [#name("林兆恒")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2475*], [#delta(22)],
      [147], [#name("贝内德克 奥拉")], [#age(32)], [#assoc("FIN")], [#right], [#shakehand], [#attack], [*2473*], [#delta(-8)],
      [148], [#name("巴斯蒂安 伦贝尔")], [#age(23)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2471*], [#delta(-5)],
      [149], [#name("SONE Kakeru")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2471*], [#delta(-5)],
      [150], [#name("ECSEKI Nandor")], [#age(27)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2469*], [#delta(65)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("SODERLUND Hampus")], [#age(29)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2462*], [#delta(-6)],
      [152], [#name("陶马什 拉卡托什")], [#age(28)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2461*], [#delta(-6)],
      [153], [#name("弗洛朗 兰比特")], [#age(28)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2461*], [#delta(-6)],
      [154], [#name("叶夫根 普里施切帕")], [#age(38)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2457*], [#delta(-2)],
      [155], [#name("恩佐 昂格勒")], [#age(28)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2456*], [#delta(-2)],
      [156], [#name("冯耀恩")], [#age(21)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2456*], [#delta(-15)],
      [157], [#name("SUZUKI Hayate")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2454*], [#delta(-3)],
      [158], [#name("松岛辉空")], [#age(16)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2452*], [#delta(-3)],
      [159], [#name("高承睿")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2451*], [#delta(-9)],
      [160], [#name("劳伦斯 德沃斯")], [#age(23)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2450*], [#delta(-4)],
      [161], [#name("安迪 佩雷拉")], [#age(34)], [#assoc("CUB")], [#left], [#shakehand], [#attack], [*2450*], [#delta(-4)],
      [162], [#name("全开源")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2450*], [#delta(-4)],
      [163], [#name("安德莱斯 勒文科")], [#age(25)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2450*], [#delta(15)],
      [164], [#name("埃斯特班 多尔")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2449*], [#delta(-4)],
      [165], [#name("易卜拉欣 京迪兹")], [#age(26)], [#assoc("TUR")], [#left], [#shakehand], [#attack], [*2447*], [#delta(-3)],
      [166], [#name("艾哈迈德 萨利赫")], [#age(44)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2447*], [#delta(-24)],
      [167], [#name("CAMPOS Jorge")], [#age(32)], [#assoc("CUB")], [#right], [#shakehand], [#attack], [*2442*], [#delta(-3)],
      [168], [#name("吉山僚一")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2440*], [#delta(-3)],
      [169], [#name("横谷晟")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2439*], [#delta(-3)],
      [170], [#name("加斯顿 阿尔托")], [#age(38)], [#assoc("ARG")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-1)],
      [171], [#name("MEISSNER Cedric")], [#age(23)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2438*], [#delta(10)],
      [172], [#name("帕维尔 西鲁切克")], [#age(31)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2437*], [#delta(-1)],
      [173], [#name("弗拉内 科伊奇")], [#age(31)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2437*], [#delta(-1)],
      [174], [#name("马努什 沙阿")], [#age(22)], [#assoc("IND")], [#left], [#shakehand], [#attack], [*2436*], [#delta(8)],
      [175], [#name("黄彦诚")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2435*], [#delta(-8)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("米哈伊 博博奇卡")], [#age(37)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2434*], [#delta(-1)],
      [177], [#name("KIM Taehyun")], [#age(20)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2433*], [#delta(0)],
      [178], [#name("禹衡圭")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2433*], [#delta(1)],
      [179], [#name("爱德华 约内斯库")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2430*], [#delta(-6)],
      [180], [#name("马尔科 耶夫托维奇")], [#age(36)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2429*], [#delta(0)],
      [181], [#name("文森特 皮卡尔")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2429*], [#delta(-30)],
      [182], [#name("阿德里安 拉森福斯")], [#age(20)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2428*], [#delta(-42)],
      [183], [#name("CHOI Inhyeok")], [#age(23)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2426*], [#delta(0)],
      [184], [#name("伊莱亚斯 兰弗利")], [#age(27)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2419*], [#delta(0)],
      [185], [#name("尼基尔 库马尔")], [#age(20)], [#assoc("USA")], [#left], [#shakehand], [#attack], [*2419*], [#delta(0)],
      [186], [#name("阿尔贝托 米诺")], [#age(33)], [#assoc("ECU")], [#right], [#shakehand], [#attack], [*2419*], [#delta(-37)],
      [187], [#name("穆罕默德 埃尔贝亚利")], [#age(35)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2414*], [#delta(0)],
      [188], [#name("吴柏男")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2413*], [#delta(-2)],
      [189], [#name("罗宾 德沃斯")], [#age(29)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2412*], [#delta(-1)],
      [190], [#name("迪博 泊雷特")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2411*], [#delta(-1)],
      [191], [#name("托马斯 波兰斯基")], [#age(25)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2409*], [#delta(-1)],
      [192], [#name("迪米特里耶 莱瓦亚茨")], [#age(22)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2408*], [#delta(-1)],
      [193], [#name("安德烈 普屯蒂卡")], [#age(24)], [#assoc("MDA")], [#left], [#shakehand], [#attack], [*2408*], [#delta(-1)],
      [194], [#name("迈赫迪 布洛斯")], [#age(28)], [#assoc("ALG")], [#right], [#shakehand], [#attack], [*2407*], [#delta(-20)],
      [195], [#name("MUTTI Matteo")], [#age(23)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2404*], [#delta(-2)],
      [196], [#name("纳维德 沙姆斯")], [#age(18)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2404*], [#delta(109)],
      [197], [#name("安德烈亚 朗德里厄")], [#age(27)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2401*], [#delta(-3)],
      [198], [#name("佐尔特 佩托")], [#age(36)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2401*], [#delta(-3)],
      [199], [#name("AHMADIAN Amin")], [#age(22)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2400*], [#delta(-2)],
      [200], [#name("埃里克 朱蒂")], [#age(29)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2396*], [#delta(-1)],
    )
  )
