#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("樊振东")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3159*], [#delta(0)],
      [2], [#name("王楚钦")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*3043*], [#delta(0)],
      [3], [#name("梁靖崑")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2997*], [#delta(2)],
      [4], [#name("马龙")], [#age(35)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2990*], [#delta(-1)],
      [5], [#name("达科 约奇克")], [#age(25)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2915*], [#delta(5)],
      [6], [#name("林高远")], [#age(28)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2911*], [#delta(0)],
      [7], [#name("邱党")], [#age(27)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2849*], [#delta(14)],
      [8], [#name("张本智和")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2841*], [#delta(6)],
      [9], [#name("林诗栋")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2825*], [#delta(6)],
      [10], [#name("林昀儒")], [#age(22)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2821*], [#delta(-3)],
      [11], [#name("林钟勋")], [#age(26)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2802*], [#delta(1)],
      [12], [#name("菲利克斯 勒布伦")], [#age(17)], [#assoc("FRA")], [#right], [#penhold], [#attack], [*2794*], [#delta(-1)],
      [13], [#name("艾利克斯 勒布伦")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2794*], [#delta(-9)],
      [14], [#name("奥马尔 阿萨尔")], [#age(32)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2788*], [#delta(81)],
      [15], [#name("吉村真晴")], [#age(30)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2786*], [#delta(-7)],
      [16], [#name("赵大成")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2786*], [#delta(1)],
      [17], [#name("周恺")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2785*], [#delta(2)],
      [18], [#name("卡纳克 贾哈")], [#age(23)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2785*], [#delta(2)],
      [19], [#name("特鲁斯 莫雷加德")], [#age(21)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2777*], [#delta(-1)],
      [20], [#name("周启豪")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2772*], [#delta(2)],
      [21], [#name("徐瑛彬")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2764*], [#delta(2)],
      [22], [#name("雨果 卡尔德拉诺")], [#age(27)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2763*], [#delta(-9)],
      [23], [#name("蒂姆 波尔")], [#age(42)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2763*], [#delta(2)],
      [24], [#name("克里斯坦 卡尔松")], [#age(32)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2753*], [#delta(10)],
      [25], [#name("向鹏")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2748*], [#delta(3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("张禹珍")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2748*], [#delta(-17)],
      [27], [#name("徐海东")], [#age(23)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2744*], [#delta(2)],
      [28], [#name("黄镇廷")], [#age(32)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2743*], [#delta(14)],
      [29], [#name("袁励岑")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2738*], [#delta(1)],
      [30], [#name("迪米特里 奥恰洛夫")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2734*], [#delta(-3)],
      [31], [#name("李尚洙")], [#age(33)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2732*], [#delta(4)],
      [32], [#name("安东 卡尔伯格")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2732*], [#delta(-16)],
      [33], [#name("户上隼辅")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2728*], [#delta(-2)],
      [34], [#name("安德斯 林德")], [#age(25)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2725*], [#delta(145)],
      [35], [#name("帕特里克 弗朗西斯卡")], [#age(31)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2713*], [#delta(4)],
      [36], [#name("GERALDO Joao")], [#age(28)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2713*], [#delta(42)],
      [37], [#name("田中佑汰")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2706*], [#delta(-1)],
      [38], [#name("PISTEJ Lubomir")], [#age(39)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2701*], [#delta(77)],
      [39], [#name("牛冠凯")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2697*], [#delta(-1)],
      [40], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(43)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2696*], [#delta(6)],
      [41], [#name("薛飞")], [#age(24)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2690*], [#delta(0)],
      [42], [#name("BADOWSKI Marek")], [#age(26)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2689*], [#delta(1)],
      [43], [#name("诺沙迪 阿拉米扬")], [#age(32)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2681*], [#delta(6)],
      [44], [#name("冯翊新")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2681*], [#delta(0)],
      [45], [#name("刘丁硕")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2680*], [#delta(0)],
      [46], [#name("赵子豪")], [#age(26)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2677*], [#delta(1)],
      [47], [#name("赵胜敏")], [#age(25)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2676*], [#delta(-21)],
      [48], [#name("利亚姆 皮切福德")], [#age(30)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2675*], [#delta(-16)],
      [49], [#name("蒂亚戈 阿波罗尼亚")], [#age(37)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2674*], [#delta(2)],
      [50], [#name("庄智渊")], [#age(42)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2674*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("梁俨苧")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2674*], [#delta(-3)],
      [52], [#name("托米斯拉夫 普卡")], [#age(27)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2664*], [#delta(49)],
      [53], [#name("卢文 菲鲁斯")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2664*], [#delta(-16)],
      [54], [#name("丹羽孝希")], [#age(29)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2661*], [#delta(-2)],
      [55], [#name("夸德里 阿鲁纳")], [#age(35)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2656*], [#delta(-15)],
      [56], [#name("于子洋")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2655*], [#delta(-2)],
      [57], [#name("HABESOHN Daniel")], [#age(37)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2655*], [#delta(45)],
      [58], [#name("宇田幸矢")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2650*], [#delta(34)],
      [59], [#name("王臻")], [#age(38)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2648*], [#delta(32)],
      [60], [#name("DRINKHALL Paul")], [#age(33)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2639*], [#delta(16)],
      [61], [#name("马克斯 弗雷塔斯")], [#age(35)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2638*], [#delta(19)],
      [62], [#name("朴康贤")], [#age(27)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2638*], [#delta(-3)],
      [63], [#name("马蒂亚斯 法尔克")], [#age(32)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2633*], [#delta(-39)],
      [64], [#name("弗拉迪斯拉夫 乌尔苏")], [#age(22)], [#assoc("MDA")], [#left], [#shakehand], [#attack], [*2629*], [#delta(-2)],
      [65], [#name("LAM Siu Hang")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2626*], [#delta(57)],
      [66], [#name("雅克布 迪亚斯")], [#age(28)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2622*], [#delta(-9)],
      [67], [#name("BOBOCICA Mihai")], [#age(37)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2622*], [#delta(167)],
      [68], [#name("PARK Chan-Hyeok")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2621*], [#delta(-3)],
      [69], [#name("篠塚大登")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2621*], [#delta(-3)],
      [70], [#name("乔纳森 格罗斯")], [#age(31)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2620*], [#delta(-10)],
      [71], [#name("ORT Kilian")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2617*], [#delta(-3)],
      [72], [#name("斯蒂芬 门格尔")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2613*], [#delta(-2)],
      [73], [#name("西蒙 高兹")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2608*], [#delta(-15)],
      [74], [#name("孙闻")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2608*], [#delta(-3)],
      [75], [#name("PERSSON Jon")], [#age(37)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2608*], [#delta(-42)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("曹巍")], [#age(24)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2607*], [#delta(-4)],
      [77], [#name("木造勇人")], [#age(24)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2604*], [#delta(-4)],
      [78], [#name("LEVENKO Andreas")], [#age(25)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2595*], [#delta(-1)],
      [79], [#name("ROBLES Alvaro")], [#age(32)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2593*], [#delta(-16)],
      [80], [#name("贝内迪克特 杜达")], [#age(29)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2590*], [#delta(-24)],
      [81], [#name("THAKKAR Manav")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2587*], [#delta(0)],
      [82], [#name("郭勇")], [#age(17)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2587*], [#delta(-13)],
      [83], [#name("YAN Sheng")], [#age(26)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2586*], [#delta(-1)],
      [84], [#name("陈建安")], [#age(32)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2585*], [#delta(-1)],
      [85], [#name("SGOUROPOULOS Ioannis")], [#age(23)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2582*], [#delta(-1)],
      [86], [#name("曾蓓勋")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2581*], [#delta(-1)],
      [87], [#name("KANG Dongsoo")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2580*], [#delta(-1)],
      [88], [#name("OLAH Benedek")], [#age(32)], [#assoc("FIN")], [#right], [#shakehand], [#attack], [*2576*], [#delta(0)],
      [89], [#name("SAI Linwei")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2572*], [#delta(4)],
      [90], [#name("基里尔 格拉西缅科")], [#age(27)], [#assoc("KAZ")], [#right], [#shakehand], [#attack], [*2571*], [#delta(10)],
      [91], [#name("AIDA Satoshi")], [#age(30)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2570*], [#delta(3)],
      [92], [#name("AKKUZU Can")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2568*], [#delta(-13)],
      [93], [#name("CASSIN Alexandre")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2568*], [#delta(5)],
      [94], [#name("特里斯坦 弗洛雷")], [#age(28)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2559*], [#delta(9)],
      [95], [#name("MAJOROS Bence")], [#age(26)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2558*], [#delta(-42)],
      [96], [#name("高承睿")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2558*], [#delta(-29)],
      [97], [#name("GNANASEKARAN Sathiyan")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2555*], [#delta(21)],
      [98], [#name("BARDET Lilian")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2552*], [#delta(8)],
      [99], [#name("吴晙诚")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2552*], [#delta(9)],
      [100], [#name("MATSUYAMA Yuki")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2552*], [#delta(9)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("艾曼纽 莱贝松")], [#age(35)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2551*], [#delta(9)],
      [102], [#name("HACHARD Antoine")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2548*], [#delta(10)],
      [103], [#name("REDZIMSKI Milosz")], [#age(17)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2548*], [#delta(1)],
      [104], [#name("ZELJKO Filip")], [#age(27)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2547*], [#delta(23)],
      [105], [#name("罗伯特 加尔多斯")], [#age(44)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2546*], [#delta(-18)],
      [106], [#name("DE NODREST Leo")], [#age(23)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2545*], [#delta(7)],
      [107], [#name("WALTHER Ricardo")], [#age(32)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2543*], [#delta(7)],
      [108], [#name("MARTINKO Jiri")], [#age(24)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2541*], [#delta(8)],
      [109], [#name("REITSPIES David")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2541*], [#delta(8)],
      [110], [#name("安宰贤")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2538*], [#delta(-55)],
      [111], [#name("ACHANTA Sharath")], [#age(41)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2536*], [#delta(-14)],
      [112], [#name("ALLEGRO Martin")], [#age(27)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2536*], [#delta(-38)],
      [113], [#name("塞德里克 纽廷克")], [#age(30)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2533*], [#delta(-52)],
      [114], [#name("KUBIK Maciej")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2533*], [#delta(-7)],
      [115], [#name("RASSENFOSSE Adrien")], [#age(20)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2532*], [#delta(-40)],
      [116], [#name("WU Jiaji")], [#age(28)], [#assoc("DOM")], [#right], [#penhold], [#attack], [*2532*], [#delta(4)],
      [117], [#name("ANDRAS Csaba")], [#age(21)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2532*], [#delta(4)],
      [118], [#name("凯 斯图姆珀")], [#age(21)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2529*], [#delta(5)],
      [119], [#name("CIFUENTES Horacio")], [#age(25)], [#assoc("ARG")], [#right], [#shakehand], [#attack], [*2524*], [#delta(0)],
      [120], [#name("汪洋")], [#age(29)], [#assoc("SVK")], [#right], [#shakehand], [#defense], [*2524*], [#delta(-15)],
      [121], [#name("陈垣宇")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2523*], [#delta(4)],
      [122], [#name("PENG Wang-Wei")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2523*], [#delta(4)],
      [123], [#name("JANCARIK Lubomir")], [#age(36)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2522*], [#delta(-59)],
      [124], [#name("KOZUL Deni")], [#age(26)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2522*], [#delta(-13)],
      [125], [#name("LIU Yebo")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2522*], [#delta(3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("ROLLAND Jules")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2521*], [#delta(3)],
      [127], [#name("HAMADA Kazuki")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2520*], [#delta(3)],
      [128], [#name("及川瑞基")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2519*], [#delta(-39)],
      [129], [#name("MEISSNER Cedric")], [#age(23)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2517*], [#delta(2)],
      [130], [#name("HWANG Minha")], [#age(24)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2517*], [#delta(2)],
      [131], [#name("YANG Tzu-Yi")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2517*], [#delta(12)],
      [132], [#name("DORR Esteban")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2513*], [#delta(1)],
      [133], [#name("吉村和弘")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2512*], [#delta(1)],
      [134], [#name("松岛辉空")], [#age(16)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2509*], [#delta(6)],
      [135], [#name("MUTTI Matteo")], [#age(23)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2505*], [#delta(2)],
      [136], [#name("MAGDY Shady")], [#age(28)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2504*], [#delta(2)],
      [137], [#name("黄友政")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2503*], [#delta(4)],
      [138], [#name("雅罗斯列夫 扎姆登科")], [#age(35)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2503*], [#delta(-42)],
      [139], [#name("奥维迪乌 伊奥内斯库")], [#age(34)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2499*], [#delta(-40)],
      [140], [#name("TAHARA Shogo")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2497*], [#delta(2)],
      [141], [#name("神巧也")], [#age(30)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2496*], [#delta(3)],
      [142], [#name("LIANG Guodong")], [#age(20)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*2496*], [#delta(3)],
      [143], [#name("CANTERO Jesus")], [#age(41)], [#assoc("ESP")], [#right], [#penhold], [#attack], [*2495*], [#delta(3)],
      [144], [#name("CARVALHO Diogo")], [#age(31)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2492*], [#delta(5)],
      [145], [#name("王晨策")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2492*], [#delta(5)],
      [146], [#name("RANEFUR Elias")], [#age(27)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2491*], [#delta(5)],
      [147], [#name("MATI Taiwo")], [#age(18)], [#assoc("NGR")], [#left], [#shakehand], [#attack], [*2488*], [#delta(220)],
      [148], [#name("PRYSHCHEPA Ievgen")], [#age(38)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2488*], [#delta(-13)],
      [149], [#name("TSUBOI Gustavo")], [#age(38)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2486*], [#delta(8)],
      [150], [#name("MENG Fanbo")], [#age(23)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2481*], [#delta(9)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("KIM Taehyun")], [#age(20)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2481*], [#delta(9)],
      [152], [#name("KIM Donghyun")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2479*], [#delta(9)],
      [153], [#name("PEREIRA Andy")], [#age(34)], [#assoc("CUB")], [#left], [#shakehand], [#attack], [*2478*], [#delta(9)],
      [154], [#name("LAMBIET Florent")], [#age(28)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2477*], [#delta(-64)],
      [155], [#name("YEH Chih-Wei")], [#age(33)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2476*], [#delta(8)],
      [156], [#name("ISHIY Vitor")], [#age(28)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2476*], [#delta(2)],
      [157], [#name("SONE Kakeru")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2472*], [#delta(8)],
      [158], [#name("尼马 阿拉米安")], [#age(31)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2469*], [#delta(-4)],
      [159], [#name("CHIRITA Iulian")], [#age(17)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2467*], [#delta(51)],
      [160], [#name("HODAEI Amir Hossein")], [#age(25)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2464*], [#delta(-13)],
      [161], [#name("LI Hsin-Yang")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2464*], [#delta(7)],
      [162], [#name("JARVIS Tom")], [#age(24)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2463*], [#delta(-23)],
      [163], [#name("KULCZYCKI Samuel")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2463*], [#delta(6)],
      [164], [#name("SODERLUND Hampus")], [#age(29)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2462*], [#delta(6)],
      [165], [#name("吉山僚一")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2462*], [#delta(7)],
      [166], [#name("STOYANOV Niagol")], [#age(36)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2461*], [#delta(-18)],
      [167], [#name("IONESCU Eduard")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2459*], [#delta(-12)],
      [168], [#name("SUZUKI Hayate")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2458*], [#delta(7)],
      [169], [#name("ELBEIALI Mohamed")], [#age(35)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2458*], [#delta(55)],
      [170], [#name("LORENZO Santiago")], [#age(22)], [#assoc("ARG")], [#right], [#shakehand], [#attack], [*2457*], [#delta(-3)],
      [171], [#name("HUANG Yan-Cheng")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2456*], [#delta(-18)],
      [172], [#name("廖振珽")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2456*], [#delta(4)],
      [173], [#name("SHAH Manush")], [#age(22)], [#assoc("IND")], [#left], [#shakehand], [#attack], [*2455*], [#delta(-37)],
      [174], [#name("温瑞博")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2454*], [#delta(64)],
      [175], [#name("ISTRATE Andrei")], [#age(18)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2454*], [#delta(-9)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("HAUG Borgar")], [#age(21)], [#assoc("NOR")], [#left], [#shakehand], [#attack], [*2453*], [#delta(1)],
      [177], [#name("PORET Thibault")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2453*], [#delta(1)],
      [178], [#name("AFANADOR Brian")], [#age(26)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2452*], [#delta(128)],
      [179], [#name("ANGLES Enzo")], [#age(28)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2451*], [#delta(1)],
      [180], [#name("QUAN Kaiyuan")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2451*], [#delta(1)],
      [181], [#name("MOVILEANU Darius")], [#age(18)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2450*], [#delta(-17)],
      [182], [#name("LAKATOS Tamas")], [#age(28)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2450*], [#delta(0)],
      [183], [#name("SEYFRIED Joe")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2449*], [#delta(0)],
      [184], [#name("LI Hon Ming")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2444*], [#delta(1)],
      [185], [#name("KOJIC Frane")], [#age(31)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2442*], [#delta(1)],
      [186], [#name("GAO Yang")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2442*], [#delta(2)],
      [187], [#name("MONTEIRO Joao")], [#age(40)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2441*], [#delta(-13)],
      [188], [#name("哈米特 德赛")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2441*], [#delta(-32)],
      [189], [#name("YOKOTANI Jo")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2439*], [#delta(0)],
      [190], [#name("BERTRAND Irvin")], [#age(23)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2439*], [#delta(0)],
      [191], [#name("PICCOLIN Jordy")], [#age(26)], [#assoc("ITA")], [#left], [#shakehand], [#attack], [*2438*], [#delta(0)],
      [192], [#name("安德烈 加奇尼")], [#age(37)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2436*], [#delta(-40)],
      [193], [#name("WOO Hyeonggyu")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2436*], [#delta(0)],
      [194], [#name("CAMPOS Jorge")], [#age(32)], [#assoc("CUB")], [#right], [#shakehand], [#attack], [*2433*], [#delta(1)],
      [195], [#name("MADRID Marcos")], [#age(37)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2433*], [#delta(12)],
      [196], [#name("CHAN Baldwin")], [#age(19)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2433*], [#delta(0)],
      [197], [#name("SZUDI Adam")], [#age(27)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-73)],
      [198], [#name("ABDELAZIZ Youssef")], [#age(23)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2430*], [#delta(6)],
      [199], [#name("JEVTOVIC Marko")], [#age(36)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2429*], [#delta(-1)],
      [200], [#name("PANG Koen")], [#age(21)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2428*], [#delta(-6)],
    )
  )
