#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("樊振东")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3074*], [#delta(1)],
      [2], [#name("王楚钦")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*3054*], [#delta(-1)],
      [3], [#name("马龙")], [#age(35)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3016*], [#delta(0)],
      [4], [#name("林昀儒")], [#age(22)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2991*], [#delta(6)],
      [5], [#name("梁靖崑")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2961*], [#delta(1)],
      [6], [#name("林高远")], [#age(28)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2949*], [#delta(-2)],
      [7], [#name("菲利克斯 勒布伦")], [#age(17)], [#assoc("FRA")], [#right], [#penhold], [#attack], [*2932*], [#delta(-2)],
      [8], [#name("周启豪")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2874*], [#delta(-1)],
      [9], [#name("户上隼辅")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2822*], [#delta(8)],
      [10], [#name("特鲁斯 莫雷加德")], [#age(21)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2810*], [#delta(-2)],
      [11], [#name("林诗栋")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2802*], [#delta(0)],
      [12], [#name("张本智和")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2802*], [#delta(10)],
      [13], [#name("雨果 卡尔德拉诺")], [#age(27)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2799*], [#delta(0)],
      [14], [#name("迪米特里 奥恰洛夫")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2793*], [#delta(1)],
      [15], [#name("卡纳克 贾哈")], [#age(23)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2785*], [#delta(-3)],
      [16], [#name("徐瑛彬")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2783*], [#delta(23)],
      [17], [#name("林钟勋")], [#age(26)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2776*], [#delta(3)],
      [18], [#name("邱党")], [#age(27)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2773*], [#delta(0)],
      [19], [#name("乔纳森 格罗斯")], [#age(31)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2770*], [#delta(-10)],
      [20], [#name("田中佑汰")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2766*], [#delta(-1)],
      [21], [#name("利亚姆 皮切福德")], [#age(30)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2758*], [#delta(3)],
      [22], [#name("黄镇廷")], [#age(32)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2755*], [#delta(-1)],
      [23], [#name("向鹏")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2750*], [#delta(8)],
      [24], [#name("松岛辉空")], [#age(16)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2744*], [#delta(6)],
      [25], [#name("吴晙诚")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2740*], [#delta(25)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("安东 卡尔伯格")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2734*], [#delta(-12)],
      [27], [#name("蒂姆 波尔")], [#age(42)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2730*], [#delta(-11)],
      [28], [#name("梁俨苧")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2730*], [#delta(1)],
      [29], [#name("张禹珍")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2730*], [#delta(-6)],
      [30], [#name("马蒂亚斯 法尔克")], [#age(32)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2729*], [#delta(-2)],
      [31], [#name("西蒙 高兹")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2726*], [#delta(-4)],
      [32], [#name("斯蒂芬 门格尔")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2721*], [#delta(67)],
      [33], [#name("孙闻")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2719*], [#delta(-8)],
      [34], [#name("李尚洙")], [#age(33)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2709*], [#delta(75)],
      [35], [#name("帕特里克 弗朗西斯卡")], [#age(31)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2699*], [#delta(-2)],
      [36], [#name("奥马尔 阿萨尔")], [#age(32)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2698*], [#delta(21)],
      [37], [#name("赵大成")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2698*], [#delta(35)],
      [38], [#name("周恺")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2692*], [#delta(-12)],
      [39], [#name("庄智渊")], [#age(42)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2690*], [#delta(-7)],
      [40], [#name("安宰贤")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2690*], [#delta(0)],
      [41], [#name("基里尔 格拉西缅科")], [#age(27)], [#assoc("KAZ")], [#right], [#shakehand], [#attack], [*2687*], [#delta(43)],
      [42], [#name("马克斯 弗雷塔斯")], [#age(35)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2687*], [#delta(0)],
      [43], [#name("薛飞")], [#age(24)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2685*], [#delta(-6)],
      [44], [#name("吉村真晴")], [#age(30)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2682*], [#delta(-3)],
      [45], [#name("卢文 菲鲁斯")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2679*], [#delta(-11)],
      [46], [#name("安德烈 加奇尼")], [#age(37)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2673*], [#delta(-2)],
      [47], [#name("蒂亚戈 阿波罗尼亚")], [#age(37)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2671*], [#delta(-11)],
      [48], [#name("托米斯拉夫 普卡")], [#age(27)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2666*], [#delta(6)],
      [49], [#name("贝内迪克特 杜达")], [#age(29)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2666*], [#delta(7)],
      [50], [#name("丹羽孝希")], [#age(29)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2661*], [#delta(-3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("BADOWSKI Marek")], [#age(26)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2655*], [#delta(1)],
      [52], [#name("达科 约奇克")], [#age(25)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2655*], [#delta(-17)],
      [53], [#name("刘丁硕")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2654*], [#delta(-2)],
      [54], [#name("艾利克斯 勒布伦")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2650*], [#delta(-6)],
      [55], [#name("吉村和弘")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2649*], [#delta(49)],
      [56], [#name("GERALDO Joao")], [#age(28)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2648*], [#delta(-7)],
      [57], [#name("赵胜敏")], [#age(25)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2643*], [#delta(-14)],
      [58], [#name("克里斯坦 卡尔松")], [#age(32)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2638*], [#delta(2)],
      [59], [#name("篠塚大登")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2636*], [#delta(-13)],
      [60], [#name("高承睿")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2634*], [#delta(64)],
      [61], [#name("爱德华 约内斯库")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2634*], [#delta(19)],
      [62], [#name("宇田幸矢")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2633*], [#delta(0)],
      [63], [#name("冯翊新")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2631*], [#delta(1)],
      [64], [#name("陈垣宇")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2630*], [#delta(3)],
      [65], [#name("赵子豪")], [#age(26)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2629*], [#delta(4)],
      [66], [#name("及川瑞基")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2623*], [#delta(2)],
      [67], [#name("HABESOHN Daniel")], [#age(37)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2620*], [#delta(3)],
      [68], [#name("徐海东")], [#age(23)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2619*], [#delta(-30)],
      [69], [#name("ROLLAND Jules")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2619*], [#delta(18)],
      [70], [#name("ALLEGRO Martin")], [#age(27)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2619*], [#delta(4)],
      [71], [#name("BARDET Lilian")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2618*], [#delta(-16)],
      [72], [#name("JANCARIK Lubomir")], [#age(36)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2618*], [#delta(5)],
      [73], [#name("于子洋")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2617*], [#delta(-20)],
      [74], [#name("雅克布 迪亚斯")], [#age(28)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2616*], [#delta(-16)],
      [75], [#name("奥维迪乌 伊奥内斯库")], [#age(34)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2615*], [#delta(64)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("弗拉迪斯拉夫 乌尔苏")], [#age(22)], [#assoc("MDA")], [#left], [#shakehand], [#attack], [*2615*], [#delta(-3)],
      [77], [#name("BRODD Viktor")], [#age(33)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2612*], [#delta(-1)],
      [78], [#name("牛冠凯")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2612*], [#delta(-12)],
      [79], [#name("CASSIN Alexandre")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2610*], [#delta(73)],
      [80], [#name("王臻")], [#age(38)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2609*], [#delta(10)],
      [81], [#name("曾蓓勋")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2608*], [#delta(-36)],
      [82], [#name("PERSSON Jon")], [#age(37)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2608*], [#delta(-4)],
      [83], [#name("夸德里 阿鲁纳")], [#age(35)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2606*], [#delta(-22)],
      [84], [#name("木造勇人")], [#age(24)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2604*], [#delta(-3)],
      [85], [#name("ROBLES Alvaro")], [#age(32)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2602*], [#delta(-3)],
      [86], [#name("神巧也")], [#age(30)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2601*], [#delta(-23)],
      [87], [#name("WOO Hyeonggyu")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2600*], [#delta(42)],
      [88], [#name("朴康贤")], [#age(27)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2599*], [#delta(-17)],
      [89], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(43)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2597*], [#delta(-3)],
      [90], [#name("诺沙迪 阿拉米扬")], [#age(32)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2595*], [#delta(-2)],
      [91], [#name("LAM Siu Hang")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2593*], [#delta(-32)],
      [92], [#name("ORT Kilian")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2593*], [#delta(-3)],
      [93], [#name("袁励岑")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2590*], [#delta(-18)],
      [94], [#name("尼马 阿拉米安")], [#age(31)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2589*], [#delta(-3)],
      [95], [#name("温瑞博")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2589*], [#delta(-3)],
      [96], [#name("黄彦诚")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2589*], [#delta(-3)],
      [97], [#name("吉山僚一")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2584*], [#delta(-18)],
      [98], [#name("LAKATOS Tamas")], [#age(28)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2582*], [#delta(-15)],
      [99], [#name("罗伯特 加尔多斯")], [#age(44)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2580*], [#delta(18)],
      [100], [#name("ELBEIALI Mohamed")], [#age(35)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2580*], [#delta(-3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("严升")], [#age(26)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2577*], [#delta(-1)],
      [102], [#name("AN Ji Song")], [#age(27)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2574*], [#delta(0)],
      [103], [#name("米洛什 雷德齐姆斯基")], [#age(17)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2573*], [#delta(3)],
      [104], [#name("PARK Chan-Hyeok")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2573*], [#delta(-1)],
      [105], [#name("马金宝")], [#age(23)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2571*], [#delta(-4)],
      [106], [#name("KULCZYCKI Samuel")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2567*], [#delta(-12)],
      [107], [#name("陈建安")], [#age(32)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2566*], [#delta(-2)],
      [108], [#name("PEREIRA Andy")], [#age(34)], [#assoc("CUB")], [#left], [#shakehand], [#attack], [*2564*], [#delta(92)],
      [109], [#name("郭勇")], [#age(17)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2562*], [#delta(7)],
      [110], [#name("汪洋")], [#age(29)], [#assoc("SVK")], [#right], [#shakehand], [#defense], [*2558*], [#delta(-12)],
      [111], [#name("ZELJKO Filip")], [#age(27)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2557*], [#delta(-16)],
      [112], [#name("安德斯 林德")], [#age(25)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2555*], [#delta(-27)],
      [113], [#name("MENG Fanbo")], [#age(23)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2552*], [#delta(-17)],
      [114], [#name("MATSUYAMA Yuki")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2552*], [#delta(1)],
      [115], [#name("廖振珽")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2550*], [#delta(4)],
      [116], [#name("AIDA Satoshi")], [#age(30)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2549*], [#delta(-9)],
      [117], [#name("THAKKAR Manav")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2549*], [#delta(1)],
      [118], [#name("RASSENFOSSE Adrien")], [#age(20)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2548*], [#delta(-10)],
      [119], [#name("黄友政")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2546*], [#delta(-8)],
      [120], [#name("曹巍")], [#age(24)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2546*], [#delta(-55)],
      [121], [#name("HACHARD Antoine")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2545*], [#delta(0)],
      [122], [#name("REMBERT Bastien")], [#age(23)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2543*], [#delta(-10)],
      [123], [#name("DORR Esteban")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2542*], [#delta(-1)],
      [124], [#name("GNANASEKARAN Sathiyan")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2537*], [#delta(2)],
      [125], [#name("王晨策")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2537*], [#delta(2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("LEVENKO Andreas")], [#age(25)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2537*], [#delta(-6)],
      [127], [#name("SZUDI Adam")], [#age(27)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2534*], [#delta(22)],
      [128], [#name("CIFUENTES Horacio")], [#age(25)], [#assoc("ARG")], [#right], [#shakehand], [#attack], [*2533*], [#delta(32)],
      [129], [#name("KUBIK Maciej")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2533*], [#delta(26)],
      [130], [#name("ANDRAS Csaba")], [#age(21)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2532*], [#delta(-2)],
      [131], [#name("滨田一辉")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2530*], [#delta(-1)],
      [132], [#name("孙正")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2529*], [#delta(-1)],
      [133], [#name("PRYSHCHEPA Ievgen")], [#age(38)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2529*], [#delta(0)],
      [134], [#name("WALTHER Ricardo")], [#age(32)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2526*], [#delta(0)],
      [135], [#name("KOZUL Deni")], [#age(26)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2524*], [#delta(9)],
      [136], [#name("KOLODZIEJCZYK Maciej")], [#age(22)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2524*], [#delta(134)],
      [137], [#name("NOROOZI Afshin")], [#age(38)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2523*], [#delta(0)],
      [138], [#name("刘夜泊")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2522*], [#delta(0)],
      [139], [#name("艾曼纽 莱贝松")], [#age(35)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2522*], [#delta(-25)],
      [140], [#name("MUTTI Matteo")], [#age(23)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2521*], [#delta(114)],
      [141], [#name("SEYFRIED Joe")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2518*], [#delta(-18)],
      [142], [#name("BOBOCICA Mihai")], [#age(37)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2518*], [#delta(-10)],
      [143], [#name("HWANG Minha")], [#age(24)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2517*], [#delta(-3)],
      [144], [#name("YANG Tzu-Yi")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2517*], [#delta(-3)],
      [145], [#name("LI Hsin-Yang")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2517*], [#delta(-3)],
      [146], [#name("CHIRITA Iulian")], [#age(17)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2515*], [#delta(-3)],
      [147], [#name("MEISSNER Cedric")], [#age(23)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2513*], [#delta(-12)],
      [148], [#name("SONE Kakeru")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2510*], [#delta(-3)],
      [149], [#name("DE NODREST Leo")], [#age(23)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2506*], [#delta(-24)],
      [150], [#name("SGOUROPOULOS Ioannis")], [#age(23)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2506*], [#delta(-3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("特里斯坦 弗洛雷")], [#age(28)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2506*], [#delta(-3)],
      [152], [#name("MAGDY Shady")], [#age(28)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2504*], [#delta(-2)],
      [153], [#name("AFANADOR Brian")], [#age(26)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2503*], [#delta(-43)],
      [154], [#name("SIPOS Rares")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2501*], [#delta(131)],
      [155], [#name("HODAEI Amir Hossein")], [#age(25)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2499*], [#delta(-1)],
      [156], [#name("TAHARA Shogo")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2497*], [#delta(0)],
      [157], [#name("LIANG Guodong")], [#age(20)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*2496*], [#delta(0)],
      [158], [#name("CANTERO Jesus")], [#age(41)], [#assoc("ESP")], [#right], [#penhold], [#attack], [*2495*], [#delta(1)],
      [159], [#name("MAJOROS Bence")], [#age(26)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2493*], [#delta(2)],
      [160], [#name("NG Pak Nam")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2493*], [#delta(2)],
      [161], [#name("卢卡 姆拉德诺维奇")], [#age(25)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2493*], [#delta(62)],
      [162], [#name("CARVALHO Diogo")], [#age(31)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2492*], [#delta(1)],
      [163], [#name("LEVAJAC Dimitrije")], [#age(22)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2490*], [#delta(1)],
      [164], [#name("凯 斯图姆珀")], [#age(21)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2488*], [#delta(-28)],
      [165], [#name("REITSPIES David")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2487*], [#delta(2)],
      [166], [#name("KIM Daewoo")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2487*], [#delta(2)],
      [167], [#name("PARK Gyeongtae")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2485*], [#delta(3)],
      [168], [#name("MONTEIRO Joao")], [#age(40)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2485*], [#delta(-15)],
      [169], [#name("PENG Wang-Wei")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2485*], [#delta(3)],
      [170], [#name("SAI Linwei")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2484*], [#delta(3)],
      [171], [#name("WU Jiaji")], [#age(28)], [#assoc("DOM")], [#right], [#penhold], [#attack], [*2484*], [#delta(-25)],
      [172], [#name("PISTEJ Lubomir")], [#age(39)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2484*], [#delta(-21)],
      [173], [#name("BURGOS Nicolas")], [#age(22)], [#assoc("CHI")], [#right], [#shakehand], [#attack], [*2483*], [#delta(16)],
      [174], [#name("AKKUZU Can")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2483*], [#delta(0)],
      [175], [#name("DRINKHALL Paul")], [#age(33)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2483*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("KOJIC Frane")], [#age(31)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2479*], [#delta(-11)],
      [177], [#name("KIM Donghyun")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2479*], [#delta(2)],
      [178], [#name("MARTINKO Jiri")], [#age(24)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2477*], [#delta(26)],
      [179], [#name("朴圭贤")], [#age(18)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2477*], [#delta(-8)],
      [180], [#name("RANEFUR Elias")], [#age(27)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2474*], [#delta(0)],
      [181], [#name("JARVIS Tom")], [#age(24)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2474*], [#delta(-68)],
      [182], [#name("ISTRATE Andrei")], [#age(18)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2474*], [#delta(-4)],
      [183], [#name("GIL Minseok")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2471*], [#delta(-1)],
      [184], [#name("BOULOUSSA Mehdi")], [#age(28)], [#assoc("ALG")], [#right], [#shakehand], [#attack], [*2470*], [#delta(-7)],
      [185], [#name("TSUBOI Gustavo")], [#age(38)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2469*], [#delta(-1)],
      [186], [#name("STOYANOV Niagol")], [#age(36)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2469*], [#delta(8)],
      [187], [#name("PANG Koen")], [#age(21)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2468*], [#delta(20)],
      [188], [#name("ISHIY Vitor")], [#age(28)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2466*], [#delta(-30)],
      [189], [#name("KIM Taehyun")], [#age(20)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2463*], [#delta(-3)],
      [190], [#name("MADRID Marcos")], [#age(37)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2463*], [#delta(47)],
      [191], [#name("SHAH Manush")], [#age(22)], [#assoc("IND")], [#left], [#shakehand], [#attack], [*2463*], [#delta(-4)],
      [192], [#name("哈米特 德赛")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2463*], [#delta(-11)],
      [193], [#name("LAMBIET Florent")], [#age(28)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2457*], [#delta(-10)],
      [194], [#name("SALEH Ahmed")], [#age(44)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2457*], [#delta(-1)],
      [195], [#name("TEODORO Guilherme")], [#age(22)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2455*], [#delta(0)],
      [196], [#name("ACHANTA Sharath")], [#age(41)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2454*], [#delta(0)],
      [197], [#name("SODERLUND Hampus")], [#age(29)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2454*], [#delta(0)],
      [198], [#name("KANG Dongsoo")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2454*], [#delta(0)],
      [199], [#name("ABDELAZIZ Youssef")], [#age(23)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2450*], [#delta(0)],
      [200], [#name("CHAN Baldwin")], [#age(19)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2449*], [#delta(-10)],
    )
  )
