#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("孙颖莎")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3150*], [#delta(0)],
      [2], [#name("陈梦")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3060*], [#delta(0)],
      [3], [#name("陈幸同")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2979*], [#delta(0)],
      [4], [#name("王艺迪")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2960*], [#delta(0)],
      [5], [#name("早田希娜")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2927*], [#delta(0)],
      [6], [#name("平野美宇")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2924*], [#delta(7)],
      [7], [#name("王曼昱")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2910*], [#delta(-1)],
      [8], [#name("何卓佳")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2875*], [#delta(-1)],
      [9], [#name("伊藤美诚")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2860*], [#delta(0)],
      [10], [#name("桥本帆乃香")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2825*], [#delta(1)],
      [11], [#name("钱天一")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2821*], [#delta(-3)],
      [12], [#name("伯纳黛特 斯佐科斯")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2812*], [#delta(27)],
      [13], [#name("申裕斌")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2804*], [#delta(6)],
      [14], [#name("蒯曼")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2802*], [#delta(1)],
      [15], [#name("杨晓欣")], [#age(35)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2799*], [#delta(8)],
      [16], [#name("张瑞")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2798*], [#delta(-2)],
      [17], [#name("范思琦")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2786*], [#delta(0)],
      [18], [#name("张本美和")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2784*], [#delta(-8)],
      [19], [#name("韩莹")], [#age(40)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2762*], [#delta(-3)],
      [20], [#name("郑怡静")], [#age(31)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2759*], [#delta(-8)],
      [21], [#name("石川佳纯")], [#age(30)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2758*], [#delta(0)],
      [22], [#name("小盐遥菜")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2756*], [#delta(-4)],
      [23], [#name("安藤南")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2747*], [#delta(1)],
      [24], [#name("伊丽莎白 萨玛拉")], [#age(34)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2731*], [#delta(4)],
      [25], [#name("朱芊曦")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2729*], [#delta(-5)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("木原美悠")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2728*], [#delta(1)],
      [27], [#name("芝田沙季")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2709*], [#delta(-1)],
      [28], [#name("刘炜珊")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2708*], [#delta(-6)],
      [29], [#name("单晓娜")], [#age(40)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2707*], [#delta(3)],
      [30], [#name("长崎美柚")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2695*], [#delta(-5)],
      [31], [#name("梁夏银")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2682*], [#delta(3)],
      [32], [#name("金河英")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2679*], [#delta(-1)],
      [33], [#name("阿德里安娜 迪亚兹")], [#age(23)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2679*], [#delta(-4)],
      [34], [#name("玛妮卡 巴特拉")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2672*], [#delta(17)],
      [35], [#name("冯天薇")], [#age(37)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2671*], [#delta(0)],
      [36], [#name("徐奕")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2667*], [#delta(9)],
      [37], [#name("刘佳")], [#age(41)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2665*], [#delta(-1)],
      [38], [#name("田志希")], [#age(31)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2662*], [#delta(10)],
      [39], [#name("佐藤瞳")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2660*], [#delta(-2)],
      [40], [#name("徐孝元")], [#age(36)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2659*], [#delta(15)],
      [41], [#name("森樱")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2657*], [#delta(27)],
      [42], [#name("朱成竹")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2656*], [#delta(-4)],
      [43], [#name("陈熠")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2648*], [#delta(-13)],
      [44], [#name("王晓彤")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2632*], [#delta(-2)],
      [45], [#name("倪夏莲")], [#age(60)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2629*], [#delta(36)],
      [46], [#name("傅玉")], [#age(45)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2613*], [#delta(14)],
      [47], [#name("范姝涵")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2611*], [#delta(17)],
      [48], [#name("齐菲")], [#age(23)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2608*], [#delta(-1)],
      [49], [#name("覃予萱")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2608*], [#delta(-3)],
      [50], [#name("高桥 布鲁娜")], [#age(23)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2607*], [#delta(4)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("杨屹韵")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2604*], [#delta(-7)],
      [52], [#name("琳达 伯格斯特罗姆")], [#age(28)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2601*], [#delta(-11)],
      [53], [#name("郭雨涵")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2600*], [#delta(-10)],
      [54], [#name("崔孝珠")], [#age(25)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2597*], [#delta(3)],
      [55], [#name("吴洋晨")], [#age(21)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2590*], [#delta(8)],
      [56], [#name("曾尖")], [#age(27)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2589*], [#delta(-6)],
      [57], [#name("普利西卡 帕瓦德")], [#age(19)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2578*], [#delta(8)],
      [58], [#name("肖瑶茜")], [#age(29)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2575*], [#delta(15)],
      [59], [#name("李时温")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2575*], [#delta(-10)],
      [60], [#name("妮娜 米特兰姆")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2572*], [#delta(-27)],
      [61], [#name("奥拉万 帕拉南")], [#age(26)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2568*], [#delta(15)],
      [62], [#name("石洵瑶")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2566*], [#delta(0)],
      [63], [#name("笹尾明日香")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2558*], [#delta(7)],
      [64], [#name("纵歌曼")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2557*], [#delta(-3)],
      [65], [#name("韩菲儿")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2552*], [#delta(-13)],
      [66], [#name("LIU Hsing-Yin")], [#age(36)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2551*], [#delta(93)],
      [67], [#name("袁嘉楠")], [#age(38)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2544*], [#delta(-27)],
      [68], [#name("MADARASZ Dora")], [#age(30)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2541*], [#delta(38)],
      [69], [#name("苏萨西尼 萨维塔布特")], [#age(29)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2540*], [#delta(6)],
      [70], [#name("陈沂芊")], [#age(21)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2539*], [#delta(1)],
      [71], [#name("WAN Yuan")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2538*], [#delta(7)],
      [72], [#name("乔治娜 波塔")], [#age(38)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2536*], [#delta(0)],
      [73], [#name("SOO Wai Yam")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2535*], [#delta(1)],
      [74], [#name("DRAGOMAN Andreea")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2535*], [#delta(-18)],
      [75], [#name("HUANG Yi-Hua")], [#age(39)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2532*], [#delta(11)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("李雅可")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2531*], [#delta(-17)],
      [77], [#name("DIACONU Adina")], [#age(24)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2528*], [#delta(-11)],
      [78], [#name("李恩惠")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2527*], [#delta(-9)],
      [79], [#name("BAJOR Natalia")], [#age(26)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2521*], [#delta(94)],
      [80], [#name("萨比亚 温特")], [#age(31)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2516*], [#delta(-3)],
      [81], [#name("李昱谆")], [#age(26)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2508*], [#delta(-14)],
      [82], [#name("斯丽贾 阿库拉")], [#age(25)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2498*], [#delta(12)],
      [83], [#name("杜凯琹")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2497*], [#delta(0)],
      [84], [#name("刘杨子")], [#age(21)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2494*], [#delta(3)],
      [85], [#name("陈思羽")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2493*], [#delta(0)],
      [86], [#name("杨蕙菁")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2491*], [#delta(-6)],
      [87], [#name("BILENKO Tetyana")], [#age(40)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2490*], [#delta(1)],
      [88], [#name("LI Yuqi")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2489*], [#delta(1)],
      [89], [#name("蒂娜 梅谢芙")], [#age(29)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2487*], [#delta(1)],
      [90], [#name("HAPONOVA Hanna")], [#age(38)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2487*], [#delta(-11)],
      [91], [#name("LAY Jian Fang")], [#age(50)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2483*], [#delta(1)],
      [92], [#name("SCHREINER Franziska")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2482*], [#delta(35)],
      [93], [#name("CHASSELIN Pauline")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2481*], [#delta(-9)],
      [94], [#name("苏蒂尔塔 穆克吉")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2481*], [#delta(-3)],
      [95], [#name("BRATEYKO Solomiya")], [#age(24)], [#assoc("UKR")], [#left], [#shakehand], [#attack], [*2474*], [#delta(50)],
      [96], [#name("AKAE Kaho")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2472*], [#delta(0)],
      [97], [#name("邵杰妮")], [#age(29)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2470*], [#delta(19)],
      [98], [#name("ZARIF Audrey")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2466*], [#delta(1)],
      [99], [#name("YOON Hyobin")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2464*], [#delta(3)],
      [100], [#name("ZHANG Xiangyu")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2463*], [#delta(3)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("GUISNEL Oceane")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2462*], [#delta(0)],
      [102], [#name("PARTYKA Natalia")], [#age(34)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2460*], [#delta(2)],
      [103], [#name("CHITALE Diya")], [#age(20)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2456*], [#delta(4)],
      [104], [#name("SUGASAWA Yukari")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2450*], [#delta(8)],
      [105], [#name("PESOTSKA Margaryta")], [#age(32)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2448*], [#delta(-23)],
      [106], [#name("ZAHARIA Elena")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2446*], [#delta(31)],
      [107], [#name("KAMATH Archana")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2445*], [#delta(6)],
      [108], [#name("CIOBANU Irina")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2445*], [#delta(2)],
      [109], [#name("KIM Byeolnim")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2445*], [#delta(6)],
      [110], [#name("HURSEY Anna")], [#age(17)], [#assoc("WAL")], [#right], [#shakehand], [#attack], [*2444*], [#delta(15)],
      [111], [#name("MENDE Rin")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2443*], [#delta(13)],
      [112], [#name("安妮特 考夫曼")], [#age(17)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2441*], [#delta(-12)],
      [113], [#name("张安")], [#age(27)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2440*], [#delta(-16)],
      [114], [#name("ZANG Xiaotong")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2437*], [#delta(5)],
      [115], [#name("索菲亚 波尔卡诺娃")], [#age(29)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2436*], [#delta(-62)],
      [116], [#name("王 艾米")], [#age(21)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2436*], [#delta(10)],
      [117], [#name("LEE Daeun")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2435*], [#delta(-8)],
      [118], [#name("CHENG Pusyuan")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2433*], [#delta(-13)],
      [119], [#name("金娜英")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2432*], [#delta(-26)],
      [120], [#name("朱思冰")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2431*], [#delta(84)],
      [121], [#name("张墨")], [#age(34)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2430*], [#delta(0)],
      [122], [#name("汉娜 高达")], [#age(16)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2427*], [#delta(-11)],
      [123], [#name("吴咏琳")], [#age(20)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2426*], [#delta(63)],
      [124], [#name("MALOBABIC Ivana")], [#age(43)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2425*], [#delta(7)],
      [125], [#name("RAKOVAC Lea")], [#age(27)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2425*], [#delta(29)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("LENG Yutong")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2424*], [#delta(-4)],
      [127], [#name("JEE Minhyung")], [#age(36)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2424*], [#delta(-4)],
      [128], [#name("OJIO Yuna")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2424*], [#delta(0)],
      [129], [#name("LAM Yee Lok")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2424*], [#delta(9)],
      [130], [#name("KUKULKOVA Tatiana")], [#age(23)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2421*], [#delta(-72)],
      [131], [#name("艾希卡 穆克吉")], [#age(26)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2420*], [#delta(-33)],
      [132], [#name("SU Pei-Ling")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2416*], [#delta(-3)],
      [133], [#name("LEE Seungeun")], [#age(16)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2415*], [#delta(-3)],
      [134], [#name("CHANG Li Sian Alice")], [#age(23)], [#assoc("MAS")], [#right], [#shakehand], [#defense], [*2414*], [#delta(-1)],
      [135], [#name("CHEN Ying-Chen")], [#age(24)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2413*], [#delta(42)],
      [136], [#name("WANG Tianyi")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2412*], [#delta(-1)],
      [137], [#name("PICCOLIN Giorgia")], [#age(27)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2412*], [#delta(-42)],
      [138], [#name("SURJAN Sabina")], [#age(23)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2410*], [#delta(-24)],
      [139], [#name("SAWETTABUT Jinnipa")], [#age(23)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2408*], [#delta(10)],
      [140], [#name("LUTZ Camille")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2402*], [#delta(-22)],
      [141], [#name("CHENG Hsien-Tzu")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2402*], [#delta(29)],
      [142], [#name("LOEUILLETTE Stephanie")], [#age(31)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2401*], [#delta(-1)],
      [143], [#name("布里特 伊尔兰德")], [#age(29)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2398*], [#delta(-4)],
      [144], [#name("SINGEORZAN Ioana")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2397*], [#delta(16)],
      [145], [#name("BERGAND Filippa")], [#age(24)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2396*], [#delta(86)],
      [146], [#name("GHORPADE Yashaswini")], [#age(19)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2394*], [#delta(1)],
      [147], [#name("LUTZ Charlotte")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2392*], [#delta(-39)],
      [148], [#name("KIM Seongjin")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2391*], [#delta(-8)],
      [149], [#name("MANTZ Chantal")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2390*], [#delta(-1)],
      [150], [#name("WEGRZYN Anna")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2387*], [#delta(58)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("MATELOVA Hana")], [#age(33)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2385*], [#delta(-15)],
      [152], [#name("MIGOT Marie")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2384*], [#delta(-2)],
      [153], [#name("PARK Gahyeon")], [#age(16)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2383*], [#delta(-2)],
      [154], [#name("SUNG Rachel")], [#age(19)], [#assoc("USA")], [#left], [#shakehand], [#attack], [*2382*], [#delta(4)],
      [155], [#name("KUMAHARA Luca")], [#age(28)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2380*], [#delta(-2)],
      [156], [#name("GHOSH Swastika")], [#age(20)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2377*], [#delta(11)],
      [157], [#name("MOYLAND Sally")], [#age(16)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2377*], [#delta(4)],
      [158], [#name("WIELGOS Zuzanna")], [#age(18)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2376*], [#delta(10)],
      [159], [#name("HUANG Yu-Jie")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2376*], [#delta(-3)],
      [160], [#name("ARAPOVIC Hana")], [#age(19)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2376*], [#delta(33)],
      [161], [#name("SOLJA Amelie")], [#age(33)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2373*], [#delta(-44)],
      [162], [#name("RYU Hanna")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2372*], [#delta(-28)],
      [163], [#name("NAGYVARADI Mercedes")], [#age(29)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2368*], [#delta(20)],
      [164], [#name("克里斯蒂娜 卡尔伯格")], [#age(23)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2368*], [#delta(8)],
      [165], [#name("AOKI Sachi")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2368*], [#delta(34)],
      [166], [#name("WANG Yi-Ju")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2367*], [NEW],
      [167], [#name("HO Tin-Tin")], [#age(25)], [#assoc("ENG")], [#right], [#penhold], [#attack], [*2362*], [#delta(-24)],
      [168], [#name("STEFANOVA Nikoleta")], [#age(39)], [#assoc("ITA")], [#left], [#shakehand], [#attack], [*2362*], [#delta(-5)],
      [169], [#name("LEE Daeun")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2361*], [#delta(-5)],
      [170], [#name("ZHANG Wenjing")], [#age(24)], [#assoc("HKG")], [#right], [#shakehand], [#defense], [*2361*], [#delta(-4)],
      [171], [#name("WONG Xin Ru")], [#age(22)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2360*], [#delta(-19)],
      [172], [#name("HUANG Hsin")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2358*], [#delta(-26)],
      [173], [#name("HUANG Yu-Wen")], [#age(27)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2355*], [#delta(-18)],
      [174], [#name("李皓晴")], [#age(31)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2352*], [#delta(-3)],
      [175], [#name("MONFARDINI Gaia")], [#age(22)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2350*], [#delta(-43)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("DE NUTTE Sarah")], [#age(31)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2349*], [#delta(-56)],
      [177], [#name("BALAZOVA Barbora")], [#age(31)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2348*], [#delta(-35)],
      [178], [#name("DING Yijie")], [#age(15)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2348*], [#delta(-2)],
      [179], [#name("LYNE Karen")], [#age(21)], [#assoc("MAS")], [#left], [#shakehand], [#attack], [*2347*], [#delta(-4)],
      [180], [#name("LUPULESKU Izabela")], [#age(24)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2344*], [#delta(48)],
      [181], [#name("BALINT Bernadett")], [#age(27)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2344*], [#delta(56)],
      [182], [#name("LI Ching Wan")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2342*], [#delta(-38)],
      [183], [#name("LEE Hoi Man")], [#age(20)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2339*], [#delta(9)],
      [184], [#name("YAN Yutong")], [#age(15)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2336*], [#delta(28)],
      [185], [#name("TOLIOU Aikaterini")], [#age(28)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2333*], [#delta(-20)],
      [186], [#name("VIGNJEVIC Dragana")], [#age(24)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2326*], [#delta(-24)],
      [187], [#name("ZHANG Sofia-Xuan")], [#age(24)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2321*], [#delta(-8)],
      [188], [#name("KLEE Sophia")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2321*], [#delta(22)],
      [189], [#name("WANG Yiduo")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2321*], [#delta(-8)],
      [190], [#name("ZHOU Jingyi")], [#age(18)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2317*], [#delta(-8)],
      [191], [#name("WEGRZYN Katarzyna")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2317*], [#delta(-34)],
      [192], [#name("KHETKHUAN Tamolwan")], [#age(26)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2316*], [#delta(-7)],
      [193], [#name("YEH Yi-Tian")], [#age(16)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2314*], [#delta(-24)],
      [194], [#name("GRIESEL Mia")], [#age(17)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2313*], [#delta(35)],
      [195], [#name("MOSTAFAVI Leili")], [#age(23)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2311*], [#delta(-6)],
      [196], [#name("FONSECA Daniela")], [#age(21)], [#assoc("CUB")], [#left], [#shakehand], [#attack], [*2310*], [#delta(-5)],
      [197], [#name("RILISKYTE Kornelija")], [#age(20)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2310*], [#delta(38)],
      [198], [#name("PLAIAN Tania")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2309*], [#delta(-24)],
      [199], [#name("LAVROVA Anastassiya")], [#age(28)], [#assoc("KAZ")], [#right], [#shakehand], [#attack], [*2309*], [#delta(92)],
      [200], [#name("ALHODABY Mariam")], [#age(23)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2305*], [#delta(-6)],
    )
  )
