#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("孙颖莎")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3148*], [#delta(0)],
      [2], [#name("陈梦")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3060*], [#delta(0)],
      [3], [#name("陈幸同")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2982*], [#delta(0)],
      [4], [#name("王艺迪")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2960*], [#delta(0)],
      [5], [#name("早田希娜")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2926*], [#delta(0)],
      [6], [#name("平野美宇")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2924*], [#delta(7)],
      [7], [#name("王曼昱")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2916*], [#delta(-1)],
      [8], [#name("何卓佳")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2875*], [#delta(-1)],
      [9], [#name("伊藤美诚")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2861*], [#delta(0)],
      [10], [#name("桥本帆乃香")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2825*], [#delta(1)],
      [11], [#name("钱天一")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2825*], [#delta(-3)],
      [12], [#name("伯纳黛特 斯佐科斯")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2812*], [#delta(24)],
      [13], [#name("申裕斌")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2806*], [#delta(6)],
      [14], [#name("蒯曼")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2805*], [#delta(1)],
      [15], [#name("张瑞")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2800*], [#delta(-1)],
      [16], [#name("杨晓欣")], [#age(35)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2800*], [#delta(6)],
      [17], [#name("范思琦")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2788*], [#delta(0)],
      [18], [#name("张本美和")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2785*], [#delta(-8)],
      [19], [#name("韩莹")], [#age(40)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2761*], [#delta(-1)],
      [20], [#name("小盐遥菜")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2760*], [#delta(-4)],
      [21], [#name("郑怡静")], [#age(31)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2760*], [#delta(-9)],
      [22], [#name("伊丽莎白 萨玛拉")], [#age(34)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2731*], [#delta(4)],
      [23], [#name("木原美悠")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2729*], [#delta(2)],
      [24], [#name("朱芊曦")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2728*], [#delta(-4)],
      [25], [#name("刘炜珊")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2710*], [#delta(-4)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("芝田沙季")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2710*], [#delta(-2)],
      [27], [#name("单晓娜")], [#age(40)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2706*], [#delta(3)],
      [28], [#name("长崎美柚")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2695*], [#delta(-5)],
      [29], [#name("金河英")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2681*], [#delta(0)],
      [30], [#name("阿德里安娜 迪亚兹")], [#age(23)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2680*], [#delta(-3)],
      [31], [#name("梁夏银")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2679*], [#delta(1)],
      [32], [#name("玛妮卡 巴特拉")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2673*], [#delta(17)],
      [33], [#name("徐奕")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2670*], [#delta(8)],
      [34], [#name("刘佳")], [#age(41)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2665*], [#delta(-1)],
      [35], [#name("田志希")], [#age(31)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2662*], [#delta(10)],
      [36], [#name("佐藤瞳")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2660*], [#delta(-2)],
      [37], [#name("徐孝元")], [#age(36)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2659*], [#delta(16)],
      [38], [#name("森樱")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2657*], [#delta(24)],
      [39], [#name("朱成竹")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2655*], [#delta(-4)],
      [40], [#name("陈熠")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2649*], [#delta(-12)],
      [41], [#name("王晓彤")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2633*], [#delta(-2)],
      [42], [#name("倪夏莲")], [#age(60)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2630*], [#delta(37)],
      [43], [#name("傅玉")], [#age(45)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2613*], [#delta(12)],
      [44], [#name("范姝涵")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2611*], [#delta(16)],
      [45], [#name("高桥 布鲁娜")], [#age(23)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2608*], [#delta(7)],
      [46], [#name("覃予萱")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2607*], [#delta(-3)],
      [47], [#name("齐菲")], [#age(23)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2606*], [#delta(-3)],
      [48], [#name("石洵瑶")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2604*], [#delta(-2)],
      [49], [#name("杨屹韵")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2602*], [#delta(-7)],
      [50], [#name("琳达 伯格斯特隆")], [#age(28)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2601*], [#delta(-12)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("崔孝珠")], [#age(25)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2597*], [#delta(3)],
      [52], [#name("曾尖")], [#age(27)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2589*], [#delta(-4)],
      [53], [#name("吴洋晨")], [#age(21)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2589*], [#delta(6)],
      [54], [#name("普利西卡 帕瓦德")], [#age(19)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2578*], [#delta(7)],
      [55], [#name("肖瑶茜")], [#age(29)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2576*], [#delta(15)],
      [56], [#name("李时温")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2574*], [#delta(-9)],
      [57], [#name("妮娜 米特兰姆")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2573*], [#delta(-26)],
      [58], [#name("LIU Hsing-Yin")], [#age(36)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2563*], [#delta(88)],
      [59], [#name("笹尾明日香")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2558*], [#delta(8)],
      [60], [#name("李昱谆")], [#age(26)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2557*], [#delta(4)],
      [61], [#name("纵歌曼")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2557*], [#delta(-3)],
      [62], [#name("韩菲儿")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2552*], [#delta(-12)],
      [63], [#name("袁嘉楠")], [#age(38)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2545*], [#delta(-26)],
      [64], [#name("SOO Wai Yam")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2543*], [#delta(4)],
      [65], [#name("MADARASZ Dora")], [#age(30)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2541*], [#delta(36)],
      [66], [#name("苏萨西尼 萨维塔布特")], [#age(29)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2541*], [#delta(6)],
      [67], [#name("乔治娜 波塔")], [#age(38)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2538*], [#delta(2)],
      [68], [#name("万远")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2537*], [#delta(6)],
      [69], [#name("陈沂芊")], [#age(21)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2536*], [#delta(2)],
      [70], [#name("HUANG Yi-Hua")], [#age(39)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2532*], [#delta(12)],
      [71], [#name("李雅可")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2530*], [#delta(-14)],
      [72], [#name("DIACONU Adina")], [#age(24)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2529*], [#delta(-9)],
      [73], [#name("奥拉万 帕拉南")], [#age(26)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2527*], [#delta(0)],
      [74], [#name("李恩惠")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2527*], [#delta(-9)],
      [75], [#name("BAJOR Natalia")], [#age(26)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2521*], [#delta(87)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("DRAGOMAN Andreea")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2517*], [#delta(-10)],
      [77], [#name("萨比亚 温特")], [#age(31)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2508*], [#delta(-1)],
      [78], [#name("杜凯琹")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2501*], [#delta(-1)],
      [79], [#name("斯丽贾 阿库拉")], [#age(25)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2498*], [#delta(11)],
      [80], [#name("刘杨子")], [#age(21)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2498*], [#delta(3)],
      [81], [#name("陈思羽")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2490*], [#delta(3)],
      [82], [#name("杨蕙菁")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2487*], [#delta(-4)],
      [83], [#name("HAPONOVA Hanna")], [#age(38)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2487*], [#delta(-8)],
      [84], [#name("蒂娜 梅谢芙")], [#age(29)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2486*], [#delta(1)],
      [85], [#name("布里特 伊尔兰德")], [#age(29)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2483*], [#delta(2)],
      [86], [#name("LAY Jian Fang")], [#age(50)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2482*], [#delta(2)],
      [87], [#name("CHASSELIN Pauline")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2480*], [#delta(-6)],
      [88], [#name("SCHREINER Franziska")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2480*], [#delta(37)],
      [89], [#name("苏蒂尔塔 穆克吉")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2479*], [#delta(0)],
      [90], [#name("BRATEYKO Solomiya")], [#age(24)], [#assoc("UKR")], [#left], [#shakehand], [#attack], [*2479*], [#delta(49)],
      [91], [#name("赤江夏星")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2473*], [#delta(1)],
      [92], [#name("邵杰妮")], [#age(29)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2470*], [#delta(18)],
      [93], [#name("ZARIF Audrey")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2464*], [#delta(4)],
      [94], [#name("YOON Hyobin")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2463*], [#delta(4)],
      [95], [#name("张翔宇")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2462*], [#delta(4)],
      [96], [#name("GUISNEL Oceane")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2462*], [#delta(0)],
      [97], [#name("CHITALE Diya")], [#age(20)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2454*], [#delta(7)],
      [98], [#name("PESOTSKA Margaryta")], [#age(32)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2448*], [#delta(-18)],
      [99], [#name("安妮特 考夫曼")], [#age(17)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2448*], [#delta(-5)],
      [100], [#name("KAMATH Archana")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2445*], [#delta(7)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("KIM Byeolnim")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2445*], [#delta(8)],
      [102], [#name("ZAHARIA Elena")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2443*], [#delta(28)],
      [103], [#name("CIOBANU Irina")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2442*], [#delta(2)],
      [104], [#name("安娜 赫西")], [#age(17)], [#assoc("WAL")], [#right], [#shakehand], [#attack], [*2442*], [#delta(14)],
      [105], [#name("张安")], [#age(27)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2441*], [#delta(-12)],
      [106], [#name("面手凛")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2440*], [#delta(10)],
      [107], [#name("王 艾米")], [#age(21)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2436*], [#delta(10)],
      [108], [#name("索菲亚 波尔卡诺娃")], [#age(29)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2436*], [#delta(-57)],
      [109], [#name("李多恩")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2434*], [#delta(-6)],
      [110], [#name("金娜英")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2432*], [#delta(-24)],
      [111], [#name("CHENG Pusyuan")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2432*], [#delta(-9)],
      [112], [#name("朱思冰")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2432*], [#delta(76)],
      [113], [#name("张墨")], [#age(34)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2431*], [#delta(0)],
      [114], [#name("JEE Minhyung")], [#age(36)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2428*], [#delta(0)],
      [115], [#name("汉娜 高达")], [#age(16)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2426*], [#delta(-9)],
      [116], [#name("MALOBABIC Ivana")], [#age(43)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2426*], [#delta(4)],
      [117], [#name("莱娅 拉科瓦奇")], [#age(27)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2425*], [#delta(26)],
      [118], [#name("吴咏琳")], [#age(20)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2425*], [#delta(56)],
      [119], [#name("LAM Yee Lok")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2424*], [#delta(14)],
      [120], [#name("KUKULKOVA Tatiana")], [#age(23)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2421*], [#delta(-64)],
      [121], [#name("小盐悠菜")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2420*], [#delta(0)],
      [122], [#name("艾希卡 穆克吉")], [#age(26)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2419*], [#delta(-27)],
      [123], [#name("SU Pei-Ling")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2417*], [#delta(-4)],
      [124], [#name("LEE Seungeun")], [#age(16)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2414*], [#delta(-2)],
      [125], [#name("CHANG Li Sian Alice")], [#age(23)], [#assoc("MAS")], [#right], [#shakehand], [#defense], [*2414*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("王添艺")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2412*], [#delta(0)],
      [127], [#name("CHEN Ying-Chen")], [#age(24)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2412*], [#delta(36)],
      [128], [#name("PICCOLIN Giorgia")], [#age(27)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2412*], [#delta(-37)],
      [129], [#name("GHORPADE Yashaswini")], [#age(19)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2411*], [#delta(0)],
      [130], [#name("SURJAN Sabina")], [#age(23)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2409*], [#delta(-22)],
      [131], [#name("SAWETTABUT Jinnipa")], [#age(23)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2406*], [#delta(11)],
      [132], [#name("LOEUILLETTE Stephanie")], [#age(31)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2404*], [#delta(0)],
      [133], [#name("LUTZ Camille")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2403*], [#delta(-22)],
      [134], [#name("CHENG Hsien-Tzu")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2401*], [#delta(24)],
      [135], [#name("MANTZ Chantal")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2400*], [#delta(-4)],
      [136], [#name("SINGEORZAN Ioana")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2394*], [#delta(15)],
      [137], [#name("LUTZ Charlotte")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2394*], [#delta(-37)],
      [138], [#name("BERGAND Filippa")], [#age(24)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2392*], [#delta(78)],
      [139], [#name("KIM Seongjin")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2390*], [#delta(-5)],
      [140], [#name("汉娜 马特洛娃")], [#age(33)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2386*], [#delta(-12)],
      [141], [#name("WEGRZYN Anna")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2386*], [#delta(53)],
      [142], [#name("朴佳贤")], [#age(16)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2386*], [#delta(-2)],
      [143], [#name("SUNG Rachel")], [#age(19)], [#assoc("USA")], [#left], [#shakehand], [#attack], [*2381*], [#delta(5)],
      [144], [#name("HUANG Yu-Jie")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2377*], [#delta(1)],
      [145], [#name("GHOSH Swastika")], [#age(20)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2376*], [#delta(8)],
      [146], [#name("MOYLAND Sally")], [#age(16)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2375*], [#delta(3)],
      [147], [#name("WIELGOS Zuzanna")], [#age(18)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2373*], [#delta(8)],
      [148], [#name("ARAPOVIC Hana")], [#age(19)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2373*], [#delta(31)],
      [149], [#name("柳韩娜")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2372*], [#delta(-26)],
      [150], [#name("NAGYVARADI Mercedes")], [#age(29)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2369*], [#delta(21)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("克里斯蒂娜 卡尔伯格")], [#age(23)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2369*], [#delta(8)],
      [152], [#name("WANG Yi-Ju")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2366*], [NEW],
      [153], [#name("青木咲智")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2365*], [#delta(33)],
      [154], [#name("SOLJA Amelie")], [#age(33)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2363*], [#delta(-39)],
      [155], [#name("HO Tin-Tin")], [#age(25)], [#assoc("ENG")], [#right], [#penhold], [#attack], [*2362*], [#delta(-18)],
      [156], [#name("WONG Xin Ru")], [#age(22)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2361*], [#delta(-15)],
      [157], [#name("HUANG Hsin")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2358*], [#delta(-19)],
      [158], [#name("李多恩")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2357*], [#delta(-4)],
      [159], [#name("STEFANOVA Nikoleta")], [#age(39)], [#assoc("ITA")], [#left], [#shakehand], [#attack], [*2357*], [#delta(-3)],
      [160], [#name("HUANG Yu-Wen")], [#age(27)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2354*], [#delta(-16)],
      [161], [#name("李皓晴")], [#age(31)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2353*], [#delta(-4)],
      [162], [#name("DE NUTTE Sarah")], [#age(31)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2349*], [#delta(-50)],
      [163], [#name("BALAZOVA Barbora")], [#age(31)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2348*], [#delta(-27)],
      [164], [#name("MONFARDINI Gaia")], [#age(22)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2346*], [#delta(-37)],
      [165], [#name("LYNE Karen")], [#age(21)], [#assoc("MAS")], [#left], [#shakehand], [#attack], [*2346*], [#delta(-4)],
      [166], [#name("LI Ching Wan")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2344*], [#delta(-31)],
      [167], [#name("丁怡婕")], [#age(15)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2343*], [#delta(-2)],
      [168], [#name("BALINT Bernadett")], [#age(27)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2342*], [#delta(51)],
      [169], [#name("KHETKHUAN Tamolwan")], [#age(26)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2338*], [#delta(-3)],
      [170], [#name("LUPULESKU Izabela")], [#age(24)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2338*], [#delta(39)],
      [171], [#name("LEE Hoi Man")], [#age(20)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2334*], [#delta(9)],
      [172], [#name("YAN Yutong")], [#age(15)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2333*], [#delta(27)],
      [173], [#name("TOLIOU Aikaterini")], [#age(28)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2332*], [#delta(-21)],
      [174], [#name("VIGNJEVIC Dragana")], [#age(24)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2324*], [#delta(-24)],
      [175], [#name("ZHANG Sofia-Xuan")], [#age(24)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2320*], [#delta(-7)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("KLEE Sophia")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2320*], [#delta(19)],
      [177], [#name("WEGRZYN Katarzyna")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2317*], [#delta(-30)],
      [178], [#name("ZHOU Jingyi")], [#age(18)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2316*], [#delta(-9)],
      [179], [#name("GRIESEL Mia")], [#age(17)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2311*], [#delta(31)],
      [180], [#name("LAVROVA Anastassiya")], [#age(28)], [#assoc("KAZ")], [#right], [#shakehand], [#attack], [*2310*], [#delta(81)],
      [181], [#name("FONSECA Daniela")], [#age(21)], [#assoc("CUB")], [#left], [#shakehand], [#attack], [*2310*], [#delta(-4)],
      [182], [#name("PLAIAN Tania")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2308*], [#delta(-22)],
      [183], [#name("RILISKYTE Kornelija")], [#age(20)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2304*], [#delta(35)],
      [184], [#name("MEI-ROSU Bianca")], [#age(16)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2303*], [#delta(23)],
      [185], [#name("DYMYTRENKO Anastasiya")], [#age(21)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2301*], [#delta(-9)],
      [186], [#name("WONG Hoi Tung")], [#age(18)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2300*], [#delta(-16)],
      [187], [#name("ALHODABY Mariam")], [#age(23)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2298*], [#delta(-5)],
      [188], [#name("SAINI Suhana")], [#age(17)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2297*], [#delta(-1)],
      [189], [#name("TAKAHASHI Giulia")], [#age(18)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2295*], [#delta(15)],
      [190], [#name("朱梓予")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2293*], [#delta(-6)],
      [191], [#name("XIANG Junlin")], [#age(16)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2293*], [#delta(-6)],
      [192], [#name("叶伊恬")], [#age(16)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2292*], [#delta(-25)],
      [193], [#name("JEGER Mateja")], [#age(28)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2292*], [#delta(13)],
      [194], [#name("ALTINKAYA Sibel")], [#age(30)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2292*], [#delta(-4)],
      [195], [#name("TODOROVIC Andrea")], [#age(31)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2291*], [#delta(-22)],
      [196], [#name("CHEN Chi-Shiuan")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2288*], [#delta(-18)],
      [197], [#name("YAMADA Jessica")], [#age(34)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2287*], [#delta(-8)],
      [198], [#name("BLASKOVA Zdena")], [#age(22)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2286*], [#delta(-34)],
      [199], [#name("TEE Ai Xin")], [#age(22)], [#assoc("MAS")], [#right], [#penhold], [#attack], [*2284*], [#delta(-8)],
      [200], [#name("GOI Rui Xuan")], [#age(22)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2283*], [#delta(44)],
    )
  )
