#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("孙颖莎")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3143*], [#delta(0)],
      [2], [#name("陈梦")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3060*], [#delta(0)],
      [3], [#name("陈幸同")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2979*], [#delta(2)],
      [4], [#name("王艺迪")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2960*], [#delta(0)],
      [5], [#name("早田希娜")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2919*], [#delta(6)],
      [6], [#name("王曼昱")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2903*], [#delta(-3)],
      [7], [#name("何卓佳")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2887*], [#delta(-1)],
      [8], [#name("钱天一")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2861*], [#delta(-1)],
      [9], [#name("伊藤美诚")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2846*], [#delta(0)],
      [10], [#name("桥本帆乃香")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2825*], [#delta(-2)],
      [11], [#name("平野美宇")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2825*], [#delta(-1)],
      [12], [#name("郑怡静")], [#age(31)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2819*], [#delta(5)],
      [13], [#name("张瑞")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2798*], [#delta(-1)],
      [14], [#name("蒯曼")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2792*], [#delta(-1)],
      [15], [#name("张本美和")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2788*], [#delta(-1)],
      [16], [#name("韩莹")], [#age(40)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2788*], [#delta(5)],
      [17], [#name("范思琦")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2786*], [#delta(-2)],
      [18], [#name("小盐遥菜")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2783*], [#delta(-2)],
      [19], [#name("朱芊曦")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2766*], [#delta(0)],
      [20], [#name("申裕斌")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2760*], [#delta(5)],
      [21], [#name("石川佳纯")], [#age(30)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2758*], [#delta(-1)],
      [22], [#name("刘炜珊")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2750*], [#delta(0)],
      [23], [#name("杨晓欣")], [#age(35)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2750*], [#delta(0)],
      [24], [#name("安藤南")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2747*], [#delta(0)],
      [25], [#name("芝田沙季")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2709*], [#delta(2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("木原美悠")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2706*], [#delta(10)],
      [27], [#name("长崎美柚")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2702*], [#delta(-9)],
      [28], [#name("伊丽莎白 萨玛拉")], [#age(34)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2700*], [#delta(11)],
      [29], [#name("朱成竹")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2697*], [#delta(11)],
      [30], [#name("阿德里安娜 迪亚兹")], [#age(23)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2686*], [#delta(-2)],
      [31], [#name("陈熠")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2685*], [#delta(-2)],
      [32], [#name("金河英")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2679*], [#delta(-2)],
      [33], [#name("单晓娜")], [#age(40)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2677*], [#delta(-1)],
      [34], [#name("妮娜 米特兰姆")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2676*], [#delta(17)],
      [35], [#name("冯天薇")], [#age(37)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2671*], [#delta(-4)],
      [36], [#name("梁夏银")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2665*], [#delta(-3)],
      [37], [#name("刘佳")], [#age(41)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2660*], [#delta(-3)],
      [38], [#name("佐藤瞳")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2660*], [#delta(-3)],
      [39], [#name("李时温")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2647*], [#delta(19)],
      [40], [#name("徐孝元")], [#age(36)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2646*], [#delta(28)],
      [41], [#name("伯纳黛特 斯佐科斯")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2643*], [#delta(-15)],
      [42], [#name("田志希")], [#age(31)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2642*], [#delta(13)],
      [43], [#name("袁嘉楠")], [#age(38)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2636*], [#delta(-5)],
      [44], [#name("琳达 伯格斯特罗姆")], [#age(28)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2631*], [#delta(-2)],
      [45], [#name("徐奕")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2621*], [#delta(1)],
      [46], [#name("覃予萱")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2621*], [#delta(1)],
      [47], [#name("齐菲")], [#age(23)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2614*], [#delta(1)],
      [48], [#name("玛妮卡 巴特拉")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2609*], [#delta(-4)],
      [49], [#name("李恩惠")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2602*], [#delta(3)],
      [50], [#name("曾尖")], [#age(27)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2596*], [#delta(-13)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("韩菲儿")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2585*], [#delta(5)],
      [52], [#name("索菲亚 波尔卡诺娃")], [#age(29)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2585*], [#delta(-11)],
      [53], [#name("李昱谆")], [#age(26)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2580*], [#delta(4)],
      [54], [#name("DRAGOMAN Andreea")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2572*], [#delta(47)],
      [55], [#name("崔孝珠")], [#age(25)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2570*], [#delta(-12)],
      [56], [#name("KUKULKOVA Tatiana")], [#age(23)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2569*], [#delta(137)],
      [57], [#name("傅玉")], [#age(45)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2567*], [#delta(7)],
      [58], [#name("纵歌曼")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2565*], [#delta(2)],
      [59], [#name("石洵瑶")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2564*], [#delta(2)],
      [60], [#name("吴洋晨")], [#age(21)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2564*], [#delta(2)],
      [61], [#name("范姝涵")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2561*], [#delta(2)],
      [62], [#name("DIACONU Adina")], [#age(24)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2558*], [#delta(17)],
      [63], [#name("森樱")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2556*], [#delta(2)],
      [64], [#name("笹尾明日香")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2553*], [#delta(2)],
      [65], [#name("HUANG Yi-Hua")], [#age(39)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2541*], [#delta(5)],
      [66], [#name("苏蒂尔塔 穆克吉")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2541*], [#delta(-13)],
      [67], [#name("陈沂芊")], [#age(21)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2539*], [#delta(4)],
      [68], [#name("乔治娜 波塔")], [#age(38)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2536*], [#delta(69)],
      [69], [#name("肖瑶茜")], [#age(29)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2536*], [#delta(20)],
      [70], [#name("SOO Wai Yam")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2535*], [#delta(3)],
      [71], [#name("苏萨西尼 萨维塔布特")], [#age(29)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2529*], [#delta(-26)],
      [72], [#name("WAN Yuan")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2528*], [#delta(3)],
      [73], [#name("萨比亚 温特")], [#age(31)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2527*], [#delta(-14)],
      [74], [#name("奥拉万 帕拉南")], [#age(26)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2522*], [#delta(12)],
      [75], [#name("斯丽贾 阿库拉")], [#age(25)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2517*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("HAPONOVA Hanna")], [#age(38)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2513*], [#delta(126)],
      [77], [#name("杨蕙菁")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2511*], [#delta(1)],
      [78], [#name("蒂娜 梅谢芙")], [#age(29)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2508*], [#delta(33)],
      [79], [#name("倪夏莲")], [#age(60)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2507*], [#delta(-2)],
      [80], [#name("PESOTSKA Margaryta")], [#age(32)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2506*], [#delta(-26)],
      [81], [#name("杜凯琹")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2504*], [#delta(-31)],
      [82], [#name("普利西卡 帕瓦德")], [#age(19)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2501*], [#delta(-13)],
      [83], [#name("刘杨子")], [#age(21)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2494*], [#delta(-3)],
      [84], [#name("BILENKO Tetyana")], [#age(40)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2490*], [#delta(-1)],
      [85], [#name("ZARIF Audrey")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2489*], [#delta(51)],
      [86], [#name("LI Yuqi")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2489*], [#delta(-2)],
      [87], [#name("GUISNEL Oceane")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2486*], [#delta(0)],
      [88], [#name("LAY Jian Fang")], [#age(50)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2483*], [#delta(0)],
      [89], [#name("PICCOLIN Giorgia")], [#age(27)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2476*], [#delta(61)],
      [90], [#name("AKAE Kaho")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2472*], [#delta(1)],
      [91], [#name("张安")], [#age(27)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2472*], [#delta(-42)],
      [92], [#name("DE NUTTE Sarah")], [#age(31)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2465*], [#delta(0)],
      [93], [#name("安妮特 考夫曼")], [#age(17)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2464*], [#delta(0)],
      [94], [#name("ZHANG Xiangyu")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2463*], [#delta(0)],
      [95], [#name("PARTYKA Natalia")], [#age(34)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2460*], [#delta(0)],
      [96], [#name("LUTZ Camille")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2459*], [#delta(11)],
      [97], [#name("CHENG Pusyuan")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2458*], [#delta(-1)],
      [98], [#name("MADARASZ Dora")], [#age(30)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2457*], [#delta(-8)],
      [99], [#name("LEE Daeun")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2456*], [#delta(-2)],
      [100], [#name("CIOBANU Irina")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2455*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("SUGASAWA Yukari")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2450*], [#delta(-2)],
      [102], [#name("YOON Hyobin")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2449*], [#delta(-2)],
      [103], [#name("高桥 布鲁娜")], [#age(23)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2449*], [#delta(-22)],
      [104], [#name("艾希卡 穆克吉")], [#age(26)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2446*], [#delta(-2)],
      [105], [#name("SURJAN Sabina")], [#age(23)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2445*], [#delta(-20)],
      [106], [#name("KIM Byeolnim")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2445*], [#delta(-2)],
      [107], [#name("邵杰妮")], [#age(29)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2442*], [#delta(-35)],
      [108], [#name("CHASSELIN Pauline")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2441*], [#delta(-2)],
      [109], [#name("LUTZ Charlotte")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2440*], [#delta(24)],
      [110], [#name("SOLJA Amelie")], [#age(33)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2439*], [#delta(28)],
      [111], [#name("SCHREINER Franziska")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2434*], [#delta(-1)],
      [112], [#name("张墨")], [#age(34)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2430*], [#delta(-9)],
      [113], [#name("CHITALE Diya")], [#age(20)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2429*], [#delta(-1)],
      [114], [#name("王 艾米")], [#age(21)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2428*], [#delta(-40)],
      [115], [#name("金娜英")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2427*], [#delta(-2)],
      [116], [#name("HURSEY Anna")], [#age(17)], [#assoc("WAL")], [#right], [#shakehand], [#attack], [*2425*], [#delta(-2)],
      [117], [#name("HUANG Yu-Wen")], [#age(27)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2425*], [#delta(-12)],
      [118], [#name("LIU Hsing-Yin")], [#age(36)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2424*], [#delta(-3)],
      [119], [#name("LENG Yutong")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2424*], [#delta(-3)],
      [120], [#name("JEE Minhyung")], [#age(36)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2424*], [#delta(-3)],
      [121], [#name("MENDE Rin")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2423*], [#delta(42)],
      [122], [#name("ZANG Xiaotong")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2417*], [#delta(-2)],
      [123], [#name("SU Pei-Ling")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2416*], [#delta(-2)],
      [124], [#name("LOEUILLETTE Stephanie")], [#age(31)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2416*], [#delta(-2)],
      [125], [#name("MALOBABIC Ivana")], [#age(43)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2414*], [#delta(24)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("MONFARDINI Gaia")], [#age(22)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2414*], [#delta(44)],
      [127], [#name("CHANG Li Sian Alice")], [#age(23)], [#assoc("MAS")], [#right], [#shakehand], [#defense], [*2414*], [#delta(-4)],
      [128], [#name("陈思羽")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2414*], [#delta(-61)],
      [129], [#name("WANG Tianyi")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2412*], [#delta(-4)],
      [130], [#name("汉娜 高达")], [#age(16)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2407*], [#delta(-21)],
      [131], [#name("MATELOVA Hana")], [#age(33)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2406*], [#delta(9)],
      [132], [#name("ZAHARIA Elena")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2405*], [#delta(-14)],
      [133], [#name("HO Tin-Tin")], [#age(25)], [#assoc("ENG")], [#right], [#penhold], [#attack], [*2404*], [#delta(-9)],
      [134], [#name("LEE Seungeun")], [#age(16)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2404*], [#delta(-6)],
      [135], [#name("LAM Yee Lok")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2404*], [#delta(-53)],
      [136], [#name("GHORPADE Yashaswini")], [#age(19)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2398*], [#delta(-6)],
      [137], [#name("布里特 伊尔兰德")], [#age(29)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2398*], [#delta(-6)],
      [138], [#name("KIM Seongjin")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2397*], [#delta(-6)],
      [139], [#name("MANTZ Chantal")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2397*], [#delta(-5)],
      [140], [#name("BRATEYKO Solomiya")], [#age(24)], [#assoc("UKR")], [#left], [#shakehand], [#attack], [*2389*], [#delta(28)],
      [141], [#name("HUANG Hsin")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2389*], [#delta(-2)],
      [142], [#name("SAWETTABUT Jinnipa")], [#age(23)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2385*], [#delta(43)],
      [143], [#name("MIGOT Marie")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2384*], [#delta(-2)],
      [144], [#name("WONG Xin Ru")], [#age(22)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2383*], [#delta(18)],
      [145], [#name("OJIO Yuna")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2383*], [#delta(10)],
      [146], [#name("KUMAHARA Luca")], [#age(28)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2380*], [#delta(-17)],
      [147], [#name("HUANG Yu-Jie")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2376*], [#delta(-3)],
      [148], [#name("LI Ching Wan")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2374*], [#delta(-1)],
      [149], [#name("WEGRZYN Katarzyna")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2374*], [#delta(-1)],
      [150], [#name("SUNG Rachel")], [#age(19)], [#assoc("USA")], [#left], [#shakehand], [#attack], [*2373*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("BALAZOVA Barbora")], [#age(31)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2371*], [#delta(22)],
      [152], [#name("SINGEORZAN Ioana")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2370*], [#delta(-10)],
      [153], [#name("WIELGOS Zuzanna")], [#age(18)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2367*], [#delta(0)],
      [154], [#name("MOYLAND Sally")], [#age(16)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2365*], [#delta(2)],
      [155], [#name("VIGNJEVIC Dragana")], [#age(24)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2363*], [#delta(2)],
      [156], [#name("STEFANOVA Nikoleta")], [#age(39)], [#assoc("ITA")], [#left], [#shakehand], [#attack], [*2362*], [#delta(2)],
      [157], [#name("LEE Daeun")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2361*], [#delta(2)],
      [158], [#name("TOLIOU Aikaterini")], [#age(28)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2361*], [#delta(-23)],
      [159], [#name("ZHANG Wenjing")], [#age(24)], [#assoc("HKG")], [#right], [#shakehand], [#defense], [*2361*], [#delta(1)],
      [160], [#name("GHOSH Swastika")], [#age(20)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2360*], [#delta(1)],
      [161], [#name("YEH Yi-Tian")], [#age(16)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2357*], [#delta(-18)],
      [162], [#name("TENNISON Reeth")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2355*], [#delta(69)],
      [163], [#name("RYU Hanna")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2354*], [#delta(1)],
      [164], [#name("CHENG Hsien-Tzu")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2353*], [#delta(1)],
      [165], [#name("BAJOR Natalia")], [#age(26)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2352*], [#delta(-39)],
      [166], [#name("李皓晴")], [#age(31)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2352*], [#delta(-47)],
      [167], [#name("PLAIAN Tania")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2348*], [#delta(-1)],
      [168], [#name("LYNE Karen")], [#age(21)], [#assoc("MAS")], [#left], [#shakehand], [#attack], [*2347*], [#delta(-1)],
      [169], [#name("克里斯蒂娜 卡尔伯格")], [#age(23)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2345*], [#delta(-15)],
      [170], [#name("DING Yijie")], [#age(15)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2344*], [#delta(-1)],
      [171], [#name("CHEN Ying-Chen")], [#age(24)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2344*], [#delta(0)],
      [172], [#name("BLASKOVA Zdena")], [#age(22)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2343*], [#delta(0)],
      [173], [#name("KAMATH Archana")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2335*], [#delta(1)],
      [174], [#name("PARK Gahyeon")], [#age(16)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2330*], [#delta(1)],
      [175], [#name("LEE Hoi Man")], [#age(20)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2328*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("ZHANG Sofia-Xuan")], [#age(24)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2327*], [#delta(-31)],
      [177], [#name("吴咏琳")], [#age(20)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2321*], [#delta(-69)],
      [178], [#name("WANG Yiduo")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2321*], [#delta(43)],
      [179], [#name("ZHOU Jingyi")], [#age(18)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2321*], [#delta(-27)],
      [180], [#name("NAGYVARADI Mercedes")], [#age(29)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2318*], [#delta(-1)],
      [181], [#name("KHETKHUAN Tamolwan")], [#age(26)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2316*], [#delta(-1)],
      [182], [#name("TODOROVIC Andrea")], [#age(31)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2312*], [#delta(-5)],
      [183], [#name("MOSTAFAVI Leili")], [#age(23)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2311*], [#delta(1)],
      [184], [#name("DYMYTRENKO Anastasiya")], [#age(21)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2310*], [#delta(2)],
      [185], [#name("ALTINKAYA Sibel")], [#age(30)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2310*], [#delta(-39)],
      [186], [#name("WONG Hoi Tung")], [#age(18)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2306*], [#delta(1)],
      [187], [#name("ARAPOVIC Hana")], [#age(19)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2305*], [#delta(-60)],
      [188], [#name("ALHODABY Mariam")], [#age(23)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2305*], [#delta(74)],
      [189], [#name("ZHU Ziyu")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2305*], [#delta(246)],
      [190], [#name("SILVA Yadira")], [#age(38)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2304*], [#delta(-8)],
      [191], [#name("KLEE Sophia")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2301*], [#delta(0)],
      [192], [#name("TOMANOVSKA Katerina")], [#age(28)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2300*], [#delta(-3)],
      [193], [#name("CHEN Chi-Shiuan")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2299*], [#delta(-3)],
      [194], [#name("XIANG Junlin")], [#age(16)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2296*], [#delta(0)],
      [195], [#name("AOKI Sachi")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2293*], [#delta(1)],
      [196], [#name("COK Isa")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2291*], [#delta(3)],
      [197], [#name("JEGER Mateja")], [#age(28)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2290*], [#delta(1)],
      [198], [#name("MEN Shuohan")], [#age(23)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2289*], [#delta(3)],
      [199], [#name("BRZYSKA Anna")], [#age(18)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2288*], [#delta(-7)],
      [200], [#name("朱思冰")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2287*], [#delta(3)],
    )
  )
