#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("陈梦")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3115*], [#delta(0)],
      [2], [#name("孙颖莎")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3097*], [#delta(0)],
      [3], [#name("王曼昱")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3054*], [#delta(0)],
      [4], [#name("王艺迪")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2998*], [#delta(0)],
      [5], [#name("陈幸同")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2924*], [#delta(0)],
      [6], [#name("何卓佳")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2888*], [#delta(3)],
      [7], [#name("早田希娜")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2852*], [#delta(-1)],
      [8], [#name("伊藤美诚")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2845*], [#delta(-1)],
      [9], [#name("小盐遥菜")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2838*], [#delta(-1)],
      [10], [#name("范思琦")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2835*], [#delta(2)],
      [11], [#name("桥本帆乃香")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2825*], [#delta(-1)],
      [12], [#name("张瑞")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2794*], [#delta(-1)],
      [13], [#name("平野美宇")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2777*], [#delta(1)],
      [14], [#name("袁嘉楠")], [#age(38)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2774*], [#delta(-1)],
      [15], [#name("石川佳纯")], [#age(30)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2767*], [#delta(0)],
      [16], [#name("刘炜珊")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2766*], [#delta(15)],
      [17], [#name("钱天一")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2760*], [#delta(-1)],
      [18], [#name("玛妮卡 巴特拉")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2748*], [#delta(3)],
      [19], [#name("安藤南")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2745*], [#delta(0)],
      [20], [#name("曾尖")], [#age(27)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2738*], [#delta(0)],
      [21], [#name("木原美悠")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2737*], [#delta(2)],
      [22], [#name("蒯曼")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2735*], [#delta(-5)],
      [23], [#name("杨晓欣")], [#age(35)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2733*], [#delta(-1)],
      [24], [#name("长崎美柚")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2714*], [#delta(2)],
      [25], [#name("芝田沙季")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2710*], [#delta(2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("伯纳黛特 斯佐科斯")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2709*], [#delta(-2)],
      [27], [#name("朱成竹")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2706*], [#delta(-9)],
      [28], [#name("单晓娜")], [#age(40)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2701*], [#delta(-3)],
      [29], [#name("张本美和")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2693*], [#delta(1)],
      [30], [#name("崔孝珠")], [#age(25)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2689*], [#delta(18)],
      [31], [#name("徐孝元")], [#age(36)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2683*], [#delta(-3)],
      [32], [#name("韩莹")], [#age(40)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2681*], [#delta(0)],
      [33], [#name("申裕斌")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2679*], [#delta(-4)],
      [34], [#name("索菲亚 波尔卡诺娃")], [#age(29)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2678*], [#delta(-1)],
      [35], [#name("陈熠")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2671*], [#delta(5)],
      [36], [#name("李恩惠")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2671*], [#delta(-2)],
      [37], [#name("傅玉")], [#age(45)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2663*], [#delta(0)],
      [38], [#name("刘佳")], [#age(41)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2660*], [#delta(0)],
      [39], [#name("佐藤瞳")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2660*], [#delta(0)],
      [40], [#name("陈思羽")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2649*], [#delta(-5)],
      [41], [#name("郑怡静")], [#age(31)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2644*], [#delta(8)],
      [42], [#name("齐菲")], [#age(23)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2631*], [#delta(-6)],
      [43], [#name("琳达 伯格斯特罗姆")], [#age(28)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2626*], [#delta(-2)],
      [44], [#name("杜凯琹")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2621*], [#delta(6)],
      [45], [#name("田志希")], [#age(31)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2615*], [#delta(2)],
      [46], [#name("阿德里安娜 迪亚兹")], [#age(23)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2615*], [#delta(-3)],
      [47], [#name("森樱")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2610*], [#delta(-3)],
      [48], [#name("石洵瑶")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2608*], [#delta(-6)],
      [49], [#name("斯丽贾 阿库拉")], [#age(25)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2607*], [#delta(8)],
      [50], [#name("PESOTSKA Margaryta")], [#age(32)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2599*], [#delta(-5)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("王 艾米")], [#age(21)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2598*], [#delta(-5)],
      [52], [#name("梁夏银")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2582*], [#delta(1)],
      [53], [#name("金河英")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2581*], [#delta(1)],
      [54], [#name("吴洋晨")], [#age(21)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2579*], [#delta(2)],
      [55], [#name("朱芊曦")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2573*], [#delta(4)],
      [56], [#name("李昱谆")], [#age(26)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2565*], [#delta(-5)],
      [57], [#name("徐奕")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2561*], [#delta(1)],
      [58], [#name("苏萨西尼 萨维塔布特")], [#age(29)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2559*], [#delta(-6)],
      [59], [#name("倪夏莲")], [#age(60)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2558*], [#delta(-4)],
      [60], [#name("SOO Wai Yam")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2543*], [#delta(2)],
      [61], [#name("覃予萱")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2543*], [#delta(2)],
      [62], [#name("杨蕙菁")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2541*], [#delta(2)],
      [63], [#name("MADARASZ Dora")], [#age(30)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2533*], [#delta(23)],
      [64], [#name("艾希卡 穆克吉")], [#age(26)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2533*], [#delta(1)],
      [65], [#name("韩菲儿")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2531*], [#delta(1)],
      [66], [#name("奥拉万 帕拉南")], [#age(26)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2527*], [#delta(6)],
      [67], [#name("CHITALE Diya")], [#age(20)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2527*], [#delta(-6)],
      [68], [#name("安妮特 考夫曼")], [#age(17)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2525*], [#delta(5)],
      [69], [#name("张安")], [#age(27)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2523*], [#delta(-1)],
      [70], [#name("笹尾明日香")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2522*], [#delta(-1)],
      [71], [#name("普利西卡 帕瓦德")], [#age(19)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2519*], [#delta(-4)],
      [72], [#name("BAJOR Natalia")], [#age(26)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2516*], [#delta(-12)],
      [73], [#name("李时温")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2515*], [#delta(9)],
      [74], [#name("JEE Minhyung")], [#age(36)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2509*], [#delta(0)],
      [75], [#name("刘杨子")], [#age(21)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2503*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("伊丽莎白 萨玛拉")], [#age(34)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2502*], [#delta(13)],
      [77], [#name("妮娜 米特兰姆")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2501*], [#delta(-6)],
      [78], [#name("DIACONU Adina")], [#age(24)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2499*], [#delta(5)],
      [79], [#name("LIU Hsing-Yin")], [#age(36)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2496*], [#delta(-4)],
      [80], [#name("LAY Jian Fang")], [#age(50)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2496*], [#delta(-1)],
      [81], [#name("LI Yuqi")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2489*], [#delta(0)],
      [82], [#name("高桥 布鲁娜")], [#age(23)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2486*], [#delta(-4)],
      [83], [#name("布里特 伊尔兰德")], [#age(29)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2483*], [#delta(1)],
      [84], [#name("赤江夏星")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2473*], [#delta(1)],
      [85], [#name("蒂娜 梅谢芙")], [#age(29)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2466*], [#delta(45)],
      [86], [#name("金娜英")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2466*], [#delta(2)],
      [87], [#name("CHASSELIN Pauline")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2460*], [#delta(3)],
      [88], [#name("张墨")], [#age(34)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2459*], [#delta(3)],
      [89], [#name("邵杰妮")], [#age(29)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2457*], [#delta(3)],
      [90], [#name("肖瑶茜")], [#age(29)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2457*], [#delta(14)],
      [91], [#name("BALAZOVA Barbora")], [#age(31)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2456*], [#delta(-21)],
      [92], [#name("DRAGOMAN Andreea")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2455*], [#delta(-15)],
      [93], [#name("ZAHARIA Elena")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2454*], [#delta(-6)],
      [94], [#name("陈沂芊")], [#age(21)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2452*], [NEW],
      [95], [#name("KUMAHARA Luca")], [#age(28)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2449*], [#delta(-1)],
      [96], [#name("CIOBANU Irina")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2447*], [#delta(-16)],
      [97], [#name("HUANG Yi-Hua")], [#age(39)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2446*], [#delta(-2)],
      [98], [#name("KIM Byeolnim")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2445*], [#delta(-2)],
      [99], [#name("克里斯蒂娜 卡尔伯格")], [#age(23)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2439*], [#delta(-6)],
      [100], [#name("SU Pei-Ling")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("LI Ching Wan")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-1)],
      [102], [#name("MATELOVA Hana")], [#age(33)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2436*], [#delta(-1)],
      [103], [#name("SCHREINER Franziska")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2434*], [#delta(17)],
      [104], [#name("MANTZ Chantal")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2431*], [#delta(3)],
      [105], [#name("ZHOU Jingyi")], [#age(18)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2428*], [#delta(-8)],
      [106], [#name("PICCOLIN Giorgia")], [#age(27)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2425*], [#delta(-8)],
      [107], [#name("LENG Yutong")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2425*], [#delta(-2)],
      [108], [#name("纵歌曼")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2424*], [#delta(-2)],
      [109], [#name("ZANG Xiaotong")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2419*], [#delta(-1)],
      [110], [#name("MALOBABIC Ivana")], [#age(43)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2415*], [#delta(-1)],
      [111], [#name("GHOSH Swastika")], [#age(20)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2413*], [#delta(31)],
      [112], [#name("王添艺")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2412*], [#delta(-2)],
      [113], [#name("LAM Yee Lok")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2410*], [#delta(-2)],
      [114], [#name("YOON Hyobin")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2408*], [#delta(-2)],
      [115], [#name("TOLIOU Aikaterini")], [#age(28)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2406*], [#delta(0)],
      [116], [#name("万远")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2404*], [#delta(-14)],
      [117], [#name("SURJAN Sabina")], [#age(23)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2403*], [#delta(1)],
      [118], [#name("LUTZ Charlotte")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2402*], [#delta(-2)],
      [119], [#name("汉娜 高达")], [#age(16)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2401*], [#delta(-6)],
      [120], [#name("LUTZ Camille")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2396*], [#delta(-1)],
      [121], [#name("萨比亚 温特")], [#age(31)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2389*], [#delta(0)],
      [122], [#name("HUANG Yu-Jie")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2386*], [#delta(-5)],
      [123], [#name("WONG Xin Ru")], [#age(22)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2386*], [#delta(6)],
      [124], [#name("MIGOT Marie")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2384*], [#delta(3)],
      [125], [#name("ALTINKAYA Sibel")], [#age(30)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2383*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("SINGEORZAN Ioana")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2383*], [#delta(-12)],
      [127], [#name("乔治娜 波塔")], [#age(38)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2379*], [#delta(26)],
      [128], [#name("BLASKOVA Zdena")], [#age(22)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2377*], [#delta(0)],
      [129], [#name("CHENG Hsien-Tzu")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2374*], [#delta(-7)],
      [130], [#name("SUNG Rachel")], [#age(19)], [#assoc("USA")], [#left], [#shakehand], [#attack], [*2373*], [#delta(1)],
      [131], [#name("HUANG Hsin")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2373*], [NEW],
      [132], [#name("MOYLAND Sally")], [#age(16)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2371*], [#delta(0)],
      [133], [#name("GHORPADE Yashaswini")], [#age(19)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2371*], [#delta(0)],
      [134], [#name("YEH Yi-Tian")], [#age(16)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2370*], [#delta(-10)],
      [135], [#name("ZHANG Sofia-Xuan")], [#age(24)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2368*], [#delta(33)],
      [136], [#name("KIM Seongjin")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2368*], [#delta(-2)],
      [137], [#name("KUKULKOVA Tatiana")], [#age(23)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2366*], [#delta(25)],
      [138], [#name("RYU Hanna")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2366*], [#delta(-3)],
      [139], [#name("HUANG Yu-Wen")], [#age(27)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2366*], [#delta(-3)],
      [140], [#name("VIVARELLI Debora")], [#age(30)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2364*], [#delta(-37)],
      [141], [#name("苏蒂尔塔 穆克吉")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2364*], [#delta(-4)],
      [142], [#name("DE NUTTE Sarah")], [#age(31)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2362*], [#delta(-17)],
      [143], [#name("KHETKHUAN Tamolwan")], [#age(26)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2361*], [#delta(-5)],
      [144], [#name("VIGNJEVIC Dragana")], [#age(24)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2361*], [#delta(-5)],
      [145], [#name("小盐悠菜")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2361*], [#delta(-5)],
      [146], [#name("HURSEY Anna")], [#age(17)], [#assoc("WAL")], [#right], [#shakehand], [#attack], [*2360*], [#delta(-5)],
      [147], [#name("LEE Daeun")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2357*], [#delta(-3)],
      [148], [#name("STEFANOVA Nikoleta")], [#age(39)], [#assoc("ITA")], [#left], [#shakehand], [#attack], [*2357*], [#delta(-3)],
      [149], [#name("CHENG Pusyuan")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2352*], [#delta(-3)],
      [150], [#name("HO Tin-Tin")], [#age(25)], [#assoc("ENG")], [#right], [#penhold], [#attack], [*2352*], [#delta(-27)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("LEE Daeun")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2351*], [#delta(3)],
      [152], [#name("面手凛")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2350*], [#delta(-5)],
      [153], [#name("JEGER Mateja")], [#age(28)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2348*], [#delta(-5)],
      [154], [#name("PLAIAN Tania")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2348*], [#delta(-2)],
      [155], [#name("李皓晴")], [#age(31)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2348*], [#delta(-6)],
      [156], [#name("MOSTAFAVI Leili")], [#age(23)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2338*], [#delta(-1)],
      [157], [#name("GUISNEL Oceane")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2337*], [#delta(-1)],
      [158], [#name("LOEUILLETTE Stephanie")], [#age(31)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2334*], [#delta(-1)],
      [159], [#name("SAWETTABUT Jinnipa")], [#age(23)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2333*], [#delta(4)],
      [160], [#name("DYMYTRENKO Anastasiya")], [#age(21)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2332*], [#delta(-2)],
      [161], [#name("LUPULESKU Izabela")], [#age(24)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2331*], [#delta(-1)],
      [162], [#name("BERGAND Filippa")], [#age(24)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2331*], [#delta(-1)],
      [163], [#name("ARAPOVIC Hana")], [#age(19)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2330*], [#delta(-12)],
      [164], [#name("WEGRZYN Anna")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2330*], [#delta(-21)],
      [165], [#name("KAMATH Archana")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2321*], [#delta(0)],
      [166], [#name("SOLJA Amelie")], [#age(33)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2321*], [#delta(-2)],
      [167], [#name("NAGYVARADI Mercedes")], [#age(29)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2318*], [#delta(-1)],
      [168], [#name("LEE Hoi Man")], [#age(20)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2315*], [#delta(29)],
      [169], [#name("MEN Shuohan")], [#age(23)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2311*], [#delta(-2)],
      [170], [#name("ZARIF Audrey")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2308*], [#delta(-1)],
      [171], [#name("TODOROVIC Andrea")], [#age(31)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2306*], [#delta(-1)],
      [172], [#name("WIELGOS Zuzanna")], [#age(18)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2304*], [#delta(-1)],
      [173], [#name("PARK Gahyeon")], [#age(16)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2302*], [#delta(-1)],
      [174], [#name("CHANG Li Sian Alice")], [#age(23)], [#assoc("MAS")], [#right], [#shakehand], [#defense], [*2302*], [#delta(-1)],
      [175], [#name("BRATEYKO Solomiya")], [#age(24)], [#assoc("UKR")], [#left], [#shakehand], [#attack], [*2300*], [#delta(11)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("XIANG Junlin")], [#age(16)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2293*], [#delta(0)],
      [177], [#name("EDEM Offiong")], [#age(37)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2292*], [#delta(0)],
      [178], [#name("BALINT Bernadett")], [#age(27)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2291*], [#delta(0)],
      [179], [#name("AOKI Sachi")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2291*], [#delta(0)],
      [180], [#name("吴咏琳")], [#age(20)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2290*], [#delta(-30)],
      [181], [#name("WONG Hoi Tung")], [#age(18)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2290*], [#delta(61)],
      [182], [#name("MONFARDINI Gaia")], [#age(22)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2288*], [#delta(-2)],
      [183], [#name("朱思冰")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2287*], [#delta(-2)],
      [184], [#name("YAMADA Jessica")], [#age(34)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2287*], [#delta(-2)],
      [185], [#name("WEGRZYN Katarzyna")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2287*], [#delta(-10)],
      [186], [#name("YAN Yutong")], [#age(15)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2285*], [#delta(-3)],
      [187], [#name("AUEAWIRIYAYOTHIN Wanwisa")], [#age(19)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2285*], [#delta(-3)],
      [188], [#name("HAPONOVA Hanna")], [#age(38)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2285*], [#delta(-29)],
      [189], [#name("MUSKANTOR Rebecca")], [#age(20)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2284*], [#delta(-4)],
      [190], [#name("TENNISON Reeth")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2277*], [#delta(5)],
      [191], [#name("LABOSOVA Ema")], [#age(22)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2274*], [#delta(-3)],
      [192], [#name("SILVA Yadira")], [#age(38)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2273*], [#delta(-3)],
      [193], [#name("HUANG Yu-Chiao")], [#age(27)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2273*], [NEW],
      [194], [#name("CHOI Haeeun")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2272*], [#delta(-4)],
      [195], [#name("TSAI Yun-En")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2271*], [#delta(-4)],
      [196], [#name("CHEN Chi-Shiuan")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2269*], [#delta(-4)],
      [197], [#name("MORET Rachel")], [#age(34)], [#assoc("SUI")], [#left], [#shakehand], [#attack], [*2269*], [#delta(3)],
      [198], [#name("MISCHEK Karoline")], [#age(25)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2262*], [#delta(-24)],
      [199], [#name("WANG Yiduo")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2262*], [#delta(-5)],
      [200], [#name("JALLI Sarah")], [#age(17)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2258*], [#delta(-4)],
    )
  )
