#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("孙颖莎")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3144*], [#delta(0)],
      [2], [#name("陈梦")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3044*], [#delta(0)],
      [3], [#name("王曼昱")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3036*], [#delta(3)],
      [4], [#name("陈幸同")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3004*], [#delta(-1)],
      [5], [#name("王艺迪")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2960*], [#delta(-1)],
      [6], [#name("早田希娜")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2920*], [#delta(-1)],
      [7], [#name("何卓佳")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2857*], [#delta(2)],
      [8], [#name("蒯曼")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2850*], [#delta(5)],
      [9], [#name("申裕斌")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2846*], [#delta(-1)],
      [10], [#name("平野美宇")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2835*], [#delta(-3)],
      [11], [#name("桥本帆乃香")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2825*], [#delta(-1)],
      [12], [#name("钱天一")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2825*], [#delta(-1)],
      [13], [#name("韩莹")], [#age(40)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2806*], [#delta(8)],
      [14], [#name("伊藤美诚")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2801*], [#delta(-2)],
      [15], [#name("张瑞")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2800*], [#delta(-1)],
      [16], [#name("伯纳黛特 斯佐科斯")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2782*], [#delta(0)],
      [17], [#name("陈熠")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2780*], [#delta(2)],
      [18], [#name("张本美和")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2777*], [#delta(2)],
      [19], [#name("木原美悠")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2776*], [#delta(-1)],
      [20], [#name("范思琦")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2771*], [#delta(-3)],
      [21], [#name("石川佳纯")], [#age(30)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2759*], [#delta(1)],
      [22], [#name("安藤南")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2747*], [#delta(1)],
      [23], [#name("杨晓欣")], [#age(35)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2745*], [#delta(-8)],
      [24], [#name("小盐遥菜")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2742*], [#delta(0)],
      [25], [#name("单晓娜")], [#age(40)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2723*], [#delta(5)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("郑怡静")], [#age(31)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2717*], [#delta(0)],
      [27], [#name("芝田沙季")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2710*], [#delta(1)],
      [28], [#name("长崎美柚")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2709*], [#delta(1)],
      [29], [#name("朱芊曦")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2700*], [#delta(-4)],
      [30], [#name("妮娜 米特兰姆")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2692*], [#delta(31)],
      [31], [#name("森樱")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2691*], [#delta(8)],
      [32], [#name("刘炜珊")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2688*], [#delta(-5)],
      [33], [#name("石洵瑶")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2682*], [#delta(21)],
      [34], [#name("田志希")], [#age(31)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2682*], [#delta(8)],
      [35], [#name("徐奕")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2678*], [#delta(-2)],
      [36], [#name("倪夏莲")], [#age(60)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2675*], [#delta(11)],
      [37], [#name("徐孝元")], [#age(36)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2672*], [#delta(1)],
      [38], [#name("奥拉万 帕拉南")], [#age(26)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2670*], [#delta(39)],
      [39], [#name("刘佳")], [#age(41)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2665*], [#delta(-4)],
      [40], [#name("佐藤瞳")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2662*], [#delta(-3)],
      [41], [#name("阿德里安娜 迪亚兹")], [#age(23)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2654*], [#delta(3)],
      [42], [#name("高桥 布鲁娜")], [#age(23)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2653*], [#delta(-8)],
      [43], [#name("王晓彤")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2650*], [#delta(3)],
      [44], [#name("崔孝珠")], [#age(25)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2642*], [#delta(14)],
      [45], [#name("曾尖")], [#age(27)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2641*], [#delta(14)],
      [46], [#name("邵杰妮")], [#age(29)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2637*], [#delta(51)],
      [47], [#name("朱成竹")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2636*], [#delta(-7)],
      [48], [#name("袁嘉楠")], [#age(38)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2635*], [#delta(19)],
      [49], [#name("李恩惠")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2628*], [#delta(-4)],
      [50], [#name("范姝涵")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2625*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("朱思冰")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2620*], [#delta(70)],
      [52], [#name("李时温")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2614*], [#delta(-9)],
      [53], [#name("韩菲儿")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2612*], [#delta(12)],
      [54], [#name("肖瑶茜")], [#age(29)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2607*], [#delta(9)],
      [55], [#name("吴洋晨")], [#age(21)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2606*], [#delta(5)],
      [56], [#name("李雅可")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2603*], [#delta(18)],
      [57], [#name("杨屹韵")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2602*], [#delta(-2)],
      [58], [#name("覃予萱")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2602*], [#delta(-6)],
      [59], [#name("笹尾明日香")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2600*], [#delta(3)],
      [60], [#name("郭雨涵")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2600*], [#delta(-4)],
      [61], [#name("傅玉")], [#age(45)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2596*], [#delta(-13)],
      [62], [#name("金河英")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2592*], [#delta(-13)],
      [63], [#name("普利西卡 帕瓦德")], [#age(19)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2592*], [#delta(-32)],
      [64], [#name("齐菲")], [#age(23)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2591*], [#delta(-13)],
      [65], [#name("梁夏银")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2578*], [#delta(-8)],
      [66], [#name("王 艾米")], [#age(21)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2568*], [#delta(49)],
      [67], [#name("玛妮卡 巴特拉")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2560*], [#delta(-31)],
      [68], [#name("琳达 伯格斯特罗姆")], [#age(28)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2558*], [#delta(-27)],
      [69], [#name("PESOTSKA Margaryta")], [#age(32)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2555*], [#delta(27)],
      [70], [#name("萨比亚 温特")], [#age(31)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2554*], [#delta(17)],
      [71], [#name("NOMURA Moe")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2553*], [#delta(2)],
      [72], [#name("DRAGOMAN Andreea")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2544*], [#delta(-19)],
      [73], [#name("ZHANG Xiangyu")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2544*], [#delta(26)],
      [74], [#name("SOO Wai Yam")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2543*], [#delta(-6)],
      [75], [#name("刘杨子")], [#age(21)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2542*], [#delta(9)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("苏萨西尼 萨维塔布特")], [#age(29)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2535*], [#delta(-7)],
      [77], [#name("汉娜 高达")], [#age(16)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2531*], [#delta(26)],
      [78], [#name("李昱谆")], [#age(26)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2531*], [#delta(-3)],
      [79], [#name("赤江夏星")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2530*], [#delta(23)],
      [80], [#name("STEFANOVA Nikoleta")], [#age(39)], [#assoc("ITA")], [#left], [#shakehand], [#attack], [*2528*], [#delta(88)],
      [81], [#name("纵歌曼")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2523*], [#delta(-17)],
      [82], [#name("SURJAN Sabina")], [#age(23)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2520*], [#delta(52)],
      [83], [#name("DIACONU Adina")], [#age(24)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2517*], [#delta(-3)],
      [84], [#name("陈沂芊")], [#age(21)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2515*], [#delta(-8)],
      [85], [#name("万远")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2512*], [#delta(-7)],
      [86], [#name("杜凯琹")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2501*], [#delta(-3)],
      [87], [#name("LIU Hsing-Yin")], [#age(36)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2492*], [#delta(13)],
      [88], [#name("伊丽莎白 萨玛拉")], [#age(34)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2492*], [#delta(-56)],
      [89], [#name("HUANG Yi-Hua")], [#age(39)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2490*], [#delta(-4)],
      [90], [#name("CIOBANU Irina")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2489*], [#delta(-2)],
      [91], [#name("LI Yuqi")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2489*], [#delta(-2)],
      [92], [#name("苏蒂尔塔 穆克吉")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2488*], [#delta(3)],
      [93], [#name("杨蕙菁")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2486*], [#delta(-2)],
      [94], [#name("MATELOVA Hana")], [#age(33)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2483*], [#delta(36)],
      [95], [#name("布里特 伊尔兰德")], [#age(29)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2483*], [#delta(-3)],
      [96], [#name("张墨")], [#age(34)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2479*], [#delta(26)],
      [97], [#name("BAJOR Natalia")], [#age(26)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2471*], [#delta(-16)],
      [98], [#name("蒂娜 梅谢芙")], [#age(29)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2468*], [#delta(-8)],
      [99], [#name("CHASSELIN Pauline")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2467*], [#delta(-1)],
      [100], [#name("乔治娜 波塔")], [#age(38)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2463*], [#delta(-30)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("KIM Byeolnim")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2462*], [#delta(0)],
      [102], [#name("CHENG Hsien-Tzu")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2461*], [#delta(34)],
      [103], [#name("MALOBABIC Ivana")], [#age(43)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2456*], [#delta(-32)],
      [104], [#name("小盐悠菜")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2455*], [#delta(1)],
      [105], [#name("LAY Jian Fang")], [#age(50)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2455*], [#delta(-12)],
      [106], [#name("BALAZOVA Barbora")], [#age(31)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2450*], [#delta(80)],
      [107], [#name("LEE Daeun")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2449*], [#delta(11)],
      [108], [#name("艾希卡 穆克吉")], [#age(26)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2448*], [#delta(24)],
      [109], [#name("克里斯蒂娜 卡尔伯格")], [#age(23)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2448*], [#delta(3)],
      [110], [#name("MADARASZ Dora")], [#age(30)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2446*], [#delta(-31)],
      [111], [#name("HAPONOVA Hanna")], [#age(38)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2444*], [#delta(-39)],
      [112], [#name("ZARIF Audrey")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2444*], [#delta(-4)],
      [113], [#name("ZAHARIA Elena")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2443*], [#delta(-2)],
      [114], [#name("面手凛")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2440*], [#delta(-1)],
      [115], [#name("陈思羽")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-29)],
      [116], [#name("ZANG Xiaotong")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-2)],
      [117], [#name("GHOSH Swastika")], [#age(20)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2437*], [#delta(39)],
      [118], [#name("索菲亚 波尔卡诺娃")], [#age(29)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2436*], [#delta(-2)],
      [119], [#name("GUISNEL Oceane")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2435*], [#delta(-2)],
      [120], [#name("斯丽贾 阿库拉")], [#age(25)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2435*], [#delta(-26)],
      [121], [#name("金娜英")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2430*], [#delta(-39)],
      [122], [#name("张安")], [#age(27)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2426*], [#delta(4)],
      [123], [#name("LENG Yutong")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2425*], [#delta(1)],
      [124], [#name("BRATEYKO Solomiya")], [#age(24)], [#assoc("UKR")], [#left], [#shakehand], [#attack], [*2424*], [#delta(-58)],
      [125], [#name("CHITALE Diya")], [#age(20)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2423*], [#delta(-19)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("LUTZ Camille")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2421*], [#delta(7)],
      [127], [#name("SU Pei-Ling")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2417*], [#delta(8)],
      [128], [#name("SCHREINER Franziska")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2416*], [#delta(-19)],
      [129], [#name("DE NUTTE Sarah")], [#age(31)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2416*], [#delta(-25)],
      [130], [#name("HUANG Yu-Wen")], [#age(27)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2416*], [#delta(-2)],
      [131], [#name("WEGRZYN Anna")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2414*], [#delta(-24)],
      [132], [#name("CHANG Li Sian Alice")], [#age(23)], [#assoc("MAS")], [#right], [#shakehand], [#defense], [*2414*], [#delta(5)],
      [133], [#name("王添艺")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2412*], [#delta(6)],
      [134], [#name("LAVROVA Anastassiya")], [#age(28)], [#assoc("KAZ")], [#right], [#shakehand], [#attack], [*2412*], [#delta(32)],
      [135], [#name("吴咏琳")], [#age(20)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2411*], [#delta(-10)],
      [136], [#name("SAWETTABUT Jinnipa")], [#age(23)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2407*], [#delta(5)],
      [137], [#name("JEE Minhyung")], [#age(36)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2406*], [#delta(-14)],
      [138], [#name("CHEN Ying-Chen")], [#age(24)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2405*], [#delta(-19)],
      [139], [#name("LOEUILLETTE Stephanie")], [#age(31)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2401*], [#delta(3)],
      [140], [#name("MANTZ Chantal")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2400*], [#delta(6)],
      [141], [#name("HUANG Hsin")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2397*], [#delta(28)],
      [142], [#name("KUKULKOVA Tatiana")], [#age(23)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2396*], [#delta(33)],
      [143], [#name("SUNG Rachel")], [#age(19)], [#assoc("USA")], [#left], [#shakehand], [#attack], [*2395*], [#delta(10)],
      [144], [#name("SINGEORZAN Ioana")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2394*], [#delta(1)],
      [145], [#name("GHORPADE Yashaswini")], [#age(19)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2394*], [#delta(-16)],
      [146], [#name("LUTZ Charlotte")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2393*], [#delta(-2)],
      [147], [#name("安妮特 考夫曼")], [#age(17)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2391*], [#delta(0)],
      [148], [#name("YAN Yutong")], [#age(15)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2390*], [#delta(34)],
      [149], [#name("PARK Gahyeon")], [#age(16)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2389*], [#delta(16)],
      [150], [#name("CHENG Pusyuan")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2387*], [#delta(-30)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("LEE Seungeun")], [#age(16)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2385*], [#delta(-8)],
      [152], [#name("HUANG Yu-Chiao")], [#age(27)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2384*], [#delta(77)],
      [153], [#name("MIGOT Marie")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2384*], [#delta(-5)],
      [154], [#name("RAKOVAC Lea")], [#age(27)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2384*], [#delta(-23)],
      [155], [#name("KIM Seongjin")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2382*], [#delta(-4)],
      [156], [#name("BALINT Bernadett")], [#age(27)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2381*], [#delta(31)],
      [157], [#name("KUMAHARA Luca")], [#age(28)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2380*], [#delta(-3)],
      [158], [#name("LUPULESKU Izabela")], [#age(24)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2380*], [#delta(30)],
      [159], [#name("KAMATH Archana")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2380*], [#delta(-19)],
      [160], [#name("LAM Yee Lok")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2378*], [#delta(-33)],
      [161], [#name("ZHANG Sofia-Xuan")], [#age(24)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2378*], [#delta(12)],
      [162], [#name("GRIESEL Mia")], [#age(17)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2373*], [#delta(31)],
      [163], [#name("BERGAND Filippa")], [#age(24)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2372*], [#delta(1)],
      [164], [#name("YEH Yi-Tian")], [#age(16)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2372*], [#delta(6)],
      [165], [#name("BLASKOVA Zdena")], [#age(22)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2371*], [#delta(48)],
      [166], [#name("HURSEY Anna")], [#age(17)], [#assoc("WAL")], [#right], [#shakehand], [#attack], [*2369*], [#delta(-14)],
      [167], [#name("NAGYVARADI Mercedes")], [#age(29)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2369*], [#delta(13)],
      [168], [#name("YOON Hyobin")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2369*], [#delta(-30)],
      [169], [#name("WIELGOS Zuzanna")], [#age(18)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2368*], [#delta(-59)],
      [170], [#name("RYU Hanna")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2368*], [#delta(-13)],
      [171], [#name("李皓晴")], [#age(31)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2366*], [#delta(0)],
      [172], [#name("WANG Yi-Ju")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2366*], [#delta(-14)],
      [173], [#name("TOLIOU Aikaterini")], [#age(28)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2366*], [#delta(10)],
      [174], [#name("AOKI Sachi")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2365*], [#delta(-15)],
      [175], [#name("PLAIAN Tania")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2364*], [#delta(-15)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("HO Tin-Tin")], [#age(25)], [#assoc("ENG")], [#right], [#penhold], [#attack], [*2362*], [#delta(-14)],
      [177], [#name("MOYLAND Sally")], [#age(16)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2362*], [#delta(-27)],
      [178], [#name("ZHANG Wenjing")], [#age(24)], [#assoc("HKG")], [#right], [#shakehand], [#defense], [*2361*], [#delta(-15)],
      [179], [#name("ARAPOVIC Hana")], [#age(19)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2361*], [#delta(-18)],
      [180], [#name("TAKEYA Misuzu")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2345*], [#delta(63)],
      [181], [#name("COSSIO Arantxa")], [#age(19)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2344*], [#delta(3)],
      [182], [#name("KHETKHUAN Tamolwan")], [#age(26)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2342*], [#delta(-3)],
      [183], [#name("SOLJA Amelie")], [#age(33)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2341*], [#delta(-6)],
      [184], [#name("ALHODABY Mariam")], [#age(23)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2338*], [#delta(16)],
      [185], [#name("MONFARDINI Gaia")], [#age(22)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2336*], [#delta(13)],
      [186], [#name("LEE Daeun")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2329*], [#delta(-19)],
      [187], [#name("DING Yijie")], [#age(15)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2327*], [#delta(-11)],
      [188], [#name("LEE Hoi Man")], [#age(20)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2325*], [#delta(-7)],
      [189], [#name("VIGNJEVIC Dragana")], [#age(24)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2324*], [#delta(-4)],
      [190], [#name("HUANG Yu-Jie")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2323*], [#delta(-35)],
      [191], [#name("YOO Yerin")], [#age(15)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2319*], [#delta(45)],
      [192], [#name("AUEAWIRIYAYOTHIN Wanwisa")], [#age(19)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2317*], [#delta(33)],
      [193], [#name("DARI Helga")], [#age(21)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2317*], [#delta(-3)],
      [194], [#name("WANG Yiduo")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2314*], [#delta(-2)],
      [195], [#name("MOSTAFAVI Leili")], [#age(23)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2310*], [#delta(-1)],
      [196], [#name("WONG Xin Ru")], [#age(22)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2310*], [#delta(-18)],
      [197], [#name("MAKSUTI Aneta")], [#age(28)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2310*], [NEW],
      [198], [#name("LYNE Karen")], [#age(21)], [#assoc("MAS")], [#left], [#shakehand], [#attack], [*2309*], [#delta(-26)],
      [199], [#name("CHEN Chi-Shiuan")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2309*], [#delta(7)],
      [200], [#name("TAKAHASHI Giulia")], [#age(18)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2306*], [#delta(10)],
    )
  )
