#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("孙颖莎")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3060*], [#delta(5)],
      [2], [#name("陈梦")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3053*], [#delta(0)],
      [3], [#name("刘诗雯")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2991*], [#delta(0)],
      [4], [#name("朱雨玲")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2980*], [#delta(-3)],
      [5], [#name("王曼昱")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2969*], [#delta(-1)],
      [6], [#name("顾玉婷")], [#age(24)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2887*], [#delta(9)],
      [7], [#name("丁宁")], [#age(29)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2865*], [#delta(-2)],
      [8], [#name("木子")], [#age(30)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2856*], [#delta(1)],
      [9], [#name("平野美宇")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2846*], [#delta(10)],
      [10], [#name("早田希娜")], [#age(19)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2843*], [#delta(-3)],
      [11], [#name("冯亚兰")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2840*], [#delta(0)],
      [12], [#name("武杨")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2840*], [#delta(10)],
      [13], [#name("王艺迪")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2840*], [#delta(-1)],
      [14], [#name("伊藤美诚")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2836*], [#delta(4)],
      [15], [#name("何卓佳")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2835*], [#delta(-7)],
      [16], [#name("陈可")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2790*], [#delta(1)],
      [17], [#name("陈幸同")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2785*], [#delta(-7)],
      [18], [#name("刘斐")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2777*], [#delta(39)],
      [19], [#name("韩莹")], [#age(36)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2770*], [#delta(2)],
      [20], [#name("石川佳纯")], [#age(26)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2766*], [#delta(-7)],
      [21], [#name("钱天一")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2760*], [#delta(16)],
      [22], [#name("佐藤瞳")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2756*], [#delta(11)],
      [23], [#name("GU Ruochen")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2747*], [#delta(1)],
      [24], [#name("张瑞")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2743*], [#delta(2)],
      [25], [#name("长崎美柚")], [#age(17)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2743*], [#delta(19)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("车晓曦")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2739*], [#delta(9)],
      [27], [#name("金宋依")], [#age(25)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2736*], [#delta(-2)],
      [28], [#name("孙铭阳")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2732*], [#delta(-1)],
      [29], [#name("傅玉")], [#age(41)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2727*], [#delta(20)],
      [30], [#name("李佳燚")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2726*], [#delta(-2)],
      [31], [#name("郑怡静")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2724*], [#delta(19)],
      [32], [#name("范思琦")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2724*], [#delta(-3)],
      [33], [#name("LIU Xi")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2718*], [#delta(-1)],
      [34], [#name("冯天薇")], [#age(33)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2707*], [#delta(-14)],
      [35], [#name("杨晓欣")], [#age(31)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2705*], [#delta(19)],
      [36], [#name("徐孝元")], [#age(32)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2704*], [#delta(0)],
      [37], [#name("李皓晴")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2703*], [#delta(10)],
      [38], [#name("于梦雨")], [#age(30)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2695*], [#delta(-15)],
      [39], [#name("张蔷")], [#age(25)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2693*], [#delta(0)],
      [40], [#name("石洵瑶")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2691*], [#delta(2)],
      [41], [#name("CHA Hyo Sim")], [#age(25)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2690*], [#delta(0)],
      [42], [#name("梁夏银")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2688*], [#delta(10)],
      [43], [#name("加藤美优")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2687*], [#delta(-27)],
      [44], [#name("安藤南")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2685*], [#delta(-14)],
      [45], [#name("SOO Wai Yam")], [#age(21)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2673*], [#delta(-11)],
      [46], [#name("侯美玲")], [#age(30)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2662*], [#delta(2)],
      [47], [#name("桥本帆乃香")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2661*], [#delta(-16)],
      [48], [#name("倪夏莲")], [#age(56)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2654*], [#delta(91)],
      [49], [#name("木原美悠")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2652*], [#delta(-3)],
      [50], [#name("芝田沙季")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2649*], [#delta(-12)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("陈思羽")], [#age(26)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2649*], [#delta(2)],
      [52], [#name("杜凯琹")], [#age(23)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2646*], [#delta(-38)],
      [53], [#name("李芬")], [#age(43)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2645*], [#delta(2)],
      [54], [#name("YOO Eunchong")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2638*], [#delta(2)],
      [55], [#name("伯纳黛特 斯佐科斯")], [#age(24)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2637*], [#delta(8)],
      [56], [#name("KIM Nam Hae")], [#age(23)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2635*], [#delta(2)],
      [57], [#name("金河英")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2630*], [#delta(4)],
      [58], [#name("森樱")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2626*], [#delta(17)],
      [59], [#name("李倩")], [#age(33)], [#assoc("POL")], [#right], [#shakehand], [#defense], [*2626*], [#delta(-14)],
      [60], [#name("LIU Xin")], [#age(22)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2616*], [#delta(14)],
      [61], [#name("李倩")], [#age(33)], [#assoc("CHN")], [?], [?], [?], [*2611*], [NEW],
      [62], [#name("田志希")], [#age(27)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2610*], [#delta(5)],
      [63], [#name("PESOTSKA Margaryta")], [#age(28)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2606*], [#delta(-23)],
      [64], [#name("BILENKO Tetyana")], [#age(36)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2604*], [#delta(21)],
      [65], [#name("曾尖")], [#age(23)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2603*], [#delta(61)],
      [66], [#name("HUANG Yingqi")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2600*], [#delta(0)],
      [67], [#name("崔孝珠")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2596*], [#delta(-7)],
      [68], [#name("妮娜 米特兰姆")], [#age(23)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2596*], [#delta(57)],
      [69], [#name("EKHOLM Matilda")], [#age(37)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2595*], [#delta(12)],
      [70], [#name("SUN Jiayi")], [#age(19)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2594*], [#delta(-2)],
      [71], [#name("琳达 伯格斯特隆")], [#age(24)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2590*], [#delta(44)],
      [72], [#name("CHENG Hsien-Tzu")], [#age(26)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2589*], [#delta(-29)],
      [73], [#name("单晓娜")], [#age(36)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2587*], [#delta(-22)],
      [74], [#name("刘佳")], [#age(37)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2584*], [#delta(15)],
      [75], [#name("佩特丽莎 索尔佳")], [#age(25)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2584*], [#delta(-10)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("蒯曼")], [#age(15)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2579*], [#delta(-3)],
      [77], [#name("李洁")], [#age(35)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2575*], [#delta(23)],
      [78], [#name("大藤沙月")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2570*], [#delta(-8)],
      [79], [#name("MADARASZ Dora")], [#age(26)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2569*], [#delta(14)],
      [80], [#name("小盐遥菜")], [#age(14)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2567*], [#delta(-4)],
      [81], [#name("申裕斌")], [#age(15)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2564*], [#delta(-12)],
      [82], [#name("郭雨涵")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2562*], [#delta(-2)],
      [83], [#name("YUAN Yuan")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2562*], [#delta(13)],
      [84], [#name("汉娜 马特洛娃")], [#age(29)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2561*], [#delta(-20)],
      [85], [#name("LIU Hsing-Yin")], [#age(32)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2561*], [#delta(12)],
      [86], [#name("MAEDA Miyu")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2560*], [#delta(-4)],
      [87], [#name("邵杰妮")], [#age(25)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2559*], [#delta(7)],
      [88], [#name("索菲亚 波尔卡诺娃")], [#age(25)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2557*], [#delta(2)],
      [89], [#name("浜本由惟")], [#age(21)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2552*], [#delta(-11)],
      [90], [#name("李佼")], [#age(46)], [#assoc("NED")], [#left], [#penhold], [#attack], [*2552*], [#delta(-4)],
      [91], [#name("NARUMOTO Ayami")], [#age(24)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2551*], [#delta(-4)],
      [92], [#name("苏萨西尼 萨维塔布特")], [#age(25)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2549*], [#delta(-20)],
      [93], [#name("DOLGIKH Maria")], [#age(32)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2538*], [#delta(-2)],
      [94], [#name("张安")], [#age(23)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2535*], [#delta(13)],
      [95], [#name("GRZYBOWSKA-FRANC Katarzyna")], [#age(30)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2528*], [#delta(3)],
      [96], [#name("刘炜珊")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2528*], [#delta(3)],
      [97], [#name("王 艾米")], [#age(17)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2525*], [#delta(5)],
      [98], [#name("LI Xiang")], [#age(25)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2525*], [#delta(3)],
      [99], [#name("李恩惠")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2524*], [#delta(-22)],
      [100], [#name("陈熠")], [#age(15)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2524*], [#delta(6)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("维多利亚 帕芙洛维奇")], [#age(41)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2520*], [#delta(-6)],
      [102], [#name("LIN Ye")], [#age(23)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2516*], [#delta(-10)],
      [103], [#name("KIM Youjin")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2513*], [#delta(-19)],
      [104], [#name("MIKHAILOVA Polina")], [#age(33)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2512*], [#delta(51)],
      [105], [#name("JI Eunchae")], [#age(23)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2510*], [#delta(44)],
      [106], [#name("LEE Nakyung")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2509*], [#delta(5)],
      [107], [#name("KIM Mingyung")], [#age(27)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2506*], [#delta(6)],
      [108], [#name("乔治娜 波塔")], [#age(34)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2504*], [#delta(-49)],
      [109], [#name("BAJOR Natalia")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2503*], [#delta(36)],
      [110], [#name("PARTYKA Natalia")], [#age(30)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2501*], [#delta(46)],
      [111], [#name("DODEAN Daniela")], [#age(31)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2500*], [#delta(21)],
      [112], [#name("阿德里安娜 迪亚兹")], [#age(19)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2499*], [#delta(-33)],
      [113], [#name("吴洋晨")], [#age(17)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2499*], [#delta(5)],
      [114], [#name("MA Wenting")], [#age(29)], [#assoc("NOR")], [#right], [#shakehand], [#attack], [*2499*], [#delta(3)],
      [115], [#name("HUANG Fanzhen")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2493*], [#delta(4)],
      [116], [#name("WU Yue")], [#age(29)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2492*], [#delta(4)],
      [117], [#name("HAPONOVA Hanna")], [#age(34)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2491*], [#delta(53)],
      [118], [#name("边宋京")], [#age(18)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2488*], [#delta(15)],
      [119], [#name("DIACONU Adina")], [#age(20)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2486*], [#delta(3)],
      [120], [#name("李时温")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2486*], [#delta(-4)],
      [121], [#name("VOROBEVA Olga")], [#age(29)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2484*], [#delta(-17)],
      [122], [#name("萨比亚 温特")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2483*], [#delta(1)],
      [123], [#name("伊丽莎白 萨玛拉")], [#age(30)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2482*], [#delta(-52)],
      [124], [#name("LANG Kristin")], [#age(34)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2481*], [#delta(0)],
      [125], [#name("布里特 伊尔兰德")], [#age(25)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2480*], [#delta(-37)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("LIN Chia-Hsuan")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2480*], [#delta(62)],
      [127], [#name("MATSUDAIRA Shiho")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2479*], [#delta(1)],
      [128], [#name("KIM Jiho")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2478*], [#delta(-14)],
      [129], [#name("朱成竹")], [#age(22)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2477*], [#delta(30)],
      [130], [#name("KIMURA Mitsuho")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2477*], [#delta(-3)],
      [131], [#name("STRBIKOVA Renata")], [#age(40)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2473*], [#delta(-2)],
      [132], [#name("DE NUTTE Sarah")], [#age(27)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2471*], [#delta(26)],
      [133], [#name("KOLISH Anastasia")], [#age(18)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2470*], [#delta(-2)],
      [134], [#name("SOMA Yumeno")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2461*], [#delta(-25)],
      [135], [#name("ABE Airi")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2460*], [#delta(1)],
      [136], [#name("张墨")], [#age(30)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2459*], [#delta(-53)],
      [137], [#name("玛妮卡 巴特拉")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2458*], [#delta(31)],
      [138], [#name("LAY Jian Fang")], [#age(46)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2453*], [#delta(3)],
      [139], [#name("BALAZOVA Barbora")], [#age(27)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2451*], [#delta(-36)],
      [140], [#name("TRIGOLOS Daria")], [#age(20)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2449*], [#delta(3)],
      [141], [#name("TSAI Yu-Chin")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#defense], [*2447*], [#delta(5)],
      [142], [#name("普利西卡 帕瓦德")], [#age(15)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2447*], [#delta(5)],
      [143], [#name("李昱谆")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2442*], [#delta(37)],
      [144], [#name("SOLJA Amelie")], [#age(29)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-34)],
      [145], [#name("DRAGOMAN Andreea")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2437*], [#delta(5)],
      [146], [#name("TIAN Yuan")], [#age(44)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2437*], [#delta(5)],
      [147], [#name("森田美咲")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2426*], [#delta(10)],
      [148], [#name("LAM Yee Lok")], [#age(23)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2423*], [#delta(-10)],
      [149], [#name("SU Pei-Ling")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2421*], [#delta(-44)],
      [150], [#name("ZHANG Binyue")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2420*], [#delta(10)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("CHEN Ting-Ting")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2420*], [#delta(-3)],
      [152], [#name("BRATEYKO Solomiya")], [#age(20)], [#assoc("UKR")], [#left], [#shakehand], [#attack], [*2419*], [#delta(10)],
      [153], [#name("MALANINA Maria")], [#age(21)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2418*], [#delta(12)],
      [154], [#name("LEE En-Chi")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2418*], [#delta(148)],
      [155], [#name("YU Hsiu-Ting")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2416*], [#delta(12)],
      [156], [#name("GROFOVA Karin")], [#age(25)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2414*], [#delta(13)],
      [157], [#name("MAK Tze Wing")], [#age(21)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2414*], [#delta(-20)],
      [158], [#name("LEE Ka Yee")], [#age(17)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2413*], [#delta(33)],
      [159], [#name("RYU Hanna")], [#age(17)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2413*], [#delta(12)],
      [160], [#name("DEGRAEF Margo")], [#age(21)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2411*], [#delta(12)],
      [161], [#name("HUANG Yu-Wen")], [#age(23)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2408*], [#delta(13)],
      [162], [#name("NOSKOVA Yana")], [#age(25)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2408*], [#delta(11)],
      [163], [#name("KOMWONG Nanthana")], [#age(39)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2403*], [#delta(-9)],
      [164], [#name("KUMAHARA Luca")], [#age(24)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2402*], [#delta(13)],
      [165], [#name("奥拉万 帕拉南")], [#age(22)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2401*], [#delta(-4)],
      [166], [#name("高桥 布鲁娜")], [#age(19)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2401*], [#delta(18)],
      [167], [#name("PLAIAN Tania")], [#age(18)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2399*], [#delta(12)],
      [168], [#name("KIM Jin Hyang")], [#age(23)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2398*], [#delta(13)],
      [169], [#name("ZARIF Audrey")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2397*], [#delta(13)],
      [170], [#name("出泽杏佳")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2397*], [#delta(104)],
      [171], [#name("NAKAMORI Honami")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2396*], [#delta(-36)],
      [172], [#name("ZANG Xiaotong")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2396*], [#delta(11)],
      [173], [#name("SURJAN Sabina")], [#age(19)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2393*], [#delta(38)],
      [174], [#name("LOEUILLETTE Stephanie")], [#age(27)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2393*], [#delta(16)],
      [175], [#name("SHIOMI Maki")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2390*], [#delta(-33)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("RI Hyon Sim")], [#age(22)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2390*], [#delta(9)],
      [177], [#name("LIU Juan")], [#age(34)], [#assoc("USA")], [#left], [#penhold], [#attack], [*2389*], [#delta(9)],
      [178], [#name("苏蒂尔塔 穆克吉")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2388*], [#delta(9)],
      [179], [#name("NG Wing Nam")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2387*], [#delta(-16)],
      [180], [#name("横井咲樱")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2379*], [#delta(-4)],
      [181], [#name("TOKUNAGA Miko")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2379*], [#delta(13)],
      [182], [#name("KIM Sol Song")], [#age(25)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2378*], [#delta(11)],
      [183], [#name("KULIKOVA Olga")], [#age(26)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2375*], [#delta(13)],
      [184], [#name("BOGDANOVA Nadezhda")], [#age(19)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2373*], [#delta(21)],
      [185], [#name("FEHER Orsolya")], [#age(20)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2372*], [#delta(13)],
      [186], [#name("GASNIER Laura")], [#age(26)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2372*], [#delta(-22)],
      [187], [#name("蒂娜 梅谢芙")], [#age(25)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2371*], [#delta(-9)],
      [188], [#name("VERMAAS Kim")], [#age(23)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2371*], [#delta(-35)],
      [189], [#name("LI Ching Wan")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2370*], [#delta(-45)],
      [190], [#name("PERGEL Szandra")], [#age(31)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2370*], [#delta(-69)],
      [191], [#name("KAMATH Archana")], [#age(19)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2369*], [#delta(-2)],
      [192], [#name("郭焱")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2369*], [#delta(7)],
      [193], [#name("HO Tin-Tin")], [#age(21)], [#assoc("GBR")], [#right], [#penhold], [#attack], [*2368*], [#delta(21)],
      [194], [#name("JOKIC Tijana")], [#age(19)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2368*], [#delta(6)],
      [195], [#name("杨屹韵")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2367*], [#delta(24)],
      [196], [#name("CIOBANU Irina")], [#age(24)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2367*], [#delta(1)],
      [197], [#name("KIM Haeun")], [#age(22)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2364*], [#delta(4)],
      [198], [#name("KUO Chia-Yun")], [#age(21)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2364*], [#delta(4)],
      [199], [#name("TOLIOU Aikaterini")], [#age(24)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2359*], [#delta(-7)],
      [200], [#name("KATO Chiaki")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2357*], [#delta(4)],
    )
  )
