#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("马龙")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3121*], [#delta(0)],
      [2], [#name("张继科")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3008*], [#delta(0)],
      [3], [#name("蒂姆 波尔")], [#age(30)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2943*], [#delta(1)],
      [4], [#name("王皓")], [#age(28)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2927*], [#delta(1)],
      [5], [#name("许昕")], [#age(21)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*2910*], [#delta(3)],
      [6], [#name("王励勤")], [#age(33)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2908*], [#delta(-3)],
      [7], [#name("郝帅")], [#age(28)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2901*], [#delta(-1)],
      [8], [#name("陈玘")], [#age(27)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2838*], [#delta(1)],
      [9], [#name("闫安")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2801*], [#delta(1)],
      [10], [#name("马琳")], [#age(31)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2772*], [#delta(-3)],
      [11], [#name("朱世赫")], [#age(31)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2755*], [#delta(2)],
      [12], [#name("米凯尔 梅兹")], [#age(30)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2724*], [#delta(5)],
      [13], [#name("高宁")], [#age(29)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2723*], [#delta(33)],
      [14], [#name("博扬 托基奇")], [#age(30)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2720*], [#delta(4)],
      [15], [#name("柳承敏")], [#age(29)], [#assoc("KOR")], [#right], [#penhold], [#attack], [*2709*], [#delta(5)],
      [16], [#name("基里尔 斯卡奇科夫")], [#age(24)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2703*], [#delta(25)],
      [17], [#name("庄智渊")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2698*], [#delta(2)],
      [18], [#name("金珉鉐")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2693*], [#delta(8)],
      [19], [#name("阿德里安 马特内")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2692*], [#delta(4)],
      [20], [#name("迪米特里 奥恰洛夫")], [#age(23)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2684*], [#delta(-4)],
      [21], [#name("维尔纳 施拉格")], [#age(39)], [#assoc("AUT")], [?], [?], [?], [*2673*], [#delta(1)],
      [22], [#name("吴尚垠")], [#age(34)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2672*], [#delta(-10)],
      [23], [#name("帕特里克 鲍姆")], [#age(24)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2671*], [#delta(-9)],
      [24], [#name("水谷隼")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2649*], [#delta(-13)],
      [25], [#name("岸川圣也")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2649*], [#delta(-10)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("林高远")], [#age(16)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2647*], [#delta(3)],
      [27], [#name("李尚洙")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2636*], [#delta(-6)],
      [28], [#name("梁柱恩")], [#age(32)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2631*], [#delta(19)],
      [29], [#name("弗拉基米尔 萨姆索诺夫")], [#age(35)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2625*], [#delta(-4)],
      [30], [#name("丹羽孝希")], [#age(17)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2622*], [#delta(3)],
      [31], [#name("方博")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2615*], [#delta(-1)],
      [32], [#name("高木和卓")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2612*], [#delta(-1)],
      [33], [#name("佐兰 普里莫拉克")], [#age(42)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2608*], [#delta(-1)],
      [34], [#name("陈建安")], [#age(20)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2606*], [#delta(-10)],
      [35], [#name("亚历山大 卡拉卡谢维奇")], [#age(36)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2604*], [#delta(-1)],
      [36], [#name("若昂 蒙泰罗")], [#age(28)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2603*], [#delta(-1)],
      [37], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(31)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2601*], [#delta(-1)],
      [38], [#name("阿德里安 克里桑")], [#age(31)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2595*], [#delta(-1)],
      [39], [#name("巴斯蒂安 斯特格")], [#age(30)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2594*], [#delta(0)],
      [40], [#name("罗伯特 加尔多斯")], [#age(32)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2592*], [#delta(-2)],
      [41], [#name("YIN Hang")], [#age(16)], [#assoc("CHN")], [?], [?], [?], [*2590*], [#delta(-1)],
      [42], [#name("赵彦来")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2588*], [#delta(0)],
      [43], [#name("松平贤二")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2582*], [#delta(0)],
      [44], [#name("徐贤德")], [#age(20)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2581*], [#delta(0)],
      [45], [#name("卢文 菲鲁斯")], [#age(23)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2573*], [#delta(0)],
      [46], [#name("诺沙迪 阿拉米扬")], [#age(20)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2566*], [#delta(2)],
      [47], [#name("里卡多 瓦尔特")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2563*], [#delta(4)],
      [48], [#name("马克斯 弗雷塔斯")], [#age(23)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2560*], [#delta(4)],
      [49], [#name("吉村真晴")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2557*], [#delta(16)],
      [50], [#name("何志文")], [#age(49)], [#assoc("ESP")], [#left], [#penhold], [#attack], [*2556*], [#delta(3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("李廷佑")], [#age(27)], [#assoc("KOR")], [#left], [#penhold], [#attack], [*2556*], [#delta(3)],
      [52], [#name("西蒙 高兹")], [#age(17)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2552*], [#delta(-3)],
      [53], [#name("松平健太")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2546*], [#delta(24)],
      [54], [#name("丹尼尔 哈贝松")], [#age(25)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2544*], [#delta(1)],
      [55], [#name("巴托什 苏赫")], [#age(28)], [#assoc("POL")], [?], [?], [?], [*2541*], [#delta(2)],
      [56], [#name("克里斯蒂安 苏斯")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2538*], [#delta(2)],
      [57], [#name("谭瑞午")], [#age(28)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2537*], [#delta(2)],
      [58], [#name("上田仁")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2535*], [#delta(3)],
      [59], [#name("笠原弘光")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2535*], [#delta(3)],
      [60], [#name("詹斯 伦德奎斯特")], [#age(32)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2533*], [#delta(3)],
      [61], [#name("蒂亚戈 阿波罗尼亚")], [#age(25)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2533*], [#delta(3)],
      [62], [#name("张成万")], [#age(26)], [#assoc("PRK")], [?], [?], [?], [*2530*], [#delta(5)],
      [63], [#name("陈卫星")], [#age(39)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2526*], [#delta(5)],
      [64], [#name("吉田海伟")], [#age(30)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2526*], [#delta(-4)],
      [65], [#name("伊戈尔 鲁布佐夫")], [#age(31)], [#assoc("RUS")], [?], [?], [?], [*2525*], [#delta(4)],
      [66], [#name("帕尔 格雷尔")], [#age(29)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2524*], [#delta(4)],
      [67], [#name("张钰")], [#age(30)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2520*], [#delta(5)],
      [68], [#name("康坦 罗比诺特")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2518*], [#delta(3)],
      [69], [#name("杨子")], [#age(27)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2515*], [#delta(-3)],
      [70], [#name("亚历山大 希巴耶夫")], [#age(21)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2515*], [#delta(3)],
      [71], [#name("ZHAN Jian")], [#age(29)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2510*], [#delta(3)],
      [72], [#name("LIU Yi")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2509*], [#delta(3)],
      [73], [#name("沙拉特 阿昌塔")], [#age(29)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2509*], [#delta(3)],
      [74], [#name("约尔根 佩尔森")], [#age(45)], [#assoc("SWE")], [?], [?], [?], [*2508*], [#delta(7)],
      [75], [#name("托马斯 凯纳特")], [#age(34)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2505*], [#delta(3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("丁祥恩")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2504*], [#delta(3)],
      [77], [#name("利亚姆 皮切福德")], [#age(18)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2504*], [#delta(3)],
      [78], [#name("阿列克谢 利文佐夫")], [#age(30)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2503*], [#delta(-22)],
      [79], [#name("陈丰")], [#age(17)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2502*], [#delta(55)],
      [80], [#name("大矢英俊")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2492*], [#delta(2)],
      [81], [#name("李虎")], [#age(23)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2490*], [#delta(2)],
      [82], [#name("德米特里 普罗科普科夫")], [#age(31)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2489*], [#delta(11)],
      [83], [#name("艾曼纽 莱贝松")], [#age(23)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2486*], [#delta(2)],
      [84], [#name("林聚")], [#age(32)], [#assoc("DOM")], [?], [?], [?], [*2483*], [#delta(2)],
      [85], [#name("阿列克谢 斯米尔诺夫")], [#age(34)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2481*], [#delta(-57)],
      [86], [#name("斯特凡 菲格尔")], [#age(23)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2477*], [#delta(2)],
      [87], [#name("约瑟夫 西蒙契克")], [#age(31)], [#assoc("CZE")], [?], [?], [?], [*2472*], [#delta(2)],
      [88], [#name("阿尔弗雷多 卡内罗斯")], [#age(33)], [#assoc("ESP")], [?], [?], [?], [*2470*], [#delta(2)],
      [89], [#name("王增羿")], [#age(28)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2466*], [#delta(3)],
      [90], [#name("黄镇廷")], [#age(20)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2460*], [#delta(8)],
      [91], [#name("奥马尔 阿萨尔")], [#age(20)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2456*], [#delta(96)],
      [92], [#name("让 米歇尔 塞弗")], [#age(42)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2456*], [#delta(2)],
      [93], [#name("安德烈 加奇尼")], [#age(25)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2454*], [#delta(3)],
      [94], [#name("卡洛斯 马查多")], [#age(31)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2454*], [#delta(3)],
      [95], [#name("张一博")], [#age(26)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2451*], [#delta(4)],
      [96], [#name("VANG Bora")], [#age(24)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2450*], [#delta(4)],
      [97], [#name("吴家骥")], [#age(16)], [#assoc("DOM")], [#right], [#penhold], [#attack], [*2448*], [#delta(-6)],
      [98], [#name("刘松")], [#age(39)], [#assoc("ARG")], [?], [?], [?], [*2447*], [#delta(-11)],
      [99], [#name("江天一")], [#age(23)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2444*], [#delta(2)],
      [100], [#name("卢博米尔 皮斯特耶")], [#age(27)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2439*], [#delta(2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("彼得 塞雷达")], [#age(27)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2438*], [#delta(2)],
      [102], [#name("佐尔坦 费杰科内斯")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2437*], [#delta(2)],
      [103], [#name("古斯塔沃 坪井")], [#age(26)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2436*], [#delta(-8)],
      [104], [#name("金赫峰")], [#age(26)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2432*], [#delta(1)],
      [105], [#name("阿兰 本特森")], [#age(43)], [#assoc("DEN")], [?], [?], [?], [*2429*], [#delta(1)],
      [106], [#name("三内贤太郎")], [#age(22)], [#assoc("JPN")], [?], [?], [?], [*2427*], [#delta(1)],
      [107], [#name("卡林尼科斯 格林卡")], [#age(39)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2423*], [#delta(1)],
      [108], [#name("米哈伊尔 派科夫")], [#age(22)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2419*], [#delta(2)],
      [109], [#name("托本 沃西克")], [#age(38)], [#assoc("GER")], [?], [?], [?], [*2417*], [#delta(2)],
      [110], [#name("威廉 亨泽尔")], [#age(29)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2417*], [#delta(27)],
      [111], [#name("丹尼尔 古拉克")], [#age(28)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2416*], [#delta(1)],
      [112], [#name("金正勋")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2414*], [#delta(1)],
      [113], [#name("唐鹏")], [#age(30)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2409*], [#delta(-29)],
      [114], [#name("雅罗斯拉夫 扎穆登科")], [#age(23)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2409*], [#delta(2)],
      [115], [#name("费奥多尔 库兹明")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2408*], [#delta(2)],
      [116], [#name("郑荣植")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2405*], [#delta(3)],
      [117], [#name("李镇权")], [#age(24)], [#assoc("KOR")], [?], [?], [?], [*2404*], [#delta(3)],
      [118], [#name("帕维尔 普拉托诺夫")], [#age(28)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2403*], [#delta(-3)],
      [119], [#name("雅库布 科索夫斯基")], [#age(29)], [#assoc("POL")], [?], [?], [?], [*2402*], [#delta(3)],
      [120], [#name("达尼埃尔 科希鲍")], [#age(20)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2402*], [#delta(53)],
      [121], [#name("周雨")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2401*], [#delta(2)],
      [122], [#name("托米斯拉夫 科拉雷克")], [#age(23)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2399*], [#delta(4)],
      [123], [#name("斯蒂芬 门格尔")], [#age(23)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2398*], [#delta(4)],
      [124], [#name("埃里克 伊拉什")], [#age(31)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2398*], [#delta(4)],
      [125], [#name("塩野真人")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2397*], [#delta(4)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("LAGOGIANNIS Konstantinos")], [#age(30)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2396*], [#delta(4)],
      [127], [#name("康斯坦丁 乔蒂")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2396*], [#delta(4)],
      [128], [#name("RUMGAY Gavin")], [#age(27)], [#assoc("SCO")], [#right], [#shakehand], [#attack], [*2395*], [#delta(-3)],
      [129], [#name("彼得 科贝尔")], [#age(40)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2392*], [#delta(3)],
      [130], [#name("松本和雄")], [#age(26)], [#assoc("BRA")], [#left], [#penhold], [#attack], [*2391*], [#delta(25)],
      [131], [#name("亚历山大 迪杜赫")], [#age(29)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2391*], [#delta(2)],
      [132], [#name("卢博米尔 扬察里克")], [#age(24)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2387*], [#delta(3)],
      [133], [#name("LI Kewei")], [#age(31)], [#assoc("MLT")], [?], [?], [?], [*2387*], [#delta(3)],
      [134], [#name("村松雄斗")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2383*], [#delta(75)],
      [135], [#name("HUNG Tzu-Hsiang")], [#age(17)], [#assoc("TPE")], [#right], [#penhold], [#attack], [*2383*], [#delta(-14)],
      [136], [#name("帕维尔 费尔蒂科夫斯基")], [#age(21)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2379*], [#delta(2)],
      [137], [#name("格里戈里 弗拉索夫")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2378*], [#delta(2)],
      [138], [#name("米哈伊 博博奇卡")], [#age(25)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2376*], [#delta(2)],
      [139], [#name("尹在荣")], [#age(28)], [#assoc("KOR")], [?], [?], [?], [*2374*], [#delta(2)],
      [140], [#name("下山隆敬")], [#age(26)], [#assoc("JPN")], [?], [?], [?], [*2374*], [#delta(2)],
      [141], [#name("亚诺什 雅各布")], [#age(25)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2372*], [#delta(9)],
      [142], [#name("吉田雅己")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2372*], [#delta(1)],
      [143], [#name("李静")], [#age(36)], [#assoc("HKG")], [?], [?], [?], [*2371*], [#delta(1)],
      [144], [#name("马尔科 耶夫托维奇")], [#age(24)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2369*], [#delta(1)],
      [145], [#name("HIGASHI Yuto")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2369*], [#delta(1)],
      [146], [#name("尼亚戈尔 斯托亚诺夫")], [#age(24)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2368*], [#delta(1)],
      [147], [#name("帕维尔 西鲁切克")], [#age(19)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2368*], [#delta(1)],
      [148], [#name("帕特里克 弗朗西斯卡")], [#age(19)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2366*], [#delta(1)],
      [149], [#name("马科斯 马德里")], [#age(25)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2365*], [#delta(-35)],
      [150], [#name("达米安 埃洛伊")], [#age(42)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2363*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("马蒂斯 布尔吉斯")], [#age(22)], [#assoc("LAT")], [#right], [#shakehand], [#attack], [*2362*], [#delta(1)],
      [152], [#name("PETIOT Jeremy")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2356*], [#delta(-43)],
      [153], [#name("KIM Nam Chol")], [#age(23)], [#assoc("PRK")], [?], [?], [?], [*2354*], [#delta(1)],
      [154], [#name("安德烈 菲利蒙")], [#age(34)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2352*], [#delta(2)],
      [155], [#name("佐尔特 佩托")], [#age(24)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2351*], [#delta(2)],
      [156], [#name("亚当 帕塔纽什")], [#age(33)], [#assoc("HUN")], [#right], [#shakehand], [#defense], [*2351*], [#delta(-38)],
      [157], [#name("叶夫根尼 齐特切蒂宁")], [#age(41)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2350*], [#delta(1)],
      [158], [#name("BARDON Michal")], [#age(33)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2348*], [#delta(2)],
      [159], [#name("尚坤")], [#age(21)], [#assoc("CHN")], [?], [?], [?], [*2348*], [#delta(2)],
      [160], [#name("特里斯坦 弗洛雷")], [#age(16)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2346*], [#delta(17)],
      [161], [#name("乔恩 佩尔森")], [#age(25)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2341*], [#delta(1)],
      [162], [#name("罗伯特 斯文松")], [#age(28)], [#assoc("SWE")], [?], [?], [?], [*2341*], [#delta(1)],
      [163], [#name("LIU Yanan")], [#age(17)], [#assoc("CHN")], [?], [?], [?], [*2341*], [#delta(1)],
      [164], [#name("KIM Song Nam")], [#age(19)], [#assoc("PRK")], [?], [?], [?], [*2340*], [#delta(1)],
      [165], [#name("LEE Junsang")], [#age(21)], [#assoc("KOR")], [?], [?], [?], [*2338*], [#delta(2)],
      [166], [#name("MARTINEZ Michel")], [#age(32)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2338*], [#delta(51)],
      [167], [#name("金泰勋")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2337*], [#delta(1)],
      [168], [#name("STORF Martin")], [#age(22)], [#assoc("AUT")], [?], [?], [?], [*2335*], [#delta(1)],
      [169], [#name("托马斯 科涅茨尼")], [#age(26)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2334*], [#delta(1)],
      [170], [#name("瓦西里 拉凯耶夫")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2334*], [#delta(1)],
      [171], [#name("安德鲁 巴格利")], [#age(28)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2333*], [#delta(-12)],
      [172], [#name("吴志祺")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2333*], [#delta(0)],
      [173], [#name("赫苏斯 坎特罗")], [#age(29)], [#assoc("ESP")], [#right], [#penhold], [#attack], [*2332*], [#delta(2)],
      [174], [#name("奥维迪乌 伊奥内斯库")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2331*], [#delta(2)],
      [175], [#name("艾哈迈德 萨利赫")], [#age(32)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2331*], [#delta(-9)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("李良夫")], [#age(20)], [#assoc("TUR")], [#left], [#shakehand], [#attack], [*2325*], [#delta(2)],
      [177], [#name("DURANSPAHIC Admir")], [#age(24)], [#assoc("BIH")], [#right], [#shakehand], [#attack], [*2325*], [#delta(57)],
      [178], [#name("安东宁 加夫拉斯")], [#age(26)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2324*], [#delta(1)],
      [179], [#name("黄圣盛")], [#age(24)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2324*], [#delta(1)],
      [180], [#name("阿卜杜勒-卡德尔 萨利富")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2323*], [#delta(1)],
      [181], [#name("安迪 佩雷拉")], [#age(22)], [#assoc("CUB")], [#left], [#shakehand], [#attack], [*2321*], [#delta(1)],
      [182], [#name("HORVAT Mitja")], [#age(33)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2318*], [#delta(2)],
      [183], [#name("JUZBASIC Ivan")], [#age(31)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2317*], [#delta(3)],
      [184], [#name("王臻")], [#age(26)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2316*], [#delta(4)],
      [185], [#name("克里斯托夫 勒古")], [#age(38)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2315*], [#delta(73)],
      [186], [#name("GOLEBIOWSKI Mateusz")], [#age(21)], [#assoc("POL")], [?], [?], [?], [*2315*], [#delta(3)],
      [187], [#name("BROSSIER Benjamin")], [#age(17)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2314*], [#delta(58)],
      [188], [#name("克里斯坦 卡尔松")], [#age(20)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2311*], [#delta(-35)],
      [189], [#name("彼得 法泽卡斯")], [#age(30)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2308*], [#delta(1)],
      [190], [#name("FLORITZ Philipp")], [#age(20)], [#assoc("BUL")], [#right], [#shakehand], [#attack], [*2307*], [#delta(1)],
      [191], [#name("金东贤")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2307*], [#delta(-17)],
      [192], [#name("埃尔萨伊德 拉辛")], [#age(31)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2306*], [#delta(-7)],
      [193], [#name("古德蒙迪 斯蒂芬森")], [#age(29)], [#assoc("ISL")], [?], [?], [?], [*2305*], [#delta(-1)],
      [194], [#name("马克 杜兰")], [#age(25)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2305*], [#delta(-1)],
      [195], [#name("叶夫根 普里施切帕")], [#age(26)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2304*], [#delta(-1)],
      [196], [#name("郑培峰")], [#age(15)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2304*], [#delta(10)],
      [197], [#name("寇磊")], [#age(24)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2303*], [#delta(-2)],
      [198], [#name("康斯坦丁诺斯 帕帕乔治乌")], [#age(32)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2302*], [#delta(-2)],
      [199], [#name("MORIMOTO Kohei")], [#age(20)], [#assoc("JPN")], [?], [?], [?], [*2294*], [#delta(-2)],
      [200], [#name("托马斯 特雷格勒")], [#age(21)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2294*], [#delta(-76)],
    )
  )
