#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("丁宁")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*3004*], [#delta(0)],
      [2], [#name("郭焱")], [#age(29)], [#assoc("CHN")], [?], [?], [?], [*2962*], [#delta(0)],
      [3], [#name("李晓霞")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2925*], [#delta(0)],
      [4], [#name("武杨")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2865*], [#delta(1)],
      [5], [#name("刘诗雯")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2861*], [#delta(-1)],
      [6], [#name("范瑛")], [#age(25)], [#assoc("CHN")], [?], [?], [?], [*2829*], [#delta(1)],
      [7], [#name("郭跃")], [#age(23)], [#assoc("CHN")], [?], [?], [?], [*2785*], [#delta(-1)],
      [8], [#name("WANG Xuan")], [#age(22)], [#assoc("CHN")], [?], [?], [?], [*2755*], [#delta(20)],
      [9], [#name("冯亚兰")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2740*], [#delta(-1)],
      [10], [#name("帖雅娜")], [#age(32)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2739*], [#delta(6)],
      [11], [#name("高军")], [#age(42)], [#assoc("USA")], [?], [?], [?], [*2704*], [#delta(0)],
      [12], [#name("梁夏银")], [#age(17)], [#assoc("COR")], [#right], [#shakehand], [#attack], [*2702*], [#delta(1)],
      [13], [#name("常晨晨")], [#age(25)], [#assoc("CHN")], [?], [?], [?], [*2698*], [#delta(1)],
      [14], [#name("福原爱")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2688*], [#delta(-5)],
      [15], [#name("文佳")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2684*], [#delta(0)],
      [16], [#name("李佼")], [#age(38)], [#assoc("NED")], [#left], [#penhold], [#attack], [*2683*], [#delta(-6)],
      [17], [#name("吴佳多")], [#age(34)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2662*], [#delta(14)],
      [18], [#name("侯美玲")], [#age(22)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2654*], [#delta(1)],
      [19], [#name("维多利亚 帕夫洛维奇")], [#age(33)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2653*], [#delta(2)],
      [20], [#name("朱雨玲")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2647*], [#delta(0)],
      [21], [#name("RAO Jingwen")], [#age(26)], [#assoc("CHN")], [?], [?], [?], [*2642*], [NEW],
      [22], [#name("尹善爱")], [#age(28)], [#assoc("KOR")], [?], [?], [?], [*2641*], [#delta(31)],
      [23], [#name("李洁")], [#age(27)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2638*], [#delta(-1)],
      [24], [#name("姚彦")], [#age(23)], [#assoc("CHN")], [?], [?], [?], [*2637*], [#delta(-1)],
      [25], [#name("石贺净")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2630*], [#delta(-7)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("文炫晶")], [#age(27)], [#assoc("KOR")], [?], [?], [?], [*2629*], [#delta(-2)],
      [27], [#name("金仲")], [#age(22)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2627*], [#delta(-1)],
      [28], [#name("冯天薇")], [#age(25)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2611*], [#delta(-16)],
      [29], [#name("平野早矢香")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2611*], [#delta(-12)],
      [30], [#name("唐汭序")], [#age(30)], [#assoc("KOR")], [?], [?], [?], [*2601*], [#delta(-1)],
      [31], [#name("王越古")], [#age(31)], [#assoc("SGP")], [?], [?], [?], [*2595*], [#delta(-1)],
      [32], [#name("金景娥")], [#age(34)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2593*], [#delta(-7)],
      [33], [#name("李佳薇")], [#age(30)], [#assoc("SGP")], [?], [?], [?], [*2581*], [#delta(0)],
      [34], [#name("徐孝元")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2572*], [#delta(11)],
      [35], [#name("JIA Jun")], [#age(25)], [#assoc("CHN")], [?], [?], [?], [*2571*], [#delta(-1)],
      [36], [#name("石川佳纯")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2566*], [#delta(-9)],
      [37], [#name("朴美英")], [#age(30)], [#assoc("KOR")], [?], [?], [?], [*2561*], [#delta(-5)],
      [38], [#name("福冈春菜")], [#age(27)], [#assoc("JPN")], [?], [?], [?], [*2561*], [#delta(-2)],
      [39], [#name("李恩姬")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2551*], [#delta(-2)],
      [40], [#name("刘佳")], [#age(29)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2543*], [#delta(0)],
      [41], [#name("李晓丹")], [#age(21)], [#assoc("CHN")], [?], [?], [?], [*2542*], [#delta(3)],
      [42], [#name("埃尔卡 塞尔")], [#age(38)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2541*], [#delta(56)],
      [43], [#name("于梦雨")], [#age(22)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2536*], [#delta(-2)],
      [44], [#name("KANG Misoon")], [#age(18)], [#assoc("KOR")], [?], [?], [?], [*2535*], [#delta(-2)],
      [45], [#name("藤井宽子")], [#age(29)], [#assoc("JPN")], [?], [?], [?], [*2529*], [#delta(-6)],
      [46], [#name("安娜 蒂克米罗娃")], [#age(27)], [#assoc("RUS")], [?], [?], [?], [*2527*], [#delta(18)],
      [47], [#name("陈梦")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2526*], [#delta(-1)],
      [48], [#name("李倩")], [#age(25)], [#assoc("POL")], [#right], [#shakehand], [#defense], [*2525*], [#delta(8)],
      [49], [#name("沈燕飞")], [#age(32)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2525*], [#delta(-6)],
      [50], [#name("伊雷妮 伊万坎")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2522*], [#delta(-12)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("李皓晴")], [#age(19)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2520*], [#delta(21)],
      [52], [#name("若宫三纱子")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2520*], [#delta(-5)],
      [53], [#name("李雪")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#defense], [*2520*], [#delta(-18)],
      [54], [#name("吴雪")], [#age(31)], [#assoc("DOM")], [?], [?], [?], [*2517*], [#delta(-4)],
      [55], [#name("尼科莱塔 斯特凡诺娃")], [#age(27)], [#assoc("ITA")], [#left], [#shakehand], [#attack], [*2516*], [#delta(-7)],
      [56], [#name("木子")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2505*], [#delta(-4)],
      [57], [#name("克里斯汀 朗")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2489*], [#delta(-3)],
      [58], [#name("佩特拉 洛瓦斯")], [#age(31)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2487*], [#delta(5)],
      [59], [#name("鲁塔 帕斯考斯基涅")], [#age(34)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2487*], [#delta(-4)],
      [60], [#name("伊韦塔 瓦切诺夫斯卡")], [#age(25)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2478*], [#delta(-11)],
      [61], [#name("崔文渶")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2476*], [#delta(-4)],
      [62], [#name("黄怡桦")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2473*], [#delta(-4)],
      [63], [#name("石垣优香")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2470*], [#delta(-12)],
      [64], [#name("顾玉婷")], [#age(16)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2469*], [#delta(-4)],
      [65], [#name("乔治娜 波塔")], [#age(26)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2468*], [#delta(28)],
      [66], [#name("伊丽莎白 萨马拉")], [#age(22)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2468*], [#delta(-5)],
      [67], [#name("宋马音")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2468*], [#delta(-5)],
      [68], [#name("韦罗妮卡 帕夫洛维奇")], [#age(33)], [#assoc("BLR")], [?], [?], [?], [*2462*], [#delta(28)],
      [69], [#name("伊娃 奥多罗娃")], [#age(32)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2458*], [#delta(-3)],
      [70], [#name("克里斯蒂娜 托特")], [#age(37)], [#assoc("HUN")], [?], [?], [?], [*2456*], [#delta(-3)],
      [71], [#name("斯韦特兰娜 加尼娜")], [#age(33)], [#assoc("RUS")], [?], [?], [?], [*2452*], [#delta(0)],
      [72], [#name("倪夏莲")], [#age(48)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2446*], [#delta(-4)],
      [73], [#name("孙祯琦")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2443*], [#delta(-4)],
      [74], [#name("姜华珺")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-9)],
      [75], [#name("奥克萨娜 法德耶娃")], [#age(36)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("山梨有理")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2423*], [#delta(-2)],
      [77], [#name("埃卡特里娜 恩图拉基")], [#age(29)], [#assoc("GRE")], [?], [?], [?], [*2423*], [#delta(-2)],
      [78], [#name("朱芳")], [#age(35)], [#assoc("ESP")], [?], [?], [?], [*2422*], [#delta(-2)],
      [79], [#name("孙蓓蓓")], [#age(27)], [#assoc("SGP")], [?], [?], [?], [*2420*], [#delta(-20)],
      [80], [#name("加布里埃拉 费赫尔")], [#age(23)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2404*], [#delta(-1)],
      [81], [#name("羡宜芳")], [#age(34)], [#assoc("FRA")], [#right], [#shakehand], [#defense], [*2404*], [#delta(2)],
      [82], [#name("朴晟惠")], [#age(25)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2399*], [#delta(-1)],
      [83], [#name("雷娜塔 斯特尔比科娃")], [#age(32)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2397*], [#delta(2)],
      [84], [#name("丹妮拉 多迪安")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2397*], [#delta(-2)],
      [85], [#name("波琳娜 米哈伊洛娃")], [#age(25)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2396*], [#delta(27)],
      [86], [#name("吴颖岚")], [#age(19)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2395*], [#delta(25)],
      [87], [#name("郑怡静")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2394*], [#delta(-10)],
      [88], [#name("ZHAO Yan")], [#age(18)], [#assoc("CHN")], [?], [?], [?], [*2392*], [#delta(-4)],
      [89], [#name("金加 斯特凡斯卡")], [#age(31)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2379*], [#delta(19)],
      [90], [#name("HE Sirin")], [#age(22)], [#assoc("TUR")], [?], [?], [?], [*2374*], [#delta(40)],
      [91], [#name("塔玛拉 鲍罗斯")], [#age(34)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2369*], [#delta(-21)],
      [92], [#name("特蒂亚娜 比连科")], [#age(28)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2368*], [#delta(-4)],
      [93], [#name("卡罗尔 格伦迪施")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2365*], [#delta(1)],
      [94], [#name("艾米丽 索尔佳")], [#age(21)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2363*], [#delta(20)],
      [95], [#name("达娜 切霍娃")], [#age(28)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2358*], [#delta(12)],
      [96], [#name("娜塔莉亚 帕尔蒂卡")], [#age(22)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2355*], [#delta(-16)],
      [97], [#name("森园美咲")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2355*], [#delta(-7)],
      [98], [#name("韩杏")], [#age(22)], [#assoc("CGO")], [?], [?], [?], [*2354*], [#delta(-7)],
      [99], [#name("玛格丽塔 佩索茨卡")], [#age(20)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2354*], [#delta(-21)],
      [100], [#name("于国诗")], [#age(25)], [#assoc("HKG")], [?], [?], [?], [*2351*], [#delta(-14)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("利娜 米西科尼特")], [#age(23)], [#assoc("LTU")], [?], [?], [?], [*2344*], [#delta(-9)],
      [102], [#name("李嫱冰")], [#age(26)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2340*], [#delta(-15)],
      [103], [#name("纳迪娜 博尔迈尔")], [#age(30)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2337*], [#delta(-6)],
      [104], [#name("玛蒂尔达 埃克霍尔姆")], [#age(29)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2334*], [#delta(21)],
      [105], [#name("TANIOKA Ayuka")], [#age(17)], [#assoc("JPN")], [?], [?], [?], [*2330*], [#delta(-4)],
      [106], [#name("尤利娅 普罗霍罗娃")], [#age(24)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2329*], [#delta(-4)],
      [107], [#name("金慧星")], [#age(18)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2326*], [#delta(-3)],
      [108], [#name("AMBRUS Krisztina")], [#age(19)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2317*], [#delta(18)],
      [109], [#name("SANG Xu Stephanie")], [#age(25)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2297*], [#delta(1)],
      [110], [#name("素塔西尼 萨维塔布特")], [#age(17)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2295*], [#delta(3)],
      [111], [#name("佩特丽莎 索尔佳")], [#age(17)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2291*], [#delta(-6)],
      [112], [#name("安娜玛丽亚 埃尔德利")], [#age(26)], [#assoc("SRB")], [#right], [#shakehand], [#defense], [*2287*], [#delta(3)],
      [113], [#name("松泽茉里奈")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2286*], [#delta(-24)],
      [114], [#name("卡梅利娅 雅各布")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#defense], [*2286*], [#delta(2)],
      [115], [#name("前田美优")], [#age(15)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2286*], [#delta(2)],
      [116], [#name("凯莉 西布利")], [#age(23)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2285*], [#delta(2)],
      [117], [#name("黄淑琴")], [#age(27)], [#assoc("MAS")], [?], [?], [?], [*2284*], [#delta(2)],
      [118], [#name("玛丽娜 克拉夫琴科")], [#age(38)], [#assoc("ISR")], [#right], [#shakehand], [#attack], [*2284*], [#delta(2)],
      [119], [#name("KIM Minhee")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2282*], [#delta(2)],
      [120], [#name("加利娅 德沃拉克")], [#age(23)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2282*], [#delta(-17)],
      [121], [#name("安德烈娅 巴库拉")], [#age(30)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2282*], [#delta(1)],
      [122], [#name("朴英淑")], [#age(23)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2280*], [#delta(2)],
      [123], [#name("KUMARESAN Shamini")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2279*], [#delta(51)],
      [124], [#name("HANFFOU Sarah")], [#age(25)], [#assoc("CMR")], [#right], [#shakehand], [#attack], [*2272*], [#delta(-1)],
      [125], [#name("亚娜 诺斯科娃")], [#age(17)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2270*], [#delta(16)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("洪剑芳")], [#age(38)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2265*], [#delta(1)],
      [127], [#name("叶连娜 季米娜")], [#age(42)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2263*], [#delta(1)],
      [128], [#name("布里特 伊尔兰德")], [#age(17)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2263*], [#delta(15)],
      [129], [#name("萨宾 温特")], [#age(19)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2260*], [#delta(-30)],
      [130], [#name("李瑨丽")], [#age(34)], [#assoc("NZL")], [?], [?], [?], [*2260*], [#delta(-1)],
      [131], [#name("李依真")], [#age(24)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2260*], [#delta(-25)],
      [132], [#name("米艾 斯科娃")], [#age(25)], [#assoc("DEN")], [#right], [#shakehand], [#attack], [*2256*], [#delta(-23)],
      [133], [#name("田代早纪")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2255*], [#delta(7)],
      [134], [#name("安德里亚 托多罗维奇")], [#age(19)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2253*], [#delta(-2)],
      [135], [#name("张墨")], [#age(22)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2252*], [#delta(36)],
      [136], [#name("伯纳黛特 斯佐科斯")], [#age(16)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2249*], [#delta(-3)],
      [137], [#name("琳达 克雷默斯")], [#age(26)], [#assoc("NED")], [?], [?], [?], [*2247*], [#delta(-3)],
      [138], [#name("谭文玲")], [#age(39)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2247*], [#delta(-3)],
      [139], [#name("LI Isabelle Siyun")], [#age(17)], [#assoc("SGP")], [#right], [#shakehand], [#defense], [*2246*], [#delta(6)],
      [140], [#name("MATZKE Laura")], [#age(23)], [#assoc("GER")], [?], [?], [?], [*2245*], [#delta(-4)],
      [141], [#name("桑德拉 佩尔格尔")], [#age(23)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2240*], [#delta(-4)],
      [142], [#name("索菲亚 波尔卡诺娃")], [#age(17)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2239*], [#delta(-3)],
      [143], [#name("徐洁")], [#age(29)], [#assoc("POL")], [?], [?], [?], [*2239*], [#delta(-43)],
      [144], [#name("马莉薇")], [#age(28)], [#assoc("MAS")], [#right], [#shakehand], [#attack], [*2234*], [#delta(-2)],
      [145], [#name("林佳慧")], [#age(24)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2231*], [#delta(-1)],
      [146], [#name("田原")], [#age(36)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2231*], [#delta(5)],
      [147], [#name("萨拉 拉米雷斯")], [#age(24)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2225*], [#delta(-52)],
      [148], [#name("玛丽亚 多尔吉赫")], [#age(24)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2225*], [#delta(-2)],
      [149], [#name("DUBKOVA Elena")], [#age(20)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2223*], [#delta(-11)],
      [150], [#name("亚迪拉 席尔瓦")], [#age(26)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2222*], [#delta(10)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("叶莲娜 库兹米娜")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2217*], [#delta(-3)],
      [152], [#name("张蔷")], [#age(17)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2215*], [#delta(-3)],
      [153], [#name("韩莹")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2215*], [#delta(-3)],
      [154], [#name("YOON Suwon")], [#age(28)], [#assoc("KOR")], [?], [?], [?], [*2214*], [#delta(-2)],
      [155], [#name("LEE Hyun")], [#age(19)], [#assoc("KOR")], [?], [?], [?], [*2211*], [#delta(-2)],
      [156], [#name("DEDERKO Zhenhua")], [#age(34)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2210*], [#delta(-2)],
      [157], [#name("KRIEGHOFF Anna")], [#age(17)], [#assoc("GER")], [?], [?], [?], [*2210*], [#delta(-2)],
      [158], [#name("陈思羽")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2209*], [#delta(-2)],
      [159], [#name("KUSINSKA Klaudia")], [#age(18)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2209*], [#delta(68)],
      [160], [#name("JO Yujin")], [#age(19)], [#assoc("KOR")], [?], [?], [?], [*2207*], [#delta(44)],
      [161], [#name("李佳燚")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2206*], [#delta(-4)],
      [162], [#name("熊乃仪")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2203*], [#delta(-4)],
      [163], [#name("金宋依")], [#age(17)], [#assoc("COR")], [#right], [#shakehand], [#defense], [*2203*], [#delta(-4)],
      [164], [#name("KREKINA Svetlana")], [#age(30)], [#assoc("RUS")], [?], [?], [?], [*2202*], [#delta(-3)],
      [165], [#name("伊琳娜 乔巴努")], [#age(16)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2201*], [#delta(-3)],
      [166], [#name("尤利娅 内库拉")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2200*], [#delta(-3)],
      [167], [#name("LIU Na")], [#age(28)], [#assoc("IRL")], [?], [?], [?], [*2200*], [#delta(9)],
      [168], [#name("奥尔加 沃罗贝娃")], [#age(21)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2199*], [#delta(-4)],
      [169], [#name("LI Bin")], [#age(23)], [#assoc("HUN")], [?], [?], [?], [*2198*], [#delta(-4)],
      [170], [#name("乔安娜 德林克霍尔")], [#age(24)], [#assoc("ENG")], [#right], [#shakehand], [#defense], [*2197*], [#delta(-4)],
      [171], [#name("MUHLBACH Kathrin")], [#age(19)], [#assoc("GER")], [?], [?], [?], [*2195*], [#delta(-1)],
      [172], [#name("汉娜 哈珀诺娃")], [#age(26)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2193*], [#delta(-4)],
      [173], [#name("宋惠佳")], [#age(16)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2193*], [#delta(-4)],
      [174], [#name("多拉 马达拉斯")], [#age(18)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2190*], [#delta(-43)],
      [175], [#name("GUAN Mengyuan")], [#age(19)], [#assoc("HKG")], [?], [?], [?], [*2189*], [#delta(56)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("科尔内莉亚 莫尔纳")], [#age(28)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2189*], [#delta(-4)],
      [177], [#name("KOLTSOVA Anastasia")], [#age(24)], [#assoc("RUS")], [?], [?], [?], [*2177*], [#delta(-30)],
      [178], [#name("肖瑶茜")], [#age(17)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2177*], [#delta(22)],
      [179], [#name("马丁娜 波哈尔")], [#age(30)], [#assoc("SLO")], [?], [?], [?], [*2176*], [#delta(18)],
      [180], [#name("VORONOVA Anastasia")], [#age(26)], [#assoc("RUS")], [?], [?], [?], [*2172*], [#delta(60)],
      [181], [#name("YANG Fen")], [#age(29)], [#assoc("CGO")], [?], [?], [?], [*2171*], [#delta(-6)],
      [182], [#name("SIN Hye Song")], [#age(18)], [#assoc("PRK")], [?], [?], [?], [*2167*], [#delta(-5)],
      [183], [#name("金贞弦")], [#age(26)], [#assoc("KOR")], [?], [?], [?], [*2165*], [#delta(-5)],
      [184], [#name("金玟耿")], [#age(19)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2158*], [#delta(-4)],
      [185], [#name("HWANG Jina")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2157*], [#delta(-4)],
      [186], [#name("阿尼萨拉 穆昂苏克")], [#age(35)], [#assoc("THA")], [?], [?], [?], [*2157*], [#delta(-4)],
      [187], [#name("卡特琳娜 佩卡沃娃")], [#age(24)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2154*], [#delta(-4)],
      [188], [#name("藤井优子")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2153*], [#delta(-4)],
      [189], [#name("奥菲昂 埃德姆")], [#age(25)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2152*], [#delta(-4)],
      [190], [#name("SZCZERKOWSKA Magdalena")], [#age(19)], [#assoc("POL")], [?], [?], [?], [*2151*], [#delta(-17)],
      [191], [#name("KNEZEVIC Monika")], [#age(21)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2151*], [#delta(-5)],
      [192], [#name("KIM Mijeong")], [#age(22)], [#assoc("KOR")], [?], [?], [?], [*2149*], [#delta(-5)],
      [193], [#name("DOBREVA Polina")], [#age(19)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2148*], [#delta(-5)],
      [194], [#name("TIMINA Yana")], [#age(36)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2147*], [#delta(-5)],
      [195], [#name("卡塔日娜 格日博夫斯卡-弗朗茨")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2147*], [#delta(-28)],
      [196], [#name("卡塔琳娜 加京斯卡")], [#age(41)], [#assoc("BUL")], [?], [?], [?], [*2146*], [#delta(-6)],
      [197], [#name("梅塞德丝 纳吉瓦劳迪")], [#age(17)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2140*], [#delta(-6)],
      [198], [#name("MOON Bosun")], [#age(25)], [#assoc("KOR")], [?], [?], [?], [*2138*], [#delta(-4)],
      [199], [#name("LIU Xi")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2137*], [#delta(-4)],
      [200], [#name("劳拉 加斯尼尔")], [#age(18)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2135*], [#delta(-7)],
    )
  )
