#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("马龙")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3176*], [#delta(0)],
      [2], [#name("樊振东")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3035*], [#delta(0)],
      [3], [#name("张继科")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3023*], [#delta(1)],
      [4], [#name("迪米特里 奥恰洛夫")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2989*], [#delta(1)],
      [5], [#name("许昕")], [#age(26)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*2975*], [#delta(-2)],
      [6], [#name("黄镇廷")], [#age(25)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2867*], [#delta(9)],
      [7], [#name("水谷隼")], [#age(27)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2855*], [#delta(7)],
      [8], [#name("方博")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2853*], [#delta(-1)],
      [9], [#name("闫安")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2843*], [#delta(-1)],
      [10], [#name("唐鹏")], [#age(35)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2823*], [#delta(15)],
      [11], [#name("梁靖崑")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2806*], [#delta(-2)],
      [12], [#name("尚坤")], [#age(26)], [#assoc("CHN")], [?], [?], [?], [*2801*], [#delta(-2)],
      [13], [#name("庄智渊")], [#age(35)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2795*], [#delta(-7)],
      [14], [#name("吉田海伟")], [#age(35)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2791*], [#delta(-3)],
      [15], [#name("弗拉基米尔 萨姆索诺夫")], [#age(40)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2771*], [#delta(1)],
      [16], [#name("吉村真晴")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2762*], [#delta(19)],
      [17], [#name("利亚姆 皮切福德")], [#age(23)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2757*], [#delta(67)],
      [18], [#name("周雨")], [#age(24)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2754*], [#delta(-1)],
      [19], [#name("雨果 卡尔德拉诺")], [#age(20)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2725*], [#delta(80)],
      [20], [#name("夸德里 阿鲁纳")], [#age(28)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2719*], [#delta(2)],
      [21], [#name("马蒂亚斯 法尔克")], [#age(25)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2715*], [#delta(13)],
      [22], [#name("朱世赫")], [#age(36)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2708*], [#delta(8)],
      [23], [#name("艾曼纽 莱贝松")], [#age(28)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2707*], [#delta(70)],
      [24], [#name("朴申赫")], [#age(23)], [#assoc("PRK")], [#left], [#penhold], [#attack], [*2705*], [#delta(46)],
      [25], [#name("安德烈 加奇尼")], [#age(30)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2704*], [#delta(3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("乔纳森 格罗斯")], [#age(24)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2701*], [#delta(-6)],
      [27], [#name("GERELL Par")], [#age(34)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2700*], [#delta(5)],
      [28], [#name("西蒙 高兹")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2699*], [#delta(15)],
      [29], [#name("李尚洙")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2698*], [#delta(22)],
      [30], [#name("李廷佑")], [#age(32)], [#assoc("KOR")], [#left], [#penhold], [#attack], [*2696*], [#delta(-3)],
      [31], [#name("LI Ahmet")], [#age(25)], [#assoc("TUR")], [#left], [#shakehand], [#attack], [*2688*], [#delta(18)],
      [32], [#name("松平健太")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2686*], [#delta(6)],
      [33], [#name("蒂亚戈 阿波罗尼亚")], [#age(30)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2685*], [#delta(6)],
      [34], [#name("村松雄斗")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2679*], [#delta(3)],
      [35], [#name("贝内迪克特 杜达")], [#age(22)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2673*], [#delta(56)],
      [36], [#name("李平")], [#age(30)], [#assoc("QAT")], [#right], [#shakehand], [#attack], [*2673*], [#delta(6)],
      [37], [#name("HO Kwan Kit")], [#age(19)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2672*], [#delta(105)],
      [38], [#name("马克斯 弗雷塔斯")], [#age(28)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2670*], [#delta(-9)],
      [39], [#name("大岛祐哉")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2665*], [#delta(-27)],
      [40], [#name("奥马尔 阿萨尔")], [#age(25)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2660*], [#delta(7)],
      [41], [#name("克里斯坦 卡尔松")], [#age(25)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2659*], [#delta(-18)],
      [42], [#name("亚历山大 希巴耶夫")], [#age(26)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2653*], [#delta(-21)],
      [43], [#name("周恺")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2649*], [#delta(1)],
      [44], [#name("森园政崇")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2648*], [#delta(-18)],
      [45], [#name("斯特凡 菲格尔")], [#age(28)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2647*], [#delta(-9)],
      [46], [#name("ACHANTA Sharath")], [#age(34)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2647*], [#delta(83)],
      [47], [#name("上田仁")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2646*], [#delta(-1)],
      [48], [#name("雅克布 迪亚斯")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2646*], [#delta(50)],
      [49], [#name("陈卫星")], [#age(44)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2642*], [#delta(1)],
      [50], [#name("刘丁硕")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2637*], [#delta(2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("巴斯蒂安 斯蒂格")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2633*], [#delta(4)],
      [52], [#name("汪洋")], [#age(22)], [#assoc("SVK")], [#right], [#shakehand], [#defense], [*2631*], [#delta(-34)],
      [53], [#name("WALTHER Ricardo")], [#age(25)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2629*], [#delta(0)],
      [54], [#name("丹羽孝希")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2626*], [#delta(-30)],
      [55], [#name("佐兰 普里莫拉克")], [#age(47)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2626*], [#delta(111)],
      [56], [#name("塩野真人")], [#age(30)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2621*], [#delta(0)],
      [57], [#name("达米安 艾洛伊")], [#age(47)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2618*], [#delta(0)],
      [58], [#name("王臻")], [#age(31)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2618*], [#delta(8)],
      [59], [#name("HIELSCHER Lars")], [#age(37)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2617*], [#delta(-1)],
      [60], [#name("张禹珍")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2616*], [#delta(3)],
      [61], [#name("丁祥恩")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2614*], [#delta(18)],
      [62], [#name("薛飞")], [#age(17)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2613*], [#delta(-2)],
      [63], [#name("罗伯特 加尔多斯")], [#age(37)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2612*], [#delta(19)],
      [64], [#name("帕特里克 弗朗西斯卡")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2611*], [#delta(-31)],
      [65], [#name("吉田雅己")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2610*], [#delta(-4)],
      [66], [#name("LI Hu")], [#age(28)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2606*], [#delta(-1)],
      [67], [#name("TSUBOI Gustavo")], [#age(31)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2605*], [#delta(-19)],
      [68], [#name("PERSSON Jon")], [#age(30)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2605*], [#delta(63)],
      [69], [#name("郑荣植")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2602*], [#delta(-28)],
      [70], [#name("雅罗斯列夫 扎姆登科")], [#age(28)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2602*], [#delta(104)],
      [71], [#name("MACHADO Carlos")], [#age(36)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2602*], [#delta(4)],
      [72], [#name("卢文 菲鲁斯")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2602*], [#delta(-10)],
      [73], [#name("MACHI Asuka")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2601*], [#delta(-6)],
      [74], [#name("LAKEEV Vasily")], [#age(32)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2600*], [#delta(-6)],
      [75], [#name("TORIOLA Segun")], [#age(42)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2596*], [#delta(84)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("王楚钦")], [#age(16)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2590*], [#delta(0)],
      [77], [#name("OUAICHE Stephane")], [#age(23)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2589*], [#delta(0)],
      [78], [#name("奥维迪乌 伊奥内斯库")], [#age(27)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2587*], [#delta(57)],
      [79], [#name("MONTEIRO Thiago")], [#age(35)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2586*], [#delta(57)],
      [80], [#name("博扬 托基奇")], [#age(35)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2586*], [#delta(30)],
      [81], [#name("ZHAI Yujia")], [#age(21)], [#assoc("DEN")], [#right], [#shakehand], [#attack], [*2582*], [#delta(-12)],
      [82], [#name("林高远")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2580*], [#delta(1)],
      [83], [#name("GERALDO Joao")], [#age(21)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2578*], [#delta(3)],
      [84], [#name("何志文")], [#age(54)], [#assoc("ESP")], [#left], [#penhold], [#attack], [*2578*], [#delta(18)],
      [85], [#name("ROBINOT Quentin")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2577*], [#delta(11)],
      [86], [#name("阿德里安 马特内")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2566*], [#delta(1)],
      [87], [#name("CHOE Il")], [#age(23)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2566*], [#delta(-14)],
      [88], [#name("KIM Minhyeok")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2565*], [#delta(0)],
      [89], [#name("VLASOV Grigory")], [#age(32)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2561*], [#delta(17)],
      [90], [#name("蒂姆 波尔")], [#age(35)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2559*], [#delta(-71)],
      [91], [#name("基里尔 格拉西缅科")], [#age(20)], [#assoc("KAZ")], [#right], [#shakehand], [#attack], [*2558*], [#delta(92)],
      [92], [#name("尼马 阿拉米安")], [#age(24)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2557*], [#delta(17)],
      [93], [#name("高宁")], [#age(34)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2556*], [#delta(2)],
      [94], [#name("林钟勋")], [#age(19)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2556*], [#delta(26)],
      [95], [#name("GHOSH Soumyajit")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2553*], [#delta(-24)],
      [96], [#name("SODERLUND Hampus")], [#age(22)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2550*], [#delta(4)],
      [97], [#name("SEO Hyundeok")], [#age(25)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2550*], [#delta(4)],
      [98], [#name("MIKUTIS Tomas")], [#age(23)], [#assoc("LTU")], [#right], [#shakehand], [#defense], [*2549*], [#delta(111)],
      [99], [#name("PATTANTYUS Adam")], [#age(38)], [#assoc("HUN")], [#right], [#shakehand], [#defense], [*2547*], [#delta(56)],
      [100], [#name("金珉锡")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2543*], [#delta(3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("詹斯 伦德奎斯特")], [#age(37)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2543*], [#delta(3)],
      [102], [#name("MATSUDAIRA Kenji")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2543*], [#delta(3)],
      [103], [#name("KANG Dongsoo")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2540*], [#delta(4)],
      [104], [#name("赵胜敏")], [#age(18)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2540*], [#delta(4)],
      [105], [#name("GORAK Daniel")], [#age(33)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2537*], [#delta(32)],
      [106], [#name("江天一")], [#age(28)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2532*], [#delta(-17)],
      [107], [#name("CANTERO Jesus")], [#age(34)], [#assoc("ESP")], [#right], [#penhold], [#attack], [*2529*], [#delta(-17)],
      [108], [#name("ZHU Cheng")], [#age(19)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2528*], [#delta(5)],
      [109], [#name("吉村和弘")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2527*], [#delta(5)],
      [110], [#name("哈米特 德赛")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2525*], [#delta(22)],
      [111], [#name("SAMBE Kohei")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2525*], [#delta(-37)],
      [112], [#name("寇磊")], [#age(29)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2523*], [#delta(-53)],
      [113], [#name("MATSUMOTO Cazuo")], [#age(31)], [#assoc("BRA")], [#left], [#penhold], [#attack], [*2520*], [#delta(69)],
      [114], [#name("MONTEIRO Joao")], [#age(33)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2519*], [#delta(-101)],
      [115], [#name("GNANASEKARAN Sathiyan")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2516*], [#delta(4)],
      [116], [#name("陈建安")], [#age(25)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2514*], [#delta(-52)],
      [117], [#name("SZOCS Hunor")], [#age(24)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2505*], [#delta(10)],
      [118], [#name("KONECNY Tomas")], [#age(31)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2504*], [#delta(40)],
      [119], [#name("TAKAKIWA Taku")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2504*], [#delta(4)],
      [120], [#name("FERTIKOWSKI Pawel")], [#age(26)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2504*], [#delta(4)],
      [121], [#name("DRINKHALL Paul")], [#age(26)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2502*], [#delta(-9)],
      [122], [#name("BROSSIER Benjamin")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2500*], [#delta(-28)],
      [123], [#name("TANVIRIYAVECHAKUL Padasak")], [#age(20)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2499*], [#delta(128)],
      [124], [#name("特里斯坦 弗洛雷")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2499*], [#delta(-43)],
      [125], [#name("SAKAI Asuka")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2499*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("及川瑞基")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2499*], [#delta(78)],
      [127], [#name("米凯尔 梅兹")], [#age(35)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2499*], [#delta(1)],
      [128], [#name("DEVOS Robin")], [#age(22)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2496*], [#delta(-50)],
      [129], [#name("斯蒂芬 门格尔")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2496*], [#delta(-49)],
      [130], [#name("帕特里克 鲍姆")], [#age(29)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2495*], [#delta(0)],
      [131], [#name("OBESLO Michal")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2494*], [#delta(2)],
      [132], [#name("谭瑞午")], [#age(33)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2490*], [#delta(-16)],
      [133], [#name("贝内德克 奥拉")], [#age(25)], [#assoc("FIN")], [#right], [#shakehand], [#attack], [*2489*], [#delta(-22)],
      [134], [#name("德米特里 佩罗普科夫")], [#age(36)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2488*], [#delta(31)],
      [135], [#name("KEINATH Thomas")], [#age(39)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2487*], [#delta(65)],
      [136], [#name("阿尔瓦罗 罗布勒斯")], [#age(25)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2487*], [#delta(-14)],
      [137], [#name("WANG Zengyi")], [#age(33)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2485*], [#delta(-106)],
      [138], [#name("BOBOCICA Mihai")], [#age(30)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2485*], [#delta(24)],
      [139], [#name("TSUBOI Yuma")], [#age(19)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2484*], [#delta(-1)],
      [140], [#name("ROBINOT Alexandre")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2484*], [#delta(39)],
      [141], [#name("TAZOE Kenta")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2483*], [#delta(12)],
      [142], [#name("HACHARD Antoine")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2483*], [#delta(-3)],
      [143], [#name("CHEN Feng")], [#age(22)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2483*], [#delta(20)],
      [144], [#name("达科 约奇克")], [#age(18)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2482*], [#delta(59)],
      [145], [#name("NORDBERG Hampus")], [#age(29)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2481*], [#delta(-5)],
      [146], [#name("CHO Eonrae")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2480*], [#delta(-5)],
      [147], [#name("BAIBULDIN Andrei")], [#age(30)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2478*], [#delta(-4)],
      [148], [#name("KOJIC Frane")], [#age(24)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2478*], [#delta(-33)],
      [149], [#name("托米斯拉夫 普卡")], [#age(20)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2477*], [#delta(82)],
      [150], [#name("VRABLIK Jiri")], [#age(33)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2476*], [#delta(-6)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("PAIKOV Mikhail")], [#age(27)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2474*], [#delta(-59)],
      [152], [#name("KANG Wi Hun")], [#age(27)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2474*], [#delta(60)],
      [153], [#name("AKKUZU Can")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2473*], [#delta(-7)],
      [154], [#name("安东 卡尔伯格")], [#age(19)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2472*], [#delta(-100)],
      [155], [#name("TREGLER Tomas")], [#age(26)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2471*], [#delta(-8)],
      [156], [#name("KIM Donghyun")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2470*], [#delta(-7)],
      [157], [#name("AFANADOR Brian")], [#age(19)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2470*], [#delta(180)],
      [158], [#name("ANDERSSON Harald")], [#age(25)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2470*], [#delta(-7)],
      [159], [#name("神巧也")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2468*], [#delta(-7)],
      [160], [#name("KENJAEV Zokhid")], [#age(24)], [#assoc("UZB")], [#right], [#shakehand], [#attack], [*2468*], [#delta(175)],
      [161], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(36)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2467*], [#delta(-121)],
      [162], [#name("朴康贤")], [#age(20)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2466*], [#delta(-45)],
      [163], [#name("RECH DALDOSSO Marco")], [#age(24)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2463*], [#delta(140)],
      [164], [#name("HABESOHN Daniel")], [#age(30)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2462*], [#delta(-7)],
      [165], [#name("LAM Siu Hang")], [#age(20)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2459*], [#delta(13)],
      [166], [#name("LAKATOS Tamas")], [#age(21)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2459*], [#delta(1)],
      [167], [#name("木造勇人")], [#age(17)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2454*], [#delta(-3)],
      [168], [#name("HIRANO Yuki")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2450*], [#delta(0)],
      [169], [#name("塞德里克 纽廷克")], [#age(23)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2450*], [#delta(-24)],
      [170], [#name("KUZMIN Fedor")], [#age(33)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2448*], [#delta(-1)],
      [171], [#name("吴尚垠")], [#age(39)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2446*], [#delta(-1)],
      [172], [#name("WANG Jianan")], [#age(33)], [#assoc("CGO")], [?], [?], [?], [*2446*], [#delta(-1)],
      [173], [#name("ALTO Gaston")], [#age(31)], [#assoc("ARG")], [#right], [#shakehand], [#attack], [*2446*], [#delta(89)],
      [174], [#name("ECSEKI Nandor")], [#age(20)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2445*], [#delta(-2)],
      [175], [#name("SALIFOU Abdel-Kader")], [#age(27)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2445*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("LASHIN Elsayed")], [#age(36)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2445*], [#delta(53)],
      [177], [#name("MUTTI Leonardo")], [#age(21)], [#assoc("ITA")], [#left], [#shakehand], [#attack], [*2440*], [#delta(-23)],
      [178], [#name("PARK Chan-Hyeok")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2439*], [#delta(-3)],
      [179], [#name("PRYSHCHEPA Ievgen")], [#age(31)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2439*], [#delta(98)],
      [180], [#name("ELBEIALI Mohamed")], [#age(28)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-4)],
      [181], [#name("REED Daniel")], [#age(27)], [#assoc("ENG")], [?], [?], [?], [*2437*], [#delta(-4)],
      [182], [#name("JANCARIK Lubomir")], [#age(29)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2436*], [#delta(-97)],
      [183], [#name("SZUDI Adam")], [#age(20)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2436*], [#delta(70)],
      [184], [#name("JOUTI Eric")], [#age(22)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2435*], [#delta(-3)],
      [185], [#name("SIRUCEK Pavel")], [#age(24)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2434*], [#delta(90)],
      [186], [#name("PAPAGEORGIOU Konstantinos")], [#age(37)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2432*], [#delta(-61)],
      [187], [#name("JEAN Gregoire")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2432*], [#delta(-3)],
      [188], [#name("YANG Heng-Wei")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2431*], [#delta(1)],
      [189], [#name("WALKER Samuel")], [#age(21)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-9)],
      [190], [#name("KLEIN Dennis")], [#age(19)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2431*], [#delta(1)],
      [191], [#name("MIUCHI Kentaro")], [#age(27)], [#assoc("JPN")], [?], [?], [?], [*2428*], [#delta(1)],
      [192], [#name("BAGGALEY Andrew")], [#age(33)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2428*], [#delta(2)],
      [193], [#name("ABIODUN Bode")], [#age(36)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2427*], [#delta(136)],
      [194], [#name("TAO Wenzhang")], [#age(22)], [#assoc("USA")], [#right], [#penhold], [#attack], [*2427*], [#delta(1)],
      [195], [#name("JEVTOVIC Marko")], [#age(29)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2426*], [#delta(53)],
      [196], [#name("ZIBRAT Jan")], [#age(24)], [#assoc("SLO")], [#left], [#shakehand], [#attack], [*2426*], [#delta(101)],
      [197], [#name("CHIANG Hung-Chieh")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2426*], [#delta(-152)],
      [198], [#name("FUJIMURA Tomoya")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2426*], [#delta(-2)],
      [199], [#name("PARK Jeongwoo")], [#age(19)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2425*], [#delta(-2)],
      [200], [#name("LEE Chia-Sheng")], [#age(21)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2424*], [#delta(-2)],
    )
  )
