#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("马龙")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3119*], [#delta(0)],
      [2], [#name("许昕")], [#age(26)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*3098*], [#delta(0)],
      [3], [#name("樊振东")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3062*], [#delta(0)],
      [4], [#name("张继科")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2959*], [#delta(0)],
      [5], [#name("迪米特里 奥恰洛夫")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2949*], [#delta(0)],
      [6], [#name("水谷隼")], [#age(27)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2911*], [#delta(0)],
      [7], [#name("方博")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2855*], [#delta(0)],
      [8], [#name("闫安")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2843*], [#delta(0)],
      [9], [#name("朱世赫")], [#age(36)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2831*], [#delta(0)],
      [10], [#name("黄镇廷")], [#age(25)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2808*], [#delta(0)],
      [11], [#name("梁靖崑")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2806*], [#delta(0)],
      [12], [#name("尚坤")], [#age(26)], [#assoc("CHN")], [?], [?], [?], [*2801*], [#delta(0)],
      [13], [#name("庄智渊")], [#age(35)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2801*], [#delta(0)],
      [14], [#name("郑荣植")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2797*], [#delta(0)],
      [15], [#name("吉村真晴")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2768*], [#delta(0)],
      [16], [#name("西蒙 高兹")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2763*], [#delta(0)],
      [17], [#name("周雨")], [#age(24)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2754*], [#delta(0)],
      [18], [#name("陈建安")], [#age(25)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2754*], [#delta(0)],
      [19], [#name("唐鹏")], [#age(35)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2744*], [#delta(0)],
      [20], [#name("吉田海伟")], [#age(35)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2739*], [#delta(0)],
      [21], [#name("弗拉基米尔 萨姆索诺夫")], [#age(40)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2739*], [#delta(0)],
      [22], [#name("巴斯蒂安 斯蒂格")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2726*], [#delta(0)],
      [23], [#name("村松雄斗")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2712*], [#delta(0)],
      [24], [#name("林高远")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2704*], [#delta(1)],
      [25], [#name("松平健太")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2703*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("乔纳森 格罗斯")], [#age(24)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2702*], [#delta(1)],
      [27], [#name("李平")], [#age(30)], [#assoc("QAT")], [#right], [#shakehand], [#attack], [*2702*], [#delta(1)],
      [28], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(36)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2702*], [#delta(1)],
      [29], [#name("李尚洙")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2701*], [#delta(1)],
      [30], [#name("艾曼纽 莱贝松")], [#age(28)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2699*], [#delta(1)],
      [31], [#name("朴申赫")], [#age(23)], [#assoc("PRK")], [#left], [#penhold], [#attack], [*2698*], [#delta(-7)],
      [32], [#name("张本智和")], [#age(13)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2698*], [#delta(0)],
      [33], [#name("李廷佑")], [#age(32)], [#assoc("KOR")], [#left], [#penhold], [#attack], [*2696*], [#delta(0)],
      [34], [#name("利亚姆 皮切福德")], [#age(23)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2691*], [#delta(0)],
      [35], [#name("GERELL Par")], [#age(34)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2688*], [#delta(0)],
      [36], [#name("斯特凡 菲格尔")], [#age(28)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2684*], [#delta(0)],
      [37], [#name("马克斯 弗雷塔斯")], [#age(28)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2677*], [#delta(0)],
      [38], [#name("蒂亚戈 阿波罗尼亚")], [#age(30)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2675*], [#delta(0)],
      [39], [#name("马蒂亚斯 法尔克")], [#age(25)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2672*], [#delta(0)],
      [40], [#name("夸德里 阿鲁纳")], [#age(28)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2671*], [#delta(0)],
      [41], [#name("特里斯坦 弗洛雷")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2669*], [#delta(0)],
      [42], [#name("雨果 卡尔德拉诺")], [#age(20)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2664*], [#delta(0)],
      [43], [#name("林钟勋")], [#age(19)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2662*], [#delta(0)],
      [44], [#name("陈卫星")], [#age(44)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2656*], [#delta(0)],
      [45], [#name("安德烈 加奇尼")], [#age(30)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2653*], [#delta(0)],
      [46], [#name("周恺")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2650*], [#delta(0)],
      [47], [#name("LI Ahmet")], [#age(25)], [#assoc("TUR")], [#left], [#shakehand], [#attack], [*2644*], [#delta(0)],
      [48], [#name("MATSUDAIRA Kenji")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2644*], [#delta(0)],
      [49], [#name("雅克布 迪亚斯")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2643*], [#delta(0)],
      [50], [#name("刘丁硕")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2637*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("帕特里克 弗朗西斯卡")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2636*], [#delta(0)],
      [52], [#name("贝内德克 奥拉")], [#age(25)], [#assoc("FIN")], [#right], [#shakehand], [#attack], [*2631*], [#delta(0)],
      [53], [#name("GERALDO Joao")], [#age(21)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2630*], [#delta(0)],
      [54], [#name("汪洋")], [#age(22)], [#assoc("SVK")], [#right], [#shakehand], [#defense], [*2626*], [#delta(0)],
      [55], [#name("达米安 艾洛伊")], [#age(47)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2618*], [#delta(0)],
      [56], [#name("上田仁")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2618*], [#delta(0)],
      [57], [#name("HIELSCHER Lars")], [#age(37)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2617*], [#delta(0)],
      [58], [#name("王臻")], [#age(31)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2617*], [#delta(0)],
      [59], [#name("MATSUMOTO Cazuo")], [#age(31)], [#assoc("BRA")], [#left], [#penhold], [#attack], [*2616*], [#delta(0)],
      [60], [#name("斯蒂芬 门格尔")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2616*], [#delta(0)],
      [61], [#name("TSUBOI Gustavo")], [#age(31)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2615*], [#delta(0)],
      [62], [#name("薛飞")], [#age(17)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2613*], [#delta(0)],
      [63], [#name("TAKAKIWA Taku")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2612*], [#delta(0)],
      [64], [#name("吉田雅己")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2611*], [#delta(0)],
      [65], [#name("大岛祐哉")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2610*], [#delta(0)],
      [66], [#name("SAMBE Kohei")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2610*], [#delta(0)],
      [67], [#name("森园政崇")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2609*], [#delta(0)],
      [68], [#name("DRINKHALL Paul")], [#age(26)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2606*], [#delta(0)],
      [69], [#name("何志文")], [#age(54)], [#assoc("ESP")], [#left], [#penhold], [#attack], [*2606*], [#delta(0)],
      [70], [#name("LAKEEV Vasily")], [#age(32)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2601*], [#delta(0)],
      [71], [#name("及川瑞基")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2600*], [#delta(0)],
      [72], [#name("寇磊")], [#age(29)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2600*], [#delta(0)],
      [73], [#name("克里斯坦 卡尔松")], [#age(25)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2599*], [#delta(0)],
      [74], [#name("WALTHER Ricardo")], [#age(25)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2598*], [#delta(0)],
      [75], [#name("神巧也")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2597*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("奥马尔 阿萨尔")], [#age(25)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2597*], [#delta(0)],
      [77], [#name("亚历山大 希巴耶夫")], [#age(26)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2593*], [#delta(0)],
      [78], [#name("王楚钦")], [#age(16)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2590*], [#delta(0)],
      [79], [#name("高宁")], [#age(34)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2584*], [#delta(0)],
      [80], [#name("ACHANTA Sharath")], [#age(34)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2583*], [#delta(0)],
      [81], [#name("JANCARIK Lubomir")], [#age(29)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2582*], [#delta(0)],
      [82], [#name("罗伯特 加尔多斯")], [#age(37)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2580*], [#delta(0)],
      [83], [#name("贝内迪克特 杜达")], [#age(22)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2579*], [#delta(0)],
      [84], [#name("ROBINOT Quentin")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2579*], [#delta(0)],
      [85], [#name("TORIOLA Segun")], [#age(42)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2578*], [#delta(0)],
      [86], [#name("张禹珍")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2578*], [#delta(0)],
      [87], [#name("赵胜敏")], [#age(18)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2575*], [#delta(0)],
      [88], [#name("卢文 菲鲁斯")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2574*], [#delta(0)],
      [89], [#name("VLASOV Grigory")], [#age(32)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2572*], [#delta(0)],
      [90], [#name("PERSSON Jon")], [#age(30)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2571*], [#delta(0)],
      [91], [#name("托米斯拉夫 普卡")], [#age(20)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2571*], [#delta(0)],
      [92], [#name("雅罗斯列夫 扎姆登科")], [#age(28)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2568*], [#delta(0)],
      [93], [#name("BAI He")], [#age(29)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2567*], [#delta(0)],
      [94], [#name("博扬 托基奇")], [#age(35)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2567*], [#delta(0)],
      [95], [#name("阿德里安 马特内")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2567*], [#delta(0)],
      [96], [#name("KIM Minhyeok")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2565*], [#delta(1)],
      [97], [#name("蒂姆 波尔")], [#age(35)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2563*], [#delta(1)],
      [98], [#name("BROSSIER Benjamin")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2558*], [#delta(1)],
      [99], [#name("CASSIN Alexandre")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2554*], [#delta(17)],
      [100], [#name("ANDERSSON Harald")], [#age(25)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2553*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("GORAK Daniel")], [#age(33)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2552*], [#delta(0)],
      [102], [#name("诺沙迪 阿拉米扬")], [#age(25)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2552*], [#delta(0)],
      [103], [#name("PATTANTYUS Adam")], [#age(38)], [#assoc("HUN")], [#right], [#shakehand], [#defense], [*2551*], [#delta(0)],
      [104], [#name("丁祥恩")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2551*], [#delta(0)],
      [105], [#name("CHOE Il")], [#age(23)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2551*], [#delta(-9)],
      [106], [#name("奥维迪乌 伊奥内斯库")], [#age(27)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2550*], [#delta(-1)],
      [107], [#name("SEO Hyundeok")], [#age(25)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2550*], [#delta(-1)],
      [108], [#name("朴康贤")], [#age(20)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2549*], [#delta(-1)],
      [109], [#name("MACHI Asuka")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2546*], [#delta(-1)],
      [110], [#name("KANG Dongsoo")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2540*], [#delta(-1)],
      [111], [#name("GHOSH Soumyajit")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2539*], [#delta(-1)],
      [112], [#name("KONECNY Tomas")], [#age(31)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2537*], [#delta(-1)],
      [113], [#name("OUAICHE Stephane")], [#age(23)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2537*], [#delta(-1)],
      [114], [#name("SZUDI Adam")], [#age(20)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2535*], [#delta(-1)],
      [115], [#name("CANTERO Jesus")], [#age(34)], [#assoc("ESP")], [#right], [#penhold], [#attack], [*2529*], [#delta(-1)],
      [116], [#name("ZHU Cheng")], [#age(19)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2528*], [#delta(-1)],
      [117], [#name("吉村和弘")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2522*], [#delta(0)],
      [118], [#name("HO Kwan Kit")], [#age(19)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2520*], [#delta(0)],
      [119], [#name("帕特里克 鲍姆")], [#age(29)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2520*], [#delta(0)],
      [120], [#name("CHEN Feng")], [#age(22)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2520*], [#delta(0)],
      [121], [#name("丹羽孝希")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2519*], [#delta(0)],
      [122], [#name("阿德里安 克里桑")], [#age(36)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2518*], [#delta(0)],
      [123], [#name("尼马 阿拉米安")], [#age(24)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2517*], [#delta(0)],
      [124], [#name("SZOCS Hunor")], [#age(24)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2513*], [#delta(0)],
      [125], [#name("MACHADO Carlos")], [#age(36)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2512*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("PRYSHCHEPA Ievgen")], [#age(31)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2510*], [#delta(0)],
      [127], [#name("NORDBERG Hampus")], [#age(29)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2508*], [#delta(0)],
      [128], [#name("FERTIKOWSKI Pawel")], [#age(26)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2504*], [#delta(0)],
      [129], [#name("廖振珽")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2503*], [#delta(0)],
      [130], [#name("詹斯 伦德奎斯特")], [#age(37)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2502*], [#delta(0)],
      [131], [#name("OBESLO Michal")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2501*], [#delta(0)],
      [132], [#name("RYUZAKI Tonin")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2501*], [#delta(0)],
      [133], [#name("HACHARD Antoine")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2499*], [#delta(0)],
      [134], [#name("米凯尔 梅兹")], [#age(35)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2499*], [#delta(0)],
      [135], [#name("木造勇人")], [#age(17)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2498*], [#delta(0)],
      [136], [#name("SODERLUND Hampus")], [#age(22)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2498*], [#delta(0)],
      [137], [#name("IZUMO Takuto")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2493*], [#delta(0)],
      [138], [#name("金珉锡")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2493*], [#delta(0)],
      [139], [#name("VRABLIK Jiri")], [#age(33)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2490*], [#delta(0)],
      [140], [#name("基里尔 斯卡奇科夫")], [#age(29)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2490*], [#delta(0)],
      [141], [#name("ROBINOT Alexandre")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2489*], [#delta(0)],
      [142], [#name("哈米特 德赛")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2489*], [#delta(0)],
      [143], [#name("德米特里 佩罗普科夫")], [#age(36)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2488*], [#delta(0)],
      [144], [#name("WANG Zengyi")], [#age(33)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2488*], [#delta(0)],
      [145], [#name("基里尔 格拉西缅科")], [#age(20)], [#assoc("KAZ")], [#right], [#shakehand], [#attack], [*2486*], [#delta(0)],
      [146], [#name("KANG Wi Hun")], [#age(27)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2484*], [#delta(6)],
      [147], [#name("安东 卡尔伯格")], [#age(19)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2482*], [#delta(-1)],
      [148], [#name("TAZOE Kenta")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2480*], [#delta(-1)],
      [149], [#name("BAIBULDIN Andrei")], [#age(30)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2478*], [#delta(-1)],
      [150], [#name("WALKER Samuel")], [#age(21)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2476*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("LIVENTSOV Alexey")], [#age(35)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2476*], [#delta(-1)],
      [152], [#name("PAIKOV Mikhail")], [#age(27)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2474*], [#delta(-1)],
      [153], [#name("MONTEIRO Joao")], [#age(33)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2473*], [#delta(0)],
      [154], [#name("AKKUZU Can")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2472*], [#delta(0)],
      [155], [#name("KIM Donghyun")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2470*], [#delta(0)],
      [156], [#name("MADRID Marcos")], [#age(30)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2470*], [#delta(0)],
      [157], [#name("ALLEGRO Martin")], [#age(20)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2466*], [#delta(0)],
      [158], [#name("TREGLER Tomas")], [#age(26)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2465*], [#delta(0)],
      [159], [#name("AFANADOR Brian")], [#age(19)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2463*], [#delta(0)],
      [160], [#name("SAKAI Asuka")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2461*], [#delta(0)],
      [161], [#name("MIKUTIS Tomas")], [#age(23)], [#assoc("LTU")], [#right], [#shakehand], [#defense], [*2458*], [#delta(0)],
      [162], [#name("FLORAS Robert")], [#age(24)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2456*], [#delta(0)],
      [163], [#name("CHIANG Hung-Chieh")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2455*], [#delta(0)],
      [164], [#name("PETO Zsolt")], [#age(29)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2454*], [#delta(0)],
      [165], [#name("HIRANO Yuki")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2450*], [#delta(1)],
      [166], [#name("ISHIY Vitor")], [#age(21)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2450*], [#delta(1)],
      [167], [#name("塞德里克 纽廷克")], [#age(23)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2449*], [#delta(2)],
      [168], [#name("ZHAI Yujia")], [#age(21)], [#assoc("DEN")], [#right], [#shakehand], [#attack], [*2448*], [#delta(2)],
      [169], [#name("ALTO Gaston")], [#age(31)], [#assoc("ARG")], [#right], [#shakehand], [#attack], [*2447*], [#delta(2)],
      [170], [#name("ROBLES Alvaro")], [#age(25)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2446*], [#delta(2)],
      [171], [#name("WANG Jianan")], [#age(33)], [#assoc("CGO")], [?], [?], [?], [*2446*], [#delta(2)],
      [172], [#name("MONTEIRO Thiago")], [#age(35)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2446*], [#delta(2)],
      [173], [#name("YANG Tzu-Yi")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2446*], [#delta(2)],
      [174], [#name("SALIFOU Abdel-Kader")], [#age(27)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2445*], [#delta(2)],
      [175], [#name("CHERNOV Konstantin")], [#age(19)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2442*], [#delta(2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("DEVOS Robin")], [#age(22)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2440*], [#delta(2)],
      [177], [#name("PARK Chan-Hyeok")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2440*], [#delta(2)],
      [178], [#name("POLANSKY Tomas")], [#age(18)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2439*], [#delta(49)],
      [179], [#name("ELBEIALI Mohamed")], [#age(28)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2439*], [#delta(1)],
      [180], [#name("REED Daniel")], [#age(27)], [#assoc("ENG")], [?], [?], [?], [*2437*], [#delta(1)],
      [181], [#name("BOBOCICA Mihai")], [#age(30)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2435*], [#delta(1)],
      [182], [#name("HABESOHN Daniel")], [#age(30)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2435*], [#delta(1)],
      [183], [#name("AKERSTROM Fabian")], [#age(28)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2435*], [#delta(1)],
      [184], [#name("SEYFRIED Joe")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2434*], [#delta(-19)],
      [185], [#name("JOUTI Eric")], [#age(22)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2433*], [#delta(0)],
      [186], [#name("KOJIC Frane")], [#age(24)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2432*], [#delta(0)],
      [187], [#name("YANG Heng-Wei")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2431*], [#delta(0)],
      [188], [#name("KUZMIN Fedor")], [#age(33)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2430*], [#delta(1)],
      [189], [#name("RECH DALDOSSO Marco")], [#age(24)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2430*], [#delta(1)],
      [190], [#name("MIUCHI Kentaro")], [#age(27)], [#assoc("JPN")], [?], [?], [?], [*2429*], [#delta(1)],
      [191], [#name("KLEIN Dennis")], [#age(19)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2428*], [#delta(1)],
      [192], [#name("JEAN Gregoire")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2427*], [#delta(1)],
      [193], [#name("TAO Wenzhang")], [#age(22)], [#assoc("USA")], [#right], [#penhold], [#attack], [*2427*], [#delta(1)],
      [194], [#name("江天一")], [#age(28)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2426*], [#delta(1)],
      [195], [#name("安宰贤")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2426*], [#delta(1)],
      [196], [#name("FUJIMURA Tomoya")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2426*], [#delta(1)],
      [197], [#name("PARK Jeongwoo")], [#age(19)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2425*], [#delta(1)],
      [198], [#name("亚历山大 卡拉卡谢维奇")], [#age(41)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2423*], [#delta(1)],
      [199], [#name("SALEH Ahmed")], [#age(37)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2421*], [#delta(1)],
      [200], [#name("HWANG Minha")], [#age(17)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2421*], [#delta(1)],
    )
  )
