#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("丁宁")], [#age(26)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*3014*], [#delta(0)],
      [2], [#name("朱雨玲")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2964*], [#delta(1)],
      [3], [#name("刘诗雯")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2954*], [#delta(1)],
      [4], [#name("木子")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2948*], [#delta(-2)],
      [5], [#name("李晓霞")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2946*], [#delta(0)],
      [6], [#name("陈梦")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2944*], [#delta(0)],
      [7], [#name("武杨")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2939*], [#delta(0)],
      [8], [#name("韩莹")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2834*], [#delta(1)],
      [9], [#name("胡丽梅")], [#age(21)], [#assoc("CHN")], [#right], [#penhold], [#defense], [*2826*], [#delta(5)],
      [10], [#name("石川佳纯")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2806*], [#delta(0)],
      [11], [#name("文佳")], [#age(27)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2792*], [#delta(0)],
      [12], [#name("佩特丽莎 索尔佳")], [#age(22)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2787*], [#delta(-4)],
      [13], [#name("徐孝元")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2757*], [#delta(46)],
      [14], [#name("李佼")], [#age(43)], [#assoc("NED")], [#left], [#penhold], [#attack], [*2751*], [#delta(-2)],
      [15], [#name("福原爱")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2745*], [#delta(5)],
      [16], [#name("车晓曦")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2736*], [#delta(0)],
      [17], [#name("伊藤美诚")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2734*], [#delta(9)],
      [18], [#name("王曼昱")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2729*], [#delta(-1)],
      [19], [#name("梁夏银")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2726*], [#delta(55)],
      [20], [#name("李明顺")], [#age(24)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2721*], [#delta(1)],
      [21], [#name("帖雅娜")], [#age(37)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2715*], [#delta(14)],
      [22], [#name("若宫三纱子")], [#age(27)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2714*], [#delta(1)],
      [23], [#name("刘高阳")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2711*], [#delta(10)],
      [24], [#name("郑怡静")], [#age(24)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2702*], [#delta(14)],
      [25], [#name("伊丽莎白 萨玛拉")], [#age(27)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2697*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("傅玉")], [#age(38)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2689*], [#delta(-1)],
      [27], [#name("田志希")], [#age(24)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2686*], [#delta(-9)],
      [28], [#name("李洁")], [#age(32)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2683*], [#delta(2)],
      [29], [#name("平野美宇")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2682*], [#delta(-16)],
      [30], [#name("李皓晴")], [#age(24)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2682*], [#delta(21)],
      [31], [#name("倪夏莲")], [#age(53)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2681*], [#delta(0)],
      [32], [#name("李倩")], [#age(30)], [#assoc("POL")], [#right], [#shakehand], [#defense], [*2681*], [#delta(-4)],
      [33], [#name("MIKHAILOVA Polina")], [#age(30)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2675*], [#delta(-14)],
      [34], [#name("冯天薇")], [#age(30)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2671*], [#delta(-2)],
      [35], [#name("GU Ruochen")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2667*], [#delta(-1)],
      [36], [#name("张蔷")], [#age(22)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2655*], [#delta(3)],
      [37], [#name("PARTYKA Natalia")], [#age(27)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2652*], [#delta(10)],
      [38], [#name("单晓娜")], [#age(33)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2652*], [#delta(-9)],
      [39], [#name("浜本由惟")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2650*], [#delta(5)],
      [40], [#name("侯美玲")], [#age(27)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2649*], [#delta(-25)],
      [41], [#name("刘佳")], [#age(34)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2648*], [#delta(-19)],
      [42], [#name("崔孝珠")], [#age(18)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2645*], [#delta(-5)],
      [43], [#name("DODEAN Daniela")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2636*], [#delta(6)],
      [44], [#name("陈幸同")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2634*], [#delta(6)],
      [45], [#name("于梦雨")], [#age(27)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2632*], [#delta(-9)],
      [46], [#name("沈燕飞")], [#age(37)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2632*], [#delta(-5)],
      [47], [#name("姜华珺")], [#age(32)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2629*], [#delta(-20)],
      [48], [#name("石垣优香")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2624*], [#delta(6)],
      [49], [#name("陈可")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2620*], [#delta(-4)],
      [50], [#name("桥本帆乃香")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2620*], [#delta(454)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("顾玉婷")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2617*], [#delta(-5)],
      [52], [#name("何卓佳")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2613*], [#delta(-4)],
      [53], [#name("LI Xue")], [#age(31)], [#assoc("FRA")], [#right], [#shakehand], [#defense], [*2611*], [#delta(45)],
      [54], [#name("早田希娜")], [#age(16)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2606*], [#delta(25)],
      [55], [#name("杜凯琹")], [#age(20)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2606*], [#delta(28)],
      [56], [#name("加藤美优")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2597*], [#delta(1)],
      [57], [#name("曾尖")], [#age(20)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2594*], [#delta(54)],
      [58], [#name("佐藤瞳")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2591*], [#delta(-16)],
      [59], [#name("金宋依")], [#age(22)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2588*], [#delta(-3)],
      [60], [#name("乔治娜 波塔")], [#age(31)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2585*], [#delta(-7)],
      [61], [#name("伊莲 埃万坎")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2583*], [#delta(7)],
      [62], [#name("NG Wing Nam")], [#age(24)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2583*], [#delta(-4)],
      [63], [#name("王艺迪")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2573*], [#delta(12)],
      [64], [#name("杨晓欣")], [#age(28)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2572*], [#delta(-4)],
      [65], [#name("LIN Ye")], [#age(20)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2567*], [#delta(-25)],
      [66], [#name("SONG Maeum")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2565*], [#delta(72)],
      [67], [#name("ABE Megumi")], [#age(30)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2562*], [#delta(-2)],
      [68], [#name("吴佳多")], [#age(39)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2562*], [#delta(-2)],
      [69], [#name("BALAZOVA Barbora")], [#age(24)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2562*], [#delta(17)],
      [70], [#name("MAEDA Miyu")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2559*], [#delta(10)],
      [71], [#name("PARK Youngsook")], [#age(28)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2555*], [#delta(-16)],
      [72], [#name("陈思羽")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2553*], [#delta(-10)],
      [73], [#name("DOLGIKH Maria")], [#age(29)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2549*], [#delta(57)],
      [74], [#name("萨比亚 温特")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2547*], [#delta(3)],
      [75], [#name("MATSUZAWA Marina")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2544*], [#delta(-4)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("VACENOVSKA Iveta")], [#age(30)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2543*], [#delta(21)],
      [77], [#name("ZHOU Yihan")], [#age(22)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2541*], [#delta(12)],
      [78], [#name("LANG Kristin")], [#age(31)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2536*], [#delta(-11)],
      [79], [#name("森田美咲")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2534*], [#delta(-16)],
      [80], [#name("PESOTSKA Margaryta")], [#age(25)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2532*], [#delta(-16)],
      [81], [#name("BILENKO Tetyana")], [#age(33)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2531*], [#delta(-29)],
      [82], [#name("李芬")], [#age(40)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2531*], [#delta(-39)],
      [83], [#name("LIU Hsing-Yin")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2521*], [#delta(5)],
      [84], [#name("ODOROVA Eva")], [#age(37)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2517*], [#delta(-3)],
      [85], [#name("MATELOVA Hana")], [#age(26)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2515*], [#delta(24)],
      [86], [#name("邵杰妮")], [#age(22)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2512*], [#delta(-14)],
      [87], [#name("PASKAUSKIENE Ruta")], [#age(39)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2512*], [#delta(-5)],
      [88], [#name("NOSKOVA Yana")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2506*], [#delta(-19)],
      [89], [#name("维多利亚 帕芙洛维奇")], [#age(38)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2504*], [#delta(-19)],
      [90], [#name("李恩惠")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2503*], [#delta(-6)],
      [91], [#name("PROKHOROVA Yulia")], [#age(29)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2503*], [#delta(-15)],
      [92], [#name("KOMWONG Nanthana")], [#age(36)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2497*], [#delta(0)],
      [93], [#name("KIM Jiho")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2495*], [#delta(29)],
      [94], [#name("RI Mi Gyong")], [#age(26)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2492*], [#delta(-4)],
      [95], [#name("张安")], [#age(20)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2490*], [#delta(-4)],
      [96], [#name("伯纳黛特 斯佐科斯")], [#age(21)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2487*], [#delta(-11)],
      [97], [#name("WANG Chen")], [#age(42)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2483*], [#delta(-24)],
      [98], [#name("STRBIKOVA Renata")], [#age(37)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2477*], [#delta(-3)],
      [99], [#name("PERGEL Szandra")], [#age(28)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2475*], [#delta(24)],
      [100], [#name("苏萨西尼 萨维塔布特")], [#age(22)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2474*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("BAJOR Natalia")], [#age(19)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2469*], [#delta(47)],
      [102], [#name("TIKHOMIROVA Anna")], [#age(32)], [#assoc("RUS")], [?], [?], [?], [*2469*], [#delta(-9)],
      [103], [#name("BOLLMEIER Nadine")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2468*], [#delta(-4)],
      [104], [#name("KIM Hye Song")], [#age(23)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2467*], [#delta(-4)],
      [105], [#name("索菲亚 波尔卡诺娃")], [#age(22)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2465*], [#delta(-27)],
      [106], [#name("TASHIRO Saki")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2459*], [#delta(58)],
      [107], [#name("GRZYBOWSKA-FRANC Katarzyna")], [#age(27)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2457*], [#delta(-13)],
      [108], [#name("李时温")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2457*], [#delta(-47)],
      [109], [#name("JI Eunchae")], [#age(20)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2456*], [#delta(-6)],
      [110], [#name("SUZUKI Rika")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2447*], [#delta(-3)],
      [111], [#name("CHA Hyo Sim")], [#age(22)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2445*], [#delta(-3)],
      [112], [#name("布里特 伊尔兰德")], [#age(22)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2443*], [#delta(-6)],
      [113], [#name("森樱")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2441*], [#delta(8)],
      [114], [#name("SO Eka")], [#age(21)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2439*], [#delta(-1)],
      [115], [#name("KATO Kyoka")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-1)],
      [116], [#name("HUANG Yi-Hua")], [#age(32)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-20)],
      [117], [#name("GRUNDISCH Carole")], [#age(30)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2437*], [#delta(3)],
      [118], [#name("LEE I-Chen")], [#age(29)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2435*], [#delta(-13)],
      [119], [#name("JUNG Yumi")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2433*], [#delta(-1)],
      [120], [#name("阿德里安娜 迪亚兹")], [#age(16)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2431*], [#delta(26)],
      [121], [#name("EKHOLM Matilda")], [#age(34)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2431*], [#delta(-17)],
      [122], [#name("CECHOVA Dana")], [#age(33)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2429*], [#delta(43)],
      [123], [#name("CHENG Hsien-Tzu")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2428*], [#delta(-8)],
      [124], [#name("WU Yue")], [#age(26)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2427*], [#delta(36)],
      [125], [#name("玛利亚 肖")], [#age(22)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2426*], [#delta(-38)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("YOON Hyobin")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2424*], [#delta(75)],
      [127], [#name("SOO Wai Yam")], [#age(18)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2423*], [#delta(-3)],
      [128], [#name("LOVAS Petra")], [#age(36)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2422*], [#delta(4)],
      [129], [#name("GUI Lin")], [#age(23)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2421*], [#delta(25)],
      [130], [#name("IACOB Camelia")], [#age(24)], [#assoc("ROU")], [#right], [#shakehand], [#defense], [*2417*], [#delta(-5)],
      [131], [#name("KUSINSKA Klaudia")], [#age(23)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2415*], [#delta(8)],
      [132], [#name("YOO Eunchong")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2414*], [#delta(-4)],
      [133], [#name("KUMAHARA Luca")], [#age(21)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2412*], [#delta(-4)],
      [134], [#name("妮娜 米特兰姆")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2409*], [#delta(0)],
      [135], [#name("ZHENG Shichang")], [#age(24)], [#assoc("CHN")], [?], [?], [?], [*2407*], [#delta(0)],
      [136], [#name("RAMIREZ Sara")], [#age(29)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2406*], [#delta(-10)],
      [137], [#name("MENGE Merve")], [#age(27)], [#assoc("TUR")], [?], [?], [?], [*2405*], [#delta(-35)],
      [138], [#name("LEE Sujin")], [#age(24)], [#assoc("KOR")], [?], [?], [?], [*2401*], [#delta(-1)],
      [139], [#name("ERDELJI Anamaria")], [#age(31)], [#assoc("SRB")], [#right], [#shakehand], [#defense], [*2401*], [#delta(-22)],
      [140], [#name("AN Yeongeun")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2399*], [#delta(1)],
      [141], [#name("MORIZONO Mizuki")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2394*], [NEW],
      [142], [#name("RAKOVAC Lea")], [#age(20)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2390*], [#delta(2)],
      [143], [#name("LEE Yearam")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2389*], [#delta(2)],
      [144], [#name("HAPONOVA Hanna")], [#age(31)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2389*], [#delta(-17)],
      [145], [#name("DRAGOMAN Andreea")], [#age(16)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2384*], [#delta(14)],
      [146], [#name("ALTINKAYA Sibel")], [#age(23)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2383*], [#delta(27)],
      [147], [#name("NIWA Misato")], [#age(23)], [#assoc("JPN")], [?], [?], [?], [*2382*], [#delta(0)],
      [148], [#name("DIACONU Adina")], [#age(17)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2376*], [#delta(9)],
      [149], [#name("MATSUDAIRA Shiho")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2376*], [#delta(9)],
      [150], [#name("ZHENG Jiaqi")], [#age(28)], [#assoc("USA")], [?], [?], [?], [*2376*], [#delta(-10)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("CHOI Yelin")], [#age(18)], [#assoc("KOR")], [?], [?], [?], [*2376*], [#delta(-1)],
      [152], [#name("LIN Chia-Hui")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2375*], [#delta(-1)],
      [153], [#name("张墨")], [#age(27)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2375*], [#delta(-1)],
      [154], [#name("LI Ching Wan")], [#age(22)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2374*], [#delta(-1)],
      [155], [#name("安藤南")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2374*], [#delta(0)],
      [156], [#name("LAY Jian Fang")], [#age(43)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2373*], [#delta(0)],
      [157], [#name("MANTZ Chantal")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2372*], [#delta(-26)],
      [158], [#name("朱成竹")], [#age(19)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2370*], [#delta(16)],
      [159], [#name("CHOI Jeongmin")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2370*], [#delta(2)],
      [160], [#name("SUN Chen")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2369*], [#delta(3)],
      [161], [#name("蒂娜 梅谢芙")], [#age(22)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2369*], [#delta(-49)],
      [162], [#name("范思琦")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2365*], [#delta(4)],
      [163], [#name("CHO Hala")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2365*], [#delta(4)],
      [164], [#name("FEHER Gabriela")], [#age(28)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2364*], [#delta(-28)],
      [165], [#name("DAS Mouma")], [#age(32)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2363*], [#delta(3)],
      [166], [#name("SAVELYEVA Antonina")], [#age(30)], [#assoc("RUS")], [?], [?], [?], [*2360*], [#delta(4)],
      [167], [#name("SOLJA Amelie")], [#age(26)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2358*], [#delta(60)],
      [168], [#name("MU Jingyu")], [#age(17)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2357*], [#delta(3)],
      [169], [#name("HIRICI Cristina")], [#age(24)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2356*], [#delta(3)],
      [170], [#name("DVORAK Galia")], [#age(28)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2355*], [#delta(-54)],
      [171], [#name("VOROBEVA Olga")], [#age(26)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2352*], [#delta(9)],
      [172], [#name("CHIU Ssu-Hua")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#defense], [*2352*], [#delta(3)],
      [173], [#name("KHETKHUAN Tamolwan")], [#age(19)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2351*], [#delta(-54)],
      [174], [#name("SILVA Ligia")], [#age(35)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2349*], [#delta(3)],
      [175], [#name("PENKAVOVA Katerina")], [#age(29)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2346*], [#delta(3)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("WAN Yuan")], [#age(19)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2345*], [#delta(-33)],
      [177], [#name("PARK Seri")], [#age(19)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2344*], [#delta(57)],
      [178], [#name("LEE Dasom")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2338*], [#delta(3)],
      [179], [#name("LEE Yujin")], [#age(20)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2338*], [#delta(3)],
      [180], [#name("GASNIER Laura")], [#age(23)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2337*], [#delta(4)],
      [181], [#name("MADARASZ Dora")], [#age(23)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2335*], [#delta(-39)],
      [182], [#name("ABE Airi")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2335*], [#delta(3)],
      [183], [#name("JONG Un Ju")], [#age(21)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2334*], [#delta(4)],
      [184], [#name("LI Chunli")], [#age(54)], [#assoc("NZL")], [#right], [#penhold], [#attack], [*2333*], [#delta(5)],
      [185], [#name("GALIC Alex")], [#age(22)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2331*], [#delta(9)],
      [186], [#name("CHASSELIN Pauline")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2331*], [#delta(13)],
      [187], [#name("TIAN Yuan")], [#age(41)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2330*], [#delta(5)],
      [188], [#name("KIM Byeolnim")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2326*], [#delta(-78)],
      [189], [#name("琳达 伯格斯特罗姆")], [#age(21)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2324*], [#delta(-40)],
      [190], [#name("KANG Dayeon")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2321*], [#delta(6)],
      [191], [#name("LEE Nakyung")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2318*], [#delta(7)],
      [192], [#name("PRIVALOVA Alexandra")], [#age(29)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2317*], [#delta(-23)],
      [193], [#name("NAKAHATA Natsumi")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2315*], [NEW],
      [194], [#name("HUANG Hsin")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2314*], [#delta(6)],
      [195], [#name("NAGYVARADI Mercedes")], [#age(22)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2313*], [#delta(66)],
      [196], [#name("HUANG Yu-Chiao")], [#age(20)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2312*], [#delta(6)],
      [197], [#name("NG Sock Khim")], [#age(32)], [#assoc("MAS")], [?], [?], [?], [*2311*], [#delta(7)],
      [198], [#name("SHIOMI Maki")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2309*], [#delta(111)],
      [199], [#name("BIKBAEVA Anna")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2308*], [#delta(10)],
      [200], [#name("HAN Xing")], [#age(27)], [#assoc("CGO")], [?], [?], [?], [*2308*], [#delta(6)],
    )
  )
