#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("樊振东")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3136*], [#delta(0)],
      [2], [#name("王楚钦")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*3108*], [#delta(0)],
      [3], [#name("马龙")], [#age(37)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3025*], [#delta(0)],
      [4], [#name("林诗栋")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2990*], [#delta(0)],
      [5], [#name("雨果 卡尔德拉诺")], [#age(29)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2956*], [#delta(0)],
      [6], [#name("梁靖崑")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2926*], [#delta(2)],
      [7], [#name("艾利克斯 勒布伦")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2910*], [#delta(0)],
      [8], [#name("菲利克斯 勒布伦")], [#age(19)], [#assoc("FRA")], [#right], [#penhold], [#attack], [*2894*], [#delta(-2)],
      [9], [#name("林昀儒")], [#age(24)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2877*], [#delta(3)],
      [10], [#name("特鲁斯 莫雷加德")], [#age(23)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2876*], [#delta(0)],
      [11], [#name("李尚洙")], [#age(35)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2846*], [#delta(-2)],
      [12], [#name("户上隼辅")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2842*], [#delta(29)],
      [13], [#name("向鹏")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2802*], [#delta(0)],
      [14], [#name("帕特里克 弗朗西斯卡")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2802*], [#delta(1)],
      [15], [#name("松岛辉空")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2800*], [#delta(-1)],
      [16], [#name("安宰贤")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2794*], [#delta(10)],
      [17], [#name("西蒙 高兹")], [#age(31)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2793*], [#delta(14)],
      [18], [#name("安东 卡尔伯格")], [#age(28)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2784*], [#delta(-1)],
      [19], [#name("张本智和")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2783*], [#delta(-8)],
      [20], [#name("迪米特里 奥恰洛夫")], [#age(37)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2768*], [#delta(-2)],
      [21], [#name("蒂姆 波尔")], [#age(44)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2763*], [#delta(-1)],
      [22], [#name("周启豪")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2762*], [#delta(-1)],
      [23], [#name("达科 约奇克")], [#age(27)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2758*], [#delta(-7)],
      [24], [#name("汤姆 贾维斯")], [#age(26)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2753*], [#delta(112)],
      [25], [#name("黄友政")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2743*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("弗拉维安 科顿")], [#age(17)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2743*], [#delta(-1)],
      [27], [#name("克里斯坦 卡尔松")], [#age(34)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2741*], [#delta(6)],
      [28], [#name("张禹珍")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2737*], [#delta(6)],
      [29], [#name("温瑞博")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2726*], [#delta(-2)],
      [30], [#name("刘丁硕")], [#age(27)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2716*], [#delta(0)],
      [31], [#name("吉村真晴")], [#age(32)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2716*], [#delta(28)],
      [32], [#name("夸德里 阿鲁纳")], [#age(37)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2711*], [#delta(79)],
      [33], [#name("林高远")], [#age(30)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2709*], [#delta(-14)],
      [34], [#name("篠塚大登")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2705*], [#delta(-12)],
      [35], [#name("徐瑛彬")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2704*], [#delta(0)],
      [36], [#name("贝内迪克特 杜达")], [#age(31)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2699*], [#delta(0)],
      [37], [#name("安德斯 林德")], [#age(27)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2698*], [#delta(12)],
      [38], [#name("赵胜敏")], [#age(27)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2696*], [#delta(0)],
      [39], [#name("托米斯拉夫 普卡")], [#age(29)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2690*], [#delta(-7)],
      [40], [#name("徐海东")], [#age(25)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2689*], [#delta(0)],
      [41], [#name("邱党")], [#age(29)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2689*], [#delta(-17)],
      [42], [#name("黄镇廷")], [#age(34)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2688*], [#delta(53)],
      [43], [#name("陈垣宇")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2684*], [#delta(-1)],
      [44], [#name("赵大成")], [#age(23)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2682*], [#delta(47)],
      [45], [#name("滨田一辉")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2675*], [#delta(-1)],
      [46], [#name("丹尼尔 哈贝松")], [#age(39)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2674*], [#delta(33)],
      [47], [#name("村松雄斗")], [#age(29)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2673*], [#delta(-2)],
      [48], [#name("基里尔 格拉西缅科")], [#age(29)], [#assoc("KAZ")], [#right], [#shakehand], [#attack], [*2673*], [#delta(64)],
      [49], [#name("高承睿")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2673*], [#delta(33)],
      [50], [#name("利亚姆 皮切福德")], [#age(32)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2665*], [#delta(-7)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("冯翊新")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2662*], [#delta(-4)],
      [52], [#name("SHAH Manush")], [#age(24)], [#assoc("IND")], [#left], [#shakehand], [#attack], [*2662*], [#delta(15)],
      [53], [#name("田中佑汰")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2659*], [#delta(-5)],
      [54], [#name("孙闻")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2655*], [#delta(-4)],
      [55], [#name("BADOWSKI Marek")], [#age(28)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2655*], [#delta(-4)],
      [56], [#name("周恺")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2653*], [#delta(-4)],
      [57], [#name("斯蒂芬 门格尔")], [#age(37)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2652*], [#delta(-4)],
      [58], [#name("马金宝")], [#age(25)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2652*], [#delta(-4)],
      [59], [#name("宇田幸矢")], [#age(24)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2652*], [#delta(-3)],
      [60], [#name("牛冠凯")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2651*], [#delta(-3)],
      [61], [#name("卡纳克 贾哈")], [#age(25)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2651*], [#delta(-24)],
      [62], [#name("朴圭贤")], [#age(20)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2647*], [#delta(-4)],
      [63], [#name("乔纳森 格罗斯")], [#age(33)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2645*], [#delta(-2)],
      [64], [#name("WOO Hyeonggyu")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2643*], [#delta(-2)],
      [65], [#name("里卡多 瓦尔特")], [#age(34)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2642*], [#delta(-10)],
      [66], [#name("马克斯 弗雷塔斯")], [#age(37)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2636*], [#delta(44)],
      [67], [#name("吴晙诚")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2636*], [#delta(-7)],
      [68], [#name("袁励岑")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2635*], [#delta(-3)],
      [69], [#name("马蒂亚斯 法尔克")], [#age(34)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2630*], [#delta(-41)],
      [70], [#name("亚历山大 卡辛")], [#age(27)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2630*], [#delta(-4)],
      [71], [#name("CHIRITA Iulian")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2628*], [#delta(-7)],
      [72], [#name("梁俨苧")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2626*], [#delta(-4)],
      [73], [#name("庄智渊")], [#age(44)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2624*], [#delta(-3)],
      [74], [#name("米洛什 雷德齐姆斯基")], [#age(19)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2623*], [#delta(-45)],
      [75], [#name("朴康贤")], [#age(29)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2623*], [#delta(-4)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("凯 斯图姆珀")], [#age(23)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2621*], [#delta(-4)],
      [77], [#name("埃斯特班 多尔")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2620*], [#delta(-3)],
      [78], [#name("曹巍")], [#age(26)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2617*], [#delta(-1)],
      [79], [#name("于子洋")], [#age(27)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2617*], [#delta(-1)],
      [80], [#name("ABBASI Amirreza")], [#age(25)], [#assoc("MLT")], [#right], [#shakehand], [#defense], [*2613*], [#delta(0)],
      [81], [#name("奥马尔 阿萨尔")], [#age(34)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2612*], [#delta(39)],
      [82], [#name("BRODD Viktor")], [#age(35)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2612*], [#delta(-1)],
      [83], [#name("PERSSON Jon")], [#age(39)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2607*], [#delta(0)],
      [84], [#name("KIM Minhyeok")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2606*], [#delta(1)],
      [85], [#name("爱德华 约内斯库")], [#age(21)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2603*], [#delta(3)],
      [86], [#name("郭冠宏")], [#age(17)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2602*], [#delta(-23)],
      [87], [#name("廖振珽")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2601*], [#delta(-12)],
      [88], [#name("RANEFUR Elias")], [#age(29)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2600*], [#delta(1)],
      [89], [#name("薛飞")], [#age(26)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2597*], [#delta(-50)],
      [90], [#name("雅克布 迪亚斯")], [#age(30)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2597*], [#delta(2)],
      [91], [#name("木造勇人")], [#age(26)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2596*], [#delta(2)],
      [92], [#name("ORT Kilian")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2594*], [#delta(2)],
      [93], [#name("安德烈 贝特尔斯迈尔")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2594*], [#delta(3)],
      [94], [#name("PORET Thibault")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2593*], [#delta(-25)],
      [95], [#name("林钟勋")], [#age(28)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2589*], [#delta(-49)],
      [96], [#name("陈建安")], [#age(34)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2583*], [#delta(2)],
      [97], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(45)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2583*], [#delta(10)],
      [98], [#name("李和宸")], [#age(16)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2582*], [#delta(1)],
      [99], [#name("神巧也")], [#age(32)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2580*], [#delta(1)],
      [100], [#name("吉山僚一")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2578*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("阿尔瓦罗 罗布勒斯")], [#age(34)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2577*], [#delta(46)],
      [102], [#name("尼马 阿拉米安")], [#age(33)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2577*], [#delta(1)],
      [103], [#name("AKKUZU Can")], [#age(28)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2577*], [#delta(1)],
      [104], [#name("严升")], [#age(28)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2576*], [#delta(1)],
      [105], [#name("AN Ji Song")], [#age(29)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2574*], [#delta(1)],
      [106], [#name("CARVALHO Diogo")], [#age(33)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2572*], [#delta(3)],
      [107], [#name("GERALDO Joao")], [#age(30)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2570*], [#delta(90)],
      [108], [#name("MARTINKO Jiri")], [#age(26)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2565*], [#delta(5)],
      [109], [#name("RASSENFOSSE Adrien")], [#age(22)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2563*], [#delta(35)],
      [110], [#name("LAKATOS Tamas")], [#age(30)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2563*], [#delta(5)],
      [111], [#name("ANDRAS Csaba")], [#age(23)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2561*], [#delta(6)],
      [112], [#name("陈俊菘")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2561*], [#delta(6)],
      [113], [#name("PARK Chan-Hyeok")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2560*], [#delta(6)],
      [114], [#name("YIU Kwan To")], [#age(21)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2554*], [#delta(7)],
      [115], [#name("赵子豪")], [#age(28)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2553*], [#delta(7)],
      [116], [#name("SAKAI Yuhi")], [#age(19)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2553*], [#delta(7)],
      [117], [#name("PICARD Vincent")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2553*], [#delta(7)],
      [118], [#name("KULCZYCKI Samuel")], [#age(23)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2553*], [#delta(-28)],
      [119], [#name("曾蓓勋")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2553*], [#delta(6)],
      [120], [#name("莱奥纳多 饭冢")], [#age(19)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2552*], [#delta(10)],
      [121], [#name("MATSUDAIRA Kenji")], [#age(36)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2551*], [#delta(-37)],
      [122], [#name("贝内德克 奥拉")], [#age(34)], [#assoc("FIN")], [#right], [#shakehand], [#attack], [*2550*], [#delta(-49)],
      [123], [#name("吉村和弘")], [#age(29)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2546*], [#delta(3)],
      [124], [#name("HACHARD Antoine")], [#age(31)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2545*], [#delta(3)],
      [125], [#name("诺沙迪 阿拉米扬")], [#age(34)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2545*], [#delta(-17)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("BARDET Lilian")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2545*], [#delta(-24)],
      [127], [#name("及川瑞基")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2544*], [#delta(1)],
      [128], [#name("HAGIHARA Keishi")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2543*], [#delta(1)],
      [129], [#name("卢文 菲鲁斯")], [#age(37)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2541*], [#delta(3)],
      [130], [#name("LAM Siu Hang")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2540*], [#delta(89)],
      [131], [#name("MOVILEANU Darius")], [#age(20)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2539*], [#delta(22)],
      [132], [#name("GREBNEV Maksim")], [#age(23)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2537*], [#delta(1)],
      [133], [#name("郭勇")], [#age(19)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2537*], [#delta(-19)],
      [134], [#name("王晨策")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2537*], [#delta(0)],
      [135], [#name("KIM Taehyun")], [#age(22)], [#assoc("MLT")], [#left], [#shakehand], [#attack], [*2536*], [#delta(0)],
      [136], [#name("上田仁")], [#age(34)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2535*], [#delta(1)],
      [137], [#name("VERDONSCHOT Wim")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2532*], [#delta(4)],
      [138], [#name("艾曼纽 莱贝松")], [#age(37)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2532*], [#delta(0)],
      [139], [#name("SIPOS Rares")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2530*], [#delta(0)],
      [140], [#name("孙正")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2529*], [#delta(0)],
      [141], [#name("PRYSHCHEPA Ievgen")], [#age(40)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2528*], [#delta(1)],
      [142], [#name("LANDRIEU Andrea")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2525*], [#delta(3)],
      [143], [#name("蒂亚戈 阿波罗尼亚")], [#age(39)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2524*], [#delta(-57)],
      [144], [#name("罗伯特 加尔多斯")], [#age(46)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2524*], [#delta(-1)],
      [145], [#name("MATSUYAMA Yuki")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2524*], [#delta(1)],
      [146], [#name("THAKKAR Manav")], [#age(25)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2524*], [#delta(-30)],
      [147], [#name("POLANSKY Tomas")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2523*], [#delta(1)],
      [148], [#name("NOROOZI Afshin")], [#age(40)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2523*], [#delta(1)],
      [149], [#name("刘夜泊")], [#age(24)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2522*], [#delta(1)],
      [150], [#name("ANGELAKIS Konstantinos")], [#age(28)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2522*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("MENG Fanbo")], [#age(25)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2520*], [#delta(1)],
      [152], [#name("哈米特 德赛")], [#age(32)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2517*], [#delta(4)],
      [153], [#name("BOURRASSAUD Florian")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2516*], [#delta(4)],
      [154], [#name("KUMAR Nikhil")], [#age(22)], [#assoc("USA")], [#left], [#shakehand], [#attack], [*2516*], [#delta(4)],
      [155], [#name("HO Kwan Kit")], [#age(28)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2516*], [#delta(4)],
      [156], [#name("弗拉迪斯拉夫 乌尔苏")], [#age(24)], [#assoc("MDA")], [#left], [#shakehand], [#attack], [*2515*], [#delta(4)],
      [157], [#name("雅罗斯列夫 扎姆登科")], [#age(37)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2514*], [#delta(4)],
      [158], [#name("安德烈 加奇尼")], [#age(39)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2513*], [#delta(-82)],
      [159], [#name("MEISSNER Cedric")], [#age(25)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2512*], [#delta(3)],
      [160], [#name("YOKOTANI Jo")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2511*], [#delta(4)],
      [161], [#name("CHAN Baldwin")], [#age(21)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2511*], [#delta(-74)],
      [162], [#name("SONE Kakeru")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2509*], [#delta(3)],
      [163], [#name("QUAN Kaiyuan")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2509*], [#delta(3)],
      [164], [#name("RUIZ Romain")], [#age(28)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2508*], [#delta(3)],
      [165], [#name("TSUBOI Yuma")], [#age(28)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2507*], [#delta(4)],
      [166], [#name("吉山和希")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2507*], [#delta(48)],
      [167], [#name("LEVENKO Andreas")], [#age(27)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2506*], [#delta(-13)],
      [168], [#name("MAJOROS Bence")], [#age(28)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2506*], [#delta(2)],
      [169], [#name("特里斯坦 弗洛雷")], [#age(30)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2505*], [#delta(2)],
      [170], [#name("SURAVAJJULA Snehit")], [#age(25)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2503*], [#delta(4)],
      [171], [#name("OUAICHE Stephane")], [#age(32)], [#assoc("ALG")], [#left], [#shakehand], [#attack], [*2501*], [#delta(4)],
      [172], [#name("ROLLAND Jules")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2501*], [#delta(4)],
      [173], [#name("BERTRAND Irvin")], [#age(25)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2500*], [#delta(4)],
      [174], [#name("LI Hsin-Yang")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2499*], [#delta(4)],
      [175], [#name("黄彦诚")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2498*], [#delta(5)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("张宇安")], [#age(19)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2497*], [#delta(5)],
      [177], [#name("LIANG Guodong")], [#age(22)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*2495*], [#delta(5)],
      [178], [#name("SGOUROPOULOS Ioannis")], [#age(25)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2493*], [#delta(5)],
      [179], [#name("AIDA Satoshi")], [#age(32)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2492*], [#delta(6)],
      [180], [#name("KUBIK Maciej")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2491*], [#delta(6)],
      [181], [#name("MONTEIRO Joao")], [#age(42)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2491*], [#delta(-2)],
      [182], [#name("BOBOCICA Mihai")], [#age(39)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2491*], [#delta(5)],
      [183], [#name("PENG Wang-Wei")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2491*], [#delta(5)],
      [184], [#name("REMBERT Bastien")], [#age(25)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2490*], [#delta(5)],
      [185], [#name("HAUG Borgar")], [#age(23)], [#assoc("NOR")], [#left], [#shakehand], [#attack], [*2490*], [#delta(31)],
      [186], [#name("本雅明 法拉吉")], [#age(16)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2489*], [#delta(20)],
      [187], [#name("REITSPIES David")], [#age(29)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2487*], [#delta(4)],
      [188], [#name("SEYFRIED Joe")], [#age(27)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2486*], [#delta(4)],
      [189], [#name("SODERLUND Hampus")], [#age(31)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2485*], [#delta(5)],
      [190], [#name("WALKER Samuel")], [#age(30)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2485*], [#delta(5)],
      [191], [#name("SAI Linwei")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2484*], [#delta(5)],
      [192], [#name("NG Pak Nam")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2484*], [#delta(6)],
      [193], [#name("HODAEI Amir Hossein")], [#age(27)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2483*], [#delta(6)],
      [194], [#name("SANCHI Francisco")], [#age(26)], [#assoc("ARG")], [#right], [#shakehand], [#attack], [*2482*], [#delta(62)],
      [195], [#name("KURMANGALIYEV Alan")], [#age(18)], [#assoc("KAZ")], [#right], [#shakehand], [#attack], [*2481*], [#delta(-5)],
      [196], [#name("JANG Seongil")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2474*], [#delta(9)],
      [197], [#name("HAM Yu Song")], [#age(26)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2473*], [#delta(4)],
      [198], [#name("PLETEA Cristian")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2471*], [#delta(10)],
      [199], [#name("DE NODREST Leo")], [#age(25)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2468*], [#delta(10)],
      [200], [#name("PANTOJA Miguel")], [#age(21)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2467*], [#delta(83)],
    )
  )
