#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("孙颖莎")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3107*], [#delta(0)],
      [2], [#name("王曼昱")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2974*], [#delta(0)],
      [3], [#name("陈幸同")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2969*], [#delta(0)],
      [4], [#name("蒯曼")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2955*], [#delta(0)],
      [5], [#name("张本美和")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2924*], [#delta(2)],
      [6], [#name("王艺迪")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2923*], [#delta(0)],
      [7], [#name("金琴英")], [#age(24)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2915*], [#delta(-2)],
      [8], [#name("桥本帆乃香")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2898*], [#delta(4)],
      [9], [#name("何卓佳")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2876*], [#delta(-1)],
      [10], [#name("朱雨玲")], [#age(30)], [#assoc("MAC")], [#right], [#shakehand], [#attack], [*2855*], [#delta(1)],
      [11], [#name("石洵瑶")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2841*], [#delta(-2)],
      [12], [#name("伊藤美诚")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2825*], [#delta(3)],
      [13], [#name("陈熠")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2813*], [#delta(-3)],
      [14], [#name("大藤沙月")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2812*], [#delta(15)],
      [15], [#name("郑怡静")], [#age(33)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2799*], [#delta(6)],
      [16], [#name("刘炜珊")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2787*], [#delta(-3)],
      [17], [#name("早田希娜")], [#age(25)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2780*], [#delta(-1)],
      [18], [#name("申裕斌")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2771*], [#delta(2)],
      [19], [#name("钱天一")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2769*], [#delta(-5)],
      [20], [#name("杨屹韵")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2763*], [#delta(-3)],
      [21], [#name("佐藤瞳")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2754*], [#delta(2)],
      [22], [#name("索菲亚 波尔卡诺娃")], [#age(31)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2745*], [#delta(5)],
      [23], [#name("芝田沙季")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2743*], [#delta(-4)],
      [24], [#name("纵歌曼")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2737*], [#delta(8)],
      [25], [#name("王晓彤")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2725*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("朱芊曦")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2723*], [#delta(2)],
      [27], [#name("木原美悠")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2716*], [#delta(-3)],
      [28], [#name("覃予萱")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2715*], [#delta(8)],
      [29], [#name("出泽杏佳")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2696*], [#delta(-7)],
      [30], [#name("韩莹")], [#age(42)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2689*], [#delta(-12)],
      [31], [#name("边松景")], [#age(24)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2688*], [#delta(2)],
      [32], [#name("横井咲樱")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2683*], [#delta(-1)],
      [33], [#name("长崎美柚")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2677*], [#delta(1)],
      [34], [#name("袁嘉楠")], [#age(40)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2677*], [#delta(27)],
      [35], [#name("萨宾 温特")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2675*], [#delta(0)],
      [36], [#name("布鲁娜 高桥")], [#age(25)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2670*], [#delta(26)],
      [37], [#name("朱思冰")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2668*], [#delta(0)],
      [38], [#name("李洁")], [#age(41)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2662*], [NEW],
      [39], [#name("范姝涵")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2661*], [#delta(0)],
      [40], [#name("韩菲儿")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2658*], [#delta(-2)],
      [41], [#name("小盐悠菜")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2645*], [#delta(2)],
      [42], [#name("安娜 赫西")], [#age(19)], [#assoc("WAL")], [#right], [#shakehand], [#attack], [*2635*], [#delta(31)],
      [43], [#name("徐孝元")], [#age(38)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2629*], [#delta(-3)],
      [44], [#name("平野美宇")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2623*], [#delta(3)],
      [45], [#name("万远")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2621*], [#delta(1)],
      [46], [#name("简彤娟")], [#age(23)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2619*], [#delta(13)],
      [47], [#name("徐奕")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2618*], [#delta(4)],
      [48], [#name("崔孝珠")], [#age(27)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2615*], [#delta(17)],
      [49], [#name("阿德里安娜 迪亚兹")], [#age(25)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2612*], [#delta(-1)],
      [50], [#name("安妮特 考夫曼")], [#age(19)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2611*], [#delta(-8)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("伯纳黛特 斯佐科斯")], [#age(30)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2610*], [#delta(-25)],
      [52], [#name("伊丽莎白 萨马拉")], [#age(36)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2601*], [#delta(-7)],
      [53], [#name("嵯水影")], [#age(25)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2601*], [#delta(1)],
      [54], [#name("杜凯琹")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2600*], [#delta(-5)],
      [55], [#name("李昱谆")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2599*], [#delta(1)],
      [56], [#name("张安")], [#age(29)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2594*], [#delta(-6)],
      [57], [#name("琳达 伯格斯特隆")], [#age(30)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2592*], [#delta(-5)],
      [58], [#name("赤江夏星")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2591*], [#delta(16)],
      [59], [#name("布里特 伊尔兰德")], [#age(31)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2588*], [#delta(1)],
      [60], [#name("莱娅 拉科瓦奇")], [#age(29)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2585*], [#delta(35)],
      [61], [#name("奥拉万 帕拉南")], [#age(28)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2575*], [#delta(7)],
      [62], [#name("伊丽莎白 阿布拉米安")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2574*], [NEW],
      [63], [#name("素塔西尼 萨维塔布特")], [#age(31)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2570*], [#delta(24)],
      [64], [#name("哈娜 阿拉波维奇")], [#age(21)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2563*], [#delta(55)],
      [65], [#name("林依诺")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2560*], [#delta(4)],
      [66], [#name("斯维斯蒂卡 戈什")], [#age(22)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2560*], [#delta(1)],
      [67], [#name("刘杨子")], [#age(23)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2557*], [#delta(5)],
      [68], [#name("叶伊恬")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2554*], [#delta(-27)],
      [69], [#name("姚睿轩")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2553*], [#delta(15)],
      [70], [#name("李多恩")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2551*], [#delta(-15)],
      [71], [#name("汉娜 高达")], [#age(18)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2550*], [#delta(-18)],
      [72], [#name("李恩惠")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2550*], [#delta(-28)],
      [73], [#name("梁夏银")], [#age(31)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2549*], [#delta(-15)],
      [74], [#name("傅玉")], [#age(47)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2548*], [#delta(-10)],
      [75], [#name("倪夏莲")], [#age(62)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2543*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("笹尾明日香")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2539*], [#delta(-10)],
      [77], [#name("陈思羽")], [#age(32)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2536*], [#delta(0)],
      [78], [#name("曾尖")], [#age(29)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2536*], [#delta(-8)],
      [79], [#name("金娜英")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2533*], [#delta(-49)],
      [80], [#name("金河英")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2533*], [#delta(-2)],
      [81], [#name("邵杰妮")], [#age(31)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2523*], [#delta(-2)],
      [82], [#name("莎莉 莫伊兰")], [#age(18)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2520*], [#delta(-1)],
      [83], [#name("蒂娜 梅谢芙")], [#age(31)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2517*], [#delta(2)],
      [84], [#name("CHENG Pusyuan")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2516*], [#delta(2)],
      [85], [#name("单晓娜")], [#age(42)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2513*], [#delta(-2)],
      [86], [#name("乔治娜 波塔")], [#age(40)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2512*], [#delta(2)],
      [87], [#name("玛格丽塔 佩索茨卡")], [#age(34)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2510*], [#delta(27)],
      [88], [#name("萨比娜 苏尔扬")], [#age(25)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2504*], [#delta(42)],
      [89], [#name("黄禹乔")], [#age(29)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2503*], [#delta(-13)],
      [90], [#name("迪亚 奇塔莱")], [#age(22)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2498*], [#delta(10)],
      [91], [#name("祝启慧")], [#age(13)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2497*], [#delta(33)],
      [92], [#name("肖瑶茜")], [#age(31)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2496*], [#delta(-35)],
      [93], [#name("阿迪娜 迪亚科努")], [#age(26)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2496*], [#delta(-30)],
      [94], [#name("菲利帕 贝里安德")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2495*], [#delta(24)],
      [95], [#name("克里斯蒂娜 卡尔伯格")], [#age(25)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2495*], [#delta(39)],
      [96], [#name("张翔宇")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2492*], [#delta(0)],
      [97], [#name("苏籽童")], [#age(16)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2491*], [#delta(1)],
      [98], [#name("埃杰 哈拉奇")], [#age(23)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2491*], [#delta(128)],
      [99], [#name("妮娜 米特兰姆")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2490*], [#delta(-28)],
      [100], [#name("面手凛")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2487*], [#delta(10)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("朴佳贤")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2487*], [#delta(-8)],
      [102], [#name("普利蒂卡 帕瓦德")], [#age(21)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2484*], [#delta(-22)],
      [103], [#name("青木咲智")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2483*], [#delta(-1)],
      [104], [#name("金成珍")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2478*], [#delta(45)],
      [105], [#name("刘馨尹")], [#age(38)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2477*], [#delta(-2)],
      [106], [#name("柳韩娜")], [#age(23)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2475*], [#delta(-16)],
      [107], [#name("朱梓予")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2475*], [#delta(74)],
      [108], [#name("艾希卡 穆克吉")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2475*], [#delta(-2)],
      [109], [#name("莱娜 霍查特")], [#age(17)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2473*], [#delta(8)],
      [110], [#name("崔海恩")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2469*], [#delta(-2)],
      [111], [#name("胡一")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2468*], [#delta(4)],
      [112], [#name("高森爱央")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2468*], [#delta(-5)],
      [113], [#name("苏珊娜 维尔戈斯")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2468*], [#delta(119)],
      [114], [#name("焦尔吉娅 皮科林")], [#age(29)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2467*], [#delta(-13)],
      [115], [#name("张墨")], [#age(36)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2467*], [#delta(-23)],
      [116], [#name("伊万娜 马洛巴比奇")], [#age(45)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2466*], [#delta(48)],
      [117], [#name("汉娜 马特洛娃")], [#age(35)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2466*], [#delta(-6)],
      [118], [#name("安德烈娅 德拉戈曼")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2460*], [#delta(-6)],
      [119], [#name("KLEE Sophia")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2460*], [#delta(115)],
      [120], [#name("苏蒂尔塔 穆克吉")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2458*], [#delta(26)],
      [121], [#name("黄愉偼")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2457*], [#delta(-32)],
      [122], [#name("UESAWA Anne")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2454*], [#delta(55)],
      [123], [#name("娜塔莉亚 巴约尔")], [#age(28)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2453*], [#delta(43)],
      [124], [#name("陈忞昕")], [#age(16)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2452*], [#delta(-11)],
      [125], [#name("朱成竹")], [#age(28)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2448*], [#delta(-34)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("盖娅 蒙法尔迪尼")], [#age(24)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2447*], [#delta(-44)],
      [127], [#name("索洛米娅 布拉捷伊科")], [#age(26)], [#assoc("UKR")], [#left], [#shakehand], [#attack], [*2446*], [#delta(-18)],
      [128], [#name("玛妮卡 巴特拉")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2445*], [#delta(-29)],
      [129], [#name("郑先知")], [#age(32)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2442*], [#delta(-13)],
      [130], [#name("许玴玪")], [#age(15)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2439*], [#delta(22)],
      [131], [#name("竹谷美凉")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2439*], [#delta(-27)],
      [132], [#name("金谞润")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2437*], [#delta(6)],
      [133], [#name("丁怡婕")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2437*], [#delta(-12)],
      [134], [#name("杨晓欣")], [#age(37)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2435*], [#delta(-11)],
      [135], [#name("李时温")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2434*], [#delta(24)],
      [136], [#name("MAKSUTI Aneta")], [#age(30)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-11)],
      [137], [#name("伊莎贝拉 卢普列斯库")], [#age(26)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2430*], [#delta(20)],
      [138], [#name("金妮帕 萨维塔布特")], [#age(25)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2427*], [#delta(-10)],
      [139], [#name("何天天")], [#age(27)], [#assoc("ENG")], [#right], [#penhold], [#attack], [*2424*], [#delta(-42)],
      [140], [#name("迪维扬希 布霍米克")], [#age(15)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2422*], [#delta(-8)],
      [141], [#name("比安卡 梅罗苏")], [#age(18)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2421*], [#delta(-5)],
      [142], [#name("黄怡桦")], [#age(41)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2418*], [#delta(-13)],
      [143], [#name("麻生丽名")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2416*], [NEW],
      [144], [#name("ROY Krittwika")], [#age(31)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2412*], [#delta(-11)],
      [145], [#name("刘媛")], [#age(40)], [#assoc("AUT")], [#right], [#penhold], [#attack], [*2407*], [#delta(0)],
      [146], [#name("CHOI Nahyun")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2405*], [#delta(30)],
      [147], [#name("波琳 沙斯兰")], [#age(28)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2402*], [#delta(0)],
      [148], [#name("舒麟茜")], [#age(19)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2400*], [#delta(2)],
      [149], [#name("巴尔博拉 巴拉佐娃")], [#age(33)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2398*], [#delta(2)],
      [150], [#name("LYNE Karen")], [#age(23)], [#assoc("MAS")], [#left], [#shakehand], [#attack], [*2393*], [#delta(-30)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("刘叡潾")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2392*], [#delta(4)],
      [152], [#name("闫禹橦")], [#age(17)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2391*], [#delta(11)],
      [153], [#name("塔尼娅 普莱安")], [#age(24)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2389*], [#delta(3)],
      [154], [#name("MATIUNINA Veronika")], [#age(19)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2388*], [#delta(-10)],
      [155], [#name("木村香纯")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2388*], [#delta(3)],
      [156], [#name("SAINI Suhana")], [#age(19)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2387*], [#delta(-17)],
      [157], [#name("面田采巳")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2387*], [#delta(223)],
      [158], [#name("埃列娜 扎哈里亚")], [#age(21)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2385*], [#delta(-23)],
      [159], [#name("TEE Ai Xin")], [#age(24)], [#assoc("MAS")], [#right], [#penhold], [#attack], [*2384*], [#delta(15)],
      [160], [#name("安娜 布日斯卡")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2383*], [#delta(46)],
      [161], [#name("雷切尔 莫雷特")], [#age(36)], [#assoc("SUI")], [#left], [#shakehand], [#attack], [*2383*], [#delta(-34)],
      [162], [#name("张璇")], [#age(26)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2382*], [#delta(61)],
      [163], [#name("弗兰琪斯卡 施莱纳")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2382*], [#delta(36)],
      [164], [#name("柳是宇")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2381*], [#delta(-38)],
      [165], [#name("KODET Hanka")], [#age(15)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2381*], [#delta(97)],
      [166], [#name("GRIESEL Mia")], [#age(19)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2380*], [#delta(-13)],
      [167], [#name("WU Ying Syuan")], [#age(16)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2380*], [#delta(8)],
      [168], [#name("赵王琪")], [#age(15)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2380*], [#delta(5)],
      [169], [#name("杨惠泽")], [#age(15)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2380*], [#delta(18)],
      [170], [#name("辛德雷拉 达斯")], [#age(16)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2378*], [#delta(-16)],
      [171], [#name("PAK Su Gyong")], [#age(23)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2378*], [#delta(-10)],
      [172], [#name("斯丽贾 阿库拉")], [#age(27)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2375*], [#delta(-29)],
      [173], [#name("王艾米")], [#age(23)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2373*], [#delta(-36)],
      [174], [#name("ORTEGA Daniela")], [#age(27)], [#assoc("CHI")], [#right], [#shakehand], [#attack], [*2371*], [#delta(-7)],
      [175], [#name("RAD Elvira")], [#age(21)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2369*], [#delta(116)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("RILISKYTE Kornelija")], [#age(22)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2368*], [#delta(-7)],
      [177], [#name("艾卡特里尼 托利乌")], [#age(30)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2366*], [#delta(-7)],
      [178], [#name("李承垠")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2365*], [#delta(-7)],
      [179], [#name("马泰娅 耶格尔")], [#age(30)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2362*], [#delta(-37)],
      [180], [#name("卡塔日娜 文格任")], [#age(24)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2361*], [#delta(-32)],
      [181], [#name("卡琳 格罗福娃")], [#age(31)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2361*], [#delta(-9)],
      [182], [#name("蔡昀恩")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2361*], [#delta(-20)],
      [183], [#name("李多恩")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2356*], [#delta(-15)],
      [184], [#name("奥黛丽 扎里夫")], [#age(27)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2356*], [#delta(-62)],
      [185], [#name("夏洛特 卢茨")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2351*], [#delta(-44)],
      [186], [#name("郭铮")], [#age(15)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2348*], [#delta(-7)],
      [187], [#name("CRUZ Kheith")], [#age(19)], [#assoc("PHI")], [#right], [#shakehand], [#attack], [*2347*], [#delta(-7)],
      [188], [#name("MATOS Ines")], [#age(21)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2345*], [#delta(-6)],
      [189], [#name("绍蕾什 阿卡舍娃")], [#age(25)], [#assoc("KAZ")], [#right], [#shakehand], [#attack], [*2345*], [#delta(2)],
      [190], [#name("塔蒂亚娜 库库尔科娃")], [#age(25)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2344*], [#delta(-50)],
      [191], [#name("安德里亚 托多罗维奇")], [#age(33)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2341*], [#delta(-8)],
      [192], [#name("MEN Shuohan")], [#age(25)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2340*], [#delta(88)],
      [193], [#name("巫嘉恩")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2339*], [#delta(-9)],
      [194], [#name("池旼亨")], [#age(38)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2338*], [#delta(-16)],
      [195], [#name("ITAGAKI Koharu")], [#age(15)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2338*], [#delta(-6)],
      [196], [#name("GUO Jiangshan")], [#age(26)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2337*], [#delta(-31)],
      [197], [#name("彭郁涵")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2336*], [#delta(5)],
      [198], [#name("VIVARELLI Debora")], [#age(32)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2334*], [#delta(55)],
      [199], [#name("CHANG Li Sian Alice")], [#age(25)], [#assoc("MAS")], [#right], [#shakehand], [#defense], [*2329*], [#delta(-11)],
      [200], [#name("陈昭澐")], [#age(20)], [#assoc("SGP")], [#right], [#shakehand], [#defense], [*2327*], [#delta(-10)],
    )
  )
