#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("陈梦")], [#age(31)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3135*], [#delta(1)],
      [2], [#name("孙颖莎")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3086*], [#delta(-1)],
      [3], [#name("王曼昱")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3010*], [#delta(0)],
      [4], [#name("朱雨玲")], [#age(30)], [#assoc("MAC")], [#right], [#shakehand], [#attack], [*2986*], [#delta(9)],
      [5], [#name("蒯曼")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2981*], [#delta(-1)],
      [6], [#name("陈熠")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2958*], [#delta(8)],
      [7], [#name("伊藤美诚")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2933*], [#delta(-2)],
      [8], [#name("桥本帆乃香")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2890*], [#delta(-1)],
      [9], [#name("范思琦")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2889*], [#delta(-1)],
      [10], [#name("陈幸同")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2888*], [#delta(-4)],
      [11], [#name("张本美和")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2884*], [#delta(-2)],
      [12], [#name("金琴英")], [#age(24)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2872*], [#delta(-1)],
      [13], [#name("张瑞")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2840*], [#delta(2)],
      [14], [#name("王艺迪")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2831*], [#delta(2)],
      [15], [#name("大藤沙月")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2819*], [#delta(-5)],
      [16], [#name("何卓佳")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2807*], [#delta(1)],
      [17], [#name("刘炜珊")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2794*], [#delta(1)],
      [18], [#name("郑怡静")], [#age(33)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2773*], [#delta(3)],
      [19], [#name("长崎美柚")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2773*], [#delta(-7)],
      [20], [#name("申裕斌")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2772*], [#delta(13)],
      [21], [#name("木原美悠")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2765*], [#delta(-1)],
      [22], [#name("朱芊曦")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2761*], [#delta(12)],
      [23], [#name("石川佳纯")], [#age(32)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2759*], [#delta(-1)],
      [24], [#name("石洵瑶")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2758*], [#delta(-5)],
      [25], [#name("早田希娜")], [#age(25)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2757*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("钱天一")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2756*], [#delta(-3)],
      [27], [#name("安藤南")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2747*], [#delta(-3)],
      [28], [#name("芝田沙季")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2743*], [#delta(-2)],
      [29], [#name("佐藤瞳")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2738*], [#delta(-2)],
      [30], [#name("出泽杏佳")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2732*], [#delta(8)],
      [31], [#name("韩莹")], [#age(42)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2724*], [#delta(9)],
      [32], [#name("袁嘉楠")], [#age(40)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2722*], [#delta(-4)],
      [33], [#name("森樱")], [#age(29)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2716*], [#delta(-2)],
      [34], [#name("覃予萱")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2715*], [#delta(-2)],
      [35], [#name("王晓彤")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2710*], [#delta(4)],
      [36], [#name("徐奕")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2708*], [#delta(-6)],
      [37], [#name("纵歌曼")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2705*], [#delta(-1)],
      [38], [#name("朱思冰")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2692*], [#delta(3)],
      [39], [#name("小盐遥菜")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2691*], [#delta(3)],
      [40], [#name("伯纳黛特 斯佐科斯")], [#age(30)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2684*], [#delta(-5)],
      [41], [#name("边宋京")], [#age(24)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2683*], [#delta(3)],
      [42], [#name("杨屹韵")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2677*], [#delta(-13)],
      [43], [#name("吴洋晨")], [#age(23)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2677*], [#delta(2)],
      [44], [#name("小盐悠菜")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2669*], [#delta(4)],
      [45], [#name("朱梓予")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2667*], [#delta(1)],
      [46], [#name("范姝涵")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2667*], [#delta(1)],
      [47], [#name("李洁")], [#age(41)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2662*], [#delta(2)],
      [48], [#name("韩菲儿")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2658*], [#delta(-5)],
      [49], [#name("高桥 布鲁娜")], [#age(25)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2652*], [#delta(-12)],
      [50], [#name("面田采巳")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2652*], [#delta(24)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("张翔宇")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2649*], [#delta(-1)],
      [52], [#name("梁夏银")], [#age(31)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2648*], [#delta(-1)],
      [53], [#name("普利西卡 帕瓦德")], [#age(21)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2644*], [#delta(1)],
      [54], [#name("索菲亚 波尔卡诺娃")], [#age(31)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2640*], [#delta(-2)],
      [55], [#name("横井咲樱")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2638*], [#delta(1)],
      [56], [#name("斯丽贾 阿库拉")], [#age(27)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2633*], [#delta(210)],
      [57], [#name("阿德里安娜 迪亚兹")], [#age(25)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2631*], [#delta(1)],
      [58], [#name("汉娜 马特洛娃")], [#age(35)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2627*], [#delta(-5)],
      [59], [#name("萨比亚 温特")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2624*], [#delta(-2)],
      [60], [#name("叶伊恬")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2618*], [#delta(3)],
      [61], [#name("KIM Seongjin")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2609*], [#delta(1)],
      [62], [#name("安妮特 考夫曼")], [#age(19)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2605*], [#delta(2)],
      [63], [#name("曾尖")], [#age(29)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2603*], [#delta(-2)],
      [64], [#name("布里特 伊尔兰德")], [#age(31)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2602*], [#delta(5)],
      [65], [#name("嵯水影")], [#age(25)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2601*], [#delta(0)],
      [66], [#name("青木咲智")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2601*], [#delta(38)],
      [67], [#name("徐孝元")], [#age(38)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2600*], [#delta(-1)],
      [68], [#name("郭雨涵")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2600*], [#delta(-1)],
      [69], [#name("奥拉万 帕拉南")], [#age(28)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2589*], [#delta(34)],
      [70], [#name("李昱谆")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2589*], [#delta(-11)],
      [71], [#name("齐菲")], [#age(25)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2587*], [#delta(-1)],
      [72], [#name("朴佳贤")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2585*], [#delta(3)],
      [73], [#name("CHITALE Diya")], [#age(22)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2579*], [#delta(19)],
      [74], [#name("平野美宇")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2578*], [#delta(3)],
      [75], [#name("李多恩")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2572*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("伊丽莎白 阿布拉米安")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2572*], [#delta(-4)],
      [77], [#name("万远")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2570*], [#delta(-22)],
      [78], [#name("CHOI Haeeun")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2566*], [#delta(-2)],
      [79], [#name("PESOTSKA Margaryta")], [#age(34)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2564*], [#delta(27)],
      [80], [#name("DRAGOMAN Andreea")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2563*], [#delta(1)],
      [81], [#name("野村萌")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2553*], [#delta(-3)],
      [82], [#name("李雅可")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2548*], [#delta(1)],
      [83], [#name("安娜 赫西")], [#age(19)], [#assoc("WAL")], [#right], [#shakehand], [#attack], [*2548*], [#delta(-15)],
      [84], [#name("傅玉")], [#age(47)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2546*], [#delta(34)],
      [85], [#name("崔孝珠")], [#age(27)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2546*], [#delta(4)],
      [86], [#name("吴咏琳")], [#age(22)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2545*], [#delta(144)],
      [87], [#name("赤江夏星")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2545*], [#delta(-3)],
      [88], [#name("倪夏莲")], [#age(62)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2544*], [#delta(-2)],
      [89], [#name("陈沂芊")], [#age(23)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2541*], [#delta(-29)],
      [90], [#name("汉娜 高达")], [#age(18)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2540*], [#delta(10)],
      [91], [#name("笹尾明日香")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2539*], [#delta(-3)],
      [92], [#name("陈思羽")], [#age(32)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2537*], [#delta(-1)],
      [93], [#name("杜凯琹")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2535*], [#delta(-6)],
      [94], [#name("姚睿轩")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2533*], [#delta(-4)],
      [95], [#name("金河英")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2533*], [#delta(-1)],
      [96], [#name("苏籽童")], [#age(16)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2530*], [#delta(18)],
      [97], [#name("RYU Hanna")], [#age(23)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2530*], [#delta(-18)],
      [98], [#name("琳达 伯格斯特隆")], [#age(30)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2528*], [#delta(-3)],
      [99], [#name("BAJOR Natalia")], [#age(28)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2527*], [#delta(6)],
      [100], [#name("田志希")], [#age(33)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2526*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("张墨")], [#age(36)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2523*], [#delta(-4)],
      [102], [#name("克里斯蒂娜 卡尔伯格")], [#age(25)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2523*], [#delta(-3)],
      [103], [#name("刘杨子")], [#age(23)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2519*], [#delta(-1)],
      [104], [#name("面手凛")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2518*], [#delta(7)],
      [105], [#name("LUPULESKU Izabela")], [#age(26)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2515*], [#delta(-12)],
      [106], [#name("单晓娜")], [#age(42)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2513*], [#delta(-35)],
      [107], [#name("李恩惠")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2511*], [#delta(45)],
      [108], [#name("艾希卡 穆克吉")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2509*], [#delta(18)],
      [109], [#name("苏蒂尔塔 穆克吉")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2507*], [#delta(35)],
      [110], [#name("伊丽莎白 萨玛拉")], [#age(36)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2506*], [#delta(-3)],
      [111], [#name("高森爱央")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2506*], [#delta(9)],
      [112], [#name("HUANG Yu-Jie")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2506*], [#delta(36)],
      [113], [#name("LUTZ Charlotte")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2505*], [#delta(-31)],
      [114], [#name("乔治娜 波塔")], [#age(40)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2504*], [#delta(-2)],
      [115], [#name("王 艾米")], [#age(23)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2501*], [#delta(12)],
      [116], [#name("PARK Joohyun")], [#age(32)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2499*], [#delta(-3)],
      [117], [#name("HUANG Yu-Chiao")], [#age(29)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2497*], [#delta(-16)],
      [118], [#name("LUTZ Camille")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2496*], [#delta(-33)],
      [119], [#name("KIMURA Kasumi")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2495*], [#delta(-4)],
      [120], [#name("莱娅 拉科瓦奇")], [#age(29)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2493*], [#delta(-24)],
      [121], [#name("妮娜 米特兰姆")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2490*], [#delta(-5)],
      [122], [#name("CIOBANU Irina")], [#age(30)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2489*], [#delta(-5)],
      [123], [#name("李皓晴")], [#age(33)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2488*], [#delta(-4)],
      [124], [#name("ASO Reina")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2486*], [#delta(-3)],
      [125], [#name("杨蕙菁")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2486*], [#delta(-3)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("SOLJA Amelie")], [#age(35)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2482*], [#delta(-3)],
      [127], [#name("YOO Yerin")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2479*], [#delta(-18)],
      [128], [#name("巫嘉恩")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2478*], [#delta(-4)],
      [129], [#name("PICCOLIN Giorgia")], [#age(29)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2474*], [#delta(45)],
      [130], [#name("朱成竹")], [#age(28)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2474*], [#delta(-1)],
      [131], [#name("MONFARDINI Gaia")], [#age(24)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2473*], [#delta(-51)],
      [132], [#name("金娜英")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2473*], [#delta(1)],
      [133], [#name("胡一")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2472*], [#delta(-2)],
      [134], [#name("MATIUNINA Veronika")], [#age(19)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2472*], [#delta(-2)],
      [135], [#name("王添艺")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2470*], [#delta(0)],
      [136], [#name("YAN Yutong")], [#age(17)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2469*], [#delta(53)],
      [137], [#name("KAMATH Archana")], [#age(25)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2468*], [#delta(1)],
      [138], [#name("DING Yijie")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2467*], [#delta(1)],
      [139], [#name("CHENG Pusyuan")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2465*], [#delta(1)],
      [140], [#name("BHOWMICK Divyanshi")], [#age(15)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2464*], [#delta(16)],
      [141], [#name("张安")], [#age(29)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2463*], [#delta(-33)],
      [142], [#name("DIACONU Adina")], [#age(26)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2463*], [#delta(3)],
      [143], [#name("ARAPOVIC Hana")], [#age(21)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2462*], [#delta(-9)],
      [144], [#name("KIM Byeolnim")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2462*], [#delta(-2)],
      [145], [#name("BERGAND Filippa")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2462*], [#delta(84)],
      [146], [#name("邵杰妮")], [#age(31)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2461*], [#delta(-9)],
      [147], [#name("GHOSH Swastika")], [#age(22)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2460*], [#delta(-19)],
      [148], [#name("刘佳")], [#age(43)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2459*], [#delta(-5)],
      [149], [#name("TAILAKOVA Mariia")], [#age(24)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2457*], [NEW],
      [150], [#name("祝启慧")], [#age(13)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2456*], [#delta(-14)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("KIM Seoyun")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2454*], [#delta(-5)],
      [152], [#name("UESAWA Anne")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2454*], [#delta(-5)],
      [153], [#name("LIU Hsing-Yin")], [#age(38)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2450*], [#delta(-28)],
      [154], [#name("SOO Wai Yam")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2450*], [#delta(-5)],
      [155], [#name("GUO ZHENG Nina")], [#age(15)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2448*], [#delta(-5)],
      [156], [#name("苏萨西尼 萨维塔布特")], [#age(31)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2447*], [#delta(-46)],
      [157], [#name("WU Ying Syuan")], [#age(16)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2443*], [#delta(-4)],
      [158], [#name("PENG Yu-Han")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2442*], [#delta(-3)],
      [159], [#name("CHENG Hsien-Tzu")], [#age(32)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2441*], [#delta(-5)],
      [160], [#name("WEGRZYN Katarzyna")], [#age(24)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-19)],
      [161], [#name("ZANG Xiaotong")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-4)],
      [162], [#name("ORTEGA Daniela")], [#age(27)], [#assoc("CHI")], [#right], [#shakehand], [#attack], [*2438*], [#delta(41)],
      [163], [#name("SU Pei-Ling")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2437*], [#delta(-4)],
      [164], [#name("杨晓欣")], [#age(37)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2435*], [#delta(-3)],
      [165], [#name("MEI-ROSU Bianca")], [#age(18)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2435*], [#delta(-3)],
      [166], [#name("HO Tin-Tin")], [#age(27)], [#assoc("ENG")], [#right], [#penhold], [#attack], [*2435*], [#delta(-3)],
      [167], [#name("TAKEYA Misuzu")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2434*], [#delta(-3)],
      [168], [#name("蒂娜 梅谢芙")], [#age(31)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2434*], [#delta(1)],
      [169], [#name("MOYLAND Sally")], [#age(18)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2434*], [#delta(-39)],
      [170], [#name("CHEN Min-Hsin")], [#age(16)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2433*], [#delta(-2)],
      [171], [#name("肖瑶茜")], [#age(31)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2433*], [#delta(-11)],
      [172], [#name("GHORPADE Yashaswini")], [#age(21)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2433*], [#delta(56)],
      [173], [#name("CHEN Ying-Chen")], [#age(26)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-7)],
      [174], [#name("MAKSUTI Aneta")], [#age(30)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-7)],
      [175], [#name("HEO Yerim")], [#age(15)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2430*], [#delta(-17)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("WIELGOS Zuzanna")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2424*], [#delta(-4)],
      [177], [#name("MANTZ Chantal")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2424*], [#delta(-4)],
      [178], [#name("SURJAN Sabina")], [#age(25)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2417*], [#delta(2)],
      [179], [#name("BALINT Bernadett")], [#age(29)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2415*], [#delta(-4)],
      [180], [#name("BRZYSKA Anna")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2414*], [#delta(14)],
      [181], [#name("LOEUILLETTE Stephanie")], [#age(33)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2413*], [#delta(-5)],
      [182], [#name("李多恩")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2409*], [#delta(24)],
      [183], [#name("ALTINKAYA Sibel")], [#age(32)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2408*], [#delta(-12)],
      [184], [#name("TSAI Yun-En")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2407*], [#delta(-5)],
      [185], [#name("LIU Yuan")], [#age(40)], [#assoc("AUT")], [#right], [#penhold], [#attack], [*2407*], [#delta(-4)],
      [186], [#name("LAM Yee Lok")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2407*], [#delta(-35)],
      [187], [#name("HUANG Yi-Hua")], [#age(41)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2407*], [#delta(8)],
      [188], [#name("STRBIKOVA Renata")], [#age(46)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2406*], [#delta(-6)],
      [189], [#name("YOON Hyobin")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2405*], [#delta(-6)],
      [190], [#name("CHASSELIN Pauline")], [#age(28)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2402*], [#delta(-5)],
      [191], [#name("WANG Xiaonan")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2402*], [#delta(-5)],
      [192], [#name("SUNG Rachel")], [#age(21)], [#assoc("USA")], [#left], [#shakehand], [#attack], [*2401*], [#delta(-5)],
      [193], [#name("HAPONOVA Hanna")], [#age(40)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2398*], [#delta(-5)],
      [194], [#name("ZAHARIA Elena")], [#age(21)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2396*], [#delta(-1)],
      [195], [#name("HUANG Yu-Wen")], [#age(29)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2395*], [#delta(-5)],
      [196], [#name("李时温")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2394*], [#delta(-12)],
      [197], [#name("KIM Haeun")], [#age(28)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2394*], [#delta(-6)],
      [198], [#name("ROY Krittwika")], [#age(31)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2394*], [#delta(-21)],
      [199], [#name("LYNE Karen")], [#age(23)], [#assoc("MAS")], [#left], [#shakehand], [#attack], [*2393*], [#delta(-7)],
      [200], [#name("PLAIAN Tania")], [#age(24)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2389*], [#delta(-4)],
    )
  )
