#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("陈梦")], [#age(31)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3135*], [#delta(0)],
      [2], [#name("孙颖莎")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3107*], [#delta(0)],
      [3], [#name("王曼昱")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2974*], [#delta(0)],
      [4], [#name("陈幸同")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2969*], [#delta(0)],
      [5], [#name("蒯曼")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2955*], [#delta(0)],
      [6], [#name("张本美和")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2924*], [#delta(2)],
      [7], [#name("王艺迪")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2923*], [#delta(0)],
      [8], [#name("金琴英")], [#age(24)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2915*], [#delta(-2)],
      [9], [#name("桥本帆乃香")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2898*], [#delta(6)],
      [10], [#name("范思琦")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2889*], [#delta(-1)],
      [11], [#name("何卓佳")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2876*], [#delta(-1)],
      [12], [#name("朱雨玲")], [#age(30)], [#assoc("MAC")], [#right], [#shakehand], [#attack], [*2855*], [#delta(1)],
      [13], [#name("石洵瑶")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2841*], [#delta(-2)],
      [14], [#name("张瑞")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2840*], [#delta(0)],
      [15], [#name("伊藤美诚")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2825*], [#delta(3)],
      [16], [#name("陈熠")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2813*], [#delta(-4)],
      [17], [#name("大藤沙月")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2812*], [#delta(18)],
      [18], [#name("郑怡静")], [#age(33)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2799*], [#delta(8)],
      [19], [#name("刘炜珊")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2787*], [#delta(-3)],
      [20], [#name("早田希娜")], [#age(25)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2780*], [#delta(-1)],
      [21], [#name("申裕斌")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2771*], [#delta(4)],
      [22], [#name("钱天一")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2769*], [#delta(-5)],
      [23], [#name("杨屹韵")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2763*], [#delta(-3)],
      [24], [#name("石川佳纯")], [#age(32)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2759*], [#delta(-3)],
      [25], [#name("佐藤瞳")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2755*], [#delta(3)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("安藤南")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2747*], [#delta(-2)],
      [27], [#name("索菲亚 波尔卡诺娃")], [#age(31)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2745*], [#delta(5)],
      [28], [#name("芝田沙季")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2743*], [#delta(-5)],
      [29], [#name("纵歌曼")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2737*], [#delta(9)],
      [30], [#name("王晓彤")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2725*], [#delta(0)],
      [31], [#name("朱芊曦")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2723*], [#delta(2)],
      [32], [#name("木原美悠")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2716*], [#delta(-3)],
      [33], [#name("森樱")], [#age(29)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2716*], [#delta(1)],
      [34], [#name("覃予萱")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2715*], [#delta(10)],
      [35], [#name("出泽杏佳")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2696*], [#delta(-8)],
      [36], [#name("小盐遥菜")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2691*], [#delta(3)],
      [37], [#name("韩莹")], [#age(42)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2689*], [#delta(-15)],
      [38], [#name("边宋京")], [#age(24)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2688*], [#delta(2)],
      [39], [#name("横井咲樱")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2683*], [#delta(-2)],
      [40], [#name("长崎美柚")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2677*], [#delta(1)],
      [41], [#name("袁嘉楠")], [#age(40)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2677*], [#delta(30)],
      [42], [#name("吴洋晨")], [#age(23)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2677*], [#delta(0)],
      [43], [#name("萨比亚 温特")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2675*], [#delta(0)],
      [44], [#name("高桥 布鲁娜")], [#age(25)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2670*], [#delta(28)],
      [45], [#name("朱思冰")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2668*], [#delta(0)],
      [46], [#name("李洁")], [#age(41)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2662*], [NEW],
      [47], [#name("范姝涵")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2661*], [#delta(0)],
      [48], [#name("韩菲儿")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2658*], [#delta(-2)],
      [49], [#name("小盐悠菜")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2645*], [#delta(2)],
      [50], [#name("安娜 赫西")], [#age(19)], [#assoc("WAL")], [#right], [#shakehand], [#attack], [*2635*], [#delta(34)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("徐孝元")], [#age(38)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2629*], [#delta(-3)],
      [52], [#name("平野美宇")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2623*], [#delta(3)],
      [53], [#name("万远")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2622*], [#delta(1)],
      [54], [#name("陈沂芊")], [#age(23)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2619*], [#delta(14)],
      [55], [#name("徐奕")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2618*], [#delta(4)],
      [56], [#name("崔孝珠")], [#age(27)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2615*], [#delta(19)],
      [57], [#name("阿德里安娜 迪亚兹")], [#age(25)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2612*], [#delta(-1)],
      [58], [#name("安妮特 考夫曼")], [#age(19)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2611*], [#delta(-8)],
      [59], [#name("伯纳黛特 斯佐科斯")], [#age(30)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2610*], [#delta(-28)],
      [60], [#name("伊丽莎白 萨玛拉")], [#age(36)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2601*], [#delta(-7)],
      [61], [#name("嵯水影")], [#age(25)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2601*], [#delta(1)],
      [62], [#name("郭雨涵")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2600*], [#delta(2)],
      [63], [#name("杜凯琹")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2600*], [#delta(-6)],
      [64], [#name("李昱谆")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2599*], [#delta(1)],
      [65], [#name("张安")], [#age(29)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2594*], [#delta(-7)],
      [66], [#name("琳达 伯格斯特隆")], [#age(30)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2592*], [#delta(-6)],
      [67], [#name("赤江夏星")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2591*], [#delta(19)],
      [68], [#name("布里特 伊尔兰德")], [#age(31)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2588*], [#delta(2)],
      [69], [#name("齐菲")], [#age(25)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2587*], [#delta(0)],
      [70], [#name("莱娅 拉科瓦奇")], [#age(29)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2585*], [#delta(39)],
      [71], [#name("奥拉万 帕拉南")], [#age(28)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2575*], [#delta(7)],
      [72], [#name("ABRAAMIAN Elizabet")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2575*], [NEW],
      [73], [#name("苏萨西尼 萨维塔布特")], [#age(31)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2570*], [#delta(27)],
      [74], [#name("ARAPOVIC Hana")], [#age(21)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2563*], [#delta(67)],
      [75], [#name("LAM Yee Lok")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2560*], [#delta(4)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("GHOSH Swastika")], [#age(22)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2560*], [#delta(1)],
      [77], [#name("刘杨子")], [#age(23)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2557*], [#delta(6)],
      [78], [#name("叶伊恬")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2554*], [#delta(-29)],
      [79], [#name("野村萌")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2553*], [#delta(2)],
      [80], [#name("姚睿轩")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2553*], [#delta(17)],
      [81], [#name("李多恩")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2551*], [#delta(-18)],
      [82], [#name("汉娜 高达")], [#age(18)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2550*], [#delta(-21)],
      [83], [#name("李恩惠")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2550*], [#delta(-31)],
      [84], [#name("梁夏银")], [#age(31)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2549*], [#delta(-17)],
      [85], [#name("李雅可")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2548*], [#delta(0)],
      [86], [#name("傅玉")], [#age(47)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2548*], [#delta(-12)],
      [87], [#name("倪夏莲")], [#age(62)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2544*], [#delta(0)],
      [88], [#name("笹尾明日香")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2539*], [#delta(-12)],
      [89], [#name("陈思羽")], [#age(32)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2537*], [#delta(0)],
      [90], [#name("曾尖")], [#age(29)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2536*], [#delta(-10)],
      [91], [#name("金娜英")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2533*], [#delta(-55)],
      [92], [#name("金河英")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2533*], [#delta(-2)],
      [93], [#name("田志希")], [#age(33)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2526*], [#delta(1)],
      [94], [#name("邵杰妮")], [#age(31)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2523*], [#delta(-3)],
      [95], [#name("MOYLAND Sally")], [#age(18)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2520*], [#delta(-2)],
      [96], [#name("蒂娜 梅谢芙")], [#age(31)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2517*], [#delta(2)],
      [97], [#name("CHENG Pusyuan")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2516*], [#delta(2)],
      [98], [#name("单晓娜")], [#age(42)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2513*], [#delta(-2)],
      [99], [#name("乔治娜 波塔")], [#age(40)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2512*], [#delta(2)],
      [100], [#name("PESOTSKA Margaryta")], [#age(34)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2510*], [#delta(36)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("SURJAN Sabina")], [#age(25)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2504*], [#delta(55)],
      [102], [#name("HUANG Yu-Chiao")], [#age(29)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2503*], [#delta(-14)],
      [103], [#name("PARK Joohyun")], [#age(32)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2499*], [#delta(3)],
      [104], [#name("CHITALE Diya")], [#age(22)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2498*], [#delta(12)],
      [105], [#name("祝启慧")], [#age(13)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2497*], [#delta(43)],
      [106], [#name("肖瑶茜")], [#age(31)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2496*], [#delta(-40)],
      [107], [#name("DIACONU Adina")], [#age(26)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2496*], [#delta(-34)],
      [108], [#name("BERGAND Filippa")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2496*], [#delta(32)],
      [109], [#name("克里斯蒂娜 卡尔伯格")], [#age(25)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2495*], [#delta(51)],
      [110], [#name("张翔宇")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2492*], [#delta(0)],
      [111], [#name("SU Tsz Tung")], [#age(16)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2491*], [#delta(1)],
      [112], [#name("HARAC Ece")], [#age(23)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2491*], [#delta(161)],
      [113], [#name("妮娜 米特兰姆")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2490*], [#delta(-31)],
      [114], [#name("CIOBANU Irina")], [#age(30)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2489*], [#delta(0)],
      [115], [#name("李皓晴")], [#age(33)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2488*], [#delta(0)],
      [116], [#name("面手凛")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2487*], [#delta(14)],
      [117], [#name("朴佳贤")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2487*], [#delta(-10)],
      [118], [#name("杨蕙菁")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2486*], [#delta(0)],
      [119], [#name("普利西卡 帕瓦德")], [#age(21)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2484*], [#delta(-27)],
      [120], [#name("AOKI Sachi")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2483*], [#delta(-1)],
      [121], [#name("SOLJA Amelie")], [#age(35)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2482*], [#delta(-1)],
      [122], [#name("KIM Seongjin")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2478*], [#delta(58)],
      [123], [#name("LIU Hsing-Yin")], [#age(38)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2477*], [#delta(-2)],
      [124], [#name("RYU Hanna")], [#age(23)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2475*], [#delta(-21)],
      [125], [#name("艾希卡 穆克吉")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2475*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("朱梓予")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2475*], [#delta(96)],
      [127], [#name("HOCHART Leana")], [#age(17)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2473*], [#delta(12)],
      [128], [#name("王添艺")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2470*], [#delta(-4)],
      [129], [#name("CHOI Haeeun")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2469*], [#delta(-1)],
      [130], [#name("胡一")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2469*], [#delta(7)],
      [131], [#name("高森爱央")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2468*], [#delta(-5)],
      [132], [#name("WIELGOS Zuzanna")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2468*], [#delta(147)],
      [133], [#name("KAMATH Archana")], [#age(25)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2468*], [#delta(-6)],
      [134], [#name("PICCOLIN Giorgia")], [#age(29)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2467*], [#delta(-17)],
      [135], [#name("张墨")], [#age(36)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2467*], [#delta(-30)],
      [136], [#name("MALOBABIC Ivana")], [#age(45)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2466*], [#delta(63)],
      [137], [#name("汉娜 马特洛娃")], [#age(35)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2466*], [#delta(-5)],
      [138], [#name("KIM Byeolnim")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2462*], [#delta(-7)],
      [139], [#name("DRAGOMAN Andreea")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2460*], [#delta(-6)],
      [140], [#name("KLEE Sophia")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2460*], [#delta(141)],
      [141], [#name("刘佳")], [#age(43)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2459*], [#delta(-7)],
      [142], [#name("苏蒂尔塔 穆克吉")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2458*], [#delta(33)],
      [143], [#name("HUANG Yu-Jie")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2457*], [#delta(-41)],
      [144], [#name("UESAWA Anne")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2454*], [#delta(73)],
      [145], [#name("BAJOR Natalia")], [#age(28)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2453*], [#delta(57)],
      [146], [#name("CHEN Min-Hsin")], [#age(16)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2452*], [#delta(-11)],
      [147], [#name("SOO Wai Yam")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2450*], [#delta(-39)],
      [148], [#name("朱成竹")], [#age(28)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2448*], [#delta(-44)],
      [149], [#name("MONFARDINI Gaia")], [#age(24)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2447*], [#delta(-54)],
      [150], [#name("BRATEYKO Solomiya")], [#age(26)], [#assoc("UKR")], [#left], [#shakehand], [#attack], [*2446*], [#delta(-21)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("玛妮卡 巴特拉")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2445*], [#delta(-38)],
      [152], [#name("CHENG Hsien-Tzu")], [#age(32)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2442*], [#delta(-14)],
      [153], [#name("HEO Yerim")], [#age(15)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2439*], [#delta(32)],
      [154], [#name("TAKEYA Misuzu")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2439*], [#delta(-32)],
      [155], [#name("ZANG Xiaotong")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-11)],
      [156], [#name("KIM Seoyun")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2437*], [#delta(9)],
      [157], [#name("SU Pei-Ling")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2437*], [#delta(-11)],
      [158], [#name("DING Yijie")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2437*], [#delta(-15)],
      [159], [#name("杨晓欣")], [#age(37)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2435*], [#delta(-12)],
      [160], [#name("李时温")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2434*], [#delta(32)],
      [161], [#name("CHEN Ying-Chen")], [#age(26)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-12)],
      [162], [#name("MAKSUTI Aneta")], [#age(30)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-12)],
      [163], [#name("LUPULESKU Izabela")], [#age(26)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2430*], [#delta(27)],
      [164], [#name("SAWETTABUT Jinnipa")], [#age(25)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2427*], [#delta(-11)],
      [165], [#name("HO Tin-Tin")], [#age(27)], [#assoc("ENG")], [#right], [#penhold], [#attack], [*2424*], [#delta(-54)],
      [166], [#name("MANTZ Chantal")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2424*], [#delta(-12)],
      [167], [#name("BHOWMICK Divyanshi")], [#age(15)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2422*], [#delta(-9)],
      [168], [#name("MEI-ROSU Bianca")], [#age(18)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2421*], [#delta(-6)],
      [169], [#name("HUANG Yi-Hua")], [#age(41)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2418*], [#delta(-14)],
      [170], [#name("ASO Reina")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2416*], [NEW],
      [171], [#name("BALINT Bernadett")], [#age(29)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2415*], [#delta(-7)],
      [172], [#name("LOEUILLETTE Stephanie")], [#age(33)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2413*], [#delta(-6)],
      [173], [#name("ROY Krittwika")], [#age(31)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2412*], [#delta(-14)],
      [174], [#name("LIU Yuan")], [#age(40)], [#assoc("AUT")], [#right], [#penhold], [#attack], [*2407*], [#delta(-1)],
      [175], [#name("YOON Hyobin")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2405*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("CHOI Nahyun")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2405*], [#delta(40)],
      [177], [#name("CHASSELIN Pauline")], [#age(28)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2402*], [#delta(-1)],
      [178], [#name("WANG Xiaonan")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2402*], [#delta(-1)],
      [179], [#name("SUNG Rachel")], [#age(21)], [#assoc("USA")], [#left], [#shakehand], [#attack], [*2401*], [#delta(-1)],
      [180], [#name("SER Lin Qian")], [#age(19)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2400*], [#delta(1)],
      [181], [#name("HAPONOVA Hanna")], [#age(40)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2398*], [#delta(1)],
      [182], [#name("BALAZOVA Barbora")], [#age(33)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2398*], [#delta(1)],
      [183], [#name("HUANG Yu-Wen")], [#age(29)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2395*], [#delta(1)],
      [184], [#name("KIM Haeun")], [#age(28)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2394*], [#delta(-61)],
      [185], [#name("LYNE Karen")], [#age(23)], [#assoc("MAS")], [#left], [#shakehand], [#attack], [*2393*], [#delta(-43)],
      [186], [#name("YOO Yerin")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2392*], [#delta(2)],
      [187], [#name("YAN Yutong")], [#age(17)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2391*], [#delta(11)],
      [188], [#name("PLAIAN Tania")], [#age(24)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2389*], [#delta(1)],
      [189], [#name("MATIUNINA Veronika")], [#age(19)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2388*], [#delta(-17)],
      [190], [#name("KIMURA Kasumi")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2388*], [#delta(1)],
      [191], [#name("SAINI Suhana")], [#age(19)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2387*], [#delta(-24)],
      [192], [#name("面田采巳")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2387*], [#delta(307)],
      [193], [#name("ZAHARIA Elena")], [#age(21)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2385*], [#delta(-32)],
      [194], [#name("TEE Ai Xin")], [#age(24)], [#assoc("MAS")], [#right], [#penhold], [#attack], [*2384*], [#delta(18)],
      [195], [#name("MIGOT Marie")], [#age(27)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2384*], [#delta(-1)],
      [196], [#name("BRZYSKA Anna")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2383*], [#delta(55)],
      [197], [#name("MORET Rachel")], [#age(36)], [#assoc("SUI")], [#left], [#shakehand], [#attack], [*2383*], [#delta(-45)],
      [198], [#name("ZHANG Sofia-Xuan")], [#age(26)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2382*], [#delta(71)],
      [199], [#name("SCHREINER Franziska")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2382*], [#delta(42)],
      [200], [#name("YOO Siwoo")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2381*], [#delta(-49)],
    )
  )
