#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("刘诗雯")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3041*], [#delta(0)],
      [2], [#name("丁宁")], [#age(28)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*3040*], [#delta(0)],
      [3], [#name("朱雨玲")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3031*], [#delta(2)],
      [4], [#name("王曼昱")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3020*], [#delta(-1)],
      [5], [#name("陈梦")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2990*], [#delta(-1)],
      [6], [#name("石川佳纯")], [#age(25)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2914*], [#delta(0)],
      [7], [#name("陈幸同")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2898*], [#delta(0)],
      [8], [#name("冯亚兰")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2892*], [#delta(0)],
      [9], [#name("孙颖莎")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2889*], [#delta(0)],
      [10], [#name("木子")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2871*], [#delta(0)],
      [11], [#name("顾玉婷")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2867*], [#delta(0)],
      [12], [#name("芝田沙季")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2844*], [#delta(16)],
      [13], [#name("车晓曦")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2813*], [#delta(-1)],
      [14], [#name("胡丽梅")], [#age(23)], [#assoc("CHN")], [#right], [#penhold], [#defense], [*2810*], [#delta(-1)],
      [15], [#name("张瑞")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2802*], [#delta(-1)],
      [16], [#name("郑怡静")], [#age(26)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2781*], [#delta(-1)],
      [17], [#name("武杨")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2781*], [#delta(-1)],
      [18], [#name("陈可")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2766*], [#delta(-1)],
      [19], [#name("LIU Xi")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2758*], [#delta(-1)],
      [20], [#name("王艺迪")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2750*], [#delta(-1)],
      [21], [#name("伊藤美诚")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2749*], [#delta(-1)],
      [22], [#name("平野美宇")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2749*], [#delta(2)],
      [23], [#name("GU Ruochen")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2747*], [#delta(-1)],
      [24], [#name("何卓佳")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2743*], [#delta(-1)],
      [25], [#name("张蔷")], [#age(24)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2726*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("文佳")], [#age(29)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2723*], [#delta(0)],
      [27], [#name("金宋依")], [#age(24)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2718*], [#delta(0)],
      [28], [#name("杜凯琹")], [#age(22)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2713*], [#delta(24)],
      [29], [#name("李佳燚")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2702*], [#delta(0)],
      [30], [#name("长崎美柚")], [#age(16)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2697*], [#delta(19)],
      [31], [#name("冯天薇")], [#age(32)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2689*], [#delta(0)],
      [32], [#name("田志希")], [#age(26)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2688*], [#delta(0)],
      [33], [#name("LANG Kristin")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2681*], [#delta(0)],
      [34], [#name("杨晓欣")], [#age(30)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2678*], [#delta(-4)],
      [35], [#name("加藤美优")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2669*], [#delta(0)],
      [36], [#name("佐藤瞳")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2668*], [#delta(18)],
      [37], [#name("索菲亚 波尔卡诺娃")], [#age(24)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2661*], [#delta(0)],
      [38], [#name("刘高阳")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2657*], [#delta(0)],
      [39], [#name("孙铭阳")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2654*], [#delta(0)],
      [40], [#name("桥本帆乃香")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2652*], [#delta(-6)],
      [41], [#name("范思琦")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2647*], [#delta(0)],
      [42], [#name("李芬")], [#age(42)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2642*], [#delta(-2)],
      [43], [#name("徐孝元")], [#age(31)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2638*], [#delta(-22)],
      [44], [#name("李洁")], [#age(34)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2637*], [#delta(1)],
      [45], [#name("李倩")], [#age(32)], [#assoc("POL")], [#right], [#shakehand], [#defense], [*2634*], [#delta(1)],
      [46], [#name("钱天一")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2633*], [#delta(1)],
      [47], [#name("MIKHAILOVA Polina")], [#age(32)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2628*], [#delta(33)],
      [48], [#name("倪夏莲")], [#age(55)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2628*], [#delta(26)],
      [49], [#name("HUANG Yingqi")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2627*], [#delta(-1)],
      [50], [#name("单晓娜")], [#age(35)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2626*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("傅玉")], [#age(40)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2624*], [#delta(0)],
      [52], [#name("伯纳黛特 斯佐科斯")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2623*], [#delta(-16)],
      [53], [#name("崔孝珠")], [#age(20)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2621*], [#delta(0)],
      [54], [#name("乔治娜 波塔")], [#age(33)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2618*], [#delta(31)],
      [55], [#name("安藤南")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2617*], [#delta(4)],
      [56], [#name("伊丽莎白 萨玛拉")], [#age(29)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2614*], [#delta(30)],
      [57], [#name("早田希娜")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2611*], [#delta(-1)],
      [58], [#name("EKHOLM Matilda")], [#age(36)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2611*], [#delta(-14)],
      [59], [#name("森樱")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2611*], [#delta(33)],
      [60], [#name("石洵瑶")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2609*], [#delta(-5)],
      [61], [#name("浜本由惟")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2608*], [#delta(-4)],
      [62], [#name("曾尖")], [#age(22)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2603*], [#delta(-2)],
      [63], [#name("侯美玲")], [#age(29)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2600*], [#delta(-2)],
      [64], [#name("于梦雨")], [#age(29)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2595*], [#delta(-2)],
      [65], [#name("KIM Youjin")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2594*], [#delta(24)],
      [66], [#name("KIM Jiho")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2590*], [#delta(-3)],
      [67], [#name("SHIOMI Maki")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2588*], [#delta(6)],
      [68], [#name("陈思羽")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2588*], [#delta(-10)],
      [69], [#name("李皓晴")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2586*], [#delta(-26)],
      [70], [#name("YOON Hyobin")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2584*], [#delta(65)],
      [71], [#name("梁夏银")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2583*], [#delta(-29)],
      [72], [#name("刘佳")], [#age(36)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2583*], [#delta(-7)],
      [73], [#name("MATSUZAWA Marina")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2581*], [#delta(-7)],
      [74], [#name("韩莹")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2581*], [#delta(-7)],
      [75], [#name("MAEDA Miyu")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2580*], [#delta(-7)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("大藤沙月")], [#age(14)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2576*], [#delta(-6)],
      [77], [#name("CHENG Hsien-Tzu")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2572*], [#delta(-8)],
      [78], [#name("YOO Eunchong")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2564*], [#delta(-7)],
      [79], [#name("森田美咲")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2563*], [#delta(-7)],
      [80], [#name("VOROBEVA Olga")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2561*], [#delta(-5)],
      [81], [#name("李佼")], [#age(45)], [#assoc("NED")], [#left], [#penhold], [#attack], [*2561*], [#delta(-5)],
      [82], [#name("张墨")], [#age(29)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2559*], [#delta(-5)],
      [83], [#name("HAPONOVA Hanna")], [#age(33)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2558*], [#delta(7)],
      [84], [#name("BALAZOVA Barbora")], [#age(26)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2549*], [#delta(12)],
      [85], [#name("SO Eka")], [#age(23)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2544*], [#delta(-6)],
      [86], [#name("阿德里安娜 迪亚兹")], [#age(18)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2542*], [#delta(29)],
      [87], [#name("佩特丽莎 索尔佳")], [#age(24)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2535*], [#delta(-4)],
      [88], [#name("DODEAN Daniela")], [#age(30)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2535*], [#delta(-4)],
      [89], [#name("JI Eunchae")], [#age(22)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2528*], [#delta(-1)],
      [90], [#name("GRZYBOWSKA-FRANC Katarzyna")], [#age(29)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2528*], [#delta(-12)],
      [91], [#name("PESOTSKA Margaryta")], [#age(27)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2520*], [#delta(0)],
      [92], [#name("苏萨西尼 萨维塔布特")], [#age(24)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2515*], [#delta(26)],
      [93], [#name("CHA Hyo Sim")], [#age(24)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2510*], [#delta(4)],
      [94], [#name("刘炜珊")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2510*], [#delta(4)],
      [95], [#name("LIN Ye")], [#age(22)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2507*], [#delta(5)],
      [96], [#name("NING Jing")], [#age(18)], [#assoc("AZE")], [?], [?], [?], [*2506*], [#delta(5)],
      [97], [#name("玛妮卡 巴特拉")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2505*], [#delta(5)],
      [98], [#name("李时温")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2504*], [#delta(-4)],
      [99], [#name("CHOE Hyon Hwa")], [#age(26)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2502*], [#delta(5)],
      [100], [#name("布里特 伊尔兰德")], [#age(24)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2502*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("KIMURA Mitsuho")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2502*], [#delta(4)],
      [102], [#name("DVORAK Galia")], [#age(30)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2500*], [#delta(18)],
      [103], [#name("SOO Wai Yam")], [#age(20)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2499*], [#delta(-39)],
      [104], [#name("MA Wenting")], [#age(28)], [#assoc("NOR")], [#right], [#shakehand], [#attack], [*2496*], [#delta(-9)],
      [105], [#name("HUANG Yi-Hua")], [#age(34)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2493*], [#delta(3)],
      [106], [#name("LI Xiang")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2491*], [#delta(82)],
      [107], [#name("SOMA Yumeno")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2490*], [#delta(52)],
      [108], [#name("KATO Kyoka")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2488*], [#delta(2)],
      [109], [#name("蒂娜 梅谢芙")], [#age(24)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2488*], [#delta(15)],
      [110], [#name("MALOBABIC Ivana")], [#age(38)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2486*], [#delta(296)],
      [111], [#name("LIU Hsing-Yin")], [#age(31)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2486*], [#delta(0)],
      [112], [#name("PARTYKA Natalia")], [#age(29)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2485*], [#delta(-9)],
      [113], [#name("李恩惠")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2484*], [#delta(-1)],
      [114], [#name("SOLJA Amelie")], [#age(28)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2484*], [#delta(69)],
      [115], [#name("维多利亚 帕芙洛维奇")], [#age(40)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2481*], [#delta(-9)],
      [116], [#name("MORIZONO Mizuki")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2480*], [#delta(-29)],
      [117], [#name("LIN Chia-Chih")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2479*], [#delta(-4)],
      [118], [#name("妮娜 米特兰姆")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2476*], [#delta(-25)],
      [119], [#name("木原美悠")], [#age(14)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2474*], [#delta(-12)],
      [120], [#name("PARK Joohyun")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2472*], [#delta(1)],
      [121], [#name("笹尾明日香")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2471*], [#delta(-7)],
      [122], [#name("KIM Nam Hae")], [#age(22)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2470*], [#delta(0)],
      [123], [#name("朱成竹")], [#age(21)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2468*], [#delta(19)],
      [124], [#name("KIM Seoyeon")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2465*], [#delta(-1)],
      [125], [#name("TAILAKOVA Mariia")], [#age(17)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2464*], [#delta(-43)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("MADARASZ Dora")], [#age(25)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2463*], [#delta(-1)],
      [127], [#name("高桥 布鲁娜")], [#age(18)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2462*], [#delta(39)],
      [128], [#name("PERGEL Szandra")], [#age(30)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2461*], [#delta(59)],
      [129], [#name("ZAHARIA Alina")], [#age(21)], [#assoc("ROU")], [#right], [#shakehand], [#defense], [*2460*], [#delta(-20)],
      [130], [#name("SU Pei-Ling")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2459*], [#delta(-14)],
      [131], [#name("琳达 伯格斯特隆")], [#age(23)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2456*], [#delta(-3)],
      [132], [#name("NOSKOVA Yana")], [#age(24)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2455*], [#delta(5)],
      [133], [#name("YUAN Yuan")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2453*], [#delta(-7)],
      [134], [#name("NARUMOTO Ayami")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2452*], [#delta(-7)],
      [135], [#name("PROKHOROVA Yulia")], [#age(31)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2450*], [#delta(-5)],
      [136], [#name("李昱谆")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2445*], [#delta(26)],
      [137], [#name("PASKAUSKIENE Ruta")], [#age(41)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2444*], [#delta(-5)],
      [138], [#name("STRBIKOVA Renata")], [#age(39)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2444*], [#delta(-21)],
      [139], [#name("NG Wing Nam")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2443*], [#delta(-58)],
      [140], [#name("CHASSELIN Pauline")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2443*], [#delta(38)],
      [141], [#name("萨比亚 温特")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2439*], [#delta(10)],
      [142], [#name("WU Yue")], [#age(28)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2439*], [#delta(13)],
      [143], [#name("ZHOU Yihan")], [#age(24)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2439*], [#delta(-5)],
      [144], [#name("TIAN Yuan")], [#age(43)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2437*], [#delta(-5)],
      [145], [#name("LIN Chia-Hsuan")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2435*], [#delta(23)],
      [146], [#name("ODOROVA Eva")], [#age(39)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2433*], [#delta(-6)],
      [147], [#name("GASNIER Laura")], [#age(25)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2433*], [#delta(0)],
      [148], [#name("LEE Ka Yee")], [#age(16)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-15)],
      [149], [#name("邵杰妮")], [#age(24)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2426*], [#delta(-18)],
      [150], [#name("汉娜 马特洛娃")], [#age(28)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2425*], [#delta(-31)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("DAS Mouma")], [#age(34)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2423*], [#delta(-7)],
      [152], [#name("DOLGIKH Maria")], [#age(31)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2423*], [#delta(-7)],
      [153], [#name("UMEMURA Yuka")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2423*], [#delta(-7)],
      [154], [#name("HUANG Fanzhen")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2422*], [#delta(-6)],
      [155], [#name("申裕斌")], [#age(14)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2421*], [#delta(-6)],
      [156], [#name("JUNG Yumi")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2418*], [#delta(-4)],
      [157], [#name("LIN Chia-Hui")], [#age(31)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2418*], [#delta(-4)],
      [158], [#name("BAJOR Natalia")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2415*], [#delta(-1)],
      [159], [#name("PETEK Petra")], [#age(25)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2411*], [#delta(135)],
      [160], [#name("CHIU Ssu-Hua")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#defense], [*2411*], [#delta(0)],
      [161], [#name("HO Tin-Tin")], [#age(20)], [#assoc("GBR")], [#right], [#penhold], [#attack], [*2411*], [#delta(0)],
      [162], [#name("RI Hyon Sim")], [#age(21)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2409*], [#delta(1)],
      [163], [#name("KUKULKOVA Tatiana")], [#age(18)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2408*], [#delta(1)],
      [164], [#name("KHETKHUAN Tamolwan")], [#age(21)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2407*], [#delta(1)],
      [165], [#name("KATO Chiaki")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2406*], [#delta(2)],
      [166], [#name("肖瑶茜")], [#age(24)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2403*], [#delta(-32)],
      [167], [#name("DRAGOMAN Andreea")], [#age(18)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2402*], [#delta(-24)],
      [168], [#name("LEE Yearam")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2401*], [#delta(2)],
      [169], [#name("SUZUKI Rika")], [#age(24)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2400*], [#delta(20)],
      [170], [#name("JONG Un Ju")], [#age(23)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2399*], [#delta(2)],
      [171], [#name("NAGAO Takako")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2399*], [#delta(2)],
      [172], [#name("BILENKO Tetyana")], [#age(35)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2398*], [#delta(21)],
      [173], [#name("CIOBANU Irina")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2397*], [#delta(-17)],
      [174], [#name("SUN Jiayi")], [#age(18)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2397*], [#delta(-33)],
      [175], [#name("ZARIF Audrey")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2396*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("MIGOT Marie")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2396*], [#delta(35)],
      [177], [#name("GUSEVA Ekaterina")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2395*], [#delta(20)],
      [178], [#name("SABITOVA Valentina")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2394*], [#delta(1)],
      [179], [#name("LOEUILLETTE Stephanie")], [#age(26)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2393*], [#delta(-43)],
      [180], [#name("艾希卡 穆克吉")], [#age(21)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2390*], [#delta(10)],
      [181], [#name("WANG Chen")], [#age(44)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2388*], [#delta(0)],
      [182], [#name("SHCHERBATYKH Valeria")], [#age(20)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2388*], [#delta(-2)],
      [183], [#name("张安")], [#age(22)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2387*], [#delta(-8)],
      [184], [#name("KUMAHARA Luca")], [#age(23)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2387*], [#delta(-2)],
      [185], [#name("PRIVALOVA Alexandra")], [#age(31)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2386*], [#delta(21)],
      [186], [#name("TODOROVIC Andrea")], [#age(26)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2384*], [#delta(5)],
      [187], [#name("BALINT Bernadett")], [#age(22)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2384*], [#delta(47)],
      [188], [#name("DIACONU Adina")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2382*], [#delta(-4)],
      [189], [#name("GRUNDISCH Carole")], [#age(32)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2381*], [#delta(-4)],
      [190], [#name("LI Ching Wan")], [#age(24)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2380*], [#delta(75)],
      [191], [#name("LUPULESKU Izabela")], [#age(19)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2378*], [#delta(24)],
      [192], [#name("MATSUDAIRA Shiho")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2376*], [#delta(-6)],
      [193], [#name("PICCOLIN Giorgia")], [#age(22)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2375*], [#delta(-22)],
      [194], [#name("LIU Yu-Hsin")], [#age(25)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2372*], [#delta(23)],
      [195], [#name("MANTZ Chantal")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2371*], [#delta(-3)],
      [196], [#name("JEGER Mateja")], [#age(23)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2367*], [#delta(-67)],
      [197], [#name("HUANG Yu-Chiao")], [#age(22)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2366*], [#delta(1)],
      [198], [#name("KULIKOVA Olga")], [#age(25)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2365*], [#delta(-40)],
      [199], [#name("LAM Yee Lok")], [#age(22)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2365*], [#delta(-49)],
      [200], [#name("LEE Yujin")], [#age(22)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2364*], [#delta(0)],
    )
  )
