#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("丁宁")], [#age(28)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*3098*], [#delta(0)],
      [2], [#name("陈梦")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3033*], [#delta(1)],
      [3], [#name("朱雨玲")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2975*], [#delta(2)],
      [4], [#name("刘诗雯")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2962*], [#delta(2)],
      [5], [#name("孙颖莎")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2947*], [#delta(2)],
      [6], [#name("陈幸同")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2944*], [#delta(-4)],
      [7], [#name("王曼昱")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2934*], [#delta(-3)],
      [8], [#name("木子")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2912*], [#delta(0)],
      [9], [#name("冯亚兰")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2892*], [#delta(0)],
      [10], [#name("顾玉婷")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2867*], [#delta(0)],
      [11], [#name("胡丽梅")], [#age(23)], [#assoc("CHN")], [#right], [#penhold], [#defense], [*2826*], [#delta(1)],
      [12], [#name("石川佳纯")], [#age(25)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2806*], [#delta(-1)],
      [13], [#name("张蔷")], [#age(24)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2805*], [#delta(1)],
      [14], [#name("陈可")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2787*], [#delta(1)],
      [15], [#name("伊藤美诚")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2785*], [#delta(-2)],
      [16], [#name("金宋依")], [#age(24)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2763*], [#delta(0)],
      [17], [#name("武杨")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2761*], [#delta(0)],
      [18], [#name("LIU Xi")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2758*], [#delta(0)],
      [19], [#name("张瑞")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2752*], [#delta(0)],
      [20], [#name("GU Ruochen")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2747*], [#delta(0)],
      [21], [#name("田志希")], [#age(26)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2739*], [#delta(0)],
      [22], [#name("车晓曦")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2738*], [#delta(0)],
      [23], [#name("LANG Kristin")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2728*], [#delta(0)],
      [24], [#name("文佳")], [#age(29)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2728*], [#delta(0)],
      [25], [#name("伊丽莎白 萨玛拉")], [#age(29)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2719*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("早田希娜")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2710*], [#delta(0)],
      [27], [#name("孙铭阳")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2709*], [#delta(1)],
      [28], [#name("李倩")], [#age(32)], [#assoc("POL")], [#right], [#shakehand], [#defense], [*2696*], [#delta(1)],
      [29], [#name("徐孝元")], [#age(31)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2694*], [#delta(1)],
      [30], [#name("李佳燚")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2691*], [#delta(2)],
      [31], [#name("索菲亚 波尔卡诺娃")], [#age(24)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2689*], [#delta(2)],
      [32], [#name("加藤美优")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2688*], [#delta(-5)],
      [33], [#name("平野美宇")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2681*], [#delta(-2)],
      [34], [#name("何卓佳")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2676*], [#delta(0)],
      [35], [#name("冯天薇")], [#age(32)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2661*], [#delta(24)],
      [36], [#name("芝田沙季")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2658*], [#delta(1)],
      [37], [#name("刘高阳")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2657*], [#delta(1)],
      [38], [#name("刘佳")], [#age(36)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2655*], [#delta(1)],
      [39], [#name("杜凯琹")], [#age(22)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2655*], [#delta(-3)],
      [40], [#name("杨晓欣")], [#age(30)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2650*], [#delta(0)],
      [41], [#name("傅玉")], [#age(40)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2647*], [#delta(2)],
      [42], [#name("DODEAN Daniela")], [#age(30)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2646*], [#delta(2)],
      [43], [#name("陈思羽")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2645*], [#delta(2)],
      [44], [#name("李洁")], [#age(34)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2645*], [#delta(2)],
      [45], [#name("李芬")], [#age(42)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2645*], [#delta(2)],
      [46], [#name("侯美玲")], [#age(29)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2644*], [#delta(2)],
      [47], [#name("乔治娜 波塔")], [#age(33)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2643*], [#delta(2)],
      [48], [#name("曾尖")], [#age(22)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2641*], [#delta(2)],
      [49], [#name("姜华珺")], [#age(34)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2640*], [#delta(2)],
      [50], [#name("浜本由惟")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2637*], [#delta(2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("伯纳黛特 斯佐科斯")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2635*], [#delta(3)],
      [52], [#name("桥本帆乃香")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2635*], [#delta(3)],
      [53], [#name("王艺迪")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2630*], [#delta(3)],
      [54], [#name("长崎美柚")], [#age(16)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2627*], [#delta(20)],
      [55], [#name("钱天一")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2627*], [#delta(10)],
      [56], [#name("单晓娜")], [#age(35)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2626*], [#delta(-3)],
      [57], [#name("韩莹")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2625*], [#delta(-15)],
      [58], [#name("李皓晴")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2623*], [#delta(-1)],
      [59], [#name("MAEDA Miyu")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2613*], [#delta(-1)],
      [60], [#name("安藤南")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2604*], [#delta(2)],
      [61], [#name("于梦雨")], [#age(29)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2602*], [#delta(-1)],
      [62], [#name("SOO Wai Yam")], [#age(20)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2599*], [#delta(1)],
      [63], [#name("CHENG Hsien-Tzu")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2598*], [#delta(1)],
      [64], [#name("郑怡静")], [#age(26)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2597*], [#delta(-29)],
      [65], [#name("石洵瑶")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2597*], [#delta(-24)],
      [66], [#name("崔孝珠")], [#age(20)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2593*], [#delta(0)],
      [67], [#name("倪夏莲")], [#age(55)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2589*], [#delta(0)],
      [68], [#name("森樱")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2581*], [#delta(-7)],
      [69], [#name("MATSUZAWA Marina")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2581*], [#delta(0)],
      [70], [#name("妮娜 米特兰姆")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2580*], [#delta(0)],
      [71], [#name("维多利亚 帕芙洛维奇")], [#age(40)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2579*], [#delta(0)],
      [72], [#name("佐藤瞳")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2578*], [#delta(-4)],
      [73], [#name("MIKHAILOVA Polina")], [#age(32)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2576*], [#delta(-1)],
      [74], [#name("MORIZONO Mizuki")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2576*], [#delta(-1)],
      [75], [#name("森田美咲")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2563*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("李佼")], [#age(45)], [#assoc("NED")], [#left], [#penhold], [#attack], [*2561*], [#delta(1)],
      [77], [#name("梁夏银")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2560*], [#delta(1)],
      [78], [#name("大藤沙月")], [#age(14)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2558*], [#delta(1)],
      [79], [#name("木原美悠")], [#age(14)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2555*], [#delta(-3)],
      [80], [#name("苏萨西尼 萨维塔布特")], [#age(24)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2553*], [#delta(0)],
      [81], [#name("BALAZOVA Barbora")], [#age(26)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2550*], [#delta(0)],
      [82], [#name("EKHOLM Matilda")], [#age(36)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2548*], [#delta(0)],
      [83], [#name("布里特 伊尔兰德")], [#age(24)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2545*], [#delta(0)],
      [84], [#name("SO Eka")], [#age(23)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2544*], [#delta(0)],
      [85], [#name("SHIOMI Maki")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2529*], [#delta(0)],
      [86], [#name("JI Eunchae")], [#age(22)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2528*], [#delta(0)],
      [87], [#name("KIM Youjin")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2525*], [#delta(1)],
      [88], [#name("HUANG Yi-Hua")], [#age(34)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2524*], [#delta(-1)],
      [89], [#name("ZHOU Yihan")], [#age(24)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2520*], [#delta(0)],
      [90], [#name("NOSKOVA Yana")], [#age(24)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2518*], [#delta(1)],
      [91], [#name("李时温")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2518*], [#delta(1)],
      [92], [#name("MA Wenting")], [#age(28)], [#assoc("NOR")], [#right], [#shakehand], [#attack], [*2514*], [#delta(1)],
      [93], [#name("阿德里安娜 迪亚兹")], [#age(18)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2512*], [#delta(-3)],
      [94], [#name("VOROBEVA Olga")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2512*], [#delta(0)],
      [95], [#name("佩特丽莎 索尔佳")], [#age(24)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2511*], [#delta(0)],
      [96], [#name("刘炜珊")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2510*], [#delta(0)],
      [97], [#name("SUN Jiayi")], [#age(18)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2509*], [#delta(0)],
      [98], [#name("NING Jing")], [#age(18)], [#assoc("AZE")], [?], [?], [?], [*2506*], [#delta(0)],
      [99], [#name("CHOE Hyon Hwa")], [#age(26)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2502*], [#delta(0)],
      [100], [#name("KIMURA Mitsuho")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2502*], [#delta(94)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("肖瑶茜")], [#age(24)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2501*], [#delta(-1)],
      [102], [#name("DIACONU Adina")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2496*], [#delta(4)],
      [103], [#name("张墨")], [#age(29)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2493*], [#delta(-2)],
      [104], [#name("LIN Ye")], [#age(22)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2492*], [#delta(-2)],
      [105], [#name("KIM Jiho")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2492*], [#delta(5)],
      [106], [#name("NG Wing Nam")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2488*], [#delta(-3)],
      [107], [#name("KATO Kyoka")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2488*], [#delta(-3)],
      [108], [#name("邵杰妮")], [#age(24)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2486*], [#delta(-3)],
      [109], [#name("李恩惠")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2484*], [#delta(-2)],
      [110], [#name("KHETKHUAN Tamolwan")], [#age(21)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2484*], [#delta(-2)],
      [111], [#name("笹尾明日香")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2478*], [#delta(0)],
      [112], [#name("PARK Joohyun")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2472*], [#delta(0)],
      [113], [#name("PROKHOROVA Yulia")], [#age(31)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2469*], [#delta(0)],
      [114], [#name("PASKAUSKIENE Ruta")], [#age(41)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2468*], [#delta(0)],
      [115], [#name("PESOTSKA Margaryta")], [#age(27)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2467*], [#delta(0)],
      [116], [#name("KIM Seoyeon")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2465*], [#delta(0)],
      [117], [#name("STRBIKOVA Renata")], [#age(39)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2459*], [#delta(1)],
      [118], [#name("DOLGIKH Maria")], [#age(31)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2453*], [#delta(1)],
      [119], [#name("YUAN Yuan")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2453*], [#delta(1)],
      [120], [#name("NARUMOTO Ayami")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2452*], [#delta(2)],
      [121], [#name("HAPONOVA Hanna")], [#age(33)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2449*], [#delta(2)],
      [122], [#name("汉娜 马特洛娃")], [#age(28)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2448*], [#delta(2)],
      [123], [#name("LIU Hsing-Yin")], [#age(31)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2448*], [#delta(2)],
      [124], [#name("高桥 布鲁娜")], [#age(18)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2448*], [#delta(4)],
      [125], [#name("LIN Chia-Hui")], [#age(31)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2444*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("YOON Hyobin")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2441*], [#delta(1)],
      [127], [#name("CHA Hyo Sim")], [#age(24)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2438*], [#delta(2)],
      [128], [#name("TIAN Yuan")], [#age(43)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2437*], [#delta(3)],
      [129], [#name("范思琦")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2436*], [#delta(3)],
      [130], [#name("LEE Ka Yee")], [#age(16)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2434*], [#delta(128)],
      [131], [#name("YOO Eunchong")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2433*], [#delta(2)],
      [132], [#name("LIN Chia-Chih")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2433*], [#delta(2)],
      [133], [#name("ODOROVA Eva")], [#age(39)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2433*], [#delta(2)],
      [134], [#name("LOEUILLETTE Stephanie")], [#age(26)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2433*], [#delta(2)],
      [135], [#name("PERGEL Szandra")], [#age(30)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2433*], [#delta(2)],
      [136], [#name("玛妮卡 巴特拉")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2432*], [#delta(2)],
      [137], [#name("HO Tin-Tin")], [#age(20)], [#assoc("GBR")], [#right], [#penhold], [#attack], [*2431*], [#delta(2)],
      [138], [#name("琳达 伯格斯特隆")], [#age(23)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2429*], [#delta(2)],
      [139], [#name("朱成竹")], [#age(21)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2427*], [#delta(2)],
      [140], [#name("TAILAKOVA Mariia")], [#age(17)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2425*], [#delta(-19)],
      [141], [#name("PARTYKA Natalia")], [#age(29)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2424*], [#delta(1)],
      [142], [#name("UMEMURA Yuka")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2423*], [#delta(1)],
      [143], [#name("LIN Chia-Hsuan")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2422*], [#delta(1)],
      [144], [#name("SU Pei-Ling")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2422*], [#delta(51)],
      [145], [#name("LAM Yee Lok")], [#age(22)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2421*], [#delta(0)],
      [146], [#name("GRZYBOWSKA-FRANC Katarzyna")], [#age(29)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2420*], [#delta(0)],
      [147], [#name("HUANG Yingqi")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2420*], [#delta(0)],
      [148], [#name("JUNG Yumi")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2418*], [#delta(0)],
      [149], [#name("GUI Lin")], [#age(25)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2418*], [#delta(0)],
      [150], [#name("KIM Nam Hae")], [#age(22)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2416*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("蒂娜 梅谢芙")], [#age(24)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2416*], [#delta(0)],
      [152], [#name("GASNIER Laura")], [#age(25)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2415*], [#delta(0)],
      [153], [#name("ZHANG Sofia-Xuan")], [#age(19)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2413*], [#delta(157)],
      [154], [#name("KULIKOVA Olga")], [#age(25)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2413*], [#delta(-1)],
      [155], [#name("WU Yue")], [#age(28)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2413*], [#delta(-38)],
      [156], [#name("CHIU Ssu-Hua")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#defense], [*2411*], [#delta(-2)],
      [157], [#name("李昱谆")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2410*], [#delta(-2)],
      [158], [#name("RI Hyon Sim")], [#age(21)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2409*], [#delta(-2)],
      [159], [#name("DRAGOMAN Andreea")], [#age(18)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2408*], [#delta(-29)],
      [160], [#name("KATO Chiaki")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2406*], [NEW],
      [161], [#name("SHCHERBATYKH Valeria")], [#age(20)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2405*], [#delta(-3)],
      [162], [#name("LEE Yearam")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2401*], [#delta(-3)],
      [163], [#name("JONG Un Ju")], [#age(23)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2399*], [#delta(-3)],
      [164], [#name("张安")], [#age(22)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2399*], [#delta(-55)],
      [165], [#name("NAGAO Takako")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2399*], [#delta(-4)],
      [166], [#name("KAMATH Archana")], [#age(18)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2397*], [#delta(103)],
      [167], [#name("KOMWONG Nanthana")], [#age(38)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2397*], [#delta(-5)],
      [168], [#name("HUANG Yu-Wen")], [#age(22)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2395*], [#delta(-5)],
      [169], [#name("MORET Rachel")], [#age(29)], [#assoc("SUI")], [#left], [#shakehand], [#attack], [*2395*], [#delta(21)],
      [170], [#name("SABITOVA Valentina")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2394*], [#delta(-6)],
      [171], [#name("PFEFER Laura")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2392*], [#delta(-6)],
      [172], [#name("VASYLIEVA Ievgeniia")], [#age(28)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2392*], [#delta(-6)],
      [173], [#name("GUSEVA Ekaterina")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2391*], [#delta(-6)],
      [174], [#name("萨比亚 温特")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2391*], [#delta(-6)],
      [175], [#name("WANG Chen")], [#age(44)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2388*], [#delta(-6)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("MADARASZ Dora")], [#age(25)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2387*], [#delta(-6)],
      [177], [#name("KUMAHARA Luca")], [#age(23)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2387*], [#delta(-6)],
      [178], [#name("JEGER Mateja")], [#age(23)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2387*], [#delta(-6)],
      [179], [#name("SUN Yizhen")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2384*], [#delta(-6)],
      [180], [#name("LEE I-Chen")], [#age(31)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2381*], [#delta(-5)],
      [181], [#name("GRUNDISCH Carole")], [#age(32)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2381*], [#delta(-5)],
      [182], [#name("GALIC Alex")], [#age(24)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2376*], [#delta(-5)],
      [183], [#name("LAY Jian Fang")], [#age(45)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2376*], [#delta(-5)],
      [184], [#name("MATSUDAIRA Shiho")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2376*], [#delta(-5)],
      [185], [#name("SUZUKI Rika")], [#age(24)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2374*], [#delta(-5)],
      [186], [#name("艾希卡 穆克吉")], [#age(21)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2373*], [#delta(-5)],
      [187], [#name("MANTZ Chantal")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2371*], [#delta(-4)],
      [188], [#name("KOLISH Anastasia")], [#age(17)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2370*], [#delta(13)],
      [189], [#name("CIOBANU Irina")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2369*], [#delta(-5)],
      [190], [#name("SOLJA Amelie")], [#age(28)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2369*], [#delta(-5)],
      [191], [#name("SOMA Yumeno")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2369*], [#delta(-5)],
      [192], [#name("MIGOT Marie")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2366*], [#delta(-4)],
      [193], [#name("HUANG Yu-Chiao")], [#age(22)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2366*], [#delta(-4)],
      [194], [#name("LEE Yujin")], [#age(22)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2364*], [#delta(-3)],
      [195], [#name("NAGYVARADI Mercedes")], [#age(24)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2363*], [#delta(-2)],
      [196], [#name("万远")], [#age(21)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2360*], [#delta(0)],
      [197], [#name("ZHOU Chuyi")], [#age(17)], [#assoc("AZE")], [#right], [#penhold], [#attack], [*2358*], [#delta(1)],
      [198], [#name("TRIGOLOS Daria")], [#age(19)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2358*], [#delta(-11)],
      [199], [#name("HUANG Hsin")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2356*], [#delta(0)],
      [200], [#name("SAWETTABUT Jinnipa")], [#age(18)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2356*], [#delta(-18)],
    )
  )
