#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("陈梦")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3131*], [#delta(0)],
      [2], [#name("王曼昱")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3005*], [#delta(2)],
      [3], [#name("伊藤美诚")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2992*], [#delta(4)],
      [4], [#name("王艺迪")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2971*], [#delta(1)],
      [5], [#name("孙颖莎")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2955*], [#delta(-3)],
      [6], [#name("刘诗雯")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2950*], [#delta(0)],
      [7], [#name("钱天一")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2864*], [#delta(2)],
      [8], [#name("陈幸同")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2862*], [#delta(8)],
      [9], [#name("石川佳纯")], [#age(27)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2843*], [#delta(1)],
      [10], [#name("郑怡静")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2834*], [#delta(2)],
      [11], [#name("张瑞")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2829*], [#delta(2)],
      [12], [#name("早田希娜")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2804*], [#delta(2)],
      [13], [#name("桥本帆乃香")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2786*], [#delta(5)],
      [14], [#name("佐藤瞳")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2776*], [#delta(9)],
      [15], [#name("单晓娜")], [#age(37)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2768*], [#delta(7)],
      [16], [#name("木原美悠")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2755*], [#delta(18)],
      [17], [#name("田志希")], [#age(28)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2755*], [#delta(3)],
      [18], [#name("冯天薇")], [#age(34)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2745*], [#delta(20)],
      [19], [#name("平野美宇")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2737*], [#delta(10)],
      [20], [#name("韩莹")], [#age(37)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2726*], [#delta(4)],
      [21], [#name("范思琦")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2726*], [#delta(4)],
      [22], [#name("何卓佳")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2724*], [#delta(-7)],
      [23], [#name("石洵瑶")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2718*], [#delta(4)],
      [24], [#name("芝田沙季")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2715*], [#delta(-5)],
      [25], [#name("加藤美优")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2714*], [#delta(10)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("刘炜珊")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2711*], [#delta(4)],
      [27], [#name("长崎美柚")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2695*], [#delta(1)],
      [28], [#name("崔孝珠")], [#age(22)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2694*], [#delta(3)],
      [29], [#name("安藤南")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2691*], [#delta(3)],
      [30], [#name("杨晓欣")], [#age(32)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2676*], [#delta(3)],
      [31], [#name("妮娜 米特兰姆")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2653*], [#delta(-5)],
      [32], [#name("蒯曼")], [#age(16)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2652*], [#delta(7)],
      [33], [#name("陈思羽")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2649*], [#delta(7)],
      [34], [#name("布里特 伊尔兰德")], [#age(26)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2645*], [#delta(7)],
      [35], [#name("佩特丽莎 索尔佳")], [#age(26)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2645*], [#delta(2)],
      [36], [#name("陈熠")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2641*], [#delta(7)],
      [37], [#name("曾尖")], [#age(24)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2639*], [#delta(5)],
      [38], [#name("小盐遥菜")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2637*], [#delta(-2)],
      [39], [#name("倪夏莲")], [#age(57)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2634*], [#delta(5)],
      [40], [#name("梁夏银")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2633*], [#delta(5)],
      [41], [#name("于梦雨")], [#age(31)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2632*], [#delta(9)],
      [42], [#name("森樱")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2617*], [#delta(32)],
      [43], [#name("李倩")], [#age(34)], [#assoc("CHN")], [?], [?], [?], [*2615*], [#delta(6)],
      [44], [#name("吴洋晨")], [#age(18)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2611*], [#delta(7)],
      [45], [#name("玛妮卡 巴特拉")], [#age(25)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2611*], [#delta(7)],
      [46], [#name("李皓晴")], [#age(28)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2607*], [#delta(15)],
      [47], [#name("索菲亚 波尔卡诺娃")], [#age(26)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2604*], [#delta(12)],
      [48], [#name("杜凯琹")], [#age(24)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2602*], [#delta(-2)],
      [49], [#name("素塔西尼 萨维塔布特")], [#age(26)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2599*], [#delta(4)],
      [50], [#name("徐孝元")], [#age(33)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2598*], [#delta(6)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("李时温")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2597*], [#delta(6)],
      [52], [#name("郑先知")], [#age(27)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2595*], [#delta(6)],
      [53], [#name("苏慧音")], [#age(22)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2595*], [#delta(-5)],
      [54], [#name("傅玉")], [#age(42)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2590*], [#delta(-7)],
      [55], [#name("玛格丽塔 佩索茨卡")], [#age(29)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2583*], [#delta(-1)],
      [56], [#name("金河英")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2577*], [#delta(4)],
      [57], [#name("袁嘉楠")], [#age(35)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2564*], [#delta(-2)],
      [58], [#name("阿德里安娜 迪亚兹")], [#age(20)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2562*], [#delta(4)],
      [59], [#name("萨宾 温特")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2561*], [#delta(4)],
      [60], [#name("波琳娜 米哈伊洛娃")], [#age(34)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2546*], [#delta(6)],
      [61], [#name("李恩惠")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2545*], [#delta(6)],
      [62], [#name("申裕斌")], [#age(16)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2543*], [#delta(6)],
      [63], [#name("大藤沙月")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2540*], [#delta(6)],
      [64], [#name("柳恩钟")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2533*], [#delta(8)],
      [65], [#name("伊丽莎白 萨马拉")], [#age(31)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2532*], [#delta(18)],
      [66], [#name("朱成竹")], [#age(23)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2531*], [#delta(-2)],
      [67], [#name("林叶")], [#age(24)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2530*], [#delta(3)],
      [68], [#name("邵杰妮")], [#age(26)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2524*], [#delta(3)],
      [69], [#name("阿迪娜 迪亚科努")], [#age(21)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2522*], [#delta(4)],
      [70], [#name("丹妮拉 多迪安")], [#age(32)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2516*], [#delta(5)],
      [71], [#name("乔治娜 波塔")], [#age(35)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2510*], [#delta(5)],
      [72], [#name("奥拉万 帕拉南")], [#age(23)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2508*], [#delta(5)],
      [73], [#name("卡塔日娜 格日博夫斯卡-弗朗茨")], [#age(31)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2503*], [#delta(5)],
      [74], [#name("李昱谆")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2496*], [#delta(8)],
      [75], [#name("普利蒂卡 帕瓦德")], [#age(16)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2491*], [#delta(57)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("刘佳")], [#age(38)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2485*], [#delta(8)],
      [77], [#name("吴颖岚")], [#age(28)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2484*], [#delta(9)],
      [78], [#name("金星宁")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2480*], [#delta(9)],
      [79], [#name("娜塔莉亚 巴约尔")], [#age(23)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2477*], [#delta(1)],
      [80], [#name("吴玥")], [#age(30)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2473*], [#delta(8)],
      [81], [#name("杨蕙菁")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2472*], [#delta(8)],
      [82], [#name("汉娜 马特洛娃")], [#age(30)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2472*], [#delta(-3)],
      [83], [#name("安娜 韦格任")], [#age(19)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2471*], [#delta(31)],
      [84], [#name("巴尔博拉 巴拉佐娃")], [#age(28)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2467*], [#delta(-3)],
      [85], [#name("加利娅 德沃拉克")], [#age(32)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2464*], [#delta(25)],
      [86], [#name("王艾米")], [#age(18)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2463*], [#delta(6)],
      [87], [#name("张安")], [#age(24)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2460*], [#delta(4)],
      [88], [#name("伯纳黛特 斯佐科斯")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2459*], [#delta(5)],
      [89], [#name("特蒂亚娜 比连科")], [#age(37)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2441*], [#delta(6)],
      [90], [#name("伊琳娜 乔巴努")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2440*], [#delta(7)],
      [91], [#name("林依诺")], [#age(24)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2439*], [#delta(7)],
      [92], [#name("布鲁娜 高桥")], [#age(20)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2436*], [#delta(8)],
      [93], [#name("奥尔加 沃罗贝娃")], [#age(30)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2435*], [#delta(-8)],
      [94], [#name("瓦列里娅 谢尔巴特赫")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2434*], [#delta(7)],
      [95], [#name("刘馨尹")], [#age(33)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2432*], [#delta(7)],
      [96], [#name("张墨")], [#age(31)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2432*], [#delta(7)],
      [97], [#name("TOMANOVSKA Katerina")], [#age(25)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2430*], [#delta(7)],
      [98], [#name("LIU Juan")], [#age(35)], [#assoc("USA")], [#left], [#penhold], [#attack], [*2428*], [#delta(8)],
      [99], [#name("横井咲樱")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2422*], [#delta(29)],
      [100], [#name("莎拉 德努特")], [#age(28)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2422*], [#delta(53)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("琳达 伯格斯特隆")], [#age(25)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2418*], [#delta(10)],
      [102], [#name("LENG Yutong")], [#age(16)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2417*], [#delta(10)],
      [103], [#name("MIGOT Marie")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2410*], [#delta(-4)],
      [104], [#name("苏蒂尔塔 穆克吉")], [#age(25)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2409*], [#delta(-14)],
      [105], [#name("亚娜 诺斯科娃")], [#age(26)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2409*], [#delta(0)],
      [106], [#name("洪剑芳")], [#age(47)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2407*], [#delta(9)],
      [107], [#name("齐菲")], [#age(20)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2404*], [#delta(10)],
      [108], [#name("斯丽贾 阿库拉")], [#age(22)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2401*], [#delta(1)],
      [109], [#name("何天天")], [#age(22)], [#assoc("GBR")], [#right], [#penhold], [#attack], [*2399*], [#delta(9)],
      [110], [#name("肖瑶茜")], [#age(26)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2397*], [#delta(-2)],
      [111], [#name("玛丽亚 泰拉科娃")], [#age(19)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2395*], [#delta(5)],
      [112], [#name("TRIGOLOS Daria")], [#age(21)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2395*], [#delta(15)],
      [113], [#name("尚塔尔 曼茨")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2393*], [#delta(7)],
      [114], [#name("安德烈娅 德拉戈曼")], [#age(20)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2393*], [#delta(53)],
      [115], [#name("伊万娜 马洛巴比奇")], [#age(40)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2390*], [#delta(7)],
      [116], [#name("娜塔莉亚 帕尔蒂卡")], [#age(31)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2390*], [#delta(-20)],
      [117], [#name("艾卡特里尼 托利乌")], [#age(25)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2389*], [#delta(6)],
      [118], [#name("多拉 马达拉斯")], [#age(27)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2387*], [#delta(6)],
      [119], [#name("奥黛丽 扎里夫")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2386*], [#delta(6)],
      [120], [#name("马泰娅 耶格尔")], [#age(25)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2384*], [#delta(6)],
      [121], [#name("艾希卡 穆克吉")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2382*], [#delta(8)],
      [122], [#name("李清韵")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2382*], [#delta(8)],
      [123], [#name("LUNG Lisa")], [#age(21)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2377*], [#delta(-4)],
      [124], [#name("埃列娜 扎哈里亚")], [#age(16)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2376*], [#delta(10)],
      [125], [#name("汉娜 哈珀诺娃")], [#age(35)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2375*], [#delta(-4)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("史蒂芬妮 洛伊莱")], [#age(28)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2371*], [#delta(-19)],
      [127], [#name("伊丽莎白 阿布拉米安")], [#age(17)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2369*], [#delta(6)],
      [128], [#name("塔尼娅 普莱安")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2368*], [#delta(16)],
      [129], [#name("卡琳 格罗福娃")], [#age(26)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2363*], [#delta(25)],
      [130], [#name("万远")], [#age(23)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2363*], [#delta(5)],
      [131], [#name("BOGDANOVA Nadezhda")], [#age(20)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2359*], [#delta(5)],
      [132], [#name("KOLISH Anastasia")], [#age(19)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2356*], [#delta(17)],
      [133], [#name("柳韩娜")], [#age(18)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2354*], [#delta(6)],
      [134], [#name("张本美和")], [#age(12)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2353*], [#delta(6)],
      [135], [#name("SUNG Rachel")], [#age(16)], [#assoc("USA")], [#left], [#shakehand], [#attack], [*2350*], [#delta(6)],
      [136], [#name("克里斯蒂娜 卡尔伯格")], [#age(20)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2350*], [#delta(98)],
      [137], [#name("金妮帕 萨维塔布特")], [#age(20)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2349*], [#delta(5)],
      [138], [#name("安德里亚 托多罗维奇")], [#age(28)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2349*], [#delta(58)],
      [139], [#name("王添艺")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2348*], [#delta(7)],
      [140], [#name("LI Yuqi")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2346*], [#delta(7)],
      [141], [#name("雷切尔 莫雷特")], [#age(31)], [#assoc("SUI")], [#left], [#shakehand], [#attack], [*2346*], [#delta(7)],
      [142], [#name("张璇")], [#age(21)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2343*], [#delta(26)],
      [143], [#name("李多恩")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2343*], [#delta(7)],
      [144], [#name("BLASKOVA Zdena")], [#age(19)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2342*], [#delta(7)],
      [145], [#name("VIVARELLI Debora")], [#age(27)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2341*], [#delta(-32)],
      [146], [#name("VISHNIAKOVA Olga")], [#age(19)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2341*], [#delta(15)],
      [147], [#name("CHAU Wing Sze")], [#age(18)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2338*], [#delta(5)],
      [148], [#name("亚迪拉 席尔瓦")], [#age(35)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2336*], [#delta(8)],
      [149], [#name("苏珮绫")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2336*], [#delta(8)],
      [150], [#name("蒂娜 梅谢芙")], [#age(26)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2335*], [#delta(-19)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("LAURENTI Jamila")], [#age(18)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2335*], [#delta(7)],
      [152], [#name("YAMADA Jessica")], [#age(31)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2333*], [#delta(8)],
      [153], [#name("索洛米娅 布拉捷伊科")], [#age(21)], [#assoc("UKR")], [#left], [#shakehand], [#attack], [*2333*], [#delta(6)],
      [154], [#name("奥塞阿娜 古伊斯内尔")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2332*], [#delta(8)],
      [155], [#name("MALININA Natalia")], [#age(18)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2331*], [#delta(8)],
      [156], [#name("卢卡 熊原")], [#age(25)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2329*], [#delta(10)],
      [157], [#name("卡塔日娜 文格任")], [#age(19)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2329*], [#delta(-14)],
      [158], [#name("卡米耶 卢茨")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2324*], [#delta(6)],
      [159], [#name("菲利帕 贝里安德")], [#age(21)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2323*], [#delta(11)],
      [160], [#name("PATKAR Madhurika")], [#age(33)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2322*], [#delta(51)],
      [161], [#name("崔海恩")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2319*], [#delta(11)],
      [162], [#name("KLEE Sophia")], [#age(17)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2319*], [#delta(53)],
      [163], [#name("艾米丽 索尔佳")], [#age(30)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2318*], [#delta(-26)],
      [164], [#name("GAUTHIER Lucie")], [#age(20)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2314*], [#delta(42)],
      [165], [#name("萨比娜 苏尔扬")], [#age(20)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2312*], [#delta(6)],
      [166], [#name("阿林娜 斯劳京娜")], [#age(17)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2311*], [#delta(7)],
      [167], [#name("伊莎贝拉 卢普列斯库")], [#age(21)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2307*], [#delta(36)],
      [168], [#name("TOMANOVA Tamara")], [#age(26)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2307*], [#delta(9)],
      [169], [#name("黄郁雯")], [#age(24)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2305*], [#delta(5)],
      [170], [#name("阿查娜 卡马特")], [#age(20)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2303*], [#delta(-1)],
      [171], [#name("COK Isa")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2303*], [#delta(4)],
      [172], [#name("鲁塔 帕斯考斯基涅")], [#age(43)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2293*], [#delta(7)],
      [173], [#name("金加 斯特凡斯卡")], [#age(40)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2289*], [#delta(8)],
      [174], [#name("弗兰琪斯卡 施莱纳")], [#age(19)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2289*], [#delta(2)],
      [175], [#name("盖娅 蒙法尔迪尼")], [#age(19)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2287*], [#delta(8)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("伯纳德特 巴林特")], [#age(24)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2286*], [#delta(8)],
      [177], [#name("塔蒂亚娜 库库尔科娃")], [#age(20)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2286*], [#delta(-22)],
      [178], [#name("DOBREVA Polina")], [#age(28)], [#assoc("BUL")], [#right], [#shakehand], [#attack], [*2283*], [#delta(7)],
      [179], [#name("米艾 斯科娃")], [#age(34)], [#assoc("DEN")], [#right], [#shakehand], [#attack], [*2283*], [#delta(7)],
      [180], [#name("焦尔吉娅 皮科林")], [#age(24)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2283*], [#delta(0)],
      [181], [#name("CHERNYAVSKAYA Ekaterina")], [#age(24)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2283*], [#delta(23)],
      [182], [#name("西贝尔 阿尔滕卡亚")], [#age(27)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2279*], [#delta(7)],
      [183], [#name("HSU Yi-Chen")], [#age(18)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2279*], [#delta(8)],
      [184], [#name("FORT Nolwenn")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2277*], [#delta(-19)],
      [185], [#name("JAZBEC Ida")], [#age(26)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2276*], [#delta(7)],
      [186], [#name("ROY Krittwika")], [#age(26)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2275*], [#delta(1)],
      [187], [#name("梅塞德丝 纳吉瓦劳迪")], [#age(26)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2274*], [#delta(6)],
      [188], [#name("JOKIC Tijana")], [#age(20)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2272*], [#delta(6)],
      [189], [#name("MISCHEK Karoline")], [#age(22)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2272*], [#delta(6)],
      [190], [#name("PAVLOVIC Andrea")], [#age(20)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2272*], [#delta(114)],
      [191], [#name("金娜英")], [#age(15)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2267*], [#delta(6)],
      [192], [#name("弗拉达 沃罗宁娜")], [#age(16)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2266*], [#delta(6)],
      [193], [#name("奥菲昂 埃德姆")], [#age(34)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2263*], [#delta(8)],
      [194], [#name("HO Ying")], [#age(25)], [#assoc("MAS")], [#right], [#shakehand], [#attack], [*2262*], [#delta(8)],
      [195], [#name("YILMAZ Ozge")], [#age(18)], [#assoc("TUR")], [#left], [#shakehand], [#attack], [*2258*], [#delta(-17)],
      [196], [#name("吴咏琳")], [#age(17)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2258*], [#delta(9)],
      [197], [#name("YOVKOVA Maria")], [#age(21)], [#assoc("BUL")], [#right], [#shakehand], [#attack], [*2257*], [#delta(27)],
      [198], [#name("埃杰 哈拉奇")], [#age(18)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2256*], [#delta(-8)],
      [199], [#name("SHINOHARA Yura")], [#age(14)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2256*], [#delta(9)],
      [200], [#name("CAI Fong-En")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2255*], [#delta(9)],
    )
  )
