#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("陈梦")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3104*], [#delta(1)],
      [2], [#name("王曼昱")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3089*], [#delta(-1)],
      [3], [#name("孙颖莎")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3088*], [#delta(0)],
      [4], [#name("王艺迪")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3012*], [#delta(0)],
      [5], [#name("刘诗雯")], [#age(31)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2950*], [#delta(0)],
      [6], [#name("陈幸同")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2895*], [#delta(0)],
      [7], [#name("钱天一")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2864*], [#delta(0)],
      [8], [#name("早田希娜")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2847*], [#delta(0)],
      [9], [#name("杜凯琹")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2832*], [#delta(15)],
      [10], [#name("张瑞")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2829*], [#delta(-1)],
      [11], [#name("伊藤美诚")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2821*], [#delta(-1)],
      [12], [#name("申裕斌")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2801*], [#delta(0)],
      [13], [#name("刘炜珊")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2795*], [#delta(0)],
      [14], [#name("桥本帆乃香")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2787*], [#delta(0)],
      [15], [#name("石川佳纯")], [#age(29)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2771*], [#delta(0)],
      [16], [#name("平野美宇")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2759*], [#delta(-5)],
      [17], [#name("徐孝元")], [#age(35)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2752*], [#delta(-1)],
      [18], [#name("安藤南")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2745*], [#delta(-1)],
      [19], [#name("韩莹")], [#age(39)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2733*], [#delta(-1)],
      [20], [#name("蒯曼")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2728*], [#delta(17)],
      [21], [#name("范思琦")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2726*], [#delta(-1)],
      [22], [#name("何卓佳")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2724*], [#delta(-1)],
      [23], [#name("石洵瑶")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2718*], [#delta(-1)],
      [24], [#name("加藤美优")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2712*], [#delta(-1)],
      [25], [#name("芝田沙季")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2711*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("袁嘉楠")], [#age(37)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2689*], [#delta(1)],
      [27], [#name("冯天薇")], [#age(36)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2689*], [#delta(13)],
      [28], [#name("长崎美柚")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2687*], [#delta(0)],
      [29], [#name("杨晓欣")], [#age(34)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2685*], [#delta(0)],
      [30], [#name("木原美悠")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2685*], [#delta(-4)],
      [31], [#name("佐藤瞳")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2681*], [#delta(0)],
      [32], [#name("田志希")], [#age(30)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2675*], [#delta(-13)],
      [33], [#name("倪夏莲")], [#age(59)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2675*], [#delta(-3)],
      [34], [#name("梁夏银")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2671*], [#delta(-2)],
      [35], [#name("伯纳黛特 斯佐科斯")], [#age(27)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2664*], [#delta(-2)],
      [36], [#name("小盐遥菜")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2663*], [#delta(5)],
      [37], [#name("金河英")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2662*], [#delta(-3)],
      [38], [#name("刘佳")], [#age(40)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2660*], [#delta(-3)],
      [39], [#name("琳达 伯格斯特罗姆")], [#age(27)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2658*], [#delta(-3)],
      [40], [#name("朱成竹")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2640*], [#delta(-1)],
      [41], [#name("陈熠")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2639*], [#delta(-3)],
      [42], [#name("曾尖")], [#age(26)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2636*], [#delta(0)],
      [43], [#name("吴洋晨")], [#age(20)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2634*], [#delta(9)],
      [44], [#name("崔孝珠")], [#age(24)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2632*], [#delta(-1)],
      [45], [#name("单晓娜")], [#age(39)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2625*], [#delta(-1)],
      [46], [#name("傅玉")], [#age(44)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2623*], [#delta(0)],
      [47], [#name("SOO Wai Yam")], [#age(24)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2623*], [#delta(0)],
      [48], [#name("苏萨西尼 萨维塔布特")], [#age(28)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2622*], [#delta(0)],
      [49], [#name("阿德里安娜 迪亚兹")], [#age(22)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2618*], [#delta(0)],
      [50], [#name("森樱")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2614*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("PESOTSKA Margaryta")], [#age(31)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2612*], [#delta(0)],
      [52], [#name("郑怡静")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2610*], [#delta(-7)],
      [53], [#name("陈思羽")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2581*], [#delta(1)],
      [54], [#name("张安")], [#age(26)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2563*], [#delta(1)],
      [55], [#name("ABRAAMIAN Elizabet")], [#age(19)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2562*], [#delta(2)],
      [56], [#name("王 艾米")], [#age(20)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2558*], [#delta(-3)],
      [57], [#name("刘杨子")], [#age(20)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2557*], [#delta(19)],
      [58], [#name("DE NUTTE Sarah")], [#age(30)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2555*], [#delta(-2)],
      [59], [#name("LAY Jian Fang")], [#age(49)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2545*], [#delta(-1)],
      [60], [#name("李恩惠")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2545*], [#delta(-1)],
      [61], [#name("BALAZOVA Barbora")], [#age(30)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2539*], [#delta(-1)],
      [62], [#name("李时温")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2537*], [#delta(-1)],
      [63], [#name("YOO Eunchong")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2533*], [#delta(-1)],
      [64], [#name("NG Wing Nam")], [#age(30)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2530*], [#delta(-1)],
      [65], [#name("高桥 布鲁娜")], [#age(22)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2526*], [#delta(-1)],
      [66], [#name("LIN Ye")], [#age(26)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2520*], [#delta(0)],
      [67], [#name("佩特丽莎 索尔佳")], [#age(28)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2519*], [#delta(0)],
      [68], [#name("李皓晴")], [#age(30)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2514*], [#delta(0)],
      [69], [#name("DIACONU Adina")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2511*], [#delta(0)],
      [70], [#name("妮娜 米特兰姆")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2508*], [#delta(0)],
      [71], [#name("MATELOVA Hana")], [#age(32)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2508*], [#delta(0)],
      [72], [#name("玛妮卡 巴特拉")], [#age(27)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2503*], [#delta(1)],
      [73], [#name("萨比亚 温特")], [#age(30)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2503*], [#delta(-8)],
      [74], [#name("LIU Hsing-Yin")], [#age(35)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2500*], [#delta(1)],
      [75], [#name("索菲亚 波尔卡诺娃")], [#age(28)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2487*], [#delta(-3)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("普利西卡 帕瓦德")], [#age(18)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2485*], [#delta(-2)],
      [77], [#name("KIM Byeolnim")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2480*], [#delta(1)],
      [78], [#name("蒂娜 梅谢芙")], [#age(28)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2477*], [#delta(2)],
      [79], [#name("CHENG Hsien-Tzu")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2476*], [#delta(2)],
      [80], [#name("杨蕙菁")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2472*], [#delta(2)],
      [81], [#name("奥拉万 帕拉南")], [#age(25)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2470*], [#delta(2)],
      [82], [#name("DRAGOMAN Andreea")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2466*], [#delta(2)],
      [83], [#name("ZAHARIA Elena")], [#age(18)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2462*], [#delta(2)],
      [84], [#name("克里斯蒂娜 卡尔伯格")], [#age(22)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2460*], [#delta(2)],
      [85], [#name("邵杰妮")], [#age(28)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2458*], [#delta(2)],
      [86], [#name("SUNG Rachel")], [#age(18)], [#assoc("USA")], [#left], [#shakehand], [#attack], [*2458*], [#delta(33)],
      [87], [#name("BAJOR Natalia")], [#age(25)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2454*], [#delta(1)],
      [88], [#name("BILENKO Tetyana")], [#age(39)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2443*], [#delta(3)],
      [89], [#name("张本美和")], [#age(14)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2441*], [#delta(42)],
      [90], [#name("CIOBANU Irina")], [#age(27)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2435*], [#delta(3)],
      [91], [#name("WEGRZYN Katarzyna")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2434*], [#delta(3)],
      [92], [#name("TRIGOLOS Daria")], [#age(23)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2432*], [#delta(-3)],
      [93], [#name("布里特 伊尔兰德")], [#age(28)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2431*], [#delta(2)],
      [94], [#name("张墨")], [#age(33)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2426*], [#delta(3)],
      [95], [#name("VORONINA Vlada")], [#age(18)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2425*], [#delta(1)],
      [96], [#name("DODEAN Daniela")], [#age(34)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2425*], [#delta(2)],
      [97], [#name("肖瑶茜")], [#age(28)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2423*], [#delta(2)],
      [98], [#name("安妮特 考夫曼")], [#age(16)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2422*], [#delta(-21)],
      [99], [#name("李昱谆")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2421*], [#delta(1)],
      [100], [#name("MALOBABIC Ivana")], [#age(42)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2421*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("LUTZ Camille")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2420*], [#delta(-9)],
      [102], [#name("苏蒂尔塔 穆克吉")], [#age(27)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2419*], [#delta(1)],
      [103], [#name("PICCOLIN Giorgia")], [#age(26)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2418*], [#delta(1)],
      [104], [#name("LENG Yutong")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2417*], [#delta(1)],
      [105], [#name("金娜英")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2415*], [#delta(1)],
      [106], [#name("NOSKOVA Yana")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2413*], [#delta(-27)],
      [107], [#name("MANTZ Chantal")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2410*], [#delta(11)],
      [108], [#name("TODOROVIC Andrea")], [#age(30)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2409*], [#delta(-1)],
      [109], [#name("斯丽贾 阿库拉")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2409*], [#delta(-1)],
      [110], [#name("艾希卡 穆克吉")], [#age(25)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2407*], [#delta(-1)],
      [111], [#name("齐菲")], [#age(22)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2404*], [#delta(-1)],
      [112], [#name("KAMATH Archana")], [#age(22)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2401*], [#delta(-22)],
      [113], [#name("伊丽莎白 萨玛拉")], [#age(33)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2400*], [#delta(-2)],
      [114], [#name("SAWETTABUT Jinnipa")], [#age(22)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2389*], [#delta(-2)],
      [115], [#name("MIKHAILOVA Polina")], [#age(36)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2388*], [#delta(-2)],
      [116], [#name("PLAIAN Tania")], [#age(21)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2388*], [#delta(-2)],
      [117], [#name("MEN Shuohan")], [#age(22)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2388*], [NEW],
      [118], [#name("LAM Yee Lok")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2386*], [#delta(-3)],
      [119], [#name("CHITALE Diya")], [#age(19)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2384*], [#delta(-17)],
      [120], [#name("MORET Rachel")], [#age(33)], [#assoc("SUI")], [#left], [#shakehand], [#attack], [*2383*], [#delta(-4)],
      [121], [#name("LI Ching Wan")], [#age(28)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2382*], [#delta(-4)],
      [122], [#name("BRATEYKO Solomiya")], [#age(23)], [#assoc("UKR")], [#left], [#shakehand], [#attack], [*2372*], [#delta(16)],
      [123], [#name("ARAPOVIC Hana")], [#age(18)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2370*], [#delta(-3)],
      [124], [#name("HO Tin-Tin")], [#age(24)], [#assoc("GBR")], [#right], [#penhold], [#attack], [*2368*], [#delta(-3)],
      [125], [#name("CHASSELIN Pauline")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2361*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("LUTZ Charlotte")], [#age(17)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2359*], [#delta(-3)],
      [127], [#name("SU Pei-Ling")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2356*], [#delta(0)],
      [128], [#name("DOBREVA Polina")], [#age(30)], [#assoc("BUL")], [#right], [#shakehand], [#attack], [*2355*], [#delta(0)],
      [129], [#name("汉娜 高达")], [#age(15)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2355*], [#delta(-3)],
      [130], [#name("RYU Hanna")], [#age(20)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2354*], [#delta(-1)],
      [131], [#name("ZARIF Audrey")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2353*], [#delta(-1)],
      [132], [#name("DYMYTRENKO Anastasiya")], [#age(20)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2349*], [#delta(-10)],
      [133], [#name("王添艺")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2348*], [#delta(-1)],
      [134], [#name("LI Yuqi")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2346*], [#delta(-1)],
      [135], [#name("LEE Daeun")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2343*], [#delta(-1)],
      [136], [#name("SINGEORZAN Ioana")], [#age(18)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2343*], [#delta(41)],
      [137], [#name("LABOSOVA Ema")], [#age(21)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2339*], [#delta(6)],
      [138], [#name("CHAU Wing Sze")], [#age(20)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2338*], [#delta(-2)],
      [139], [#name("GUISNEL Oceane")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2337*], [#delta(-2)],
      [140], [#name("LOEUILLETTE Stephanie")], [#age(30)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2334*], [#delta(-1)],
      [141], [#name("KUMAHARA Luca")], [#age(27)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2333*], [#delta(-1)],
      [142], [#name("KLEE Sophia")], [#age(19)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2328*], [#delta(12)],
      [143], [#name("HAPONOVA Hanna")], [#age(37)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2325*], [#delta(-2)],
      [144], [#name("TOMANOVSKA Katerina")], [#age(27)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2325*], [#delta(-2)],
      [145], [#name("HURSEY Anna")], [#age(16)], [#assoc("WAL")], [#right], [#shakehand], [#attack], [*2325*], [#delta(-10)],
      [146], [#name("BALINT Bernadett")], [#age(26)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2322*], [#delta(39)],
      [147], [#name("CHOI Haeeun")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2319*], [#delta(-3)],
      [148], [#name("ZHOU Jingyi")], [#age(17)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2317*], [#delta(-2)],
      [149], [#name("EDEM Offiong")], [#age(36)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2316*], [#delta(-2)],
      [150], [#name("PATKAR Madhurika")], [#age(35)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2315*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("SCHREINER Franziska")], [#age(21)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2312*], [#delta(-27)],
      [152], [#name("TOLIOU Aikaterini")], [#age(27)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2311*], [#delta(-3)],
      [153], [#name("JEGER Mateja")], [#age(27)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2311*], [#delta(-3)],
      [154], [#name("MIGOT Marie")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2309*], [#delta(-2)],
      [155], [#name("SOLJA Amelie")], [#age(32)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2308*], [#delta(19)],
      [156], [#name("HUANG Yu-Wen")], [#age(26)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2307*], [#delta(-3)],
      [157], [#name("GHORPADE Yashaswini")], [#age(18)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2302*], [#delta(2)],
      [158], [#name("ALTINKAYA Sibel")], [#age(29)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2302*], [#delta(-3)],
      [159], [#name("JEE Minhyung")], [#age(35)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2301*], [#delta(-3)],
      [160], [#name("万远")], [#age(25)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2299*], [#delta(0)],
      [161], [#name("SLAUTINA Arina")], [#age(19)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2298*], [#delta(-4)],
      [162], [#name("MADARASZ Dora")], [#age(29)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2297*], [#delta(-4)],
      [163], [#name("MOSTAFAVI Leili")], [#age(22)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2293*], [#delta(-12)],
      [164], [#name("SURJAN Sabina")], [#age(22)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2292*], [#delta(-3)],
      [165], [#name("SER Lin Qian")], [#age(16)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2292*], [#delta(61)],
      [166], [#name("STEFANSKA Kinga")], [#age(42)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2289*], [#delta(-4)],
      [167], [#name("ARLIA Nicole")], [#age(17)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2288*], [#delta(-4)],
      [168], [#name("YAMADA Jessica")], [#age(33)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2287*], [#delta(-4)],
      [169], [#name("乔治娜 波塔")], [#age(37)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2287*], [#delta(-4)],
      [170], [#name("FORT Nolwenn")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2286*], [#delta(-4)],
      [171], [#name("ZHANG Sofia-Xuan")], [#age(23)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2285*], [#delta(-4)],
      [172], [#name("PAVLOVIC Andrea")], [#age(22)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2282*], [#delta(-3)],
      [173], [#name("CAREY Charlotte")], [#age(26)], [#assoc("GBR")], [#left], [#shakehand], [#attack], [*2280*], [#delta(54)],
      [174], [#name("BLASKOVA Zdena")], [#age(21)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2279*], [#delta(-3)],
      [175], [#name("WEGRZYN Anna")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2278*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("KISEL Darya")], [#age(20)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2277*], [#delta(-1)],
      [177], [#name("MITROFAN Luciana")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2272*], [#delta(6)],
      [178], [#name("BERGAND Filippa")], [#age(23)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2271*], [#delta(-2)],
      [179], [#name("LUPULESKU Izabela")], [#age(23)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2270*], [#delta(-7)],
      [180], [#name("IMRE Leila")], [#age(25)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2270*], [#delta(29)],
      [181], [#name("SHAHSAVARI Neda")], [#age(36)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2268*], [#delta(-3)],
      [182], [#name("SILVA Yadira")], [#age(37)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2266*], [#delta(-3)],
      [183], [#name("MISCHEK Karoline")], [#age(24)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2262*], [#delta(-3)],
      [184], [#name("SELVAKUMAR Selena")], [#age(22)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2262*], [#delta(-3)],
      [185], [#name("HO Ying")], [#age(27)], [#assoc("MAS")], [#right], [#shakehand], [#attack], [*2262*], [#delta(-3)],
      [186], [#name("GOI Rui Xuan")], [#age(21)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2261*], [#delta(-2)],
      [187], [#name("PARTYKA Natalia")], [#age(33)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2260*], [#delta(0)],
      [188], [#name("VEGA Paulina")], [#age(38)], [#assoc("CHI")], [#left], [#shakehand], [#attack], [*2257*], [#delta(2)],
      [189], [#name("SHINOHARA Yura")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2256*], [#delta(3)],
      [190], [#name("LEE Yeonhui")], [#age(18)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2255*], [#delta(4)],
      [191], [#name("SCHOLZ Vivien")], [#age(25)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2255*], [#delta(79)],
      [192], [#name("HARTBRICH Leonie")], [#age(23)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2254*], [#delta(-6)],
      [193], [#name("SEVCIKOVA Marketa")], [#age(24)], [#assoc("CZE")], [#right], [#shakehand], [#defense], [*2253*], [#delta(2)],
      [194], [#name("RILISKYTE Kornelija")], [#age(19)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2251*], [#delta(-26)],
      [195], [#name("NAGYVARADI Mercedes")], [#age(28)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2250*], [#delta(2)],
      [196], [#name("FONSECA Daniela")], [#age(20)], [#assoc("CUB")], [#left], [#shakehand], [#attack], [*2250*], [#delta(8)],
      [197], [#name("GHOSH Swastika")], [#age(19)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2249*], [#delta(-6)],
      [198], [#name("ALHODABY Mariam")], [#age(22)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2246*], [#delta(2)],
      [199], [#name("MUSKANTOR Rebecca")], [#age(19)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2245*], [#delta(-1)],
      [200], [#name("COK Isa")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2245*], [#delta(1)],
    )
  )
