#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("陈梦")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3115*], [#delta(1)],
      [2], [#name("孙颖莎")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3097*], [#delta(2)],
      [3], [#name("王曼昱")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3053*], [#delta(-2)],
      [4], [#name("陈幸同")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2957*], [#delta(2)],
      [5], [#name("王艺迪")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2949*], [#delta(-2)],
      [6], [#name("早田希娜")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2930*], [#delta(-1)],
      [7], [#name("伊藤美诚")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2856*], [#delta(0)],
      [8], [#name("何卓佳")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2834*], [#delta(0)],
      [9], [#name("桥本帆乃香")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2825*], [#delta(0)],
      [10], [#name("小盐遥菜")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2822*], [#delta(0)],
      [11], [#name("张瑞")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2810*], [#delta(0)],
      [12], [#name("范思琦")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2809*], [#delta(0)],
      [13], [#name("袁嘉楠")], [#age(37)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2795*], [#delta(25)],
      [14], [#name("朱成竹")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2775*], [#delta(42)],
      [15], [#name("平野美宇")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2774*], [#delta(-2)],
      [16], [#name("曾尖")], [#age(26)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2767*], [#delta(33)],
      [17], [#name("石川佳纯")], [#age(29)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2767*], [#delta(-1)],
      [18], [#name("钱天一")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2766*], [#delta(-4)],
      [19], [#name("伯纳黛特 斯佐科斯")], [#age(27)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2765*], [#delta(14)],
      [20], [#name("蒯曼")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2751*], [#delta(-3)],
      [21], [#name("安藤南")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2745*], [#delta(-3)],
      [22], [#name("长崎美柚")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2745*], [#delta(-2)],
      [23], [#name("木原美悠")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2724*], [#delta(-8)],
      [24], [#name("芝田沙季")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2710*], [#delta(-3)],
      [25], [#name("徐孝元")], [#age(35)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2706*], [#delta(-3)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("张本美和")], [#age(14)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2703*], [#delta(-3)],
      [27], [#name("刘炜珊")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2692*], [#delta(-1)],
      [28], [#name("单晓娜")], [#age(39)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2684*], [#delta(2)],
      [29], [#name("韩莹")], [#age(39)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2681*], [#delta(-5)],
      [30], [#name("索菲亚 波尔卡诺娃")], [#age(28)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2678*], [#delta(-3)],
      [31], [#name("李恩惠")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2671*], [#delta(-3)],
      [32], [#name("齐菲")], [#age(22)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2667*], [#delta(-3)],
      [33], [#name("陈思羽")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2665*], [#delta(12)],
      [34], [#name("傅玉")], [#age(44)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2663*], [#delta(7)],
      [35], [#name("琳达 伯格斯特隆")], [#age(27)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2661*], [#delta(42)],
      [36], [#name("刘佳")], [#age(40)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2660*], [#delta(-5)],
      [37], [#name("佐藤瞳")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2660*], [#delta(2)],
      [38], [#name("杨晓欣")], [#age(34)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2660*], [#delta(-4)],
      [39], [#name("郑怡静")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2649*], [#delta(-7)],
      [40], [#name("陈熠")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2638*], [#delta(-5)],
      [41], [#name("崔孝珠")], [#age(24)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2626*], [#delta(-1)],
      [42], [#name("苏萨西尼 萨维塔布特")], [#age(28)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2617*], [#delta(1)],
      [43], [#name("石洵瑶")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2616*], [#delta(1)],
      [44], [#name("PESOTSKA Margaryta")], [#age(31)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2612*], [#delta(2)],
      [45], [#name("森樱")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2610*], [#delta(2)],
      [46], [#name("SOO Wai Yam")], [#age(24)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2607*], [#delta(28)],
      [47], [#name("斯丽贾 阿库拉")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2604*], [#delta(62)],
      [48], [#name("田志希")], [#age(30)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2603*], [#delta(-6)],
      [49], [#name("申裕斌")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2598*], [#delta(-1)],
      [50], [#name("李昱谆")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2584*], [#delta(25)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("梁夏银")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2582*], [#delta(0)],
      [52], [#name("张安")], [#age(26)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2581*], [#delta(0)],
      [53], [#name("吴洋晨")], [#age(20)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2579*], [#delta(0)],
      [54], [#name("倪夏莲")], [#age(59)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2578*], [#delta(-4)],
      [55], [#name("阿德里安娜 迪亚兹")], [#age(22)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2577*], [#delta(2)],
      [56], [#name("金河英")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2574*], [#delta(-20)],
      [57], [#name("徐奕")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2561*], [#delta(-3)],
      [58], [#name("朱芊曦")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2561*], [#delta(-3)],
      [59], [#name("杜凯琹")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2546*], [#delta(-40)],
      [60], [#name("刘杨子")], [#age(20)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2545*], [#delta(1)],
      [61], [#name("覃予萱")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2543*], [#delta(1)],
      [62], [#name("BALAZOVA Barbora")], [#age(30)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2543*], [#delta(25)],
      [63], [#name("杨蕙菁")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2541*], [#delta(0)],
      [64], [#name("李时温")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2540*], [#delta(1)],
      [65], [#name("王 艾米")], [#age(20)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2538*], [#delta(-1)],
      [66], [#name("艾希卡 穆克吉")], [#age(25)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2533*], [#delta(0)],
      [67], [#name("韩菲儿")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2530*], [#delta(0)],
      [68], [#name("DRAGOMAN Andreea")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2526*], [#delta(2)],
      [69], [#name("笹尾明日香")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2522*], [#delta(3)],
      [70], [#name("ZHOU Jingyi")], [#age(17)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2512*], [#delta(52)],
      [71], [#name("妮娜 米特兰姆")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2509*], [#delta(-46)],
      [72], [#name("DIACONU Adina")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2507*], [#delta(-1)],
      [73], [#name("普利西卡 帕瓦德")], [#age(18)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2497*], [#delta(16)],
      [74], [#name("LAY Jian Fang")], [#age(49)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2496*], [#delta(4)],
      [75], [#name("奥拉万 帕拉南")], [#age(25)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2494*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("金娜英")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2494*], [#delta(4)],
      [77], [#name("LIU Hsing-Yin")], [#age(35)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2489*], [#delta(4)],
      [78], [#name("MADARASZ Dora")], [#age(29)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2484*], [#delta(32)],
      [79], [#name("布里特 伊尔兰德")], [#age(28)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2483*], [#delta(3)],
      [80], [#name("CHASSELIN Pauline")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2483*], [#delta(4)],
      [81], [#name("CIOBANU Irina")], [#age(27)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2482*], [#delta(2)],
      [82], [#name("PICCOLIN Giorgia")], [#age(26)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2479*], [#delta(20)],
      [83], [#name("玛妮卡 巴特拉")], [#age(27)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2468*], [#delta(-46)],
      [84], [#name("CHITALE Diya")], [#age(19)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2464*], [#delta(63)],
      [85], [#name("萨比亚 温特")], [#age(30)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2463*], [#delta(-27)],
      [86], [#name("邵杰妮")], [#age(28)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2457*], [#delta(-27)],
      [87], [#name("汉娜 马特洛娃")], [#age(32)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2454*], [#delta(30)],
      [88], [#name("HUANG Yi-Hua")], [#age(38)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2446*], [#delta(-9)],
      [89], [#name("KIM Byeolnim")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2445*], [#delta(2)],
      [90], [#name("赤江夏星")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2443*], [#delta(2)],
      [91], [#name("克里斯蒂娜 卡尔伯格")], [#age(22)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2441*], [#delta(2)],
      [92], [#name("BAJOR Natalia")], [#age(25)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2440*], [#delta(2)],
      [93], [#name("SU Pei-Ling")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2438*], [#delta(2)],
      [94], [#name("张墨")], [#age(33)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2435*], [#delta(2)],
      [95], [#name("JEE Minhyung")], [#age(35)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2435*], [#delta(2)],
      [96], [#name("ZAHARIA Elena")], [#age(18)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2433*], [#delta(15)],
      [97], [#name("HUANG Yu-Jie")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-9)],
      [98], [#name("SUNG Rachel")], [#age(18)], [#assoc("USA")], [#left], [#shakehand], [#attack], [*2431*], [#delta(0)],
      [99], [#name("高桥 布鲁娜")], [#age(22)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2430*], [#delta(-30)],
      [100], [#name("MALOBABIC Ivana")], [#age(42)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2430*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("BLASKOVA Zdena")], [#age(21)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2430*], [#delta(-1)],
      [102], [#name("纵歌曼")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2424*], [#delta(-1)],
      [103], [#name("MANTZ Chantal")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2419*], [#delta(0)],
      [104], [#name("ZANG Xiaotong")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2419*], [#delta(0)],
      [105], [#name("HO Tin-Tin")], [#age(24)], [#assoc("ENG")], [#right], [#penhold], [#attack], [*2413*], [#delta(0)],
      [106], [#name("王添艺")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2412*], [#delta(0)],
      [107], [#name("YOON Hyobin")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2410*], [#delta(-47)],
      [108], [#name("伊丽莎白 萨玛拉")], [#age(33)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2409*], [#delta(-35)],
      [109], [#name("安妮特 考夫曼")], [#age(16)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2409*], [#delta(-2)],
      [110], [#name("WEGRZYN Anna")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2403*], [#delta(8)],
      [111], [#name("万远")], [#age(25)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2401*], [#delta(1)],
      [112], [#name("SURJAN Sabina")], [#age(22)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2400*], [#delta(1)],
      [113], [#name("LI Ching Wan")], [#age(28)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2399*], [#delta(1)],
      [114], [#name("DE NUTTE Sarah")], [#age(30)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2396*], [#delta(-24)],
      [115], [#name("CHENG Hsien-Tzu")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2392*], [#delta(1)],
      [116], [#name("ARAPOVIC Hana")], [#age(18)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2391*], [#delta(27)],
      [117], [#name("LABOSOVA Ema")], [#age(21)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2384*], [#delta(66)],
      [118], [#name("肖瑶茜")], [#age(28)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2379*], [#delta(2)],
      [119], [#name("SCHREINER Franziska")], [#age(21)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2378*], [#delta(2)],
      [120], [#name("WONG Xin Ru")], [#age(21)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2375*], [#delta(94)],
      [121], [#name("LAM Yee Lok")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2373*], [#delta(2)],
      [122], [#name("蒂娜 梅谢芙")], [#age(28)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2371*], [#delta(-36)],
      [123], [#name("GHORPADE Yashaswini")], [#age(18)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2369*], [#delta(1)],
      [124], [#name("MEN Shuohan")], [#age(22)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2367*], [#delta(1)],
      [125], [#name("RYU Hanna")], [#age(20)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2366*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("MIGOT Marie")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2364*], [#delta(1)],
      [127], [#name("苏蒂尔塔 穆克吉")], [#age(27)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2364*], [#delta(1)],
      [128], [#name("KHETKHUAN Tamolwan")], [#age(25)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2361*], [#delta(2)],
      [129], [#name("李多恩")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2359*], [#delta(7)],
      [130], [#name("叶伊恬")], [#age(15)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2358*], [#delta(29)],
      [131], [#name("PLAIAN Tania")], [#age(21)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2358*], [#delta(0)],
      [132], [#name("李多恩")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2357*], [#delta(0)],
      [133], [#name("SINGEORZAN Ioana")], [#age(18)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2357*], [#delta(28)],
      [134], [#name("STEFANOVA Nikoleta")], [#age(38)], [#assoc("ITA")], [#left], [#shakehand], [#attack], [*2357*], [#delta(-1)],
      [135], [#name("GUISNEL Oceane")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2357*], [#delta(-1)],
      [136], [#name("KAMATH Archana")], [#age(22)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2357*], [#delta(-1)],
      [137], [#name("CHENG Pusyuan")], [#age(16)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2352*], [#delta(1)],
      [138], [#name("KUMAHARA Luca")], [#age(27)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2351*], [#delta(13)],
      [139], [#name("TODOROVIC Andrea")], [#age(30)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2351*], [#delta(0)],
      [140], [#name("DYMYTRENKO Anastasiya")], [#age(20)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2350*], [#delta(0)],
      [141], [#name("JEGER Mateja")], [#age(27)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2349*], [#delta(0)],
      [142], [#name("LUPULESKU Izabela")], [#age(23)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2349*], [#delta(0)],
      [143], [#name("VIGNJEVIC Dragana")], [#age(23)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2344*], [#delta(1)],
      [144], [#name("乔治娜 波塔")], [#age(37)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2343*], [#delta(1)],
      [145], [#name("MISCHEK Karoline")], [#age(24)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2343*], [#delta(1)],
      [146], [#name("李皓晴")], [#age(30)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2337*], [#delta(-78)],
      [147], [#name("LOEUILLETTE Stephanie")], [#age(30)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2334*], [#delta(1)],
      [148], [#name("SAWETTABUT Jinnipa")], [#age(22)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2329*], [#delta(-63)],
      [149], [#name("TOLIOU Aikaterini")], [#age(27)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2329*], [#delta(0)],
      [150], [#name("HAPONOVA Hanna")], [#age(37)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2325*], [#delta(2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("LUTZ Camille")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2321*], [#delta(2)],
      [152], [#name("ZHANG Sofia-Xuan")], [#age(23)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2320*], [#delta(2)],
      [153], [#name("NAGYVARADI Mercedes")], [#age(28)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2318*], [#delta(2)],
      [154], [#name("SOLJA Amelie")], [#age(32)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2315*], [#delta(2)],
      [155], [#name("TSAI Yun-En")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2312*], [#delta(46)],
      [156], [#name("WEGRZYN Katarzyna")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2312*], [#delta(-41)],
      [157], [#name("BRATEYKO Solomiya")], [#age(23)], [#assoc("UKR")], [#left], [#shakehand], [#attack], [*2312*], [#delta(0)],
      [158], [#name("SILVA Yadira")], [#age(37)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2311*], [#delta(0)],
      [159], [#name("ZARIF Audrey")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2308*], [#delta(1)],
      [160], [#name("朴佳贤")], [#age(15)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2302*], [#delta(43)],
      [161], [#name("CHANG Li Sian Alice")], [#age(22)], [#assoc("MAS")], [#right], [#shakehand], [#defense], [*2302*], [#delta(30)],
      [162], [#name("HUANG Yu-Wen")], [#age(26)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2296*], [#delta(1)],
      [163], [#name("BERGAND Filippa")], [#age(23)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2296*], [#delta(47)],
      [164], [#name("EDEM Offiong")], [#age(36)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2292*], [#delta(0)],
      [165], [#name("BALINT Bernadett")], [#age(26)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2291*], [#delta(0)],
      [166], [#name("小盐悠菜")], [#age(14)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2291*], [#delta(0)],
      [167], [#name("KUKULKOVA Tatiana")], [#age(22)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2291*], [#delta(-59)],
      [168], [#name("安娜 赫西")], [#age(16)], [#assoc("WAL")], [#right], [#shakehand], [#attack], [*2290*], [#delta(-6)],
      [169], [#name("朱思冰")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2287*], [#delta(-2)],
      [170], [#name("YAMADA Jessica")], [#age(33)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2287*], [#delta(-2)],
      [171], [#name("AUEAWIRIYAYOTHIN Wanwisa")], [#age(18)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2285*], [#delta(113)],
      [172], [#name("GONDERINGER Tessy")], [#age(29)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2282*], [#delta(122)],
      [173], [#name("FONSECA Daniela")], [#age(20)], [#assoc("CUB")], [#left], [#shakehand], [#attack], [*2281*], [#delta(-3)],
      [174], [#name("ALTINKAYA Sibel")], [#age(29)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2280*], [#delta(-3)],
      [175], [#name("吴咏琳")], [#age(19)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2277*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("CAREY Charlotte")], [#age(26)], [#assoc("WAL")], [#left], [#shakehand], [#attack], [*2276*], [#delta(-4)],
      [177], [#name("BRZYSKA Anna")], [#age(17)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2276*], [#delta(-8)],
      [178], [#name("CHOI Haeeun")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2272*], [#delta(-4)],
      [179], [#name("KLEE Sophia")], [#age(19)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2272*], [#delta(-4)],
      [180], [#name("LUTZ Charlotte")], [#age(17)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2271*], [#delta(-43)],
      [181], [#name("CHAU Wing Sze")], [#age(20)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2268*], [#delta(-4)],
      [182], [#name("DOBREVA Polina")], [#age(30)], [#assoc("BUL")], [#right], [#shakehand], [#attack], [*2268*], [#delta(-4)],
      [183], [#name("汉娜 高达")], [#age(15)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2266*], [#delta(-64)],
      [184], [#name("KIM Seongjin")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2264*], [#delta(-4)],
      [185], [#name("TOMANOVSKA Katerina")], [#age(27)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2263*], [#delta(-35)],
      [186], [#name("GHOSH Swastika")], [#age(19)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2262*], [#delta(-5)],
      [187], [#name("WANG Yiduo")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2262*], [#delta(-5)],
      [188], [#name("CHEN Chi-Shiuan")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2255*], [#delta(-4)],
      [189], [#name("WIELGOS Zuzanna")], [#age(17)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2254*], [#delta(-4)],
      [190], [#name("AOKI Sachi")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2253*], [#delta(-4)],
      [191], [#name("TENNISON Reeth")], [#age(27)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2253*], [#delta(-4)],
      [192], [#name("WROBEL Wiktoria")], [#age(16)], [#assoc("POL")], [#right], [#shakehand], [#defense], [*2253*], [#delta(-4)],
      [193], [#name("面手凛")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2252*], [#delta(-4)],
      [194], [#name("OSHONAIKE Olufunke")], [#age(47)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2249*], [#delta(-4)],
      [195], [#name("TOFANT Ana")], [#age(23)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2247*], [#delta(-3)],
      [196], [#name("SER Lin Qian")], [#age(16)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2247*], [#delta(-3)],
      [197], [#name("STEFANSKA Kinga")], [#age(42)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2243*], [#delta(-1)],
      [198], [#name("LOVET Idalys")], [#age(25)], [#assoc("CUB")], [#right], [#shakehand], [#attack], [*2243*], [#delta(-1)],
      [199], [#name("LYNE Karen")], [#age(20)], [#assoc("MAS")], [#left], [#shakehand], [#attack], [*2241*], [NEW],
      [200], [#name("GRIESEL Mia")], [#age(16)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2241*], [#delta(-6)],
    )
  )
