#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("马龙")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3047*], [#delta(0)],
      [2], [#name("许昕")], [#age(22)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*3046*], [#delta(1)],
      [3], [#name("张继科")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3020*], [#delta(-1)],
      [4], [#name("蒂姆 波尔")], [#age(31)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2960*], [#delta(0)],
      [5], [#name("王皓")], [#age(29)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2909*], [#delta(0)],
      [6], [#name("郝帅")], [#age(29)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2901*], [#delta(0)],
      [7], [#name("王励勤")], [#age(34)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2853*], [#delta(0)],
      [8], [#name("陈玘")], [#age(28)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2841*], [#delta(1)],
      [9], [#name("马琳")], [#age(32)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2820*], [#delta(-1)],
      [10], [#name("闫安")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2799*], [#delta(1)],
      [11], [#name("迪米特里 奥恰洛夫")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2773*], [#delta(1)],
      [12], [#name("丹羽孝希")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2763*], [#delta(-2)],
      [13], [#name("庄智渊")], [#age(31)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2748*], [#delta(1)],
      [14], [#name("江天一")], [#age(24)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2733*], [#delta(6)],
      [15], [#name("水谷隼")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2725*], [#delta(-2)],
      [16], [#name("米凯尔 梅兹")], [#age(31)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2724*], [#delta(-1)],
      [17], [#name("弗拉基米尔 萨姆索诺夫")], [#age(36)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2720*], [#delta(0)],
      [18], [#name("李廷佑")], [#age(28)], [#assoc("KOR")], [#left], [#penhold], [#attack], [*2710*], [#delta(0)],
      [19], [#name("吴尚垠")], [#age(35)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2709*], [#delta(13)],
      [20], [#name("博扬 托基奇")], [#age(31)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2709*], [#delta(-1)],
      [21], [#name("罗伯特 加尔多斯")], [#age(33)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2703*], [#delta(0)],
      [22], [#name("巴斯蒂安 斯特格")], [#age(31)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2696*], [#delta(0)],
      [23], [#name("李尚洙")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2693*], [#delta(42)],
      [24], [#name("阿德里安 马特内")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2692*], [#delta(-1)],
      [25], [#name("柳承敏")], [#age(30)], [#assoc("KOR")], [#right], [#penhold], [#attack], [*2681*], [#delta(-9)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("阿德里安 克里桑")], [#age(32)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2677*], [#delta(-2)],
      [27], [#name("帕特里克 鲍姆")], [#age(25)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2661*], [#delta(-1)],
      [28], [#name("丹尼尔 哈贝松")], [#age(26)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2660*], [#delta(-1)],
      [29], [#name("马克斯 弗雷塔斯")], [#age(24)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2659*], [#delta(-1)],
      [30], [#name("张一博")], [#age(27)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2658*], [#delta(15)],
      [31], [#name("林高远")], [#age(17)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2647*], [#delta(-1)],
      [32], [#name("陈卫星")], [#age(40)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2631*], [#delta(-3)],
      [33], [#name("方博")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2628*], [#delta(2)],
      [34], [#name("梁柱恩")], [#age(33)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2627*], [#delta(-3)],
      [35], [#name("卢文 菲鲁斯")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2620*], [#delta(12)],
      [36], [#name("若昂 蒙泰罗")], [#age(29)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2619*], [#delta(-2)],
      [37], [#name("ZHAN Jian")], [#age(30)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2613*], [#delta(-4)],
      [38], [#name("蒂亚戈 阿波罗尼亚")], [#age(26)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2609*], [#delta(13)],
      [39], [#name("尹在荣")], [#age(29)], [#assoc("KOR")], [?], [?], [?], [*2605*], [#delta(126)],
      [40], [#name("维尔纳 施拉格")], [#age(40)], [#assoc("AUT")], [?], [?], [?], [*2605*], [#delta(-4)],
      [41], [#name("亚历山大 卡拉卡谢维奇")], [#age(37)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2605*], [#delta(-4)],
      [42], [#name("松平贤二")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2596*], [#delta(-4)],
      [43], [#name("YIN Hang")], [#age(17)], [#assoc("CHN")], [?], [?], [?], [*2590*], [#delta(-2)],
      [44], [#name("王臻")], [#age(27)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2588*], [#delta(-2)],
      [45], [#name("谭瑞午")], [#age(29)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2588*], [#delta(31)],
      [46], [#name("高宁")], [#age(30)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2580*], [#delta(-21)],
      [47], [#name("高木和卓")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2579*], [#delta(12)],
      [48], [#name("金赫峰")], [#age(27)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2579*], [#delta(1)],
      [49], [#name("岸川圣也")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2576*], [#delta(-9)],
      [50], [#name("唐鹏")], [#age(31)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2575*], [#delta(-4)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("罗伯特 弗洛拉斯")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2572*], [#delta(-1)],
      [52], [#name("松平健太")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2568*], [#delta(-13)],
      [53], [#name("张成万")], [#age(27)], [#assoc("PRK")], [?], [?], [?], [*2566*], [#delta(-1)],
      [54], [#name("金东贤")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2564*], [#delta(44)],
      [55], [#name("詹斯 伦德奎斯特")], [#age(33)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2563*], [#delta(-2)],
      [56], [#name("沙拉特 阿昌塔")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2562*], [#delta(4)],
      [57], [#name("上田仁")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2562*], [#delta(5)],
      [58], [#name("亚当 帕塔纽什")], [#age(34)], [#assoc("HUN")], [#right], [#shakehand], [#defense], [*2557*], [#delta(-3)],
      [59], [#name("安德烈 加奇尼")], [#age(26)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2557*], [#delta(12)],
      [60], [#name("赵彦来")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2554*], [#delta(-17)],
      [61], [#name("基里尔 斯卡奇科夫")], [#age(25)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2548*], [#delta(-5)],
      [62], [#name("VANG Bora")], [#age(25)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2548*], [#delta(-5)],
      [63], [#name("村松雄斗")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2548*], [#delta(29)],
      [64], [#name("金珉鉐")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2544*], [#delta(-3)],
      [65], [#name("林聚")], [#age(33)], [#assoc("DOM")], [?], [?], [?], [*2543*], [#delta(-17)],
      [66], [#name("蒂亚戈 蒙泰罗")], [#age(31)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2530*], [#delta(16)],
      [67], [#name("卡林尼科斯 格林卡")], [#age(40)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2526*], [#delta(0)],
      [68], [#name("朱世赫")], [#age(32)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2524*], [#delta(1)],
      [69], [#name("帕特里克 弗朗西斯卡")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2512*], [#delta(36)],
      [70], [#name("LIU Yi")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2509*], [#delta(5)],
      [71], [#name("陈建安")], [#age(21)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2508*], [#delta(-7)],
      [72], [#name("米哈伊 博博奇卡")], [#age(26)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2506*], [#delta(31)],
      [73], [#name("徐贤德")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2506*], [#delta(21)],
      [74], [#name("李虎")], [#age(24)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2505*], [#delta(30)],
      [75], [#name("吉田海伟")], [#age(31)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2504*], [#delta(-7)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("帕尔 格雷尔")], [#age(30)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2503*], [#delta(-2)],
      [77], [#name("托米斯拉夫 科拉雷克")], [#age(24)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2501*], [#delta(-23)],
      [78], [#name("让 米歇尔 塞弗")], [#age(43)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2500*], [#delta(0)],
      [79], [#name("威廉 亨泽尔")], [#age(30)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2500*], [#delta(0)],
      [80], [#name("叶夫根尼 齐特切蒂宁")], [#age(42)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2496*], [#delta(3)],
      [81], [#name("郑荣植")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2496*], [#delta(-23)],
      [82], [#name("丁祥恩")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2495*], [#delta(-38)],
      [83], [#name("大矢英俊")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2492*], [#delta(2)],
      [84], [#name("张钰")], [#age(31)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2492*], [#delta(-11)],
      [85], [#name("罗科 托西奇")], [#age(33)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2490*], [#delta(-13)],
      [86], [#name("亚历山大 迪杜赫")], [#age(30)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2489*], [#delta(15)],
      [87], [#name("亚历山大 希巴耶夫")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2489*], [#delta(1)],
      [88], [#name("保罗 德林克霍尔")], [#age(22)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2489*], [#delta(-8)],
      [89], [#name("阿列克谢 利文佐夫")], [#age(31)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2488*], [#delta(-2)],
      [90], [#name("黄圣盛")], [#age(25)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2487*], [#delta(30)],
      [91], [#name("刘松")], [#age(40)], [#assoc("ARG")], [?], [?], [?], [*2483*], [#delta(43)],
      [92], [#name("里卡多 瓦尔特")], [#age(21)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2482*], [#delta(-3)],
      [93], [#name("吉村真晴")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2482*], [#delta(-3)],
      [94], [#name("吴志祺")], [#age(26)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2479*], [#delta(45)],
      [95], [#name("何志文")], [#age(50)], [#assoc("ESP")], [#left], [#penhold], [#attack], [*2478*], [#delta(0)],
      [96], [#name("克里斯蒂安 苏斯")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2478*], [#delta(0)],
      [97], [#name("艾曼纽 莱贝松")], [#age(24)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2477*], [#delta(-31)],
      [98], [#name("诺沙迪 阿拉米扬")], [#age(21)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2477*], [#delta(-35)],
      [99], [#name("王增羿")], [#age(29)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2476*], [#delta(39)],
      [100], [#name("卡洛斯 马查多")], [#age(32)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2476*], [#delta(41)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("巴托什 苏赫")], [#age(29)], [#assoc("POL")], [?], [?], [?], [*2474*], [#delta(-17)],
      [102], [#name("德米特里 普罗科普科夫")], [#age(32)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2473*], [#delta(21)],
      [103], [#name("马蒂斯 布尔吉斯")], [#age(23)], [#assoc("LAT")], [#right], [#shakehand], [#attack], [*2473*], [#delta(16)],
      [104], [#name("阿马拉杰 安东尼")], [#age(26)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2472*], [#delta(-23)],
      [105], [#name("特里斯坦 弗洛雷")], [#age(17)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2471*], [#delta(-6)],
      [106], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(32)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2470*], [#delta(-6)],
      [107], [#name("雅罗斯拉夫 扎穆登科")], [#age(24)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2469*], [#delta(28)],
      [108], [#name("松本和雄")], [#age(27)], [#assoc("BRA")], [#left], [#penhold], [#attack], [*2468*], [#delta(-31)],
      [109], [#name("寇磊")], [#age(25)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2467*], [#delta(24)],
      [110], [#name("马尔科 耶夫托维奇")], [#age(25)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2467*], [#delta(-8)],
      [111], [#name("西蒙 高兹")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2460*], [#delta(-25)],
      [112], [#name("古斯塔沃 坪井")], [#age(27)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2459*], [#delta(-5)],
      [113], [#name("彼得 科贝尔")], [#age(41)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2459*], [#delta(-7)],
      [114], [#name("SAHA Subhajit")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2458*], [#delta(-4)],
      [115], [#name("利亚姆 皮切福德")], [#age(19)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2456*], [#delta(-45)],
      [116], [#name("丹尼尔 茨维克尔")], [#age(28)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2456*], [#delta(-5)],
      [117], [#name("丹尼尔 古拉克")], [#age(29)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2455*], [#delta(-8)],
      [118], [#name("笠原弘光")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2453*], [#delta(-5)],
      [119], [#name("康坦 罗比诺特")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2451*], [#delta(-5)],
      [120], [#name("约瑟夫 西蒙契克")], [#age(32)], [#assoc("CZE")], [?], [?], [?], [*2449*], [#delta(-5)],
      [121], [#name("吴家骥")], [#age(17)], [#assoc("DOM")], [#right], [#penhold], [#attack], [*2448*], [#delta(-5)],
      [122], [#name("阿列克谢 斯米尔诺夫")], [#age(35)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2442*], [#delta(-4)],
      [123], [#name("克里斯坦 卡尔松")], [#age(21)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2442*], [#delta(46)],
      [124], [#name("格里戈里 弗拉索夫")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2442*], [#delta(67)],
      [125], [#name("约尔根 佩尔森")], [#age(46)], [#assoc("SWE")], [?], [?], [?], [*2441*], [#delta(53)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("埃尔萨伊德 拉辛")], [#age(32)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-18)],
      [127], [#name("佐尔特 佩托")], [#age(25)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2437*], [#delta(4)],
      [128], [#name("佐尔坦 费杰科内斯")], [#age(34)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2437*], [#delta(-7)],
      [129], [#name("佐兰 普里莫拉克")], [#age(43)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2434*], [#delta(-5)],
      [130], [#name("托马斯 凯纳特")], [#age(35)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2432*], [#delta(-18)],
      [131], [#name("尼亚戈尔 斯托亚诺夫")], [#age(25)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2432*], [#delta(-34)],
      [132], [#name("苏姆亚吉特 格霍什")], [#age(19)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-7)],
      [133], [#name("KATKOV Ivan")], [#age(28)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-7)],
      [134], [#name("斯特凡 菲格尔")], [#age(24)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2430*], [#delta(-7)],
      [135], [#name("阿兰 本特森")], [#age(44)], [#assoc("DEN")], [?], [?], [?], [*2427*], [#delta(28)],
      [136], [#name("三内贤太郎")], [#age(23)], [#assoc("JPN")], [?], [?], [?], [*2427*], [#delta(-7)],
      [137], [#name("陈丰")], [#age(18)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2426*], [#delta(-44)],
      [138], [#name("米哈伊尔 派科夫")], [#age(23)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2423*], [#delta(-10)],
      [139], [#name("米哈尔 奥贝斯洛")], [#age(23)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2422*], [#delta(-7)],
      [140], [#name("康斯坦丁 乔蒂")], [#age(29)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2420*], [#delta(-18)],
      [141], [#name("酒井明日翔")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2420*], [#delta(164)],
      [142], [#name("瓦西里 拉凯耶夫")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2419*], [#delta(47)],
      [143], [#name("金正勋")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2414*], [#delta(-7)],
      [144], [#name("町飞鸟")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2410*], [#delta(51)],
      [145], [#name("LEE Chia-Sheng")], [#age(17)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2408*], [#delta(112)],
      [146], [#name("HIGASHI Yuto")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2406*], [#delta(26)],
      [147], [#name("李镇权")], [#age(25)], [#assoc("KOR")], [?], [?], [?], [*2404*], [#delta(-4)],
      [148], [#name("吉田雅己")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2404*], [#delta(28)],
      [149], [#name("帕维尔 普拉托诺夫")], [#age(29)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2402*], [#delta(24)],
      [150], [#name("达米安 埃洛伊")], [#age(43)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2401*], [#delta(-6)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("周雨")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2401*], [#delta(-6)],
      [152], [#name("LINDNER Adam")], [#age(37)], [#assoc("HUN")], [#right], [#penhold], [#attack], [*2400*], [#delta(-6)],
      [153], [#name("LORENTZ Romain")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2400*], [#delta(52)],
      [154], [#name("乔恩 佩尔森")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2400*], [#delta(-7)],
      [155], [#name("尼马 阿拉米安")], [#age(20)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2399*], [#delta(89)],
      [156], [#name("塩野真人")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2397*], [#delta(-8)],
      [157], [#name("费奥多尔 库兹明")], [#age(29)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2397*], [#delta(-5)],
      [158], [#name("马科斯 马德里")], [#age(26)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2396*], [#delta(3)],
      [159], [#name("LAGOGIANNIS Konstantinos")], [#age(31)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2394*], [#delta(-10)],
      [160], [#name("马克 杜兰")], [#age(26)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2394*], [#delta(-10)],
      [161], [#name("PETIOT Jeremy")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2392*], [#delta(-10)],
      [162], [#name("KIM Song Nam")], [#age(20)], [#assoc("PRK")], [?], [?], [?], [*2390*], [#delta(-8)],
      [163], [#name("亚诺什 雅各布")], [#age(26)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2389*], [#delta(-5)],
      [164], [#name("艾哈迈德 萨利赫")], [#age(33)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2387*], [#delta(-8)],
      [165], [#name("丹尼尔 里德")], [#age(23)], [#assoc("ENG")], [?], [?], [?], [*2379*], [#delta(-3)],
      [166], [#name("汪洋")], [#age(18)], [#assoc("SVK")], [#right], [#shakehand], [#defense], [*2376*], [#delta(125)],
      [167], [#name("托马斯 科涅茨尼")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2376*], [#delta(-3)],
      [168], [#name("下山隆敬")], [#age(27)], [#assoc("JPN")], [?], [?], [?], [*2374*], [#delta(-2)],
      [169], [#name("克里斯托夫 勒古")], [#age(39)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2371*], [#delta(-2)],
      [170], [#name("李良夫")], [#age(21)], [#assoc("TUR")], [#left], [#shakehand], [#attack], [*2370*], [#delta(-15)],
      [171], [#name("RUMGAY Gavin")], [#age(28)], [#assoc("SCO")], [#right], [#shakehand], [#attack], [*2370*], [#delta(-1)],
      [172], [#name("斯蒂芬 门格尔")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2362*], [#delta(-81)],
      [173], [#name("奥维迪乌 伊奥内斯库")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2361*], [#delta(2)],
      [174], [#name("罗伯特 斯文松")], [#age(29)], [#assoc("SWE")], [?], [?], [?], [*2360*], [#delta(3)],
      [175], [#name("安德鲁 巴格利")], [#age(29)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2359*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("马塞洛 阿吉雷")], [#age(19)], [#assoc("PAR")], [#left], [#shakehand], [#attack], [*2358*], [#delta(-23)],
      [177], [#name("LE BRETON Thomas")], [#age(20)], [#assoc("FRA")], [?], [?], [?], [*2356*], [#delta(-17)],
      [178], [#name("罗宾 德沃斯")], [#age(18)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2356*], [#delta(41)],
      [179], [#name("杨子")], [#age(28)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2354*], [#delta(-42)],
      [180], [#name("黄镇廷")], [#age(21)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2354*], [#delta(-63)],
      [181], [#name("康斯坦丁诺斯 帕帕乔治乌")], [#age(33)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2349*], [#delta(36)],
      [182], [#name("尚坤")], [#age(22)], [#assoc("CHN")], [?], [?], [?], [*2348*], [#delta(1)],
      [183], [#name("萨什 拉桑")], [#age(41)], [#assoc("SLO")], [#right], [#shakehand], [#defense], [*2345*], [#delta(20)],
      [184], [#name("加斯顿 阿尔托")], [#age(27)], [#assoc("ARG")], [#right], [#shakehand], [#attack], [*2344*], [#delta(97)],
      [185], [#name("阿卜杜勒-卡德尔 萨利富")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2343*], [#delta(70)],
      [186], [#name("LIU Yanan")], [#age(18)], [#assoc("CHN")], [?], [?], [?], [*2341*], [#delta(-2)],
      [187], [#name("LEE Junsang")], [#age(22)], [#assoc("KOR")], [?], [?], [?], [*2338*], [#delta(-2)],
      [188], [#name("MARTINEZ Michel")], [#age(33)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2338*], [#delta(-2)],
      [189], [#name("KIM Nam Chol")], [#age(24)], [#assoc("PRK")], [?], [?], [?], [*2338*], [#delta(-9)],
      [190], [#name("金泰勋")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2337*], [#delta(-3)],
      [191], [#name("WU Zhikang")], [#age(18)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2333*], [#delta(-1)],
      [192], [#name("ZUBCIC Tomislav")], [#age(26)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2333*], [#delta(-13)],
      [193], [#name("达尼埃尔 科希鲍")], [#age(21)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2330*], [#delta(-34)],
      [194], [#name("维亚切斯拉夫 布罗夫")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2330*], [#delta(-23)],
      [195], [#name("夸德里 阿鲁纳")], [#age(24)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2326*], [#delta(-3)],
      [196], [#name("拉尔斯 希尔舍")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2326*], [#delta(-3)],
      [197], [#name("安德烈 菲利蒙")], [#age(35)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2325*], [#delta(-16)],
      [198], [#name("帕维尔 费尔蒂科夫斯基")], [#age(22)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2324*], [#delta(-4)],
      [199], [#name("恩佐 昂格勒")], [#age(17)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2323*], [#delta(-3)],
      [200], [#name("VOSTES Yannick")], [#age(27)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2321*], [#delta(-32)],
    )
  )
