#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("马龙")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3136*], [#delta(0)],
      [2], [#name("张继科")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3014*], [#delta(0)],
      [3], [#name("蒂姆 波尔")], [#age(31)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2944*], [#delta(0)],
      [4], [#name("许昕")], [#age(22)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*2944*], [#delta(0)],
      [5], [#name("王励勤")], [#age(34)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2909*], [#delta(0)],
      [6], [#name("郝帅")], [#age(29)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2901*], [#delta(0)],
      [7], [#name("王皓")], [#age(29)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2897*], [#delta(0)],
      [8], [#name("陈玘")], [#age(28)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2841*], [#delta(1)],
      [9], [#name("马琳")], [#age(32)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2833*], [#delta(-1)],
      [10], [#name("闫安")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2799*], [#delta(0)],
      [11], [#name("朱世赫")], [#age(32)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2776*], [#delta(1)],
      [12], [#name("水谷隼")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2766*], [#delta(-1)],
      [13], [#name("米凯尔 梅兹")], [#age(31)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2723*], [#delta(0)],
      [14], [#name("柳承敏")], [#age(30)], [#assoc("KOR")], [#right], [#penhold], [#attack], [*2722*], [#delta(0)],
      [15], [#name("庄智渊")], [#age(31)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2720*], [#delta(1)],
      [16], [#name("博扬 托基奇")], [#age(31)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2709*], [#delta(-1)],
      [17], [#name("SEO Hyundeok")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2704*], [#delta(32)],
      [18], [#name("迪米特里 奥恰洛夫")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2700*], [#delta(-1)],
      [19], [#name("阿德里安 马特内")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2693*], [#delta(-1)],
      [20], [#name("维尔纳 施拉格")], [#age(40)], [#assoc("AUT")], [?], [?], [?], [*2673*], [#delta(-1)],
      [21], [#name("帕特里克 鲍姆")], [#age(25)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2667*], [#delta(0)],
      [22], [#name("丹羽孝希")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2662*], [#delta(5)],
      [23], [#name("JANG Song Man")], [#age(27)], [#assoc("PRK")], [?], [?], [?], [*2655*], [#delta(39)],
      [24], [#name("基里尔 斯卡奇科夫")], [#age(25)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2654*], [#delta(-2)],
      [25], [#name("林高远")], [#age(17)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2647*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("弗拉基米尔 萨姆索诺夫")], [#age(36)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2646*], [#delta(-2)],
      [27], [#name("MATSUDAIRA Kenji")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2640*], [#delta(-1)],
      [28], [#name("高宁")], [#age(30)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2633*], [#delta(7)],
      [29], [#name("阿德里安 克里桑")], [#age(32)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2626*], [#delta(1)],
      [30], [#name("吴尚垠")], [#age(35)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2624*], [#delta(1)],
      [31], [#name("亚历山大 希巴耶夫")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2618*], [#delta(2)],
      [32], [#name("方博")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2615*], [#delta(2)],
      [33], [#name("亚历山大 卡拉卡谢维奇")], [#age(37)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2604*], [#delta(3)],
      [34], [#name("TAKAKIWA Taku")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2603*], [#delta(3)],
      [35], [#name("ZHAN Jian")], [#age(30)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2602*], [#delta(3)],
      [36], [#name("巴斯蒂安 斯蒂格")], [#age(31)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2598*], [#delta(4)],
      [37], [#name("诺沙迪 阿拉米扬")], [#age(21)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2597*], [#delta(-8)],
      [38], [#name("松平健太")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2595*], [#delta(12)],
      [39], [#name("MONTEIRO Joao")], [#age(29)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2595*], [#delta(2)],
      [40], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(32)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2595*], [#delta(2)],
      [41], [#name("唐鹏")], [#age(31)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2590*], [#delta(78)],
      [42], [#name("YIN Hang")], [#age(17)], [#assoc("CHN")], [?], [?], [?], [*2590*], [#delta(1)],
      [43], [#name("王臻")], [#age(27)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2588*], [#delta(1)],
      [44], [#name("丁祥恩")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2588*], [#delta(1)],
      [45], [#name("CHO Eonrae")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2587*], [#delta(1)],
      [46], [#name("卢文 菲鲁斯")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2585*], [#delta(1)],
      [47], [#name("蒂亚戈 阿波罗尼亚")], [#age(26)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2583*], [#delta(1)],
      [48], [#name("岸川圣也")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2581*], [#delta(-9)],
      [49], [#name("李廷佑")], [#age(28)], [#assoc("KOR")], [#left], [#penhold], [#attack], [*2568*], [#delta(-29)],
      [50], [#name("李尚洙")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2565*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("GERELL Par")], [#age(30)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2563*], [#delta(1)],
      [52], [#name("西蒙 高兹")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2563*], [#delta(1)],
      [53], [#name("马克斯 弗雷塔斯")], [#age(24)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2560*], [#delta(1)],
      [54], [#name("陈卫星")], [#age(40)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2555*], [#delta(1)],
      [55], [#name("何志文")], [#age(50)], [#assoc("ESP")], [#left], [#penhold], [#attack], [*2555*], [#delta(1)],
      [56], [#name("金珉锡")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2552*], [#delta(-31)],
      [57], [#name("BOBOCICA Mihai")], [#age(26)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2546*], [#delta(0)],
      [58], [#name("罗伯特 加尔多斯")], [#age(33)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2542*], [#delta(0)],
      [59], [#name("佐兰 普里莫拉克")], [#age(43)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2538*], [#delta(0)],
      [60], [#name("上田仁")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2535*], [#delta(0)],
      [61], [#name("KASAHARA Hiromitsu")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2535*], [#delta(0)],
      [62], [#name("LIN Ju")], [#age(33)], [#assoc("DOM")], [?], [?], [?], [*2534*], [#delta(18)],
      [63], [#name("江天一")], [#age(24)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2533*], [#delta(-35)],
      [64], [#name("帕特里克 弗朗西斯卡")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2529*], [#delta(-1)],
      [65], [#name("吉田海伟")], [#age(31)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2526*], [#delta(-1)],
      [66], [#name("詹斯 伦德奎斯特")], [#age(33)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2526*], [#delta(-1)],
      [67], [#name("CHEN Feng")], [#age(18)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2520*], [#delta(-1)],
      [68], [#name("TOSIC Roko")], [#age(33)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2516*], [#delta(-1)],
      [69], [#name("LIU Yi")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2509*], [#delta(0)],
      [70], [#name("谭瑞午")], [#age(29)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2508*], [#delta(0)],
      [71], [#name("梁柱恩")], [#age(33)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2507*], [#delta(-39)],
      [72], [#name("DIDUKH Oleksandr")], [#age(30)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2505*], [#delta(-1)],
      [73], [#name("SUCH Bartosz")], [#age(29)], [#assoc("POL")], [?], [?], [?], [*2504*], [#delta(-1)],
      [74], [#name("RUBTSOV Igor")], [#age(32)], [#assoc("RUS")], [?], [?], [?], [*2504*], [#delta(-1)],
      [75], [#name("WANG Zengyi")], [#age(29)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2502*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("郑荣植")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2499*], [#delta(48)],
      [77], [#name("安德烈 加奇尼")], [#age(26)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2495*], [#delta(-1)],
      [78], [#name("LIVENTSOV Alexey")], [#age(31)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2494*], [#delta(-1)],
      [79], [#name("OYA Hidetoshi")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2493*], [#delta(-1)],
      [80], [#name("黄镇廷")], [#age(21)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2489*], [#delta(-1)],
      [81], [#name("陈建安")], [#age(21)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2486*], [#delta(-13)],
      [82], [#name("WALTHER Ricardo")], [#age(21)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2483*], [#delta(-1)],
      [83], [#name("KEINATH Thomas")], [#age(35)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2482*], [#delta(-1)],
      [84], [#name("利亚姆 皮切福德")], [#age(19)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2478*], [#delta(0)],
      [85], [#name("KUZMIN Fedor")], [#age(29)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2473*], [#delta(0)],
      [86], [#name("奥马尔 阿萨尔")], [#age(21)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2473*], [#delta(0)],
      [87], [#name("PATTANTYUS Adam")], [#age(34)], [#assoc("HUN")], [#right], [#shakehand], [#defense], [*2472*], [#delta(0)],
      [88], [#name("SIMONCIK Josef")], [#age(32)], [#assoc("CZE")], [?], [?], [?], [*2472*], [#delta(0)],
      [89], [#name("MACHADO Carlos")], [#age(32)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2469*], [#delta(0)],
      [90], [#name("阿列克谢 斯米尔诺夫")], [#age(35)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2468*], [#delta(1)],
      [91], [#name("约尔根 佩尔森")], [#age(46)], [#assoc("SWE")], [?], [?], [?], [*2467*], [#delta(1)],
      [92], [#name("雅罗斯列夫 扎姆登科")], [#age(24)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2467*], [#delta(1)],
      [93], [#name("LI Hu")], [#age(24)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2465*], [#delta(1)],
      [94], [#name("ZUBCIC Tomislav")], [#age(26)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2460*], [#delta(2)],
      [95], [#name("克里斯蒂安 苏斯")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2457*], [#delta(2)],
      [96], [#name("吉村真晴")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2451*], [#delta(2)],
      [97], [#name("张钰")], [#age(31)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2450*], [#delta(2)],
      [98], [#name("WU Jiaji")], [#age(17)], [#assoc("DOM")], [#right], [#penhold], [#attack], [*2447*], [#delta(3)],
      [99], [#name("让 米歇尔 赛弗")], [#age(43)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2446*], [#delta(3)],
      [100], [#name("LI Ahmet")], [#age(21)], [#assoc("TUR")], [#left], [#shakehand], [#attack], [*2443*], [#delta(3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("德米特里 佩罗普科夫")], [#age(32)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2441*], [#delta(3)],
      [102], [#name("特里斯坦 弗洛雷")], [#age(17)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2440*], [#delta(3)],
      [103], [#name("GORAK Daniel")], [#age(29)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2439*], [#delta(3)],
      [104], [#name("HUANG Sheng-Sheng")], [#age(25)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2437*], [#delta(-21)],
      [105], [#name("FEJER-KONNERTH Zoltan")], [#age(34)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2437*], [#delta(2)],
      [106], [#name("张一博")], [#age(27)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2436*], [#delta(-11)],
      [107], [#name("PAIKOV Mikhail")], [#age(23)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2434*], [#delta(1)],
      [108], [#name("BENTSEN Allan")], [#age(44)], [#assoc("DEN")], [?], [?], [?], [*2429*], [#delta(2)],
      [109], [#name("ROBINOT Quentin")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2428*], [#delta(3)],
      [110], [#name("HUNG Tzu-Hsiang")], [#age(18)], [#assoc("TPE")], [#right], [#penhold], [#attack], [*2427*], [#delta(1)],
      [111], [#name("MIUCHI Kentaro")], [#age(23)], [#assoc("JPN")], [?], [?], [?], [*2427*], [#delta(2)],
      [112], [#name("艾曼纽 莱贝松")], [#age(24)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2424*], [#delta(2)],
      [113], [#name("HABESOHN Daniel")], [#age(26)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2424*], [#delta(2)],
      [114], [#name("卡林尼科斯 格林卡")], [#age(40)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2423*], [#delta(2)],
      [115], [#name("TSUBOI Gustavo")], [#age(27)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2423*], [#delta(5)],
      [116], [#name("LIU Song")], [#age(40)], [#assoc("ARG")], [?], [?], [?], [*2423*], [#delta(-16)],
      [117], [#name("奥维迪乌 伊奥内斯库")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2423*], [#delta(0)],
      [118], [#name("VANG Bora")], [#age(25)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2420*], [#delta(0)],
      [119], [#name("CARNEROS Alfredo")], [#age(34)], [#assoc("ESP")], [?], [?], [?], [*2414*], [#delta(3)],
      [120], [#name("KIM Junghoon")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2414*], [#delta(3)],
      [121], [#name("BAGGALEY Andrew")], [#age(29)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2412*], [#delta(4)],
      [122], [#name("MATSUMOTO Cazuo")], [#age(27)], [#assoc("BRA")], [#left], [#penhold], [#attack], [*2407*], [#delta(-1)],
      [123], [#name("WU Chih-Chi")], [#age(26)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2407*], [#delta(64)],
      [124], [#name("马蒂亚斯 法尔克")], [#age(21)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2405*], [#delta(2)],
      [125], [#name("斯特凡 菲格尔")], [#age(24)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2404*], [#delta(2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("LEE Jinkwon")], [#age(25)], [#assoc("KOR")], [?], [?], [?], [*2404*], [#delta(2)],
      [127], [#name("PETO Zsolt")], [#age(25)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2401*], [#delta(2)],
      [128], [#name("达米安 艾洛伊")], [#age(43)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2401*], [#delta(2)],
      [129], [#name("ANTHONY Amalraj")], [#age(26)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2401*], [#delta(143)],
      [130], [#name("CHTCHETININE Evgueni")], [#age(42)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2401*], [#delta(1)],
      [131], [#name("周雨")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2400*], [#delta(1)],
      [132], [#name("PERSSON Jon")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2400*], [#delta(1)],
      [133], [#name("LINDNER Adam")], [#age(37)], [#assoc("HUN")], [#right], [#penhold], [#attack], [*2400*], [#delta(1)],
      [134], [#name("ACHANTA Sharath")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2399*], [#delta(-60)],
      [135], [#name("克里斯坦 卡尔松")], [#age(21)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2398*], [#delta(0)],
      [136], [#name("斯蒂芬 门格尔")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2398*], [#delta(0)],
      [137], [#name("塩野真人")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2397*], [#delta(0)],
      [138], [#name("CIOTI Constantin")], [#age(29)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2396*], [#delta(0)],
      [139], [#name("GAVLAS Antonin")], [#age(27)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2395*], [#delta(0)],
      [140], [#name("RUMGAY Gavin")], [#age(28)], [#assoc("SCO")], [#right], [#shakehand], [#attack], [*2395*], [#delta(0)],
      [141], [#name("彼得 科贝尔")], [#age(41)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2393*], [#delta(0)],
      [142], [#name("PETIOT Jeremy")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2392*], [#delta(0)],
      [143], [#name("PISTEJ Lubomir")], [#age(28)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2390*], [#delta(0)],
      [144], [#name("DRINKHALL Paul")], [#age(22)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2389*], [#delta(0)],
      [145], [#name("SALEH Ahmed")], [#age(33)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2385*], [#delta(0)],
      [146], [#name("寇磊")], [#age(25)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2385*], [#delta(0)],
      [147], [#name("SEREDA Peter")], [#age(28)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2383*], [#delta(1)],
      [148], [#name("HIGASHI Yuto")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2379*], [#delta(1)],
      [149], [#name("HENZELL William")], [#age(30)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2379*], [#delta(3)],
      [150], [#name("村松雄斗")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2376*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("KOSOWSKI Jakub")], [#age(30)], [#assoc("POL")], [?], [?], [?], [*2375*], [#delta(0)],
      [152], [#name("YANG Zi")], [#age(28)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2375*], [#delta(-62)],
      [153], [#name("SHIMOYAMA Takanori")], [#age(27)], [#assoc("JPN")], [?], [?], [?], [*2374*], [#delta(0)],
      [154], [#name("尹在荣")], [#age(29)], [#assoc("KOR")], [?], [?], [?], [*2374*], [#delta(0)],
      [155], [#name("JAKAB Janos")], [#age(26)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2372*], [#delta(0)],
      [156], [#name("LEGOUT Christophe")], [#age(39)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2371*], [#delta(1)],
      [157], [#name("BUROV Viacheslav")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2370*], [#delta(1)],
      [158], [#name("金赫峰")], [#age(27)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2367*], [#delta(-49)],
      [159], [#name("BURGIS Matiss")], [#age(23)], [#assoc("LAT")], [#right], [#shakehand], [#attack], [*2366*], [#delta(1)],
      [160], [#name("乔纳森 格罗斯")], [#age(20)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2363*], [#delta(1)],
      [161], [#name("吉田雅己")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2358*], [#delta(1)],
      [162], [#name("LORENTZ Romain")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2358*], [#delta(1)],
      [163], [#name("MONTEIRO Thiago")], [#age(31)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2353*], [#delta(159)],
      [164], [#name("KIM Nam Chol")], [#age(24)], [#assoc("PRK")], [?], [?], [?], [*2352*], [#delta(0)],
      [165], [#name("FILIMON Andrei")], [#age(35)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2352*], [#delta(0)],
      [166], [#name("LAGOGIANNIS Konstantinos")], [#age(31)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2352*], [#delta(0)],
      [167], [#name("SVENSSON Robert")], [#age(29)], [#assoc("SWE")], [?], [?], [?], [*2350*], [#delta(0)],
      [168], [#name("VLASOV Grigory")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2350*], [#delta(0)],
      [169], [#name("JANCARIK Lubomir")], [#age(25)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2350*], [#delta(0)],
      [170], [#name("尚坤")], [#age(22)], [#assoc("CHN")], [?], [?], [?], [*2348*], [#delta(0)],
      [171], [#name("KIM Song Nam")], [#age(20)], [#assoc("PRK")], [?], [?], [?], [*2342*], [#delta(2)],
      [172], [#name("CANTERO Jesus")], [#age(30)], [#assoc("ESP")], [#right], [#penhold], [#attack], [*2341*], [#delta(-1)],
      [173], [#name("LIU Yanan")], [#age(18)], [#assoc("CHN")], [?], [?], [?], [*2341*], [#delta(-1)],
      [174], [#name("JEVTOVIC Marko")], [#age(25)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2341*], [#delta(0)],
      [175], [#name("LEE Junsang")], [#age(22)], [#assoc("KOR")], [?], [?], [?], [*2339*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("MARTINEZ Michel")], [#age(33)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2338*], [#delta(0)],
      [177], [#name("KIM Taehoon")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2337*], [#delta(0)],
      [178], [#name("RECH DALDOSSO Marco")], [#age(20)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2336*], [#delta(0)],
      [179], [#name("AGUIRRE Marcelo")], [#age(19)], [#assoc("PAR")], [#left], [#shakehand], [#attack], [*2336*], [#delta(51)],
      [180], [#name("LAKEEV Vasily")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2335*], [#delta(-1)],
      [181], [#name("KONECNY Tomas")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2335*], [#delta(-1)],
      [182], [#name("FLORITZ Philipp")], [#age(21)], [#assoc("BUL")], [#right], [#shakehand], [#attack], [*2333*], [#delta(-1)],
      [183], [#name("LASHIN Elsayed")], [#age(32)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2330*], [#delta(-1)],
      [184], [#name("STERNBERG Kasper")], [#age(23)], [#assoc("DEN")], [#right], [#shakehand], [#attack], [*2328*], [#delta(-1)],
      [185], [#name("MADRID Marcos")], [#age(26)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2328*], [#delta(-26)],
      [186], [#name("HIELSCHER Lars")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2326*], [#delta(-2)],
      [187], [#name("DURAN Marc")], [#age(26)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2325*], [#delta(-2)],
      [188], [#name("FERTIKOWSKI Pawel")], [#age(22)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2324*], [#delta(-2)],
      [189], [#name("PEREIRA Andy")], [#age(23)], [#assoc("CUB")], [#left], [#shakehand], [#attack], [*2321*], [#delta(3)],
      [190], [#name("KOLAREK Tomislav")], [#age(24)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2320*], [#delta(-2)],
      [191], [#name("李静")], [#age(37)], [#assoc("HKG")], [?], [?], [?], [*2319*], [#delta(-35)],
      [192], [#name("JUZBASIC Ivan")], [#age(32)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2317*], [#delta(-3)],
      [193], [#name("PLATONOV Pavel")], [#age(29)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2317*], [#delta(-3)],
      [194], [#name("GOLEBIOWSKI Mateusz")], [#age(22)], [#assoc("POL")], [?], [?], [?], [*2316*], [#delta(-3)],
      [195], [#name("ANGLES Enzo")], [#age(17)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2315*], [#delta(-2)],
      [196], [#name("FAZEKAS Peter")], [#age(31)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2314*], [#delta(-2)],
      [197], [#name("BARDON Michal")], [#age(34)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2310*], [#delta(-1)],
      [198], [#name("VRABLIK Jiri")], [#age(29)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2310*], [#delta(-1)],
      [199], [#name("FLORAS Robert")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2308*], [#delta(-1)],
      [200], [#name("STORF Martin")], [#age(23)], [#assoc("AUT")], [?], [?], [?], [*2306*], [#delta(-1)],
    )
  )
