#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("陈梦")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3175*], [#delta(0)],
      [2], [#name("王曼昱")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3024*], [#delta(0)],
      [3], [#name("孙颖莎")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2981*], [#delta(0)],
      [4], [#name("伊藤美诚")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2962*], [#delta(0)],
      [5], [#name("刘诗雯")], [#age(30)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2949*], [#delta(0)],
      [6], [#name("王艺迪")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2941*], [#delta(0)],
      [7], [#name("钱天一")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2863*], [#delta(0)],
      [8], [#name("陈幸同")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2862*], [#delta(0)],
      [9], [#name("张瑞")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2828*], [#delta(0)],
      [10], [#name("早田希娜")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2822*], [#delta(0)],
      [11], [#name("桥本帆乃香")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2787*], [#delta(0)],
      [12], [#name("韩莹")], [#age(38)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2773*], [#delta(0)],
      [13], [#name("佐藤瞳")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2759*], [#delta(0)],
      [14], [#name("佩特丽莎 索尔佳")], [#age(27)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2731*], [#delta(0)],
      [15], [#name("范思琦")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2725*], [#delta(0)],
      [16], [#name("何卓佳")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2724*], [#delta(0)],
      [17], [#name("石洵瑶")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2718*], [#delta(0)],
      [18], [#name("田志希")], [#age(29)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2716*], [#delta(0)],
      [19], [#name("芝田沙季")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2714*], [#delta(0)],
      [20], [#name("加藤美优")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2712*], [#delta(0)],
      [21], [#name("刘炜珊")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2710*], [#delta(0)],
      [22], [#name("冯天薇")], [#age(35)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2710*], [#delta(0)],
      [23], [#name("郑怡静")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2709*], [#delta(0)],
      [24], [#name("单晓娜")], [#age(38)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2708*], [#delta(0)],
      [25], [#name("申裕斌")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2707*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("于梦雨")], [#age(32)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2705*], [#delta(0)],
      [27], [#name("平野美宇")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2698*], [#delta(0)],
      [28], [#name("梁夏银")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2696*], [#delta(0)],
      [29], [#name("长崎美柚")], [#age(19)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2694*], [#delta(0)],
      [30], [#name("木原美悠")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2692*], [#delta(0)],
      [31], [#name("安藤南")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2691*], [#delta(0)],
      [32], [#name("石川佳纯")], [#age(28)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2689*], [#delta(0)],
      [33], [#name("金河英")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2662*], [#delta(0)],
      [34], [#name("陈思羽")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2657*], [#delta(0)],
      [35], [#name("蒯曼")], [#age(17)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2652*], [#delta(0)],
      [36], [#name("杨晓欣")], [#age(33)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2648*], [#delta(0)],
      [37], [#name("伊丽莎白 萨玛拉")], [#age(32)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2646*], [#delta(0)],
      [38], [#name("陈熠")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2641*], [#delta(0)],
      [39], [#name("崔孝珠")], [#age(23)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2640*], [#delta(0)],
      [40], [#name("小盐遥菜")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2637*], [#delta(0)],
      [41], [#name("徐孝元")], [#age(34)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2627*], [#delta(0)],
      [42], [#name("PESOTSKA Margaryta")], [#age(30)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2624*], [#delta(0)],
      [43], [#name("森樱")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2617*], [#delta(0)],
      [44], [#name("萨比亚 温特")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2616*], [#delta(0)],
      [45], [#name("倪夏莲")], [#age(58)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2615*], [#delta(0)],
      [46], [#name("吴洋晨")], [#age(19)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2611*], [#delta(0)],
      [47], [#name("李倩")], [#age(35)], [#assoc("CHN")], [?], [?], [?], [*2611*], [#delta(0)],
      [48], [#name("曾尖")], [#age(25)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2606*], [#delta(0)],
      [49], [#name("李皓晴")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2606*], [#delta(0)],
      [50], [#name("傅玉")], [#age(43)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2606*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("阿德里安娜 迪亚兹")], [#age(21)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2603*], [#delta(0)],
      [52], [#name("袁嘉楠")], [#age(36)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2597*], [#delta(0)],
      [53], [#name("妮娜 米特兰姆")], [#age(25)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2595*], [#delta(0)],
      [54], [#name("琳达 伯格斯特罗姆")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2595*], [#delta(0)],
      [55], [#name("SOO Wai Yam")], [#age(23)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2594*], [#delta(0)],
      [56], [#name("苏萨西尼 萨维塔布特")], [#age(27)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2590*], [#delta(0)],
      [57], [#name("李时温")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2582*], [#delta(0)],
      [58], [#name("玛妮卡 巴特拉")], [#age(26)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2578*], [#delta(0)],
      [59], [#name("杜凯琹")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2563*], [#delta(0)],
      [60], [#name("索菲亚 波尔卡诺娃")], [#age(27)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2553*], [#delta(0)],
      [61], [#name("李恩惠")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2545*], [#delta(0)],
      [62], [#name("CHENG Hsien-Tzu")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2542*], [#delta(0)],
      [63], [#name("MIKHAILOVA Polina")], [#age(35)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2537*], [#delta(0)],
      [64], [#name("张安")], [#age(25)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2537*], [#delta(0)],
      [65], [#name("NOSKOVA Yana")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2536*], [#delta(0)],
      [66], [#name("YOO Eunchong")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2533*], [#delta(0)],
      [67], [#name("DIACONU Adina")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2532*], [#delta(0)],
      [68], [#name("朱成竹")], [#age(24)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2529*], [#delta(0)],
      [69], [#name("DODEAN Daniela")], [#age(33)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2529*], [#delta(0)],
      [70], [#name("BAJOR Natalia")], [#age(24)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2527*], [#delta(0)],
      [71], [#name("DE NUTTE Sarah")], [#age(29)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2517*], [#delta(0)],
      [72], [#name("LIU Hsing-Yin")], [#age(34)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2515*], [#delta(0)],
      [73], [#name("BALAZOVA Barbora")], [#age(29)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2508*], [#delta(0)],
      [74], [#name("WU Yue")], [#age(31)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2507*], [#delta(0)],
      [75], [#name("布里特 伊尔兰德")], [#age(27)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2505*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("李昱谆")], [#age(24)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2496*], [#delta(0)],
      [77], [#name("HAPONOVA Hanna")], [#age(36)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2495*], [#delta(0)],
      [78], [#name("克里斯蒂娜 卡尔伯格")], [#age(21)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2489*], [#delta(0)],
      [79], [#name("刘佳")], [#age(39)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2485*], [#delta(0)],
      [80], [#name("NG Wing Nam")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2484*], [#delta(0)],
      [81], [#name("TAILAKOVA Mariia")], [#age(20)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2482*], [#delta(0)],
      [82], [#name("普利西卡 帕瓦德")], [#age(17)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2482*], [#delta(0)],
      [83], [#name("KIM Byeolnim")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2480*], [#delta(0)],
      [84], [#name("TODOROVIC Andrea")], [#age(29)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2476*], [#delta(0)],
      [85], [#name("LIN Ye")], [#age(25)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2474*], [#delta(0)],
      [86], [#name("杨蕙菁")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2472*], [#delta(0)],
      [87], [#name("JEGER Mateja")], [#age(26)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2465*], [#delta(0)],
      [88], [#name("邵杰妮")], [#age(27)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2464*], [#delta(0)],
      [89], [#name("苏蒂尔塔 穆克吉")], [#age(26)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2463*], [#delta(0)],
      [90], [#name("SHCHERBATYKH Valeria")], [#age(23)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2462*], [#delta(0)],
      [91], [#name("伯纳黛特 斯佐科斯")], [#age(26)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2460*], [#delta(0)],
      [92], [#name("王 艾米")], [#age(19)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2457*], [#delta(0)],
      [93], [#name("ABRAAMIAN Elizabet")], [#age(18)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2457*], [#delta(24)],
      [94], [#name("高桥 布鲁娜")], [#age(21)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2456*], [#delta(-1)],
      [95], [#name("CIOBANU Irina")], [#age(26)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2454*], [#delta(-1)],
      [96], [#name("玛利亚 肖")], [#age(27)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2453*], [#delta(-1)],
      [97], [#name("奥拉万 帕拉南")], [#age(24)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2447*], [#delta(-1)],
      [98], [#name("BILENKO Tetyana")], [#age(38)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2443*], [#delta(-1)],
      [99], [#name("MATELOVA Hana")], [#age(31)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2441*], [#delta(-1)],
      [100], [#name("斯丽贾 阿库拉")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2439*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("LAM Yee Lok")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2439*], [#delta(-1)],
      [102], [#name("VOROBEVA Olga")], [#age(31)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2429*], [#delta(-1)],
      [103], [#name("蒂娜 梅谢芙")], [#age(27)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2429*], [#delta(-1)],
      [104], [#name("LIU Juan")], [#age(36)], [#assoc("USA")], [#left], [#penhold], [#attack], [*2427*], [#delta(-1)],
      [105], [#name("LENG Yutong")], [#age(17)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2417*], [#delta(-1)],
      [106], [#name("ZAHARIA Elena")], [#age(17)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2416*], [#delta(3)],
      [107], [#name("MIGOT Marie")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2415*], [#delta(-2)],
      [108], [#name("金娜英")], [#age(16)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2413*], [#delta(-2)],
      [109], [#name("WEGRZYN Anna")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2407*], [#delta(-2)],
      [110], [#name("LAY Jian Fang")], [#age(48)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2407*], [#delta(-2)],
      [111], [#name("BRATEYKO Solomiya")], [#age(22)], [#assoc("UKR")], [#left], [#shakehand], [#attack], [*2405*], [#delta(-1)],
      [112], [#name("齐菲")], [#age(21)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2403*], [#delta(-1)],
      [113], [#name("ZARIF Audrey")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2396*], [#delta(-1)],
      [114], [#name("MANTZ Chantal")], [#age(25)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2395*], [#delta(-1)],
      [115], [#name("TOMANOVSKA Katerina")], [#age(26)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2392*], [#delta(-1)],
      [116], [#name("MALOBABIC Ivana")], [#age(41)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2390*], [#delta(-1)],
      [117], [#name("DVORAK Galia")], [#age(33)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2387*], [#delta(-1)],
      [118], [#name("LI Ching Wan")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2382*], [#delta(0)],
      [119], [#name("ZHANG Sofia-Xuan")], [#age(22)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2381*], [#delta(0)],
      [120], [#name("TOLIOU Aikaterini")], [#age(26)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2379*], [#delta(0)],
      [121], [#name("WEGRZYN Katarzyna")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2379*], [#delta(0)],
      [122], [#name("CHASSELIN Pauline")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2378*], [#delta(0)],
      [123], [#name("乔治娜 波塔")], [#age(36)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2376*], [#delta(0)],
      [124], [#name("LUTZ Camille")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2376*], [#delta(25)],
      [125], [#name("MADARASZ Dora")], [#age(28)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2374*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("DRAGOMAN Andreea")], [#age(21)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2374*], [#delta(-1)],
      [127], [#name("HO Tin-Tin")], [#age(23)], [#assoc("GBR")], [#right], [#penhold], [#attack], [*2371*], [#delta(-1)],
      [128], [#name("PLAIAN Tania")], [#age(20)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2368*], [#delta(-1)],
      [129], [#name("VORONINA Vlada")], [#age(17)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2359*], [#delta(0)],
      [130], [#name("KOLISH Anastasia")], [#age(20)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2356*], [#delta(0)],
      [131], [#name("WAN Yuan")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2356*], [#delta(0)],
      [132], [#name("RYU Hanna")], [#age(19)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2355*], [#delta(0)],
      [133], [#name("张本美和")], [#age(13)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2353*], [#delta(0)],
      [134], [#name("PARTYKA Natalia")], [#age(32)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2353*], [#delta(0)],
      [135], [#name("SUNG Rachel")], [#age(17)], [#assoc("USA")], [#left], [#shakehand], [#attack], [*2351*], [#delta(0)],
      [136], [#name("KAMATH Archana")], [#age(21)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2350*], [#delta(0)],
      [137], [#name("SAWETTABUT Jinnipa")], [#age(21)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2350*], [#delta(0)],
      [138], [#name("WANG Tianyi")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2348*], [#delta(0)],
      [139], [#name("LI Yuqi")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2346*], [#delta(0)],
      [140], [#name("MISCHEK Karoline")], [#age(23)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2346*], [#delta(0)],
      [141], [#name("LIU Yuan")], [#age(36)], [#assoc("AUT")], [#right], [#penhold], [#attack], [*2346*], [#delta(0)],
      [142], [#name("LEE Daeun")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2343*], [#delta(0)],
      [143], [#name("HURSEY Anna")], [#age(15)], [#assoc("WAL")], [#right], [#shakehand], [#attack], [*2342*], [#delta(-15)],
      [144], [#name("VISHNIAKOVA Olga")], [#age(20)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2341*], [#delta(-1)],
      [145], [#name("ALTINKAYA Sibel")], [#age(28)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2339*], [#delta(0)],
      [146], [#name("CHAU Wing Sze")], [#age(19)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2339*], [#delta(0)],
      [147], [#name("SILVA Yadira")], [#age(36)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2336*], [#delta(0)],
      [148], [#name("SU Pei-Ling")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2336*], [#delta(0)],
      [149], [#name("LOEUILLETTE Stephanie")], [#age(29)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2334*], [#delta(1)],
      [150], [#name("YAMADA Jessica")], [#age(32)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2333*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("GUISNEL Oceane")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2332*], [#delta(1)],
      [152], [#name("BALINT Bernadett")], [#age(25)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2330*], [#delta(1)],
      [153], [#name("LUPULESKU Izabela")], [#age(22)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2330*], [#delta(1)],
      [154], [#name("KUMAHARA Luca")], [#age(26)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2329*], [#delta(1)],
      [155], [#name("PATKAR Madhurika")], [#age(34)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2324*], [#delta(1)],
      [156], [#name("CHOI Haeeun")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2319*], [#delta(1)],
      [157], [#name("安妮特 考夫曼")], [#age(15)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2316*], [#delta(13)],
      [158], [#name("MALININA Natalia")], [#age(19)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2314*], [#delta(-14)],
      [159], [#name("KISEL Darya")], [#age(19)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2314*], [#delta(46)],
      [160], [#name("KHETKHUAN Tamolwan")], [#age(24)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2306*], [#delta(-1)],
      [161], [#name("HUANG Yu-Wen")], [#age(25)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2305*], [#delta(-1)],
      [162], [#name("TOMANOVA Tamara")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2305*], [#delta(-1)],
      [163], [#name("艾希卡 穆克吉")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2305*], [#delta(-1)],
      [164], [#name("SLAUTINA Arina")], [#age(18)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2303*], [#delta(0)],
      [165], [#name("GAUTHIER Lucie")], [#age(21)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2302*], [#delta(0)],
      [166], [#name("BERGAND Filippa")], [#age(22)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2302*], [#delta(0)],
      [167], [#name("SURJAN Sabina")], [#age(21)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2301*], [#delta(0)],
      [168], [#name("VIVARELLI Debora")], [#age(28)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2295*], [#delta(0)],
      [169], [#name("PAVLOVIC Andrea")], [#age(21)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2293*], [#delta(0)],
      [170], [#name("LUTZ Charlotte")], [#age(16)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2292*], [#delta(77)],
      [171], [#name("SOLJA Amelie")], [#age(31)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2290*], [#delta(0)],
      [172], [#name("STEFANSKA Kinga")], [#age(41)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2289*], [#delta(0)],
      [173], [#name("SCHREINER Franziska")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2289*], [#delta(0)],
      [174], [#name("张墨")], [#age(32)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2287*], [#delta(0)],
      [175], [#name("COK Isa")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2284*], [#delta(21)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("MITROFAN Luciana")], [#age(18)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2282*], [#delta(36)],
      [177], [#name("CHERNYAVSKAYA Ekaterina")], [#age(25)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2282*], [#delta(-2)],
      [178], [#name("TRIGOLOS Daria")], [#age(22)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2282*], [#delta(-2)],
      [179], [#name("PICCOLIN Giorgia")], [#age(25)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2280*], [#delta(-2)],
      [180], [#name("HSU Yi-Chen")], [#age(19)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2279*], [#delta(-2)],
      [181], [#name("DYMYTRENKO Anastasiya")], [#age(19)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2279*], [#delta(34)],
      [182], [#name("ARAPOVIC Hana")], [#age(17)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2278*], [#delta(7)],
      [183], [#name("JAZBEC Ida")], [#age(27)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2278*], [#delta(-4)],
      [184], [#name("FORT Nolwenn")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2277*], [#delta(-4)],
      [185], [#name("DIAZ Melanie")], [#age(25)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2275*], [#delta(-4)],
      [186], [#name("ROY Krittwika")], [#age(27)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2275*], [#delta(-4)],
      [187], [#name("RILISKYTE Kornelija")], [#age(18)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2274*], [#delta(0)],
      [188], [#name("NAGYVARADI Mercedes")], [#age(27)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2274*], [#delta(-5)],
      [189], [#name("JOKIC Tijana")], [#age(21)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2272*], [#delta(-5)],
      [190], [#name("BARAVOK Katsiaryna")], [#age(26)], [#assoc("BLR")], [#left], [#shakehand], [#attack], [*2266*], [#delta(-5)],
      [191], [#name("KLEE Sophia")], [#age(18)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2266*], [#delta(-33)],
      [192], [#name("HARAC Ece")], [#age(19)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2265*], [#delta(-29)],
      [193], [#name("EDEM Offiong")], [#age(35)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2264*], [#delta(-7)],
      [194], [#name("SINGEORZAN Ioana")], [#age(17)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2262*], [#delta(59)],
      [195], [#name("HO Ying")], [#age(26)], [#assoc("MAS")], [#right], [#shakehand], [#attack], [*2262*], [#delta(-7)],
      [196], [#name("LAURENTI Jamila")], [#age(19)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2259*], [#delta(-5)],
      [197], [#name("吴咏琳")], [#age(18)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2258*], [#delta(-7)],
      [198], [#name("VEGA Paulina")], [#age(37)], [#assoc("CHI")], [#left], [#shakehand], [#attack], [*2257*], [#delta(-6)],
      [199], [#name("SHINOHARA Yura")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2256*], [#delta(-6)],
      [200], [#name("CAI Fong-En")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2255*], [#delta(-6)],
    )
  )
