#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("陈梦")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3193*], [#delta(0)],
      [2], [#name("孙颖莎")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3095*], [#delta(0)],
      [3], [#name("王曼昱")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3043*], [#delta(0)],
      [4], [#name("刘诗雯")], [#age(30)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2950*], [#delta(0)],
      [5], [#name("王艺迪")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2941*], [#delta(0)],
      [6], [#name("伊藤美诚")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2891*], [#delta(0)],
      [7], [#name("早田希娜")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2875*], [#delta(3)],
      [8], [#name("钱天一")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2864*], [#delta(-1)],
      [9], [#name("陈幸同")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2862*], [#delta(-1)],
      [10], [#name("张瑞")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2829*], [#delta(-1)],
      [11], [#name("田志希")], [#age(29)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2801*], [#delta(0)],
      [12], [#name("桥本帆乃香")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2786*], [#delta(0)],
      [13], [#name("平野美宇")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2777*], [#delta(1)],
      [14], [#name("杜凯琹")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2768*], [#delta(-1)],
      [15], [#name("苏慧音")], [#age(23)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2749*], [#delta(1)],
      [16], [#name("佐藤瞳")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2733*], [#delta(-1)],
      [17], [#name("范思琦")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2726*], [#delta(0)],
      [18], [#name("韩莹")], [#age(38)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2725*], [#delta(0)],
      [19], [#name("何卓佳")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2724*], [#delta(0)],
      [20], [#name("长崎美柚")], [#age(19)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2721*], [#delta(6)],
      [21], [#name("石洵瑶")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2718*], [#delta(-1)],
      [22], [#name("加藤美优")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2712*], [#delta(1)],
      [23], [#name("刘炜珊")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2711*], [#delta(1)],
      [24], [#name("芝田沙季")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2706*], [#delta(-2)],
      [25], [#name("素塔西尼 萨维塔布特")], [#age(27)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2694*], [#delta(4)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("木原美悠")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2692*], [#delta(1)],
      [27], [#name("妮娜 米特兰姆")], [#age(25)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2692*], [#delta(19)],
      [28], [#name("安藤南")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2690*], [#delta(0)],
      [29], [#name("石川佳纯")], [#age(28)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2684*], [#delta(1)],
      [30], [#name("杨晓欣")], [#age(33)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2681*], [#delta(-9)],
      [31], [#name("梁夏银")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2671*], [#delta(-6)],
      [32], [#name("申裕斌")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2665*], [#delta(9)],
      [33], [#name("金河英")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2662*], [#delta(-1)],
      [34], [#name("刘佳")], [#age(39)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2660*], [#delta(-1)],
      [35], [#name("蒯曼")], [#age(17)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2652*], [#delta(-1)],
      [36], [#name("冯天薇")], [#age(35)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2647*], [#delta(-1)],
      [37], [#name("陈熠")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2641*], [#delta(0)],
      [38], [#name("玛格丽塔 佩索茨卡")], [#age(30)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2639*], [#delta(17)],
      [39], [#name("小盐遥菜")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2637*], [#delta(-1)],
      [40], [#name("单晓娜")], [#age(38)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2625*], [#delta(0)],
      [41], [#name("陈思羽")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2622*], [#delta(-10)],
      [42], [#name("傅玉")], [#age(43)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2622*], [#delta(-6)],
      [43], [#name("森樱")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2617*], [#delta(-1)],
      [44], [#name("吴洋晨")], [#age(19)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2611*], [#delta(-1)],
      [45], [#name("袁嘉楠")], [#age(36)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2598*], [#delta(0)],
      [46], [#name("崔孝珠")], [#age(23)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2598*], [#delta(17)],
      [47], [#name("郑怡静")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2595*], [#delta(0)],
      [48], [#name("萨宾 温特")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2594*], [#delta(0)],
      [49], [#name("曾尖")], [#age(25)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2589*], [#delta(-5)],
      [50], [#name("徐孝元")], [#age(34)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2581*], [#delta(-11)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("李皓晴")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2571*], [#delta(-1)],
      [52], [#name("索菲亚 波尔卡诺娃")], [#age(27)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2567*], [#delta(-1)],
      [53], [#name("李时温")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2557*], [#delta(-4)],
      [54], [#name("琳达 伯格斯特隆")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2557*], [#delta(0)],
      [55], [#name("玛妮卡 巴特拉")], [#age(26)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2552*], [#delta(1)],
      [56], [#name("洪剑芳")], [#age(48)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2546*], [#delta(1)],
      [57], [#name("李恩惠")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2545*], [#delta(1)],
      [58], [#name("肖瑶茜")], [#age(27)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2537*], [#delta(3)],
      [59], [#name("奥拉万 帕拉南")], [#age(24)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2536*], [#delta(3)],
      [60], [#name("阿查娜 卡马特")], [#age(21)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2536*], [#delta(44)],
      [61], [#name("佩特丽莎 索尔佳")], [#age(27)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2534*], [#delta(3)],
      [62], [#name("郑先知")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2534*], [#delta(-3)],
      [63], [#name("柳恩钟")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2533*], [#delta(2)],
      [64], [#name("阿迪娜 迪亚科努")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2532*], [#delta(2)],
      [65], [#name("伊丽莎白 阿布拉米安")], [#age(18)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2530*], [#delta(-13)],
      [66], [#name("伯纳黛特 斯佐科斯")], [#age(26)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2519*], [#delta(39)],
      [67], [#name("倪夏莲")], [#age(58)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2517*], [#delta(-14)],
      [68], [#name("刘馨尹")], [#age(34)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2515*], [#delta(1)],
      [69], [#name("吴玥")], [#age(31)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2510*], [#delta(1)],
      [70], [#name("吴颖岚")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2510*], [#delta(9)],
      [71], [#name("李昱谆")], [#age(24)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2499*], [#delta(2)],
      [72], [#name("玛丽亚 泰拉科娃")], [#age(20)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2498*], [#delta(-12)],
      [73], [#name("斯丽贾 阿库拉")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2495*], [#delta(12)],
      [74], [#name("张安")], [#age(25)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2494*], [#delta(1)],
      [75], [#name("娜塔莉亚 巴约尔")], [#age(24)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2493*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("朱成竹")], [#age(24)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2492*], [#delta(-9)],
      [77], [#name("邵杰妮")], [#age(27)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2492*], [#delta(-5)],
      [78], [#name("苏蒂尔塔 穆克吉")], [#age(26)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2490*], [#delta(-1)],
      [79], [#name("金星宁")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2480*], [#delta(1)],
      [80], [#name("林叶")], [#age(25)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2480*], [#delta(2)],
      [81], [#name("杨蕙菁")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2472*], [#delta(0)],
      [82], [#name("布鲁娜 高桥")], [#age(21)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2467*], [#delta(42)],
      [83], [#name("马泰娅 耶格尔")], [#age(26)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2465*], [#delta(0)],
      [84], [#name("王艾米")], [#age(19)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2462*], [#delta(3)],
      [85], [#name("张墨")], [#age(32)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2461*], [#delta(-14)],
      [86], [#name("亚娜 诺斯科娃")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2457*], [#delta(-18)],
      [87], [#name("汉娜 哈珀诺娃")], [#age(36)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2455*], [#delta(6)],
      [88], [#name("伊琳娜 乔巴努")], [#age(26)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2455*], [#delta(1)],
      [89], [#name("奥黛丽 扎里夫")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2455*], [#delta(1)],
      [90], [#name("安德里亚 托多罗维奇")], [#age(29)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2451*], [#delta(1)],
      [91], [#name("瓦列里娅 谢尔巴特赫")], [#age(23)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2449*], [#delta(-7)],
      [92], [#name("埃列娜 扎哈里亚")], [#age(17)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2444*], [#delta(9)],
      [93], [#name("特蒂亚娜 比连科")], [#age(38)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2443*], [#delta(1)],
      [94], [#name("莎拉 德努特")], [#age(29)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2439*], [#delta(-2)],
      [95], [#name("卡米耶 卢茨")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2430*], [#delta(24)],
      [96], [#name("阿德里安娜 迪亚兹")], [#age(21)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2427*], [#delta(0)],
      [97], [#name("雷切尔 莫雷特")], [#age(32)], [#assoc("SUI")], [#left], [#shakehand], [#attack], [*2427*], [#delta(-9)],
      [98], [#name("丹妮拉 多迪安")], [#age(33)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2425*], [#delta(-1)],
      [99], [#name("卢卡 熊原")], [#age(26)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2421*], [#delta(-1)],
      [100], [#name("奥尔加 沃罗贝娃")], [#age(31)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2418*], [#delta(-14)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("LENG Yutong")], [#age(17)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2417*], [#delta(-2)],
      [102], [#name("金娜英")], [#age(16)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2415*], [#delta(-2)],
      [103], [#name("波琳娜 米哈伊洛娃")], [#age(35)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2413*], [#delta(-25)],
      [104], [#name("汉娜 马特洛娃")], [#age(31)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2413*], [#delta(33)],
      [105], [#name("MIGOT Marie")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2412*], [#delta(-3)],
      [106], [#name("齐菲")], [#age(21)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2404*], [#delta(0)],
      [107], [#name("安娜 韦格任")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2403*], [#delta(0)],
      [108], [#name("布里特 伊尔兰德")], [#age(27)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2399*], [#delta(-34)],
      [109], [#name("巴尔博拉 巴拉佐娃")], [#age(29)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2397*], [#delta(-6)],
      [110], [#name("林依诺")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2395*], [#delta(-15)],
      [111], [#name("索洛米娅 布拉捷伊科")], [#age(22)], [#assoc("UKR")], [#left], [#shakehand], [#attack], [*2394*], [#delta(-3)],
      [112], [#name("伊万娜 马洛巴比奇")], [#age(41)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2390*], [#delta(-2)],
      [113], [#name("克里斯蒂娜 卡尔伯格")], [#age(21)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2389*], [#delta(-1)],
      [114], [#name("卡塔日娜 文格任")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2387*], [#delta(-1)],
      [115], [#name("李清韵")], [#age(27)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2382*], [#delta(0)],
      [116], [#name("张璇")], [#age(22)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2381*], [#delta(0)],
      [117], [#name("SUNG Rachel")], [#age(17)], [#assoc("USA")], [#left], [#shakehand], [#attack], [*2377*], [#delta(15)],
      [118], [#name("夏洛特 卢茨")], [#age(16)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2376*], [#delta(47)],
      [119], [#name("安德烈娅 德拉戈曼")], [#age(21)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2374*], [#delta(1)],
      [120], [#name("尚塔尔 曼茨")], [#age(25)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2374*], [#delta(2)],
      [121], [#name("波琳 沙斯兰")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2374*], [#delta(-4)],
      [122], [#name("汉娜 高达")], [#age(14)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2373*], [#delta(75)],
      [123], [#name("塔尼娅 普莱安")], [#age(20)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2368*], [#delta(0)],
      [124], [#name("MISCHEK Karoline")], [#age(23)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2360*], [#delta(12)],
      [125], [#name("普利蒂卡 帕瓦德")], [#age(17)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2359*], [#delta(-7)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("弗拉达 沃罗宁娜")], [#age(17)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2357*], [#delta(-1)],
      [127], [#name("加利娅 德沃拉克")], [#age(33)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2357*], [#delta(-1)],
      [128], [#name("苏珮绫")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2356*], [#delta(16)],
      [129], [#name("KOLISH Anastasia")], [#age(20)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2356*], [#delta(-2)],
      [130], [#name("DOBREVA Polina")], [#age(29)], [#assoc("BUL")], [#right], [#shakehand], [#attack], [*2355*], [#delta(-2)],
      [131], [#name("蒂娜 梅谢芙")], [#age(27)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2355*], [#delta(-22)],
      [132], [#name("柳韩娜")], [#age(19)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2354*], [#delta(-3)],
      [133], [#name("张本美和")], [#age(13)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2353*], [#delta(-3)],
      [134], [#name("万远")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2351*], [#delta(-3)],
      [135], [#name("金妮帕 萨维塔布特")], [#age(21)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2349*], [#delta(-2)],
      [136], [#name("乔治娜 波塔")], [#age(36)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2349*], [#delta(24)],
      [137], [#name("王添艺")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2348*], [#delta(-3)],
      [138], [#name("LI Yuqi")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2346*], [#delta(-3)],
      [139], [#name("李多恩")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2343*], [#delta(-1)],
      [140], [#name("安娜 赫西")], [#age(15)], [#assoc("WAL")], [#right], [#shakehand], [#attack], [*2343*], [#delta(-1)],
      [141], [#name("VISHNIAKOVA Olga")], [#age(20)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2341*], [#delta(-1)],
      [142], [#name("西贝尔 阿尔滕卡亚")], [#age(28)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2340*], [#delta(-1)],
      [143], [#name("CHAU Wing Sze")], [#age(19)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2338*], [#delta(-1)],
      [144], [#name("亚迪拉 席尔瓦")], [#age(36)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2337*], [#delta(-1)],
      [145], [#name("LABOSOVA Ema")], [#age(20)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2336*], [#delta(44)],
      [146], [#name("史蒂芬妮 洛伊莱")], [#age(29)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2334*], [#delta(0)],
      [147], [#name("奥塞阿娜 古伊斯内尔")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2332*], [#delta(0)],
      [148], [#name("艾卡特里尼 托利乌")], [#age(26)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2332*], [#delta(-37)],
      [149], [#name("TOMANOVSKA Katerina")], [#age(26)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2331*], [#delta(-1)],
      [150], [#name("伊莎贝拉 卢普列斯库")], [#age(22)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2330*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("TRIGOLOS Daria")], [#age(22)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2328*], [#delta(-1)],
      [152], [#name("奥菲昂 埃德姆")], [#age(35)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2325*], [#delta(-31)],
      [153], [#name("KLEE Sophia")], [#age(18)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2325*], [#delta(30)],
      [154], [#name("DYMYTRENKO Anastasiya")], [#age(19)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2323*], [#delta(-3)],
      [155], [#name("PATKAR Madhurika")], [#age(34)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2322*], [#delta(-3)],
      [156], [#name("伊丽莎白 萨马拉")], [#age(32)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2322*], [#delta(-42)],
      [157], [#name("KISEL Darya")], [#age(19)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2319*], [#delta(-12)],
      [158], [#name("崔海恩")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2319*], [#delta(-5)],
      [159], [#name("MALININA Natalia")], [#age(19)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2318*], [#delta(-3)],
      [160], [#name("黄郁雯")], [#age(25)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2318*], [#delta(-1)],
      [161], [#name("萨比娜 苏尔扬")], [#age(21)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2316*], [#delta(-7)],
      [162], [#name("安妮特 考夫曼")], [#age(15)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2315*], [#delta(-7)],
      [163], [#name("GAUTHIER Lucie")], [#age(21)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2314*], [#delta(-6)],
      [164], [#name("多拉 马达拉斯")], [#age(28)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2313*], [#delta(67)],
      [165], [#name("艾希卡 穆克吉")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2305*], [#delta(-7)],
      [166], [#name("菲利帕 贝里安德")], [#age(22)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2302*], [#delta(-5)],
      [167], [#name("阿林娜 斯劳京娜")], [#age(18)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2302*], [#delta(-5)],
      [168], [#name("COK Isa")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2302*], [#delta(0)],
      [169], [#name("娜塔莉亚 帕尔蒂卡")], [#age(32)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2294*], [#delta(-6)],
      [170], [#name("弗兰琪斯卡 施莱纳")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2292*], [#delta(-6)],
      [171], [#name("艾米丽 索尔佳")], [#age(31)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2291*], [#delta(-5)],
      [172], [#name("焦尔吉娅 皮科林")], [#age(25)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2290*], [#delta(-5)],
      [173], [#name("金加 斯特凡斯卡")], [#age(41)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2289*], [#delta(-4)],
      [174], [#name("哈娜 阿拉波维奇")], [#age(17)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2288*], [#delta(2)],
      [175], [#name("PAVLOVIC Andrea")], [#age(21)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2285*], [#delta(-5)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("梅塞德丝 纳吉瓦劳迪")], [#age(27)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2284*], [#delta(-5)],
      [177], [#name("HSU Yi-Chen")], [#age(19)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2279*], [#delta(-4)],
      [178], [#name("SHAHSAVARI Neda")], [#age(35)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2279*], [#delta(64)],
      [179], [#name("BARAVOK Katsiaryna")], [#age(26)], [#assoc("BLR")], [#left], [#shakehand], [#attack], [*2278*], [#delta(-5)],
      [180], [#name("FORT Nolwenn")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2277*], [#delta(-3)],
      [181], [#name("JAZBEC Ida")], [#age(27)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2276*], [#delta(-3)],
      [182], [#name("MITROFAN Luciana")], [#age(18)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2275*], [#delta(-10)],
      [183], [#name("ROY Krittwika")], [#age(27)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2275*], [#delta(-4)],
      [184], [#name("RILISKYTE Kornelija")], [#age(18)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2275*], [#delta(-4)],
      [185], [#name("迪亚 奇塔莱")], [#age(18)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2274*], [#delta(-4)],
      [186], [#name("HARTBRICH Leonie")], [#age(22)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2270*], [#delta(-4)],
      [187], [#name("何天天")], [#age(23)], [#assoc("GBR")], [#right], [#penhold], [#attack], [*2270*], [#delta(-12)],
      [188], [#name("埃杰 哈拉奇")], [#age(19)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2265*], [#delta(-4)],
      [189], [#name("LAURENTI Jamila")], [#age(19)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2264*], [#delta(-4)],
      [190], [#name("HO Ying")], [#age(26)], [#assoc("MAS")], [#right], [#shakehand], [#attack], [*2262*], [#delta(-3)],
      [191], [#name("YAMADA Jessica")], [#age(32)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2260*], [#delta(-3)],
      [192], [#name("吴咏琳")], [#age(18)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2258*], [#delta(-2)],
      [193], [#name("亚沙斯维尼 戈尔帕德")], [#age(17)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2257*], [#delta(63)],
      [194], [#name("SHINOHARA Yura")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2256*], [#delta(-3)],
      [195], [#name("CAI Fong-En")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2255*], [#delta(-3)],
      [196], [#name("LEE Yeonhui")], [#age(17)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2255*], [#delta(-3)],
      [197], [#name("ALHODABY Mariam")], [#age(21)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2253*], [#delta(107)],
      [198], [#name("SEVCIKOVA Marketa")], [#age(23)], [#assoc("CZE")], [#right], [#shakehand], [#defense], [*2253*], [#delta(-4)],
      [199], [#name("JOKIC Tijana")], [#age(21)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2251*], [#delta(-4)],
      [200], [#name("CHERNYAVSKAYA Ekaterina")], [#age(25)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2251*], [#delta(-4)],
    )
  )
