#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("马龙")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3067*], [#delta(0)],
      [2], [#name("王励勤")], [#age(32)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3013*], [#delta(0)],
      [3], [#name("马琳")], [#age(30)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2932*], [#delta(6)],
      [4], [#name("郝帅")], [#age(27)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2901*], [#delta(-1)],
      [5], [#name("许昕")], [#age(20)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*2898*], [#delta(-1)],
      [6], [#name("张继科")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2895*], [#delta(0)],
      [7], [#name("王皓")], [#age(27)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2892*], [#delta(-2)],
      [8], [#name("水谷隼")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2886*], [#delta(9)],
      [9], [#name("蒂姆 波尔")], [#age(29)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2870*], [#delta(2)],
      [10], [#name("朱世赫")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2856*], [#delta(-2)],
      [11], [#name("弗拉基米尔 萨姆索诺夫")], [#age(34)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2845*], [#delta(-4)],
      [12], [#name("陈玘")], [#age(26)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2836*], [#delta(-2)],
      [13], [#name("庄智渊")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2760*], [#delta(7)],
      [14], [#name("米凯尔 梅兹")], [#age(29)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2740*], [#delta(-1)],
      [15], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(30)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2740*], [#delta(1)],
      [16], [#name("迪米特里 奥恰洛夫")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2710*], [#delta(-4)],
      [17], [#name("蒂亚戈 阿波罗尼亚")], [#age(24)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2694*], [#delta(20)],
      [18], [#name("李静")], [#age(35)], [#assoc("HKG")], [?], [?], [?], [*2675*], [#delta(28)],
      [19], [#name("陈卫星")], [#age(38)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2672*], [#delta(9)],
      [20], [#name("谭瑞午")], [#age(27)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2670*], [#delta(-1)],
      [21], [#name("克里斯蒂安 苏斯")], [#age(25)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2668*], [#delta(2)],
      [22], [#name("基里尔 斯卡奇科夫")], [#age(23)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2654*], [#delta(18)],
      [23], [#name("高礼泽")], [#age(34)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2649*], [#delta(-8)],
      [24], [#name("唐鹏")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2639*], [#delta(-6)],
      [25], [#name("方博")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2634*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("岸川圣也")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2632*], [#delta(12)],
      [27], [#name("李廷佑")], [#age(26)], [#assoc("KOR")], [#left], [#penhold], [#attack], [*2623*], [#delta(0)],
      [28], [#name("博扬 托基奇")], [#age(29)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2621*], [#delta(39)],
      [29], [#name("柳承敏")], [#age(28)], [#assoc("KOR")], [#right], [#penhold], [#attack], [*2619*], [#delta(-15)],
      [30], [#name("吉田海伟")], [#age(29)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2612*], [#delta(-9)],
      [31], [#name("尹在荣")], [#age(27)], [#assoc("KOR")], [?], [?], [?], [*2610*], [#delta(-1)],
      [32], [#name("闫安")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2609*], [#delta(-1)],
      [33], [#name("CHO Eonrae")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2604*], [#delta(3)],
      [34], [#name("SEO Hyundeok")], [#age(19)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2601*], [#delta(-1)],
      [35], [#name("上田仁")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2601*], [#delta(-1)],
      [36], [#name("阿列克谢 斯米尔诺夫")], [#age(33)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2595*], [#delta(6)],
      [37], [#name("吴尚垠")], [#age(33)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2592*], [#delta(-8)],
      [38], [#name("卡林尼科斯 格林卡")], [#age(38)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2590*], [#delta(1)],
      [39], [#name("PETO Zsolt")], [#age(23)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2590*], [#delta(20)],
      [40], [#name("金珉锡")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2576*], [#delta(4)],
      [41], [#name("JAKAB Janos")], [#age(24)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2573*], [#delta(16)],
      [42], [#name("佐兰 普里莫拉克")], [#age(41)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2568*], [#delta(3)],
      [43], [#name("阿德里安 克里桑")], [#age(30)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2563*], [#delta(87)],
      [44], [#name("郑荣植")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2558*], [#delta(5)],
      [45], [#name("罗伯特 加尔多斯")], [#age(31)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2555*], [#delta(2)],
      [46], [#name("SIMONCIK Josef")], [#age(30)], [#assoc("CZE")], [?], [?], [?], [*2553*], [#delta(330)],
      [47], [#name("维尔纳 施拉格")], [#age(38)], [#assoc("AUT")], [?], [?], [?], [*2548*], [#delta(-15)],
      [48], [#name("金赫峰")], [#age(25)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2547*], [#delta(23)],
      [49], [#name("LEE Jungsam")], [#age(26)], [#assoc("KOR")], [?], [?], [?], [*2546*], [#delta(4)],
      [50], [#name("KIM Junghoon")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2544*], [#delta(4)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("FEJER-KONNERTH Zoltan")], [#age(32)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2543*], [#delta(4)],
      [52], [#name("李尚洙")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2542*], [#delta(4)],
      [53], [#name("KOSIBA Daniel")], [#age(19)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2541*], [#delta(123)],
      [54], [#name("韩阳")], [#age(32)], [#assoc("JPN")], [?], [?], [?], [*2529*], [#delta(7)],
      [55], [#name("GERELL Par")], [#age(28)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2528*], [#delta(40)],
      [56], [#name("OYA Hidetoshi")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2527*], [#delta(6)],
      [57], [#name("CHTCHETININE Evgueni")], [#age(40)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2527*], [#delta(29)],
      [58], [#name("何志文")], [#age(48)], [#assoc("ESP")], [#left], [#penhold], [#attack], [*2525*], [#delta(6)],
      [59], [#name("约尔根 佩尔森")], [#age(44)], [#assoc("SWE")], [?], [?], [?], [*2520*], [#delta(6)],
      [60], [#name("尚坤")], [#age(20)], [#assoc("CHN")], [?], [?], [?], [*2519*], [#delta(6)],
      [61], [#name("VLASOV Grigory")], [#age(26)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2513*], [#delta(8)],
      [62], [#name("MACHADO Carlos")], [#age(30)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2512*], [#delta(44)],
      [63], [#name("巴斯蒂安 斯蒂格")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2510*], [#delta(-11)],
      [64], [#name("RUBTSOV Igor")], [#age(30)], [#assoc("RUS")], [?], [?], [?], [*2506*], [#delta(8)],
      [65], [#name("马克斯 弗雷塔斯")], [#age(22)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2502*], [#delta(28)],
      [66], [#name("LIU Song")], [#age(38)], [#assoc("ARG")], [?], [?], [?], [*2495*], [#delta(103)],
      [67], [#name("WANG Zengyi")], [#age(27)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2490*], [#delta(53)],
      [68], [#name("LIN Ju")], [#age(31)], [#assoc("DOM")], [?], [?], [?], [*2489*], [#delta(-8)],
      [69], [#name("高宁")], [#age(28)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2488*], [#delta(-34)],
      [70], [#name("JANG Song Man")], [#age(25)], [#assoc("PRK")], [?], [?], [?], [*2488*], [#delta(-44)],
      [71], [#name("塩野真人")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2484*], [#delta(3)],
      [72], [#name("安德烈 加奇尼")], [#age(24)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2483*], [#delta(-22)],
      [73], [#name("PLATONOV Pavel")], [#age(27)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2473*], [#delta(179)],
      [74], [#name("德米特里 佩罗普科夫")], [#age(30)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2473*], [#delta(-52)],
      [75], [#name("让 米歇尔 赛弗")], [#age(41)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2467*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("张钰")], [#age(29)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2465*], [#delta(-25)],
      [77], [#name("帕特里克 鲍姆")], [#age(23)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2464*], [#delta(1)],
      [78], [#name("RI Chol Guk")], [#age(25)], [#assoc("PRK")], [?], [?], [?], [*2462*], [#delta(1)],
      [79], [#name("VRABLIK Jiri")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2458*], [#delta(-3)],
      [80], [#name("SEREDA Peter")], [#age(26)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2457*], [#delta(20)],
      [81], [#name("LEE Jinkwon")], [#age(23)], [#assoc("KOR")], [?], [?], [?], [*2451*], [#delta(-1)],
      [82], [#name("阿德里安 马特内")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2449*], [#delta(-7)],
      [83], [#name("LEGOUT Christophe")], [#age(37)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2447*], [#delta(14)],
      [84], [#name("卢文 菲鲁斯")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2444*], [#delta(-3)],
      [85], [#name("江天一")], [#age(22)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2433*], [#delta(-37)],
      [86], [#name("HENZELL William")], [#age(28)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2432*], [#delta(26)],
      [87], [#name("亚历山大 卡拉卡谢维奇")], [#age(35)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2432*], [#delta(26)],
      [88], [#name("SVENSSON Robert")], [#age(27)], [#assoc("SWE")], [?], [?], [?], [*2431*], [#delta(4)],
      [89], [#name("KUZMIN Fedor")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-31)],
      [90], [#name("ERLANDSEN Geir")], [#age(34)], [#assoc("NOR")], [?], [?], [?], [*2428*], [#delta(-5)],
      [91], [#name("松平健太")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2428*], [#delta(-21)],
      [92], [#name("KEINATH Thomas")], [#age(33)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2424*], [#delta(-5)],
      [93], [#name("TREGLER Tomas")], [#age(20)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2418*], [#delta(28)],
      [94], [#name("PISTEJ Lubomir")], [#age(26)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2417*], [#delta(16)],
      [95], [#name("詹斯 伦德奎斯特")], [#age(31)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2416*], [#delta(-70)],
      [96], [#name("MONRAD Martin")], [#age(33)], [#assoc("DEN")], [?], [?], [?], [*2413*], [#delta(-8)],
      [97], [#name("VOSTES Yannick")], [#age(25)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2412*], [#delta(-7)],
      [98], [#name("YOKOYAMA Yuichi")], [#age(23)], [#assoc("JPN")], [?], [?], [?], [*2411*], [#delta(-9)],
      [99], [#name("MONTEIRO Joao")], [#age(27)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2409*], [#delta(-56)],
      [100], [#name("丹羽孝希")], [#age(16)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2403*], [#delta(-9)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("ILLAS Erik")], [#age(30)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2401*], [#delta(-24)],
      [102], [#name("LIVENTSOV Alexey")], [#age(29)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2393*], [#delta(-6)],
      [103], [#name("WOSIK Torben")], [#age(37)], [#assoc("GER")], [?], [?], [?], [*2392*], [#delta(-5)],
      [104], [#name("亚历山大 希巴耶夫")], [#age(20)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2390*], [#delta(4)],
      [105], [#name("KASAHARA Hiromitsu")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2390*], [#delta(-6)],
      [106], [#name("TSUBOI Gustavo")], [#age(25)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2388*], [#delta(39)],
      [107], [#name("LI Kewei")], [#age(30)], [#assoc("MLT")], [?], [?], [?], [*2388*], [#delta(-6)],
      [108], [#name("蒋澎龙")], [#age(34)], [#assoc("TPE")], [?], [?], [?], [*2385*], [#delta(-6)],
      [109], [#name("HUANG Sheng-Sheng")], [#age(23)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2384*], [#delta(5)],
      [110], [#name("彼得 科贝尔")], [#age(39)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2383*], [#delta(-69)],
      [111], [#name("KONECNY Tomas")], [#age(25)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2382*], [#delta(-8)],
      [112], [#name("达米安 艾洛伊")], [#age(41)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2382*], [#delta(-8)],
      [113], [#name("SUCH Bartosz")], [#age(27)], [#assoc("POL")], [?], [?], [?], [*2379*], [#delta(-50)],
      [114], [#name("斯蒂芬 门格尔")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2379*], [#delta(-9)],
      [115], [#name("PLACHY Josef")], [#age(39)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2378*], [#delta(-8)],
      [116], [#name("帕特里克 弗朗西斯卡")], [#age(18)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2378*], [#delta(-22)],
      [117], [#name("LIM Jaehyun")], [#age(25)], [#assoc("KOR")], [?], [?], [?], [*2375*], [#delta(-8)],
      [118], [#name("LAKEEV Vasily")], [#age(26)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2371*], [#delta(-7)],
      [119], [#name("寇磊")], [#age(23)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2371*], [#delta(239)],
      [120], [#name("WANG Jianan")], [#age(27)], [#assoc("CGO")], [?], [?], [?], [*2364*], [#delta(-5)],
      [121], [#name("TSE Ka Chun")], [#age(24)], [#assoc("HKG")], [?], [?], [?], [*2364*], [#delta(-5)],
      [122], [#name("SHIMOYAMA Takanori")], [#age(25)], [#assoc("JPN")], [?], [?], [?], [*2362*], [#delta(-5)],
      [123], [#name("MA Liang")], [#age(19)], [#assoc("SGP")], [?], [?], [?], [*2362*], [#delta(-5)],
      [124], [#name("TAKAKIWA Taku")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2359*], [#delta(-2)],
      [125], [#name("丁祥恩")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2358*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("STEPHENSEN Gudmundur")], [#age(28)], [#assoc("ISL")], [?], [?], [?], [*2357*], [#delta(1)],
      [127], [#name("雅罗斯列夫 扎姆登科")], [#age(22)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2346*], [#delta(7)],
      [128], [#name("DANIEL Artur")], [#age(28)], [#assoc("POL")], [?], [?], [?], [*2345*], [#delta(-4)],
      [129], [#name("CHIANG Hung-Chieh")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2345*], [#delta(-4)],
      [130], [#name("CANTERO Jesus")], [#age(28)], [#assoc("ESP")], [#right], [#penhold], [#attack], [*2342*], [#delta(147)],
      [131], [#name("OBESLO Michal")], [#age(21)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2341*], [#delta(-5)],
      [132], [#name("KOLAREK Tomislav")], [#age(22)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2339*], [#delta(181)],
      [133], [#name("SAKAMOTO Ryusuke")], [#age(26)], [#assoc("JPN")], [?], [?], [?], [*2336*], [#delta(-4)],
      [134], [#name("卢兹扬 布拉斯奇克")], [#age(36)], [#assoc("POL")], [?], [?], [?], [*2336*], [#delta(-3)],
      [135], [#name("奥马尔 阿萨尔")], [#age(19)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2335*], [#delta(88)],
      [136], [#name("梁柱恩")], [#age(31)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2332*], [#delta(-3)],
      [137], [#name("ANTHONY Amalraj")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2331*], [#delta(123)],
      [138], [#name("KIM Nam Chol")], [#age(22)], [#assoc("PRK")], [?], [?], [?], [*2330*], [#delta(15)],
      [139], [#name("GORAK Daniel")], [#age(27)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2328*], [#delta(0)],
      [140], [#name("CHOJNOWSKI Patryk")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2326*], [#delta(58)],
      [141], [#name("ROGIERS Benjamin")], [#age(21)], [#assoc("BEL")], [?], [?], [?], [*2325*], [#delta(135)],
      [142], [#name("YIN Hang")], [#age(15)], [#assoc("CHN")], [?], [?], [?], [*2324*], [#delta(-7)],
      [143], [#name("林高远")], [#age(15)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2324*], [#delta(-7)],
      [144], [#name("KOSOWSKI Jakub")], [#age(28)], [#assoc("POL")], [?], [?], [?], [*2318*], [#delta(-4)],
      [145], [#name("KIM Gangwoog")], [#age(21)], [#assoc("KOR")], [?], [?], [?], [*2317*], [#delta(-4)],
      [146], [#name("张一博")], [#age(25)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2316*], [#delta(16)],
      [147], [#name("MONTEIRO Thiago")], [#age(29)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2315*], [#delta(-4)],
      [148], [#name("JEVTOVIC Marko")], [#age(23)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2314*], [#delta(51)],
      [149], [#name("JUZBASIC Ivan")], [#age(30)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2312*], [#delta(131)],
      [150], [#name("PAZSY Ferenc")], [#age(36)], [#assoc("HUN")], [?], [?], [?], [*2312*], [#delta(25)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("GAVLAS Antonin")], [#age(25)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2306*], [#delta(-5)],
      [152], [#name("JOVER Sebastien")], [#age(35)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2303*], [#delta(-5)],
      [153], [#name("HAN Jimin")], [#age(21)], [#assoc("KOR")], [?], [?], [?], [*2301*], [#delta(-4)],
      [154], [#name("ACHANTA Sharath")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2299*], [#delta(-86)],
      [155], [#name("ZWICKL Daniel")], [#age(26)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2298*], [#delta(-5)],
      [156], [#name("LIU Zhongze")], [#age(22)], [#assoc("SGP")], [?], [?], [?], [*2297*], [#delta(-5)],
      [157], [#name("BOBOCICA Mihai")], [#age(24)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2296*], [#delta(-75)],
      [158], [#name("AKHLAGHPASAND Mohammadreza")], [#age(32)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2295*], [#delta(44)],
      [159], [#name("MATSUDAIRA Kenji")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2294*], [#delta(-5)],
      [160], [#name("YIANGOU Marios")], [#age(19)], [#assoc("CYP")], [#right], [#shakehand], [#attack], [*2292*], [#delta(155)],
      [161], [#name("SALIFOU Abdel-Kader")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2291*], [#delta(109)],
      [162], [#name("LASHIN Elsayed")], [#age(30)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2288*], [#delta(2)],
      [163], [#name("MATSUMOTO Cazuo")], [#age(25)], [#assoc("BRA")], [#left], [#penhold], [#attack], [*2287*], [#delta(33)],
      [164], [#name("艾曼纽 莱贝松")], [#age(22)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2285*], [#delta(-20)],
      [165], [#name("BARDON Michal")], [#age(32)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2285*], [#delta(-28)],
      [166], [#name("SILVA Andre")], [#age(21)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2284*], [#delta(-10)],
      [167], [#name("诺沙迪 阿拉米扬")], [#age(19)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2282*], [#delta(20)],
      [168], [#name("BENTSEN Allan")], [#age(42)], [#assoc("DEN")], [?], [?], [?], [*2281*], [#delta(-49)],
      [169], [#name("FAZEKAS Peter")], [#age(29)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2278*], [#delta(-10)],
      [170], [#name("LI Ahmet")], [#age(19)], [#assoc("TUR")], [#left], [#shakehand], [#attack], [*2276*], [#delta(-10)],
      [171], [#name("YANG Zi")], [#age(26)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2275*], [#delta(-88)],
      [172], [#name("PAPADIMITRIOU Dimitrios")], [#age(26)], [#assoc("GRE")], [?], [?], [?], [*2263*], [#delta(264)],
      [173], [#name("MEROTOHUN Monday")], [#age(33)], [#assoc("NGR")], [#right], [#shakehand], [#defense], [*2262*], [#delta(41)],
      [174], [#name("ELBEIALI Mohamed")], [#age(22)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2260*], [#delta(-6)],
      [175], [#name("陈建安")], [#age(19)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2257*], [#delta(8)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("DRINKHALL Paul")], [#age(20)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2257*], [#delta(-48)],
      [177], [#name("KIM Song Nam")], [#age(18)], [#assoc("PRK")], [?], [?], [?], [*2257*], [#delta(-7)],
      [178], [#name("BURGIS Matiss")], [#age(21)], [#assoc("LAT")], [#right], [#shakehand], [#attack], [*2251*], [#delta(-40)],
      [179], [#name("SIMONER Christoph")], [#age(27)], [#assoc("AUT")], [?], [?], [?], [*2249*], [#delta(-8)],
      [180], [#name("MADRID Marcos")], [#age(24)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2247*], [#delta(17)],
      [181], [#name("HABESOHN Daniel")], [#age(24)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2245*], [#delta(-18)],
      [182], [#name("CHENG Jingqi")], [#age(16)], [#assoc("CHN")], [?], [?], [?], [*2245*], [#delta(-9)],
      [183], [#name("CIHAK Marek")], [#age(36)], [#assoc("CZE")], [?], [?], [?], [*2244*], [#delta(-9)],
      [184], [#name("DURANSPAHIC Admir")], [#age(23)], [#assoc("BIH")], [#right], [#shakehand], [#attack], [*2244*], [#delta(406)],
      [185], [#name("SAHA Subhajit")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2241*], [#delta(78)],
      [186], [#name("HOYAMA Hugo")], [#age(41)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2241*], [#delta(-21)],
      [187], [#name("TUGWELL Finn")], [#age(34)], [#assoc("DEN")], [?], [?], [?], [*2239*], [#delta(-103)],
      [188], [#name("SIRUCEK Pavel")], [#age(18)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2234*], [#delta(33)],
      [189], [#name("OLEJNIK Martin")], [#age(38)], [#assoc("CZE")], [?], [?], [?], [*2232*], [#delta(-11)],
      [190], [#name("HU Bin")], [#age(28)], [#assoc("CGO")], [?], [?], [?], [*2231*], [#delta(-11)],
      [191], [#name("NASIRU Kazeem")], [#age(36)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2230*], [#delta(-11)],
      [192], [#name("HORVAT Mitja")], [#age(32)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2229*], [#delta(-11)],
      [193], [#name("CHOU Tung-Yu")], [#age(23)], [#assoc("TPE")], [?], [?], [?], [*2226*], [#delta(-38)],
      [194], [#name("FILIMON Lucian")], [#age(31)], [#assoc("ROU")], [?], [?], [?], [*2221*], [#delta(-12)],
      [195], [#name("SONG Hongyuan")], [#age(17)], [#assoc("CHN")], [?], [?], [?], [*2219*], [#delta(-10)],
      [196], [#name("VANG Bora")], [#age(23)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2219*], [#delta(495)],
      [197], [#name("TRAN Tuan Quynh")], [#age(27)], [#assoc("VIE")], [?], [?], [?], [*2219*], [NEW],
      [198], [#name("YORDANOV Teodor")], [#age(32)], [#assoc("BUL")], [#left], [#shakehand], [#attack], [*2218*], [#delta(73)],
      [199], [#name("TORIOLA Segun")], [#age(36)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2215*], [#delta(-13)],
      [200], [#name("FILIMON Andrei")], [#age(33)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2212*], [#delta(-12)],
    )
  )
