#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("刘诗雯")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2975*], [#delta(2)],
      [2], [#name("郭跃")], [#age(22)], [#assoc("CHN")], [?], [?], [?], [*2941*], [#delta(0)],
      [3], [#name("郭焱")], [#age(28)], [#assoc("CHN")], [?], [?], [?], [*2906*], [#delta(1)],
      [4], [#name("李晓霞")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2892*], [#delta(-3)],
      [5], [#name("范瑛")], [#age(24)], [#assoc("CHN")], [?], [?], [?], [*2871*], [#delta(0)],
      [6], [#name("丁宁")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2836*], [#delta(1)],
      [7], [#name("冯天薇")], [#age(24)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2813*], [#delta(5)],
      [8], [#name("冯亚兰")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2733*], [NEW],
      [9], [#name("高军")], [#age(41)], [#assoc("USA")], [?], [?], [?], [*2716*], [#delta(-1)],
      [10], [#name("福原爱")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2707*], [#delta(-4)],
      [11], [#name("金景娥")], [#age(33)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2692*], [#delta(0)],
      [12], [#name("武杨")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2680*], [#delta(2)],
      [13], [#name("李倩")], [#age(24)], [#assoc("POL")], [#right], [#shakehand], [#defense], [*2655*], [#delta(-3)],
      [14], [#name("姜华珺")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2649*], [#delta(6)],
      [15], [#name("丹妮拉 多迪安")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2639*], [#delta(4)],
      [16], [#name("姚彦")], [#age(22)], [#assoc("CHN")], [?], [?], [?], [*2637*], [#delta(1)],
      [17], [#name("文佳")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2634*], [#delta(1)],
      [18], [#name("唐汭序")], [#age(29)], [#assoc("KOR")], [?], [?], [?], [*2632*], [#delta(6)],
      [19], [#name("平野早矢香")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2618*], [#delta(13)],
      [20], [#name("黄怡桦")], [#age(26)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2617*], [#delta(16)],
      [21], [#name("石垣优香")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2616*], [#delta(-5)],
      [22], [#name("WANG Xuan")], [#age(21)], [#assoc("CHN")], [?], [?], [?], [*2613*], [#delta(1)],
      [23], [#name("沈燕飞")], [#age(31)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2601*], [#delta(2)],
      [24], [#name("石贺净")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2595*], [#delta(-11)],
      [25], [#name("李洁")], [#age(26)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2595*], [#delta(-4)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("克里斯蒂娜 托特")], [#age(36)], [#assoc("HUN")], [?], [?], [?], [*2590*], [#delta(-4)],
      [27], [#name("朴美英")], [#age(29)], [#assoc("KOR")], [?], [?], [?], [*2586*], [#delta(1)],
      [28], [#name("王越古")], [#age(30)], [#assoc("SGP")], [?], [?], [?], [*2586*], [#delta(-13)],
      [29], [#name("常晨晨")], [#age(24)], [#assoc("CHN")], [?], [?], [?], [*2583*], [#delta(1)],
      [30], [#name("玛丽娜 克拉夫琴科")], [#age(37)], [#assoc("ISR")], [#right], [#shakehand], [#attack], [*2574*], [#delta(1)],
      [31], [#name("李雪")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#defense], [*2573*], [#delta(42)],
      [32], [#name("柳絮飞")], [#age(29)], [#assoc("HKG")], [?], [?], [?], [*2567*], [#delta(3)],
      [33], [#name("李佳薇")], [#age(29)], [#assoc("SGP")], [?], [?], [?], [*2566*], [#delta(-7)],
      [34], [#name("埃尔卡 塞尔")], [#age(37)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2548*], [#delta(-1)],
      [35], [#name("林菱")], [#age(33)], [#assoc("HKG")], [?], [?], [?], [*2536*], [#delta(2)],
      [36], [#name("刘佳")], [#age(28)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2534*], [#delta(16)],
      [37], [#name("李晓丹")], [#age(20)], [#assoc("CHN")], [?], [?], [?], [*2526*], [#delta(-3)],
      [38], [#name("孙蓓蓓")], [#age(26)], [#assoc("SGP")], [?], [?], [?], [*2525*], [#delta(1)],
      [39], [#name("帖雅娜")], [#age(31)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2519*], [#delta(1)],
      [40], [#name("金仲")], [#age(21)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2516*], [#delta(1)],
      [41], [#name("于梦雨")], [#age(21)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2512*], [#delta(-12)],
      [42], [#name("吴雪")], [#age(30)], [#assoc("DOM")], [?], [?], [?], [*2506*], [#delta(0)],
      [43], [#name("福冈春菜")], [#age(26)], [#assoc("JPN")], [?], [?], [?], [*2500*], [#delta(0)],
      [44], [#name("李恩姬")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2500*], [#delta(1)],
      [45], [#name("李佼")], [#age(37)], [#assoc("NED")], [#left], [#penhold], [#attack], [*2496*], [#delta(-18)],
      [46], [#name("克里斯汀 朗")], [#age(25)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2496*], [#delta(0)],
      [47], [#name("维多利亚 帕夫洛维奇")], [#age(32)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2479*], [#delta(10)],
      [48], [#name("伊丽莎白 萨马拉")], [#age(21)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2475*], [#delta(15)],
      [49], [#name("木子")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2472*], [#delta(6)],
      [50], [#name("崔文渶")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2472*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("李瑨丽")], [#age(33)], [#assoc("NZL")], [?], [?], [?], [*2471*], [#delta(0)],
      [52], [#name("鲁塔 帕斯考斯基涅")], [#age(33)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2465*], [#delta(14)],
      [53], [#name("叶莲娜 库兹米娜")], [#age(21)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2463*], [#delta(1)],
      [54], [#name("伊韦塔 瓦切诺夫斯卡")], [#age(24)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2461*], [#delta(-7)],
      [55], [#name("伊娃 奥多罗娃")], [#age(31)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2460*], [#delta(-17)],
      [56], [#name("朱芳")], [#age(34)], [#assoc("ESP")], [?], [?], [?], [*2457*], [#delta(8)],
      [57], [#name("加利娅 德沃拉克")], [#age(22)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2454*], [#delta(1)],
      [58], [#name("张瑞")], [#age(31)], [#assoc("HKG")], [?], [?], [?], [*2447*], [#delta(-10)],
      [59], [#name("安娜玛丽亚 埃尔德利")], [#age(25)], [#assoc("SRB")], [#right], [#shakehand], [#defense], [*2440*], [#delta(-6)],
      [60], [#name("藤沼亚衣")], [#age(28)], [#assoc("JPN")], [?], [?], [?], [*2438*], [#delta(-16)],
      [61], [#name("金慧星")], [#age(17)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2435*], [#delta(-1)],
      [62], [#name("SANG Xu Stephanie")], [#age(24)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2434*], [#delta(-1)],
      [63], [#name("藤井宽子")], [#age(28)], [#assoc("JPN")], [?], [?], [?], [*2432*], [#delta(2)],
      [64], [#name("朴晟惠")], [#age(24)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2419*], [#delta(-2)],
      [65], [#name("侯美玲")], [#age(21)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2411*], [#delta(13)],
      [66], [#name("石川佳纯")], [#age(17)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2404*], [#delta(-17)],
      [67], [#name("科尔内莉亚 莫尔纳")], [#age(27)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2400*], [#delta(12)],
      [68], [#name("森园美咲")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2398*], [#delta(2)],
      [69], [#name("雷娜塔 斯特尔比科娃")], [#age(31)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2394*], [#delta(2)],
      [70], [#name("KANG Misoon")], [#age(17)], [#assoc("KOR")], [?], [?], [?], [*2391*], [#delta(4)],
      [71], [#name("韦罗妮卡 帕夫洛维奇")], [#age(32)], [#assoc("BLR")], [?], [?], [?], [*2389*], [#delta(-12)],
      [72], [#name("郑怡静")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2379*], [#delta(4)],
      [73], [#name("山梨有理")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2378*], [#delta(-17)],
      [74], [#name("伊雷妮 伊万坎")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2374*], [#delta(3)],
      [75], [#name("梁夏银")], [#age(16)], [#assoc("COR")], [#right], [#shakehand], [#attack], [*2363*], [#delta(26)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("李嫱冰")], [#age(25)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2362*], [#delta(-7)],
      [77], [#name("萨拉 拉米雷斯")], [#age(23)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2361*], [#delta(3)],
      [78], [#name("叶连娜 季米娜")], [#age(41)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2359*], [#delta(-11)],
      [79], [#name("米艾 斯科娃")], [#age(24)], [#assoc("DEN")], [#right], [#shakehand], [#attack], [*2359*], [#delta(-7)],
      [80], [#name("若宫三纱子")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2356*], [#delta(29)],
      [81], [#name("佩特拉 洛瓦斯")], [#age(30)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2355*], [#delta(-13)],
      [82], [#name("娜塔莉亚 帕尔蒂卡")], [#age(21)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2349*], [#delta(2)],
      [83], [#name("KIM Minhee")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2348*], [#delta(2)],
      [84], [#name("文炫晶")], [#age(26)], [#assoc("KOR")], [?], [?], [?], [*2345*], [#delta(2)],
      [85], [#name("徐孝元")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2344*], [#delta(-3)],
      [86], [#name("徐洁")], [#age(28)], [#assoc("POL")], [?], [?], [?], [*2344*], [#delta(-5)],
      [87], [#name("玛格丽塔 佩索茨卡")], [#age(19)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2340*], [#delta(3)],
      [88], [#name("安娜 蒂克米罗娃")], [#age(26)], [#assoc("RUS")], [?], [?], [?], [*2338*], [#delta(0)],
      [89], [#name("于国诗")], [#age(24)], [#assoc("HKG")], [?], [?], [?], [*2331*], [#delta(0)],
      [90], [#name("吴佳多")], [#age(33)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2327*], [#delta(-15)],
      [91], [#name("苗苗")], [#age(29)], [#assoc("AUS")], [?], [?], [?], [*2323*], [#delta(0)],
      [92], [#name("卡罗尔 格伦迪施")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2315*], [#delta(37)],
      [93], [#name("尼科莱塔 斯特凡诺娃")], [#age(26)], [#assoc("ITA")], [#left], [#shakehand], [#attack], [*2311*], [#delta(-6)],
      [94], [#name("乔治娜 波塔")], [#age(25)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2307*], [#delta(-2)],
      [95], [#name("谭文玲")], [#age(38)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2306*], [#delta(-12)],
      [96], [#name("纳迪娜 博尔迈尔")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2304*], [#delta(-2)],
      [97], [#name("顾玉婷")], [#age(15)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2300*], [#delta(-2)],
      [98], [#name("奥克萨娜 法德耶娃")], [#age(35)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2300*], [#delta(-5)],
      [99], [#name("HAN Hye Song")], [#age(22)], [#assoc("PRK")], [?], [?], [?], [*2299*], [#delta(-3)],
      [100], [#name("SHIM Serom")], [#age(23)], [#assoc("KOR")], [?], [?], [?], [*2299*], [#delta(-3)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("洪剑芳")], [#age(37)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2297*], [#delta(-3)],
      [102], [#name("卡塔日娜 格日博夫斯卡-弗朗茨")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2283*], [#delta(-3)],
      [103], [#name("樋浦令子")], [#age(26)], [#assoc("JPN")], [?], [?], [?], [*2280*], [#delta(-3)],
      [104], [#name("金贞弦")], [#age(25)], [#assoc("KOR")], [?], [?], [?], [*2279*], [#delta(-2)],
      [105], [#name("渡边裕子")], [#age(26)], [#assoc("JPN")], [?], [?], [?], [*2277*], [#delta(-2)],
      [106], [#name("萨宾 温特")], [#age(18)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2271*], [#delta(-2)],
      [107], [#name("塔玛拉 鲍罗斯")], [#age(33)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2270*], [#delta(28)],
      [108], [#name("TANIOKA Ayuka")], [#age(16)], [#assoc("JPN")], [?], [?], [?], [*2265*], [#delta(-2)],
      [109], [#name("佩特丽莎 索尔佳")], [#age(16)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2265*], [#delta(-4)],
      [110], [#name("高王")], [#age(30)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2257*], [#delta(-2)],
      [111], [#name("亚娜 诺斯科娃")], [#age(16)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2254*], [#delta(-4)],
      [112], [#name("SUN Jin")], [#age(30)], [#assoc("HKG")], [?], [?], [?], [*2248*], [#delta(-1)],
      [113], [#name("利娜 米西科尼特")], [#age(22)], [#assoc("LTU")], [?], [?], [?], [*2241*], [#delta(0)],
      [114], [#name("特蒂亚娜 比连科")], [#age(27)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2240*], [#delta(-4)],
      [115], [#name("玛丽亚 多尔吉赫")], [#age(23)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2238*], [#delta(-1)],
      [116], [#name("艾米丽 索尔佳")], [#age(20)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2236*], [#delta(-1)],
      [117], [#name("羡宜芳")], [#age(33)], [#assoc("FRA")], [#right], [#shakehand], [#defense], [*2229*], [#delta(-1)],
      [118], [#name("DESSAINT Aurore")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2228*], [#delta(-6)],
      [119], [#name("卡塔琳娜 加京斯卡")], [#age(40)], [#assoc("BUL")], [?], [?], [?], [*2227*], [#delta(-2)],
      [120], [#name("尤利娅 内库拉")], [#age(24)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2225*], [#delta(-2)],
      [121], [#name("陈梦")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2223*], [#delta(-1)],
      [122], [#name("张墨")], [#age(21)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2215*], [#delta(-1)],
      [123], [#name("刘媛")], [#age(25)], [#assoc("AUT")], [#right], [#penhold], [#attack], [*2213*], [#delta(-1)],
      [124], [#name("熊乃仪")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2209*], [#delta(-1)],
      [125], [#name("玛蒂尔达 埃克霍尔姆")], [#age(28)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2200*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("孙祯琦")], [#age(23)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2199*], [#delta(1)],
      [127], [#name("MOON Bosun")], [#age(24)], [#assoc("KOR")], [?], [?], [?], [*2198*], [#delta(1)],
      [128], [#name("孙杨")], [#age(27)], [#assoc("NZL")], [?], [?], [?], [*2195*], [#delta(2)],
      [129], [#name("伯纳黛特 斯佐科斯")], [#age(15)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2193*], [#delta(-4)],
      [130], [#name("卡琳娜 荣松")], [#age(31)], [#assoc("SWE")], [?], [?], [?], [*2191*], [#delta(1)],
      [131], [#name("安东尼娜 希曼斯卡")], [#age(27)], [#assoc("POL")], [?], [?], [?], [*2186*], [#delta(1)],
      [132], [#name("SHENG Dandan")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2181*], [#delta(1)],
      [133], [#name("吴颖岚")], [#age(18)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2180*], [#delta(1)],
      [134], [#name("阿尼萨拉 穆昂苏克")], [#age(34)], [#assoc("THA")], [?], [?], [?], [*2175*], [#delta(2)],
      [135], [#name("李皓晴")], [#age(18)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2167*], [#delta(3)],
      [136], [#name("乔安娜 德林克霍尔")], [#age(23)], [#assoc("ENG")], [#right], [#shakehand], [#defense], [*2167*], [#delta(-17)],
      [137], [#name("桑德拉 佩尔格尔")], [#age(22)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2166*], [#delta(0)],
      [138], [#name("LI Isabelle Siyun")], [#age(16)], [#assoc("SGP")], [#right], [#shakehand], [#defense], [*2165*], [#delta(7)],
      [139], [#name("VORONOVA Anastasia")], [#age(25)], [#assoc("RUS")], [?], [?], [?], [*2158*], [#delta(0)],
      [140], [#name("朴英淑")], [#age(22)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2158*], [#delta(0)],
      [141], [#name("LEE Hyun")], [#age(18)], [#assoc("KOR")], [?], [?], [?], [*2158*], [#delta(30)],
      [142], [#name("埃卡特里娜 恩图拉基")], [#age(28)], [#assoc("GRE")], [?], [?], [?], [*2158*], [#delta(-1)],
      [143], [#name("倪夏莲")], [#age(47)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2157*], [#delta(-1)],
      [144], [#name("安德烈娅 巴库拉")], [#age(29)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2157*], [#delta(14)],
      [145], [#name("藤井优子")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2153*], [#delta(-2)],
      [146], [#name("KASABOVA Asya")], [#age(34)], [#assoc("BUL")], [?], [?], [?], [*2152*], [#delta(-2)],
      [147], [#name("NAM Somi")], [#age(21)], [#assoc("KOR")], [?], [?], [?], [*2150*], [#delta(6)],
      [148], [#name("塔尼娅 克拉默")], [#age(30)], [#assoc("GER")], [?], [?], [?], [*2145*], [#delta(-1)],
      [149], [#name("MATZKE Laura")], [#age(22)], [#assoc("GER")], [?], [?], [?], [*2141*], [#delta(0)],
      [150], [#name("YOON Suwon")], [#age(27)], [#assoc("KOR")], [?], [?], [?], [*2140*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("MATTENET Audrey")], [#age(25)], [#assoc("FRA")], [?], [?], [?], [*2139*], [#delta(0)],
      [152], [#name("LI Bin")], [#age(22)], [#assoc("HUN")], [?], [?], [?], [*2133*], [#delta(0)],
      [153], [#name("CHO Hala")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2132*], [#delta(1)],
      [154], [#name("达娜 切霍娃")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2125*], [#delta(-30)],
      [155], [#name("MEDINA Paula")], [#age(21)], [#assoc("COL")], [#right], [#shakehand], [#attack], [*2120*], [#delta(61)],
      [156], [#name("YANG Fen")], [#age(28)], [#assoc("CGO")], [?], [?], [?], [*2118*], [#delta(-1)],
      [157], [#name("利吉娅 席尔瓦")], [#age(29)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2117*], [#delta(24)],
      [158], [#name("MIKHAYLOVA Olga")], [#age(23)], [#assoc("RUS")], [?], [?], [?], [*2116*], [#delta(-1)],
      [159], [#name("KUMARESAN Shamini")], [#age(22)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2114*], [#delta(0)],
      [160], [#name("安德里亚 托多罗维奇")], [#age(18)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2114*], [#delta(-12)],
      [161], [#name("SZCZERKOWSKA Magdalena")], [#age(18)], [#assoc("POL")], [?], [?], [?], [*2113*], [#delta(-15)],
      [162], [#name("巴尔博拉 巴拉佐娃")], [#age(18)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2113*], [#delta(44)],
      [163], [#name("田代早纪")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2109*], [#delta(-3)],
      [164], [#name("HWANG Jina")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2106*], [#delta(-3)],
      [165], [#name("MUHLBACH Kathrin")], [#age(18)], [#assoc("GER")], [?], [?], [?], [*2106*], [#delta(23)],
      [166], [#name("FETUKHINA Margarita")], [#age(22)], [#assoc("RUS")], [?], [?], [?], [*2105*], [#delta(-3)],
      [167], [#name("林佳慧")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2105*], [#delta(-3)],
      [168], [#name("卡梅利娅 雅各布")], [#age(18)], [#assoc("ROU")], [#right], [#shakehand], [#defense], [*2104*], [#delta(25)],
      [169], [#name("卡特琳娜 佩卡沃娃")], [#age(23)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2104*], [#delta(-4)],
      [170], [#name("BARTOSOVA Hana")], [#age(29)], [#assoc("CZE")], [?], [?], [?], [*2101*], [#delta(-4)],
      [171], [#name("马丁娜 波哈尔")], [#age(29)], [#assoc("SLO")], [?], [?], [?], [*2100*], [#delta(-4)],
      [172], [#name("斯韦特兰娜 加尼娜")], [#age(32)], [#assoc("RUS")], [?], [?], [?], [*2098*], [#delta(-4)],
      [173], [#name("尤利娅 普罗霍罗娃")], [#age(23)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2098*], [#delta(57)],
      [174], [#name("YAO Junyu")], [#age(18)], [#assoc("CHN")], [?], [?], [?], [*2097*], [#delta(-5)],
      [175], [#name("KIM Mijeong")], [#age(21)], [#assoc("KOR")], [?], [?], [?], [*2097*], [#delta(-5)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("多拉 马达拉斯")], [#age(17)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2094*], [#delta(-14)],
      [177], [#name("HE Sirin")], [#age(21)], [#assoc("TUR")], [?], [?], [?], [*2093*], [#delta(-21)],
      [178], [#name("郑佳奇")], [#age(22)], [#assoc("USA")], [?], [?], [?], [*2089*], [#delta(-6)],
      [179], [#name("SEBE Anamaria")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#defense], [*2087*], [#delta(-6)],
      [180], [#name("LEE Hyelin")], [#age(21)], [#assoc("KOR")], [?], [?], [?], [*2087*], [#delta(-6)],
      [181], [#name("PETZNER Martina")], [#age(26)], [#assoc("AUT")], [?], [?], [?], [*2087*], [#delta(-6)],
      [182], [#name("KUSINSKA Klaudia")], [#age(17)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2084*], [#delta(-6)],
      [183], [#name("车晓曦")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2081*], [#delta(-6)],
      [184], [#name("AMBRUS Krisztina")], [#age(18)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2075*], [#delta(5)],
      [185], [#name("HYON Ryon Hui")], [#age(21)], [#assoc("PRK")], [?], [?], [?], [*2074*], [#delta(-6)],
      [186], [#name("NOUWEN Carla")], [#age(24)], [#assoc("NED")], [?], [?], [?], [*2072*], [#delta(-6)],
      [187], [#name("穆玛 达斯")], [#age(26)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2070*], [#delta(-5)],
      [188], [#name("ABBAT Alice")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2065*], [#delta(-5)],
      [189], [#name("铃木李茄")], [#age(16)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2064*], [#delta(-5)],
      [190], [#name("素塔西尼 萨维塔布特")], [#age(16)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2062*], [#delta(-5)],
      [191], [#name("PASTOR Agata")], [#age(24)], [#assoc("POL")], [?], [?], [?], [*2060*], [#delta(-5)],
      [192], [#name("黄淑琴")], [#age(26)], [#assoc("MAS")], [?], [?], [?], [*2060*], [#delta(-5)],
      [193], [#name("CHAKRABORTY Kasturi")], [#age(29)], [#assoc("IND")], [?], [?], [?], [*2057*], [#delta(-3)],
      [194], [#name("SHER Sadia Falak")], [#age(24)], [#assoc("PAK")], [?], [?], [?], [*2055*], [#delta(-3)],
      [195], [#name("李依真")], [#age(23)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2055*], [#delta(-3)],
      [196], [#name("叶莲娜 莫克鲁索娃")], [#age(30)], [#assoc("MDA")], [?], [?], [?], [*2049*], [#delta(-2)],
      [197], [#name("MAGDY Raghd")], [#age(27)], [#assoc("EGY")], [?], [?], [?], [*2048*], [#delta(-1)],
      [198], [#name("马莉薇")], [#age(27)], [#assoc("MAS")], [#right], [#shakehand], [#attack], [*2046*], [#delta(-20)],
      [199], [#name("GOLOTA Marta")], [#age(22)], [#assoc("POL")], [?], [?], [?], [*2044*], [#delta(-2)],
      [200], [#name("RAMOS Fabiola")], [#age(33)], [#assoc("VEN")], [?], [?], [?], [*2043*], [#delta(115)],
    )
  )
