#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("马龙")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3132*], [#delta(0)],
      [2], [#name("王皓")], [#age(26)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2997*], [#delta(0)],
      [3], [#name("蒂姆 波尔")], [#age(28)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2959*], [#delta(2)],
      [4], [#name("马琳")], [#age(29)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2946*], [#delta(-1)],
      [5], [#name("郝帅")], [#age(26)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2910*], [#delta(-1)],
      [6], [#name("谭瑞午")], [#age(26)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2883*], [#delta(0)],
      [7], [#name("许昕")], [#age(19)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*2858*], [#delta(6)],
      [8], [#name("王励勤")], [#age(31)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2835*], [#delta(-1)],
      [9], [#name("张继科")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2821*], [#delta(-1)],
      [10], [#name("吴尚垠")], [#age(32)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2808*], [#delta(-1)],
      [11], [#name("陈玘")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2782*], [#delta(0)],
      [12], [#name("张超")], [#age(24)], [#assoc("CHN")], [?], [?], [?], [*2780*], [#delta(0)],
      [13], [#name("朱世赫")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2756*], [#delta(10)],
      [14], [#name("弗拉基米尔 萨姆索诺夫")], [#age(33)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2748*], [#delta(0)],
      [15], [#name("卡林尼科斯 格林卡")], [#age(37)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2742*], [#delta(0)],
      [16], [#name("孔令辉")], [#age(34)], [#assoc("CHN")], [?], [?], [?], [*2711*], [#delta(2)],
      [17], [#name("李廷佑")], [#age(25)], [#assoc("KOR")], [#left], [#penhold], [#attack], [*2698*], [#delta(3)],
      [18], [#name("尹在荣")], [#age(26)], [#assoc("KOR")], [?], [?], [?], [*2666*], [#delta(33)],
      [19], [#name("佐兰 普里莫拉克")], [#age(40)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2659*], [#delta(0)],
      [20], [#name("高礼泽")], [#age(33)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2655*], [#delta(-3)],
      [21], [#name("帕特里克 鲍姆")], [#age(22)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2647*], [#delta(15)],
      [22], [#name("水谷隼")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2646*], [#delta(34)],
      [23], [#name("维尔纳 施拉格")], [#age(37)], [#assoc("AUT")], [?], [?], [?], [*2643*], [#delta(-1)],
      [24], [#name("克里斯蒂安 苏斯")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2633*], [#delta(-14)],
      [25], [#name("林聚")], [#age(30)], [#assoc("DOM")], [?], [?], [?], [*2631*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("唐鹏")], [#age(28)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2630*], [#delta(32)],
      [27], [#name("张成万")], [#age(24)], [#assoc("PRK")], [?], [?], [?], [*2628*], [#delta(-1)],
      [28], [#name("彼得 科贝尔")], [#age(38)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2622*], [#delta(3)],
      [29], [#name("李平")], [#age(23)], [#assoc("QAT")], [#right], [#shakehand], [#attack], [*2618*], [#delta(-1)],
      [30], [#name("邱贻可")], [#age(24)], [#assoc("CHN")], [?], [?], [?], [*2611*], [#delta(2)],
      [31], [#name("江天一")], [#age(21)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2610*], [#delta(-1)],
      [32], [#name("高宁")], [#age(27)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2610*], [#delta(1)],
      [33], [#name("李静")], [#age(34)], [#assoc("HKG")], [?], [?], [?], [*2603*], [#delta(47)],
      [34], [#name("柳承敏")], [#age(27)], [#assoc("KOR")], [#right], [#penhold], [#attack], [*2597*], [#delta(23)],
      [35], [#name("约尔根 佩尔森")], [#age(43)], [#assoc("SWE")], [?], [?], [?], [*2596*], [#delta(-19)],
      [36], [#name("佐尔坦 费杰科内斯")], [#age(31)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2585*], [#delta(13)],
      [37], [#name("费奥多尔 库兹明")], [#age(26)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2574*], [#delta(22)],
      [38], [#name("米凯尔 梅兹")], [#age(28)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2572*], [#delta(0)],
      [39], [#name("亚历山大 卡拉卡谢维奇")], [#age(34)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2568*], [#delta(-10)],
      [40], [#name("陈卫星")], [#age(37)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2567*], [#delta(-6)],
      [41], [#name("伊戈尔 鲁布佐夫")], [#age(29)], [#assoc("RUS")], [?], [?], [?], [*2566*], [#delta(46)],
      [42], [#name("罗伯特 加尔多斯")], [#age(30)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2565*], [#delta(-2)],
      [43], [#name("金赫峰")], [#age(24)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2560*], [#delta(-1)],
      [44], [#name("吉田海伟")], [#age(28)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2559*], [#delta(-9)],
      [45], [#name("米哈伊 博博奇卡")], [#age(23)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2555*], [#delta(23)],
      [46], [#name("庄智渊")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2554*], [#delta(-21)],
      [47], [#name("迪米特里 奥恰洛夫")], [#age(21)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2551*], [#delta(-26)],
      [48], [#name("阿德里安 马特内")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2551*], [#delta(-5)],
      [49], [#name("李正三")], [#age(25)], [#assoc("KOR")], [?], [?], [?], [*2546*], [#delta(-3)],
      [50], [#name("韩阳")], [#age(31)], [#assoc("JPN")], [?], [?], [?], [*2543*], [#delta(-13)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("金正勋")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2542*], [#delta(-4)],
      [52], [#name("赵彦来")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2542*], [#delta(-4)],
      [53], [#name("塞贡 托里奥拉")], [#age(35)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2539*], [#delta(-3)],
      [54], [#name("黄圣盛")], [#age(22)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2526*], [#delta(-2)],
      [55], [#name("张钰")], [#age(28)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2522*], [#delta(-14)],
      [56], [#name("江宏杰")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2514*], [#delta(-3)],
      [57], [#name("沙拉特 阿昌塔")], [#age(27)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2509*], [#delta(18)],
      [58], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(29)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2507*], [#delta(-4)],
      [59], [#name("阿德里安 克里桑")], [#age(29)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2506*], [#delta(-32)],
      [60], [#name("松平健太")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2505*], [#delta(34)],
      [61], [#name("NAGY Krisztian")], [#age(20)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2502*], [#delta(-16)],
      [62], [#name("帕尔 格雷尔")], [#age(27)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2494*], [#delta(-2)],
      [63], [#name("詹斯 伦德奎斯特")], [#age(30)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2493*], [#delta(-2)],
      [64], [#name("芬 图格威尔")], [#age(33)], [#assoc("DEN")], [?], [?], [?], [*2489*], [#delta(-2)],
      [65], [#name("安德烈 加奇尼")], [#age(23)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2469*], [#delta(-10)],
      [66], [#name("安德烈 菲利蒙")], [#age(32)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2467*], [#delta(-3)],
      [67], [#name("阿卜杜勒-卡德尔 萨利富")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2464*], [#delta(-3)],
      [68], [#name("杨敏")], [#age(46)], [#assoc("ITA")], [?], [?], [?], [*2461*], [#delta(-3)],
      [69], [#name("卢兹扬 布拉斯奇克")], [#age(35)], [#assoc("POL")], [?], [?], [?], [*2456*], [#delta(-2)],
      [70], [#name("克里斯托夫 勒古")], [#age(36)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2452*], [#delta(61)],
      [71], [#name("王增羿")], [#age(26)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2452*], [#delta(-27)],
      [72], [#name("威廉 亨泽尔")], [#age(27)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2447*], [#delta(-3)],
      [73], [#name("塩野真人")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2443*], [#delta(-3)],
      [74], [#name("李哲国")], [#age(24)], [#assoc("PRK")], [?], [?], [?], [*2442*], [#delta(-3)],
      [75], [#name("卢博米尔 扬察里克")], [#age(22)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2437*], [#delta(-3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("刘松")], [#age(37)], [#assoc("ARG")], [?], [?], [?], [*2436*], [#delta(-3)],
      [77], [#name("LEI Zhenhua")], [#age(23)], [#assoc("CHN")], [?], [?], [?], [*2436*], [#delta(-3)],
      [78], [#name("保罗 德林克霍尔")], [#age(19)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2428*], [#delta(-2)],
      [79], [#name("盖尔 埃兰森")], [#age(33)], [#assoc("NOR")], [?], [?], [?], [*2427*], [#delta(-2)],
      [80], [#name("BARDON Michal")], [#age(31)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2417*], [#delta(-1)],
      [81], [#name("马克斯 弗雷塔斯")], [#age(21)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2416*], [#delta(-3)],
      [82], [#name("达米安 埃洛伊")], [#age(40)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2411*], [#delta(-1)],
      [83], [#name("基里尔 斯卡奇科夫")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2410*], [#delta(7)],
      [84], [#name("康斯坦丁 乔蒂")], [#age(26)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2406*], [#delta(-1)],
      [85], [#name("若昂 蒙泰罗")], [#age(26)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2406*], [#delta(49)],
      [86], [#name("拉尔斯 希尔舍")], [#age(30)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2402*], [#delta(35)],
      [87], [#name("YOKOYAMA Yuichi")], [#age(22)], [#assoc("JPN")], [?], [?], [?], [*2398*], [#delta(-3)],
      [88], [#name("李镇权")], [#age(22)], [#assoc("KOR")], [?], [?], [?], [*2396*], [#delta(-3)],
      [89], [#name("大矢英俊")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2396*], [#delta(-3)],
      [90], [#name("丹尼尔 茨维克尔")], [#age(25)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2390*], [#delta(-2)],
      [91], [#name("WANG Jianfeng")], [#age(43)], [#assoc("NOR")], [#right], [#penhold], [#attack], [*2390*], [#delta(-2)],
      [92], [#name("阿列克谢 利文佐夫")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2389*], [#delta(4)],
      [93], [#name("蒋澎龙")], [#age(33)], [#assoc("TPE")], [?], [?], [?], [*2386*], [#delta(-2)],
      [94], [#name("KONGSGAARD Christian")], [#age(26)], [#assoc("DEN")], [?], [?], [?], [*2385*], [#delta(-2)],
      [95], [#name("约翰 阿克塞尔奎斯特")], [#age(24)], [#assoc("SWE")], [?], [?], [?], [*2384*], [#delta(-2)],
      [96], [#name("CHMIEL Pawel")], [#age(23)], [#assoc("POL")], [?], [?], [?], [*2383*], [#delta(-1)],
      [97], [#name("HAN Jimin")], [#age(20)], [#assoc("KOR")], [?], [?], [?], [*2382*], [#delta(0)],
      [98], [#name("罗伯特 斯文松")], [#age(26)], [#assoc("SWE")], [?], [?], [?], [*2379*], [#delta(0)],
      [99], [#name("约瑟夫 普拉希")], [#age(38)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2378*], [#delta(0)],
      [100], [#name("松平贤二")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2378*], [#delta(-61)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("巴斯蒂安 斯特格")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2376*], [#delta(-1)],
      [102], [#name("亚诺什 雅各布")], [#age(23)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2376*], [#delta(1)],
      [103], [#name("林载贤")], [#age(24)], [#assoc("KOR")], [?], [?], [?], [*2374*], [#delta(-2)],
      [104], [#name("巴托什 苏赫")], [#age(26)], [#assoc("POL")], [?], [?], [?], [*2370*], [#delta(-2)],
      [105], [#name("马克西姆 什梅廖夫")], [#age(38)], [#assoc("RUS")], [?], [?], [?], [*2370*], [#delta(-23)],
      [106], [#name("艾哈迈德 萨利赫")], [#age(30)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2369*], [#delta(-1)],
      [107], [#name("艾曼纽 莱贝松")], [#age(21)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2366*], [#delta(-3)],
      [108], [#name("梁柱恩")], [#age(30)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2365*], [#delta(5)],
      [109], [#name("TAMMINEN Timo")], [#age(21)], [#assoc("FIN")], [?], [?], [?], [*2359*], [#delta(-3)],
      [110], [#name("高木和卓")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2359*], [#delta(-3)],
      [111], [#name("阿兰 本特森")], [#age(41)], [#assoc("DEN")], [?], [?], [?], [*2359*], [#delta(-3)],
      [112], [#name("KO Junhyung")], [#age(26)], [#assoc("KOR")], [?], [?], [?], [*2355*], [#delta(-3)],
      [113], [#name("叶夫根尼 齐特切蒂宁")], [#age(39)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2352*], [#delta(-2)],
      [114], [#name("BOBILLIER Loic")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2352*], [#delta(-2)],
      [115], [#name("DOAN Kien Quoc")], [#age(30)], [#assoc("VIE")], [#left], [#shakehand], [#attack], [*2342*], [#delta(-1)],
      [116], [#name("吴志祺")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2342*], [#delta(-1)],
      [117], [#name("让 米歇尔 塞弗")], [#age(40)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2341*], [#delta(18)],
      [118], [#name("小山雨果")], [#age(40)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2341*], [#delta(-2)],
      [119], [#name("阿列克谢 斯米尔诺夫")], [#age(32)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2337*], [#delta(-53)],
      [120], [#name("坂本龙介")], [#age(25)], [#assoc("JPN")], [?], [?], [?], [*2337*], [#delta(-3)],
      [121], [#name("蒂亚戈 阿波罗尼亚")], [#age(23)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2329*], [#delta(-3)],
      [122], [#name("下山隆敬")], [#age(24)], [#assoc("JPN")], [?], [?], [?], [*2329*], [#delta(-3)],
      [123], [#name("奥维迪乌 伊奥内斯库")], [#age(20)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2325*], [#delta(179)],
      [124], [#name("彼得 法泽卡斯")], [#age(28)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2322*], [#delta(-2)],
      [125], [#name("亚历山大 迪杜赫")], [#age(27)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2322*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("卢文 菲鲁斯")], [#age(21)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2321*], [#delta(46)],
      [127], [#name("何志文")], [#age(47)], [#assoc("ESP")], [#left], [#penhold], [#attack], [*2320*], [#delta(-3)],
      [128], [#name("费伦茨 帕西")], [#age(35)], [#assoc("HUN")], [?], [?], [?], [*2320*], [#delta(-3)],
      [129], [#name("陈建安")], [#age(18)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2317*], [#delta(-3)],
      [130], [#name("崔贤珍")], [#age(30)], [#assoc("KOR")], [?], [?], [?], [*2317*], [#delta(-3)],
      [131], [#name("SIMONER Christoph")], [#age(26)], [#assoc("AUT")], [?], [?], [?], [*2316*], [#delta(-3)],
      [132], [#name("雅罗斯拉夫 扎穆登科")], [#age(21)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2315*], [#delta(-3)],
      [133], [#name("托马斯 凯纳特")], [#age(32)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2314*], [#delta(-3)],
      [134], [#name("阿尔弗雷多 卡内罗斯")], [#age(31)], [#assoc("ESP")], [?], [?], [?], [*2309*], [#delta(-1)],
      [135], [#name("托本 沃西克")], [#age(36)], [#assoc("GER")], [?], [?], [?], [*2305*], [#delta(1)],
      [136], [#name("瓦西里 拉凯耶夫")], [#age(25)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2304*], [#delta(21)],
      [137], [#name("ZENG Cem")], [#age(24)], [#assoc("TUR")], [?], [?], [?], [*2304*], [#delta(10)],
      [138], [#name("李尚洙")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2302*], [#delta(-1)],
      [139], [#name("格里戈里 弗拉索夫")], [#age(25)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2302*], [#delta(-1)],
      [140], [#name("托马斯 科涅茨尼")], [#age(24)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2302*], [#delta(-1)],
      [141], [#name("博扬 托基奇")], [#age(28)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2301*], [#delta(-21)],
      [142], [#name("MOSELHY Emad")], [#age(30)], [#assoc("EGY")], [?], [?], [?], [*2299*], [#delta(-2)],
      [143], [#name("TSUBOGUCHI Michikazu")], [#age(23)], [#assoc("JPN")], [?], [?], [?], [*2291*], [#delta(-2)],
      [144], [#name("萨什 拉桑")], [#age(38)], [#assoc("SLO")], [#right], [#shakehand], [#defense], [*2290*], [#delta(-2)],
      [145], [#name("WANG Jianan")], [#age(26)], [#assoc("CGO")], [?], [?], [?], [*2287*], [#delta(-2)],
      [146], [#name("卡洛斯 马查多")], [#age(29)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2282*], [#delta(-2)],
      [147], [#name("雅库布 科索夫斯基")], [#age(27)], [#assoc("POL")], [?], [?], [?], [*2275*], [#delta(-37)],
      [148], [#name("彼得 塞雷达")], [#age(25)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2274*], [#delta(-3)],
      [149], [#name("CHO Jihoon")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2267*], [#delta(-3)],
      [150], [#name("马蒂斯 布尔吉斯")], [#age(20)], [#assoc("LAT")], [#right], [#shakehand], [#attack], [*2266*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("卢博米尔 皮斯特耶")], [#age(25)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2263*], [#delta(-2)],
      [152], [#name("PETRUKHIN Evgeny")], [#age(24)], [#assoc("RUS")], [?], [?], [?], [*2261*], [#delta(107)],
      [153], [#name("马丁 奥列尼克")], [#age(37)], [#assoc("CZE")], [?], [?], [?], [*2256*], [#delta(-2)],
      [154], [#name("FILIMON Lucian")], [#age(30)], [#assoc("ROU")], [?], [?], [?], [*2253*], [#delta(-2)],
      [155], [#name("丹尼尔 古拉克")], [#age(26)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2251*], [#delta(-2)],
      [156], [#name("岸川圣也")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2249*], [#delta(-1)],
      [157], [#name("马雷克 齐哈克")], [#age(35)], [#assoc("CZE")], [?], [?], [?], [*2245*], [#delta(-1)],
      [158], [#name("古斯塔沃 坪井")], [#age(24)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2240*], [#delta(0)],
      [159], [#name("CHOU Tung-Yu")], [#age(22)], [#assoc("TPE")], [?], [?], [?], [*2239*], [#delta(0)],
      [160], [#name("SZYMANSKI Filip")], [#age(26)], [#assoc("POL")], [?], [?], [?], [*2236*], [#delta(0)],
      [161], [#name("米哈伊尔 派科夫")], [#age(20)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2235*], [#delta(0)],
      [162], [#name("马良")], [#age(18)], [#assoc("SGP")], [?], [?], [?], [*2232*], [#delta(0)],
      [163], [#name("NASIRU Kazeem")], [#age(35)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2230*], [#delta(0)],
      [164], [#name("REDJEP Ronald")], [#age(36)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2226*], [#delta(0)],
      [165], [#name("塞巴斯蒂安 若韦尔")], [#age(34)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2223*], [#delta(0)],
      [166], [#name("HORVAT Mitja")], [#age(31)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2222*], [#delta(0)],
      [167], [#name("ZEIMYS Kestutis")], [#age(21)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2219*], [#delta(1)],
      [168], [#name("VAINULA Vallot")], [#age(31)], [#assoc("EST")], [#right], [#shakehand], [#attack], [*2219*], [#delta(1)],
      [169], [#name("杨子")], [#age(25)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2219*], [#delta(1)],
      [170], [#name("松本和雄")], [#age(24)], [#assoc("BRA")], [#left], [#penhold], [#attack], [*2216*], [#delta(9)],
      [171], [#name("斯特凡 菲格尔")], [#age(21)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2215*], [#delta(0)],
      [172], [#name("佐尔特 佩托")], [#age(22)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2214*], [#delta(1)],
      [173], [#name("RAMIREZ Jose Miguel")], [#age(26)], [#assoc("GUA")], [#right], [#shakehand], [#attack], [*2212*], [#delta(1)],
      [174], [#name("康斯坦丁诺斯 帕帕乔治乌")], [#age(30)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2207*], [#delta(1)],
      [175], [#name("伊日 维拉波里克")], [#age(26)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2207*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("ROBERTSON Adam")], [#age(25)], [#assoc("WAL")], [?], [?], [?], [*2207*], [#delta(1)],
      [177], [#name("罗科 托西奇")], [#age(30)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2206*], [#delta(25)],
      [178], [#name("德米特里 普罗科普科夫")], [#age(29)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2206*], [#delta(0)],
      [179], [#name("GOLOVANOV Stanislav")], [#age(21)], [#assoc("BUL")], [#right], [#shakehand], [#attack], [*2204*], [#delta(-47)],
      [180], [#name("DAVID Petr")], [#age(25)], [#assoc("CZE")], [?], [?], [?], [*2197*], [#delta(0)],
      [181], [#name("布里斯 奥利维耶")], [#age(27)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2195*], [#delta(0)],
      [182], [#name("CAI Xiaoli")], [#age(30)], [#assoc("SGP")], [?], [?], [?], [*2194*], [#delta(0)],
      [183], [#name("KOSZYK Boguslaw")], [#age(22)], [#assoc("POL")], [?], [?], [?], [*2193*], [#delta(0)],
      [184], [#name("KANG Donghoon")], [#age(22)], [#assoc("KOR")], [?], [?], [?], [*2193*], [#delta(0)],
      [185], [#name("丁祥恩")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2193*], [#delta(0)],
      [186], [#name("克里斯坦 卡尔松")], [#age(18)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2191*], [#delta(0)],
      [187], [#name("上田仁")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2188*], [#delta(0)],
      [188], [#name("蒂亚戈 蒙泰罗")], [#age(28)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2188*], [#delta(5)],
      [189], [#name("LEONG Kin Wa")], [#age(29)], [#assoc("MAC")], [?], [?], [?], [*2188*], [#delta(-1)],
      [190], [#name("苏姆亚吉特 格霍什")], [#age(16)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2186*], [#delta(263)],
      [191], [#name("安东宁 加夫拉斯")], [#age(24)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2185*], [#delta(12)],
      [192], [#name("丹尼尔 哈贝松")], [#age(23)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2182*], [#delta(-3)],
      [193], [#name("PRESSLMAYER Bernhard")], [#age(29)], [#assoc("AUT")], [?], [?], [?], [*2178*], [#delta(-3)],
      [194], [#name("HINSE Pierre-Luc")], [#age(22)], [#assoc("CAN")], [?], [?], [?], [*2177*], [#delta(-3)],
      [195], [#name("BRATANOV Martin")], [#age(35)], [#assoc("BEL")], [?], [?], [?], [*2176*], [#delta(-3)],
      [196], [#name("ZOMBORI David")], [#age(21)], [#assoc("HUN")], [?], [?], [?], [*2174*], [#delta(67)],
      [197], [#name("达尼埃尔 科希鲍")], [#age(18)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2170*], [#delta(-43)],
      [198], [#name("SEO Younggyun")], [#age(24)], [#assoc("KOR")], [?], [?], [?], [*2164*], [#delta(-4)],
      [199], [#name("阿马拉杰 安东尼")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2163*], [#delta(59)],
      [200], [#name("MEROTOHUN Monday")], [#age(32)], [#assoc("NGR")], [#right], [#shakehand], [#defense], [*2161*], [#delta(-4)],
    )
  )
