#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("张怡宁")], [#age(28)], [#assoc("CHN")], [?], [?], [?], [*3202*], [#delta(0)],
      [2], [#name("李晓霞")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3062*], [#delta(0)],
      [3], [#name("郭跃")], [#age(21)], [#assoc("CHN")], [?], [?], [?], [*2891*], [#delta(0)],
      [4], [#name("曹臻")], [#age(22)], [#assoc("CHN")], [?], [?], [?], [*2846*], [#delta(0)],
      [5], [#name("刘诗雯")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2825*], [#delta(0)],
      [6], [#name("朴美英")], [#age(28)], [#assoc("KOR")], [?], [?], [?], [*2822*], [#delta(0)],
      [7], [#name("高军")], [#age(40)], [#assoc("USA")], [?], [?], [?], [*2796*], [#delta(0)],
      [8], [#name("郭焱")], [#age(27)], [#assoc("CHN")], [?], [?], [?], [*2791*], [#delta(0)],
      [9], [#name("金景娥")], [#age(32)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2778*], [#delta(1)],
      [10], [#name("丁宁")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2764*], [#delta(1)],
      [11], [#name("维多利亚 帕夫洛维奇")], [#age(31)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2742*], [#delta(20)],
      [12], [#name("范瑛")], [#age(23)], [#assoc("CHN")], [?], [?], [?], [*2714*], [#delta(0)],
      [13], [#name("彭陆洋")], [#age(24)], [#assoc("CHN")], [?], [?], [?], [*2707*], [#delta(0)],
      [14], [#name("刘佳")], [#age(27)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2698*], [#delta(0)],
      [15], [#name("平野早矢香")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2687*], [#delta(45)],
      [16], [#name("姚彦")], [#age(21)], [#assoc("CHN")], [?], [?], [?], [*2680*], [#delta(-1)],
      [17], [#name("石垣优香")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2669*], [#delta(0)],
      [18], [#name("帖雅娜")], [#age(30)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2658*], [#delta(0)],
      [19], [#name("常晨晨")], [#age(23)], [#assoc("CHN")], [?], [?], [?], [*2657*], [#delta(0)],
      [20], [#name("冯天薇")], [#age(23)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2639*], [#delta(-11)],
      [21], [#name("姜华珺")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2632*], [#delta(-1)],
      [22], [#name("于梦雨")], [#age(20)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2619*], [#delta(5)],
      [23], [#name("田势美贵江")], [#age(29)], [#assoc("JPN")], [?], [?], [?], [*2616*], [#delta(-1)],
      [24], [#name("唐汭序")], [#age(28)], [#assoc("KOR")], [?], [?], [?], [*2609*], [#delta(-1)],
      [25], [#name("文佳")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2608*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("沈燕飞")], [#age(30)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2601*], [#delta(-1)],
      [27], [#name("李佳薇")], [#age(28)], [#assoc("SGP")], [?], [?], [?], [*2599*], [#delta(-1)],
      [28], [#name("王越古")], [#age(29)], [#assoc("SGP")], [?], [?], [?], [*2585*], [#delta(-12)],
      [29], [#name("孙蓓蓓")], [#age(25)], [#assoc("SGP")], [?], [?], [?], [*2576*], [#delta(28)],
      [30], [#name("玛丽娜 克拉夫琴科")], [#age(36)], [#assoc("ISR")], [#right], [#shakehand], [#attack], [*2574*], [#delta(-2)],
      [31], [#name("柳絮飞")], [#age(28)], [#assoc("HKG")], [?], [?], [?], [*2569*], [#delta(-2)],
      [32], [#name("林菱")], [#age(32)], [#assoc("HKG")], [?], [?], [?], [*2556*], [#delta(-2)],
      [33], [#name("李恩姬")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2548*], [#delta(-1)],
      [34], [#name("克里斯蒂娜 托特")], [#age(35)], [#assoc("HUN")], [?], [?], [?], [*2541*], [#delta(-13)],
      [35], [#name("金仲")], [#age(20)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2534*], [#delta(-1)],
      [36], [#name("伊娃 奥多罗娃")], [#age(30)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2532*], [#delta(-1)],
      [37], [#name("李洁")], [#age(25)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2525*], [#delta(0)],
      [38], [#name("李佼")], [#age(36)], [#assoc("NED")], [#left], [#penhold], [#attack], [*2525*], [#delta(-2)],
      [39], [#name("尼科莱塔 斯特凡诺娃")], [#age(25)], [#assoc("ITA")], [#left], [#shakehand], [#attack], [*2520*], [#delta(22)],
      [40], [#name("吴佳多")], [#age(32)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2516*], [#delta(25)],
      [41], [#name("吴雪")], [#age(29)], [#assoc("DOM")], [?], [?], [?], [*2506*], [#delta(-1)],
      [42], [#name("石贺净")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2489*], [#delta(0)],
      [43], [#name("山梨有理")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2488*], [#delta(0)],
      [44], [#name("孙祯琦")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2479*], [#delta(31)],
      [45], [#name("韦罗妮卡 帕夫洛维奇")], [#age(31)], [#assoc("BLR")], [?], [?], [?], [*2475*], [#delta(1)],
      [46], [#name("樋浦令子")], [#age(25)], [#assoc("JPN")], [?], [?], [?], [*2473*], [#delta(-8)],
      [47], [#name("徐孝元")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2472*], [#delta(0)],
      [48], [#name("李瑨丽")], [#age(32)], [#assoc("NZL")], [?], [?], [?], [*2471*], [#delta(0)],
      [49], [#name("李倩")], [#age(23)], [#assoc("POL")], [#right], [#shakehand], [#defense], [*2468*], [#delta(15)],
      [50], [#name("木子")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2460*], [#delta(21)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("倪夏莲")], [#age(46)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2444*], [#delta(1)],
      [52], [#name("安娜玛丽亚 埃尔德利")], [#age(24)], [#assoc("SRB")], [#right], [#shakehand], [#defense], [*2435*], [#delta(50)],
      [53], [#name("塔玛拉 鲍罗斯")], [#age(32)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2435*], [#delta(-20)],
      [54], [#name("SANG Xu Stephanie")], [#age(23)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2434*], [#delta(0)],
      [55], [#name("埃尔卡 塞尔")], [#age(36)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2429*], [#delta(-16)],
      [56], [#name("科尔内莉亚 莫尔纳")], [#age(26)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2425*], [#delta(3)],
      [57], [#name("娜塔莉亚 帕尔蒂卡")], [#age(20)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2421*], [#delta(-12)],
      [58], [#name("WANG Xuan")], [#age(20)], [#assoc("CHN")], [?], [?], [?], [*2420*], [NEW],
      [59], [#name("鲁塔 帕斯考斯基涅")], [#age(32)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2413*], [#delta(23)],
      [60], [#name("李雪")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#defense], [*2410*], [#delta(-7)],
      [61], [#name("洪剑芳")], [#age(36)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2408*], [#delta(1)],
      [62], [#name("侯美玲")], [#age(20)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2403*], [#delta(-21)],
      [63], [#name("田惠庆")], [#age(32)], [#assoc("KOR")], [?], [?], [?], [*2401*], [#delta(0)],
      [64], [#name("克里斯汀 朗")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2400*], [#delta(64)],
      [65], [#name("徐洁")], [#age(27)], [#assoc("POL")], [?], [?], [?], [*2399*], [#delta(-10)],
      [66], [#name("纳迪娜 博尔迈尔")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2397*], [#delta(17)],
      [67], [#name("崔文渶")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2395*], [#delta(-1)],
      [68], [#name("郑怡静")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2388*], [#delta(0)],
      [69], [#name("福原爱")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2387*], [#delta(-25)],
      [70], [#name("谭文玲")], [#age(37)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2384*], [#delta(-21)],
      [71], [#name("石川佳纯")], [#age(16)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2376*], [#delta(-13)],
      [72], [#name("黄怡桦")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2375*], [#delta(-3)],
      [73], [#name("安娜 蒂克米罗娃")], [#age(25)], [#assoc("RUS")], [?], [?], [?], [*2359*], [#delta(-23)],
      [74], [#name("丹妮拉 多迪安")], [#age(21)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2358*], [#delta(-23)],
      [75], [#name("卡罗尔 格伦迪施")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2351*], [#delta(-5)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("米艾 斯科娃")], [#age(23)], [#assoc("DEN")], [#right], [#shakehand], [#attack], [*2344*], [#delta(0)],
      [77], [#name("藤井宽子")], [#age(27)], [#assoc("JPN")], [?], [?], [?], [*2341*], [#delta(-4)],
      [78], [#name("文炫晶")], [#age(25)], [#assoc("KOR")], [?], [?], [?], [*2339*], [#delta(-1)],
      [79], [#name("小西杏")], [#age(29)], [#assoc("JPN")], [?], [?], [?], [*2331*], [#delta(1)],
      [80], [#name("奥克萨娜 法德耶娃")], [#age(34)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2323*], [#delta(57)],
      [81], [#name("李晓丹")], [#age(19)], [#assoc("CHN")], [?], [?], [?], [*2319*], [#delta(385)],
      [82], [#name("高王")], [#age(29)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2318*], [#delta(-1)],
      [83], [#name("朱芳")], [#age(33)], [#assoc("ESP")], [?], [?], [?], [*2312*], [#delta(-16)],
      [84], [#name("伊丽莎白 萨马拉")], [#age(20)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2309*], [#delta(-28)],
      [85], [#name("武杨")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2304*], [#delta(118)],
      [86], [#name("苗苗")], [#age(28)], [#assoc("AUS")], [?], [?], [?], [*2302*], [#delta(-2)],
      [87], [#name("福冈春菜")], [#age(25)], [#assoc("JPN")], [?], [?], [?], [*2300*], [#delta(-2)],
      [88], [#name("SUN Jin")], [#age(29)], [#assoc("HKG")], [?], [?], [?], [*2290*], [#delta(-1)],
      [89], [#name("叶莲娜 库兹米娜")], [#age(20)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2285*], [#delta(-1)],
      [90], [#name("CAO Lisi")], [#age(18)], [#assoc("CHN")], [?], [?], [?], [*2282*], [#delta(-1)],
      [91], [#name("玛蒂尔达 埃克霍尔姆")], [#age(27)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2282*], [#delta(12)],
      [92], [#name("乔治娜 波塔")], [#age(24)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2282*], [#delta(-14)],
      [93], [#name("特蒂亚娜 比连科")], [#age(26)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2279*], [#delta(-3)],
      [94], [#name("达娜 切霍娃")], [#age(26)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2278*], [#delta(-3)],
      [95], [#name("VORONOVA Anastasia")], [#age(24)], [#assoc("RUS")], [?], [?], [?], [*2276*], [#delta(20)],
      [96], [#name("乔安娜 德林克霍尔")], [#age(22)], [#assoc("ENG")], [#right], [#shakehand], [#defense], [*2275*], [#delta(-4)],
      [97], [#name("朴晟惠")], [#age(23)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2274*], [#delta(-4)],
      [98], [#name("KO Somi")], [#age(25)], [#assoc("KOR")], [?], [?], [?], [*2273*], [#delta(-4)],
      [99], [#name("SHIM Serom")], [#age(22)], [#assoc("KOR")], [?], [?], [?], [*2273*], [#delta(-4)],
      [100], [#name("朴英淑")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2270*], [#delta(-4)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("若宫三纱子")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2259*], [#delta(-4)],
      [102], [#name("KIM Soongsil")], [#age(28)], [#assoc("KOR")], [?], [?], [?], [*2258*], [#delta(-4)],
      [103], [#name("安东尼娜 希曼斯卡")], [#age(26)], [#assoc("POL")], [?], [?], [?], [*2257*], [#delta(-4)],
      [104], [#name("林佳慧")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2252*], [#delta(-3)],
      [105], [#name("叶连娜 季米娜")], [#age(40)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2251*], [#delta(-19)],
      [106], [#name("利娜 米西科尼特")], [#age(21)], [#assoc("LTU")], [?], [?], [?], [*2241*], [#delta(-2)],
      [107], [#name("伊韦塔 瓦切诺夫斯卡")], [#age(23)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2240*], [#delta(14)],
      [108], [#name("叶莲娜 莫克鲁索娃")], [#age(29)], [#assoc("MDA")], [?], [?], [?], [*2238*], [#delta(-3)],
      [109], [#name("玛丽亚 多尔吉赫")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2238*], [#delta(-3)],
      [110], [#name("李嫱冰")], [#age(24)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2232*], [#delta(-31)],
      [111], [#name("渡边裕子")], [#age(25)], [#assoc("JPN")], [?], [?], [?], [*2232*], [#delta(-4)],
      [112], [#name("MOON Bosun")], [#age(23)], [#assoc("KOR")], [?], [?], [?], [*2230*], [#delta(-4)],
      [113], [#name("陆云凤")], [#age(25)], [#assoc("TPE")], [?], [?], [?], [*2229*], [#delta(-4)],
      [114], [#name("藤沼亚衣")], [#age(27)], [#assoc("JPN")], [?], [?], [?], [*2229*], [#delta(-42)],
      [115], [#name("埃卡特里娜 恩图拉基")], [#age(27)], [#assoc("GRE")], [?], [?], [?], [*2225*], [#delta(-5)],
      [116], [#name("卡塔琳娜 加京斯卡")], [#age(39)], [#assoc("BUL")], [?], [?], [?], [*2222*], [#delta(-3)],
      [117], [#name("羡宜芳")], [#age(32)], [#assoc("FRA")], [#right], [#shakehand], [#defense], [*2222*], [#delta(-43)],
      [118], [#name("加利娅 德沃拉克")], [#age(21)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2221*], [#delta(-7)],
      [119], [#name("艾米丽 索尔佳")], [#age(19)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2221*], [#delta(-2)],
      [120], [#name("张墨")], [#age(20)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2220*], [#delta(78)],
      [121], [#name("LI Bin")], [#age(21)], [#assoc("HUN")], [?], [?], [?], [*2213*], [#delta(-5)],
      [122], [#name("劳拉 内格里索利")], [#age(35)], [#assoc("ITA")], [?], [?], [?], [*2212*], [#delta(-8)],
      [123], [#name("YANG Fen")], [#age(27)], [#assoc("CGO")], [?], [?], [?], [*2203*], [#delta(-5)],
      [124], [#name("于国诗")], [#age(23)], [#assoc("HKG")], [?], [?], [?], [*2201*], [#delta(-5)],
      [125], [#name("HE Sirin")], [#age(20)], [#assoc("TUR")], [?], [?], [?], [*2201*], [#delta(4)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("雷娜塔 斯特尔比科娃")], [#age(30)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2196*], [#delta(29)],
      [127], [#name("卡琳娜 荣松")], [#age(30)], [#assoc("SWE")], [?], [?], [?], [*2193*], [#delta(-5)],
      [128], [#name("KASABOVA Asya")], [#age(33)], [#assoc("BUL")], [?], [?], [?], [*2188*], [#delta(-5)],
      [129], [#name("萨拉 拉米雷斯")], [#age(22)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2186*], [#delta(7)],
      [130], [#name("金贞弦")], [#age(24)], [#assoc("KOR")], [?], [?], [?], [*2184*], [#delta(-6)],
      [131], [#name("卡特琳娜 佩卡沃娃")], [#age(22)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2178*], [#delta(-6)],
      [132], [#name("桑德拉 佩尔格尔")], [#age(21)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2169*], [#delta(-6)],
      [133], [#name("越崎步")], [#age(28)], [#assoc("JPN")], [?], [?], [?], [*2167*], [#delta(-6)],
      [134], [#name("伊雷妮 伊万坎")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2167*], [#delta(11)],
      [135], [#name("ARAQUE Johana")], [#age(27)], [#assoc("COL")], [?], [?], [?], [*2162*], [#delta(-5)],
      [136], [#name("阿尼萨拉 穆昂苏克")], [#age(33)], [#assoc("THA")], [?], [?], [?], [*2161*], [#delta(-4)],
      [137], [#name("佩特拉 洛瓦斯")], [#age(29)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2160*], [#delta(-2)],
      [138], [#name("森园美咲")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2155*], [#delta(-4)],
      [139], [#name("藤井优子")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2141*], [#delta(-1)],
      [140], [#name("YOON Suwon")], [#age(26)], [#assoc("KOR")], [?], [?], [?], [*2140*], [#delta(-1)],
      [141], [#name("TERUI Moemi")], [#age(21)], [#assoc("JPN")], [?], [?], [?], [*2138*], [#delta(-1)],
      [142], [#name("张瑞")], [#age(30)], [#assoc("HKG")], [?], [?], [?], [*2134*], [#delta(-1)],
      [143], [#name("琳达 克雷默斯")], [#age(24)], [#assoc("NED")], [?], [?], [?], [*2131*], [#delta(53)],
      [144], [#name("PATKAR Madhurika")], [#age(22)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2130*], [#delta(160)],
      [145], [#name("RAMOS Fabiola")], [#age(32)], [#assoc("VEN")], [?], [?], [?], [*2128*], [#delta(-2)],
      [146], [#name("CHO Hala")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2127*], [#delta(-2)],
      [147], [#name("HOU Yu-Ling")], [#age(19)], [#assoc("TPE")], [?], [?], [?], [*2126*], [#delta(-1)],
      [148], [#name("熊乃仪")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2124*], [#delta(-1)],
      [149], [#name("劳拉 罗伯逊")], [#age(25)], [#assoc("GER")], [?], [?], [?], [*2119*], [#delta(-16)],
      [150], [#name("SAKO Karin")], [#age(21)], [#assoc("BRA")], [?], [?], [?], [*2119*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("丽塔 凯尔泰")], [#age(31)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2118*], [#delta(-20)],
      [152], [#name("MIKHAYLOVA Olga")], [#age(22)], [#assoc("RUS")], [?], [?], [?], [*2116*], [#delta(-3)],
      [153], [#name("马莉薇")], [#age(26)], [#assoc("MAS")], [#right], [#shakehand], [#attack], [*2116*], [#delta(47)],
      [154], [#name("GUAN Mengyuan")], [#age(17)], [#assoc("HKG")], [?], [?], [?], [*2115*], [#delta(-4)],
      [155], [#name("LIU Na")], [#age(26)], [#assoc("IRL")], [?], [?], [?], [*2115*], [#delta(65)],
      [156], [#name("塔尼娅 克拉默")], [#age(29)], [#assoc("GER")], [?], [?], [?], [*2114*], [#delta(-56)],
      [157], [#name("斯韦特兰娜 加尼娜")], [#age(31)], [#assoc("RUS")], [?], [?], [?], [*2109*], [#delta(-6)],
      [158], [#name("玛格丽塔 佩索茨卡")], [#age(18)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2109*], [#delta(-6)],
      [159], [#name("马丁娜 波哈尔")], [#age(28)], [#assoc("SLO")], [?], [?], [?], [*2100*], [#delta(-3)],
      [160], [#name("金慧星")], [#age(16)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2099*], [#delta(-3)],
      [161], [#name("尤利娅 内库拉")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2098*], [#delta(-3)],
      [162], [#name("刘媛")], [#age(24)], [#assoc("AUT")], [#right], [#penhold], [#attack], [*2095*], [#delta(-50)],
      [163], [#name("AGGARWAL Neha")], [#age(19)], [#assoc("IND")], [?], [?], [?], [*2090*], [#delta(-4)],
      [164], [#name("尤利娅 普罗霍罗娃")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2088*], [#delta(-10)],
      [165], [#name("ROVANI Silir")], [#age(21)], [#assoc("INA")], [#right], [#shakehand], [#attack], [*2082*], [#delta(-3)],
      [166], [#name("吴颖岚")], [#age(17)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2080*], [#delta(-3)],
      [167], [#name("TANIOKA Ayuka")], [#age(15)], [#assoc("JPN")], [?], [?], [?], [*2080*], [#delta(-3)],
      [168], [#name("萨宾 温特")], [#age(17)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2078*], [#delta(65)],
      [169], [#name("HYON Ryon Hui")], [#age(20)], [#assoc("PRK")], [?], [?], [?], [*2074*], [#delta(-4)],
      [170], [#name("SHER Sadia Falak")], [#age(23)], [#assoc("PAK")], [?], [?], [?], [*2073*], [#delta(-4)],
      [171], [#name("李皓晴")], [#age(17)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2070*], [#delta(-4)],
      [172], [#name("卡塔日娜 格日博夫斯卡-弗朗茨")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2068*], [#delta(118)],
      [173], [#name("BARTOSOVA Hana")], [#age(28)], [#assoc("CZE")], [?], [?], [?], [*2067*], [#delta(10)],
      [174], [#name("MATTENET Audrey")], [#age(24)], [#assoc("FRA")], [?], [?], [?], [*2063*], [#delta(-14)],
      [175], [#name("JANTA-LIPINSKA Anna")], [#age(24)], [#assoc("POL")], [?], [?], [?], [*2062*], [#delta(-6)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("KIM Mijeong")], [#age(20)], [#assoc("KOR")], [?], [?], [?], [*2059*], [#delta(-6)],
      [177], [#name("黄淑琴")], [#age(25)], [#assoc("MAS")], [?], [?], [?], [*2057*], [#delta(29)],
      [178], [#name("BOGDANOVA Baiba")], [#age(22)], [#assoc("LAT")], [#right], [#shakehand], [#attack], [*2053*], [#delta(-5)],
      [179], [#name("DOMANIKU Besire")], [#age(37)], [#assoc("KOS")], [#right], [#shakehand], [#attack], [*2053*], [#delta(-4)],
      [180], [#name("ALI Meral Ildiz")], [#age(22)], [#assoc("TUR")], [?], [?], [?], [*2052*], [#delta(-38)],
      [181], [#name("梁夏银")], [#age(15)], [#assoc("COR")], [#right], [#shakehand], [#attack], [*2051*], [#delta(-4)],
      [182], [#name("佩特丽莎 索尔佳")], [#age(15)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2046*], [#delta(53)],
      [183], [#name("KIM Sujin")], [#age(25)], [#assoc("KOR")], [?], [?], [?], [*2045*], [#delta(-5)],
      [184], [#name("克里斯蒂娜 菲利")], [#age(30)], [#assoc("GRE")], [?], [?], [?], [*2042*], [#delta(-5)],
      [185], [#name("ZANARDI Marine")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2035*], [#delta(-9)],
      [186], [#name("汉娜 哈珀诺娃")], [#age(24)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2030*], [#delta(-6)],
      [187], [#name("LEE Hyun")], [#age(17)], [#assoc("KOR")], [?], [?], [?], [*2027*], [#delta(-6)],
      [188], [#name("GUFRANOVA Rimma")], [#age(18)], [#assoc("UZB")], [#right], [#shakehand], [#attack], [*2026*], [#delta(-6)],
      [189], [#name("穆玛 达斯")], [#age(25)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2025*], [#delta(23)],
      [190], [#name("MATZKE Laura")], [#age(21)], [#assoc("GER")], [?], [?], [?], [*2024*], [#delta(12)],
      [191], [#name("刘馨尹")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2023*], [#delta(-7)],
      [192], [#name("陈梦")], [#age(15)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2021*], [#delta(-7)],
      [193], [#name("AASEBO Marte")], [#age(19)], [#assoc("NOR")], [#right], [#shakehand], [#attack], [*2020*], [#delta(-7)],
      [194], [#name("EZZEDDINE Ruaida")], [#age(20)], [#assoc("VEN")], [?], [?], [?], [*2020*], [#delta(-7)],
      [195], [#name("卡梅利娅 雅各布")], [#age(17)], [#assoc("ROU")], [#right], [#shakehand], [#defense], [*2019*], [#delta(53)],
      [196], [#name("李依真")], [#age(22)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2017*], [#delta(-8)],
      [197], [#name("利吉娅 席尔瓦")], [#age(28)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2016*], [#delta(-8)],
      [198], [#name("KOZLOVSKAIAI Anna")], [#age(23)], [#assoc("RUS")], [?], [?], [?], [*2016*], [#delta(-8)],
      [199], [#name("金加 斯特凡斯卡")], [#age(29)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2015*], [#delta(-8)],
      [200], [#name("孙杨")], [#age(26)], [#assoc("NZL")], [?], [?], [?], [*2015*], [#delta(-8)],
    )
  )
