#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("刘诗雯")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3076*], [#delta(0)],
      [2], [#name("郭跃")], [#age(21)], [#assoc("CHN")], [?], [?], [?], [*2978*], [#delta(0)],
      [3], [#name("李晓霞")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2900*], [#delta(0)],
      [4], [#name("曹臻")], [#age(22)], [#assoc("CHN")], [?], [?], [?], [*2846*], [#delta(0)],
      [5], [#name("朴美英")], [#age(28)], [#assoc("KOR")], [?], [?], [?], [*2843*], [#delta(0)],
      [6], [#name("唐汭序")], [#age(28)], [#assoc("KOR")], [?], [?], [?], [*2827*], [#delta(0)],
      [7], [#name("丁宁")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2782*], [#delta(0)],
      [8], [#name("金景娥")], [#age(32)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2724*], [#delta(0)],
      [9], [#name("高军")], [#age(40)], [#assoc("USA")], [?], [?], [?], [*2716*], [#delta(0)],
      [10], [#name("范瑛")], [#age(23)], [#assoc("CHN")], [?], [?], [?], [*2714*], [#delta(0)],
      [11], [#name("彭陆洋")], [#age(24)], [#assoc("CHN")], [?], [?], [?], [*2707*], [#delta(0)],
      [12], [#name("冯天薇")], [#age(23)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2674*], [#delta(0)],
      [13], [#name("常晨晨")], [#age(23)], [#assoc("CHN")], [?], [?], [?], [*2657*], [#delta(0)],
      [14], [#name("刘佳")], [#age(27)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2653*], [#delta(0)],
      [15], [#name("埃尔卡 塞尔")], [#age(36)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2633*], [#delta(0)],
      [16], [#name("姜华珺")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2632*], [#delta(0)],
      [17], [#name("维多利亚 帕夫洛维奇")], [#age(31)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2629*], [#delta(0)],
      [18], [#name("于梦雨")], [#age(20)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2624*], [#delta(0)],
      [19], [#name("李佼")], [#age(36)], [#assoc("NED")], [#left], [#penhold], [#attack], [*2624*], [#delta(0)],
      [20], [#name("克里斯蒂娜 托特")], [#age(35)], [#assoc("HUN")], [?], [?], [?], [*2618*], [#delta(0)],
      [21], [#name("石垣优香")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2618*], [#delta(0)],
      [22], [#name("崔文渶")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2616*], [#delta(0)],
      [23], [#name("文佳")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2608*], [#delta(0)],
      [24], [#name("李洁")], [#age(25)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2607*], [#delta(0)],
      [25], [#name("沈燕飞")], [#age(30)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2601*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("李佳薇")], [#age(28)], [#assoc("SGP")], [?], [?], [?], [*2599*], [#delta(0)],
      [27], [#name("平野早矢香")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2593*], [#delta(0)],
      [28], [#name("伊韦塔 瓦切诺夫斯卡")], [#age(23)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2589*], [#delta(0)],
      [29], [#name("李晓丹")], [#age(19)], [#assoc("CHN")], [?], [?], [?], [*2586*], [#delta(0)],
      [30], [#name("玛丽娜 克拉夫琴科")], [#age(36)], [#assoc("ISR")], [#right], [#shakehand], [#attack], [*2574*], [#delta(1)],
      [31], [#name("若宫三纱子")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2569*], [#delta(1)],
      [32], [#name("姚彦")], [#age(21)], [#assoc("CHN")], [?], [?], [?], [*2562*], [#delta(1)],
      [33], [#name("福原爱")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2547*], [#delta(12)],
      [34], [#name("伊娃 奥多罗娃")], [#age(30)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2540*], [#delta(0)],
      [35], [#name("李雪")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#defense], [*2540*], [#delta(0)],
      [36], [#name("达娜 切霍娃")], [#age(26)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2537*], [#delta(0)],
      [37], [#name("尼科莱塔 斯特凡诺娃")], [#age(25)], [#assoc("ITA")], [#left], [#shakehand], [#attack], [*2537*], [#delta(0)],
      [38], [#name("金仲")], [#age(20)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2534*], [#delta(0)],
      [39], [#name("郭焱")], [#age(27)], [#assoc("CHN")], [?], [?], [?], [*2534*], [#delta(0)],
      [40], [#name("福冈春菜")], [#age(25)], [#assoc("JPN")], [?], [?], [?], [*2532*], [#delta(0)],
      [41], [#name("帖雅娜")], [#age(30)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2521*], [#delta(0)],
      [42], [#name("吴雪")], [#age(29)], [#assoc("DOM")], [?], [?], [?], [*2506*], [#delta(0)],
      [43], [#name("藤沼亚衣")], [#age(27)], [#assoc("JPN")], [?], [?], [?], [*2495*], [#delta(0)],
      [44], [#name("山梨有理")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2491*], [#delta(0)],
      [45], [#name("石川佳纯")], [#age(16)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2488*], [#delta(-15)],
      [46], [#name("王越古")], [#age(29)], [#assoc("SGP")], [?], [?], [?], [*2480*], [#delta(0)],
      [47], [#name("朱芳")], [#age(33)], [#assoc("ESP")], [?], [?], [?], [*2475*], [#delta(0)],
      [48], [#name("李瑨丽")], [#age(32)], [#assoc("NZL")], [?], [?], [?], [*2471*], [#delta(0)],
      [49], [#name("叶莲娜 库兹米娜")], [#age(20)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2463*], [#delta(0)],
      [50], [#name("木子")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2460*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("孙蓓蓓")], [#age(25)], [#assoc("SGP")], [?], [?], [?], [*2457*], [#delta(0)],
      [52], [#name("鲁塔 帕斯考斯基涅")], [#age(32)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2451*], [#delta(0)],
      [53], [#name("韦罗妮卡 帕夫洛维奇")], [#age(31)], [#assoc("BLR")], [?], [?], [?], [*2449*], [#delta(0)],
      [54], [#name("黄怡桦")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2443*], [#delta(0)],
      [55], [#name("柳絮飞")], [#age(28)], [#assoc("HKG")], [?], [?], [?], [*2442*], [#delta(0)],
      [56], [#name("雷娜塔 斯特尔比科娃")], [#age(30)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2441*], [#delta(0)],
      [57], [#name("米艾 斯科娃")], [#age(23)], [#assoc("DEN")], [#right], [#shakehand], [#attack], [*2438*], [#delta(0)],
      [58], [#name("SANG Xu Stephanie")], [#age(23)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2434*], [#delta(0)],
      [59], [#name("VORONOVA Anastasia")], [#age(24)], [#assoc("RUS")], [?], [?], [?], [*2431*], [#delta(0)],
      [60], [#name("科尔内莉亚 莫尔纳")], [#age(26)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2425*], [#delta(0)],
      [61], [#name("李倩")], [#age(23)], [#assoc("POL")], [#right], [#shakehand], [#defense], [*2421*], [#delta(0)],
      [62], [#name("吴佳多")], [#age(32)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2421*], [#delta(0)],
      [63], [#name("WANG Xuan")], [#age(20)], [#assoc("CHN")], [?], [?], [?], [*2420*], [#delta(0)],
      [64], [#name("林菱")], [#age(32)], [#assoc("HKG")], [?], [?], [?], [*2416*], [#delta(0)],
      [65], [#name("樋浦令子")], [#age(25)], [#assoc("JPN")], [?], [?], [?], [*2404*], [#delta(1)],
      [66], [#name("纳迪娜 博尔迈尔")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2397*], [#delta(1)],
      [67], [#name("石贺净")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2397*], [#delta(-2)],
      [68], [#name("金慧星")], [#age(16)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2390*], [#delta(0)],
      [69], [#name("森园美咲")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2390*], [#delta(0)],
      [70], [#name("孙祯琦")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2383*], [#delta(0)],
      [71], [#name("徐洁")], [#age(27)], [#assoc("POL")], [?], [?], [?], [*2382*], [#delta(0)],
      [72], [#name("安娜玛丽亚 埃尔德利")], [#age(24)], [#assoc("SRB")], [#right], [#shakehand], [#defense], [*2381*], [#delta(0)],
      [73], [#name("乔治娜 波塔")], [#age(24)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2375*], [#delta(0)],
      [74], [#name("侯美玲")], [#age(20)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2370*], [#delta(0)],
      [75], [#name("藤井优子")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2366*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("朴英淑")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2360*], [#delta(0)],
      [77], [#name("李嫱冰")], [#age(24)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2356*], [#delta(0)],
      [78], [#name("丹妮拉 多迪安")], [#age(21)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2354*], [#delta(0)],
      [79], [#name("谭文玲")], [#age(37)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2351*], [#delta(0)],
      [80], [#name("田惠庆")], [#age(32)], [#assoc("KOR")], [?], [?], [?], [*2343*], [#delta(0)],
      [81], [#name("克里斯汀 朗")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2343*], [#delta(0)],
      [82], [#name("藤井宽子")], [#age(27)], [#assoc("JPN")], [?], [?], [?], [*2341*], [#delta(0)],
      [83], [#name("文炫晶")], [#age(25)], [#assoc("KOR")], [?], [?], [?], [*2339*], [#delta(0)],
      [84], [#name("张瑞")], [#age(30)], [#assoc("HKG")], [?], [?], [?], [*2337*], [#delta(0)],
      [85], [#name("伊丽莎白 萨马拉")], [#age(20)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2333*], [#delta(0)],
      [86], [#name("小西杏")], [#age(29)], [#assoc("JPN")], [?], [?], [?], [*2331*], [#delta(0)],
      [87], [#name("SHIM Serom")], [#age(22)], [#assoc("KOR")], [?], [?], [?], [*2329*], [#delta(43)],
      [88], [#name("HAN Hye Song")], [#age(21)], [#assoc("PRK")], [?], [?], [?], [*2326*], [#delta(-1)],
      [89], [#name("高王")], [#age(29)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2325*], [#delta(-1)],
      [90], [#name("奥克萨娜 法德耶娃")], [#age(34)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2323*], [#delta(-1)],
      [91], [#name("TANIOKA Ayuka")], [#age(15)], [#assoc("JPN")], [?], [?], [?], [*2322*], [#delta(-1)],
      [92], [#name("武杨")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2304*], [#delta(-1)],
      [93], [#name("洪剑芳")], [#age(36)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2297*], [#delta(-1)],
      [94], [#name("熊乃仪")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2296*], [#delta(-1)],
      [95], [#name("玛格丽塔 佩索茨卡")], [#age(18)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2292*], [#delta(-1)],
      [96], [#name("朴晟惠")], [#age(23)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2286*], [#delta(0)],
      [97], [#name("CAO Lisi")], [#age(18)], [#assoc("CHN")], [?], [?], [?], [*2282*], [#delta(-2)],
      [98], [#name("KO Somi")], [#age(25)], [#assoc("KOR")], [?], [?], [?], [*2273*], [#delta(-1)],
      [99], [#name("KIM Soongsil")], [#age(28)], [#assoc("KOR")], [?], [?], [?], [*2258*], [#delta(-1)],
      [100], [#name("特蒂亚娜 比连科")], [#age(26)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2258*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("娜塔莉亚 帕尔蒂卡")], [#age(20)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2257*], [#delta(-1)],
      [102], [#name("李恩姬")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2256*], [#delta(-1)],
      [103], [#name("叶连娜 季米娜")], [#age(40)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2251*], [#delta(-1)],
      [104], [#name("SUN Jin")], [#age(29)], [#assoc("HKG")], [?], [?], [?], [*2248*], [#delta(-1)],
      [105], [#name("利娜 米西科尼特")], [#age(21)], [#assoc("LTU")], [?], [?], [?], [*2241*], [#delta(-1)],
      [106], [#name("玛丽亚 多尔吉赫")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2238*], [#delta(-1)],
      [107], [#name("苗苗")], [#age(28)], [#assoc("AUS")], [?], [?], [?], [*2238*], [#delta(-1)],
      [108], [#name("佩特拉 洛瓦斯")], [#age(29)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2235*], [#delta(-1)],
      [109], [#name("渡边裕子")], [#age(25)], [#assoc("JPN")], [?], [?], [?], [*2232*], [#delta(-1)],
      [110], [#name("塔玛拉 鲍罗斯")], [#age(32)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2230*], [#delta(-1)],
      [111], [#name("MOON Bosun")], [#age(23)], [#assoc("KOR")], [?], [?], [?], [*2230*], [#delta(-1)],
      [112], [#name("羡宜芳")], [#age(32)], [#assoc("FRA")], [#right], [#shakehand], [#defense], [*2229*], [#delta(-1)],
      [113], [#name("郑怡静")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2228*], [#delta(-1)],
      [114], [#name("安东尼娜 希曼斯卡")], [#age(26)], [#assoc("POL")], [?], [?], [?], [*2225*], [#delta(-1)],
      [115], [#name("卡塔琳娜 加京斯卡")], [#age(39)], [#assoc("BUL")], [?], [?], [?], [*2222*], [#delta(-1)],
      [116], [#name("艾米丽 索尔佳")], [#age(19)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2221*], [#delta(-1)],
      [117], [#name("梁夏银")], [#age(15)], [#assoc("COR")], [#right], [#shakehand], [#attack], [*2218*], [#delta(-1)],
      [118], [#name("PETTERSSON Malin")], [#age(18)], [#assoc("SWE")], [?], [?], [?], [*2216*], [#delta(-1)],
      [119], [#name("张墨")], [#age(20)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2214*], [#delta(-1)],
      [120], [#name("LI Bin")], [#age(21)], [#assoc("HUN")], [?], [?], [?], [*2213*], [#delta(-1)],
      [121], [#name("卡塔日娜 格日博夫斯卡-弗朗茨")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2208*], [#delta(-1)],
      [122], [#name("于国诗")], [#age(23)], [#assoc("HKG")], [?], [?], [?], [*2200*], [#delta(-1)],
      [123], [#name("孙杨")], [#age(26)], [#assoc("NZL")], [?], [?], [?], [*2195*], [#delta(-1)],
      [124], [#name("埃卡特里娜 恩图拉基")], [#age(27)], [#assoc("GRE")], [?], [?], [?], [*2194*], [#delta(-1)],
      [125], [#name("卡琳娜 荣松")], [#age(30)], [#assoc("SWE")], [?], [?], [?], [*2193*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("徐孝元")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2192*], [#delta(-1)],
      [127], [#name("HE Sirin")], [#age(20)], [#assoc("TUR")], [?], [?], [?], [*2191*], [#delta(-1)],
      [128], [#name("安娜 蒂克米罗娃")], [#age(25)], [#assoc("RUS")], [?], [?], [?], [*2185*], [#delta(-1)],
      [129], [#name("穆玛 达斯")], [#age(25)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2179*], [#delta(-1)],
      [130], [#name("卡特琳娜 佩卡沃娃")], [#age(22)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2178*], [#delta(-1)],
      [131], [#name("金贞弦")], [#age(24)], [#assoc("KOR")], [?], [?], [?], [*2178*], [#delta(3)],
      [132], [#name("桑德拉 佩尔格尔")], [#age(21)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2169*], [#delta(-1)],
      [133], [#name("越崎步")], [#age(28)], [#assoc("JPN")], [?], [?], [?], [*2167*], [#delta(-1)],
      [134], [#name("伊雷妮 伊万坎")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2167*], [#delta(-1)],
      [135], [#name("玛蒂尔达 埃克霍尔姆")], [#age(27)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2163*], [#delta(0)],
      [136], [#name("阿尼萨拉 穆昂苏克")], [#age(33)], [#assoc("THA")], [?], [?], [?], [*2160*], [#delta(0)],
      [137], [#name("倪夏莲")], [#age(46)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2157*], [#delta(0)],
      [138], [#name("KANG Misoon")], [#age(16)], [#assoc("KOR")], [?], [?], [?], [*2156*], [#delta(0)],
      [139], [#name("KASABOVA Asya")], [#age(33)], [#assoc("BUL")], [?], [?], [?], [*2154*], [#delta(0)],
      [140], [#name("卡罗尔 格伦迪施")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2151*], [#delta(0)],
      [141], [#name("乔安娜 德林克霍尔")], [#age(22)], [#assoc("ENG")], [#right], [#shakehand], [#defense], [*2146*], [#delta(0)],
      [142], [#name("HAAN Simone")], [#age(25)], [#assoc("LUX")], [?], [?], [?], [*2142*], [#delta(0)],
      [143], [#name("YOON Suwon")], [#age(26)], [#assoc("KOR")], [?], [?], [?], [*2140*], [#delta(0)],
      [144], [#name("RAMOS Fabiola")], [#age(32)], [#assoc("VEN")], [?], [?], [?], [*2123*], [#delta(0)],
      [145], [#name("萨拉 拉米雷斯")], [#age(22)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2123*], [#delta(0)],
      [146], [#name("劳拉 罗伯逊")], [#age(25)], [#assoc("GER")], [?], [?], [?], [*2119*], [#delta(0)],
      [147], [#name("SAKO Karin")], [#age(21)], [#assoc("BRA")], [?], [?], [?], [*2119*], [#delta(0)],
      [148], [#name("YANG Fen")], [#age(27)], [#assoc("CGO")], [?], [?], [?], [*2118*], [#delta(0)],
      [149], [#name("丽塔 凯尔泰")], [#age(31)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2118*], [#delta(0)],
      [150], [#name("MIKHAYLOVA Olga")], [#age(22)], [#assoc("RUS")], [?], [?], [?], [*2116*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("金加 斯特凡斯卡")], [#age(29)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2115*], [#delta(0)],
      [152], [#name("塔尼娅 克拉默")], [#age(29)], [#assoc("GER")], [?], [?], [?], [*2114*], [#delta(0)],
      [153], [#name("亚娜 诺斯科娃")], [#age(15)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2111*], [#delta(0)],
      [154], [#name("加利娅 德沃拉克")], [#age(21)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2110*], [#delta(0)],
      [155], [#name("CHAKRABORTY Kasturi")], [#age(28)], [#assoc("IND")], [?], [?], [?], [*2110*], [#delta(0)],
      [156], [#name("斯韦特兰娜 加尼娜")], [#age(31)], [#assoc("RUS")], [?], [?], [?], [*2109*], [#delta(0)],
      [157], [#name("FETUKHINA Margarita")], [#age(21)], [#assoc("RUS")], [?], [?], [?], [*2105*], [#delta(0)],
      [158], [#name("林佳慧")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2105*], [#delta(0)],
      [159], [#name("佩特丽莎 索尔佳")], [#age(15)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2101*], [#delta(0)],
      [160], [#name("马丁娜 波哈尔")], [#age(28)], [#assoc("SLO")], [?], [?], [?], [*2100*], [#delta(0)],
      [161], [#name("尤利娅 内库拉")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2098*], [#delta(0)],
      [162], [#name("刘媛")], [#age(24)], [#assoc("AUT")], [#right], [#penhold], [#attack], [*2095*], [#delta(0)],
      [163], [#name("GUAN Mengyuan")], [#age(17)], [#assoc("HKG")], [?], [?], [?], [*2091*], [#delta(0)],
      [164], [#name("AGGARWAL Neha")], [#age(19)], [#assoc("IND")], [?], [?], [?], [*2090*], [#delta(0)],
      [165], [#name("尤利娅 普罗霍罗娃")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2088*], [#delta(0)],
      [166], [#name("波琳娜 米哈伊洛娃")], [#age(23)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2087*], [#delta(0)],
      [167], [#name("LEE Hyelin")], [#age(20)], [#assoc("KOR")], [?], [?], [?], [*2087*], [#delta(65)],
      [168], [#name("PETZNER Martina")], [#age(25)], [#assoc("AUT")], [?], [?], [?], [*2087*], [#delta(-1)],
      [169], [#name("克里斯蒂娜 希里奇")], [#age(17)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2077*], [#delta(-1)],
      [170], [#name("马莉薇")], [#age(26)], [#assoc("MAS")], [#right], [#shakehand], [#attack], [*2076*], [#delta(-1)],
      [171], [#name("HYON Ryon Hui")], [#age(20)], [#assoc("PRK")], [?], [?], [?], [*2074*], [#delta(-1)],
      [172], [#name("SHER Sadia Falak")], [#age(23)], [#assoc("PAK")], [?], [?], [?], [*2073*], [#delta(-1)],
      [173], [#name("利吉娅 席尔瓦")], [#age(28)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2071*], [#delta(-1)],
      [174], [#name("BARTOSOVA Hana")], [#age(28)], [#assoc("CZE")], [?], [?], [?], [*2067*], [#delta(-1)],
      [175], [#name("MUHLBACH Kathrin")], [#age(17)], [#assoc("GER")], [?], [?], [?], [*2063*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("JANTA-LIPINSKA Anna")], [#age(24)], [#assoc("POL")], [?], [?], [?], [*2062*], [#delta(-1)],
      [177], [#name("黄淑琴")], [#age(25)], [#assoc("MAS")], [?], [?], [?], [*2060*], [#delta(-1)],
      [178], [#name("KIM Mijeong")], [#age(20)], [#assoc("KOR")], [?], [?], [?], [*2059*], [#delta(-1)],
      [179], [#name("吴颖岚")], [#age(17)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2058*], [#delta(-1)],
      [180], [#name("ALI Meral Ildiz")], [#age(22)], [#assoc("TUR")], [?], [?], [?], [*2052*], [#delta(-1)],
      [181], [#name("多拉 马达拉斯")], [#age(16)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2050*], [#delta(-1)],
      [182], [#name("叶莲娜 莫克鲁索娃")], [#age(29)], [#assoc("MDA")], [?], [?], [?], [*2049*], [#delta(-1)],
      [183], [#name("亚历山德拉 普里瓦洛娃")], [#age(22)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2046*], [#delta(-1)],
      [184], [#name("KIM Sujin")], [#age(25)], [#assoc("KOR")], [?], [?], [?], [*2045*], [#delta(-1)],
      [185], [#name("EZZEDDINE Ruaida")], [#age(20)], [#assoc("VEN")], [?], [?], [?], [*2044*], [#delta(-1)],
      [186], [#name("TOMAZINI Jana")], [#age(23)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2042*], [#delta(-1)],
      [187], [#name("萨宾 温特")], [#age(17)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2037*], [#delta(-1)],
      [188], [#name("ZANARDI Marine")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2035*], [#delta(-1)],
      [189], [#name("卡梅利娅 雅各布")], [#age(17)], [#assoc("ROU")], [#right], [#shakehand], [#defense], [*2034*], [#delta(-1)],
      [190], [#name("DESSAINT Aurore")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2028*], [#delta(-1)],
      [191], [#name("汉娜 哈珀诺娃")], [#age(24)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2028*], [#delta(-1)],
      [192], [#name("SZCZERKOWSKA Magdalena")], [#age(17)], [#assoc("POL")], [?], [?], [?], [*2027*], [#delta(-1)],
      [193], [#name("LEE Hyun")], [#age(17)], [#assoc("KOR")], [?], [?], [?], [*2027*], [#delta(-1)],
      [194], [#name("ROVANI Silir")], [#age(21)], [#assoc("INA")], [#right], [#shakehand], [#attack], [*2026*], [#delta(-1)],
      [195], [#name("MATZKE Laura")], [#age(21)], [#assoc("GER")], [?], [?], [?], [*2024*], [#delta(-1)],
      [196], [#name("刘馨尹")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2023*], [#delta(-1)],
      [197], [#name("陈梦")], [#age(15)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2021*], [#delta(-1)],
      [198], [#name("AASEBO Marte")], [#age(19)], [#assoc("NOR")], [#right], [#shakehand], [#attack], [*2020*], [#delta(-1)],
      [199], [#name("KOZLOVSKAIAI Anna")], [#age(23)], [#assoc("RUS")], [?], [?], [?], [*2018*], [#delta(-1)],
      [200], [#name("李依真")], [#age(22)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2017*], [#delta(-1)],
    )
  )
