#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("马龙")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3193*], [#delta(0)],
      [2], [#name("樊振东")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3075*], [#delta(0)],
      [3], [#name("许昕")], [#age(27)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*2970*], [#delta(0)],
      [4], [#name("李尚洙")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2922*], [#delta(0)],
      [5], [#name("闫安")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2917*], [#delta(0)],
      [6], [#name("水谷隼")], [#age(28)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2875*], [#delta(0)],
      [7], [#name("蒂姆 波尔")], [#age(36)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2874*], [#delta(0)],
      [8], [#name("迪米特里 奥恰洛夫")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2858*], [#delta(0)],
      [9], [#name("方博")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2856*], [#delta(0)],
      [10], [#name("黄镇廷")], [#age(26)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2831*], [#delta(2)],
      [11], [#name("弗拉基米尔 萨姆索诺夫")], [#age(41)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2829*], [#delta(12)],
      [12], [#name("梁靖崑")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2828*], [#delta(1)],
      [13], [#name("林高远")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2814*], [#delta(2)],
      [14], [#name("吉田雅己")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2812*], [#delta(-4)],
      [15], [#name("丹羽孝希")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2777*], [#delta(-1)],
      [16], [#name("周雨")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2775*], [#delta(0)],
      [17], [#name("卢文 菲鲁斯")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2773*], [#delta(0)],
      [18], [#name("张本智和")], [#age(14)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2764*], [#delta(-7)],
      [19], [#name("巴斯蒂安 斯蒂格")], [#age(36)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2762*], [#delta(1)],
      [20], [#name("张继科")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2760*], [#delta(2)],
      [21], [#name("雨果 卡尔德拉诺")], [#age(21)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2754*], [#delta(3)],
      [22], [#name("ACHANTA Sharath")], [#age(35)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2745*], [#delta(3)],
      [23], [#name("李平")], [#age(31)], [#assoc("QAT")], [#right], [#shakehand], [#attack], [*2732*], [#delta(4)],
      [24], [#name("庄智渊")], [#age(36)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2726*], [#delta(-3)],
      [25], [#name("丁祥恩")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2724*], [#delta(3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("马蒂亚斯 法尔克")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2724*], [#delta(7)],
      [27], [#name("林钟勋")], [#age(20)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2723*], [#delta(8)],
      [28], [#name("马克斯 弗雷塔斯")], [#age(29)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2723*], [#delta(-10)],
      [29], [#name("西蒙 高兹")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2722*], [#delta(40)],
      [30], [#name("PISTEJ Lubomir")], [#age(33)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2721*], [#delta(-1)],
      [31], [#name("乔纳森 格罗斯")], [#age(25)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2716*], [#delta(-1)],
      [32], [#name("吉田海伟")], [#age(36)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2709*], [#delta(-1)],
      [33], [#name("奥维迪乌 伊奥内斯库")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2706*], [#delta(-1)],
      [34], [#name("上田仁")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2703*], [#delta(-15)],
      [35], [#name("吉村真晴")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2702*], [#delta(-1)],
      [36], [#name("赵胜敏")], [#age(19)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2688*], [#delta(39)],
      [37], [#name("松平健太")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2688*], [#delta(0)],
      [38], [#name("艾曼纽 莱贝松")], [#age(29)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2684*], [#delta(-2)],
      [39], [#name("亚历山大 希巴耶夫")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2682*], [#delta(-13)],
      [40], [#name("大岛祐哉")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2679*], [#delta(16)],
      [41], [#name("DRINKHALL Paul")], [#age(27)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2675*], [#delta(63)],
      [42], [#name("HO Kwan Kit")], [#age(20)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2672*], [#delta(-4)],
      [43], [#name("王楚钦")], [#age(17)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2668*], [#delta(7)],
      [44], [#name("周恺")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2663*], [#delta(-3)],
      [45], [#name("奥马尔 阿萨尔")], [#age(26)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2660*], [#delta(-6)],
      [46], [#name("里卡多 瓦尔特")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2656*], [#delta(-4)],
      [47], [#name("雅克布 迪亚斯")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2650*], [#delta(-2)],
      [48], [#name("郑荣植")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2650*], [#delta(-2)],
      [49], [#name("特里斯坦 弗洛雷")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2645*], [#delta(39)],
      [50], [#name("廖振珽")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2644*], [#delta(-10)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("TAZOE Kenta")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2641*], [#delta(-4)],
      [52], [#name("OUAICHE Stephane")], [#age(24)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2637*], [#delta(-4)],
      [53], [#name("刘丁硕")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2637*], [#delta(-4)],
      [54], [#name("木造勇人")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2629*], [#delta(-11)],
      [55], [#name("MACHI Asuka")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2628*], [#delta(-4)],
      [56], [#name("朴申赫")], [#age(24)], [#assoc("PRK")], [#left], [#penhold], [#attack], [*2627*], [#delta(-4)],
      [57], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(37)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2627*], [#delta(-4)],
      [58], [#name("SZOCS Hunor")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2625*], [#delta(-4)],
      [59], [#name("夸德里 阿鲁纳")], [#age(29)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2624*], [#delta(31)],
      [60], [#name("博扬 托基奇")], [#age(36)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2624*], [#delta(-3)],
      [61], [#name("GERELL Par")], [#age(35)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2621*], [#delta(-3)],
      [62], [#name("吉村和弘")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2619*], [#delta(-3)],
      [63], [#name("达米安 艾洛伊")], [#age(48)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2618*], [#delta(-3)],
      [64], [#name("陈卫星")], [#age(45)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2615*], [#delta(-3)],
      [65], [#name("WANG Zengyi")], [#age(34)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2615*], [#delta(-3)],
      [66], [#name("KIM Donghyun")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2611*], [#delta(-3)],
      [67], [#name("托米斯拉夫 普卡")], [#age(21)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2611*], [#delta(-3)],
      [68], [#name("江天一")], [#age(29)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2610*], [#delta(-3)],
      [69], [#name("及川瑞基")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2610*], [#delta(-3)],
      [70], [#name("安东 卡尔伯格")], [#age(20)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2608*], [#delta(-3)],
      [71], [#name("LAM Siu Hang")], [#age(21)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2606*], [#delta(-3)],
      [72], [#name("诺沙迪 阿拉米扬")], [#age(26)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2605*], [#delta(-2)],
      [73], [#name("神巧也")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2603*], [#delta(-2)],
      [74], [#name("王臻")], [#age(32)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2601*], [#delta(-1)],
      [75], [#name("张禹珍")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2600*], [#delta(-31)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("TREGLER Tomas")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2600*], [#delta(0)],
      [77], [#name("林昀儒")], [#age(16)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2599*], [#delta(31)],
      [78], [#name("PERSSON Jon")], [#age(31)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2599*], [#delta(-1)],
      [79], [#name("RYUZAKI Tonin")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2599*], [#delta(-1)],
      [80], [#name("薛飞")], [#age(18)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2598*], [#delta(-1)],
      [81], [#name("利亚姆 皮切福德")], [#age(24)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2595*], [#delta(-1)],
      [82], [#name("克里斯坦 卡尔松")], [#age(26)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2592*], [#delta(-1)],
      [83], [#name("安德烈 加奇尼")], [#age(31)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2592*], [#delta(-1)],
      [84], [#name("村松雄斗")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2592*], [#delta(-29)],
      [85], [#name("ROBINOT Quentin")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2592*], [#delta(-2)],
      [86], [#name("尼马 阿拉米安")], [#age(25)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2591*], [#delta(-2)],
      [87], [#name("高宁")], [#age(35)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2588*], [#delta(-15)],
      [88], [#name("TAKAKIWA Taku")], [#age(29)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2586*], [#delta(-3)],
      [89], [#name("罗伯特 加尔多斯")], [#age(38)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2585*], [#delta(-3)],
      [90], [#name("斯特凡 菲格尔")], [#age(29)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2583*], [#delta(-3)],
      [91], [#name("丹尼尔 哈贝松")], [#age(31)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2582*], [#delta(-2)],
      [92], [#name("帕特里克 弗朗西斯卡")], [#age(25)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2576*], [#delta(0)],
      [93], [#name("ANTHONY Amalraj")], [#age(31)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2576*], [#delta(-2)],
      [94], [#name("金珉锡")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2572*], [#delta(-1)],
      [95], [#name("MATSUYAMA Yuki")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2570*], [#delta(-1)],
      [96], [#name("蒂亚戈 阿波罗尼亚")], [#age(31)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2570*], [#delta(-1)],
      [97], [#name("LAKATOS Tamas")], [#age(22)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2570*], [#delta(-1)],
      [98], [#name("贝内迪克特 杜达")], [#age(23)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2569*], [#delta(-24)],
      [99], [#name("阿德里安 克里桑")], [#age(37)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2568*], [#delta(-2)],
      [100], [#name("FANG Yinchi")], [#age(21)], [#assoc("CHN")], [?], [?], [?], [*2566*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("塞德里克 纽廷克")], [#age(24)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2566*], [#delta(-2)],
      [102], [#name("MONTEIRO Joao")], [#age(34)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2566*], [#delta(-2)],
      [103], [#name("KANG Dongsoo")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2559*], [#delta(-1)],
      [104], [#name("HACHARD Antoine")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2556*], [#delta(-1)],
      [105], [#name("BOBOCICA Mihai")], [#age(31)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2554*], [#delta(0)],
      [106], [#name("寇磊")], [#age(30)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2552*], [#delta(0)],
      [107], [#name("达科 约奇克")], [#age(19)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2551*], [#delta(0)],
      [108], [#name("哈米特 德赛")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2550*], [#delta(-7)],
      [109], [#name("KANG Wi Hun")], [#age(28)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2546*], [#delta(0)],
      [110], [#name("MONTEIRO Thiago")], [#age(36)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2545*], [#delta(0)],
      [111], [#name("森园政崇")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2545*], [#delta(0)],
      [112], [#name("LANDRIEU Andrea")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2542*], [#delta(0)],
      [113], [#name("CANTERO Jesus")], [#age(35)], [#assoc("ESP")], [#right], [#penhold], [#attack], [*2542*], [#delta(0)],
      [114], [#name("金光宏畅")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2539*], [#delta(0)],
      [115], [#name("VRABLIK Jiri")], [#age(34)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2534*], [#delta(0)],
      [116], [#name("SHETTY Sanil")], [#age(28)], [#assoc("IND")], [#left], [#shakehand], [#attack], [*2533*], [#delta(92)],
      [117], [#name("NORDBERG Hampus")], [#age(30)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2533*], [#delta(-1)],
      [118], [#name("OBESLO Michal")], [#age(28)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2533*], [#delta(-1)],
      [119], [#name("POLANSKY Tomas")], [#age(19)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2531*], [#delta(-1)],
      [120], [#name("LIVENTSOV Alexey")], [#age(36)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2526*], [#delta(0)],
      [121], [#name("ANDERSSON Harald")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2524*], [#delta(0)],
      [122], [#name("TAKAMI Masaki")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2523*], [#delta(-3)],
      [123], [#name("德米特里 佩罗普科夫")], [#age(37)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2523*], [#delta(-1)],
      [124], [#name("HIRANO Yuki")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2522*], [#delta(-1)],
      [125], [#name("PARK Jeongwoo")], [#age(20)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2522*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("SALEH Ahmed")], [#age(38)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2522*], [#delta(5)],
      [127], [#name("ANGLES Enzo")], [#age(22)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2520*], [#delta(-2)],
      [128], [#name("PAPAGEORGIOU Konstantinos")], [#age(38)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2518*], [#delta(-2)],
      [129], [#name("ORT Kilian")], [#age(21)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2517*], [#delta(-2)],
      [130], [#name("GAVLAS Antonin")], [#age(32)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2517*], [#delta(-2)],
      [131], [#name("朴康贤")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2517*], [#delta(43)],
      [132], [#name("基里尔 斯卡奇科夫")], [#age(30)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2515*], [#delta(-3)],
      [133], [#name("斯蒂芬 门格尔")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2514*], [#delta(-3)],
      [134], [#name("FLORAS Robert")], [#age(25)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2508*], [#delta(-2)],
      [135], [#name("徐海东")], [#age(17)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2505*], [#delta(-2)],
      [136], [#name("ISMAILOV Sadi")], [#age(21)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2504*], [#delta(-2)],
      [137], [#name("AKKUZU Can")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2504*], [#delta(-2)],
      [138], [#name("FERTIKOWSKI Pawel")], [#age(27)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2504*], [#delta(-2)],
      [139], [#name("CARVALHO Diogo")], [#age(25)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2503*], [#delta(-1)],
      [140], [#name("SALIFOU Abdel-Kader")], [#age(28)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2502*], [#delta(-1)],
      [141], [#name("PENG Wang-Wei")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2501*], [#delta(-1)],
      [142], [#name("GERALDO Joao")], [#age(22)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2499*], [#delta(-1)],
      [143], [#name("米凯尔 梅兹")], [#age(36)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2499*], [#delta(-1)],
      [144], [#name("SAKAI Asuka")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2498*], [#delta(-1)],
      [145], [#name("基里尔 格拉西缅科")], [#age(21)], [#assoc("KAZ")], [#right], [#shakehand], [#attack], [*2497*], [#delta(0)],
      [146], [#name("WALKER Samuel")], [#age(22)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2497*], [#delta(0)],
      [147], [#name("阿尔瓦罗 罗布勒斯")], [#age(26)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2496*], [#delta(0)],
      [148], [#name("汪洋")], [#age(23)], [#assoc("SVK")], [#right], [#shakehand], [#defense], [*2496*], [#delta(0)],
      [149], [#name("SEYFRIED Joe")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2496*], [#delta(0)],
      [150], [#name("LAKEEV Vasily")], [#age(33)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2495*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("SEO Hyundeok")], [#age(26)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2494*], [#delta(18)],
      [152], [#name("LEVENKO Andreas")], [#age(19)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2493*], [#delta(0)],
      [153], [#name("ARVIDSSON Simon")], [#age(27)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2493*], [#delta(0)],
      [154], [#name("YANG Shuo")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2492*], [#delta(0)],
      [155], [#name("TSUBOI Yuma")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2488*], [#delta(0)],
      [156], [#name("GNANASEKARAN Sathiyan")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2488*], [#delta(53)],
      [157], [#name("BOULOUSSA Mehdi")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2486*], [#delta(0)],
      [158], [#name("SGOUROPOULOS Ioannis")], [#age(17)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2485*], [#delta(96)],
      [159], [#name("KIM Minhyeok")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2485*], [#delta(69)],
      [160], [#name("BROSSIER Benjamin")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2480*], [#delta(-1)],
      [161], [#name("徐瑛彬")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2480*], [#delta(29)],
      [162], [#name("NAGY Krisztian")], [#age(28)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2479*], [#delta(-2)],
      [163], [#name("TSUBOI Gustavo")], [#age(32)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2476*], [#delta(33)],
      [164], [#name("侯英超")], [#age(37)], [#assoc("CAN")], [#right], [#shakehand], [#defense], [*2476*], [#delta(-2)],
      [165], [#name("BAIBULDIN Andrei")], [#age(31)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2475*], [#delta(-2)],
      [166], [#name("雅罗斯列夫 扎姆登科")], [#age(29)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2474*], [#delta(-2)],
      [167], [#name("MAJOROS Bence")], [#age(20)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2473*], [#delta(-2)],
      [168], [#name("卡纳克 贾哈")], [#age(17)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2473*], [#delta(-10)],
      [169], [#name("CHO Eonrae")], [#age(31)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2471*], [#delta(-3)],
      [170], [#name("NG Pak Nam")], [#age(19)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2469*], [#delta(-3)],
      [171], [#name("FLORITZ Philipp")], [#age(26)], [#assoc("BUL")], [#right], [#shakehand], [#attack], [*2468*], [#delta(-3)],
      [172], [#name("詹斯 伦德奎斯特")], [#age(38)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2465*], [#delta(-2)],
      [173], [#name("BRODD Viktor")], [#age(27)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2465*], [#delta(-2)],
      [174], [#name("BAGGALEY Andrew")], [#age(34)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2462*], [#delta(-37)],
      [175], [#name("MACHADO Carlos")], [#age(37)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2461*], [#delta(-3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("JANCARIK Lubomir")], [#age(30)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2460*], [#delta(-3)],
      [177], [#name("SAMBE Kohei")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2460*], [#delta(-2)],
      [178], [#name("宇田幸矢")], [#age(16)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2459*], [#delta(-34)],
      [179], [#name("TORIOLA Segun")], [#age(43)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2456*], [#delta(-2)],
      [180], [#name("陈建安")], [#age(26)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2452*], [#delta(-29)],
      [181], [#name("MATSUDAIRA Kenji")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2451*], [#delta(0)],
      [182], [#name("安宰贤")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2451*], [#delta(-21)],
      [183], [#name("YU Heyi")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2450*], [#delta(-3)],
      [184], [#name("户上隼辅")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2449*], [#delta(4)],
      [185], [#name("ZHAI Yujia")], [#age(22)], [#assoc("DEN")], [#right], [#shakehand], [#attack], [*2448*], [#delta(-3)],
      [186], [#name("JOUTI Eric")], [#age(23)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2446*], [#delta(31)],
      [187], [#name("AFANADOR Brian")], [#age(20)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2442*], [#delta(-3)],
      [188], [#name("CHIANG Hung-Chieh")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2441*], [#delta(16)],
      [189], [#name("MADRID Marcos")], [#age(31)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2437*], [#delta(-13)],
      [190], [#name("GHOSH Soumyajit")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2437*], [#delta(-5)],
      [191], [#name("REED Daniel")], [#age(28)], [#assoc("ENG")], [?], [?], [?], [*2437*], [#delta(-5)],
      [192], [#name("SIRUCEK Pavel")], [#age(25)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2435*], [#delta(-5)],
      [193], [#name("贝内德克 奥拉")], [#age(26)], [#assoc("FIN")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-37)],
      [194], [#name("KOJIC Frane")], [#age(25)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-5)],
      [195], [#name("GAUZY Paul")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2429*], [#delta(-3)],
      [196], [#name("PAIKOV Mikhail")], [#age(28)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2429*], [#delta(-3)],
      [197], [#name("KONECNY Tomas")], [#age(32)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2426*], [#delta(-3)],
      [198], [#name("KOZUL Deni")], [#age(20)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2426*], [#delta(-3)],
      [199], [#name("卡林尼科斯 格林卡")], [#age(45)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2426*], [#delta(-2)],
      [200], [#name("邱党")], [#age(21)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2424*], [#delta(-1)],
    )
  )
