#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("马龙")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3193*], [#delta(0)],
      [2], [#name("樊振东")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3029*], [#delta(0)],
      [3], [#name("林高远")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2988*], [#delta(11)],
      [4], [#name("许昕")], [#age(27)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*2970*], [#delta(-1)],
      [5], [#name("水谷隼")], [#age(28)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2937*], [#delta(2)],
      [6], [#name("蒂姆 波尔")], [#age(36)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2899*], [#delta(2)],
      [7], [#name("闫安")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2897*], [#delta(-2)],
      [8], [#name("方博")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2853*], [#delta(1)],
      [9], [#name("张本智和")], [#age(14)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2847*], [#delta(1)],
      [10], [#name("迪米特里 奥恰洛夫")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2842*], [#delta(-4)],
      [11], [#name("弗拉基米尔 萨姆索诺夫")], [#age(41)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2829*], [#delta(1)],
      [12], [#name("庄智渊")], [#age(36)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2819*], [#delta(14)],
      [13], [#name("李尚洙")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2816*], [#delta(-9)],
      [14], [#name("西蒙 高兹")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2800*], [#delta(30)],
      [15], [#name("梁靖崑")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2797*], [#delta(-2)],
      [16], [#name("松平健太")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2773*], [#delta(3)],
      [17], [#name("雨果 卡尔德拉诺")], [#age(21)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2761*], [#delta(1)],
      [18], [#name("张继科")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2760*], [#delta(3)],
      [19], [#name("陈建安")], [#age(26)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2757*], [#delta(64)],
      [20], [#name("奥马尔 阿萨尔")], [#age(26)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2745*], [#delta(22)],
      [21], [#name("巴斯蒂安 斯蒂格")], [#age(36)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2743*], [#delta(1)],
      [22], [#name("丹羽孝希")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2742*], [#delta(-7)],
      [23], [#name("吉田雅己")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2729*], [#delta(-3)],
      [24], [#name("马克斯 弗雷塔斯")], [#age(29)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2726*], [#delta(5)],
      [25], [#name("周雨")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2723*], [#delta(-9)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("卢文 菲鲁斯")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2719*], [#delta(-9)],
      [27], [#name("丁祥恩")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2717*], [#delta(0)],
      [28], [#name("马蒂亚斯 法尔克")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2711*], [#delta(0)],
      [29], [#name("上田仁")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2710*], [#delta(-5)],
      [30], [#name("吉田海伟")], [#age(36)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2709*], [#delta(2)],
      [31], [#name("薛飞")], [#age(18)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2707*], [#delta(28)],
      [32], [#name("乔纳森 格罗斯")], [#age(25)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2705*], [#delta(16)],
      [33], [#name("林钟勋")], [#age(20)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2702*], [#delta(0)],
      [34], [#name("李平")], [#age(31)], [#assoc("QAT")], [#right], [#shakehand], [#attack], [*2701*], [#delta(0)],
      [35], [#name("寇磊")], [#age(30)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2694*], [#delta(80)],
      [36], [#name("安德烈 加奇尼")], [#age(31)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2690*], [#delta(46)],
      [37], [#name("及川瑞基")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2685*], [#delta(1)],
      [38], [#name("亚历山大 希巴耶夫")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2682*], [#delta(2)],
      [39], [#name("朴申赫")], [#age(24)], [#assoc("PRK")], [#left], [#penhold], [#attack], [*2680*], [#delta(2)],
      [40], [#name("WALTHER Ricardo")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2675*], [#delta(20)],
      [41], [#name("克里斯坦 卡尔松")], [#age(26)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2671*], [#delta(11)],
      [42], [#name("林昀儒")], [#age(16)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2670*], [#delta(-11)],
      [43], [#name("ACHANTA Sharath")], [#age(35)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2667*], [#delta(-20)],
      [44], [#name("赵胜敏")], [#age(19)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2666*], [#delta(-8)],
      [45], [#name("周恺")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2663*], [#delta(2)],
      [46], [#name("王楚钦")], [#age(17)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2661*], [#delta(-1)],
      [47], [#name("森园政崇")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2659*], [#delta(24)],
      [48], [#name("安东 卡尔伯格")], [#age(20)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2658*], [#delta(-9)],
      [49], [#name("夸德里 阿鲁纳")], [#age(29)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2655*], [#delta(2)],
      [50], [#name("特里斯坦 弗洛雷")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2653*], [#delta(5)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("郑荣植")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2650*], [#delta(3)],
      [52], [#name("吉村真晴")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2648*], [#delta(-17)],
      [53], [#name("吉村和弘")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2646*], [#delta(24)],
      [54], [#name("GERELL Par")], [#age(35)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2644*], [#delta(-24)],
      [55], [#name("蒂亚戈 阿波罗尼亚")], [#age(31)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2644*], [#delta(57)],
      [56], [#name("诺沙迪 阿拉米扬")], [#age(26)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2640*], [#delta(8)],
      [57], [#name("博扬 托基奇")], [#age(36)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2639*], [#delta(46)],
      [58], [#name("OUAICHE Stephane")], [#age(24)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2637*], [#delta(-1)],
      [59], [#name("刘丁硕")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2637*], [#delta(-1)],
      [60], [#name("TREGLER Tomas")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2636*], [#delta(27)],
      [61], [#name("黄镇廷")], [#age(26)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2636*], [#delta(-50)],
      [62], [#name("TAZOE Kenta")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2633*], [#delta(-13)],
      [63], [#name("MONTEIRO Joao")], [#age(34)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2632*], [#delta(35)],
      [64], [#name("朱霖峰")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2630*], [#delta(-3)],
      [65], [#name("艾曼纽 莱贝松")], [#age(29)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2629*], [#delta(-40)],
      [66], [#name("PISTEJ Lubomir")], [#age(33)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2622*], [#delta(-10)],
      [67], [#name("达米安 艾洛伊")], [#age(48)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2618*], [#delta(-2)],
      [68], [#name("LAM Siu Hang")], [#age(21)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2618*], [#delta(6)],
      [69], [#name("NG Pak Nam")], [#age(19)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2617*], [#delta(102)],
      [70], [#name("帕特里克 弗朗西斯卡")], [#age(25)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2617*], [#delta(29)],
      [71], [#name("大岛祐哉")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2616*], [#delta(-21)],
      [72], [#name("TAKAKIWA Taku")], [#age(29)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2615*], [#delta(-5)],
      [73], [#name("MACHI Asuka")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2615*], [#delta(-27)],
      [74], [#name("斯特凡 菲格尔")], [#age(29)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2614*], [#delta(46)],
      [75], [#name("廖振珽")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2613*], [#delta(-7)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("奥维迪乌 伊奥内斯库")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2612*], [#delta(-39)],
      [77], [#name("DRINKHALL Paul")], [#age(27)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2611*], [#delta(-8)],
      [78], [#name("KIM Donghyun")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2611*], [#delta(-8)],
      [79], [#name("ROBINOT Quentin")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2610*], [#delta(44)],
      [80], [#name("贝内迪克特 杜达")], [#age(23)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2610*], [#delta(21)],
      [81], [#name("阿尔瓦罗 罗布勒斯")], [#age(26)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2609*], [#delta(62)],
      [82], [#name("WANG Zengyi")], [#age(34)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2608*], [#delta(10)],
      [83], [#name("PERSSON Jon")], [#age(31)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2607*], [#delta(-7)],
      [84], [#name("神巧也")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2603*], [#delta(-9)],
      [85], [#name("CASSIN Alexandre")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2602*], [#delta(130)],
      [86], [#name("HABESOHN Daniel")], [#age(31)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2601*], [#delta(-2)],
      [87], [#name("王臻")], [#age(32)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2601*], [#delta(-9)],
      [88], [#name("罗伯特 加尔多斯")], [#age(38)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2599*], [#delta(18)],
      [89], [#name("汪洋")], [#age(23)], [#assoc("SVK")], [#right], [#shakehand], [#defense], [*2599*], [#delta(55)],
      [90], [#name("AKKUZU Can")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2598*], [#delta(-37)],
      [91], [#name("MATSUYAMA Yuki")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2597*], [#delta(-12)],
      [92], [#name("HO Kwan Kit")], [#age(20)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2589*], [#delta(-49)],
      [93], [#name("高宁")], [#age(35)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2588*], [#delta(-8)],
      [94], [#name("利亚姆 皮切福德")], [#age(24)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2587*], [#delta(-8)],
      [95], [#name("BOBOCICA Mihai")], [#age(31)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2584*], [#delta(13)],
      [96], [#name("ROBINOT Alexandre")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2583*], [#delta(9)],
      [97], [#name("尼马 阿拉米安")], [#age(25)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2580*], [#delta(-17)],
      [98], [#name("基里尔 格拉西缅科")], [#age(21)], [#assoc("KAZ")], [#right], [#shakehand], [#attack], [*2578*], [#delta(-35)],
      [99], [#name("RYUZAKI Tonin")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2578*], [#delta(-11)],
      [100], [#name("张禹珍")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2576*], [#delta(-10)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("金珉锡")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2572*], [#delta(-6)],
      [102], [#name("托米斯拉夫 普卡")], [#age(21)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2571*], [#delta(33)],
      [103], [#name("基里尔 斯卡奇科夫")], [#age(30)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2570*], [#delta(21)],
      [104], [#name("塞德里克 纽廷克")], [#age(24)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2567*], [#delta(-11)],
      [105], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(37)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2565*], [#delta(-43)],
      [106], [#name("MATSUDAIRA Kenji")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2563*], [#delta(-25)],
      [107], [#name("KANG Dongsoo")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2559*], [#delta(-3)],
      [108], [#name("LI Ahmet")], [#age(26)], [#assoc("TUR")], [#left], [#shakehand], [#attack], [*2557*], [#delta(104)],
      [109], [#name("雅克布 迪亚斯")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2556*], [#delta(-36)],
      [110], [#name("LAKATOS Tamas")], [#age(22)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2556*], [#delta(4)],
      [111], [#name("SALIFOU Abdel-Kader")], [#age(28)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2554*], [#delta(65)],
      [112], [#name("江天一")], [#age(29)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2543*], [#delta(-40)],
      [113], [#name("SIRUCEK Pavel")], [#age(25)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2538*], [#delta(38)],
      [114], [#name("KANG Wi Hun")], [#age(28)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2538*], [#delta(2)],
      [115], [#name("GNANASEKARAN Sathiyan")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2537*], [#delta(41)],
      [116], [#name("ISMAILOV Sadi")], [#age(21)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2537*], [#delta(-19)],
      [117], [#name("KOZUL Deni")], [#age(20)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2537*], [#delta(58)],
      [118], [#name("HACHARD Antoine")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2536*], [#delta(-16)],
      [119], [#name("PAPAGEORGIOU Konstantinos")], [#age(38)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2533*], [#delta(8)],
      [120], [#name("PRYSHCHEPA Ievgen")], [#age(32)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2533*], [#delta(190)],
      [121], [#name("金光宏畅")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2533*], [#delta(-3)],
      [122], [#name("徐海东")], [#age(17)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2532*], [#delta(-3)],
      [123], [#name("TAKAMI Masaki")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2529*], [#delta(32)],
      [124], [#name("CARVALHO Diogo")], [#age(25)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2528*], [#delta(-3)],
      [125], [#name("ANGLES Enzo")], [#age(22)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2527*], [#delta(-14)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("LIVENTSOV Alexey")], [#age(36)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2526*], [#delta(-4)],
      [127], [#name("ORT Kilian")], [#age(21)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2526*], [#delta(-20)],
      [128], [#name("HIRANO Yuki")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2524*], [#delta(-3)],
      [129], [#name("PARK Jeongwoo")], [#age(20)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2522*], [#delta(-3)],
      [130], [#name("ANTHONY Amalraj")], [#age(31)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2518*], [#delta(-21)],
      [131], [#name("朴康贤")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2517*], [#delta(-1)],
      [132], [#name("SEREDA Peter")], [#age(33)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2517*], [#delta(61)],
      [133], [#name("SALEH Ahmed")], [#age(38)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2516*], [#delta(-2)],
      [134], [#name("宇田幸矢")], [#age(16)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2515*], [#delta(-2)],
      [135], [#name("GERALDO Joao")], [#age(22)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2513*], [#delta(-7)],
      [136], [#name("KONG Lingxuan")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2513*], [#delta(-2)],
      [137], [#name("徐瑛彬")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2511*], [#delta(-8)],
      [138], [#name("TSUBOI Yuma")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2510*], [#delta(-2)],
      [139], [#name("BOULOUSSA Mehdi")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2507*], [#delta(-22)],
      [140], [#name("PLETEA Cristian")], [#age(17)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2504*], [#delta(44)],
      [141], [#name("阿德里安 克里桑")], [#age(37)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2502*], [#delta(-31)],
      [142], [#name("达科 约奇克")], [#age(19)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2501*], [#delta(-46)],
      [143], [#name("木造勇人")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2500*], [#delta(-54)],
      [144], [#name("米凯尔 梅兹")], [#age(36)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2499*], [#delta(-4)],
      [145], [#name("SAKAI Asuka")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2498*], [#delta(-4)],
      [146], [#name("SZUDI Adam")], [#age(21)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2498*], [#delta(77)],
      [147], [#name("帕特里克 鲍姆")], [#age(30)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2497*], [#delta(105)],
      [148], [#name("贝内德克 奥拉")], [#age(26)], [#assoc("FIN")], [#right], [#shakehand], [#attack], [*2496*], [#delta(42)],
      [149], [#name("TSUBOI Gustavo")], [#age(32)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2496*], [#delta(13)],
      [150], [#name("LAKEEV Vasily")], [#age(33)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2495*], [#delta(-5)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("SEO Hyundeok")], [#age(26)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2494*], [#delta(-5)],
      [152], [#name("ANDERSSON Harald")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2493*], [#delta(-4)],
      [153], [#name("BROSSIER Benjamin")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2489*], [#delta(-62)],
      [154], [#name("KIM Minhyeok")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2485*], [#delta(0)],
      [155], [#name("JANCARIK Lubomir")], [#age(30)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2484*], [#delta(19)],
      [156], [#name("CANTERO Jesus")], [#age(35)], [#assoc("ESP")], [#right], [#penhold], [#attack], [*2484*], [#delta(-43)],
      [157], [#name("卡纳克 贾哈")], [#age(17)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2481*], [#delta(10)],
      [158], [#name("STOYANOV Niagol")], [#age(30)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2479*], [#delta(-1)],
      [159], [#name("NORDBERG Hampus")], [#age(30)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2478*], [#delta(0)],
      [160], [#name("詹斯 伦德奎斯特")], [#age(38)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2478*], [#delta(42)],
      [161], [#name("MADRID Marcos")], [#age(31)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2478*], [#delta(35)],
      [162], [#name("PENG Wang-Wei")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2477*], [#delta(-2)],
      [163], [#name("GHOSH Soumyajit")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2476*], [#delta(5)],
      [164], [#name("侯英超")], [#age(37)], [#assoc("CAN")], [#right], [#shakehand], [#defense], [*2476*], [#delta(-1)],
      [165], [#name("FLORAS Robert")], [#age(25)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2476*], [#delta(-23)],
      [166], [#name("BAIBULDIN Andrei")], [#age(31)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2475*], [#delta(-2)],
      [167], [#name("MONTEIRO Thiago")], [#age(36)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2471*], [#delta(15)],
      [168], [#name("CHO Eonrae")], [#age(31)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2471*], [#delta(1)],
      [169], [#name("GUNDUZ Ibrahim")], [#age(20)], [#assoc("TUR")], [#left], [#shakehand], [#attack], [*2470*], [#delta(81)],
      [170], [#name("哈米特 德赛")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2470*], [#delta(-31)],
      [171], [#name("FLORITZ Philipp")], [#age(26)], [#assoc("BUL")], [#right], [#shakehand], [#attack], [*2470*], [#delta(2)],
      [172], [#name("SEYFRIED Joe")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2470*], [#delta(-14)],
      [173], [#name("FERTIKOWSKI Pawel")], [#age(27)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2469*], [#delta(-1)],
      [174], [#name("GAVLAS Antonin")], [#age(32)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2469*], [#delta(-37)],
      [175], [#name("GORAK Daniel")], [#age(34)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2465*], [#delta(-9)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("CHEN Diogo")], [#age(21)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2464*], [#delta(54)],
      [177], [#name("BAGGALEY Andrew")], [#age(34)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2462*], [#delta(0)],
      [178], [#name("SAMBE Kohei")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2460*], [#delta(2)],
      [179], [#name("JOUTI Eric")], [#age(23)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2459*], [#delta(10)],
      [180], [#name("POLANSKY Tomas")], [#age(19)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2459*], [#delta(-86)],
      [181], [#name("LANDRIEU Andrea")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2457*], [#delta(-28)],
      [182], [#name("TORIOLA Segun")], [#age(43)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2456*], [#delta(-1)],
      [183], [#name("YANG Heng-Wei")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2456*], [#delta(11)],
      [184], [#name("OBESLO Michal")], [#age(28)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2456*], [#delta(-46)],
      [185], [#name("BRODD Viktor")], [#age(27)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2454*], [#delta(-2)],
      [186], [#name("ARVIDSSON Simon")], [#age(27)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2451*], [#delta(-37)],
      [187], [#name("安宰贤")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2451*], [#delta(-1)],
      [188], [#name("YU Heyi")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2450*], [#delta(-1)],
      [189], [#name("ZHAI Yujia")], [#age(22)], [#assoc("DEN")], [#right], [#shakehand], [#attack], [*2448*], [#delta(-1)],
      [190], [#name("LAMBIET Florent")], [#age(22)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2448*], [#delta(86)],
      [191], [#name("SGOUROPOULOS Ioannis")], [#age(17)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2443*], [#delta(-39)],
      [192], [#name("AFANADOR Brian")], [#age(20)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2442*], [#delta(-1)],
      [193], [#name("ABIODUN Bode")], [#age(37)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2442*], [#delta(-1)],
      [194], [#name("SZOCS Hunor")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2441*], [#delta(-94)],
      [195], [#name("牛冠凯")], [#age(15)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2439*], [#delta(126)],
      [196], [#name("YANG Xinyu")], [#age(16)], [#assoc("AZE")], [#right], [#shakehand], [#attack], [*2438*], [#delta(64)],
      [197], [#name("CHOE Il")], [#age(24)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-2)],
      [198], [#name("斯蒂芬 门格尔")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2435*], [#delta(-65)],
      [199], [#name("邱党")], [#age(21)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2434*], [#delta(6)],
      [200], [#name("MAJOROS Bence")], [#age(20)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2434*], [#delta(1)],
    )
  )
