#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("丁宁")], [#age(27)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*3017*], [#delta(0)],
      [2], [#name("刘诗雯")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2997*], [#delta(0)],
      [3], [#name("陈梦")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2974*], [#delta(0)],
      [4], [#name("木子")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2947*], [#delta(0)],
      [5], [#name("韩莹")], [#age(34)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2914*], [#delta(0)],
      [6], [#name("朱雨玲")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2911*], [#delta(0)],
      [7], [#name("平野美宇")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2904*], [#delta(0)],
      [8], [#name("冯天薇")], [#age(31)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2864*], [#delta(0)],
      [9], [#name("石川佳纯")], [#age(24)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2862*], [#delta(0)],
      [10], [#name("胡丽梅")], [#age(22)], [#assoc("CHN")], [#right], [#penhold], [#defense], [*2826*], [#delta(0)],
      [11], [#name("王曼昱")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2818*], [#delta(0)],
      [12], [#name("陈幸同")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2808*], [#delta(0)],
      [13], [#name("武杨")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2791*], [#delta(0)],
      [14], [#name("顾玉婷")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2769*], [#delta(0)],
      [15], [#name("郑怡静")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2768*], [#delta(0)],
      [16], [#name("文佳")], [#age(28)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2748*], [#delta(0)],
      [17], [#name("早田希娜")], [#age(17)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2745*], [#delta(0)],
      [18], [#name("车晓曦")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2738*], [#delta(0)],
      [19], [#name("金宋依")], [#age(23)], [#assoc("COR")], [#right], [#shakehand], [#defense], [*2738*], [#delta(0)],
      [20], [#name("安藤南")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2725*], [#delta(0)],
      [21], [#name("刘高阳")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2711*], [#delta(1)],
      [22], [#name("桥本帆乃香")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2707*], [#delta(23)],
      [23], [#name("伊藤美诚")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2707*], [#delta(0)],
      [24], [#name("曾尖")], [#age(21)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2695*], [#delta(0)],
      [25], [#name("田志希")], [#age(25)], [#assoc("COR")], [#left], [#shakehand], [#attack], [*2689*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("单晓娜")], [#age(34)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2687*], [#delta(0)],
      [27], [#name("于梦雨")], [#age(28)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2683*], [#delta(0)],
      [28], [#name("石洵瑶")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2683*], [#delta(0)],
      [29], [#name("森樱")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2677*], [#delta(0)],
      [30], [#name("何卓佳")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2676*], [#delta(0)],
      [31], [#name("崔孝珠")], [#age(19)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2672*], [#delta(0)],
      [32], [#name("克里斯汀 朗")], [#age(32)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2668*], [#delta(0)],
      [33], [#name("顾若辰")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2667*], [#delta(0)],
      [34], [#name("乔治娜 波塔")], [#age(32)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2656*], [#delta(0)],
      [35], [#name("李佳燚")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2656*], [#delta(0)],
      [36], [#name("佐藤瞳")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2655*], [#delta(-15)],
      [37], [#name("张蔷")], [#age(23)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2655*], [#delta(-1)],
      [38], [#name("杨晓欣")], [#age(29)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2650*], [#delta(-1)],
      [39], [#name("李洁")], [#age(33)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2647*], [#delta(-1)],
      [40], [#name("萨宾 温特")], [#age(25)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2644*], [#delta(-1)],
      [41], [#name("加藤美优")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2643*], [#delta(-1)],
      [42], [#name("陈思羽")], [#age(24)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2642*], [#delta(-1)],
      [43], [#name("倪夏莲")], [#age(54)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2639*], [#delta(-1)],
      [44], [#name("索菲亚 波尔卡诺娃")], [#age(23)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2639*], [#delta(22)],
      [45], [#name("佩特丽莎 索尔佳")], [#age(23)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2639*], [#delta(-2)],
      [46], [#name("金景娥")], [#age(40)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2638*], [#delta(-2)],
      [47], [#name("梁夏银")], [#age(23)], [#assoc("COR")], [#right], [#shakehand], [#attack], [*2632*], [#delta(-1)],
      [48], [#name("布里特 伊尔兰德")], [#age(23)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2628*], [#delta(-1)],
      [49], [#name("侯美玲")], [#age(28)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2628*], [#delta(4)],
      [50], [#name("森园美咲")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2627*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("李芬")], [#age(41)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2624*], [#delta(1)],
      [52], [#name("娜塔莉亚 帕尔蒂卡")], [#age(28)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2622*], [#delta(-3)],
      [53], [#name("刘佳")], [#age(35)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2621*], [#delta(-3)],
      [54], [#name("陈可")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2620*], [#delta(-3)],
      [55], [#name("SHENG Dandan")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2616*], [#delta(-1)],
      [56], [#name("浜本由惟")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2615*], [#delta(-1)],
      [57], [#name("PARK Joohyun")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2615*], [#delta(39)],
      [58], [#name("帖雅娜")], [#age(38)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2613*], [#delta(-2)],
      [59], [#name("傅玉")], [#age(39)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2612*], [#delta(-2)],
      [60], [#name("玛蒂尔达 埃克霍尔姆")], [#age(35)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2609*], [#delta(-1)],
      [61], [#name("李倩")], [#age(31)], [#assoc("POL")], [#right], [#shakehand], [#defense], [*2603*], [#delta(-1)],
      [62], [#name("巴尔博拉 巴拉佐娃")], [#age(25)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2599*], [#delta(-1)],
      [63], [#name("素塔西尼 萨维塔布特")], [#age(23)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2598*], [#delta(6)],
      [64], [#name("芝田沙季")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2594*], [#delta(15)],
      [65], [#name("徐孝元")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2594*], [#delta(-3)],
      [66], [#name("吴颖岚")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2594*], [#delta(-3)],
      [67], [#name("苏慧音")], [#age(19)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2589*], [#delta(-3)],
      [68], [#name("宋马音")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2580*], [#delta(-1)],
      [69], [#name("伊丽莎白 萨马拉")], [#age(28)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2579*], [#delta(-11)],
      [70], [#name("张墨")], [#age(28)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2574*], [#delta(-5)],
      [71], [#name("王艺迪")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2573*], [#delta(-3)],
      [72], [#name("郑先知")], [#age(24)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2570*], [#delta(-2)],
      [73], [#name("姜华珺")], [#age(33)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2570*], [#delta(-2)],
      [74], [#name("前田美优")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2566*], [#delta(-2)],
      [75], [#name("KATO Kyoka")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2566*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("周一涵")], [#age(23)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2564*], [#delta(-1)],
      [77], [#name("李佼")], [#age(44)], [#assoc("NED")], [#left], [#penhold], [#attack], [*2561*], [#delta(-1)],
      [78], [#name("李皓晴")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2560*], [#delta(-1)],
      [79], [#name("伯纳黛特 斯佐科斯")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2560*], [#delta(4)],
      [80], [#name("维多利亚 帕夫洛维奇")], [#age(39)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2558*], [#delta(-2)],
      [81], [#name("李时温")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2555*], [#delta(-1)],
      [82], [#name("杜凯琹")], [#age(21)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2554*], [#delta(-1)],
      [83], [#name("李恩惠")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2543*], [#delta(-9)],
      [84], [#name("CHOE Hyon Hwa")], [#age(25)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2536*], [#delta(1)],
      [85], [#name("特蒂亚娜 比连科")], [#age(34)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2534*], [#delta(1)],
      [86], [#name("黄怡桦")], [#age(33)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2530*], [#delta(3)],
      [87], [#name("宋惠佳")], [#age(22)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2529*], [#delta(3)],
      [88], [#name("刘馨尹")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2528*], [#delta(6)],
      [89], [#name("KIM Youjin")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2527*], [#delta(2)],
      [90], [#name("松泽茉里奈")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2524*], [#delta(2)],
      [91], [#name("汉娜 马特洛娃")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2523*], [#delta(-9)],
      [92], [#name("阿迪娜 迪亚科努")], [#age(18)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2517*], [#delta(-4)],
      [93], [#name("达蒙万 克宽")], [#age(20)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2517*], [#delta(56)],
      [94], [#name("SHIOMI Maki")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2516*], [#delta(-1)],
      [95], [#name("阿德里安娜 迪亚兹")], [#age(17)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2515*], [#delta(-11)],
      [96], [#name("桑德拉 佩尔格尔")], [#age(29)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2512*], [#delta(-9)],
      [97], [#name("钱天一")], [#age(17)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2509*], [#delta(-2)],
      [98], [#name("亚娜 诺斯科娃")], [#age(23)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2507*], [#delta(6)],
      [99], [#name("李美京")], [#age(27)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2505*], [#delta(-2)],
      [100], [#name("木原美悠")], [#age(13)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2503*], [#delta(73)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("洪剑芳")], [#age(44)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2502*], [#delta(-2)],
      [102], [#name("伊韦塔 瓦切诺夫斯卡")], [#age(31)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2498*], [#delta(0)],
      [103], [#name("卡塔日娜 格日博夫斯卡-弗朗茨")], [#age(28)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2497*], [#delta(0)],
      [104], [#name("汉娜 哈珀诺娃")], [#age(32)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2496*], [#delta(6)],
      [105], [#name("丹妮拉 多迪安")], [#age(29)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2486*], [#delta(1)],
      [106], [#name("孙颖莎")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2485*], [#delta(1)],
      [107], [#name("尹孝彬")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2485*], [#delta(1)],
      [108], [#name("智恩彩")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2482*], [#delta(51)],
      [109], [#name("玛丽亚 多尔吉赫")], [#age(30)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2482*], [#delta(-11)],
      [110], [#name("安娜 蒂克米罗娃")], [#age(33)], [#assoc("RUS")], [?], [?], [?], [*2481*], [#delta(-1)],
      [111], [#name("尚塔尔 曼茨")], [#age(21)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2476*], [#delta(24)],
      [112], [#name("玛格丽塔 佩索茨卡")], [#age(26)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2476*], [#delta(0)],
      [113], [#name("长崎美柚")], [#age(15)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2476*], [#delta(0)],
      [114], [#name("肖瑶茜")], [#age(23)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2475*], [#delta(0)],
      [115], [#name("KULIKOVA Olga")], [#age(24)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2472*], [#delta(-14)],
      [116], [#name("SABITOVA Valentina")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2471*], [#delta(-16)],
      [117], [#name("伊琳娜 乔巴努")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2471*], [#delta(-2)],
      [118], [#name("马文婷")], [#age(27)], [#assoc("NOR")], [#right], [#shakehand], [#attack], [*2470*], [#delta(28)],
      [119], [#name("MORIZONO Mizuki")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2470*], [#delta(-3)],
      [120], [#name("尤利娅 普罗霍罗娃")], [#age(30)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2469*], [#delta(-3)],
      [121], [#name("郑有美")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2466*], [#delta(-2)],
      [122], [#name("KIM Seoyeon")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2465*], [#delta(-2)],
      [123], [#name("劳拉 加斯尼尔")], [#age(24)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2454*], [#delta(-18)],
      [124], [#name("加利娅 德沃拉克")], [#age(29)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2449*], [#delta(-1)],
      [125], [#name("奥尔加 沃罗贝娃")], [#age(27)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2448*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("吴玥")], [#age(27)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2446*], [#delta(-2)],
      [127], [#name("雷娜塔 斯特尔比科娃")], [#age(38)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2446*], [#delta(-2)],
      [128], [#name("梅塞德丝 纳吉瓦劳迪")], [#age(23)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2444*], [#delta(108)],
      [129], [#name("妮娜 米特兰姆")], [#age(21)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2440*], [#delta(-2)],
      [130], [#name("卢卡 熊原")], [#age(22)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2439*], [#delta(-19)],
      [131], [#name("林叶")], [#age(21)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2439*], [#delta(-3)],
      [132], [#name("范思琦")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2436*], [#delta(-3)],
      [133], [#name("NING Jing")], [#age(17)], [#assoc("AZE")], [?], [?], [?], [*2435*], [#delta(-2)],
      [134], [#name("伊娃 奥多罗娃")], [#age(38)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2435*], [#delta(-4)],
      [135], [#name("高王")], [#age(37)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-17)],
      [136], [#name("CHA Hyo Sim")], [#age(23)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2431*], [#delta(-4)],
      [137], [#name("MAK Tze Wing")], [#age(19)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2430*], [#delta(-4)],
      [138], [#name("田原")], [#age(42)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2428*], [#delta(-2)],
      [139], [#name("林佳慧")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2425*], [#delta(-2)],
      [140], [#name("黄郁雯")], [#age(21)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2424*], [#delta(-2)],
      [141], [#name("玛丽亚 泰拉科娃")], [#age(16)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2423*], [#delta(-2)],
      [142], [#name("NAGAO Takako")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2419*], [#delta(-1)],
      [143], [#name("GALIC Alex")], [#age(23)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2416*], [#delta(-1)],
      [144], [#name("KIM Jiho")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2412*], [#delta(-1)],
      [145], [#name("金加 斯特凡斯卡")], [#age(37)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2411*], [#delta(-1)],
      [146], [#name("张安")], [#age(21)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2410*], [#delta(-1)],
      [147], [#name("李依真")], [#age(30)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2410*], [#delta(23)],
      [148], [#name("ZHENG Shichang")], [#age(25)], [#assoc("CHN")], [?], [?], [?], [*2407*], [#delta(-1)],
      [149], [#name("亚历山德拉 普里瓦洛娃")], [#age(30)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2403*], [#delta(-1)],
      [150], [#name("柳恩钟")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2402*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("AN Yeongeun")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2399*], [#delta(0)],
      [152], [#name("黄禹乔")], [#age(21)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2398*], [#delta(0)],
      [153], [#name("琳达 伯格斯特隆")], [#age(22)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2397*], [#delta(0)],
      [154], [#name("玛妮卡 巴特拉")], [#age(22)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2396*], [#delta(-20)],
      [155], [#name("林依诺")], [#age(21)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2396*], [#delta(-33)],
      [156], [#name("MINAGAWA Yuka")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2395*], [#delta(103)],
      [157], [#name("萨拉 拉米雷斯")], [#age(30)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2395*], [#delta(-3)],
      [158], [#name("史蒂芬妮 洛伊莱")], [#age(25)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2393*], [#delta(46)],
      [159], [#name("艾希卡 穆克吉")], [#age(20)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2389*], [#delta(-3)],
      [160], [#name("王晨")], [#age(43)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2388*], [#delta(-3)],
      [161], [#name("NARUMOTO Ayami")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2387*], [#delta(-1)],
      [162], [#name("SUN Yizhen")], [#age(17)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2384*], [#delta(-1)],
      [163], [#name("波琳娜 米哈伊洛娃")], [#age(31)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2384*], [#delta(-23)],
      [164], [#name("穆玛 达斯")], [#age(33)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2382*], [#delta(-1)],
      [165], [#name("NIWA Misato")], [#age(24)], [#assoc("JPN")], [?], [?], [?], [*2382*], [#delta(-1)],
      [166], [#name("卡罗尔 格伦迪施")], [#age(31)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2381*], [#delta(-1)],
      [167], [#name("铃木李茄")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2380*], [#delta(-1)],
      [168], [#name("奥塞阿娜 古伊斯内尔")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2379*], [#delta(-1)],
      [169], [#name("LEE Yearam")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2376*], [#delta(-1)],
      [170], [#name("PATKAR Madhurika")], [#age(30)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2376*], [#delta(-12)],
      [171], [#name("松平志穗")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2376*], [#delta(-2)],
      [172], [#name("多拉 马达拉斯")], [#age(24)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2373*], [#delta(-17)],
      [173], [#name("申裕斌")], [#age(13)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2370*], [#delta(67)],
      [174], [#name("GUI Lin")], [#age(24)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2367*], [#delta(-12)],
      [175], [#name("LEE Yujin")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2364*], [#delta(-4)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("KUSINSKA Klaudia")], [#age(24)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2363*], [#delta(-55)],
      [177], [#name("何天天")], [#age(19)], [#assoc("GBR")], [#right], [#penhold], [#attack], [*2363*], [#delta(-5)],
      [178], [#name("阿查娜 卡马特")], [#age(17)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2356*], [#delta(-1)],
      [179], [#name("黄歆")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2355*], [#delta(-1)],
      [180], [#name("奥黛丽 扎里夫")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2353*], [#delta(22)],
      [181], [#name("SIKORSKA Magdalena")], [#age(31)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2353*], [#delta(-6)],
      [182], [#name("ARLOUSKAYA Alina")], [#age(22)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2352*], [#delta(-8)],
      [183], [#name("LIU Yu-Hsin")], [#age(24)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2351*], [#delta(-4)],
      [184], [#name("CHIU Ssu-Hua")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#defense], [*2351*], [#delta(-4)],
      [185], [#name("布鲁娜 高桥")], [#age(17)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2351*], [#delta(71)],
      [186], [#name("娜塔莉亚 巴约尔")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2349*], [#delta(6)],
      [187], [#name("莎拉 德努特")], [#age(25)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2349*], [#delta(7)],
      [188], [#name("MOKHNACHEVA Svetlana")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2347*], [#delta(-6)],
      [189], [#name("LIN Po-Hsuan")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2347*], [#delta(-6)],
      [190], [#name("YAMAMOTO Rei")], [#age(22)], [#assoc("JPN")], [?], [?], [?], [*2347*], [#delta(-6)],
      [191], [#name("ODONO Yui")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2347*], [#delta(-5)],
      [192], [#name("安德烈娅 德拉戈曼")], [#age(17)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2344*], [#delta(13)],
      [193], [#name("LIN Chia-Chih")], [#age(26)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2344*], [#delta(-5)],
      [194], [#name("BIKBAEVA Anna")], [#age(23)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2343*], [#delta(26)],
      [195], [#name("亚迪拉 席尔瓦")], [#age(32)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2342*], [#delta(-2)],
      [196], [#name("邵杰妮")], [#age(23)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2340*], [#delta(-1)],
      [197], [#name("AMBRUS Krisztina")], [#age(25)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2339*], [#delta(21)],
      [198], [#name("达娜 切霍娃")], [#age(34)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2339*], [#delta(-2)],
      [199], [#name("VIGNJEVIC Dragana")], [#age(18)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2339*], [#delta(-2)],
      [200], [#name("刘炜珊")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2338*], [#delta(-2)],
    )
  )
