#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("王励勤")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3100*], [#delta(0)],
      [2], [#name("马琳")], [#age(25)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2924*], [#delta(0)],
      [3], [#name("吴尚垠")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2877*], [#delta(0)],
      [4], [#name("米凯尔 梅兹")], [#age(24)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2865*], [#delta(0)],
      [5], [#name("陈玘")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2844*], [#delta(0)],
      [6], [#name("刘国正")], [#age(25)], [#assoc("CHN")], [?], [?], [?], [*2750*], [#delta(0)],
      [7], [#name("弗拉基米尔 萨姆索诺夫")], [#age(29)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2727*], [#delta(0)],
      [8], [#name("孔令辉")], [#age(30)], [#assoc("CHN")], [?], [?], [?], [*2725*], [#delta(0)],
      [9], [#name("郝帅")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2694*], [#delta(0)],
      [10], [#name("阿德里安 克里桑")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2692*], [#delta(0)],
      [11], [#name("蒂姆 波尔")], [#age(24)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2685*], [#delta(0)],
      [12], [#name("FENG Zhe")], [#age(30)], [#assoc("BUL")], [?], [?], [?], [*2649*], [#delta(0)],
      [13], [#name("卡林尼科斯 格林卡")], [#age(33)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2639*], [#delta(0)],
      [14], [#name("彼得 科贝尔")], [#age(34)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2631*], [#delta(0)],
      [15], [#name("柳承敏")], [#age(23)], [#assoc("KOR")], [#right], [#penhold], [#attack], [*2627*], [#delta(0)],
      [16], [#name("王皓")], [#age(22)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2624*], [#delta(0)],
      [17], [#name("陈卫星")], [#age(33)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2618*], [#delta(0)],
      [18], [#name("卢兹扬 布拉斯奇克")], [#age(31)], [#assoc("POL")], [?], [?], [?], [*2610*], [#delta(0)],
      [19], [#name("唐鹏")], [#age(24)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2598*], [#delta(0)],
      [20], [#name("FRANZ Peter")], [#age(34)], [#assoc("GER")], [?], [?], [?], [*2597*], [#delta(0)],
      [21], [#name("李廷佑")], [#age(21)], [#assoc("KOR")], [#left], [#penhold], [#attack], [*2593*], [#delta(0)],
      [22], [#name("朱世赫")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2590*], [#delta(0)],
      [23], [#name("彼得 卡尔松")], [#age(36)], [#assoc("SWE")], [?], [?], [?], [*2585*], [#delta(0)],
      [24], [#name("HEISTER Danny")], [#age(34)], [#assoc("NED")], [#left], [#shakehand], [#attack], [*2576*], [#delta(0)],
      [25], [#name("MONRAD Martin")], [#age(28)], [#assoc("DEN")], [?], [?], [?], [*2572*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("SUCH Bartosz")], [#age(22)], [#assoc("POL")], [?], [?], [?], [*2562*], [#delta(0)],
      [27], [#name("CHO Eonrae")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2542*], [#delta(0)],
      [28], [#name("吉田海伟")], [#age(24)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2537*], [#delta(0)],
      [29], [#name("李静")], [#age(30)], [#assoc("HKG")], [?], [?], [?], [*2530*], [#delta(0)],
      [30], [#name("维尔纳 施拉格")], [#age(33)], [#assoc("AUT")], [?], [?], [?], [*2526*], [#delta(0)],
      [31], [#name("巴斯蒂安 斯蒂格")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2523*], [#delta(0)],
      [32], [#name("何志文")], [#age(43)], [#assoc("ESP")], [#left], [#penhold], [#attack], [*2519*], [#delta(0)],
      [33], [#name("LEGOUT Christophe")], [#age(32)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2515*], [#delta(0)],
      [34], [#name("庄智渊")], [#age(24)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2514*], [#delta(0)],
      [35], [#name("詹斯 伦德奎斯特")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2506*], [#delta(0)],
      [36], [#name("BENTSEN Allan")], [#age(37)], [#assoc("DEN")], [?], [?], [?], [*2498*], [#delta(0)],
      [37], [#name("马文革")], [#age(37)], [#assoc("CHN")], [?], [?], [?], [*2496*], [#delta(0)],
      [38], [#name("PAVELKA Tomas")], [#age(25)], [#assoc("CZE")], [?], [?], [?], [*2488*], [#delta(0)],
      [39], [#name("ROSSKOPF Jorg")], [#age(36)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2485*], [#delta(0)],
      [40], [#name("MAZUNOV Dmitry")], [#age(34)], [#assoc("RUS")], [?], [?], [?], [*2479*], [#delta(0)],
      [41], [#name("GRUJIC Slobodan")], [#age(32)], [#assoc("SRB")], [?], [?], [?], [*2475*], [#delta(0)],
      [42], [#name("克里斯蒂安 苏斯")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2473*], [#delta(0)],
      [43], [#name("特林科 基恩")], [#age(34)], [#assoc("NED")], [#left], [#shakehand], [#attack], [*2473*], [#delta(0)],
      [44], [#name("张钰")], [#age(24)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2467*], [#delta(0)],
      [45], [#name("简 诺瓦 瓦尔德内尔")], [#age(40)], [#assoc("SWE")], [?], [?], [?], [*2463*], [#delta(0)],
      [46], [#name("让 米歇尔 赛弗")], [#age(36)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2457*], [#delta(0)],
      [47], [#name("LIN Ju")], [#age(26)], [#assoc("DOM")], [?], [?], [?], [*2457*], [#delta(0)],
      [48], [#name("马龙")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2445*], [#delta(0)],
      [49], [#name("松下浩二")], [#age(38)], [#assoc("JPN")], [#right], [?], [#defense], [*2440*], [#delta(0)],
      [50], [#name("达米安 艾洛伊")], [#age(36)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2439*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("高宁")], [#age(23)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2439*], [#delta(0)],
      [52], [#name("YANG Min")], [#age(42)], [#assoc("ITA")], [?], [?], [?], [*2424*], [#delta(0)],
      [53], [#name("OLEJNIK Martin")], [#age(33)], [#assoc("CZE")], [?], [?], [?], [*2422*], [#delta(0)],
      [54], [#name("LIM Jaehyun")], [#age(20)], [#assoc("KOR")], [?], [?], [?], [*2420*], [#delta(0)],
      [55], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(25)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2418*], [#delta(0)],
      [56], [#name("高礼泽")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2417*], [#delta(0)],
      [57], [#name("梁柱恩")], [#age(26)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2409*], [#delta(0)],
      [58], [#name("约尔根 佩尔森")], [#age(39)], [#assoc("SWE")], [?], [?], [?], [*2405*], [#delta(0)],
      [59], [#name("水谷隼")], [#age(16)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2404*], [#delta(0)],
      [60], [#name("YANG Zi")], [#age(21)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2403*], [#delta(0)],
      [61], [#name("FEJER-KONNERTH Zoltan")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2396*], [#delta(0)],
      [62], [#name("LIU Song")], [#age(33)], [#assoc("ARG")], [?], [?], [?], [*2395*], [#delta(0)],
      [63], [#name("SCHLICHTER Jorg")], [#age(22)], [#assoc("GER")], [?], [?], [?], [*2392*], [#delta(0)],
      [64], [#name("PLACHY Josef")], [#age(34)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2370*], [#delta(0)],
      [65], [#name("TOSIC Roko")], [#age(26)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2362*], [#delta(0)],
      [66], [#name("WOSIK Torben")], [#age(32)], [#assoc("GER")], [?], [?], [?], [*2359*], [#delta(0)],
      [67], [#name("阿列克谢 斯米尔诺夫")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2356*], [#delta(0)],
      [68], [#name("蒋澎龙")], [#age(29)], [#assoc("TPE")], [?], [?], [?], [*2352*], [#delta(0)],
      [69], [#name("TUGWELL Finn")], [#age(29)], [#assoc("DEN")], [?], [?], [?], [*2349*], [#delta(0)],
      [70], [#name("KEINATH Thomas")], [#age(28)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2337*], [#delta(0)],
      [71], [#name("亚历山大 卡拉卡谢维奇")], [#age(30)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2335*], [#delta(0)],
      [72], [#name("KUZMIN Fedor")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2328*], [#delta(0)],
      [73], [#name("VYBORNY Richard")], [#age(34)], [#assoc("CZE")], [?], [?], [?], [*2324*], [#delta(0)],
      [74], [#name("TORIOLA Segun")], [#age(31)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2324*], [#delta(0)],
      [75], [#name("佐兰 普里莫拉克")], [#age(36)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2320*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("张超")], [#age(20)], [#assoc("CHN")], [?], [?], [?], [*2318*], [#delta(0)],
      [77], [#name("帕特里克 奇拉")], [#age(36)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2317*], [#delta(0)],
      [78], [#name("GERELL Par")], [#age(23)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2302*], [#delta(0)],
      [79], [#name("CHO Jihoon")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2301*], [#delta(0)],
      [80], [#name("岸川圣也")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2301*], [#delta(0)],
      [81], [#name("KIM Song Chol")], [#age(22)], [#assoc("PRK")], [?], [?], [?], [*2299*], [#delta(0)],
      [82], [#name("PHUNG Armand")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2297*], [#delta(0)],
      [83], [#name("AXELQVIST Johan")], [#age(20)], [#assoc("SWE")], [?], [?], [?], [*2293*], [#delta(0)],
      [84], [#name("尹在荣")], [#age(22)], [#assoc("KOR")], [?], [?], [?], [*2293*], [#delta(0)],
      [85], [#name("FAZEKAS Peter")], [#age(24)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2287*], [#delta(0)],
      [86], [#name("NASIRU Kazeem")], [#age(31)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2283*], [#delta(0)],
      [87], [#name("KUSINSKI Marcin")], [#age(34)], [#assoc("POL")], [?], [?], [?], [*2282*], [#delta(0)],
      [88], [#name("SEREDA Peter")], [#age(21)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2279*], [#delta(0)],
      [89], [#name("HIELSCHER Lars")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2269*], [#delta(0)],
      [90], [#name("DIDUKH Oleksandr")], [#age(23)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2269*], [#delta(0)],
      [91], [#name("SAIVE Philippe")], [#age(34)], [#assoc("BEL")], [?], [?], [?], [*2267*], [#delta(0)],
      [92], [#name("MONTEIRO Joao")], [#age(22)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2266*], [#delta(0)],
      [93], [#name("MONTEIRO Thiago")], [#age(24)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2265*], [#delta(0)],
      [94], [#name("ERLANDSEN Geir")], [#age(29)], [#assoc("NOR")], [?], [?], [?], [*2262*], [#delta(0)],
      [95], [#name("ZOOGLING Mikael")], [#age(30)], [#assoc("SWE")], [?], [?], [?], [*2254*], [#delta(0)],
      [96], [#name("ABRAMOV Isaak")], [#age(34)], [#assoc("ISR")], [#right], [#shakehand], [#attack], [*2249*], [#delta(0)],
      [97], [#name("HOYAMA Hugo")], [#age(36)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2245*], [#delta(0)],
      [98], [#name("WU Chih-Chi")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2244*], [#delta(0)],
      [99], [#name("WANG Zengyi")], [#age(22)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2241*], [#delta(0)],
      [100], [#name("PISTEJ Lubomir")], [#age(21)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2241*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("KIM Taehoon")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2237*], [#delta(0)],
      [102], [#name("雅罗斯列夫 扎姆登科")], [#age(17)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2237*], [#delta(0)],
      [103], [#name("SALEH Ahmed")], [#age(26)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2236*], [#delta(0)],
      [104], [#name("KIM Junghoon")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2233*], [#delta(0)],
      [105], [#name("SHMYREV Maxim")], [#age(34)], [#assoc("RUS")], [?], [?], [?], [*2228*], [#delta(0)],
      [106], [#name("KITO Akira")], [#age(31)], [#assoc("JPN")], [?], [?], [?], [*2226*], [#delta(0)],
      [107], [#name("CIHAK Marek")], [#age(31)], [#assoc("CZE")], [?], [?], [?], [*2226*], [#delta(0)],
      [108], [#name("罗伯特 加尔多斯")], [#age(26)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2226*], [#delta(0)],
      [109], [#name("CHTCHETININE Evgueni")], [#age(35)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2223*], [#delta(0)],
      [110], [#name("ZWICKL Daniel")], [#age(21)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2220*], [#delta(0)],
      [111], [#name("谭瑞午")], [#age(22)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2219*], [#delta(0)],
      [112], [#name("WANG Jianfeng")], [#age(39)], [#assoc("NOR")], [#right], [#penhold], [#attack], [*2214*], [#delta(0)],
      [113], [#name("HUANG Johnny")], [#age(43)], [#assoc("CAN")], [?], [?], [?], [*2208*], [#delta(0)],
      [114], [#name("SVENSSON Robert")], [#age(22)], [#assoc("SWE")], [?], [?], [?], [*2206*], [#delta(0)],
      [115], [#name("基里尔 斯卡奇科夫")], [#age(18)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2206*], [#delta(0)],
      [116], [#name("DEMETER Lehel")], [#age(27)], [#assoc("HUN")], [?], [?], [?], [*2197*], [#delta(0)],
      [117], [#name("MITAMURA Muneaki")], [#age(24)], [#assoc("JPN")], [?], [?], [?], [*2192*], [#delta(0)],
      [118], [#name("MOLDOVAN Istvan")], [#age(32)], [#assoc("NOR")], [?], [?], [?], [*2190*], [#delta(0)],
      [119], [#name("CABESTANY Cedrik")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2186*], [#delta(0)],
      [120], [#name("FILIMON Andrei")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2185*], [#delta(0)],
      [121], [#name("ILLAS Erik")], [#age(25)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2180*], [#delta(0)],
      [122], [#name("LUPULESKU Ilija")], [#age(38)], [#assoc("USA")], [?], [?], [?], [*2179*], [#delta(0)],
      [123], [#name("迪米特里 奥恰洛夫")], [#age(17)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2178*], [#delta(0)],
      [124], [#name("ACHANTA Sharath")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2175*], [#delta(0)],
      [125], [#name("HAKANSSON Fredrik")], [#age(30)], [#assoc("SWE")], [?], [?], [?], [*2174*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("MATSUMOTO Cazuo")], [#age(20)], [#assoc("BRA")], [#left], [#penhold], [#attack], [*2172*], [#delta(0)],
      [127], [#name("GORAK Daniel")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2171*], [#delta(0)],
      [128], [#name("KOSTAL Radek")], [#age(31)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2167*], [#delta(0)],
      [129], [#name("AVCI Safa")], [#age(18)], [#assoc("TUR")], [?], [?], [?], [*2165*], [#delta(0)],
      [130], [#name("RI Chol Guk")], [#age(20)], [#assoc("PRK")], [?], [?], [?], [*2164*], [#delta(0)],
      [131], [#name("ZHOU Bin")], [#age(17)], [#assoc("CHN")], [?], [?], [?], [*2163*], [#delta(0)],
      [132], [#name("LIVENTSOV Alexey")], [#age(24)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2163*], [#delta(0)],
      [133], [#name("SIMONER Christoph")], [#age(22)], [#assoc("AUT")], [?], [?], [?], [*2161*], [#delta(0)],
      [134], [#name("MOLIN Magnus")], [#age(26)], [#assoc("SWE")], [?], [?], [?], [*2158*], [#delta(0)],
      [135], [#name("蒂亚戈 阿波罗尼亚")], [#age(19)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2154*], [#delta(0)],
      [136], [#name("CIOTI Constantin")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2152*], [#delta(0)],
      [137], [#name("MILICEVIC Srdan")], [#age(29)], [#assoc("BIH")], [?], [?], [?], [*2150*], [#delta(0)],
      [138], [#name("SANGUANSIN Phakpoom")], [#age(22)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2144*], [#delta(0)],
      [139], [#name("HU Jiashun")], [#age(22)], [#assoc("SUI")], [?], [?], [?], [*2143*], [#delta(0)],
      [140], [#name("CHOI Hyunjin")], [#age(26)], [#assoc("KOR")], [?], [?], [?], [*2139*], [#delta(0)],
      [141], [#name("LEE Jinkwon")], [#age(18)], [#assoc("KOR")], [?], [?], [?], [*2136*], [#delta(0)],
      [142], [#name("ELENSKY Gregory")], [#age(21)], [#assoc("ISR")], [?], [?], [?], [*2131*], [#delta(0)],
      [143], [#name("CHOU Tung-Yu")], [#age(18)], [#assoc("TPE")], [?], [?], [?], [*2130*], [#delta(0)],
      [144], [#name("安德烈 加奇尼")], [#age(19)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2126*], [#delta(0)],
      [145], [#name("JAKAB Janos")], [#age(19)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2121*], [#delta(0)],
      [146], [#name("LINDNER Adam")], [#age(30)], [#assoc("HUN")], [#right], [#penhold], [#attack], [*2120*], [#delta(0)],
      [147], [#name("TRUKSA Jaromir")], [#age(34)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2119*], [#delta(0)],
      [148], [#name("TASEI Kunihito")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2112*], [#delta(0)],
      [149], [#name("REDJEP Ronald")], [#age(32)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2111*], [#delta(0)],
      [150], [#name("GERADA Simon")], [#age(24)], [#assoc("AUS")], [?], [?], [?], [*2103*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("SAHA Subhajit")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2101*], [#delta(0)],
      [152], [#name("MANSSON Magnus")], [#age(29)], [#assoc("SWE")], [?], [?], [?], [*2101*], [#delta(0)],
      [153], [#name("CAI Xiaoli")], [#age(26)], [#assoc("SGP")], [?], [?], [?], [*2098*], [#delta(0)],
      [154], [#name("LENGEROV Kostadin")], [#age(29)], [#assoc("AUT")], [?], [?], [?], [*2096*], [#delta(0)],
      [155], [#name("PIYADASA Thilina L")], [#age(26)], [#assoc("SRI")], [?], [?], [?], [*2094*], [#delta(0)],
      [156], [#name("BOBILLIER Loic")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2092*], [#delta(0)],
      [157], [#name("LEE Jungsam")], [#age(21)], [#assoc("KOR")], [?], [?], [?], [*2091*], [#delta(0)],
      [158], [#name("JOVER Sebastien")], [#age(30)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2088*], [#delta(0)],
      [159], [#name("GRIGOREV Artur")], [#age(19)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2084*], [#delta(0)],
      [160], [#name("NAKANO Yusuke")], [#age(21)], [#assoc("JPN")], [?], [?], [?], [*2077*], [#delta(0)],
      [161], [#name("LASHIN Elsayed")], [#age(25)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2072*], [#delta(0)],
      [162], [#name("MACHADO Carlos")], [#age(25)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2069*], [#delta(0)],
      [163], [#name("FETH Stefan")], [#age(25)], [#assoc("GER")], [?], [?], [?], [*2069*], [#delta(0)],
      [164], [#name("博扬 托基奇")], [#age(24)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2069*], [#delta(0)],
      [165], [#name("SAKAMOTO Ryusuke")], [#age(21)], [#assoc("JPN")], [?], [?], [?], [*2068*], [#delta(0)],
      [166], [#name("TAKAKIWA Taku")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2068*], [#delta(0)],
      [167], [#name("PIACENTINI Valentino")], [#age(27)], [#assoc("ITA")], [?], [?], [?], [*2067*], [#delta(0)],
      [168], [#name("STEPHENSEN Gudmundur")], [#age(23)], [#assoc("ISL")], [?], [?], [?], [*2064*], [#delta(0)],
      [169], [#name("FADEEV Evgeny")], [#age(30)], [#assoc("RUS")], [?], [?], [?], [*2063*], [#delta(0)],
      [170], [#name("马克斯 弗雷塔斯")], [#age(17)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2051*], [#delta(10)],
      [171], [#name("VITSEK Ivan")], [#age(36)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2049*], [#delta(-1)],
      [172], [#name("VAINULA Vallot")], [#age(27)], [#assoc("EST")], [#right], [#shakehand], [#attack], [*2048*], [#delta(-1)],
      [173], [#name("帕特里克 鲍姆")], [#age(18)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2048*], [#delta(-1)],
      [174], [#name("KIHO Shinnosuke")], [#age(27)], [#assoc("JPN")], [?], [?], [?], [*2048*], [#delta(-1)],
      [175], [#name("STENBERG Mattias")], [#age(29)], [#assoc("SWE")], [?], [?], [?], [*2048*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("OLLIVIER Brice")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2046*], [#delta(-1)],
      [177], [#name("VOSTES Yannick")], [#age(20)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2046*], [#delta(-1)],
      [178], [#name("TABACHNIK Pablo")], [#age(28)], [#assoc("ARG")], [#left], [#shakehand], [#attack], [*2045*], [#delta(-1)],
      [179], [#name("ZHUANG David")], [#age(42)], [#assoc("USA")], [?], [?], [?], [*2045*], [#delta(-1)],
      [180], [#name("PAZSY Ferenc")], [#age(31)], [#assoc("HUN")], [?], [?], [?], [*2043*], [#delta(-1)],
      [181], [#name("MIZUNO Yuya")], [#age(18)], [#assoc("JPN")], [?], [?], [?], [*2043*], [#delta(0)],
      [182], [#name("FAN Guoliang")], [#age(27)], [#assoc("ESP")], [?], [?], [?], [*2040*], [#delta(0)],
      [183], [#name("KONECNY Tomas")], [#age(20)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2038*], [#delta(0)],
      [184], [#name("PETO Zsolt")], [#age(18)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2034*], [#delta(0)],
      [185], [#name("PETROV Sergei")], [#age(35)], [#assoc("EST")], [?], [?], [?], [*2032*], [#delta(0)],
      [186], [#name("QUENTEL Dorian")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2030*], [#delta(0)],
      [187], [#name("ZUBCIC Tomislav")], [#age(19)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2027*], [#delta(0)],
      [188], [#name("KRIEGER Alexander")], [#age(18)], [#assoc("GER")], [?], [?], [?], [*2025*], [#delta(0)],
      [189], [#name("CHANG Yen-Shu")], [#age(26)], [#assoc("TPE")], [?], [?], [?], [*2024*], [#delta(0)],
      [190], [#name("KONGSGAARD Christian")], [#age(22)], [#assoc("DEN")], [?], [?], [?], [*2023*], [#delta(0)],
      [191], [#name("ROBERTSON Adam")], [#age(21)], [#assoc("WAL")], [?], [?], [?], [*2020*], [#delta(0)],
      [192], [#name("KLASEK Marek")], [#age(30)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2018*], [#delta(0)],
      [193], [#name("DESPRES Rodolphe")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2016*], [#delta(0)],
      [194], [#name("LAKEEV Vasily")], [#age(21)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2016*], [#delta(0)],
      [195], [#name("MONDELLO Massimiliano")], [#age(30)], [#assoc("ITA")], [?], [?], [?], [*2012*], [#delta(0)],
      [196], [#name("SANGUANSIN Phuchong")], [#age(25)], [#assoc("THA")], [?], [?], [?], [*2010*], [#delta(0)],
      [197], [#name("SANCHEZ Victor")], [#age(28)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2010*], [#delta(0)],
      [198], [#name("SIMONCIK Josef")], [#age(25)], [#assoc("CZE")], [?], [?], [?], [*2007*], [#delta(0)],
      [199], [#name("AN Chol Yong")], [#age(20)], [#assoc("PRK")], [?], [?], [?], [*2006*], [#delta(1)],
      [200], [#name("MORALES Augusto")], [#age(38)], [#assoc("CHI")], [?], [?], [?], [*2005*], [#delta(1)],
    )
  )
