#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("王励勤")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3100*], [#delta(0)],
      [2], [#name("马琳")], [#age(25)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2924*], [#delta(0)],
      [3], [#name("吴尚垠")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2877*], [#delta(2)],
      [4], [#name("米凯尔 梅兹")], [#age(24)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2865*], [#delta(-1)],
      [5], [#name("陈玘")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2844*], [#delta(-1)],
      [6], [#name("刘国正")], [#age(25)], [#assoc("CHN")], [?], [?], [?], [*2750*], [#delta(1)],
      [7], [#name("弗拉基米尔 萨姆索诺夫")], [#age(29)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2727*], [#delta(-1)],
      [8], [#name("孔令辉")], [#age(30)], [#assoc("CHN")], [?], [?], [?], [*2725*], [#delta(1)],
      [9], [#name("郝帅")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2694*], [#delta(-1)],
      [10], [#name("阿德里安 克里桑")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2692*], [#delta(0)],
      [11], [#name("蒂姆 波尔")], [#age(24)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2685*], [#delta(0)],
      [12], [#name("FENG Zhe")], [#age(30)], [#assoc("BUL")], [?], [?], [?], [*2649*], [#delta(1)],
      [13], [#name("卡林尼科斯 格林卡")], [#age(33)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2639*], [#delta(1)],
      [14], [#name("彼得 科贝尔")], [#age(34)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2631*], [#delta(1)],
      [15], [#name("柳承敏")], [#age(23)], [#assoc("KOR")], [#right], [#penhold], [#attack], [*2627*], [#delta(1)],
      [16], [#name("王皓")], [#age(22)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2624*], [#delta(1)],
      [17], [#name("陈卫星")], [#age(33)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2618*], [#delta(7)],
      [18], [#name("卢兹扬 布拉斯奇克")], [#age(31)], [#assoc("POL")], [?], [?], [?], [*2610*], [#delta(0)],
      [19], [#name("唐鹏")], [#age(24)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2598*], [#delta(0)],
      [20], [#name("FRANZ Peter")], [#age(34)], [#assoc("GER")], [?], [?], [?], [*2597*], [#delta(2)],
      [21], [#name("李廷佑")], [#age(21)], [#assoc("KOR")], [#left], [#penhold], [#attack], [*2593*], [#delta(-9)],
      [22], [#name("朱世赫")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2590*], [#delta(-2)],
      [23], [#name("彼得 卡尔松")], [#age(36)], [#assoc("SWE")], [?], [?], [?], [*2585*], [#delta(-2)],
      [24], [#name("HEISTER Danny")], [#age(34)], [#assoc("NED")], [#left], [#shakehand], [#attack], [*2576*], [#delta(-1)],
      [25], [#name("马丁 蒙拉德")], [#age(28)], [#assoc("DEN")], [?], [?], [?], [*2572*], [#delta(35)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("巴托什 苏赫")], [#age(22)], [#assoc("POL")], [?], [?], [?], [*2562*], [#delta(-1)],
      [27], [#name("赵彦来")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2542*], [#delta(70)],
      [28], [#name("吉田海伟")], [#age(24)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2537*], [#delta(-1)],
      [29], [#name("李静")], [#age(30)], [#assoc("HKG")], [?], [?], [?], [*2530*], [#delta(-1)],
      [30], [#name("维尔纳 施拉格")], [#age(33)], [#assoc("AUT")], [?], [?], [?], [*2526*], [#delta(-1)],
      [31], [#name("巴斯蒂安 斯特格")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2523*], [#delta(-1)],
      [32], [#name("何志文")], [#age(43)], [#assoc("ESP")], [#left], [#penhold], [#attack], [*2519*], [#delta(0)],
      [33], [#name("克里斯托夫 勒古")], [#age(32)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2515*], [#delta(10)],
      [34], [#name("庄智渊")], [#age(24)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2514*], [#delta(-8)],
      [35], [#name("詹斯 伦德奎斯特")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2506*], [#delta(-4)],
      [36], [#name("阿兰 本特森")], [#age(37)], [#assoc("DEN")], [?], [?], [?], [*2498*], [#delta(-2)],
      [37], [#name("马文革")], [#age(37)], [#assoc("CHN")], [?], [?], [?], [*2496*], [#delta(-2)],
      [38], [#name("托马什 帕维尔卡")], [#age(25)], [#assoc("CZE")], [?], [?], [?], [*2488*], [#delta(-2)],
      [39], [#name("ROSSKOPF Jorg")], [#age(36)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2485*], [#delta(-2)],
      [40], [#name("MAZUNOV Dmitry")], [#age(34)], [#assoc("RUS")], [?], [?], [?], [*2479*], [#delta(-2)],
      [41], [#name("斯洛博丹 格鲁伊奇")], [#age(32)], [#assoc("SRB")], [?], [?], [?], [*2475*], [#delta(-2)],
      [42], [#name("克里斯蒂安 苏斯")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2473*], [#delta(-2)],
      [43], [#name("特林科 基恩")], [#age(34)], [#assoc("NED")], [#left], [#shakehand], [#attack], [*2473*], [#delta(-2)],
      [44], [#name("张钰")], [#age(24)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2466*], [#delta(-2)],
      [45], [#name("简 诺瓦 瓦尔德内尔")], [#age(40)], [#assoc("SWE")], [?], [?], [?], [*2463*], [#delta(-1)],
      [46], [#name("让 米歇尔 塞弗")], [#age(36)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2457*], [#delta(19)],
      [47], [#name("林聚")], [#age(26)], [#assoc("DOM")], [?], [?], [?], [*2457*], [#delta(-2)],
      [48], [#name("马龙")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2445*], [#delta(0)],
      [49], [#name("松下浩二")], [#age(38)], [#assoc("JPN")], [#right], [?], [#defense], [*2440*], [#delta(1)],
      [50], [#name("达米安 埃洛伊")], [#age(36)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2439*], [#delta(19)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("高宁")], [#age(23)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2439*], [#delta(-18)],
      [52], [#name("杨敏")], [#age(42)], [#assoc("ITA")], [?], [?], [?], [*2424*], [#delta(-1)],
      [53], [#name("马丁 奥列尼克")], [#age(33)], [#assoc("CZE")], [?], [?], [?], [*2422*], [#delta(-1)],
      [54], [#name("林载贤")], [#age(20)], [#assoc("KOR")], [?], [?], [?], [*2420*], [#delta(-1)],
      [55], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(25)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2418*], [#delta(-9)],
      [56], [#name("高礼泽")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2417*], [#delta(-2)],
      [57], [#name("梁柱恩")], [#age(26)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2409*], [#delta(-2)],
      [58], [#name("约尔根 佩尔森")], [#age(39)], [#assoc("SWE")], [?], [?], [?], [*2405*], [#delta(-2)],
      [59], [#name("水谷隼")], [#age(16)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2404*], [#delta(-2)],
      [60], [#name("杨子")], [#age(21)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2403*], [#delta(-2)],
      [61], [#name("佐尔坦 费杰科内斯")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2396*], [#delta(-14)],
      [62], [#name("刘松")], [#age(33)], [#assoc("ARG")], [?], [?], [?], [*2395*], [#delta(-1)],
      [63], [#name("SCHLICHTER Jorg")], [#age(22)], [#assoc("GER")], [?], [?], [?], [*2392*], [#delta(-1)],
      [64], [#name("约瑟夫 普拉希")], [#age(34)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2370*], [#delta(2)],
      [65], [#name("罗科 托西奇")], [#age(26)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2362*], [#delta(3)],
      [66], [#name("托本 沃西克")], [#age(32)], [#assoc("GER")], [?], [?], [?], [*2359*], [#delta(7)],
      [67], [#name("阿列克谢 斯米尔诺夫")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2356*], [#delta(-18)],
      [68], [#name("蒋澎龙")], [#age(29)], [#assoc("TPE")], [?], [?], [?], [*2352*], [#delta(3)],
      [69], [#name("芬 图格威尔")], [#age(29)], [#assoc("DEN")], [?], [?], [?], [*2349*], [#delta(-6)],
      [70], [#name("托马斯 凯纳特")], [#age(28)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2337*], [#delta(22)],
      [71], [#name("亚历山大 卡拉卡谢维奇")], [#age(30)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2335*], [#delta(1)],
      [72], [#name("费奥多尔 库兹明")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2328*], [#delta(43)],
      [73], [#name("VYBORNY Richard")], [#age(34)], [#assoc("CZE")], [?], [?], [?], [*2324*], [#delta(1)],
      [74], [#name("塞贡 托里奥拉")], [#age(31)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2324*], [#delta(1)],
      [75], [#name("佐兰 普里莫拉克")], [#age(36)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2320*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("张超")], [#age(20)], [#assoc("CHN")], [?], [?], [?], [*2318*], [#delta(1)],
      [77], [#name("帕特里克 奇拉")], [#age(36)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2317*], [#delta(1)],
      [78], [#name("帕尔 格雷尔")], [#age(23)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2302*], [#delta(74)],
      [79], [#name("CHO Jihoon")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2301*], [#delta(-15)],
      [80], [#name("岸川圣也")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2301*], [#delta(1)],
      [81], [#name("KIM Song Chol")], [#age(22)], [#assoc("PRK")], [?], [?], [?], [*2299*], [#delta(-2)],
      [82], [#name("PHUNG Armand")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2297*], [#delta(-2)],
      [83], [#name("约翰 阿克塞尔奎斯特")], [#age(20)], [#assoc("SWE")], [?], [?], [?], [*2293*], [#delta(95)],
      [84], [#name("尹在荣")], [#age(22)], [#assoc("KOR")], [?], [?], [?], [*2293*], [#delta(64)],
      [85], [#name("彼得 法泽卡斯")], [#age(24)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2287*], [#delta(23)],
      [86], [#name("NASIRU Kazeem")], [#age(31)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2283*], [#delta(-4)],
      [87], [#name("KUSINSKI Marcin")], [#age(34)], [#assoc("POL")], [?], [?], [?], [*2282*], [#delta(-4)],
      [88], [#name("彼得 塞雷达")], [#age(21)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2279*], [#delta(-29)],
      [89], [#name("拉尔斯 希尔舍")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2269*], [#delta(-4)],
      [90], [#name("亚历山大 迪杜赫")], [#age(23)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2269*], [#delta(-4)],
      [91], [#name("SAIVE Philippe")], [#age(34)], [#assoc("BEL")], [?], [?], [?], [*2267*], [#delta(-4)],
      [92], [#name("若昂 蒙泰罗")], [#age(22)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2266*], [#delta(37)],
      [93], [#name("蒂亚戈 蒙泰罗")], [#age(24)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2265*], [#delta(-4)],
      [94], [#name("盖尔 埃兰森")], [#age(29)], [#assoc("NOR")], [?], [?], [?], [*2262*], [#delta(-24)],
      [95], [#name("ZOOGLING Mikael")], [#age(30)], [#assoc("SWE")], [?], [?], [?], [*2254*], [#delta(-2)],
      [96], [#name("ABRAMOV Isaak")], [#age(34)], [#assoc("ISR")], [#right], [#shakehand], [#attack], [*2249*], [#delta(-2)],
      [97], [#name("小山雨果")], [#age(36)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2245*], [#delta(91)],
      [98], [#name("吴志祺")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2244*], [#delta(-3)],
      [99], [#name("王增羿")], [#age(22)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2241*], [#delta(-3)],
      [100], [#name("卢博米尔 皮斯特耶")], [#age(21)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2241*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("金泰勋")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2237*], [#delta(85)],
      [102], [#name("雅罗斯拉夫 扎穆登科")], [#age(17)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2237*], [#delta(-4)],
      [103], [#name("艾哈迈德 萨利赫")], [#age(26)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2236*], [#delta(-4)],
      [104], [#name("金正勋")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2233*], [#delta(-3)],
      [105], [#name("马克西姆 什梅廖夫")], [#age(34)], [#assoc("RUS")], [?], [?], [?], [*2228*], [#delta(-2)],
      [106], [#name("KITO Akira")], [#age(31)], [#assoc("JPN")], [?], [?], [?], [*2226*], [#delta(-2)],
      [107], [#name("马雷克 齐哈克")], [#age(31)], [#assoc("CZE")], [?], [?], [?], [*2226*], [#delta(-1)],
      [108], [#name("罗伯特 加尔多斯")], [#age(26)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2226*], [#delta(-20)],
      [109], [#name("叶夫根尼 齐特切蒂宁")], [#age(35)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2223*], [#delta(-2)],
      [110], [#name("丹尼尔 茨维克尔")], [#age(21)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2220*], [#delta(-8)],
      [111], [#name("谭瑞午")], [#age(22)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2219*], [#delta(-2)],
      [112], [#name("WANG Jianfeng")], [#age(39)], [#assoc("NOR")], [#right], [#penhold], [#attack], [*2214*], [#delta(-1)],
      [113], [#name("HUANG Johnny")], [#age(43)], [#assoc("CAN")], [?], [?], [?], [*2208*], [#delta(-1)],
      [114], [#name("罗伯特 斯文松")], [#age(22)], [#assoc("SWE")], [?], [?], [?], [*2206*], [#delta(29)],
      [115], [#name("基里尔 斯卡奇科夫")], [#age(18)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2206*], [#delta(-2)],
      [116], [#name("DEMETER Lehel")], [#age(27)], [#assoc("HUN")], [?], [?], [?], [*2197*], [#delta(-2)],
      [117], [#name("MITAMURA Muneaki")], [#age(24)], [#assoc("JPN")], [?], [?], [?], [*2192*], [#delta(-1)],
      [118], [#name("MOLDOVAN Istvan")], [#age(32)], [#assoc("NOR")], [?], [?], [?], [*2190*], [#delta(-51)],
      [119], [#name("CABESTANY Cedrik")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2186*], [#delta(-14)],
      [120], [#name("安德烈 菲利蒙")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2185*], [#delta(-2)],
      [121], [#name("埃里克 伊拉什")], [#age(25)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2180*], [#delta(-2)],
      [122], [#name("LUPULESKU Ilija")], [#age(38)], [#assoc("USA")], [?], [?], [?], [*2179*], [#delta(-2)],
      [123], [#name("迪米特里 奥恰洛夫")], [#age(17)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2178*], [#delta(-2)],
      [124], [#name("沙拉特 阿昌塔")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2175*], [#delta(1)],
      [125], [#name("HAKANSSON Fredrik")], [#age(30)], [#assoc("SWE")], [?], [?], [?], [*2174*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("松本和雄")], [#age(20)], [#assoc("BRA")], [#left], [#penhold], [#attack], [*2172*], [#delta(112)],
      [127], [#name("丹尼尔 古拉克")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2171*], [#delta(-3)],
      [128], [#name("KOSTAL Radek")], [#age(31)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2167*], [#delta(-2)],
      [129], [#name("AVCI Safa")], [#age(18)], [#assoc("TUR")], [?], [?], [?], [*2165*], [#delta(-2)],
      [130], [#name("李哲国")], [#age(20)], [#assoc("PRK")], [?], [?], [?], [*2164*], [#delta(-2)],
      [131], [#name("ZHOU Bin")], [#age(17)], [#assoc("CHN")], [?], [?], [?], [*2163*], [#delta(-1)],
      [132], [#name("阿列克谢 利文佐夫")], [#age(24)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2163*], [#delta(-1)],
      [133], [#name("SIMONER Christoph")], [#age(22)], [#assoc("AUT")], [?], [?], [?], [*2161*], [#delta(-1)],
      [134], [#name("MOLIN Magnus")], [#age(26)], [#assoc("SWE")], [?], [?], [?], [*2158*], [#delta(-24)],
      [135], [#name("蒂亚戈 阿波罗尼亚")], [#age(19)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2154*], [#delta(-45)],
      [136], [#name("康斯坦丁 乔蒂")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2152*], [#delta(-3)],
      [137], [#name("MILICEVIC Srdan")], [#age(29)], [#assoc("BIH")], [?], [?], [?], [*2150*], [#delta(-3)],
      [138], [#name("SANGUANSIN Phakpoom")], [#age(22)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2144*], [#delta(-2)],
      [139], [#name("HU Jiashun")], [#age(22)], [#assoc("SUI")], [?], [?], [?], [*2143*], [#delta(-2)],
      [140], [#name("崔贤珍")], [#age(26)], [#assoc("KOR")], [?], [?], [?], [*2139*], [#delta(-2)],
      [141], [#name("李镇权")], [#age(18)], [#assoc("KOR")], [?], [?], [?], [*2136*], [#delta(-50)],
      [142], [#name("ELENSKY Gregory")], [#age(21)], [#assoc("ISR")], [?], [?], [?], [*2131*], [#delta(47)],
      [143], [#name("CHOU Tung-Yu")], [#age(18)], [#assoc("TPE")], [?], [?], [?], [*2130*], [#delta(-3)],
      [144], [#name("安德烈 加奇尼")], [#age(19)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2126*], [#delta(-2)],
      [145], [#name("亚诺什 雅各布")], [#age(19)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2121*], [#delta(-61)],
      [146], [#name("LINDNER Adam")], [#age(30)], [#assoc("HUN")], [#right], [#penhold], [#attack], [*2120*], [#delta(-2)],
      [147], [#name("TRUKSA Jaromir")], [#age(34)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2119*], [#delta(-2)],
      [148], [#name("TASEI Kunihito")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2112*], [#delta(-2)],
      [149], [#name("REDJEP Ronald")], [#age(32)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2111*], [#delta(-2)],
      [150], [#name("GERADA Simon")], [#age(24)], [#assoc("AUS")], [?], [?], [?], [*2103*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("SAHA Subhajit")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2101*], [#delta(189)],
      [152], [#name("MANSSON Magnus")], [#age(29)], [#assoc("SWE")], [?], [?], [?], [*2101*], [#delta(-2)],
      [153], [#name("CAI Xiaoli")], [#age(26)], [#assoc("SGP")], [?], [?], [?], [*2098*], [#delta(-2)],
      [154], [#name("LENGEROV Kostadin")], [#age(29)], [#assoc("AUT")], [?], [?], [?], [*2096*], [#delta(-1)],
      [155], [#name("PIYADASA Thilina L")], [#age(26)], [#assoc("SRI")], [?], [?], [?], [*2094*], [#delta(0)],
      [156], [#name("BOBILLIER Loic")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2092*], [#delta(-15)],
      [157], [#name("李正三")], [#age(21)], [#assoc("KOR")], [?], [?], [?], [*2091*], [#delta(-1)],
      [158], [#name("塞巴斯蒂安 若韦尔")], [#age(30)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2088*], [#delta(-36)],
      [159], [#name("GRIGOREV Artur")], [#age(19)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2084*], [#delta(-24)],
      [160], [#name("NAKANO Yusuke")], [#age(21)], [#assoc("JPN")], [?], [?], [?], [*2077*], [#delta(-3)],
      [161], [#name("埃尔萨伊德 拉辛")], [#age(25)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2072*], [#delta(-3)],
      [162], [#name("卡洛斯 马查多")], [#age(25)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2069*], [#delta(-2)],
      [163], [#name("FETH Stefan")], [#age(25)], [#assoc("GER")], [?], [?], [?], [*2069*], [#delta(73)],
      [164], [#name("博扬 托基奇")], [#age(24)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2069*], [#delta(-3)],
      [165], [#name("坂本龙介")], [#age(21)], [#assoc("JPN")], [?], [?], [?], [*2068*], [#delta(-3)],
      [166], [#name("高木和卓")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2068*], [#delta(-2)],
      [167], [#name("PIACENTINI Valentino")], [#age(27)], [#assoc("ITA")], [?], [?], [?], [*2067*], [#delta(-4)],
      [168], [#name("古德蒙迪 斯蒂芬森")], [#age(23)], [#assoc("ISL")], [?], [?], [?], [*2064*], [#delta(-3)],
      [169], [#name("FADEEV Evgeny")], [#age(30)], [#assoc("RUS")], [?], [?], [?], [*2063*], [#delta(-3)],
      [170], [#name("VITSEK Ivan")], [#age(36)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2049*], [#delta(-1)],
      [171], [#name("VAINULA Vallot")], [#age(27)], [#assoc("EST")], [#right], [#shakehand], [#attack], [*2048*], [#delta(-1)],
      [172], [#name("帕特里克 鲍姆")], [#age(18)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2048*], [#delta(-1)],
      [173], [#name("KIHO Shinnosuke")], [#age(27)], [#assoc("JPN")], [?], [?], [?], [*2048*], [#delta(0)],
      [174], [#name("STENBERG Mattias")], [#age(29)], [#assoc("SWE")], [?], [?], [?], [*2048*], [#delta(0)],
      [175], [#name("布里斯 奥利维耶")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2046*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("VOSTES Yannick")], [#age(20)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2046*], [#delta(48)],
      [177], [#name("TABACHNIK Pablo")], [#age(28)], [#assoc("ARG")], [#left], [#shakehand], [#attack], [*2045*], [#delta(-23)],
      [178], [#name("ZHUANG David")], [#age(42)], [#assoc("USA")], [?], [?], [?], [*2045*], [#delta(-6)],
      [179], [#name("费伦茨 帕西")], [#age(31)], [#assoc("HUN")], [?], [?], [?], [*2043*], [#delta(-40)],
      [180], [#name("马克斯 弗雷塔斯")], [#age(17)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2043*], [#delta(12)],
      [181], [#name("MIZUNO Yuya")], [#age(18)], [#assoc("JPN")], [?], [?], [?], [*2043*], [#delta(-5)],
      [182], [#name("FAN Guoliang")], [#age(27)], [#assoc("ESP")], [?], [?], [?], [*2040*], [#delta(97)],
      [183], [#name("托马斯 科涅茨尼")], [#age(20)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2038*], [#delta(-6)],
      [184], [#name("佐尔特 佩托")], [#age(18)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2034*], [#delta(-5)],
      [185], [#name("PETROV Sergei")], [#age(35)], [#assoc("EST")], [?], [?], [?], [*2032*], [#delta(-4)],
      [186], [#name("QUENTEL Dorian")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2030*], [#delta(-4)],
      [187], [#name("ZUBCIC Tomislav")], [#age(19)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2027*], [#delta(-4)],
      [188], [#name("KRIEGER Alexander")], [#age(18)], [#assoc("GER")], [?], [?], [?], [*2025*], [#delta(-4)],
      [189], [#name("CHANG Yen-Shu")], [#age(26)], [#assoc("TPE")], [?], [?], [?], [*2024*], [#delta(-4)],
      [190], [#name("KONGSGAARD Christian")], [#age(22)], [#assoc("DEN")], [?], [?], [?], [*2023*], [#delta(33)],
      [191], [#name("ROBERTSON Adam")], [#age(21)], [#assoc("WAL")], [?], [?], [?], [*2020*], [#delta(-24)],
      [192], [#name("马雷克 克拉塞克")], [#age(30)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2018*], [#delta(-5)],
      [193], [#name("DESPRES Rodolphe")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2016*], [#delta(11)],
      [194], [#name("瓦西里 拉凯耶夫")], [#age(21)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2016*], [#delta(-4)],
      [195], [#name("MONDELLO Massimiliano")], [#age(30)], [#assoc("ITA")], [?], [?], [?], [*2012*], [#delta(-4)],
      [196], [#name("SANGUANSIN Phuchong")], [#age(25)], [#assoc("THA")], [?], [?], [?], [*2010*], [#delta(-2)],
      [197], [#name("SANCHEZ Victor")], [#age(28)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2010*], [#delta(-2)],
      [198], [#name("约瑟夫 西蒙契克")], [#age(25)], [#assoc("CZE")], [?], [?], [?], [*2007*], [#delta(-2)],
      [199], [#name("黄圣盛")], [#age(18)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2007*], [#delta(-2)],
      [200], [#name("AN Chol Yong")], [#age(20)], [#assoc("PRK")], [?], [?], [?], [*2006*], [#delta(-1)],
    )
  )
