#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("王励勤")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2999*], [#delta(0)],
      [2], [#name("马琳")], [#age(25)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2910*], [#delta(0)],
      [3], [#name("王皓")], [#age(22)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2813*], [#delta(1)],
      [4], [#name("陈玘")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2812*], [#delta(1)],
      [5], [#name("弗拉基米尔 萨姆索诺夫")], [#age(29)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2778*], [#delta(30)],
      [6], [#name("蒂姆 波尔")], [#age(24)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2771*], [#delta(-3)],
      [7], [#name("柳承敏")], [#age(23)], [#assoc("KOR")], [#right], [#penhold], [#attack], [*2717*], [#delta(-1)],
      [8], [#name("卡林尼科斯 格林卡")], [#age(33)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2700*], [#delta(-1)],
      [9], [#name("刘国正")], [#age(25)], [#assoc("CHN")], [?], [?], [?], [*2686*], [#delta(-1)],
      [10], [#name("特林科 基恩")], [#age(34)], [#assoc("NED")], [#left], [#shakehand], [#attack], [*2642*], [#delta(1)],
      [11], [#name("林聚")], [#age(26)], [#assoc("DOM")], [?], [?], [?], [*2641*], [#delta(8)],
      [12], [#name("维尔纳 施拉格")], [#age(33)], [#assoc("AUT")], [?], [?], [?], [*2634*], [#delta(-2)],
      [13], [#name("郝帅")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2627*], [#delta(-1)],
      [14], [#name("孔令辉")], [#age(30)], [#assoc("CHN")], [?], [?], [?], [*2620*], [#delta(0)],
      [15], [#name("米凯尔 梅兹")], [#age(24)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2614*], [#delta(-6)],
      [16], [#name("彼得 科贝尔")], [#age(34)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2603*], [#delta(0)],
      [17], [#name("唐鹏")], [#age(24)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2598*], [#delta(-2)],
      [18], [#name("朱世赫")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2590*], [#delta(-1)],
      [19], [#name("简 诺瓦 瓦尔德内尔")], [#age(40)], [#assoc("SWE")], [?], [?], [?], [*2588*], [#delta(-1)],
      [20], [#name("让 米歇尔 塞弗")], [#age(36)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2571*], [#delta(2)],
      [21], [#name("FRANZ Peter")], [#age(34)], [#assoc("GER")], [?], [?], [?], [*2557*], [#delta(3)],
      [22], [#name("吴尚垠")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2550*], [#delta(3)],
      [23], [#name("庄智渊")], [#age(24)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2534*], [#delta(27)],
      [24], [#name("陈卫星")], [#age(33)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2533*], [#delta(20)],
      [25], [#name("松下浩二")], [#age(38)], [#assoc("JPN")], [#right], [?], [#defense], [*2524*], [#delta(-12)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("罗伯特 加尔多斯")], [#age(26)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2523*], [#delta(21)],
      [27], [#name("梁柱恩")], [#age(26)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2520*], [#delta(-7)],
      [28], [#name("彼得 卡尔松")], [#age(36)], [#assoc("SWE")], [?], [?], [?], [*2507*], [#delta(2)],
      [29], [#name("高礼泽")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2506*], [#delta(-6)],
      [30], [#name("李静")], [#age(30)], [#assoc("HKG")], [?], [?], [?], [*2502*], [#delta(-2)],
      [31], [#name("卢兹扬 布拉斯奇克")], [#age(31)], [#assoc("POL")], [?], [?], [?], [*2499*], [#delta(-10)],
      [32], [#name("阿德里安 克里桑")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2497*], [#delta(9)],
      [33], [#name("FENG Zhe")], [#age(30)], [#assoc("BUL")], [?], [?], [?], [*2497*], [#delta(-4)],
      [34], [#name("马文革")], [#age(37)], [#assoc("CHN")], [?], [?], [?], [*2496*], [#delta(-2)],
      [35], [#name("李廷佑")], [#age(21)], [#assoc("KOR")], [#left], [#penhold], [#attack], [*2495*], [#delta(-2)],
      [36], [#name("高宁")], [#age(23)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2492*], [NEW],
      [37], [#name("蒋澎龙")], [#age(29)], [#assoc("TPE")], [?], [?], [?], [*2489*], [#delta(-3)],
      [38], [#name("MAZUNOV Dmitry")], [#age(34)], [#assoc("RUS")], [?], [?], [?], [*2479*], [#delta(-2)],
      [39], [#name("费奥多尔 库兹明")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2476*], [#delta(24)],
      [40], [#name("巴斯蒂安 斯特格")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2468*], [#delta(-9)],
      [41], [#name("张钰")], [#age(24)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2467*], [#delta(-15)],
      [42], [#name("巴托什 苏赫")], [#age(22)], [#assoc("POL")], [?], [?], [?], [*2463*], [#delta(38)],
      [43], [#name("詹斯 伦德奎斯特")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2458*], [#delta(8)],
      [44], [#name("佐尔坦 费杰科内斯")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2444*], [#delta(-5)],
      [45], [#name("托本 沃西克")], [#age(32)], [#assoc("GER")], [?], [?], [?], [*2439*], [#delta(-3)],
      [46], [#name("马龙")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2433*], [#delta(-1)],
      [47], [#name("刘松")], [#age(33)], [#assoc("ARG")], [?], [?], [?], [*2426*], [#delta(-1)],
      [48], [#name("HEISTER Danny")], [#age(34)], [#assoc("NED")], [#left], [#shakehand], [#attack], [*2423*], [#delta(36)],
      [49], [#name("马丁 奥列尼克")], [#age(33)], [#assoc("CZE")], [?], [?], [?], [*2422*], [#delta(-1)],
      [50], [#name("何志文")], [#age(43)], [#assoc("ESP")], [#left], [#penhold], [#attack], [*2422*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("拉尔斯 希尔舍")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2421*], [#delta(10)],
      [52], [#name("帕特里克 奇拉")], [#age(36)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2402*], [#delta(2)],
      [53], [#name("ROSSKOPF Jorg")], [#age(36)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2399*], [#delta(6)],
      [54], [#name("克里斯托夫 勒古")], [#age(32)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2393*], [#delta(2)],
      [55], [#name("SCHLICHTER Jorg")], [#age(22)], [#assoc("GER")], [?], [?], [?], [*2392*], [#delta(50)],
      [56], [#name("吉田海伟")], [#age(24)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2386*], [#delta(35)],
      [57], [#name("亚历山大 卡拉卡谢维奇")], [#age(30)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2386*], [#delta(-30)],
      [58], [#name("马丁 蒙拉德")], [#age(28)], [#assoc("DEN")], [?], [?], [?], [*2380*], [#delta(7)],
      [59], [#name("SAIVE Philippe")], [#age(34)], [#assoc("BEL")], [?], [?], [?], [*2379*], [#delta(-1)],
      [60], [#name("达米安 埃洛伊")], [#age(36)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2373*], [#delta(-22)],
      [61], [#name("约瑟夫 普拉希")], [#age(34)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2370*], [#delta(17)],
      [62], [#name("佐兰 普里莫拉克")], [#age(36)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2354*], [#delta(-9)],
      [63], [#name("杨子")], [#age(21)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2351*], [#delta(14)],
      [64], [#name("托马斯 凯纳特")], [#age(28)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2347*], [#delta(-27)],
      [65], [#name("克里斯蒂安 苏斯")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2334*], [#delta(-13)],
      [66], [#name("托马什 帕维尔卡")], [#age(25)], [#assoc("CZE")], [?], [?], [?], [*2331*], [#delta(-11)],
      [67], [#name("VYBORNY Richard")], [#age(34)], [#assoc("CZE")], [?], [?], [?], [*2324*], [#delta(8)],
      [68], [#name("TSIOKAS Ntaniel")], [#age(34)], [#assoc("GRE")], [?], [?], [?], [*2320*], [#delta(-25)],
      [69], [#name("张超")], [#age(20)], [#assoc("CHN")], [?], [?], [?], [*2318*], [#delta(-5)],
      [70], [#name("盖尔 埃兰森")], [#age(29)], [#assoc("NOR")], [?], [?], [?], [*2317*], [#delta(1)],
      [71], [#name("博扬 托基奇")], [#age(24)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2311*], [#delta(-11)],
      [72], [#name("丹尼尔 茨维克尔")], [#age(21)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2310*], [#delta(-6)],
      [73], [#name("杨敏")], [#age(42)], [#assoc("ITA")], [?], [?], [?], [*2307*], [#delta(-6)],
      [74], [#name("若昂 蒙泰罗")], [#age(22)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2305*], [#delta(36)],
      [75], [#name("PHUNG Armand")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2297*], [#delta(13)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("WANG Jianfeng")], [#age(39)], [#assoc("NOR")], [#right], [#penhold], [#attack], [*2295*], [#delta(-7)],
      [77], [#name("CABESTANY Cedrik")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2288*], [#delta(-4)],
      [78], [#name("阿兰 本特森")], [#age(37)], [#assoc("DEN")], [?], [?], [?], [*2286*], [#delta(-38)],
      [79], [#name("芬 图格威尔")], [#age(29)], [#assoc("DEN")], [?], [?], [?], [*2283*], [#delta(-17)],
      [80], [#name("KUSINSKI Marcin")], [#age(34)], [#assoc("POL")], [?], [?], [?], [*2282*], [#delta(82)],
      [81], [#name("PAK Won Chol")], [#age(24)], [#assoc("PRK")], [?], [?], [?], [*2274*], [#delta(-7)],
      [82], [#name("蒂亚戈 蒙泰罗")], [#age(24)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2267*], [#delta(-12)],
      [83], [#name("ZOOGLING Mikael")], [#age(30)], [#assoc("SWE")], [?], [?], [?], [*2254*], [#delta(0)],
      [84], [#name("康斯坦丁 乔蒂")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2251*], [#delta(13)],
      [85], [#name("亚历山大 迪杜赫")], [#age(23)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2250*], [#delta(2)],
      [86], [#name("丹尼尔 古拉克")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2245*], [#delta(-7)],
      [87], [#name("马克西姆 什梅廖夫")], [#age(34)], [#assoc("RUS")], [?], [?], [?], [*2242*], [#delta(-1)],
      [88], [#name("王增羿")], [#age(22)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2241*], [#delta(117)],
      [89], [#name("BOBILLIER Loic")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2239*], [#delta(100)],
      [90], [#name("迪米特里 奥恰洛夫")], [#age(17)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2235*], [#delta(77)],
      [91], [#name("费伦茨 帕西")], [#age(31)], [#assoc("HUN")], [?], [?], [?], [*2234*], [#delta(-19)],
      [92], [#name("MOLIN Magnus")], [#age(26)], [#assoc("SWE")], [?], [?], [?], [*2229*], [#delta(9)],
      [93], [#name("KITO Akira")], [#age(31)], [#assoc("JPN")], [?], [?], [?], [*2226*], [#delta(-4)],
      [94], [#name("马雷克 齐哈克")], [#age(31)], [#assoc("CZE")], [?], [?], [?], [*2226*], [#delta(48)],
      [95], [#name("叶夫根尼 齐特切蒂宁")], [#age(35)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2223*], [#delta(-5)],
      [96], [#name("LUPULESKU Ilija")], [#age(38)], [#assoc("USA")], [?], [?], [?], [*2220*], [#delta(-3)],
      [97], [#name("约尔根 佩尔森")], [#age(39)], [#assoc("SWE")], [?], [?], [?], [*2219*], [#delta(-3)],
      [98], [#name("谭瑞午")], [#age(22)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2219*], [NEW],
      [99], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(25)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2213*], [#delta(-4)],
      [100], [#name("斯洛博丹 格鲁伊奇")], [#age(32)], [#assoc("SRB")], [?], [?], [?], [*2211*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("GRIGOREV Artur")], [#age(19)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2208*], [#delta(53)],
      [102], [#name("CAI Xiaoli")], [#age(26)], [#assoc("SGP")], [?], [?], [?], [*2208*], [#delta(135)],
      [103], [#name("阿列克谢 利文佐夫")], [#age(24)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2206*], [#delta(-22)],
      [104], [#name("卢博米尔 皮斯特耶")], [#age(21)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2204*], [#delta(48)],
      [105], [#name("PIACENTINI Valentino")], [#age(27)], [#assoc("ITA")], [?], [?], [?], [*2198*], [#delta(-1)],
      [106], [#name("DEMETER Lehel")], [#age(27)], [#assoc("HUN")], [?], [?], [?], [*2197*], [#delta(-7)],
      [107], [#name("崔贤珍")], [#age(26)], [#assoc("KOR")], [?], [?], [?], [*2194*], [#delta(0)],
      [108], [#name("罗科 托西奇")], [#age(26)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2193*], [#delta(23)],
      [109], [#name("安德烈 菲利蒙")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2193*], [#delta(15)],
      [110], [#name("MITAMURA Muneaki")], [#age(24)], [#assoc("JPN")], [?], [?], [?], [*2192*], [#delta(-2)],
      [111], [#name("约翰 阿克塞尔奎斯特")], [#age(20)], [#assoc("SWE")], [?], [?], [?], [*2185*], [#delta(-15)],
      [112], [#name("林载贤")], [#age(20)], [#assoc("KOR")], [?], [?], [?], [*2183*], [#delta(-1)],
      [113], [#name("塞巴斯蒂安 若韦尔")], [#age(30)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2177*], [#delta(55)],
      [114], [#name("HAKANSSON Fredrik")], [#age(30)], [#assoc("SWE")], [?], [?], [?], [*2174*], [#delta(-29)],
      [115], [#name("HUANG Johnny")], [#age(43)], [#assoc("CAN")], [?], [?], [?], [*2174*], [#delta(-2)],
      [116], [#name("沙拉特 阿昌塔")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2169*], [#delta(-2)],
      [117], [#name("阿列克谢 斯米尔诺夫")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2167*], [#delta(-17)],
      [118], [#name("ZHOU Bin")], [#age(17)], [#assoc("CHN")], [?], [?], [?], [*2163*], [#delta(-1)],
      [119], [#name("SIMONER Christoph")], [#age(22)], [#assoc("AUT")], [?], [?], [?], [*2161*], [#delta(111)],
      [120], [#name("金正勋")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2161*], [#delta(-1)],
      [121], [#name("KIM Song Chol")], [#age(22)], [#assoc("PRK")], [?], [?], [?], [*2158*], [#delta(-1)],
      [122], [#name("金泰勋")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2157*], [#delta(-1)],
      [123], [#name("TAKAKIWA Kenichi")], [#age(21)], [#assoc("JPN")], [?], [?], [?], [*2155*], [#delta(-8)],
      [124], [#name("岸川圣也")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2155*], [#delta(-15)],
      [125], [#name("ZHUANG David")], [#age(42)], [#assoc("USA")], [?], [?], [?], [*2149*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("赵彦来")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2146*], [#delta(-1)],
      [127], [#name("罗伯特 斯文松")], [#age(22)], [#assoc("SWE")], [?], [?], [?], [*2144*], [#delta(1)],
      [128], [#name("SANGUANSIN Phakpoom")], [#age(22)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2144*], [#delta(-2)],
      [129], [#name("HU Jiashun")], [#age(22)], [#assoc("SUI")], [?], [?], [?], [*2143*], [#delta(42)],
      [130], [#name("BERTIN Christophe")], [#age(20)], [#assoc("FRA")], [?], [?], [?], [*2137*], [#delta(-54)],
      [131], [#name("LEE Chulseung")], [#age(33)], [#assoc("KOR")], [?], [?], [?], [*2134*], [#delta(-39)],
      [132], [#name("安德烈 加奇尼")], [#age(19)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2125*], [#delta(182)],
      [133], [#name("彼得 塞雷达")], [#age(21)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2125*], [#delta(-27)],
      [134], [#name("OMAR Rashid")], [#age(17)], [#assoc("UAE")], [?], [?], [?], [*2125*], [#delta(-2)],
      [135], [#name("ABRAMOV Isaak")], [#age(34)], [#assoc("ISR")], [#right], [#shakehand], [#attack], [*2123*], [#delta(-1)],
      [136], [#name("LINDNER Adam")], [#age(30)], [#assoc("HUN")], [#right], [#penhold], [#attack], [*2120*], [#delta(-3)],
      [137], [#name("TRUKSA Jaromir")], [#age(34)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2119*], [#delta(-2)],
      [138], [#name("LENGEROV Kostadin")], [#age(29)], [#assoc("AUT")], [?], [?], [?], [*2116*], [#delta(-26)],
      [139], [#name("TASEI Kunihito")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2112*], [#delta(-2)],
      [140], [#name("REDJEP Ronald")], [#age(32)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2111*], [#delta(16)],
      [141], [#name("埃尔萨伊德 拉辛")], [#age(25)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2109*], [#delta(-3)],
      [142], [#name("IGNJATOVIC Sasa")], [#age(31)], [#assoc("SLO")], [?], [?], [?], [*2106*], [#delta(38)],
      [143], [#name("MANSSON Magnus")], [#age(29)], [#assoc("SWE")], [?], [?], [?], [*2101*], [#delta(-3)],
      [144], [#name("李正三")], [#age(21)], [#assoc("KOR")], [?], [?], [?], [*2095*], [#delta(-3)],
      [145], [#name("AL-HAMMADI Hamad")], [#age(30)], [#assoc("QAT")], [?], [?], [?], [*2085*], [#delta(-1)],
      [146], [#name("塞贡 托里奥拉")], [#age(31)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2083*], [#delta(-1)],
      [147], [#name("彼得 法泽卡斯")], [#age(24)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2079*], [#delta(-45)],
      [148], [#name("ROY Soumyadeep")], [#age(21)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2078*], [#delta(-1)],
      [149], [#name("李镇权")], [#age(18)], [#assoc("KOR")], [?], [?], [?], [*2077*], [#delta(-1)],
      [150], [#name("LO Dany")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2077*], [#delta(22)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("坂本龙介")], [#age(21)], [#assoc("JPN")], [?], [?], [?], [*2071*], [#delta(-29)],
      [152], [#name("NASIRU Kazeem")], [#age(31)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2068*], [#delta(-1)],
      [153], [#name("SURBEK Dragutin")], [#age(28)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2066*], [#delta(0)],
      [154], [#name("水谷隼")], [#age(16)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2063*], [#delta(-25)],
      [155], [#name("FADEEV Evgeny")], [#age(30)], [#assoc("RUS")], [?], [?], [?], [*2063*], [#delta(-9)],
      [156], [#name("吴志祺")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2056*], [#delta(2)],
      [157], [#name("雅罗斯拉夫 扎穆登科")], [#age(17)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2054*], [#delta(160)],
      [158], [#name("PIYADASA Thilina L")], [#age(26)], [#assoc("SRI")], [?], [?], [?], [*2051*], [#delta(3)],
      [159], [#name("古德蒙迪 斯蒂芬森")], [#age(23)], [#assoc("ISL")], [?], [?], [?], [*2049*], [#delta(4)],
      [160], [#name("VITSEK Ivan")], [#age(36)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2049*], [#delta(-3)],
      [161], [#name("KIHO Shinnosuke")], [#age(27)], [#assoc("JPN")], [?], [?], [?], [*2048*], [#delta(3)],
      [162], [#name("STENBERG Mattias")], [#age(29)], [#assoc("SWE")], [?], [?], [?], [*2048*], [#delta(3)],
      [163], [#name("TAVUKCUOGLU Irfan")], [#age(26)], [#assoc("TUR")], [?], [?], [?], [*2047*], [#delta(3)],
      [164], [#name("布里斯 奥利维耶")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2046*], [#delta(-37)],
      [165], [#name("尹在荣")], [#age(22)], [#assoc("KOR")], [?], [?], [?], [*2044*], [#delta(8)],
      [166], [#name("帕特里克 鲍姆")], [#age(18)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2041*], [#delta(-50)],
      [167], [#name("ROBERTSON Adam")], [#age(21)], [#assoc("WAL")], [?], [?], [?], [*2039*], [#delta(24)],
      [168], [#name("托马斯 科涅茨尼")], [#age(20)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2038*], [#delta(2)],
      [169], [#name("BALL Andreas")], [#age(21)], [#assoc("GER")], [?], [?], [?], [*2034*], [#delta(7)],
      [170], [#name("FETH Stefan")], [#age(25)], [#assoc("GER")], [?], [?], [?], [*2032*], [#delta(-1)],
      [171], [#name("QUENTEL Dorian")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2030*], [#delta(77)],
      [172], [#name("JENKINS Ryan")], [#age(27)], [#assoc("WAL")], [#right], [#shakehand], [#attack], [*2029*], [#delta(5)],
      [173], [#name("马雷克 克拉塞克")], [#age(30)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2024*], [#delta(-70)],
      [174], [#name("MONDELLO Massimiliano")], [#age(30)], [#assoc("ITA")], [?], [?], [?], [*2024*], [#delta(-15)],
      [175], [#name("JIANG Weizhong")], [#age(37)], [#assoc("CRO")], [?], [?], [?], [*2022*], [#delta(3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("松本和雄")], [#age(20)], [#assoc("BRA")], [#left], [#penhold], [#attack], [*2018*], [#delta(-2)],
      [177], [#name("马克 杜兰")], [#age(19)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2017*], [#delta(-59)],
      [178], [#name("瓦西里 拉凯耶夫")], [#age(21)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2016*], [#delta(1)],
      [179], [#name("江宏杰")], [#age(16)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2014*], [#delta(2)],
      [180], [#name("MOLDOVAN Istvan")], [#age(32)], [#assoc("NOR")], [?], [?], [?], [*2012*], [#delta(-31)],
      [181], [#name("高木和卓")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2011*], [#delta(-51)],
      [182], [#name("马克斯 弗雷塔斯")], [#age(17)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2011*], [#delta(1)],
      [183], [#name("SANGUANSIN Phuchong")], [#age(25)], [#assoc("THA")], [?], [?], [?], [*2010*], [#delta(1)],
      [184], [#name("约瑟夫 西蒙契克")], [#age(25)], [#assoc("CZE")], [?], [?], [?], [*2007*], [#delta(55)],
      [185], [#name("SHARON Yaniv")], [#age(27)], [#assoc("ISR")], [#left], [#shakehand], [#attack], [*2005*], [#delta(1)],
      [186], [#name("许昕")], [#age(15)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*2002*], [#delta(1)],
      [187], [#name("VOZICKY Bohumil")], [#age(28)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*1999*], [#delta(5)],
      [188], [#name("PARAPANOV Konstantin")], [#age(29)], [#assoc("BUL")], [#right], [#shakehand], [#attack], [*1992*], [#delta(5)],
      [189], [#name("雅库布 科索夫斯基")], [#age(23)], [#assoc("POL")], [?], [?], [?], [*1989*], [#delta(-34)],
      [190], [#name("伊戈尔 鲁布佐夫")], [#age(25)], [#assoc("RUS")], [?], [?], [?], [*1988*], [#delta(-40)],
      [191], [#name("LIN Chen")], [#age(16)], [#assoc("CHN")], [?], [?], [?], [*1986*], [#delta(5)],
      [192], [#name("MUJICA Henry")], [#age(27)], [#assoc("VEN")], [?], [?], [?], [*1986*], [#delta(5)],
      [193], [#name("PETERSEN Christoffer")], [#age(22)], [#assoc("DEN")], [?], [?], [?], [*1985*], [#delta(67)],
      [194], [#name("ASATRYAN Murad")], [#age(21)], [#assoc("ARM")], [?], [?], [?], [*1983*], [#delta(4)],
      [195], [#name("康斯坦丁诺斯 帕帕乔治乌")], [#age(26)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*1980*], [#delta(-56)],
      [196], [#name("MILICEVIC Srdan")], [#age(29)], [#assoc("BIH")], [?], [?], [?], [*1978*], [#delta(-1)],
      [197], [#name("JINDRAK Karl")], [#age(33)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*1977*], [#delta(48)],
      [198], [#name("SLEVIN Colum")], [#age(41)], [#assoc("IRL")], [?], [?], [?], [*1977*], [#delta(1)],
      [199], [#name("CHOU Tung-Yu")], [#age(18)], [#assoc("TPE")], [?], [?], [?], [*1977*], [#delta(1)],
      [200], [#name("卢文 菲鲁斯")], [#age(17)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*1974*], [#delta(6)],
    )
  )
