#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("王励勤")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3004*], [#delta(0)],
      [2], [#name("蒂姆 波尔")], [#age(24)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2934*], [#delta(0)],
      [3], [#name("马琳")], [#age(25)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2875*], [#delta(0)],
      [4], [#name("王皓")], [#age(22)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2858*], [#delta(0)],
      [5], [#name("弗拉基米尔 萨姆索诺夫")], [#age(29)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2853*], [#delta(1)],
      [6], [#name("马龙")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2827*], [#delta(1)],
      [7], [#name("陈玘")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2787*], [#delta(-2)],
      [8], [#name("孔令辉")], [#age(30)], [#assoc("CHN")], [?], [?], [?], [*2719*], [#delta(0)],
      [9], [#name("李廷佑")], [#age(21)], [#assoc("KOR")], [#left], [#penhold], [#attack], [*2677*], [#delta(4)],
      [10], [#name("卡林尼科斯 格林卡")], [#age(33)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2663*], [#delta(16)],
      [11], [#name("阿德里安 克里桑")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2658*], [#delta(1)],
      [12], [#name("吴尚垠")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2651*], [#delta(-2)],
      [13], [#name("米凯尔 梅兹")], [#age(24)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2650*], [#delta(2)],
      [14], [#name("让 米歇尔 赛弗")], [#age(36)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2650*], [#delta(14)],
      [15], [#name("特林科 基恩")], [#age(34)], [#assoc("NED")], [#left], [#shakehand], [#attack], [*2629*], [#delta(27)],
      [16], [#name("郝帅")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2610*], [#delta(-2)],
      [17], [#name("佐兰 普里莫拉克")], [#age(36)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2587*], [#delta(5)],
      [18], [#name("YANG Zi")], [#age(21)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2585*], [#delta(3)],
      [19], [#name("朱世赫")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2583*], [#delta(0)],
      [20], [#name("HEISTER Danny")], [#age(34)], [#assoc("NED")], [#left], [#shakehand], [#attack], [*2576*], [#delta(3)],
      [21], [#name("维尔纳 施拉格")], [#age(33)], [#assoc("AUT")], [?], [?], [?], [*2564*], [#delta(9)],
      [22], [#name("陈卫星")], [#age(33)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2564*], [#delta(26)],
      [23], [#name("彼得 卡尔松")], [#age(36)], [#assoc("SWE")], [?], [?], [?], [*2547*], [#delta(-3)],
      [24], [#name("张钰")], [#age(24)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2545*], [#delta(32)],
      [25], [#name("庄智渊")], [#age(24)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2533*], [#delta(46)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(25)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2525*], [#delta(29)],
      [27], [#name("LIN Ju")], [#age(26)], [#assoc("DOM")], [?], [?], [?], [*2523*], [#delta(37)],
      [28], [#name("FENG Zhe")], [#age(30)], [#assoc("BUL")], [?], [?], [?], [*2522*], [#delta(-17)],
      [29], [#name("谭瑞午")], [#age(22)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2519*], [#delta(25)],
      [30], [#name("何志文")], [#age(43)], [#assoc("ESP")], [#left], [#penhold], [#attack], [*2519*], [#delta(-1)],
      [31], [#name("亚历山大 卡拉卡谢维奇")], [#age(30)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2514*], [#delta(41)],
      [32], [#name("蒋澎龙")], [#age(29)], [#assoc("TPE")], [?], [?], [?], [*2512*], [#delta(0)],
      [33], [#name("ROSSKOPF Jorg")], [#age(36)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2509*], [#delta(0)],
      [34], [#name("柳承敏")], [#age(23)], [#assoc("KOR")], [#right], [#penhold], [#attack], [*2504*], [#delta(-17)],
      [35], [#name("BENTSEN Allan")], [#age(37)], [#assoc("DEN")], [?], [?], [?], [*2498*], [#delta(0)],
      [36], [#name("高礼泽")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2497*], [#delta(0)],
      [37], [#name("马文革")], [#age(37)], [#assoc("CHN")], [?], [?], [?], [*2496*], [#delta(0)],
      [38], [#name("卢兹扬 布拉斯奇克")], [#age(31)], [#assoc("POL")], [?], [?], [?], [*2480*], [#delta(-22)],
      [39], [#name("OLEJNIK Martin")], [#age(33)], [#assoc("CZE")], [?], [?], [?], [*2480*], [#delta(14)],
      [40], [#name("李静")], [#age(30)], [#assoc("HKG")], [?], [?], [?], [*2477*], [#delta(0)],
      [41], [#name("RI Chol Guk")], [#age(20)], [#assoc("PRK")], [?], [?], [?], [*2465*], [#delta(2)],
      [42], [#name("WANG Zengyi")], [#age(22)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2463*], [#delta(64)],
      [43], [#name("简 诺瓦 瓦尔德内尔")], [#age(40)], [#assoc("SWE")], [?], [?], [?], [*2463*], [#delta(1)],
      [44], [#name("MONRAD Martin")], [#age(28)], [#assoc("DEN")], [?], [?], [?], [*2453*], [#delta(1)],
      [45], [#name("水谷隼")], [#age(16)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2452*], [#delta(13)],
      [46], [#name("唐鹏")], [#age(24)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2446*], [#delta(-28)],
      [47], [#name("达米安 艾洛伊")], [#age(36)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2434*], [#delta(0)],
      [48], [#name("高宁")], [#age(23)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2433*], [#delta(2)],
      [49], [#name("FEJER-KONNERTH Zoltan")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2429*], [#delta(36)],
      [50], [#name("FRANZ Peter")], [#age(34)], [#assoc("GER")], [?], [?], [?], [*2428*], [#delta(11)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("WOSIK Torben")], [#age(32)], [#assoc("GER")], [?], [?], [?], [*2423*], [#delta(28)],
      [52], [#name("KEINATH Thomas")], [#age(28)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2418*], [#delta(-18)],
      [53], [#name("约尔根 佩尔森")], [#age(39)], [#assoc("SWE")], [?], [?], [?], [*2405*], [#delta(6)],
      [54], [#name("TOSIC Roko")], [#age(26)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2404*], [#delta(-5)],
      [55], [#name("帕特里克 奇拉")], [#age(36)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2404*], [#delta(-30)],
      [56], [#name("XU Hui")], [#age(22)], [#assoc("CHN")], [?], [?], [?], [*2397*], [NEW],
      [57], [#name("ERLANDSEN Geir")], [#age(29)], [#assoc("NOR")], [?], [?], [?], [*2395*], [#delta(38)],
      [58], [#name("LIU Song")], [#age(33)], [#assoc("ARG")], [?], [?], [?], [*2395*], [#delta(4)],
      [59], [#name("YANG Min")], [#age(42)], [#assoc("ITA")], [?], [?], [?], [*2395*], [#delta(-7)],
      [60], [#name("JAKAB Janos")], [#age(19)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2394*], [#delta(91)],
      [61], [#name("巴斯蒂安 斯蒂格")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2392*], [#delta(-10)],
      [62], [#name("吉田海伟")], [#age(24)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2388*], [#delta(-2)],
      [63], [#name("SHMYREV Maxim")], [#age(34)], [#assoc("RUS")], [?], [?], [?], [*2386*], [#delta(46)],
      [64], [#name("MAZUNOV Dmitry")], [#age(34)], [#assoc("RUS")], [?], [?], [?], [*2385*], [#delta(-25)],
      [65], [#name("SUCH Bartosz")], [#age(22)], [#assoc("POL")], [?], [?], [?], [*2382*], [#delta(-41)],
      [66], [#name("金赫峰")], [#age(20)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2374*], [#delta(0)],
      [67], [#name("GERELL Par")], [#age(23)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2371*], [#delta(3)],
      [68], [#name("松下浩二")], [#age(38)], [#assoc("JPN")], [#right], [?], [#defense], [*2368*], [#delta(0)],
      [69], [#name("阿列克谢 斯米尔诺夫")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2365*], [#delta(4)],
      [70], [#name("LEGOUT Christophe")], [#age(32)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2361*], [#delta(-39)],
      [71], [#name("GRUJIC Slobodan")], [#age(32)], [#assoc("SRB")], [?], [?], [?], [*2358*], [#delta(-30)],
      [72], [#name("克里斯蒂安 苏斯")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2354*], [#delta(6)],
      [73], [#name("KUSINSKI Marcin")], [#age(34)], [#assoc("POL")], [?], [?], [?], [*2351*], [#delta(16)],
      [74], [#name("PLACHY Josef")], [#age(34)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2346*], [#delta(-7)],
      [75], [#name("江天一")], [#age(17)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2345*], [#delta(605)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("罗伯特 加尔多斯")], [#age(26)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2343*], [#delta(21)],
      [77], [#name("LEE Jungsam")], [#age(21)], [#assoc("KOR")], [?], [?], [?], [*2336*], [#delta(26)],
      [78], [#name("DIDUKH Oleksandr")], [#age(23)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2335*], [#delta(13)],
      [79], [#name("CHO Eonrae")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2334*], [#delta(-16)],
      [80], [#name("彼得 科贝尔")], [#age(34)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2328*], [#delta(-53)],
      [81], [#name("PAVELKA Tomas")], [#age(25)], [#assoc("CZE")], [?], [?], [?], [*2325*], [#delta(-43)],
      [82], [#name("TORIOLA Segun")], [#age(31)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2324*], [#delta(-6)],
      [83], [#name("梁柱恩")], [#age(26)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2312*], [#delta(-9)],
      [84], [#name("HOYAMA Hugo")], [#age(36)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2300*], [#delta(21)],
      [85], [#name("KIM Song Chol")], [#age(22)], [#assoc("PRK")], [?], [?], [?], [*2299*], [#delta(-1)],
      [86], [#name("岸川圣也")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2293*], [#delta(-4)],
      [87], [#name("VARGA Zoltan")], [#age(31)], [#assoc("HUN")], [?], [?], [?], [*2293*], [#delta(188)],
      [88], [#name("BOBILLIER Loic")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2291*], [#delta(249)],
      [89], [#name("LIM Jaehyun")], [#age(20)], [#assoc("KOR")], [?], [?], [?], [*2286*], [#delta(-43)],
      [90], [#name("VYBORNY Richard")], [#age(34)], [#assoc("CZE")], [?], [?], [?], [*2285*], [#delta(-15)],
      [91], [#name("NASIRU Kazeem")], [#age(31)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2283*], [#delta(-3)],
      [92], [#name("尹在荣")], [#age(22)], [#assoc("KOR")], [?], [?], [?], [*2281*], [#delta(-35)],
      [93], [#name("PISTEJ Lubomir")], [#age(21)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2281*], [#delta(72)],
      [94], [#name("CHIANG Hung-Chieh")], [#age(16)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2278*], [#delta(-4)],
      [95], [#name("KUZMIN Fedor")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2276*], [#delta(-12)],
      [96], [#name("VOZICKY Bohumil")], [#age(28)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2268*], [#delta(109)],
      [97], [#name("迪米特里 奥恰洛夫")], [#age(17)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2267*], [#delta(3)],
      [98], [#name("SAIVE Philippe")], [#age(34)], [#assoc("BEL")], [?], [?], [?], [*2267*], [#delta(-6)],
      [99], [#name("CHOI Hyunjin")], [#age(26)], [#assoc("KOR")], [?], [?], [?], [*2264*], [#delta(-5)],
      [100], [#name("ZUBCIC Tomislav")], [#age(19)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2252*], [#delta(90)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("ABRAMOV Isaak")], [#age(34)], [#assoc("ISR")], [#right], [#shakehand], [#attack], [*2249*], [#delta(0)],
      [102], [#name("FILIMON Andrei")], [#age(28)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2248*], [#delta(22)],
      [103], [#name("MOLDOVAN Istvan")], [#age(32)], [#assoc("NOR")], [?], [?], [?], [*2248*], [#delta(18)],
      [104], [#name("OMORI Takahiro")], [#age(27)], [#assoc("JPN")], [?], [?], [?], [*2245*], [#delta(0)],
      [105], [#name("CHTCHETININE Evgueni")], [#age(35)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2242*], [#delta(7)],
      [106], [#name("WANG Jianfeng")], [#age(39)], [#assoc("NOR")], [#right], [#penhold], [#attack], [*2239*], [#delta(9)],
      [107], [#name("KIM Taehoon")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2237*], [#delta(0)],
      [108], [#name("CABESTANY Cedrik")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2231*], [#delta(15)],
      [109], [#name("PHUNG Armand")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2228*], [#delta(-23)],
      [110], [#name("JIANG Weizhong")], [#age(37)], [#assoc("CRO")], [?], [?], [?], [*2227*], [#delta(102)],
      [111], [#name("JOVER Sebastien")], [#age(30)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2225*], [#delta(52)],
      [112], [#name("博扬 托基奇")], [#age(24)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2221*], [#delta(58)],
      [113], [#name("AN Chol Yong")], [#age(20)], [#assoc("PRK")], [?], [?], [?], [*2220*], [#delta(0)],
      [114], [#name("LO Dany")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2210*], [#delta(-34)],
      [115], [#name("詹斯 伦德奎斯特")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2209*], [#delta(-50)],
      [116], [#name("HUANG Johnny")], [#age(43)], [#assoc("CAN")], [?], [?], [?], [*2208*], [#delta(0)],
      [117], [#name("JANG Song Man")], [#age(20)], [#assoc("PRK")], [?], [?], [?], [*2208*], [#delta(0)],
      [118], [#name("ILLAS Erik")], [#age(25)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2207*], [#delta(8)],
      [119], [#name("FAZEKAS Peter")], [#age(24)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2207*], [#delta(-32)],
      [120], [#name("SEREDA Peter")], [#age(21)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2200*], [#delta(-51)],
      [121], [#name("李平")], [#age(19)], [#assoc("QAT")], [#right], [#shakehand], [#attack], [*2199*], [NEW],
      [122], [#name("CARNEROS Alfredo")], [#age(27)], [#assoc("ESP")], [?], [?], [?], [*2199*], [#delta(93)],
      [123], [#name("LEE Jinkwon")], [#age(18)], [#assoc("KOR")], [?], [?], [?], [*2198*], [#delta(-25)],
      [124], [#name("ZWICKL Daniel")], [#age(21)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2188*], [#delta(-10)],
      [125], [#name("SALEH Ahmed")], [#age(26)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2186*], [#delta(-3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("HIELSCHER Lars")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2184*], [#delta(13)],
      [127], [#name("STENBERG Mattias")], [#age(29)], [#assoc("SWE")], [?], [?], [?], [*2184*], [#delta(51)],
      [128], [#name("LUPULESKU Ilija")], [#age(38)], [#assoc("USA")], [?], [?], [?], [*2179*], [#delta(-1)],
      [129], [#name("SVENSSON Robert")], [#age(22)], [#assoc("SWE")], [?], [?], [?], [*2177*], [#delta(-11)],
      [130], [#name("ROBERTSON Adam")], [#age(21)], [#assoc("WAL")], [?], [?], [?], [*2176*], [#delta(63)],
      [131], [#name("CHO Jihoon")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2176*], [#delta(16)],
      [132], [#name("AVCI Safa")], [#age(18)], [#assoc("TUR")], [?], [?], [?], [*2165*], [#delta(3)],
      [133], [#name("ZHOU Bin")], [#age(17)], [#assoc("CHN")], [?], [?], [?], [*2163*], [#delta(3)],
      [134], [#name("ACHANTA Sharath")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2162*], [#delta(-6)],
      [135], [#name("MONTEIRO Thiago")], [#age(24)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2161*], [#delta(-42)],
      [136], [#name("KLASEK Marek")], [#age(30)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2161*], [#delta(58)],
      [137], [#name("CIHAK Marek")], [#age(31)], [#assoc("CZE")], [?], [?], [?], [*2160*], [#delta(-26)],
      [138], [#name("TAKAKIWA Taku")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2158*], [#delta(-6)],
      [139], [#name("TUGWELL Finn")], [#age(29)], [#assoc("DEN")], [?], [?], [?], [*2157*], [#delta(-37)],
      [140], [#name("ANDRIANOV Sergei")], [#age(29)], [#assoc("RUS")], [?], [?], [?], [*2156*], [#delta(201)],
      [141], [#name("HAKANSSON Fredrik")], [#age(30)], [#assoc("SWE")], [?], [?], [?], [*2155*], [#delta(-12)],
      [142], [#name("MATSUMOTO Cazuo")], [#age(20)], [#assoc("BRA")], [#left], [#penhold], [#attack], [*2154*], [#delta(-12)],
      [143], [#name("CIOTI Constantin")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2152*], [#delta(-1)],
      [144], [#name("SAKAMOTO Ryusuke")], [#age(21)], [#assoc("JPN")], [?], [?], [?], [*2152*], [#delta(48)],
      [145], [#name("KIM Junghoon")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2152*], [#delta(12)],
      [146], [#name("丹尼尔 哈贝松")], [#age(19)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2146*], [#delta(73)],
      [147], [#name("SANGUANSIN Phakpoom")], [#age(22)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2144*], [#delta(-2)],
      [148], [#name("TAKAKIWA Kenichi")], [#age(21)], [#assoc("JPN")], [?], [?], [?], [*2142*], [#delta(111)],
      [149], [#name("ZHANG Wilson")], [#age(26)], [#assoc("CAN")], [?], [?], [?], [*2141*], [#delta(-68)],
      [150], [#name("GRIGOREV Artur")], [#age(19)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2139*], [#delta(14)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("PAZSY Ferenc")], [#age(31)], [#assoc("HUN")], [?], [?], [?], [*2138*], [#delta(31)],
      [152], [#name("马克斯 弗雷塔斯")], [#age(17)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2135*], [#delta(23)],
      [153], [#name("HU Jiashun")], [#age(22)], [#assoc("SUI")], [?], [?], [?], [*2135*], [#delta(-7)],
      [154], [#name("MANSSON Magnus")], [#age(29)], [#assoc("SWE")], [?], [?], [?], [*2133*], [#delta(6)],
      [155], [#name("STEPHENSEN Gudmundur")], [#age(23)], [#assoc("ISL")], [?], [?], [?], [*2132*], [#delta(18)],
      [156], [#name("SIMONER Christoph")], [#age(22)], [#assoc("AUT")], [?], [?], [?], [*2129*], [#delta(-18)],
      [157], [#name("CHANG Yen-Shu")], [#age(26)], [#assoc("TPE")], [?], [?], [?], [*2126*], [#delta(-8)],
      [158], [#name("KITO Akira")], [#age(31)], [#assoc("JPN")], [?], [?], [?], [*2120*], [#delta(-5)],
      [159], [#name("MACHADO Carlos")], [#age(25)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2120*], [#delta(26)],
      [160], [#name("KOSOWSKI Jakub")], [#age(23)], [#assoc("POL")], [?], [?], [?], [*2119*], [#delta(50)],
      [161], [#name("TRUKSA Jaromir")], [#age(34)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2119*], [#delta(-7)],
      [162], [#name("KOSTAL Radek")], [#age(31)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2118*], [#delta(-28)],
      [163], [#name("基里尔 斯卡奇科夫")], [#age(18)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2117*], [#delta(-44)],
      [164], [#name("BERTIN Christophe")], [#age(20)], [#assoc("FRA")], [?], [?], [?], [*2115*], [#delta(-31)],
      [165], [#name("KONGSGAARD Christian")], [#age(22)], [#assoc("DEN")], [?], [?], [?], [*2111*], [#delta(-55)],
      [166], [#name("DEMETER Lehel")], [#age(27)], [#assoc("HUN")], [?], [?], [?], [*2107*], [#delta(-46)],
      [167], [#name("FETH Stefan")], [#age(25)], [#assoc("GER")], [?], [?], [?], [*2106*], [#delta(2)],
      [168], [#name("MONTEIRO Joao")], [#age(22)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2103*], [#delta(0)],
      [169], [#name("GERADA Simon")], [#age(24)], [#assoc("AUS")], [?], [?], [?], [*2103*], [#delta(-11)],
      [170], [#name("KONECNY Tomas")], [#age(20)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2100*], [#delta(16)],
      [171], [#name("LENGEROV Kostadin")], [#age(29)], [#assoc("AUT")], [?], [?], [?], [*2096*], [#delta(-10)],
      [172], [#name("PIYADASA Thilina L")], [#age(26)], [#assoc("SRI")], [?], [?], [?], [*2094*], [#delta(-10)],
      [173], [#name("KLEPRLIK Jakub")], [#age(19)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2093*], [#delta(70)],
      [174], [#name("VLASOV Grigory")], [#age(21)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2091*], [#delta(78)],
      [175], [#name("OLLIVIER Brice")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2090*], [#delta(4)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("KIHO Shinnosuke")], [#age(27)], [#assoc("JPN")], [?], [?], [?], [*2089*], [#delta(-51)],
      [177], [#name("REDJEP Ronald")], [#age(32)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2088*], [#delta(-21)],
      [178], [#name("SAHA Subhajit")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2088*], [#delta(-19)],
      [179], [#name("GORAK Daniel")], [#age(22)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2079*], [#delta(-48)],
      [180], [#name("LASHIN Elsayed")], [#age(25)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2072*], [#delta(-13)],
      [181], [#name("雅罗斯列夫 扎姆登科")], [#age(17)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2070*], [#delta(-73)],
      [182], [#name("CHOU Tung-Yu")], [#age(18)], [#assoc("TPE")], [?], [?], [?], [*2069*], [#delta(-34)],
      [183], [#name("FADEEV Evgeny")], [#age(30)], [#assoc("RUS")], [?], [?], [?], [*2063*], [#delta(-9)],
      [184], [#name("LIVENTSOV Alexey")], [#age(24)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2057*], [#delta(-47)],
      [185], [#name("蒂亚戈 阿波罗尼亚")], [#age(19)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2054*], [#delta(-44)],
      [186], [#name("VAINULA Vallot")], [#age(27)], [#assoc("EST")], [#right], [#shakehand], [#attack], [*2048*], [#delta(-9)],
      [187], [#name("TABACHNIK Pablo")], [#age(28)], [#assoc("ARG")], [#left], [#shakehand], [#attack], [*2045*], [#delta(-7)],
      [188], [#name("ZHUANG David")], [#age(42)], [#assoc("USA")], [?], [?], [?], [*2045*], [#delta(-7)],
      [189], [#name("ROY Soumyadeep")], [#age(21)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2043*], [#delta(34)],
      [190], [#name("MIZUNO Yuya")], [#age(18)], [#assoc("JPN")], [?], [?], [?], [*2043*], [#delta(-7)],
      [191], [#name("SCHLICHTER Jorg")], [#age(22)], [#assoc("GER")], [?], [?], [?], [*2040*], [#delta(-47)],
      [192], [#name("YOKOYAMA Yuichi")], [#age(18)], [#assoc("JPN")], [?], [?], [?], [*2038*], [#delta(58)],
      [193], [#name("OYA Hidetoshi")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2035*], [#delta(-22)],
      [194], [#name("PETROV Sergei")], [#age(35)], [#assoc("EST")], [?], [?], [?], [*2032*], [#delta(-6)],
      [195], [#name("MILICEVIC Srdan")], [#age(29)], [#assoc("BIH")], [?], [?], [?], [*2032*], [#delta(-52)],
      [196], [#name("NAKANO Yusuke")], [#age(21)], [#assoc("JPN")], [?], [?], [?], [*2032*], [#delta(-30)],
      [197], [#name("AXELQVIST Johan")], [#age(20)], [#assoc("SWE")], [?], [?], [?], [*2027*], [#delta(-101)],
      [198], [#name("DURAN Marc")], [#age(19)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2027*], [#delta(29)],
      [199], [#name("PRYSHCHEPA Ievgen")], [#age(20)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2026*], [#delta(176)],
      [200], [#name("PETERSEN Christoffer")], [#age(22)], [#assoc("DEN")], [?], [?], [?], [*2025*], [#delta(20)],
    )
  )
