#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("张怡宁")], [#age(24)], [#assoc("CHN")], [?], [?], [?], [*3006*], [#delta(0)],
      [2], [#name("郭焱")], [#age(23)], [#assoc("CHN")], [?], [?], [?], [*2876*], [#delta(4)],
      [3], [#name("李晓霞")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2838*], [#delta(0)],
      [4], [#name("王楠")], [#age(27)], [#assoc("CHN")], [?], [?], [?], [*2786*], [#delta(-2)],
      [5], [#name("郭跃")], [#age(17)], [#assoc("CHN")], [?], [?], [?], [*2786*], [#delta(-1)],
      [6], [#name("维多利亚 帕芙洛维奇")], [#age(27)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2776*], [#delta(4)],
      [7], [#name("林菱")], [#age(28)], [#assoc("HKG")], [?], [?], [?], [*2723*], [#delta(10)],
      [8], [#name("白杨")], [#age(21)], [#assoc("CHN")], [?], [?], [?], [*2666*], [#delta(0)],
      [9], [#name("牛剑锋")], [#age(24)], [#assoc("CHN")], [?], [?], [?], [*2652*], [#delta(-4)],
      [10], [#name("曹臻")], [#age(18)], [#assoc("CHN")], [?], [?], [?], [*2649*], [#delta(-3)],
      [11], [#name("金香美")], [#age(26)], [#assoc("PRK")], [?], [?], [?], [*2638*], [#delta(5)],
      [12], [#name("福原爱")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2622*], [#delta(6)],
      [13], [#name("李佼")], [#age(32)], [#assoc("NED")], [#left], [#penhold], [#attack], [*2615*], [#delta(37)],
      [14], [#name("桑亚婵")], [#age(24)], [#assoc("HKG")], [?], [?], [?], [*2581*], [#delta(21)],
      [15], [#name("文炫晶")], [#age(21)], [#assoc("KOR")], [?], [?], [?], [*2581*], [#delta(51)],
      [16], [#name("克里斯蒂娜 托特")], [#age(31)], [#assoc("HUN")], [?], [?], [?], [*2567*], [#delta(26)],
      [17], [#name("高军")], [#age(36)], [#assoc("USA")], [?], [?], [?], [*2564*], [#delta(8)],
      [18], [#name("帖雅娜")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2564*], [#delta(-9)],
      [19], [#name("彭陆洋")], [#age(20)], [#assoc("CHN")], [?], [?], [?], [*2559*], [#delta(-8)],
      [20], [#name("张瑞")], [#age(26)], [#assoc("HKG")], [?], [?], [?], [*2522*], [#delta(-7)],
      [21], [#name("范瑛")], [#age(19)], [#assoc("CHN")], [?], [?], [?], [*2509*], [#delta(-9)],
      [22], [#name("孙蓓蓓")], [#age(21)], [#assoc("SGP")], [?], [?], [?], [*2498*], [#delta(-2)],
      [23], [#name("常晨晨")], [#age(19)], [#assoc("CHN")], [?], [?], [?], [*2486*], [#delta(-1)],
      [24], [#name("米哈拉 斯蒂芙")], [#age(27)], [#assoc("ROU")], [?], [?], [?], [*2468*], [#delta(-9)],
      [25], [#name("李佳薇")], [#age(24)], [#assoc("SGP")], [?], [?], [?], [*2463*], [#delta(-6)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("塔玛拉 鲍罗斯")], [#age(28)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2462*], [#delta(-5)],
      [27], [#name("刘佳")], [#age(23)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2453*], [#delta(-4)],
      [28], [#name("KIM Bokrae")], [#age(28)], [#assoc("KOR")], [?], [?], [?], [*2453*], [#delta(-4)],
      [29], [#name("平野早矢香")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2448*], [#delta(0)],
      [30], [#name("FUJINUMA Ai")], [#age(23)], [#assoc("JPN")], [?], [?], [?], [*2444*], [#delta(-4)],
      [31], [#name("乔治娜 波塔")], [#age(20)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2441*], [#delta(24)],
      [32], [#name("WANG Chen")], [#age(31)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2410*], [#delta(-4)],
      [33], [#name("TAN Wenling")], [#age(33)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2404*], [#delta(3)],
      [34], [#name("福冈春菜")], [#age(21)], [#assoc("JPN")], [?], [?], [?], [*2398*], [#delta(-2)],
      [35], [#name("GANINA Svetlana")], [#age(27)], [#assoc("RUS")], [?], [?], [?], [*2397*], [#delta(73)],
      [36], [#name("KIM Mi Yong")], [#age(22)], [#assoc("PRK")], [?], [?], [?], [*2397*], [#delta(11)],
      [37], [#name("LAY Jian Fang")], [#age(32)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2396*], [#delta(-4)],
      [38], [#name("GOBEL Jessica")], [#age(24)], [#assoc("GER")], [?], [?], [?], [*2391*], [#delta(-4)],
      [39], [#name("KOSTROMINA Tatyana")], [#age(32)], [#assoc("BLR")], [?], [?], [?], [*2375*], [#delta(-12)],
      [40], [#name("金景娥")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2370*], [#delta(-26)],
      [41], [#name("柳絮飞")], [#age(24)], [#assoc("HKG")], [?], [?], [?], [*2364*], [#delta(15)],
      [42], [#name("SCHALL Elke")], [#age(32)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2361*], [#delta(29)],
      [43], [#name("ZHANG Xueling")], [#age(22)], [#assoc("SGP")], [?], [?], [?], [*2355*], [#delta(6)],
      [44], [#name("KO Un Gyong")], [#age(22)], [#assoc("PRK")], [?], [?], [?], [*2353*], [#delta(-6)],
      [45], [#name("XU Jie")], [#age(23)], [#assoc("POL")], [?], [?], [?], [*2339*], [#delta(-4)],
      [46], [#name("KONISHI An")], [#age(25)], [#assoc("JPN")], [?], [?], [?], [*2334*], [#delta(-3)],
      [47], [#name("JEON Hyekyung")], [#age(28)], [#assoc("KOR")], [?], [?], [?], [*2334*], [#delta(35)],
      [48], [#name("LANG Kristin")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2332*], [#delta(-4)],
      [49], [#name("刘诗雯")], [#age(14)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2330*], [#delta(-4)],
      [50], [#name("BATORFI Csilla")], [#age(36)], [#assoc("HUN")], [?], [?], [?], [*2327*], [#delta(2)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("KWAK Bangbang")], [#age(25)], [#assoc("KOR")], [?], [?], [?], [*2322*], [#delta(-3)],
      [52], [#name("VACENOVSKA Iveta")], [#age(19)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2321*], [#delta(9)],
      [53], [#name("SCHOPP Jie")], [#age(37)], [#assoc("GER")], [?], [?], [?], [*2316*], [#delta(-2)],
      [54], [#name("ODOROVA Eva")], [#age(26)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2314*], [#delta(66)],
      [55], [#name("SAKAMOTO Saori")], [#age(21)], [#assoc("JPN")], [?], [?], [?], [*2306*], [#delta(-1)],
      [56], [#name("STRUSE Nicole")], [#age(34)], [#assoc("GER")], [?], [?], [?], [*2305*], [#delta(2)],
      [57], [#name("PAVLOVICH Veronika")], [#age(27)], [#assoc("BLR")], [?], [?], [?], [*2298*], [#delta(3)],
      [58], [#name("ZAMFIR Adriana")], [#age(33)], [#assoc("ROU")], [?], [?], [?], [*2298*], [#delta(-1)],
      [59], [#name("藤井宽子")], [#age(23)], [#assoc("JPN")], [?], [?], [?], [*2294*], [#delta(-28)],
      [60], [#name("BADESCU Otilia")], [#age(35)], [#assoc("ROU")], [?], [?], [?], [*2293*], [#delta(-30)],
      [61], [#name("TASEI Mikie")], [#age(25)], [#assoc("JPN")], [?], [?], [?], [*2293*], [#delta(-2)],
      [62], [#name("NEGRISOLI Laura")], [#age(31)], [#assoc("ITA")], [?], [?], [?], [*2293*], [#delta(48)],
      [63], [#name("KIM Jong")], [#age(16)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2289*], [#delta(-10)],
      [64], [#name("STEFANOVA Nikoleta")], [#age(21)], [#assoc("ITA")], [#left], [#shakehand], [#attack], [*2285*], [#delta(6)],
      [65], [#name("MOLNAR Zita")], [#age(29)], [#assoc("HUN")], [?], [?], [?], [*2278*], [#delta(-1)],
      [66], [#name("NEMES Olga")], [#age(37)], [#assoc("ROU")], [?], [?], [?], [*2277*], [#delta(-1)],
      [67], [#name("LI Qiangbing")], [#age(20)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2276*], [#delta(0)],
      [68], [#name("PLAVSIC Gordana")], [#age(29)], [#assoc("SRB")], [?], [?], [?], [*2274*], [#delta(0)],
      [69], [#name("ERDELJI Anamaria")], [#age(20)], [#assoc("SRB")], [#right], [#shakehand], [#defense], [*2273*], [#delta(0)],
      [70], [#name("MIAO Miao")], [#age(24)], [#assoc("AUS")], [?], [?], [?], [*2262*], [#delta(86)],
      [71], [#name("吴雪")], [#age(25)], [#assoc("DOM")], [?], [?], [?], [*2261*], [#delta(33)],
      [72], [#name("陈晴")], [#age(21)], [#assoc("CHN")], [?], [?], [?], [*2252*], [#delta(0)],
      [73], [#name("KIM Junghyun")], [#age(20)], [#assoc("KOR")], [?], [?], [?], [*2251*], [#delta(0)],
      [74], [#name("金泽咲希")], [#age(29)], [#assoc("JPN")], [?], [?], [?], [*2249*], [#delta(26)],
      [75], [#name("MUANGSUK Anisara")], [#age(29)], [#assoc("THA")], [?], [?], [?], [*2248*], [#delta(26)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("ELLO Vivien")], [#age(31)], [#assoc("HUN")], [?], [?], [?], [*2243*], [#delta(-2)],
      [77], [#name("XU Yan")], [#age(20)], [#assoc("SGP")], [?], [?], [?], [*2243*], [#delta(1)],
      [78], [#name("梅村礼")], [#age(29)], [#assoc("JPN")], [?], [?], [?], [*2235*], [#delta(-38)],
      [79], [#name("HIURA Reiko")], [#age(21)], [#assoc("JPN")], [?], [?], [?], [*2227*], [#delta(-3)],
      [80], [#name("STRBIKOVA Renata")], [#age(26)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2227*], [#delta(35)],
      [81], [#name("李恩实")], [#age(29)], [#assoc("KOR")], [?], [?], [?], [*2218*], [#delta(-2)],
      [82], [#name("LEE Hyangmi")], [#age(23)], [#assoc("KOR")], [?], [?], [?], [*2214*], [#delta(95)],
      [83], [#name("DODEAN Daniela")], [#age(17)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2213*], [#delta(-6)],
      [84], [#name("TANIGUCHI Naoko")], [#age(25)], [#assoc("JPN")], [?], [?], [?], [*2209*], [#delta(-3)],
      [85], [#name("LI Nan")], [#age(23)], [#assoc("CHN")], [?], [?], [?], [*2203*], [#delta(-1)],
      [86], [#name("FAZEKAS Maria")], [#age(30)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2200*], [#delta(-49)],
      [87], [#name("RAMIREZ Sara")], [#age(18)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2199*], [#delta(61)],
      [88], [#name("SCHELD Alexandra")], [#age(24)], [#assoc("GER")], [?], [?], [?], [*2190*], [#delta(-3)],
      [89], [#name("LOVAS Petra")], [#age(25)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2187*], [#delta(-1)],
      [90], [#name("HAN Hye Song")], [#age(17)], [#assoc("PRK")], [?], [?], [?], [*2186*], [#delta(90)],
      [91], [#name("JEE Minhyung")], [#age(18)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2185*], [#delta(-2)],
      [92], [#name("MOCROUSOV Elena")], [#age(25)], [#assoc("MDA")], [?], [?], [?], [*2184*], [#delta(-5)],
      [93], [#name("ROBERTSON Laura")], [#age(21)], [#assoc("GER")], [?], [?], [?], [*2183*], [#delta(-3)],
      [94], [#name("POHAR Martina")], [#age(24)], [#assoc("SLO")], [?], [?], [?], [*2181*], [#delta(31)],
      [95], [#name("HASAMA Nozomi")], [#age(19)], [#assoc("JPN")], [?], [?], [?], [*2180*], [#delta(-4)],
      [96], [#name("沈燕飞")], [#age(26)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2179*], [#delta(-4)],
      [97], [#name("JANG Hyon Ae")], [#age(15)], [#assoc("PRK")], [?], [?], [?], [*2178*], [#delta(-4)],
      [98], [#name("BOLLMEIER Nadine")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2173*], [#delta(-2)],
      [99], [#name("SHIOSAKI Yuka")], [#age(24)], [#assoc("JPN")], [?], [?], [?], [*2171*], [#delta(-2)],
      [100], [#name("TAN Paey Fern")], [#age(31)], [#assoc("SGP")], [?], [?], [?], [*2168*], [#delta(-54)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("VACHOVCOVA Alena")], [#age(31)], [#assoc("CZE")], [?], [?], [?], [*2168*], [#delta(-2)],
      [102], [#name("KOMWONG Nanthana")], [#age(25)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2165*], [#delta(-40)],
      [103], [#name("KO Somi")], [#age(21)], [#assoc("KOR")], [?], [?], [?], [*2163*], [#delta(-1)],
      [104], [#name("PAOVIC Sandra")], [#age(22)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2161*], [#delta(-10)],
      [105], [#name("FUJITA Yuki")], [#age(28)], [#assoc("JPN")], [?], [?], [?], [*2157*], [#delta(0)],
      [106], [#name("DEMIENOVA Zuzana")], [#age(30)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2145*], [#delta(1)],
      [107], [#name("KISHIDA Satoko")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2142*], [#delta(2)],
      [108], [#name("PRUSIENE Jolanta")], [#age(40)], [#assoc("LTU")], [?], [?], [?], [*2130*], [#delta(3)],
      [109], [#name("KRAMER Tanja")], [#age(25)], [#assoc("GER")], [?], [?], [?], [*2125*], [#delta(-34)],
      [110], [#name("PAN Chun-Chu")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2120*], [#delta(57)],
      [111], [#name("FILI Christina")], [#age(26)], [#assoc("GRE")], [?], [?], [?], [*2119*], [#delta(39)],
      [112], [#name("ERDELJI Silvija")], [#age(26)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2114*], [#delta(4)],
      [113], [#name("ROHR Gaby")], [#age(20)], [#assoc("GER")], [?], [?], [?], [*2096*], [#delta(8)],
      [114], [#name("KIM Minhee")], [#age(20)], [#assoc("KOR")], [?], [?], [?], [*2094*], [#delta(8)],
      [115], [#name("DOBESOVA Jana")], [#age(37)], [#assoc("CZE")], [?], [?], [?], [*2094*], [#delta(8)],
      [116], [#name("ITO Midori")], [#age(20)], [#assoc("JPN")], [?], [?], [?], [*2093*], [#delta(8)],
      [117], [#name("YU Kwok See")], [#age(19)], [#assoc("HKG")], [?], [?], [?], [*2089*], [#delta(167)],
      [118], [#name("HUANG Yi-Hua")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2089*], [#delta(-20)],
      [119], [#name("朴美英")], [#age(24)], [#assoc("KOR")], [?], [?], [?], [*2081*], [#delta(9)],
      [120], [#name("TERUI Moemi")], [#age(17)], [#assoc("JPN")], [?], [?], [?], [*2080*], [#delta(6)],
      [121], [#name("ETSUZAKI Ayumi")], [#age(24)], [#assoc("JPN")], [?], [?], [?], [*2078*], [#delta(8)],
      [122], [#name("SUEMASU Asami")], [#age(24)], [#assoc("JPN")], [?], [?], [?], [*2075*], [#delta(8)],
      [123], [#name("SHIM Serom")], [#age(18)], [#assoc("KOR")], [?], [?], [?], [*2075*], [#delta(8)],
      [124], [#name("伊莲 埃万坎")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2073*], [#delta(-29)],
      [125], [#name("BAKULA Andrea")], [#age(24)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2070*], [#delta(-12)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("CICHOCKA Magdalena")], [#age(20)], [#assoc("POL")], [?], [?], [?], [*2067*], [#delta(6)],
      [127], [#name("SHIN Soohee")], [#age(24)], [#assoc("KOR")], [?], [?], [?], [*2064*], [#delta(6)],
      [128], [#name("DAS Mouma")], [#age(21)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2060*], [#delta(6)],
      [129], [#name("LIAN Qian")], [#age(22)], [#assoc("DOM")], [?], [?], [?], [*2059*], [#delta(-10)],
      [130], [#name("MEDINA Paula")], [#age(16)], [#assoc("COL")], [#right], [#shakehand], [#attack], [*2058*], [#delta(67)],
      [131], [#name("KIM Kyungha")], [#age(23)], [#assoc("KOR")], [?], [?], [?], [*2057*], [#delta(5)],
      [132], [#name("HANFFOU Sarah")], [#age(19)], [#assoc("CMR")], [#right], [#shakehand], [#attack], [*2055*], [#delta(5)],
      [133], [#name("PALINA Irina")], [#age(35)], [#assoc("RUS")], [?], [?], [?], [*2055*], [#delta(-70)],
      [134], [#name("伊丽莎白 萨玛拉")], [#age(16)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2046*], [#delta(4)],
      [135], [#name("FEHER Gabriela")], [#age(17)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2041*], [#delta(4)],
      [136], [#name("RATHER Jasna")], [#age(35)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2037*], [#delta(-9)],
      [137], [#name("KRAVCHENKO Marina")], [#age(32)], [#assoc("ISR")], [#right], [#shakehand], [#attack], [*2036*], [#delta(-31)],
      [138], [#name("ASHRAF Ayatollah")], [#age(20)], [#assoc("EGY")], [?], [?], [?], [*2034*], [#delta(300)],
      [139], [#name("TIKHOMIROVA Anna")], [#age(21)], [#assoc("RUS")], [?], [?], [?], [*2033*], [#delta(4)],
      [140], [#name("VIJAY Vishaka")], [#age(23)], [#assoc("IND")], [?], [?], [?], [*2031*], [NEW],
      [141], [#name("MIROU Maria")], [#age(28)], [#assoc("GRE")], [?], [?], [?], [*2028*], [#delta(-1)],
      [142], [#name("PIETKIEWICZ Monika")], [#age(22)], [#assoc("POL")], [?], [?], [?], [*2027*], [#delta(3)],
      [143], [#name("CECHOVA Dana")], [#age(22)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2026*], [#delta(4)],
      [144], [#name("LI Bin")], [#age(17)], [#assoc("HUN")], [?], [?], [?], [*2015*], [#delta(0)],
      [145], [#name("LEE I-Chen")], [#age(18)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2006*], [#delta(6)],
      [146], [#name("WANG Yu")], [#age(24)], [#assoc("ITA")], [?], [?], [?], [*2002*], [#delta(7)],
      [147], [#name("PERGEL Szandra")], [#age(17)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2002*], [#delta(2)],
      [148], [#name("EKHOLM Matilda")], [#age(23)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2001*], [#delta(-13)],
      [149], [#name("MOLNAR Cornelia")], [#age(22)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*1999*], [#delta(17)],
      [150], [#name("LATT Katlin")], [#age(20)], [#assoc("EST")], [#right], [#shakehand], [#attack], [*1999*], [#delta(-38)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("GOURIN Anne-Sophie")], [#age(25)], [#assoc("FRA")], [?], [?], [?], [*1998*], [#delta(3)],
      [152], [#name("PASKAUSKIENE Ruta")], [#age(28)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*1996*], [#delta(-69)],
      [153], [#name("PROKHOROVA Yulia")], [#age(18)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*1994*], [#delta(2)],
      [154], [#name("石垣优香")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*1990*], [#delta(20)],
      [155], [#name("TODOROVIC Biljana")], [#age(28)], [#assoc("SLO")], [?], [?], [?], [*1986*], [#delta(-13)],
      [156], [#name("SKOV Mie")], [#age(19)], [#assoc("DEN")], [#right], [#shakehand], [#attack], [*1985*], [#delta(4)],
      [157], [#name("CAHOREAU Nathalie")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*1985*], [#delta(4)],
      [158], [#name("CHOI Moonyoung")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*1984*], [#delta(5)],
      [159], [#name("WIGOW Susanna")], [#age(22)], [#assoc("SWE")], [?], [?], [?], [*1983*], [#delta(5)],
      [160], [#name("BILENKO Tetyana")], [#age(22)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*1978*], [#delta(-57)],
      [161], [#name("KERTAI Rita")], [#age(27)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*1974*], [#delta(7)],
      [162], [#name("BOLSHAKOVA Natalia")], [#age(19)], [#assoc("RUS")], [?], [?], [?], [*1973*], [#delta(-45)],
      [163], [#name("OSHONAIKE Olufunke")], [#age(30)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*1972*], [#delta(-11)],
      [164], [#name("JONSSON Carina")], [#age(26)], [#assoc("SWE")], [?], [?], [?], [*1970*], [#delta(-6)],
      [165], [#name("WAGGERMAYER Elena")], [#age(23)], [#assoc("AUT")], [?], [?], [?], [*1967*], [#delta(4)],
      [166], [#name("MISIKONYTE Lina")], [#age(17)], [#assoc("LTU")], [?], [?], [?], [*1967*], [#delta(293)],
      [167], [#name("DVORAK Galia")], [#age(17)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*1965*], [#delta(-53)],
      [168], [#name("JUNKER Laurence")], [#age(18)], [#assoc("BEL")], [?], [?], [?], [*1963*], [#delta(112)],
      [169], [#name("ROHR Meike")], [#age(20)], [#assoc("GER")], [?], [?], [?], [*1959*], [#delta(2)],
      [170], [#name("VAN ULSEN Sigrid")], [#age(19)], [#assoc("NED")], [?], [?], [?], [*1956*], [#delta(2)],
      [171], [#name("张墨")], [#age(16)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*1956*], [#delta(2)],
      [172], [#name("MEDINA Iizzwa")], [#age(23)], [#assoc("HON")], [#right], [#shakehand], [#attack], [*1954*], [#delta(150)],
      [173], [#name("BANH THUA Tawny")], [#age(31)], [#assoc("USA")], [?], [?], [?], [*1953*], [#delta(2)],
      [174], [#name("李恩姬")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*1952*], [#delta(2)],
      [175], [#name("JUSMA Ceria Nilasari")], [#age(25)], [#assoc("INA")], [#right], [#shakehand], [#attack], [*1950*], [#delta(19)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("YOON Sunae")], [#age(22)], [#assoc("KOR")], [?], [?], [?], [*1950*], [#delta(2)],
      [177], [#name("NECULA Iulia")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*1945*], [#delta(2)],
      [178], [#name("PARTYKA Natalia")], [#age(16)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*1939*], [#delta(3)],
      [179], [#name("BENTSEN Eldijana")], [#age(34)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*1937*], [#delta(3)],
      [180], [#name("JANTA-LIPINSKA Anna")], [#age(20)], [#assoc("POL")], [?], [?], [?], [*1933*], [#delta(3)],
      [181], [#name("IMAFUKU Kumi")], [#age(21)], [#assoc("JPN")], [?], [?], [?], [*1931*], [#delta(3)],
      [182], [#name("SUN Chian-Lan")], [#age(32)], [#assoc("TPE")], [?], [?], [?], [*1925*], [#delta(4)],
      [183], [#name("EGGEL Melanie")], [#age(23)], [#assoc("SUI")], [?], [?], [?], [*1925*], [#delta(347)],
      [184], [#name("ONO Shiho")], [#age(18)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*1924*], [#delta(28)],
      [185], [#name("STEFANSKA Kinga")], [#age(25)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*1923*], [#delta(3)],
      [186], [#name("HEINE Veronika")], [#age(19)], [#assoc("AUT")], [?], [?], [?], [*1923*], [#delta(-1)],
      [187], [#name("ZHU Fang")], [#age(29)], [#assoc("ESP")], [?], [?], [?], [*1915*], [#delta(3)],
      [188], [#name("YAMANASHI Yuri")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*1911*], [#delta(63)],
      [189], [#name("NEVES Ana")], [#age(16)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*1910*], [#delta(-2)],
      [190], [#name("SKABAR Petra")], [#age(19)], [#assoc("SLO")], [?], [?], [?], [*1908*], [#delta(152)],
      [191], [#name("BEH Lee Wei")], [#age(22)], [#assoc("MAS")], [#right], [#shakehand], [#attack], [*1905*], [#delta(-73)],
      [192], [#name("GRUNDISCH Carole")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*1901*], [#delta(3)],
      [193], [#name("PENKAVOVA Katerina")], [#age(18)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*1900*], [#delta(3)],
      [194], [#name("VUGRINEC Suncica")], [#age(18)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*1897*], [#delta(4)],
      [195], [#name("LU Yun-Feng")], [#age(21)], [#assoc("TPE")], [?], [?], [?], [*1896*], [#delta(-54)],
      [196], [#name("SZYMANSKA Antonina")], [#age(22)], [#assoc("POL")], [?], [?], [?], [*1895*], [#delta(3)],
      [197], [#name("OSMAN Bacent")], [#age(28)], [#assoc("EGY")], [?], [?], [?], [*1894*], [#delta(3)],
      [198], [#name("KOTIKHINA Irina")], [#age(25)], [#assoc("RUS")], [?], [?], [?], [*1894*], [#delta(3)],
      [199], [#name("VORONOVA Anastasia")], [#age(20)], [#assoc("RUS")], [?], [?], [?], [*1887*], [#delta(3)],
      [200], [#name("OZER Cecile")], [#age(31)], [#assoc("BEL")], [?], [?], [?], [*1885*], [#delta(4)],
    )
  )
