#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("王励勤")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2994*], [#delta(2)],
      [2], [#name("马琳")], [#age(26)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2946*], [#delta(-1)],
      [3], [#name("王皓")], [#age(23)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2921*], [#delta(1)],
      [4], [#name("蒂姆 波尔")], [#age(25)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2914*], [#delta(-2)],
      [5], [#name("陈玘")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2764*], [#delta(0)],
      [6], [#name("弗拉基米尔 萨姆索诺夫")], [#age(30)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2763*], [#delta(0)],
      [7], [#name("庄智渊")], [#age(25)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2762*], [#delta(11)],
      [8], [#name("侯英超")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2761*], [NEW],
      [9], [#name("吴尚垠")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2741*], [#delta(-2)],
      [10], [#name("詹斯 伦德奎斯特")], [#age(27)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2720*], [#delta(-2)],
      [11], [#name("孔令辉")], [#age(31)], [#assoc("CHN")], [?], [?], [?], [*2711*], [#delta(-2)],
      [12], [#name("李静")], [#age(31)], [#assoc("HKG")], [?], [?], [?], [*2710*], [#delta(-1)],
      [13], [#name("马龙")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2705*], [#delta(14)],
      [14], [#name("斯洛博丹 格鲁伊奇")], [#age(33)], [#assoc("SRB")], [?], [?], [?], [*2697*], [#delta(-1)],
      [15], [#name("柳承敏")], [#age(24)], [#assoc("KOR")], [#right], [#penhold], [#attack], [*2682*], [#delta(-3)],
      [16], [#name("金赫峰")], [#age(21)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2654*], [#delta(1)],
      [17], [#name("郝帅")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2653*], [#delta(-1)],
      [18], [#name("高礼泽")], [#age(30)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2613*], [#delta(7)],
      [19], [#name("SAIVE Philippe")], [#age(35)], [#assoc("BEL")], [?], [?], [?], [*2606*], [#delta(1)],
      [20], [#name("彼得 科贝尔")], [#age(35)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2606*], [#delta(-10)],
      [21], [#name("松下浩二")], [#age(39)], [#assoc("JPN")], [#right], [?], [#defense], [*2598*], [#delta(0)],
      [22], [#name("朱世赫")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2592*], [#delta(-7)],
      [23], [#name("张钰")], [#age(25)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2570*], [#delta(-4)],
      [24], [#name("维尔纳 施拉格")], [#age(34)], [#assoc("AUT")], [?], [?], [?], [*2565*], [#delta(-10)],
      [25], [#name("李廷佑")], [#age(22)], [#assoc("KOR")], [#left], [#penhold], [#attack], [*2562*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("江宏杰")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2547*], [#delta(36)],
      [27], [#name("李哲国")], [#age(21)], [#assoc("PRK")], [?], [?], [?], [*2534*], [#delta(9)],
      [28], [#name("林聚")], [#age(27)], [#assoc("DOM")], [?], [?], [?], [*2526*], [#delta(3)],
      [29], [#name("何志文")], [#age(44)], [#assoc("ESP")], [#left], [#penhold], [#attack], [*2526*], [#delta(-1)],
      [30], [#name("尹在荣")], [#age(23)], [#assoc("KOR")], [?], [?], [?], [*2501*], [#delta(43)],
      [31], [#name("卡林尼科斯 格林卡")], [#age(34)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2493*], [#delta(4)],
      [32], [#name("CHANG Yen-Shu")], [#age(27)], [#assoc("TPE")], [?], [?], [?], [*2491*], [#delta(53)],
      [33], [#name("陈卫星")], [#age(34)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2488*], [#delta(-11)],
      [34], [#name("达米安 埃洛伊")], [#age(37)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2486*], [#delta(4)],
      [35], [#name("阿列克谢 斯米尔诺夫")], [#age(29)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2484*], [#delta(15)],
      [36], [#name("刘松")], [#age(34)], [#assoc("ARG")], [?], [?], [?], [*2481*], [#delta(20)],
      [37], [#name("佐兰 普里莫拉克")], [#age(37)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2480*], [#delta(3)],
      [38], [#name("卢兹扬 布拉斯奇克")], [#age(32)], [#assoc("POL")], [?], [?], [?], [*2480*], [#delta(13)],
      [39], [#name("杨子")], [#age(22)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2480*], [#delta(29)],
      [40], [#name("卢博米尔 皮斯特耶")], [#age(22)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2476*], [#delta(1)],
      [41], [#name("李镇权")], [#age(19)], [#assoc("KOR")], [?], [?], [?], [*2470*], [#delta(-15)],
      [42], [#name("彼得 塞雷达")], [#age(22)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2470*], [#delta(0)],
      [43], [#name("迪米特里 奥恰洛夫")], [#age(18)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2469*], [#delta(33)],
      [44], [#name("李平")], [#age(20)], [#assoc("QAT")], [#right], [#shakehand], [#attack], [*2466*], [#delta(-1)],
      [45], [#name("高宁")], [#age(24)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2463*], [#delta(58)],
      [46], [#name("江天一")], [#age(18)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2462*], [#delta(43)],
      [47], [#name("马文革")], [#age(38)], [#assoc("CHN")], [?], [?], [?], [*2457*], [#delta(-2)],
      [48], [#name("约尔根 佩尔森")], [#age(40)], [#assoc("SWE")], [?], [?], [?], [*2454*], [#delta(-2)],
      [49], [#name("博扬 托基奇")], [#age(25)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2451*], [#delta(50)],
      [50], [#name("金泰勋")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2446*], [#delta(-3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("巴斯蒂安 斯特格")], [#age(25)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2446*], [#delta(-7)],
      [52], [#name("米凯尔 梅兹")], [#age(25)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2443*], [#delta(-18)],
      [53], [#name("克里斯蒂安 苏斯")], [#age(21)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2439*], [#delta(6)],
      [54], [#name("WANG Jianfeng")], [#age(40)], [#assoc("NOR")], [#right], [#penhold], [#attack], [*2437*], [#delta(-6)],
      [55], [#name("FENG Zhe")], [#age(31)], [#assoc("BUL")], [?], [?], [?], [*2431*], [#delta(-31)],
      [56], [#name("MOLDOVAN Istvan")], [#age(33)], [#assoc("NOR")], [?], [?], [?], [*2423*], [#delta(-4)],
      [57], [#name("罗伯特 加尔多斯")], [#age(27)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2421*], [#delta(-20)],
      [58], [#name("埃尔萨伊德 拉辛")], [#age(26)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2420*], [#delta(-3)],
      [59], [#name("谭瑞午")], [#age(23)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2417*], [#delta(27)],
      [60], [#name("塞贡 托里奥拉")], [#age(32)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2416*], [#delta(-3)],
      [61], [#name("杨敏")], [#age(43)], [#assoc("ITA")], [?], [?], [?], [*2412*], [#delta(-1)],
      [62], [#name("叶夫根尼 齐特切蒂宁")], [#age(36)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2412*], [#delta(-1)],
      [63], [#name("让 米歇尔 塞弗")], [#age(37)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2410*], [#delta(0)],
      [64], [#name("李正三")], [#age(22)], [#assoc("KOR")], [?], [?], [?], [*2407*], [#delta(2)],
      [65], [#name("亚历山大 卡拉卡谢维奇")], [#age(31)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2406*], [#delta(2)],
      [66], [#name("FRANZ Peter")], [#age(35)], [#assoc("GER")], [?], [?], [?], [*2399*], [#delta(3)],
      [67], [#name("XU Hui")], [#age(23)], [#assoc("CHN")], [?], [?], [?], [*2397*], [#delta(3)],
      [68], [#name("MAZUNOV Dmitry")], [#age(35)], [#assoc("RUS")], [?], [?], [?], [*2394*], [#delta(4)],
      [69], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(26)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2393*], [#delta(-15)],
      [70], [#name("赵彦来")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2390*], [#delta(-38)],
      [71], [#name("蒂亚戈 阿波罗尼亚")], [#age(20)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2389*], [#delta(3)],
      [72], [#name("马克西姆 什梅廖夫")], [#age(35)], [#assoc("RUS")], [?], [?], [?], [*2386*], [#delta(3)],
      [73], [#name("水谷隼")], [#age(17)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2384*], [#delta(-9)],
      [74], [#name("松平健太")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2382*], [#delta(46)],
      [75], [#name("林载贤")], [#age(21)], [#assoc("KOR")], [?], [?], [?], [*2377*], [#delta(-36)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("LIU Zhongze")], [#age(18)], [#assoc("SGP")], [?], [?], [?], [*2371*], [#delta(417)],
      [77], [#name("约瑟夫 普拉希")], [#age(35)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2370*], [#delta(2)],
      [78], [#name("费奥多尔 库兹明")], [#age(23)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2366*], [#delta(-49)],
      [79], [#name("阿德里安 克里桑")], [#age(26)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2360*], [#delta(25)],
      [80], [#name("唐鹏")], [#age(25)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2357*], [#delta(-22)],
      [81], [#name("威廉 亨泽尔")], [#age(24)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2357*], [#delta(0)],
      [82], [#name("KUSINSKI Marcin")], [#age(35)], [#assoc("POL")], [?], [?], [?], [*2351*], [#delta(1)],
      [83], [#name("蒋澎龙")], [#age(30)], [#assoc("TPE")], [?], [?], [?], [*2343*], [#delta(15)],
      [84], [#name("亚历山大 迪杜赫")], [#age(24)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2342*], [#delta(0)],
      [85], [#name("罗伯特 斯文松")], [#age(23)], [#assoc("SWE")], [?], [?], [?], [*2338*], [#delta(16)],
      [86], [#name("LEI Zhenhua")], [#age(20)], [#assoc("CHN")], [?], [?], [?], [*2331*], [#delta(2)],
      [87], [#name("高木和卓")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2326*], [#delta(32)],
      [88], [#name("费伦茨 帕西")], [#age(32)], [#assoc("HUN")], [?], [?], [?], [*2324*], [#delta(2)],
      [89], [#name("托本 沃西克")], [#age(33)], [#assoc("GER")], [?], [?], [?], [*2324*], [#delta(13)],
      [90], [#name("马雷克 克拉塞克")], [#age(31)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2324*], [#delta(1)],
      [91], [#name("马丁 蒙拉德")], [#age(29)], [#assoc("DEN")], [?], [?], [?], [*2321*], [#delta(-20)],
      [92], [#name("VYBORNY Richard")], [#age(35)], [#assoc("CZE")], [?], [?], [?], [*2320*], [#delta(2)],
      [93], [#name("特林科 基恩")], [#age(35)], [#assoc("NED")], [#left], [#shakehand], [#attack], [*2320*], [#delta(62)],
      [94], [#name("崔贤珍")], [#age(27)], [#assoc("KOR")], [?], [?], [?], [*2320*], [#delta(-1)],
      [95], [#name("MONDELLO Massimiliano")], [#age(31)], [#assoc("ITA")], [?], [?], [?], [*2317*], [#delta(0)],
      [96], [#name("佐尔坦 费杰科内斯")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2315*], [#delta(32)],
      [97], [#name("小山雨果")], [#age(37)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2315*], [#delta(-1)],
      [98], [#name("岸川圣也")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2315*], [#delta(-33)],
      [99], [#name("ZHANG Wilson")], [#age(27)], [#assoc("CAN")], [?], [?], [?], [*2313*], [#delta(-21)],
      [100], [#name("RUMGAY Gavin")], [#age(22)], [#assoc("SCO")], [#right], [#shakehand], [#attack], [*2313*], [#delta(-3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("丹尼尔 茨维克尔")], [#age(22)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2309*], [#delta(-71)],
      [102], [#name("若昂 蒙泰罗")], [#age(23)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2299*], [#delta(-69)],
      [103], [#name("韩阳")], [#age(28)], [#assoc("JPN")], [?], [?], [?], [*2298*], [NEW],
      [104], [#name("拉尔斯 希尔舍")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2297*], [#delta(1)],
      [105], [#name("VARGA Zoltan")], [#age(32)], [#assoc("HUN")], [?], [?], [?], [*2293*], [#delta(1)],
      [106], [#name("康斯坦丁 乔蒂")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2293*], [#delta(1)],
      [107], [#name("帕特里克 奇拉")], [#age(37)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2292*], [#delta(-27)],
      [108], [#name("马丁 奥列尼克")], [#age(34)], [#assoc("CZE")], [?], [?], [?], [*2291*], [#delta(0)],
      [109], [#name("保罗 德林克霍尔")], [#age(16)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2287*], [#delta(29)],
      [110], [#name("HAKANSSON Fredrik")], [#age(31)], [#assoc("SWE")], [?], [?], [?], [*2286*], [#delta(0)],
      [111], [#name("ANDRIANOV Sergei")], [#age(30)], [#assoc("RUS")], [?], [?], [?], [*2282*], [#delta(1)],
      [112], [#name("帕特里克 鲍姆")], [#age(19)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2280*], [#delta(33)],
      [113], [#name("ROSSKOPF Jorg")], [#age(37)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2280*], [#delta(-2)],
      [114], [#name("帕尔 格雷尔")], [#age(24)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2278*], [#delta(15)],
      [115], [#name("托马什 帕维尔卡")], [#age(26)], [#assoc("CZE")], [?], [?], [?], [*2273*], [#delta(-2)],
      [116], [#name("MILICEVIC Srdan")], [#age(30)], [#assoc("BIH")], [?], [?], [?], [*2272*], [#delta(-1)],
      [117], [#name("吉田海伟")], [#age(25)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2272*], [#delta(-64)],
      [118], [#name("松本和雄")], [#age(21)], [#assoc("BRA")], [#left], [#penhold], [#attack], [*2271*], [#delta(-2)],
      [119], [#name("亚诺什 雅各布")], [#age(20)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2268*], [#delta(80)],
      [120], [#name("克里斯托夫 勒古")], [#age(33)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2264*], [#delta(-71)],
      [121], [#name("AN Chol Yong")], [#age(21)], [#assoc("PRK")], [?], [?], [?], [*2263*], [#delta(-3)],
      [122], [#name("TAKAKIWA Kenichi")], [#age(22)], [#assoc("JPN")], [?], [?], [?], [*2261*], [#delta(-13)],
      [123], [#name("卡洛斯 马查多")], [#age(26)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2261*], [#delta(-36)],
      [124], [#name("沙拉特 阿昌塔")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2260*], [#delta(-42)],
      [125], [#name("坂本龙介")], [#age(22)], [#assoc("JPN")], [?], [?], [?], [*2258*], [#delta(-8)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("罗科 托西奇")], [#age(27)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2258*], [#delta(-12)],
      [127], [#name("王增羿")], [#age(23)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2253*], [#delta(9)],
      [128], [#name("KATKOV Ivan")], [#age(22)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2253*], [#delta(-7)],
      [129], [#name("金正勋")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2251*], [#delta(-37)],
      [130], [#name("KLEPRLIK Jakub")], [#age(20)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2250*], [#delta(-8)],
      [131], [#name("ABRAMOV Isaak")], [#age(35)], [#assoc("ISR")], [#right], [#shakehand], [#attack], [*2249*], [#delta(-8)],
      [132], [#name("HU Jiashun")], [#age(23)], [#assoc("SUI")], [?], [?], [?], [*2248*], [#delta(-8)],
      [133], [#name("安德烈 菲利蒙")], [#age(29)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2241*], [#delta(-6)],
      [134], [#name("WIJERS Barry")], [#age(24)], [#assoc("NED")], [?], [?], [?], [*2229*], [#delta(-1)],
      [135], [#name("HEISTER Danny")], [#age(35)], [#assoc("NED")], [#left], [#shakehand], [#attack], [*2224*], [#delta(0)],
      [136], [#name("米哈伊 博博奇卡")], [#age(20)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2220*], [#delta(1)],
      [137], [#name("托马斯 凯纳特")], [#age(29)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2216*], [#delta(-3)],
      [138], [#name("雅库布 科索夫斯基")], [#age(24)], [#assoc("POL")], [?], [?], [?], [*2215*], [#delta(39)],
      [139], [#name("GERADA Simon")], [#age(25)], [#assoc("AUS")], [?], [?], [?], [*2211*], [#delta(0)],
      [140], [#name("MIZUNO Yuya")], [#age(19)], [#assoc("JPN")], [?], [?], [?], [*2211*], [#delta(0)],
      [141], [#name("PHUNG Armand")], [#age(30)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2209*], [#delta(0)],
      [142], [#name("丹尼尔 古拉克")], [#age(23)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2209*], [#delta(0)],
      [143], [#name("张成万")], [#age(21)], [#assoc("PRK")], [?], [?], [?], [*2208*], [#delta(0)],
      [144], [#name("马蒂斯 布尔吉斯")], [#age(17)], [#assoc("LAT")], [#right], [#shakehand], [#attack], [*2205*], [#delta(0)],
      [145], [#name("梁柱恩")], [#age(27)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2204*], [#delta(65)],
      [146], [#name("TOKIYOSHI Yuichi")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2198*], [#delta(0)],
      [147], [#name("PETRUKHIN Evgeny")], [#age(21)], [#assoc("RUS")], [?], [?], [?], [*2196*], [#delta(0)],
      [148], [#name("塞巴斯蒂安 若韦尔")], [#age(31)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2196*], [#delta(113)],
      [149], [#name("GRIGOREV Artur")], [#age(20)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2192*], [#delta(-1)],
      [150], [#name("艾哈迈德 萨利赫")], [#age(27)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2188*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("马克 杜兰")], [#age(20)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2187*], [#delta(8)],
      [152], [#name("KUBOTA Ryuzo")], [#age(21)], [#assoc("JPN")], [?], [?], [?], [*2185*], [#delta(-1)],
      [153], [#name("STENBERG Mattias")], [#age(30)], [#assoc("SWE")], [?], [?], [?], [*2184*], [#delta(-1)],
      [154], [#name("VOZICKY Bohumil")], [#age(29)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2182*], [#delta(-1)],
      [155], [#name("基里尔 斯卡奇科夫")], [#age(19)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2177*], [#delta(12)],
      [156], [#name("萨什 拉桑")], [#age(35)], [#assoc("SLO")], [#right], [#shakehand], [#defense], [*2177*], [#delta(0)],
      [157], [#name("阿尔弗雷多 卡内罗斯")], [#age(28)], [#assoc("ESP")], [?], [?], [?], [*2176*], [#delta(4)],
      [158], [#name("盖尔 埃兰森")], [#age(30)], [#assoc("NOR")], [?], [?], [?], [*2175*], [#delta(-1)],
      [159], [#name("埃里克 伊拉什")], [#age(26)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2172*], [#delta(-1)],
      [160], [#name("SANGUANSIN Phakpoom")], [#age(23)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2172*], [#delta(40)],
      [161], [#name("MUJICA Henry")], [#age(28)], [#assoc("VEN")], [?], [?], [?], [*2169*], [#delta(-1)],
      [162], [#name("吴志祺")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2165*], [#delta(-62)],
      [163], [#name("BERTIN Christophe")], [#age(21)], [#assoc("FRA")], [?], [?], [?], [*2161*], [#delta(0)],
      [164], [#name("蒂亚戈 蒙泰罗")], [#age(25)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2160*], [#delta(2)],
      [165], [#name("下山隆敬")], [#age(21)], [#assoc("JPN")], [?], [?], [?], [*2157*], [#delta(32)],
      [166], [#name("塩野真人")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2155*], [#delta(2)],
      [167], [#name("SUGRUE Jason")], [#age(27)], [#assoc("IRL")], [?], [?], [?], [*2150*], [#delta(2)],
      [168], [#name("FADEEV Evgeny")], [#age(31)], [#assoc("RUS")], [?], [?], [?], [*2150*], [#delta(2)],
      [169], [#name("SANGUANSIN Phuchong")], [#age(26)], [#assoc("THA")], [?], [?], [?], [*2150*], [#delta(-19)],
      [170], [#name("马雷克 齐哈克")], [#age(32)], [#assoc("CZE")], [?], [?], [?], [*2147*], [#delta(1)],
      [171], [#name("马克斯 弗雷塔斯")], [#age(18)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2144*], [#delta(1)],
      [172], [#name("IBRAHIM Muhd Shakirin")], [#age(21)], [#assoc("MAS")], [?], [?], [?], [*2143*], [#delta(1)],
      [173], [#name("古斯塔沃 坪井")], [#age(21)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2138*], [#delta(1)],
      [174], [#name("黄圣盛")], [#age(19)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2137*], [#delta(-42)],
      [175], [#name("TAVUKCUOGLU Irfan")], [#age(27)], [#assoc("TUR")], [?], [?], [?], [*2136*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("AL-QERSHI Wael")], [#age(22)], [#assoc("YEM")], [?], [?], [?], [*2133*], [#delta(2)],
      [177], [#name("MANSSON Magnus")], [#age(30)], [#assoc("SWE")], [?], [?], [?], [*2133*], [#delta(2)],
      [178], [#name("BARDON Michal")], [#age(28)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2132*], [#delta(2)],
      [179], [#name("古德蒙迪 斯蒂芬森")], [#age(24)], [#assoc("ISL")], [?], [?], [?], [*2132*], [#delta(2)],
      [180], [#name("约翰 阿克塞尔奎斯特")], [#age(21)], [#assoc("SWE")], [?], [?], [?], [*2129*], [#delta(-16)],
      [181], [#name("彼得 法泽卡斯")], [#age(25)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2129*], [#delta(1)],
      [182], [#name("艾曼纽 莱贝松")], [#age(18)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2128*], [#delta(42)],
      [183], [#name("TSIOKAS Ntaniel")], [#age(35)], [#assoc("GRE")], [?], [?], [?], [*2127*], [#delta(0)],
      [184], [#name("OMAR Rashid")], [#age(18)], [#assoc("UAE")], [?], [?], [?], [*2119*], [#delta(1)],
      [185], [#name("安德烈 加奇尼")], [#age(20)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2118*], [#delta(1)],
      [186], [#name("KOSTAL Radek")], [#age(32)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2118*], [#delta(1)],
      [187], [#name("FENG Xiaoquan")], [#age(19)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2115*], [#delta(1)],
      [188], [#name("CAI Xiaoli")], [#age(27)], [#assoc("SGP")], [?], [?], [?], [*2113*], [#delta(-62)],
      [189], [#name("GAVRILOV Denis")], [#age(29)], [#assoc("RUS")], [?], [?], [?], [*2110*], [#delta(1)],
      [190], [#name("NOROOZI Afshin")], [#age(21)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2108*], [#delta(2)],
      [191], [#name("DEMETER Lehel")], [#age(28)], [#assoc("HUN")], [?], [?], [?], [*2107*], [#delta(2)],
      [192], [#name("芬 图格威尔")], [#age(30)], [#assoc("DEN")], [?], [?], [?], [*2107*], [#delta(146)],
      [193], [#name("TURGAMBAEV Ruslan")], [#age(27)], [#assoc("KAZ")], [?], [?], [?], [*2106*], [#delta(1)],
      [194], [#name("FETH Stefan")], [#age(26)], [#assoc("GER")], [?], [?], [?], [*2106*], [#delta(1)],
      [195], [#name("FILIMON Lucian")], [#age(27)], [#assoc("ROU")], [?], [?], [?], [*2105*], [#delta(1)],
      [196], [#name("MICHELY Gilles")], [#age(18)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2102*], [#delta(2)],
      [197], [#name("KIHO Shinnosuke")], [#age(28)], [#assoc("JPN")], [?], [?], [?], [*2098*], [#delta(-43)],
      [198], [#name("CABESTANY Cedrik")], [#age(27)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2098*], [#delta(-67)],
      [199], [#name("卢文 菲鲁斯")], [#age(18)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2096*], [#delta(2)],
      [200], [#name("LENGEROV Kostadin")], [#age(30)], [#assoc("AUT")], [?], [?], [?], [*2096*], [#delta(2)],
    )
  )
