#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("马龙")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3139*], [#delta(0)],
      [2], [#name("许昕")], [#age(25)], [#assoc("CHN")], [#left], [#penhold], [#attack], [*3010*], [#delta(0)],
      [3], [#name("樊振东")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2987*], [#delta(0)],
      [4], [#name("张继科")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2982*], [#delta(0)],
      [5], [#name("蒂姆 波尔")], [#age(34)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2942*], [#delta(0)],
      [6], [#name("迪米特里 奥恰洛夫")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2874*], [#delta(2)],
      [7], [#name("闫安")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2860*], [#delta(4)],
      [8], [#name("水谷隼")], [#age(26)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2853*], [#delta(-1)],
      [9], [#name("方博")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2846*], [#delta(-3)],
      [10], [#name("马克斯 弗雷塔斯")], [#age(27)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2829*], [#delta(0)],
      [11], [#name("弗拉基米尔 萨姆索诺夫")], [#age(39)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2776*], [#delta(1)],
      [12], [#name("塩野真人")], [#age(29)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2766*], [#delta(23)],
      [13], [#name("周雨")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2754*], [#delta(0)],
      [14], [#name("帕特里克 鲍姆")], [#age(28)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2745*], [#delta(0)],
      [15], [#name("吉村真晴")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2729*], [#delta(18)],
      [16], [#name("梁靖崑")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2727*], [#delta(4)],
      [17], [#name("卢文 菲鲁斯")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2727*], [#delta(53)],
      [18], [#name("朱世赫")], [#age(35)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2720*], [#delta(-9)],
      [19], [#name("金东贤")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2703*], [#delta(29)],
      [20], [#name("黄镇廷")], [#age(24)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2703*], [#delta(36)],
      [21], [#name("丹羽孝希")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2700*], [#delta(-6)],
      [22], [#name("松平健太")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2699*], [#delta(12)],
      [23], [#name("庄智渊")], [#age(34)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2696*], [#delta(-7)],
      [24], [#name("李廷佑")], [#age(31)], [#assoc("KOR")], [#left], [#penhold], [#attack], [*2696*], [#delta(-5)],
      [25], [#name("沙拉特 阿昌塔")], [#age(33)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2688*], [#delta(109)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("郑荣植")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2686*], [#delta(0)],
      [27], [#name("李平")], [#age(29)], [#assoc("QAT")], [#right], [#shakehand], [#attack], [*2680*], [#delta(2)],
      [28], [#name("吉田海伟")], [#age(34)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2678*], [#delta(15)],
      [29], [#name("吉田雅己")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2668*], [#delta(8)],
      [30], [#name("若昂 蒙泰罗")], [#age(32)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2667*], [#delta(-6)],
      [31], [#name("町飞鸟")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2660*], [#delta(-13)],
      [32], [#name("李尚洙")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2658*], [#delta(-4)],
      [33], [#name("唐鹏")], [#age(34)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2657*], [#delta(-8)],
      [34], [#name("巴斯蒂安 斯特格")], [#age(34)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2654*], [#delta(72)],
      [35], [#name("博扬 托基奇")], [#age(34)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2653*], [#delta(-5)],
      [36], [#name("金珉鉐")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2651*], [#delta(54)],
      [37], [#name("西蒙 高兹")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2650*], [#delta(-6)],
      [38], [#name("周恺")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2649*], [#delta(-6)],
      [39], [#name("斯蒂芬 门格尔")], [#age(27)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2646*], [#delta(49)],
      [40], [#name("蒂亚戈 阿波罗尼亚")], [#age(29)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2643*], [#delta(-17)],
      [41], [#name("森园政崇")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2637*], [#delta(36)],
      [42], [#name("阿德里安 马特内")], [#age(28)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2635*], [#delta(-2)],
      [43], [#name("汪洋")], [#age(21)], [#assoc("SVK")], [#right], [#shakehand], [#defense], [*2630*], [#delta(20)],
      [44], [#name("LIU Yi")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2630*], [#delta(-6)],
      [45], [#name("LYU Xiang")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2629*], [#delta(-6)],
      [46], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(35)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2626*], [#delta(-25)],
      [47], [#name("奥马尔 阿萨尔")], [#age(24)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2623*], [#delta(3)],
      [48], [#name("克里斯坦 卡尔松")], [#age(24)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2622*], [#delta(6)],
      [49], [#name("上田仁")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2620*], [#delta(0)],
      [50], [#name("朴申赫")], [#age(22)], [#assoc("PRK")], [#left], [#penhold], [#attack], [*2618*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("丁祥恩")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2617*], [#delta(1)],
      [52], [#name("里卡多 瓦尔特")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2617*], [#delta(-7)],
      [53], [#name("米哈伊 博博奇卡")], [#age(29)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2616*], [#delta(0)],
      [54], [#name("罗伯特 加尔多斯")], [#age(36)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2616*], [#delta(-32)],
      [55], [#name("帕特里克 弗朗西斯卡")], [#age(23)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2608*], [#delta(31)],
      [56], [#name("大岛祐哉")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2601*], [#delta(-12)],
      [57], [#name("高宁")], [#age(33)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2601*], [#delta(-40)],
      [58], [#name("陈建安")], [#age(24)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2600*], [#delta(2)],
      [59], [#name("利亚姆 皮切福德")], [#age(22)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2595*], [#delta(-2)],
      [60], [#name("基里尔 斯卡奇科夫")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2595*], [#delta(4)],
      [61], [#name("何志文")], [#age(53)], [#assoc("ESP")], [#left], [#penhold], [#attack], [*2595*], [#delta(-3)],
      [62], [#name("金民赫")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2595*], [#delta(17)],
      [63], [#name("丹尼尔 古拉克")], [#age(32)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2593*], [#delta(-2)],
      [64], [#name("陈卫星")], [#age(43)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2592*], [#delta(-2)],
      [65], [#name("安东 卡尔伯格")], [#age(18)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2591*], [#delta(16)],
      [66], [#name("斯特凡 菲格尔")], [#age(27)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2589*], [#delta(-30)],
      [67], [#name("乔恩 佩尔森")], [#age(29)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2585*], [#delta(16)],
      [68], [#name("村松雄斗")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2583*], [#delta(-27)],
      [69], [#name("WU Zhikang")], [#age(21)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2583*], [#delta(-4)],
      [70], [#name("林高远")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2580*], [#delta(-4)],
      [71], [#name("马蒂亚斯 法尔克")], [#age(24)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2579*], [#delta(75)],
      [72], [#name("大矢英俊")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2578*], [#delta(-4)],
      [73], [#name("丹尼尔 哈贝松")], [#age(29)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2576*], [#delta(-46)],
      [74], [#name("黄圣盛")], [#age(28)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2574*], [#delta(19)],
      [75], [#name("尚坤")], [#age(25)], [#assoc("CHN")], [?], [?], [?], [*2570*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("达米安 埃洛伊")], [#age(46)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2567*], [#delta(-7)],
      [77], [#name("安德烈 加奇尼")], [#age(29)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2564*], [#delta(-22)],
      [78], [#name("李虎")], [#age(27)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2559*], [#delta(-5)],
      [79], [#name("古斯塔沃 坪井")], [#age(30)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2558*], [#delta(16)],
      [80], [#name("亚历山大 希巴耶夫")], [#age(25)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2557*], [#delta(130)],
      [81], [#name("夸德里 阿鲁纳")], [#age(27)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2557*], [#delta(-39)],
      [82], [#name("保罗 德林克霍尔")], [#age(25)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2556*], [#delta(9)],
      [83], [#name("寇磊")], [#age(28)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2553*], [#delta(-8)],
      [84], [#name("徐贤德")], [#age(24)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2552*], [#delta(-6)],
      [85], [#name("薛飞")], [#age(16)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2552*], [#delta(-5)],
      [86], [#name("帕尔 格雷尔")], [#age(33)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2551*], [#delta(-39)],
      [87], [#name("德米特里 普罗科普科夫")], [#age(35)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2550*], [#delta(91)],
      [88], [#name("张禹珍")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2549*], [#delta(-6)],
      [89], [#name("林钟勋")], [#age(18)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2548*], [#delta(55)],
      [90], [#name("姜东秀")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2545*], [#delta(-5)],
      [91], [#name("何钧杰")], [#age(18)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2543*], [#delta(-24)],
      [92], [#name("亚诺什 雅各布")], [#age(29)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2541*], [#delta(-5)],
      [93], [#name("赵胜敏")], [#age(17)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2535*], [#delta(-4)],
      [94], [#name("格里戈里 弗拉索夫")], [#age(31)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2532*], [#delta(-23)],
      [95], [#name("阿列克谢 利文佐夫")], [#age(34)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2530*], [#delta(-19)],
      [96], [#name("雅库布 科索夫斯基")], [#age(33)], [#assoc("POL")], [?], [?], [?], [*2528*], [#delta(0)],
      [97], [#name("松平贤二")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2528*], [#delta(-5)],
      [98], [#name("诺沙迪 阿拉米扬")], [#age(24)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2527*], [#delta(21)],
      [99], [#name("王增羿")], [#age(32)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2525*], [#delta(-2)],
      [100], [#name("李良夫")], [#age(24)], [#assoc("TUR")], [#left], [#shakehand], [#attack], [*2525*], [#delta(2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("江宏杰")], [#age(26)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2524*], [#delta(29)],
      [102], [#name("特里斯坦 弗洛雷")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2524*], [#delta(-4)],
      [103], [#name("江天一")], [#age(27)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2522*], [#delta(-44)],
      [104], [#name("刘丁硕")], [#age(17)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2522*], [#delta(-5)],
      [105], [#name("托马斯 科涅茨尼")], [#age(30)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2518*], [#delta(35)],
      [106], [#name("马蒂斯 布尔吉斯")], [#age(26)], [#assoc("LAT")], [#right], [#shakehand], [#attack], [*2516*], [#delta(-3)],
      [107], [#name("WEI Shihao")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2515*], [#delta(-3)],
      [108], [#name("阿列克谢 斯米尔诺夫")], [#age(38)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2515*], [#delta(29)],
      [109], [#name("金赫峰")], [#age(30)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2507*], [#delta(-1)],
      [110], [#name("三部航平")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2507*], [#delta(117)],
      [111], [#name("丹尼尔 里德")], [#age(26)], [#assoc("ENG")], [?], [?], [?], [*2506*], [#delta(-2)],
      [112], [#name("苏姆亚吉特 格霍什")], [#age(22)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2503*], [#delta(8)],
      [113], [#name("阿卜杜勒-卡德尔 萨利富")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2502*], [#delta(18)],
      [114], [#name("王臻")], [#age(30)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2501*], [#delta(15)],
      [115], [#name("酒井明日翔")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2499*], [#delta(32)],
      [116], [#name("CHENG Jingqi")], [#age(21)], [#assoc("CHN")], [?], [?], [?], [*2499*], [#delta(-3)],
      [117], [#name("亚当 帕塔纽什")], [#age(37)], [#assoc("HUN")], [#right], [#shakehand], [#defense], [*2499*], [#delta(40)],
      [118], [#name("雨果 卡尔德拉诺")], [#age(19)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2499*], [#delta(36)],
      [119], [#name("ZHU Cheng")], [#age(18)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2498*], [#delta(-3)],
      [120], [#name("斯特凡 乌瓦切")], [#age(22)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2498*], [#delta(-20)],
      [121], [#name("詹斯 伦德奎斯特")], [#age(36)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2498*], [#delta(-49)],
      [122], [#name("贝内迪克特 杜达")], [#age(21)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2497*], [#delta(92)],
      [123], [#name("YANG Tzu-Yi")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2497*], [#delta(-6)],
      [124], [#name("亚历山大 卡拉卡谢维奇")], [#age(40)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2497*], [#delta(-23)],
      [125], [#name("卡林尼科斯 格林卡")], [#age(43)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2496*], [#delta(-3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("阿德里安 克里桑")], [#age(35)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2496*], [#delta(-42)],
      [127], [#name("尼亚戈尔 斯托亚诺夫")], [#age(28)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2492*], [#delta(16)],
      [128], [#name("瓦西里 拉凯耶夫")], [#age(31)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2488*], [#delta(-3)],
      [129], [#name("罗科 托西奇")], [#age(36)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2488*], [#delta(-3)],
      [130], [#name("神巧也")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2487*], [#delta(-3)],
      [131], [#name("雅库布 迪亚斯")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2485*], [#delta(18)],
      [132], [#name("埃尔萨伊德 拉辛")], [#age(35)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2484*], [#delta(-9)],
      [133], [#name("张一博")], [#age(30)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2482*], [#delta(-39)],
      [134], [#name("TAO Wenzhang")], [#age(21)], [#assoc("USA")], [#right], [#penhold], [#attack], [*2481*], [#delta(-2)],
      [135], [#name("ANDERSSON Harald")], [#age(24)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2478*], [#delta(106)],
      [136], [#name("叶夫根尼 齐特切蒂宁")], [#age(45)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2476*], [#delta(0)],
      [137], [#name("让 米歇尔 塞弗")], [#age(46)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2475*], [#delta(-9)],
      [138], [#name("弗洛朗 兰比特")], [#age(20)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2474*], [#delta(110)],
      [139], [#name("贝内德克 奥拉")], [#age(24)], [#assoc("FIN")], [#right], [#shakehand], [#attack], [*2472*], [#delta(-1)],
      [140], [#name("佐尔特 佩托")], [#age(28)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2471*], [#delta(1)],
      [141], [#name("艾曼纽 莱贝松")], [#age(27)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2471*], [#delta(-27)],
      [142], [#name("赵彦来")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2471*], [#delta(-32)],
      [143], [#name("克里斯托夫 勒古")], [#age(42)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2468*], [#delta(41)],
      [144], [#name("BROSSIER Benjamin")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2467*], [#delta(-98)],
      [145], [#name("高木和卓")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2465*], [#delta(-30)],
      [146], [#name("塞缪尔 沃克")], [#age(20)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2464*], [#delta(-13)],
      [147], [#name("佐兰 普里莫拉克")], [#age(46)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2461*], [#delta(1)],
      [148], [#name("朴康贤")], [#age(19)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2460*], [#delta(126)],
      [149], [#name("LORENTZ Romain")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2459*], [#delta(24)],
      [150], [#name("塞德里克 纽廷克")], [#age(22)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2459*], [#delta(-43)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("CHOE Il")], [#age(22)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2459*], [#delta(-1)],
      [152], [#name("迈赫迪 布洛斯")], [#age(20)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2458*], [#delta(35)],
      [153], [#name("达尼埃尔 科希鲍")], [#age(24)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2455*], [#delta(-35)],
      [154], [#name("平野友树")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2450*], [#delta(2)],
      [155], [#name("奥维迪乌 伊奥内斯库")], [#age(26)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2448*], [#delta(34)],
      [156], [#name("安德烈 菲利蒙")], [#age(38)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2447*], [#delta(36)],
      [157], [#name("艾哈迈德 萨利赫")], [#age(36)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2447*], [#delta(14)],
      [158], [#name("吴尚垠")], [#age(38)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2446*], [#delta(1)],
      [159], [#name("乔纳森 格罗斯")], [#age(23)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2446*], [#delta(27)],
      [160], [#name("廖振珽")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2446*], [#delta(0)],
      [161], [#name("谭瑞午")], [#age(32)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2443*], [#delta(-49)],
      [162], [#name("WANG Zhixu")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2442*], [#delta(109)],
      [163], [#name("若昂 热拉尔多")], [#age(20)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2441*], [#delta(-28)],
      [164], [#name("三内贤太郎")], [#age(26)], [#assoc("JPN")], [?], [?], [?], [*2440*], [#delta(0)],
      [165], [#name("朴灿赫")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2439*], [#delta(1)],
      [166], [#name("米凯尔 梅兹")], [#age(34)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2439*], [#delta(2)],
      [167], [#name("恩佐 昂格勒")], [#age(20)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2439*], [#delta(35)],
      [168], [#name("RYUZAKI Tonin")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-29)],
      [169], [#name("LEE Chia-Sheng")], [#age(20)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2438*], [#delta(66)],
      [170], [#name("马尔科 耶夫托维奇")], [#age(28)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2436*], [#delta(0)],
      [171], [#name("翟羽佳")], [#age(20)], [#assoc("DEN")], [#right], [#shakehand], [#attack], [*2435*], [#delta(-26)],
      [172], [#name("王楚钦")], [#age(15)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2433*], [#delta(0)],
      [173], [#name("帕维尔 费尔蒂科夫斯基")], [#age(25)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2432*], [#delta(-49)],
      [174], [#name("帕维尔 普拉托诺夫")], [#age(32)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-53)],
      [175], [#name("亚历山大 迪杜赫")], [#age(33)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("尼马 阿拉米安")], [#age(23)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2430*], [#delta(-1)],
      [177], [#name("TORNKVIST Andreas")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2430*], [#delta(-1)],
      [178], [#name("NOROOZI Afshin")], [#age(30)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2429*], [#delta(-1)],
      [179], [#name("ARVIDSSON Simon")], [#age(25)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2428*], [#delta(0)],
      [180], [#name("卡洛斯 马查多")], [#age(35)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2427*], [#delta(-38)],
      [181], [#name("拉尔斯 希尔舍")], [#age(36)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2426*], [#delta(-19)],
      [182], [#name("AKERSTROM Fabian")], [#age(27)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2425*], [#delta(16)],
      [183], [#name("岸川圣也")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2424*], [#delta(0)],
      [184], [#name("TAZOE Kenta")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2423*], [#delta(1)],
      [185], [#name("托马斯 特雷格勒")], [#age(25)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2423*], [#delta(-3)],
      [186], [#name("FLORITZ Philipp")], [#age(24)], [#assoc("BUL")], [#right], [#shakehand], [#attack], [*2420*], [#delta(143)],
      [187], [#name("YANG Heng-Wei")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2420*], [#delta(1)],
      [188], [#name("费奥多尔 库兹明")], [#age(32)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2420*], [#delta(-77)],
      [189], [#name("及川瑞基")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2418*], [#delta(26)],
      [190], [#name("STERNBERG Kasper")], [#age(26)], [#assoc("DEN")], [#right], [#shakehand], [#attack], [*2417*], [#delta(0)],
      [191], [#name("威廉 亨泽尔")], [#age(33)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2417*], [#delta(0)],
      [192], [#name("穆罕默德 埃尔贝亚利")], [#age(27)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2414*], [#delta(-25)],
      [193], [#name("安德鲁 巴格利")], [#age(32)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2414*], [#delta(0)],
      [194], [#name("林兆恒")], [#age(19)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2414*], [#delta(0)],
      [195], [#name("埃利亚斯 拉内富尔")], [#age(19)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2408*], [#delta(31)],
      [196], [#name("米哈伊尔 派科夫")], [#age(26)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2408*], [#delta(-43)],
      [197], [#name("吴志祺")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2407*], [#delta(2)],
      [198], [#name("CHEN Diogo")], [#age(19)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2407*], [#delta(96)],
      [199], [#name("康斯坦丁 乔蒂")], [#age(32)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2406*], [#delta(1)],
      [200], [#name("罗宾 德沃斯")], [#age(21)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2406*], [#delta(-95)],
    )
  )
