#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("丁宁")], [#age(25)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*3029*], [#delta(0)],
      [2], [#name("李晓霞")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3021*], [#delta(4)],
      [3], [#name("朱雨玲")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2997*], [#delta(-1)],
      [4], [#name("刘诗雯")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2989*], [#delta(-1)],
      [5], [#name("陈梦")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2922*], [#delta(0)],
      [6], [#name("武杨")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2921*], [#delta(-2)],
      [7], [#name("石川佳纯")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2869*], [#delta(0)],
      [8], [#name("李明顺")], [#age(23)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2801*], [#delta(1)],
      [9], [#name("文佳")], [#age(26)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2791*], [#delta(2)],
      [10], [#name("冯天薇")], [#age(29)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2781*], [#delta(0)],
      [11], [#name("韩莹")], [#age(32)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2761*], [#delta(-3)],
      [12], [#name("福原爱")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2754*], [#delta(0)],
      [13], [#name("胡丽梅")], [#age(20)], [#assoc("CHN")], [#right], [#penhold], [#defense], [*2744*], [#delta(1)],
      [14], [#name("刘佳")], [#age(33)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2719*], [#delta(7)],
      [15], [#name("徐孝元")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2708*], [#delta(-2)],
      [16], [#name("伊丽莎白 萨马拉")], [#age(26)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2699*], [#delta(19)],
      [17], [#name("王曼昱")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2696*], [#delta(-1)],
      [18], [#name("木子")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2691*], [#delta(-1)],
      [19], [#name("梁夏银")], [#age(21)], [#assoc("COR")], [#right], [#shakehand], [#attack], [*2689*], [#delta(9)],
      [20], [#name("于梦雨")], [#age(26)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2676*], [#delta(-2)],
      [21], [#name("刘高阳")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2675*], [#delta(-1)],
      [22], [#name("平野早矢香")], [#age(30)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2673*], [#delta(7)],
      [23], [#name("若宫三纱子")], [#age(26)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2662*], [#delta(34)],
      [24], [#name("李佼")], [#age(42)], [#assoc("NED")], [#left], [#penhold], [#attack], [*2651*], [#delta(68)],
      [25], [#name("李芬")], [#age(39)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2650*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("顾玉婷")], [#age(20)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2644*], [#delta(1)],
      [27], [#name("吴佳多")], [#age(38)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2641*], [#delta(28)],
      [28], [#name("沈燕飞")], [#age(36)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2637*], [#delta(8)],
      [29], [#name("陈幸同")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2633*], [#delta(2)],
      [30], [#name("单晓娜")], [#age(32)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2629*], [#delta(-6)],
      [31], [#name("李美京")], [#age(25)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2626*], [#delta(1)],
      [32], [#name("文炫晶")], [#age(31)], [#assoc("KOR")], [?], [?], [?], [*2626*], [#delta(1)],
      [33], [#name("克里斯汀 朗")], [#age(30)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2625*], [#delta(1)],
      [34], [#name("傅玉")], [#age(37)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2621*], [#delta(-9)],
      [35], [#name("伊藤美诚")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2613*], [#delta(13)],
      [36], [#name("陈思羽")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2603*], [#delta(-13)],
      [37], [#name("车晓曦")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2602*], [#delta(1)],
      [38], [#name("张蔷")], [#age(21)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2601*], [#delta(1)],
      [39], [#name("杜凯琹")], [#age(19)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2600*], [#delta(19)],
      [40], [#name("浜本由惟")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2600*], [#delta(25)],
      [41], [#name("丹妮拉 多迪安")], [#age(27)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2599*], [#delta(-1)],
      [42], [#name("ABE Megumi")], [#age(29)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2596*], [#delta(-1)],
      [43], [#name("李洁")], [#age(31)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2595*], [#delta(-13)],
      [44], [#name("侯美玲")], [#age(26)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2591*], [#delta(-25)],
      [45], [#name("乔治娜 波塔")], [#age(30)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2588*], [#delta(-30)],
      [46], [#name("特蒂亚娜 比连科")], [#age(32)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2584*], [#delta(141)],
      [47], [#name("陈可")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2584*], [#delta(-2)],
      [48], [#name("吴颖岚")], [#age(23)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2583*], [#delta(-2)],
      [49], [#name("石垣优香")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2581*], [#delta(20)],
      [50], [#name("田志希")], [#age(23)], [#assoc("COR")], [#left], [#shakehand], [#attack], [*2575*], [#delta(6)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("杨晓欣")], [#age(27)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2572*], [#delta(30)],
      [52], [#name("平野美宇")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2571*], [#delta(-5)],
      [53], [#name("索菲亚 波尔卡诺娃")], [#age(21)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2570*], [#delta(-4)],
      [54], [#name("姜华珺")], [#age(31)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2570*], [#delta(32)],
      [55], [#name("李恩姬")], [#age(29)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2569*], [#delta(-4)],
      [56], [#name("帖雅娜")], [#age(36)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2567*], [#delta(39)],
      [57], [#name("倪夏莲")], [#age(52)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2564*], [#delta(-5)],
      [58], [#name("前田美优")], [#age(19)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2564*], [#delta(-8)],
      [59], [#name("金仲")], [#age(26)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2562*], [#delta(-5)],
      [60], [#name("林叶")], [#age(19)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2557*], [#delta(54)],
      [61], [#name("李倩")], [#age(29)], [#assoc("POL")], [#right], [#shakehand], [#defense], [*2543*], [#delta(-39)],
      [62], [#name("尹善爱")], [#age(32)], [#assoc("KOR")], [?], [?], [?], [*2542*], [#delta(-3)],
      [63], [#name("伊雷妮 伊万坎")], [#age(32)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2540*], [#delta(14)],
      [64], [#name("多拉 马达拉斯")], [#age(22)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2540*], [#delta(-11)],
      [65], [#name("李皓晴")], [#age(23)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2539*], [#delta(-21)],
      [66], [#name("李雪")], [#age(30)], [#assoc("FRA")], [#right], [#shakehand], [#defense], [*2538*], [#delta(56)],
      [67], [#name("何卓佳")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2536*], [#delta(-7)],
      [68], [#name("加藤美优")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2535*], [#delta(-25)],
      [69], [#name("佩特丽莎 索尔佳")], [#age(21)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2533*], [#delta(5)],
      [70], [#name("妮娜 米特兰姆")], [#age(19)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2532*], [#delta(-9)],
      [71], [#name("维多利亚 帕夫洛维奇")], [#age(37)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2530*], [#delta(-9)],
      [72], [#name("早田希娜")], [#age(15)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2529*], [#delta(-8)],
      [73], [#name("巴尔博拉 巴拉佐娃")], [#age(23)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2528*], [#delta(26)],
      [74], [#name("黄怡桦")], [#age(31)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2528*], [#delta(61)],
      [75], [#name("佐藤瞳")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2525*], [#delta(-8)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("顾若辰")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2524*], [#delta(-6)],
      [77], [#name("郑怡静")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2523*], [#delta(-35)],
      [78], [#name("金宋依")], [#age(21)], [#assoc("COR")], [#right], [#shakehand], [#defense], [*2518*], [#delta(-2)],
      [79], [#name("李依真")], [#age(28)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2518*], [#delta(-13)],
      [80], [#name("艾米丽 索尔佳")], [#age(25)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2516*], [#delta(-7)],
      [81], [#name("玛格丽塔 佩索茨卡")], [#age(24)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2510*], [#delta(-3)],
      [82], [#name("金慧星")], [#age(22)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2510*], [#delta(-3)],
      [83], [#name("周一涵")], [#age(21)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2509*], [#delta(-8)],
      [84], [#name("伯纳黛特 斯佐科斯")], [#age(20)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2505*], [#delta(67)],
      [85], [#name("朴英淑")], [#age(27)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2502*], [#delta(-17)],
      [86], [#name("素塔西尼 萨维塔布特")], [#age(21)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2490*], [#delta(-3)],
      [87], [#name("宋惠佳")], [#age(20)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2489*], [#delta(-3)],
      [88], [#name("李清韵")], [#age(21)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2489*], [#delta(169)],
      [89], [#name("森园美咲")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2486*], [#delta(-2)],
      [90], [#name("萨宾 温特")], [#age(23)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2485*], [#delta(11)],
      [91], [#name("藤井优子")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2482*], [#delta(-2)],
      [92], [#name("亚娜 诺斯科娃")], [#age(21)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2481*], [#delta(21)],
      [93], [#name("鲁塔 帕斯考斯基涅")], [#age(38)], [#assoc("LTU")], [#right], [#shakehand], [#attack], [*2474*], [#delta(-2)],
      [94], [#name("朴晟惠")], [#age(29)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2468*], [#delta(-1)],
      [95], [#name("张安")], [#age(19)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2466*], [#delta(-1)],
      [96], [#name("加布里埃拉 费赫尔")], [#age(27)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2461*], [#delta(0)],
      [97], [#name("松泽茉里奈")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2461*], [#delta(0)],
      [98], [#name("玛丽亚 多尔吉赫")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2461*], [#delta(19)],
      [99], [#name("卡塔日娜 格日博夫斯卡-弗朗茨")], [#age(26)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2455*], [#delta(-9)],
      [100], [#name("汉娜 哈珀诺娃")], [#age(30)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2455*], [#delta(12)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("尤利娅 普罗霍罗娃")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2452*], [#delta(-19)],
      [102], [#name("安娜 蒂克米罗娃")], [#age(31)], [#assoc("RUS")], [?], [?], [?], [*2451*], [#delta(-2)],
      [103], [#name("波琳娜 米哈伊洛娃")], [#age(29)], [#assoc("RUS")], [#right], [#shakehand], [#defense], [*2450*], [#delta(2)],
      [104], [#name("卡梅利娅 雅各布")], [#age(23)], [#assoc("ROU")], [#right], [#shakehand], [#defense], [*2448*], [#delta(-1)],
      [105], [#name("伊韦塔 瓦切诺夫斯卡")], [#age(29)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2448*], [#delta(-68)],
      [106], [#name("金玟耿")], [#age(23)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2448*], [#delta(-4)],
      [107], [#name("达蒙万 克宽")], [#age(18)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2446*], [#delta(9)],
      [108], [#name("凯莉 西布利")], [#age(27)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2444*], [#delta(-2)],
      [109], [#name("孙祯琦")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2443*], [#delta(-1)],
      [110], [#name("布里特 伊尔兰德")], [#age(21)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2442*], [#delta(-38)],
      [111], [#name("娜塔莉亚 巴约尔")], [#age(18)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2436*], [#delta(84)],
      [112], [#name("莱娅 拉科瓦奇")], [#age(19)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2434*], [#delta(-24)],
      [113], [#name("小野思保")], [#age(28)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2434*], [#delta(-4)],
      [114], [#name("卡特琳娜 佩卡沃娃")], [#age(28)], [#assoc("CZE")], [#left], [#shakehand], [#attack], [*2434*], [#delta(-16)],
      [115], [#name("森樱")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2431*], [#delta(0)],
      [116], [#name("佩特拉 洛瓦斯")], [#age(35)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2427*], [#delta(-6)],
      [117], [#name("玛妮卡 巴特拉")], [#age(20)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2417*], [#delta(2)],
      [118], [#name("安娜玛丽亚 埃尔德利")], [#age(30)], [#assoc("SRB")], [#right], [#shakehand], [#defense], [*2416*], [#delta(0)],
      [119], [#name("羡宜芳")], [#age(38)], [#assoc("FRA")], [#right], [#shakehand], [#defense], [*2414*], [#delta(-56)],
      [120], [#name("GALIC Alex")], [#age(21)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2413*], [#delta(14)],
      [121], [#name("林佳慧")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2412*], [#delta(69)],
      [122], [#name("田代早纪")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2411*], [#delta(33)],
      [123], [#name("玛蒂尔达 埃克霍尔姆")], [#age(33)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2410*], [#delta(-43)],
      [124], [#name("娜塔莉亚 帕尔蒂卡")], [#age(26)], [#assoc("POL")], [#left], [#shakehand], [#attack], [*2409*], [#delta(-53)],
      [125], [#name("LI Isabelle Siyun")], [#age(21)], [#assoc("SGP")], [#right], [#shakehand], [#defense], [*2407*], [#delta(-18)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("刘斐")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2406*], [#delta(-5)],
      [127], [#name("苏慧音")], [#age(17)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2404*], [#delta(0)],
      [128], [#name("ZHENG Shichang")], [#age(23)], [#assoc("CHN")], [?], [?], [?], [*2400*], [#delta(-4)],
      [129], [#name("韩杏")], [#age(26)], [#assoc("CGO")], [?], [?], [?], [*2396*], [#delta(-3)],
      [130], [#name("雷娜塔 斯特尔比科娃")], [#age(36)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2392*], [#delta(-19)],
      [131], [#name("松平志穗")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2387*], [#delta(-8)],
      [132], [#name("KATO Kyoka")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2384*], [#delta(-2)],
      [133], [#name("张墨")], [#age(26)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2384*], [#delta(-2)],
      [134], [#name("波琳 沙斯兰")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2383*], [#delta(40)],
      [135], [#name("刘馨尹")], [#age(28)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2382*], [#delta(30)],
      [136], [#name("SAKAI Haruka")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2378*], [#delta(-11)],
      [137], [#name("GUSEVA Ekaterina")], [#age(19)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2378*], [#delta(-5)],
      [138], [#name("MORITA Ayane")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2377*], [#delta(32)],
      [139], [#name("LEE Dasom")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2375*], [#delta(-6)],
      [140], [#name("汉娜 马特洛娃")], [#age(25)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2372*], [#delta(-4)],
      [141], [#name("郑先知")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2372*], [#delta(-37)],
      [142], [#name("郑有美")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2369*], [#delta(-3)],
      [143], [#name("桑德拉 佩尔格尔")], [#age(27)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2368*], [#delta(34)],
      [144], [#name("LIU Yu-Hsin")], [#age(22)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2368*], [#delta(57)],
      [145], [#name("LENNON Emmanuelle")], [#age(28)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2367*], [#delta(40)],
      [146], [#name("尤利娅 内库拉")], [#age(29)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2367*], [#delta(46)],
      [147], [#name("范思琦")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2365*], [#delta(-6)],
      [148], [#name("CHO Hala")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2364*], [#delta(-6)],
      [149], [#name("LI Chunli")], [#age(53)], [#assoc("NZL")], [#right], [#penhold], [#attack], [*2363*], [#delta(-6)],
      [150], [#name("田原")], [#age(40)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2363*], [#delta(-6)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("卡罗尔 格伦迪施")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2363*], [#delta(-66)],
      [152], [#name("萨拉 拉米雷斯")], [#age(28)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2362*], [#delta(-7)],
      [153], [#name("尚塔尔 曼茨")], [#age(19)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2361*], [#delta(-7)],
      [154], [#name("柳恩钟")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2360*], [#delta(-34)],
      [155], [#name("MU Jingyu")], [#age(16)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2357*], [#delta(-8)],
      [156], [#name("MATSUMOTO Yuki")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2354*], [#delta(-8)],
      [157], [#name("ISHIZUKA Miwako")], [#age(28)], [#assoc("JPN")], [?], [?], [?], [*2351*], [#delta(-8)],
      [158], [#name("亚迪拉 席尔瓦")], [#age(30)], [#assoc("MEX")], [#right], [#shakehand], [#attack], [*2350*], [#delta(-8)],
      [159], [#name("BIKBAEVA Anna")], [#age(21)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2348*], [#delta(-7)],
      [160], [#name("KIM Jiho")], [#age(16)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2347*], [#delta(-7)],
      [161], [#name("黄淑琴")], [#age(31)], [#assoc("MAS")], [?], [?], [?], [*2347*], [#delta(-7)],
      [162], [#name("阿迪娜 迪亚科努")], [#age(16)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2346*], [#delta(0)],
      [163], [#name("亚历山德拉 普里瓦洛娃")], [#age(28)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2344*], [#delta(-23)],
      [164], [#name("伊娃 奥多罗娃")], [#age(36)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2340*], [#delta(-7)],
      [165], [#name("CHOI Jeongmin")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2339*], [#delta(-28)],
      [166], [#name("TSUI Pao-Wen")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#defense], [*2338*], [#delta(-7)],
      [167], [#name("SAVELYEVA Antonina")], [#age(29)], [#assoc("RUS")], [?], [?], [?], [*2338*], [#delta(-7)],
      [168], [#name("劳拉 加斯尼尔")], [#age(22)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2337*], [#delta(-7)],
      [169], [#name("纳迪娜 博尔迈尔")], [#age(34)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2336*], [#delta(-6)],
      [170], [#name("ABE Airi")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2334*], [#delta(-6)],
      [171], [#name("GUI Lin")], [#age(22)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2334*], [#delta(64)],
      [172], [#name("叶莲娜 库兹米娜")], [#age(26)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2330*], [#delta(-14)],
      [173], [#name("李时温")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2329*], [#delta(-45)],
      [174], [#name("肖瑶茜")], [#age(21)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2325*], [#delta(-45)],
      [175], [#name("洪剑芳")], [#age(42)], [#assoc("AUS")], [#right], [#penhold], [#attack], [*2325*], [#delta(-8)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("加利娅 德沃拉克")], [#age(27)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2323*], [#delta(5)],
      [177], [#name("ISHIKAWA Rira")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2323*], [#delta(16)],
      [178], [#name("铃木李茄")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2321*], [#delta(-10)],
      [179], [#name("蒂娜 梅谢芙")], [#age(21)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2320*], [#delta(-41)],
      [180], [#name("穆玛 达斯")], [#age(31)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2320*], [#delta(-11)],
      [181], [#name("智恩彩")], [#age(19)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2318*], [#delta(-10)],
      [182], [#name("李恩惠")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2315*], [#delta(-7)],
      [183], [#name("PARK Seri")], [#age(18)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2314*], [#delta(-5)],
      [184], [#name("林依诺")], [#age(19)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2314*], [#delta(-5)],
      [185], [#name("宋马音")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2313*], [#delta(-5)],
      [186], [#name("克里斯蒂娜 希里奇")], [#age(23)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2311*], [#delta(-4)],
      [187], [#name("达娜 切霍娃")], [#age(32)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2310*], [#delta(-4)],
      [188], [#name("曾尖")], [#age(19)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2309*], [NEW],
      [189], [#name("AMANO Yu")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2306*], [#delta(-3)],
      [190], [#name("尼科莱塔 斯特凡诺娃")], [#age(31)], [#assoc("ITA")], [#left], [#shakehand], [#attack], [*2304*], [#delta(-1)],
      [191], [#name("艾希卡 穆克吉")], [#age(18)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2301*], [#delta(0)],
      [192], [#name("利吉娅 席尔瓦")], [#age(34)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2299*], [#delta(2)],
      [193], [#name("HWANG Jina")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2298*], [#delta(-27)],
      [194], [#name("LEE Seul")], [#age(19)], [#assoc("KOR")], [?], [?], [?], [*2297*], [#delta(2)],
      [195], [#name("NIWA Misato")], [#age(22)], [#assoc("JPN")], [?], [?], [?], [*2297*], [#delta(2)],
      [196], [#name("SABITOVA Valentina")], [#age(25)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2297*], [#delta(2)],
      [197], [#name("SIKORSKA Magdalena")], [#age(29)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2297*], [#delta(16)],
      [198], [#name("金加 斯特凡斯卡")], [#age(35)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2294*], [#delta(-14)],
      [199], [#name("LEE Yujin")], [#age(19)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2293*], [#delta(1)],
      [200], [#name("万远")], [#age(18)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2291*], [#delta(2)],
    )
  )
