#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("王楚钦")], [#age(26)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*3101*], [#delta(0)],
      [2], [#name("菲利克斯 勒布伦")], [#age(20)], [#assoc("FRA")], [#right], [#penhold], [#attack], [*2975*], [#delta(3)],
      [3], [#name("松岛辉空")], [#age(19)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2935*], [#delta(3)],
      [4], [#name("林昀儒")], [#age(25)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2925*], [#delta(-1)],
      [5], [#name("张本智和")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2897*], [#delta(-1)],
      [6], [#name("张禹珍")], [#age(31)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2883*], [#delta(4)],
      [7], [#name("帕特里克 弗朗西斯卡")], [#age(34)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2876*], [#delta(12)],
      [8], [#name("艾利克斯 勒布伦")], [#age(23)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2866*], [#delta(-6)],
      [9], [#name("温瑞博")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2861*], [#delta(3)],
      [10], [#name("林诗栋")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2839*], [#delta(-1)],
      [11], [#name("雨果 卡尔德拉诺")], [#age(30)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2832*], [#delta(-4)],
      [12], [#name("户上隼辅")], [#age(25)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2822*], [#delta(-1)],
      [13], [#name("特鲁斯 莫雷加德")], [#age(24)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2818*], [#delta(0)],
      [14], [#name("周启豪")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2802*], [#delta(-6)],
      [15], [#name("李尚洙")], [#age(36)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2797*], [#delta(0)],
      [16], [#name("弗拉维安 科顿")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2784*], [#delta(33)],
      [17], [#name("弗拉基米尔 西多连科")], [#age(24)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2764*], [#delta(4)],
      [18], [#name("陈垣宇")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2756*], [#delta(45)],
      [19], [#name("迪米特里 奥恰洛夫")], [#age(38)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2752*], [#delta(-1)],
      [20], [#name("邱党")], [#age(30)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2751*], [#delta(-3)],
      [21], [#name("安德斯 林德")], [#age(28)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2747*], [#delta(1)],
      [22], [#name("吴晙诚")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2743*], [#delta(2)],
      [23], [#name("梁靖崑")], [#age(30)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2741*], [#delta(6)],
      [24], [#name("西蒙 高兹")], [#age(32)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2740*], [#delta(-8)],
      [25], [#name("吉山僚一")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2734*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("卢博米尔 扬察里克")], [#age(39)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2731*], [#delta(2)],
      [27], [#name("向鹏")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2723*], [#delta(-4)],
      [28], [#name("达科 约奇克")], [#age(28)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2720*], [#delta(-14)],
      [29], [#name("卡纳克 贾哈")], [#age(26)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2715*], [#delta(1)],
      [30], [#name("朴康贤")], [#age(30)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2712*], [#delta(1)],
      [31], [#name("篠塚大登")], [#age(23)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2710*], [#delta(-6)],
      [32], [#name("黄镇廷")], [#age(35)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2708*], [#delta(1)],
      [33], [#name("宇田幸矢")], [#age(25)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2706*], [#delta(-6)],
      [34], [#name("薛飞")], [#age(27)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2702*], [#delta(2)],
      [35], [#name("黄友政")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2691*], [#delta(-15)],
      [36], [#name("川上流星")], [#age(17)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2686*], [#delta(2)],
      [37], [#name("吉村真晴")], [#age(33)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2684*], [#delta(25)],
      [38], [#name("迪博 泊雷特")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2681*], [#delta(6)],
      [39], [#name("贝内迪克特 杜达")], [#age(32)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2681*], [#delta(-4)],
      [40], [#name("林高远")], [#age(31)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2677*], [#delta(0)],
      [41], [#name("米洛什 雷德齐姆斯基")], [#age(20)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2675*], [#delta(4)],
      [42], [#name("马蒂亚斯 法尔克")], [#age(35)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2674*], [#delta(57)],
      [43], [#name("林钟勋")], [#age(29)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2672*], [#delta(51)],
      [44], [#name("陈俊菘")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2671*], [#delta(-3)],
      [45], [#name("诺沙迪 阿拉米扬")], [#age(35)], [#assoc("IRI")], [#left], [#shakehand], [#attack], [*2668*], [#delta(-2)],
      [46], [#name("乔 赛弗里德")], [#age(28)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2667*], [#delta(-14)],
      [47], [#name("吉村和弘")], [#age(30)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2666*], [#delta(-1)],
      [48], [#name("徐海东")], [#age(26)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2662*], [#delta(-1)],
      [49], [#name("安东 卡尔伯格")], [#age(29)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2659*], [#delta(-10)],
      [50], [#name("滨田一辉")], [#age(23)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2655*], [#delta(-8)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("朴奎炫")], [#age(21)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2654*], [#delta(-1)],
      [52], [#name("克里斯坦 卡尔松")], [#age(35)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2650*], [#delta(16)],
      [53], [#name("牛冠凯")], [#age(24)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2645*], [#delta(2)],
      [54], [#name("周恺")], [#age(30)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2644*], [#delta(2)],
      [55], [#name("乔鲍 安德拉斯")], [#age(24)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2644*], [#delta(81)],
      [56], [#name("托米斯拉夫 普卡")], [#age(30)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2643*], [#delta(-22)],
      [57], [#name("赵胜敏")], [#age(28)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2642*], [#delta(18)],
      [58], [#name("若昂 热拉尔多")], [#age(31)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2640*], [#delta(27)],
      [59], [#name("基里尔 格拉西缅科")], [#age(30)], [#assoc("KAZ")], [#right], [#shakehand], [#attack], [*2639*], [#delta(23)],
      [60], [#name("阿德里安 拉森福斯")], [#age(23)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2639*], [#delta(68)],
      [61], [#name("阿尔瓦罗 罗布勒斯")], [#age(35)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2635*], [#delta(-1)],
      [62], [#name("冯翊新")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2630*], [#delta(-10)],
      [63], [#name("袁励岑")], [#age(26)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2630*], [#delta(1)],
      [64], [#name("高承睿")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2629*], [#delta(1)],
      [65], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(46)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2629*], [#delta(-4)],
      [66], [#name("奥马尔 阿萨尔")], [#age(35)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2619*], [#delta(-18)],
      [67], [#name("利亚姆 皮切福德")], [#age(33)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2619*], [#delta(2)],
      [68], [#name("徐瑛彬")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2617*], [#delta(3)],
      [69], [#name("莱奥 德诺德雷斯特")], [#age(26)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2617*], [#delta(-18)],
      [70], [#name("弗拉迪斯拉夫 乌尔苏")], [#age(25)], [#assoc("MDA")], [#left], [#shakehand], [#attack], [*2615*], [#delta(9)],
      [71], [#name("米哈伊 博博奇卡")], [#age(40)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2614*], [#delta(70)],
      [72], [#name("田中佑汰")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2612*], [#delta(-18)],
      [73], [#name("郭勇")], [#age(20)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2610*], [#delta(-15)],
      [74], [#name("尤利安 奇里塔")], [#age(20)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2607*], [#delta(23)],
      [75], [#name("曾蓓勋")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2605*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("ZELJKO Filip")], [#age(30)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2603*], [#delta(137)],
      [77], [#name("村松雄斗")], [#age(30)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2598*], [#delta(6)],
      [78], [#name("哈米特 德赛")], [#age(33)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2598*], [#delta(11)],
      [79], [#name("维姆 维尔东肖特")], [#age(21)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2597*], [#delta(-9)],
      [80], [#name("吉山和希")], [#age(19)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2597*], [#delta(6)],
      [81], [#name("金民赫")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2594*], [#delta(7)],
      [82], [#name("张佑安")], [#age(20)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2593*], [#delta(-45)],
      [83], [#name("马努什 沙阿")], [#age(25)], [#assoc("IND")], [#left], [#shakehand], [#attack], [*2592*], [#delta(-26)],
      [84], [#name("汤姆 贾维斯")], [#age(27)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2591*], [#delta(-12)],
      [85], [#name("郭冠宏")], [#age(18)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2590*], [#delta(-19)],
      [86], [#name("马克斯 弗雷塔斯")], [#age(38)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2590*], [#delta(-12)],
      [87], [#name("里卡多 瓦尔特")], [#age(35)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2587*], [#delta(-20)],
      [88], [#name("胡安 佩雷斯")], [#age(24)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2587*], [#delta(27)],
      [89], [#name("爱德华 约内斯库")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2586*], [#delta(-36)],
      [90], [#name("安德烈 加奇尼")], [#age(40)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2585*], [#delta(3)],
      [91], [#name("叶夫根尼 吉洪诺夫")], [#age(21)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2585*], [#delta(63)],
      [92], [#name("安宰贤")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2584*], [#delta(11)],
      [93], [#name("安德烈 贝特尔斯迈尔")], [#age(21)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2581*], [#delta(11)],
      [94], [#name("朱尔斯 罗兰")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2581*], [#delta(-35)],
      [95], [#name("纳维德 沙姆斯")], [#age(21)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2579*], [#delta(0)],
      [96], [#name("陈颢桦")], [#age(22)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2579*], [#delta(-12)],
      [97], [#name("马雷克 巴多夫斯基")], [#age(29)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2576*], [#delta(-16)],
      [98], [#name("乔纳森 格罗斯")], [#age(34)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2573*], [#delta(2)],
      [99], [#name("夸德里 阿鲁纳")], [#age(38)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2573*], [#delta(-7)],
      [100], [#name("埃斯特班 多尔")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2571*], [#delta(27)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("木造勇人")], [#age(27)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2569*], [#delta(0)],
      [102], [#name("尼基塔 阿尔捷缅科")], [#age(27)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2569*], [#delta(-24)],
      [103], [#name("赵大成")], [#age(24)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2567*], [#delta(-7)],
      [104], [#name("林兆恒")], [#age(30)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2566*], [#delta(-31)],
      [105], [#name("贝内德克 奥拉")], [#age(35)], [#assoc("FIN")], [#right], [#shakehand], [#attack], [*2566*], [#delta(-3)],
      [106], [#name("及川瑞基")], [#age(29)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2565*], [#delta(-1)],
      [107], [#name("博扬 托基奇")], [#age(45)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2565*], [#delta(-1)],
      [108], [#name("伊日 马尔廷科")], [#age(27)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2565*], [#delta(-1)],
      [109], [#name("埃利亚斯 拉内富尔")], [#age(30)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2565*], [#delta(-11)],
      [110], [#name("马纳夫 塔卡尔")], [#age(26)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2565*], [#delta(-33)],
      [111], [#name("英田理志")], [#age(33)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2565*], [#delta(-3)],
      [112], [#name("蒂亚戈 阿波罗尼亚")], [#age(40)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2559*], [#delta(-21)],
      [113], [#name("沙提安 加纳纳塞卡兰")], [#age(33)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2558*], [#delta(-26)],
      [114], [#name("文森特 皮卡尔")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2557*], [#delta(-34)],
      [115], [#name("斯蒂芬 门格尔")], [#age(38)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2555*], [#delta(9)],
      [116], [#name("弗洛里安 布拉索")], [#age(26)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2554*], [#delta(15)],
      [117], [#name("李正植")], [#age(26)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2553*], [#delta(-4)],
      [118], [#name("基里尔 斯卡奇科夫")], [#age(39)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2550*], [NEW],
      [119], [#name("卢卡 姆拉德诺维奇")], [#age(28)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2546*], [#delta(4)],
      [120], [#name("尼马 阿拉米安")], [#age(34)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2546*], [#delta(-3)],
      [121], [#name("姚钧涛")], [#age(22)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2545*], [#delta(-3)],
      [122], [#name("禹衡圭")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2545*], [#delta(-10)],
      [123], [#name("奥拉西奥 西富恩特斯")], [#age(28)], [#assoc("ARG")], [#right], [#shakehand], [#attack], [*2544*], [#delta(22)],
      [124], [#name("横谷晟")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2544*], [#delta(-34)],
      [125], [#name("尼基尔 库马尔")], [#age(23)], [#assoc("USA")], [#left], [#shakehand], [#attack], [*2543*], [#delta(-6)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("塞德里克 纽廷克")], [#age(33)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2538*], [#delta(3)],
      [127], [#name("本雅明 法拉吉")], [#age(17)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2536*], [#delta(-16)],
      [128], [#name("五十岚史弥")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2535*], [#delta(-7)],
      [129], [#name("汪洋")], [#age(32)], [#assoc("SVK")], [#right], [#shakehand], [#defense], [*2534*], [#delta(-4)],
      [130], [#name("丹尼尔 哈贝松")], [#age(40)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2530*], [#delta(-4)],
      [131], [#name("奥维迪乌 伊奥内斯库")], [#age(37)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2528*], [#delta(-21)],
      [132], [#name("凯 斯图姆珀")], [#age(24)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2524*], [#delta(-18)],
      [133], [#name("托马斯 波兰斯基")], [#age(28)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2523*], [#delta(-3)],
      [134], [#name("马金宝")], [#age(26)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2522*], [#delta(-1)],
      [135], [#name("权赫")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2518*], [#delta(-19)],
      [136], [#name("罗曼 鲁伊斯")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2518*], [#delta(-1)],
      [137], [#name("KIM Gaon")], [#age(20)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2515*], [#delta(13)],
      [138], [#name("罗伯特 加尔多斯")], [#age(47)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2514*], [#delta(-1)],
      [139], [#name("廖振珽")], [#age(30)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2513*], [#delta(-30)],
      [140], [#name("MEISSNER Cedric")], [#age(26)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2510*], [#delta(30)],
      [141], [#name("迈赫迪 布洛斯")], [#age(31)], [#assoc("ALG")], [#right], [#shakehand], [#attack], [*2509*], [#delta(-19)],
      [142], [#name("马特乌什 扎莱夫斯基")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2509*], [#delta(-3)],
      [143], [#name("安德烈 普屯蒂卡")], [#age(27)], [#assoc("MDA")], [#left], [#shakehand], [#attack], [*2508*], [#delta(76)],
      [144], [#name("西蒙 贝格伦德")], [#age(29)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2507*], [#delta(-2)],
      [145], [#name("弗拉内 科伊奇")], [#age(34)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2507*], [#delta(-2)],
      [146], [#name("列夫 卡茨曼")], [#age(25)], [#assoc("RUS")], [#left], [#shakehand], [#attack], [*2506*], [#delta(-2)],
      [147], [#name("林文政")], [#age(21)], [#assoc("AUS")], [#left], [#shakehand], [#attack], [*2504*], [#delta(106)],
      [148], [#name("若昂 蒙泰罗")], [#age(43)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2501*], [#delta(19)],
      [149], [#name("坂井雄飞")], [#age(20)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2498*], [#delta(-3)],
      [150], [#name("卢文 菲鲁斯")], [#age(38)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2495*], [#delta(-3)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("斯特凡 乌瓦切")], [#age(33)], [#assoc("ALG")], [#left], [#shakehand], [#attack], [*2494*], [#delta(-2)],
      [152], [#name("SUZUKI Hayate")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2494*], [#delta(-1)],
      [153], [#name("徐弦家")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2493*], [#delta(7)],
      [154], [#name("PAL Akash")], [#age(25)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2493*], [#delta(-16)],
      [155], [#name("伊尔万 贝特朗")], [#age(26)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2492*], [#delta(-2)],
      [156], [#name("马切伊 库比克")], [#age(23)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2491*], [#delta(5)],
      [157], [#name("达里乌斯 莫维莱亚努")], [#age(21)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2490*], [#delta(-17)],
      [158], [#name("洪敬恺")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2489*], [#delta(-26)],
      [159], [#name("岩井田骏斗")], [#age(17)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2489*], [#delta(-3)],
      [160], [#name("萩原启至")], [#age(21)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2484*], [#delta(-5)],
      [161], [#name("劳伦斯 德沃斯")], [#age(26)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2482*], [#delta(-2)],
      [162], [#name("力廉 巴德")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2478*], [#delta(-4)],
      [163], [#name("安库尔 巴塔查尔吉")], [#age(20)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2477*], [#delta(-15)],
      [164], [#name("伊沃 本")], [#age(23)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2477*], [#delta(71)],
      [165], [#name("ABDELAZIZ Youssef")], [#age(26)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2475*], [#delta(-8)],
      [166], [#name("亚历克西斯 库赖希")], [#age(22)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2475*], [#delta(9)],
      [167], [#name("SURAVAJJULA Snehit")], [#age(26)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2474*], [#delta(-2)],
      [168], [#name("MUTTI Matteo")], [#age(26)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2474*], [#delta(25)],
      [169], [#name("马塞洛 阿吉雷")], [#age(33)], [#assoc("PAR")], [#left], [#shakehand], [#attack], [*2470*], [#delta(-7)],
      [170], [#name("尼亚戈尔 斯托亚诺夫")], [#age(39)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2468*], [#delta(35)],
      [171], [#name("李和宸")], [#age(17)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2465*], [#delta(-7)],
      [172], [#name("保罗 德林克霍尔")], [#age(36)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2464*], [#delta(-4)],
      [173], [#name("阿米尔侯赛因 霍达伊")], [#age(28)], [#assoc("IRI")], [#right], [#shakehand], [#attack], [*2463*], [#delta(-21)],
      [174], [#name("萨迪 伊斯梅洛夫")], [#age(30)], [#assoc("TJK")], [#left], [#shakehand], [#attack], [*2463*], [#delta(-3)],
      [175], [#name("卢博米尔 皮斯特耶")], [#age(42)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2463*], [#delta(-55)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("德尼 科祖尔")], [#age(29)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2462*], [#delta(1)],
      [177], [#name("安迪 佩雷拉")], [#age(37)], [#assoc("CUB")], [#left], [#shakehand], [#attack], [*2461*], [#delta(-5)],
      [178], [#name("孙杨")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2457*], [#delta(25)],
      [179], [#name("GOMEZ Gustavo")], [#age(32)], [#assoc("CHI")], [#right], [#shakehand], [#attack], [*2456*], [#delta(-16)],
      [180], [#name("纳唐 拉姆")], [#age(19)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2456*], [#delta(-6)],
      [181], [#name("拉雷什 西波斯")], [#age(26)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2456*], [#delta(-47)],
      [182], [#name("PRADHIVADHI Abhinandh")], [#age(18)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2455*], [#delta(-6)],
      [183], [#name("OKANO Shunsuke")], [#age(22)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2454*], [#delta(-5)],
      [184], [#name("WONG Qi Shen")], [#age(23)], [#assoc("MAS")], [#left], [#shakehand], [#attack], [*2452*], [#delta(-4)],
      [185], [#name("SCHWEIGER Tom")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2450*], [#delta(37)],
      [186], [#name("林彦均")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2449*], [#delta(8)],
      [187], [#name("姜东秀")], [#age(32)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2447*], [#delta(-3)],
      [188], [#name("马丁 阿莱格罗")], [#age(30)], [#assoc("BEL")], [#left], [#shakehand], [#attack], [*2447*], [#delta(-15)],
      [189], [#name("冯耀恩")], [#age(24)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2447*], [#delta(-7)],
      [190], [#name("苏姆亚吉特 格霍什")], [#age(33)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2444*], [#delta(-2)],
      [191], [#name("维托 石井")], [#age(31)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2444*], [#delta(-2)],
      [192], [#name("KIM Byunghyeon")], [#age(26)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2443*], [#delta(-2)],
      [193], [#name("亚当 苏迪")], [#age(30)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2440*], [#delta(-2)],
      [194], [#name("萨穆埃尔 库尔奇茨基")], [#age(24)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-28)],
      [195], [#name("GREBNEV Maksim")], [#age(24)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2437*], [#delta(-3)],
      [196], [#name("ISTRATE Andrei")], [#age(21)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2436*], [#delta(60)],
      [197], [#name("康纳 格林")], [#age(20)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2436*], [#delta(93)],
      [198], [#name("DE LAS HERAS Rafael")], [#age(27)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2435*], [#delta(26)],
      [199], [#name("周冠宏")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2434*], [#delta(-4)],
      [200], [#name("约翰 奥耶博德")], [#age(24)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2433*], [#delta(-4)],
    )
  )
