#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("孙颖莎")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3184*], [#delta(0)],
      [2], [#name("王曼昱")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3001*], [#delta(0)],
      [3], [#name("大藤沙月")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2964*], [#delta(0)],
      [4], [#name("张本美和")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2958*], [#delta(0)],
      [5], [#name("早田希娜")], [#age(26)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2919*], [#delta(10)],
      [6], [#name("朱雨玲")], [#age(31)], [#assoc("MAC")], [#right], [#shakehand], [#attack], [*2916*], [#delta(1)],
      [7], [#name("王艺迪")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2881*], [#delta(-2)],
      [8], [#name("桥本帆乃香")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2869*], [#delta(1)],
      [9], [#name("石洵瑶")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2836*], [#delta(4)],
      [10], [#name("陈熠")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2818*], [#delta(-4)],
      [11], [#name("金琴英")], [#age(25)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2812*], [#delta(0)],
      [12], [#name("萨宾 温特")], [#age(34)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2811*], [#delta(-4)],
      [13], [#name("陈幸同")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2810*], [#delta(-1)],
      [14], [#name("阿德里安娜 迪亚兹")], [#age(26)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2790*], [#delta(14)],
      [15], [#name("佐藤瞳")], [#age(29)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2785*], [#delta(-5)],
      [16], [#name("木原美悠")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2784*], [#delta(20)],
      [17], [#name("申裕斌")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2781*], [#delta(1)],
      [18], [#name("蒯曼")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2770*], [#delta(-4)],
      [19], [#name("范姝涵")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2761*], [#delta(42)],
      [20], [#name("汉娜 高达")], [#age(19)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2760*], [#delta(-3)],
      [21], [#name("平野美宇")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2736*], [#delta(-2)],
      [22], [#name("朱芊曦")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2733*], [#delta(0)],
      [23], [#name("横井咲樱")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2731*], [#delta(11)],
      [24], [#name("安娜 赫西")], [#age(20)], [#assoc("WAL")], [#right], [#shakehand], [#attack], [*2730*], [#delta(-8)],
      [25], [#name("何卓佳")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2721*], [#delta(-1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("赤江夏星")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2716*], [#delta(3)],
      [27], [#name("伊藤美诚")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2715*], [#delta(-2)],
      [28], [#name("边松景")], [#age(25)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2711*], [#delta(-1)],
      [29], [#name("韩莹")], [#age(43)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2703*], [#delta(4)],
      [30], [#name("朱思冰")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2701*], [#delta(8)],
      [31], [#name("布鲁娜 高桥")], [#age(26)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2694*], [#delta(12)],
      [32], [#name("长崎美柚")], [#age(24)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2693*], [#delta(-2)],
      [33], [#name("芝田沙季")], [#age(29)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2688*], [#delta(2)],
      [34], [#name("奥拉万 帕拉南")], [#age(29)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2687*], [#delta(6)],
      [35], [#name("玛格丽塔 佩索茨卡")], [#age(35)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2685*], [#delta(-15)],
      [36], [#name("兼吉优花")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2685*], [#delta(5)],
      [37], [#name("笹尾明日香")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2667*], [#delta(-5)],
      [38], [#name("娜塔莉亚 巴约尔")], [#age(29)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2666*], [#delta(-12)],
      [39], [#name("叶伊恬")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2662*], [#delta(3)],
      [40], [#name("韩菲儿")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2662*], [#delta(4)],
      [41], [#name("伊丽莎白 阿布拉米安")], [#age(23)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2661*], [#delta(4)],
      [42], [#name("杨晓欣")], [#age(38)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2660*], [#delta(28)],
      [43], [#name("王晓彤")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2659*], [#delta(-20)],
      [44], [#name("莎莉 莫伊兰")], [#age(19)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2657*], [#delta(2)],
      [45], [#name("张翔宇")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2657*], [#delta(3)],
      [46], [#name("苏籽童")], [#age(17)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2657*], [#delta(3)],
      [47], [#name("杜凯琹")], [#age(30)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2653*], [#delta(6)],
      [48], [#name("出泽杏佳")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2648*], [#delta(2)],
      [49], [#name("安妮特 考夫曼")], [#age(20)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2646*], [#delta(6)],
      [50], [#name("单晓娜")], [#age(43)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2644*], [#delta(24)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("杨屹韵")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2644*], [#delta(-14)],
      [52], [#name("朱梓予")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2642*], [#delta(-31)],
      [53], [#name("伯纳黛特 斯佐科斯")], [#age(31)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2641*], [#delta(-22)],
      [54], [#name("李昱谆")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2627*], [#delta(0)],
      [55], [#name("徐奕")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2626*], [#delta(-4)],
      [56], [#name("傅玉")], [#age(48)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2620*], [#delta(-4)],
      [57], [#name("郑怡静")], [#age(34)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2618*], [#delta(7)],
      [58], [#name("覃予萱")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2608*], [#delta(-19)],
      [59], [#name("袁嘉楠")], [#age(41)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2608*], [#delta(-1)],
      [60], [#name("面田采巳")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2599*], [#delta(-1)],
      [61], [#name("高森爱央")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2599*], [#delta(2)],
      [62], [#name("纵歌曼")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2595*], [#delta(-15)],
      [63], [#name("青木咲智")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2594*], [#delta(24)],
      [64], [#name("玛妮卡 巴特拉")], [#age(31)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2593*], [#delta(33)],
      [65], [#name("迪维扬希 布霍米克")], [#age(16)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2593*], [#delta(2)],
      [66], [#name("安德烈娅 德拉戈曼")], [#age(26)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2589*], [#delta(-10)],
      [67], [#name("刘杨子")], [#age(24)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2589*], [#delta(2)],
      [68], [#name("普利蒂卡 帕瓦德")], [#age(22)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2588*], [#delta(-11)],
      [69], [#name("妮娜 米特兰姆")], [#age(30)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2587*], [#delta(3)],
      [70], [#name("村松心菜")], [#age(14)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2586*], [#delta(23)],
      [71], [#name("张安")], [#age(30)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2585*], [#delta(-11)],
      [72], [#name("小盐悠菜")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2583*], [#delta(1)],
      [73], [#name("李恩惠")], [#age(31)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2581*], [#delta(-5)],
      [74], [#name("克里斯蒂娜 卡尔伯格")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2576*], [#delta(109)],
      [75], [#name("刘叡潾")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2575*], [#delta(15)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("李洁")], [#age(42)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2573*], [#delta(-1)],
      [77], [#name("索菲亚 波尔卡诺娃")], [#age(32)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2569*], [#delta(-15)],
      [78], [#name("张墨")], [#age(37)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2562*], [#delta(53)],
      [79], [#name("卡米耶 卢茨")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2562*], [#delta(33)],
      [80], [#name("斯丽贾 阿库拉")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2559*], [#delta(22)],
      [81], [#name("黄愉偼")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2558*], [#delta(-5)],
      [82], [#name("陈昭澐")], [#age(21)], [#assoc("SGP")], [#right], [#shakehand], [#defense], [*2557*], [#delta(-5)],
      [83], [#name("姚睿轩")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2552*], [#delta(-3)],
      [84], [#name("肖瑶茜")], [#age(32)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2547*], [#delta(1)],
      [85], [#name("黎明映")], [#age(16)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2546*], [#delta(-4)],
      [86], [#name("木村香纯")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2543*], [#delta(-15)],
      [87], [#name("伊丽莎白 萨马拉")], [#age(37)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2542*], [#delta(-21)],
      [88], [#name("嵯水影")], [#age(26)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2538*], [#delta(-4)],
      [89], [#name("彭郁涵")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2538*], [#delta(40)],
      [90], [#name("金成珍")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2537*], [#delta(-4)],
      [91], [#name("金娜英")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2536*], [#delta(-26)],
      [92], [#name("比安卡 梅罗苏")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2535*], [#delta(32)],
      [93], [#name("金河英")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2533*], [#delta(-5)],
      [94], [#name("柳是宇")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2531*], [#delta(75)],
      [95], [#name("面手凛")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2531*], [#delta(-6)],
      [96], [#name("松岛美空")], [#age(13)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2530*], [#delta(-5)],
      [97], [#name("巴尔博拉 巴拉佐娃")], [#age(34)], [#assoc("SVK")], [#left], [#shakehand], [#attack], [*2529*], [#delta(12)],
      [98], [#name("丁怡婕")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2526*], [#delta(-4)],
      [99], [#name("盖娅 蒙法尔迪尼")], [#age(25)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2524*], [#delta(-4)],
      [100], [#name("吴咏琳")], [#age(23)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2518*], [#delta(-18)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("阿莱克西娅 诺丹")], [#age(16)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2509*], [#delta(73)],
      [102], [#name("祝启慧")], [#age(14)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2507*], [#delta(-6)],
      [103], [#name("王艾米")], [#age(24)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2504*], [#delta(-5)],
      [104], [#name("柳韩娜")], [#age(24)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2504*], [#delta(-25)],
      [105], [#name("邵杰妮")], [#age(32)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2503*], [#delta(14)],
      [106], [#name("姜依依")], [#age(16)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2500*], [#delta(-3)],
      [107], [#name("佐久间结生")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2497*], [#delta(-2)],
      [108], [#name("梁夏银")], [#age(32)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2496*], [#delta(-2)],
      [109], [#name("杨惠泽")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2495*], [#delta(-1)],
      [110], [#name("苏蒂尔塔 穆克吉")], [#age(31)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2493*], [#delta(96)],
      [111], [#name("舒麟茜")], [#age(20)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2492*], [#delta(-7)],
      [112], [#name("闫禹橦")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2490*], [#delta(-1)],
      [113], [#name("简彤娟")], [#age(24)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2489*], [#delta(0)],
      [114], [#name("巫嘉恩")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2484*], [#delta(-4)],
      [115], [#name("李多恩")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2483*], [#delta(-32)],
      [116], [#name("波琳 沙斯兰")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2482*], [#delta(-2)],
      [117], [#name("崔孝珠")], [#age(28)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2480*], [#delta(-39)],
      [118], [#name("弗拉达 沃罗宁娜")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2480*], [#delta(-2)],
      [119], [#name("李承垠")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2479*], [#delta(-2)],
      [120], [#name("伊莎贝拉 卢普列斯库")], [#age(27)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2479*], [#delta(-20)],
      [121], [#name("亚沙斯维尼 戈尔帕德")], [#age(22)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2478*], [#delta(73)],
      [122], [#name("帕察拉蓬 旺拉空")], [#age(19)], [#assoc("THA")], [#right], [#shakehand], [#defense], [*2478*], [#delta(-4)],
      [123], [#name("万远")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2477*], [#delta(10)],
      [124], [#name("萨比娜 苏尔扬")], [#age(26)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2476*], [#delta(-17)],
      [125], [#name("萨拉 托基奇")], [#age(20)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2475*], [#delta(31)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("蔡昀恩")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2474*], [#delta(1)],
      [127], [#name("艾希卡 穆克吉")], [#age(29)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2472*], [#delta(-7)],
      [128], [#name("汉娜 马特洛娃")], [#age(36)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2469*], [#delta(-3)],
      [129], [#name("陈忞昕")], [#age(17)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2467*], [#delta(-3)],
      [130], [#name("竹谷美凉")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2467*], [#delta(-8)],
      [131], [#name("玛丽亚 泰拉科娃")], [#age(25)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2467*], [#delta(-3)],
      [132], [#name("崔海恩")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2465*], [#delta(-2)],
      [133], [#name("迪亚 奇塔莱")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2465*], [#delta(6)],
      [134], [#name("朱成竹")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2463*], [#delta(0)],
      [135], [#name("郭铮")], [#age(16)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2461*], [#delta(11)],
      [136], [#name("刘子菱")], [#age(15)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2460*], [#delta(0)],
      [137], [#name("哈娜 阿拉波维奇")], [#age(22)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2460*], [#delta(47)],
      [138], [#name("陈思羽")], [#age(33)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2458*], [#delta(-15)],
      [139], [#name("夏洛特 卢茨")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2454*], [#delta(-38)],
      [140], [#name("麻生丽名")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2453*], [#delta(-2)],
      [141], [#name("莱娜 霍查特")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2452*], [#delta(10)],
      [142], [#name("苏珊娜 维尔戈斯")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2451*], [#delta(20)],
      [143], [#name("安娜 布日斯卡")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2449*], [#delta(0)],
      [144], [#name("朴佳贤")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2449*], [#delta(-52)],
      [145], [#name("瓦列里娅 谢尔巴特赫")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2445*], [#delta(-1)],
      [146], [#name("SINGEORZAN Ioana")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2445*], [#delta(-1)],
      [147], [#name("何天天")], [#age(28)], [#assoc("ENG")], [#right], [#penhold], [#attack], [*2444*], [#delta(-12)],
      [148], [#name("陈琦媗")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2442*], [#delta(-1)],
      [149], [#name("胡一")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2442*], [#delta(0)],
      [150], [#name("李多恩")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2442*], [#delta(9)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("布里特 伊尔兰德")], [#age(32)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2440*], [#delta(-36)],
      [152], [#name("卡塔日娜 文格任")], [#age(25)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2436*], [#delta(-11)],
      [153], [#name("石田心美")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-1)],
      [154], [#name("WU Ying Syuan")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2430*], [#delta(50)],
      [155], [#name("奥黛丽 扎里夫")], [#age(28)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2430*], [#delta(-18)],
      [156], [#name("陈佳宜")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#defense], [*2430*], [#delta(-3)],
      [157], [#name("卡琳 格罗福娃")], [#age(32)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2429*], [#delta(-3)],
      [158], [#name("塔妮莎 科特查")], [#age(20)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2427*], [#delta(-3)],
      [159], [#name("黄禹乔")], [#age(30)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2426*], [#delta(-2)],
      [160], [#name("琳达 伯格斯特隆")], [#age(31)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2425*], [#delta(-61)],
      [161], [#name("斯维斯蒂卡 戈什")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2425*], [#delta(-40)],
      [162], [#name("郑先知")], [#age(33)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2425*], [#delta(-4)],
      [163], [#name("蒂娜 梅谢芙")], [#age(32)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2424*], [#delta(26)],
      [164], [#name("塔尼娅 普莱安")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2423*], [#delta(-22)],
      [165], [#name("瓜生日咲")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2420*], [#delta(-5)],
      [166], [#name("赵王琪")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2420*], [#delta(-3)],
      [167], [#name("COK Isa")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2419*], [#delta(-27)],
      [168], [#name("冈田琴菜")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2418*], [#delta(-4)],
      [169], [#name("金恩胥")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2418*], [#delta(2)],
      [170], [#name("陈琦媗")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2417*], [#delta(-5)],
      [171], [#name("妮可 阿利亚")], [#age(21)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2415*], [#delta(2)],
      [172], [#name("乔治娜 波塔")], [#age(41)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2415*], [#delta(-5)],
      [173], [#name("辛德雷拉 达斯")], [#age(17)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2413*], [#delta(-41)],
      [174], [#name("莱娅 拉科瓦奇")], [#age(30)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2412*], [#delta(14)],
      [175], [#name("卞瑞英")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2412*], [#delta(-5)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("LEE Haelin")], [#age(15)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2404*], [#delta(0)],
      [177], [#name("金珉舒")], [#age(16)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2403*], [#delta(0)],
      [178], [#name("郑艺仁")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2403*], [#delta(-6)],
      [179], [#name("金谞润")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2401*], [#delta(-1)],
      [180], [#name("阿迪娜 迪亚科努")], [#age(27)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2401*], [#delta(-12)],
      [181], [#name("埃列娜 扎哈里亚")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2400*], [#delta(-31)],
      [182], [#name("莎拉 德努特")], [#age(34)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2395*], [#delta(-7)],
      [183], [#name("曾尖")], [#age(30)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2394*], [#delta(-17)],
      [184], [#name("倪夏莲")], [#age(63)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2392*], [#delta(-36)],
      [185], [#name("焦尔吉娅 皮科林")], [#age(30)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2392*], [#delta(0)],
      [186], [#name("黄怡桦")], [#age(42)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2391*], [#delta(0)],
      [187], [#name("绍蕾什 阿卡舍娃")], [#age(26)], [#assoc("KAZ")], [#right], [#shakehand], [#attack], [*2391*], [#delta(0)],
      [188], [#name("阿努莎 库通巴莱")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2389*], [#delta(2)],
      [189], [#name("艾卡特里尼 托利乌")], [#age(31)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2386*], [#delta(2)],
      [190], [#name("埃杰 哈拉奇")], [#age(24)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2384*], [#delta(2)],
      [191], [#name("马泰娅 耶格尔")], [#age(31)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2383*], [#delta(2)],
      [192], [#name("张璇")], [#age(27)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2382*], [#delta(26)],
      [193], [#name("徐慧尧")], [#age(19)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2380*], [#delta(3)],
      [194], [#name("弗兰琪斯卡 施莱纳")], [#age(25)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2380*], [#delta(3)],
      [195], [#name("TEE Ai Xin")], [#age(25)], [#assoc("MAS")], [#right], [#penhold], [#attack], [*2380*], [#delta(3)],
      [196], [#name("伊万娜 马洛巴比奇")], [#age(46)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2378*], [#delta(25)],
      [197], [#name("CHOI Seoyeon")], [#age(17)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2377*], [#delta(-36)],
      [198], [#name("WEI Jingming")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2375*], [#delta(2)],
      [199], [#name("XIANG Junlin")], [#age(19)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2374*], [#delta(2)],
      [200], [#name("ITAGAKI Koharu")], [#age(16)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2373*], [#delta(8)],
    )
  )
