#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Women's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("孙颖莎")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3088*], [#delta(0)],
      [2], [#name("王曼昱")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*3009*], [#delta(0)],
      [3], [#name("蒯曼")], [#age(22)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2996*], [#delta(0)],
      [4], [#name("张本美和")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2986*], [#delta(4)],
      [5], [#name("金琴英")], [#age(25)], [#assoc("PRK")], [#left], [#shakehand], [#attack], [*2900*], [#delta(1)],
      [6], [#name("大藤沙月")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2899*], [#delta(-1)],
      [7], [#name("陈熠")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2874*], [#delta(4)],
      [8], [#name("朱雨玲")], [#age(31)], [#assoc("MAC")], [#right], [#shakehand], [#attack], [*2873*], [#delta(-4)],
      [9], [#name("萨宾 温特")], [#age(34)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2863*], [#delta(-2)],
      [10], [#name("佐藤瞳")], [#age(29)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2836*], [#delta(0)],
      [11], [#name("早田希娜")], [#age(26)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2832*], [#delta(9)],
      [12], [#name("申裕斌")], [#age(22)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2831*], [#delta(7)],
      [13], [#name("王艺迪")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2830*], [#delta(-1)],
      [14], [#name("石洵瑶")], [#age(25)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2815*], [#delta(-1)],
      [15], [#name("陈幸同")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2791*], [#delta(-6)],
      [16], [#name("阿德里安娜 迪亚兹")], [#age(26)], [#assoc("PUR")], [#right], [#shakehand], [#attack], [*2782*], [#delta(0)],
      [17], [#name("芝田沙季")], [#age(29)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2766*], [#delta(1)],
      [18], [#name("长崎美柚")], [#age(24)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2759*], [#delta(-1)],
      [19], [#name("韩莹")], [#age(43)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2751*], [#delta(-4)],
      [20], [#name("赤江夏星")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2744*], [#delta(2)],
      [21], [#name("平野美宇")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2742*], [#delta(2)],
      [22], [#name("桥本帆乃香")], [#age(28)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2732*], [#delta(-8)],
      [23], [#name("王晓彤")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2729*], [#delta(2)],
      [24], [#name("木原美悠")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2721*], [#delta(-3)],
      [25], [#name("何卓佳")], [#age(28)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2718*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("钱天一")], [#age(26)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2716*], [#delta(2)],
      [27], [#name("伊藤美诚")], [#age(26)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2715*], [#delta(4)],
      [28], [#name("朱芊曦")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2713*], [#delta(-1)],
      [29], [#name("横井咲樱")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2701*], [#delta(-5)],
      [30], [#name("杨屹韵")], [#age(23)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2698*], [#delta(-1)],
      [31], [#name("朱思冰")], [#age(26)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2696*], [#delta(-1)],
      [32], [#name("郑怡静")], [#age(34)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2693*], [#delta(5)],
      [33], [#name("笹尾明日香")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2685*], [#delta(-1)],
      [34], [#name("兼吉优花")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2685*], [#delta(147)],
      [35], [#name("朱梓予")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2684*], [#delta(-2)],
      [36], [#name("边松景")], [#age(25)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2683*], [#delta(-2)],
      [37], [#name("李洁")], [#age(42)], [#assoc("NED")], [#right], [#shakehand], [#defense], [*2682*], [#delta(-2)],
      [38], [#name("韩菲儿")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2680*], [#delta(-2)],
      [39], [#name("伊丽莎白 阿布拉米安")], [#age(23)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2679*], [#delta(25)],
      [40], [#name("纵歌曼")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2669*], [#delta(0)],
      [41], [#name("伯纳黛特 斯佐科斯")], [#age(31)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2661*], [#delta(9)],
      [42], [#name("张翔宇")], [#age(21)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2657*], [#delta(0)],
      [43], [#name("出泽杏佳")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2648*], [#delta(-2)],
      [44], [#name("安娜 赫西")], [#age(20)], [#assoc("WAL")], [#right], [#shakehand], [#attack], [*2644*], [#delta(17)],
      [45], [#name("徐奕")], [#age(21)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2642*], [#delta(1)],
      [46], [#name("叶伊恬")], [#age(19)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2637*], [#delta(33)],
      [47], [#name("布鲁娜 高桥")], [#age(26)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2636*], [#delta(6)],
      [48], [#name("青木咲智")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2632*], [#delta(1)],
      [49], [#name("高森爱央")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2629*], [#delta(22)],
      [50], [#name("覃予萱")], [#age(20)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2621*], [#delta(-6)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("索菲亚 波尔卡诺娃")], [#age(32)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2615*], [#delta(-8)],
      [52], [#name("面田采巳")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2615*], [#delta(6)],
      [53], [#name("金娜英")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2615*], [#delta(-15)],
      [54], [#name("杜凯琹")], [#age(30)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2613*], [#delta(-7)],
      [55], [#name("玛妮卡 巴特拉")], [#age(31)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2612*], [#delta(1)],
      [56], [#name("奥拉万 帕拉南")], [#age(29)], [#assoc("THA")], [#left], [#shakehand], [#attack], [*2612*], [#delta(7)],
      [57], [#name("安妮特 考夫曼")], [#age(20)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2611*], [#delta(-18)],
      [58], [#name("苏籽童")], [#age(17)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2606*], [#delta(-3)],
      [59], [#name("嵯水影")], [#age(26)], [#assoc("PRK")], [#right], [#shakehand], [#defense], [*2605*], [#delta(0)],
      [60], [#name("范姝涵")], [#age(22)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2605*], [#delta(0)],
      [61], [#name("玛格丽塔 佩索茨卡")], [#age(35)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2604*], [#delta(-10)],
      [62], [#name("梁夏银")], [#age(32)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2600*], [#delta(11)],
      [63], [#name("安德烈娅 德拉戈曼")], [#age(26)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2599*], [#delta(-6)],
      [64], [#name("肖瑶茜")], [#age(32)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2598*], [#delta(64)],
      [65], [#name("面手凛")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2597*], [#delta(-3)],
      [66], [#name("袁嘉楠")], [#age(41)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2596*], [#delta(-18)],
      [67], [#name("刘杨子")], [#age(24)], [#assoc("AUS")], [#right], [#shakehand], [#attack], [*2593*], [#delta(50)],
      [68], [#name("李恩惠")], [#age(31)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2592*], [#delta(-16)],
      [69], [#name("妮娜 米特兰姆")], [#age(30)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2590*], [#delta(29)],
      [70], [#name("小盐悠菜")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2583*], [#delta(-3)],
      [71], [#name("崔孝珠")], [#age(28)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2579*], [#delta(-3)],
      [72], [#name("王艾米")], [#age(24)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2569*], [#delta(2)],
      [73], [#name("陈思羽")], [#age(33)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2569*], [#delta(-4)],
      [74], [#name("斯丽贾 阿库拉")], [#age(28)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2565*], [#delta(-29)],
      [75], [#name("汉娜 高达")], [#age(19)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2561*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("崔海恩")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2560*], [#delta(0)],
      [77], [#name("素塔西尼 萨维塔布特")], [#age(32)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2560*], [#delta(-11)],
      [78], [#name("曾尖")], [#age(30)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2556*], [#delta(-13)],
      [79], [#name("柳韩娜")], [#age(24)], [#assoc("KOR")], [#left], [#shakehand], [#attack], [*2553*], [#delta(1)],
      [80], [#name("伊丽莎白 萨马拉")], [#age(37)], [#assoc("ROU")], [#left], [#shakehand], [#attack], [*2550*], [#delta(9)],
      [81], [#name("彭郁涵")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2544*], [#delta(2)],
      [82], [#name("李昱谆")], [#age(29)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2543*], [#delta(0)],
      [83], [#name("比安卡 梅罗苏")], [#age(19)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2543*], [#delta(50)],
      [84], [#name("李多恩")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2543*], [#delta(-7)],
      [85], [#name("木村香纯")], [#age(27)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2541*], [#delta(0)],
      [86], [#name("夏洛特 卢茨")], [#age(21)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2540*], [#delta(-16)],
      [87], [#name("傅玉")], [#age(48)], [#assoc("POR")], [#right], [#penhold], [#attack], [*2537*], [#delta(-1)],
      [88], [#name("娜塔莉亚 巴约尔")], [#age(29)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2535*], [#delta(11)],
      [89], [#name("金河英")], [#age(28)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2533*], [#delta(1)],
      [90], [#name("布里特 伊尔兰德")], [#age(32)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2533*], [#delta(1)],
      [91], [#name("金成珍")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2532*], [#delta(-37)],
      [92], [#name("松岛美空")], [#age(13)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2530*], [#delta(22)],
      [93], [#name("琳达 伯格斯特隆")], [#age(31)], [#assoc("SWE")], [#right], [#shakehand], [#defense], [*2529*], [#delta(22)],
      [94], [#name("简彤娟")], [#age(24)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2526*], [#delta(37)],
      [95], [#name("丁怡婕")], [#age(18)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2526*], [#delta(-3)],
      [96], [#name("陈忞昕")], [#age(17)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2526*], [#delta(11)],
      [97], [#name("朴佳贤")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2525*], [#delta(-4)],
      [98], [#name("莎莉 莫伊兰")], [#age(19)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2521*], [#delta(79)],
      [99], [#name("张安")], [#age(30)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2520*], [#delta(-11)],
      [100], [#name("盖娅 蒙法尔迪尼")], [#age(25)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2520*], [#delta(95)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("斯维斯蒂卡 戈什")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2517*], [#delta(-5)],
      [102], [#name("单晓娜")], [#age(43)], [#assoc("GER")], [#right], [#penhold], [#attack], [*2516*], [#delta(-7)],
      [103], [#name("杨晓欣")], [#age(38)], [#assoc("MON")], [#right], [#shakehand], [#attack], [*2513*], [#delta(19)],
      [104], [#name("祝启慧")], [#age(14)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2511*], [#delta(-4)],
      [105], [#name("姚睿轩")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2509*], [#delta(-11)],
      [106], [#name("巫嘉恩")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2508*], [#delta(-5)],
      [107], [#name("竹谷美凉")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2506*], [#delta(-29)],
      [108], [#name("倪夏莲")], [#age(63)], [#assoc("LUX")], [#left], [#penhold], [#attack], [*2505*], [#delta(-24)],
      [109], [#name("萨比娜 苏尔扬")], [#age(26)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2498*], [#delta(39)],
      [110], [#name("佐久间结生")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2497*], [#delta(-5)],
      [111], [#name("刘叡潾")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2493*], [#delta(107)],
      [112], [#name("邵杰妮")], [#age(32)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2493*], [#delta(-9)],
      [113], [#name("普利蒂卡 帕瓦德")], [#age(22)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2493*], [#delta(-3)],
      [114], [#name("闫禹橦")], [#age(18)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2490*], [#delta(36)],
      [115], [#name("姜依依")], [#age(16)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2486*], [#delta(58)],
      [116], [#name("奥黛丽 扎里夫")], [#age(28)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2485*], [#delta(81)],
      [117], [#name("黄愉偼")], [#age(23)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2485*], [#delta(-45)],
      [118], [#name("麻生丽名")], [#age(24)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2478*], [#delta(0)],
      [119], [#name("亚沙斯维尼 戈尔帕德")], [#age(22)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2478*], [#delta(75)],
      [120], [#name("李承垠")], [#age(19)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2475*], [#delta(1)],
      [121], [#name("伊莎贝拉 卢普列斯库")], [#age(27)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2474*], [#delta(8)],
      [122], [#name("苏蒂尔塔 穆克吉")], [#age(31)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2471*], [#delta(-35)],
      [123], [#name("蔡昀恩")], [#age(22)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2470*], [#delta(-3)],
      [124], [#name("舒麟茜")], [#age(20)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2469*], [#delta(11)],
      [125], [#name("汉娜 马特洛娃")], [#age(36)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2469*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("迪亚 奇塔莱")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2469*], [#delta(-29)],
      [127], [#name("玛丽亚 泰拉科娃")], [#age(25)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2467*], [#delta(-3)],
      [128], [#name("村松心菜")], [#age(14)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2467*], [#delta(-20)],
      [129], [#name("万远")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2466*], [#delta(9)],
      [130], [#name("克里斯蒂娜 卡尔伯格")], [#age(26)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2465*], [#delta(-26)],
      [131], [#name("李多恩")], [#age(24)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2464*], [#delta(-1)],
      [132], [#name("卡米耶 卢茨")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2464*], [#delta(-51)],
      [133], [#name("朱成竹")], [#age(29)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2463*], [#delta(11)],
      [134], [#name("何天天")], [#age(28)], [#assoc("ENG")], [#right], [#penhold], [#attack], [*2462*], [#delta(-9)],
      [135], [#name("帕察拉蓬 旺拉空")], [#age(19)], [#assoc("THA")], [#right], [#shakehand], [#defense], [*2460*], [#delta(91)],
      [136], [#name("阿迪娜 迪亚科努")], [#age(27)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2459*], [#delta(4)],
      [137], [#name("郭铮")], [#age(16)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2456*], [#delta(27)],
      [138], [#name("张墨")], [#age(37)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2456*], [#delta(-25)],
      [139], [#name("胡一")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2456*], [#delta(-33)],
      [140], [#name("许玴玪")], [#age(16)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2453*], [#delta(-4)],
      [141], [#name("瓦列里娅 谢尔巴特赫")], [#age(28)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2447*], [#delta(-4)],
      [142], [#name("安娜 布日斯卡")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2446*], [#delta(-10)],
      [143], [#name("SINGEORZAN Ioana")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2445*], [#delta(80)],
      [144], [#name("苏珊娜 维尔戈斯")], [#age(21)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2444*], [#delta(-5)],
      [145], [#name("TEE Ai Xin")], [#age(25)], [#assoc("MAS")], [#right], [#penhold], [#attack], [*2444*], [#delta(-3)],
      [146], [#name("弗拉达 沃罗宁娜")], [#age(22)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2443*], [#delta(-3)],
      [147], [#name("艾希卡 穆克吉")], [#age(29)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2442*], [#delta(-20)],
      [148], [#name("郑先知")], [#age(33)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2441*], [#delta(-3)],
      [149], [#name("金谞润")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2441*], [#delta(-3)],
      [150], [#name("陈昭澐")], [#age(21)], [#assoc("SGP")], [#right], [#shakehand], [#defense], [*2438*], [#delta(-27)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("塔蒂亚娜 库库尔科娃")], [#age(26)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2438*], [#delta(-17)],
      [152], [#name("刘子菱")], [#age(15)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2437*], [#delta(44)],
      [153], [#name("埃杰 哈拉奇")], [#age(24)], [#assoc("TUR")], [#right], [#shakehand], [#attack], [*2435*], [#delta(50)],
      [154], [#name("林依诺")], [#age(30)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2434*], [#delta(-45)],
      [155], [#name("石田心美")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2431*], [#delta(-43)],
      [156], [#name("陈佳宜")], [#age(20)], [#assoc("TPE")], [#right], [#shakehand], [#defense], [*2430*], [#delta(0)],
      [157], [#name("莱娜 霍查特")], [#age(18)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2428*], [#delta(-3)],
      [158], [#name("黄禹乔")], [#age(30)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2426*], [#delta(0)],
      [159], [#name("莱娅 拉科瓦奇")], [#age(30)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2425*], [#delta(-43)],
      [160], [#name("瓜生日咲")], [#age(15)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2420*], [#delta(-1)],
      [161], [#name("迪维扬希 布霍米克")], [#age(16)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2419*], [#delta(-10)],
      [162], [#name("吴咏琳")], [#age(23)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2418*], [#delta(-51)],
      [163], [#name("陈琦媗")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2417*], [#delta(-1)],
      [164], [#name("卡塔日娜 文格任")], [#age(25)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2416*], [#delta(-62)],
      [165], [#name("柳是宇")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2416*], [#delta(-2)],
      [166], [#name("乔治娜 波塔")], [#age(41)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2415*], [#delta(-1)],
      [167], [#name("MATIUNINA Veronika")], [#age(20)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2413*], [#delta(-20)],
      [168], [#name("金珉舒")], [#age(16)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2413*], [#delta(-11)],
      [169], [#name("卞瑞英")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2412*], [#delta(-2)],
      [170], [#name("特蒂亚娜 比连科")], [#age(43)], [#assoc("UKR")], [#right], [#shakehand], [#defense], [*2410*], [#delta(-1)],
      [171], [#name("哈娜 阿拉波维奇")], [#age(22)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2407*], [#delta(-19)],
      [172], [#name("郑艺仁")], [#age(18)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2406*], [#delta(-2)],
      [173], [#name("COK Isa")], [#age(24)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2404*], [#delta(32)],
      [174], [#name("波琳 沙斯兰")], [#age(29)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2402*], [#delta(-3)],
      [175], [#name("张璇")], [#age(27)], [#assoc("ESP")], [#left], [#shakehand], [#attack], [*2401*], [#delta(-7)],
    )
  )
#pagebreak()

#figure(
  caption: "Women's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("塔尼娅 普莱安")], [#age(25)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2399*], [#delta(-1)],
      [177], [#name("WU Ying Syuan")], [#age(17)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2398*], [#delta(-24)],
      [178], [#name("莎拉 德努特")], [#age(34)], [#assoc("LUX")], [#right], [#shakehand], [#attack], [*2398*], [#delta(-17)],
      [179], [#name("CHANG Li Sian Alice")], [#age(26)], [#assoc("MAS")], [#right], [#shakehand], [#defense], [*2398*], [#delta(-7)],
      [180], [#name("WEI Jingming")], [#age(17)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2397*], [NEW],
      [181], [#name("黄怡桦")], [#age(42)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2391*], [#delta(-7)],
      [182], [#name("阿努莎 库通巴莱")], [#age(24)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2389*], [#delta(-6)],
      [183], [#name("弗兰琪斯卡 施莱纳")], [#age(25)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2389*], [#delta(29)],
      [184], [#name("ITAGAKI Koharu")], [#age(16)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2387*], [#delta(-24)],
      [185], [#name("赵王琪")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2385*], [#delta(-6)],
      [186], [#name("马泰娅 耶格尔")], [#age(31)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2383*], [#delta(-4)],
      [187], [#name("GUO Jiangshan")], [#age(27)], [#assoc("USA")], [#right], [#shakehand], [#attack], [*2381*], [#delta(-4)],
      [188], [#name("MEN Shuohan")], [#age(26)], [#assoc("NED")], [#right], [#shakehand], [#attack], [*2381*], [#delta(14)],
      [189], [#name("埃列娜 扎哈里亚")], [#age(22)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2380*], [#delta(-70)],
      [190], [#name("李时温")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2380*], [#delta(-41)],
      [191], [#name("黎明映")], [#age(16)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2377*], [#delta(-36)],
      [192], [#name("艾卡特里尼 托利乌")], [#age(31)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2376*], [#delta(-6)],
      [193], [#name("伊万娜 马洛巴比奇")], [#age(46)], [#assoc("CRO")], [#right], [#shakehand], [#defense], [*2375*], [#delta(-13)],
      [194], [#name("TOFANT Ana")], [#age(27)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2374*], [#delta(56)],
      [195], [#name("杨惠泽")], [#age(16)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2373*], [#delta(-7)],
      [196], [#name("萨娅莉 瓦尼")], [#age(20)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2372*], [#delta(-55)],
      [197], [#name("蒂娜 梅谢芙")], [#age(32)], [#assoc("EGY")], [#left], [#shakehand], [#attack], [*2371*], [#delta(-19)],
      [198], [#name("MAKSUTI Aneta")], [#age(31)], [#assoc("SRB")], [#right], [#shakehand], [#attack], [*2370*], [#delta(-9)],
      [199], [#name("GRIESEL Mia")], [#age(20)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2370*], [#delta(-9)],
      [200], [#name("VIJITVIRIYAGUL Kulapassr")], [#age(16)], [#assoc("THA")], [#right], [#shakehand], [#defense], [*2369*], [#delta(80)],
    )
  )
