#import "../../template_CN.typ": *
#set text(font: ("Microsoft YaHei"))

#figure(
  caption: "Men's Singles (1 - 25)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [1], [#name("王皓")], [#age(24)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*3025*], [#delta(3)],
      [2], [#name("王励勤")], [#age(29)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2981*], [#delta(-1)],
      [3], [#name("马龙")], [#age(19)], [#assoc("CHN")], [#right], [#shakehand], [#attack], [*2973*], [#delta(0)],
      [4], [#name("马琳")], [#age(27)], [#assoc("CHN")], [#right], [#penhold], [#attack], [*2880*], [#delta(-2)],
      [5], [#name("郝帅")], [#age(24)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2794*], [#delta(1)],
      [6], [#name("吴尚垠")], [#age(30)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2789*], [#delta(7)],
      [7], [#name("佐兰 普里莫拉克")], [#age(38)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2781*], [#delta(68)],
      [8], [#name("柳承敏")], [#age(25)], [#assoc("KOR")], [#right], [#penhold], [#attack], [*2780*], [#delta(-3)],
      [9], [#name("卡林尼科斯 格林卡")], [#age(35)], [#assoc("GRE")], [#right], [#shakehand], [#attack], [*2776*], [#delta(-1)],
      [10], [#name("朱世赫")], [#age(27)], [#assoc("KOR")], [#right], [#shakehand], [#defense], [*2772*], [#delta(-3)],
      [11], [#name("侯英超")], [#age(27)], [#assoc("CHN")], [#right], [#shakehand], [#defense], [*2769*], [#delta(-1)],
      [12], [#name("弗拉基米尔 萨姆索诺夫")], [#age(31)], [#assoc("BLR")], [#right], [#shakehand], [#attack], [*2760*], [#delta(-1)],
      [13], [#name("蒂姆 波尔")], [#age(26)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2750*], [#delta(-1)],
      [14], [#name("迪米特里 奥恰洛夫")], [#age(19)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2728*], [#delta(26)],
      [15], [#name("陈玘")], [#age(23)], [#assoc("CHN")], [#left], [#shakehand], [#attack], [*2727*], [#delta(-6)],
      [16], [#name("孔令辉")], [#age(32)], [#assoc("CHN")], [?], [?], [?], [*2711*], [#delta(-2)],
      [17], [#name("维尔纳 施拉格")], [#age(35)], [#assoc("AUT")], [?], [?], [?], [*2691*], [#delta(17)],
      [18], [#name("李静")], [#age(32)], [#assoc("HKG")], [?], [?], [?], [*2647*], [#delta(23)],
      [19], [#name("谭瑞午")], [#age(24)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2641*], [#delta(1)],
      [20], [#name("庄智渊")], [#age(26)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2637*], [#delta(-2)],
      [21], [#name("约尔根 佩尔森")], [#age(41)], [#assoc("SWE")], [?], [?], [?], [*2633*], [#delta(41)],
      [22], [#name("唐鹏")], [#age(26)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2629*], [#delta(11)],
      [23], [#name("亚诺什 雅各布")], [#age(21)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2625*], [#delta(0)],
      [24], [#name("陈卫星")], [#age(35)], [#assoc("AUT")], [#right], [#shakehand], [#defense], [*2623*], [#delta(0)],
      [25], [#name("梁柱恩")], [#age(28)], [#assoc("HKG")], [#right], [#penhold], [#attack], [*2615*], [#delta(0)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (26 - 50)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [26], [#name("SAIVE Philippe")], [#age(36)], [#assoc("BEL")], [?], [?], [?], [*2609*], [#delta(0)],
      [27], [#name("巴斯蒂安 斯特格")], [#age(26)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2604*], [#delta(0)],
      [28], [#name("高宁")], [#age(25)], [#assoc("SGP")], [#right], [#shakehand], [#attack], [*2588*], [#delta(0)],
      [29], [#name("杨子")], [#age(23)], [#assoc("SGP")], [#left], [#shakehand], [#attack], [*2588*], [#delta(25)],
      [30], [#name("韩阳")], [#age(29)], [#assoc("JPN")], [?], [?], [?], [*2580*], [#delta(-8)],
      [31], [#name("克里斯蒂安 苏斯")], [#age(22)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2574*], [#delta(-15)],
      [32], [#name("博扬 托基奇")], [#age(26)], [#assoc("SLO")], [#right], [#shakehand], [#attack], [*2565*], [#delta(-2)],
      [33], [#name("帕纳吉奥迪斯 吉奥尼斯")], [#age(27)], [#assoc("GRE")], [#right], [#shakehand], [#defense], [*2563*], [#delta(-2)],
      [34], [#name("VYBORNY Richard")], [#age(36)], [#assoc("CZE")], [?], [?], [?], [*2562*], [#delta(-2)],
      [35], [#name("蒋澎龙")], [#age(31)], [#assoc("TPE")], [?], [?], [?], [*2558*], [#delta(25)],
      [36], [#name("让 米歇尔 塞弗")], [#age(38)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2556*], [#delta(0)],
      [37], [#name("米凯尔 梅兹")], [#age(26)], [#assoc("DEN")], [#left], [#shakehand], [#attack], [*2552*], [#delta(29)],
      [38], [#name("李正三")], [#age(23)], [#assoc("KOR")], [?], [?], [?], [*2547*], [#delta(-23)],
      [39], [#name("金赫峰")], [#age(22)], [#assoc("PRK")], [#right], [#shakehand], [#attack], [*2538*], [#delta(-2)],
      [40], [#name("卢兹扬 布拉斯奇克")], [#age(33)], [#assoc("POL")], [?], [?], [?], [*2537*], [#delta(-2)],
      [41], [#name("李廷佑")], [#age(23)], [#assoc("KOR")], [#left], [#penhold], [#attack], [*2535*], [#delta(-22)],
      [42], [#name("高礼泽")], [#age(31)], [#assoc("HKG")], [#right], [#shakehand], [#attack], [*2534*], [#delta(15)],
      [43], [#name("林聚")], [#age(28)], [#assoc("DOM")], [?], [?], [?], [*2525*], [#delta(-4)],
      [44], [#name("尹在荣")], [#age(24)], [#assoc("KOR")], [?], [?], [?], [*2522*], [#delta(5)],
      [45], [#name("帕特里克 奇拉")], [#age(38)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2519*], [#delta(-3)],
      [46], [#name("刘松")], [#age(35)], [#assoc("ARG")], [?], [?], [?], [*2516*], [#delta(0)],
      [47], [#name("塞贡 托里奥拉")], [#age(33)], [#assoc("NGR")], [#right], [#shakehand], [#attack], [*2515*], [#delta(0)],
      [48], [#name("岸川圣也")], [#age(20)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2515*], [#delta(8)],
      [49], [#name("赵彦来")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2515*], [#delta(76)],
      [50], [#name("安德烈 菲利蒙")], [#age(30)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2495*], [#delta(1)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (51 - 75)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [51], [#name("MAZUNOV Dmitry")], [#age(36)], [#assoc("RUS")], [?], [?], [?], [*2493*], [#delta(2)],
      [52], [#name("何志文")], [#age(45)], [#assoc("ESP")], [#left], [#penhold], [#attack], [*2490*], [#delta(-31)],
      [53], [#name("蒂亚戈 蒙泰罗")], [#age(26)], [#assoc("BRA")], [#right], [#shakehand], [#attack], [*2489*], [#delta(56)],
      [54], [#name("江宏杰")], [#age(18)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2487*], [#delta(40)],
      [55], [#name("江天一")], [#age(19)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2485*], [#delta(-20)],
      [56], [#name("彼得 科贝尔")], [#age(36)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2482*], [#delta(16)],
      [57], [#name("阿列克谢 斯米尔诺夫")], [#age(30)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2477*], [#delta(10)],
      [58], [#name("阿德里安 克里桑")], [#age(27)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2476*], [#delta(0)],
      [59], [#name("托本 沃西克")], [#age(34)], [#assoc("GER")], [?], [?], [?], [*2472*], [#delta(0)],
      [60], [#name("达米安 埃洛伊")], [#age(38)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2467*], [#delta(28)],
      [61], [#name("李平")], [#age(21)], [#assoc("QAT")], [#right], [#shakehand], [#attack], [*2466*], [#delta(0)],
      [62], [#name("克里斯托夫 勒古")], [#age(34)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2463*], [#delta(-45)],
      [63], [#name("詹斯 伦德奎斯特")], [#age(28)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2458*], [#delta(50)],
      [64], [#name("罗科 托西奇")], [#age(28)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2453*], [#delta(-1)],
      [65], [#name("WANG Jianfeng")], [#age(41)], [#assoc("NOR")], [#right], [#penhold], [#attack], [*2452*], [#delta(-1)],
      [66], [#name("帕尔 格雷尔")], [#age(25)], [#assoc("SWE")], [#left], [#shakehand], [#attack], [*2450*], [#delta(-1)],
      [67], [#name("TOMASI Stefano")], [#age(24)], [#assoc("ITA")], [?], [?], [?], [*2447*], [#delta(1)],
      [68], [#name("水谷隼")], [#age(18)], [#assoc("JPN")], [#left], [#shakehand], [#attack], [*2442*], [#delta(-23)],
      [69], [#name("安德烈 加奇尼")], [#age(21)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2433*], [#delta(160)],
      [70], [#name("沙拉特 阿昌塔")], [#age(25)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2428*], [#delta(120)],
      [71], [#name("托马什 帕维尔卡")], [#age(27)], [#assoc("CZE")], [?], [?], [?], [*2423*], [#delta(-2)],
      [72], [#name("HAKANSSON Fredrik")], [#age(32)], [#assoc("SWE")], [?], [?], [?], [*2417*], [#delta(-2)],
      [73], [#name("罗伯特 加尔多斯")], [#age(28)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2417*], [#delta(-29)],
      [74], [#name("松平健太")], [#age(16)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2413*], [#delta(-45)],
      [75], [#name("XU Hui")], [#age(24)], [#assoc("CHN")], [?], [?], [?], [*2397*], [#delta(-2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (76 - 100)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [76], [#name("特林科 基恩")], [#age(36)], [#assoc("NED")], [#left], [#shakehand], [#attack], [*2393*], [#delta(-28)],
      [77], [#name("张钰")], [#age(26)], [#assoc("HKG")], [#left], [#shakehand], [#attack], [*2391*], [#delta(-3)],
      [78], [#name("费奥多尔 库兹明")], [#age(24)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2389*], [#delta(-35)],
      [79], [#name("高木和卓")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2387*], [#delta(0)],
      [80], [#name("TOKIYOSHI Yuichi")], [#age(22)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2385*], [#delta(79)],
      [81], [#name("吉田海伟")], [#age(26)], [#assoc("JPN")], [#right], [#penhold], [#attack], [*2382*], [#delta(-31)],
      [82], [#name("米哈伊 博博奇卡")], [#age(21)], [#assoc("ITA")], [#right], [#shakehand], [#attack], [*2380*], [#delta(163)],
      [83], [#name("林载贤")], [#age(22)], [#assoc("KOR")], [?], [?], [?], [*2377*], [#delta(-6)],
      [84], [#name("大矢英俊")], [#age(19)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2376*], [#delta(48)],
      [85], [#name("马克斯 弗雷塔斯")], [#age(19)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2376*], [#delta(-5)],
      [86], [#name("芬 图格威尔")], [#age(31)], [#assoc("DEN")], [?], [?], [?], [*2371*], [#delta(-5)],
      [87], [#name("CHANG Yen-Shu")], [#age(28)], [#assoc("TPE")], [?], [?], [?], [*2371*], [#delta(36)],
      [88], [#name("彼得 法泽卡斯")], [#age(26)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2369*], [#delta(-5)],
      [89], [#name("卢博米尔 扬察里克")], [#age(20)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2362*], [#delta(-5)],
      [90], [#name("坂本龙介")], [#age(23)], [#assoc("JPN")], [?], [?], [?], [*2361*], [#delta(40)],
      [91], [#name("罗伯特 斯文松")], [#age(24)], [#assoc("SWE")], [?], [?], [?], [*2359*], [#delta(-6)],
      [92], [#name("金正勋")], [#age(25)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2358*], [#delta(39)],
      [93], [#name("李镇权")], [#age(20)], [#assoc("KOR")], [?], [?], [?], [*2347*], [#delta(-6)],
      [94], [#name("马丁 奥列尼克")], [#age(35)], [#assoc("CZE")], [?], [?], [?], [*2345*], [#delta(-5)],
      [95], [#name("REDJEP Ronald")], [#age(34)], [#assoc("CRO")], [#left], [#shakehand], [#attack], [*2345*], [#delta(-5)],
      [96], [#name("KUSINSKI Marcin")], [#age(36)], [#assoc("POL")], [?], [?], [?], [*2345*], [#delta(-5)],
      [97], [#name("拉尔斯 希尔舍")], [#age(28)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2337*], [#delta(-5)],
      [98], [#name("ANDRIANOV Sergei")], [#age(31)], [#assoc("RUS")], [?], [?], [?], [*2337*], [#delta(-5)],
      [99], [#name("吴志祺")], [#age(21)], [#assoc("TPE")], [#right], [#shakehand], [#attack], [*2336*], [#delta(5)],
      [100], [#name("金泰勋")], [#age(21)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2334*], [#delta(-5)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (101 - 125)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [101], [#name("若昂 蒙泰罗")], [#age(24)], [#assoc("POR")], [#left], [#shakehand], [#attack], [*2334*], [#delta(16)],
      [102], [#name("MEROTOHUN Monday")], [#age(30)], [#assoc("NGR")], [#right], [#shakehand], [#defense], [*2332*], [#delta(-6)],
      [103], [#name("LEI Zhenhua")], [#age(21)], [#assoc("CHN")], [?], [?], [?], [*2331*], [#delta(-6)],
      [104], [#name("ROSSKOPF Jorg")], [#age(38)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2329*], [#delta(-49)],
      [105], [#name("马雷克 克拉塞克")], [#age(32)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2327*], [#delta(28)],
      [106], [#name("CHMIEL Pawel")], [#age(21)], [#assoc("POL")], [?], [?], [?], [*2325*], [#delta(-7)],
      [107], [#name("亚历山大 卡拉卡谢维奇")], [#age(32)], [#assoc("SRB")], [#left], [#shakehand], [#attack], [*2319*], [#delta(53)],
      [108], [#name("HAN Jimin")], [#age(18)], [#assoc("KOR")], [?], [?], [?], [*2319*], [#delta(-7)],
      [109], [#name("费伦茨 帕西")], [#age(33)], [#assoc("HUN")], [?], [?], [?], [*2317*], [#delta(-7)],
      [110], [#name("KLEPRLIK Jakub")], [#age(21)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2314*], [#delta(-7)],
      [111], [#name("SANCHEZ Victor")], [#age(30)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2309*], [#delta(50)],
      [112], [#name("崔贤珍")], [#age(28)], [#assoc("KOR")], [?], [?], [?], [*2304*], [#delta(-12)],
      [113], [#name("雅罗斯拉夫 扎穆登科")], [#age(19)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2298*], [#delta(-8)],
      [114], [#name("SCHLICHTER Jorg")], [#age(24)], [#assoc("GER")], [?], [?], [?], [*2296*], [#delta(-8)],
      [115], [#name("康斯坦丁 乔蒂")], [#age(24)], [#assoc("ROU")], [#right], [#shakehand], [#attack], [*2293*], [#delta(-8)],
      [116], [#name("基里尔 斯卡奇科夫")], [#age(20)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2292*], [#delta(-8)],
      [117], [#name("托马斯 科涅茨尼")], [#age(22)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2288*], [#delta(-6)],
      [118], [#name("约瑟夫 普拉希")], [#age(36)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2287*], [#delta(-6)],
      [119], [#name("卢博米尔 皮斯特耶")], [#age(23)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2284*], [#delta(-5)],
      [120], [#name("叶夫根尼 齐特切蒂宁")], [#age(37)], [#assoc("BLR")], [#right], [#shakehand], [#defense], [*2283*], [#delta(-5)],
      [121], [#name("ROY Soumyadeep")], [#age(23)], [#assoc("IND")], [#right], [#shakehand], [#attack], [*2282*], [#delta(-5)],
      [122], [#name("李哲国")], [#age(22)], [#assoc("PRK")], [?], [?], [?], [*2279*], [#delta(-4)],
      [123], [#name("卡洛斯 马查多")], [#age(27)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2278*], [#delta(-4)],
      [124], [#name("JUZBASIC Ivan")], [#age(27)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2277*], [#delta(-4)],
      [125], [#name("CHO Jihoon")], [#age(23)], [#assoc("KOR")], [#right], [#shakehand], [#attack], [*2276*], [#delta(126)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (126 - 150)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [126], [#name("塞巴斯蒂安 若韦尔")], [#age(32)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2274*], [#delta(-5)],
      [127], [#name("MENDES Enio")], [#age(22)], [#assoc("POR")], [?], [?], [?], [*2271*], [#delta(-5)],
      [128], [#name("格里戈里 弗拉索夫")], [#age(23)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2270*], [#delta(-76)],
      [129], [#name("DOAN Kien Quoc")], [#age(28)], [#assoc("VIE")], [#left], [#shakehand], [#attack], [*2269*], [#delta(-5)],
      [130], [#name("AN Chol Yong")], [#age(22)], [#assoc("PRK")], [?], [?], [?], [*2263*], [#delta(-4)],
      [131], [#name("斯洛博丹 格鲁伊奇")], [#age(34)], [#assoc("SRB")], [?], [?], [?], [*2262*], [#delta(52)],
      [132], [#name("蒂亚戈 阿波罗尼亚")], [#age(21)], [#assoc("POR")], [#right], [#shakehand], [#attack], [*2261*], [#delta(-5)],
      [133], [#name("约瑟夫 西蒙契克")], [#age(27)], [#assoc("CZE")], [?], [?], [?], [*2260*], [#delta(-4)],
      [134], [#name("黄圣盛")], [#age(20)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2253*], [#delta(13)],
      [135], [#name("FILIMON Lucian")], [#age(28)], [#assoc("ROU")], [?], [?], [?], [*2244*], [#delta(-1)],
      [136], [#name("佐尔坦 费杰科内斯")], [#age(29)], [#assoc("GER")], [#right], [#shakehand], [#attack], [*2243*], [#delta(-1)],
      [137], [#name("杨敏")], [#age(44)], [#assoc("ITA")], [?], [?], [?], [*2238*], [#delta(-27)],
      [138], [#name("MONDELLO Massimiliano")], [#age(32)], [#assoc("ITA")], [?], [?], [?], [*2235*], [#delta(-2)],
      [139], [#name("马雷克 齐哈克")], [#age(33)], [#assoc("CZE")], [?], [?], [?], [*2234*], [#delta(-2)],
      [140], [#name("布里斯 奥利维耶")], [#age(25)], [#assoc("FRA")], [#right], [#shakehand], [#attack], [*2232*], [#delta(-1)],
      [141], [#name("马克 杜兰")], [#age(21)], [#assoc("ESP")], [#right], [#shakehand], [#attack], [*2231*], [#delta(-1)],
      [142], [#name("DEMETER Lehel")], [#age(29)], [#assoc("HUN")], [?], [?], [?], [*2230*], [#delta(0)],
      [143], [#name("托马斯 凯纳特")], [#age(30)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2227*], [#delta(0)],
      [144], [#name("埃尔萨伊德 拉辛")], [#age(27)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2225*], [#delta(0)],
      [145], [#name("丹尼尔 哈贝松")], [#age(21)], [#assoc("AUT")], [#right], [#shakehand], [#attack], [*2223*], [#delta(0)],
      [146], [#name("瓦西里 拉凯耶夫")], [#age(23)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2222*], [#delta(0)],
      [147], [#name("雅库布 科索夫斯基")], [#age(25)], [#assoc("POL")], [?], [?], [?], [*2218*], [#delta(1)],
      [148], [#name("PETER-PAUL Pradeeban")], [#age(30)], [#assoc("CAN")], [#right], [#shakehand], [#attack], [*2217*], [#delta(1)],
      [149], [#name("MIZUNO Yuya")], [#age(20)], [#assoc("JPN")], [?], [?], [?], [*2211*], [#delta(1)],
      [150], [#name("马克西姆 什梅廖夫")], [#age(36)], [#assoc("RUS")], [?], [?], [?], [*2210*], [#delta(-74)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (151 - 175)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [151], [#name("安德鲁 巴格利")], [#age(24)], [#assoc("ENG")], [#right], [#shakehand], [#attack], [*2208*], [#delta(0)],
      [152], [#name("张成万")], [#age(22)], [#assoc("PRK")], [?], [?], [?], [*2208*], [#delta(0)],
      [153], [#name("彼得 塞雷达")], [#age(23)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2206*], [#delta(0)],
      [154], [#name("ROBERTSON Adam")], [#age(23)], [#assoc("WAL")], [?], [?], [?], [*2206*], [#delta(8)],
      [155], [#name("丹尼尔 古拉克")], [#age(24)], [#assoc("POL")], [#right], [#shakehand], [#attack], [*2205*], [#delta(-1)],
      [156], [#name("GRIGOREV Artur")], [#age(21)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2205*], [#delta(-1)],
      [157], [#name("丹尼尔 茨维克尔")], [#age(23)], [#assoc("HUN")], [#right], [#shakehand], [#attack], [*2204*], [#delta(-1)],
      [158], [#name("马良")], [#age(16)], [#assoc("SGP")], [?], [?], [?], [*2202*], [#delta(-87)],
      [159], [#name("马丁 蒙拉德")], [#age(30)], [#assoc("DEN")], [?], [?], [?], [*2202*], [#delta(-2)],
      [160], [#name("埃里克 伊拉什")], [#age(27)], [#assoc("SVK")], [#right], [#shakehand], [#attack], [*2200*], [#delta(-2)],
      [161], [#name("CAI Xiaoli")], [#age(28)], [#assoc("SGP")], [?], [?], [?], [*2198*], [#delta(-75)],
      [162], [#name("LIU Zhongze")], [#age(19)], [#assoc("SGP")], [?], [?], [?], [*2196*], [#delta(-80)],
      [163], [#name("VOSTES Yannick")], [#age(22)], [#assoc("BEL")], [#right], [#shakehand], [#attack], [*2183*], [#delta(2)],
      [164], [#name("古斯塔沃 坪井")], [#age(22)], [#assoc("BRA")], [#left], [#shakehand], [#attack], [*2181*], [#delta(-66)],
      [165], [#name("巴托什 苏赫")], [#age(24)], [#assoc("POL")], [?], [?], [?], [*2180*], [#delta(1)],
      [166], [#name("艾哈迈德 萨利赫")], [#age(28)], [#assoc("EGY")], [#right], [#shakehand], [#attack], [*2180*], [#delta(1)],
      [167], [#name("帕特里克 鲍姆")], [#age(20)], [#assoc("GER")], [#left], [#shakehand], [#attack], [*2180*], [#delta(1)],
      [168], [#name("松平贤二")], [#age(18)], [#assoc("JPN")], [#right], [#shakehand], [#attack], [*2175*], [#delta(107)],
      [169], [#name("VITSEK Ivan")], [#age(38)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2173*], [#delta(0)],
      [170], [#name("艾曼纽 莱贝松")], [#age(19)], [#assoc("FRA")], [#left], [#shakehand], [#attack], [*2172*], [#delta(0)],
      [171], [#name("ZHANG Wilson")], [#age(28)], [#assoc("CAN")], [?], [?], [?], [*2168*], [#delta(1)],
      [172], [#name("阿列克谢 利文佐夫")], [#age(26)], [#assoc("RUS")], [#right], [#shakehand], [#attack], [*2162*], [#delta(-34)],
      [173], [#name("HU Bin")], [#age(25)], [#assoc("CGO")], [?], [?], [?], [*2157*], [#delta(0)],
      [174], [#name("DE SOUSA Arlindo")], [#age(32)], [#assoc("LUX")], [?], [?], [?], [*2156*], [#delta(1)],
      [175], [#name("RUMGAY Gavin")], [#age(23)], [#assoc("SCO")], [#right], [#shakehand], [#attack], [*2155*], [#delta(2)],
    )
  )
#pagebreak()

#figure(
  caption: "Men's Singles (176 - 200)",
    table(
      columns: 9,
      [\#], [运动员],[年龄], [协会],  [手], [握拍], [削球], [积分], [$Delta$],
      [176], [#name("约翰 阿克塞尔奎斯特")], [#age(22)], [#assoc("SWE")], [?], [?], [?], [*2154*], [#delta(3)],
      [177], [#name("SUGRUE Jason")], [#age(28)], [#assoc("IRL")], [?], [?], [?], [*2150*], [#delta(3)],
      [178], [#name("乔恩 佩尔森")], [#age(21)], [#assoc("SWE")], [#right], [#shakehand], [#attack], [*2150*], [#delta(3)],
      [179], [#name("赫苏斯 坎特罗")], [#age(25)], [#assoc("ESP")], [#right], [#penhold], [#attack], [*2149*], [#delta(3)],
      [180], [#name("ABRAMOV Isaak")], [#age(36)], [#assoc("ISR")], [#right], [#shakehand], [#attack], [*2135*], [#delta(5)],
      [181], [#name("王增羿")], [#age(24)], [#assoc("POL")], [#right], [#penhold], [#attack], [*2130*], [#delta(7)],
      [182], [#name("卢文 菲鲁斯")], [#age(19)], [#assoc("GER")], [#right], [#shakehand], [#defense], [*2129*], [#delta(7)],
      [183], [#name("松下浩二")], [#age(40)], [#assoc("JPN")], [#right], [?], [#defense], [*2128*], [#delta(1)],
      [184], [#name("伊日 维拉波里克")], [#age(24)], [#assoc("CZE")], [#right], [#shakehand], [#attack], [*2128*], [#delta(7)],
      [185], [#name("TSIOKAS Ntaniel")], [#age(36)], [#assoc("GRE")], [?], [?], [?], [*2127*], [#delta(8)],
      [186], [#name("KONGSGAARD Christian")], [#age(24)], [#assoc("DEN")], [?], [?], [?], [*2124*], [#delta(8)],
      [187], [#name("PAPIC Juan")], [#age(37)], [#assoc("CHI")], [?], [?], [?], [*2120*], [#delta(9)],
      [188], [#name("保罗 德林克霍尔")], [#age(17)], [#assoc("GBR")], [#right], [#shakehand], [#attack], [*2117*], [#delta(9)],
      [189], [#name("MAGYAR Laszlo")], [#age(30)], [#assoc("HUN")], [#left], [#shakehand], [#attack], [*2116*], [#delta(9)],
      [190], [#name("YOKOYAMA Yuichi")], [#age(20)], [#assoc("JPN")], [?], [?], [?], [*2112*], [#delta(9)],
      [191], [#name("KUBOTA Ryuzo")], [#age(22)], [#assoc("JPN")], [?], [?], [?], [*2112*], [#delta(-27)],
      [192], [#name("TAKAKIWA Kenichi")], [#age(23)], [#assoc("JPN")], [?], [?], [?], [*2111*], [#delta(-6)],
      [193], [#name("FENG Xiaoquan")], [#age(20)], [#assoc("AUT")], [#left], [#shakehand], [#attack], [*2110*], [#delta(7)],
      [194], [#name("塩野真人")], [#age(21)], [#assoc("JPN")], [#right], [#shakehand], [#defense], [*2109*], [#delta(-18)],
      [195], [#name("下山隆敬")], [#age(22)], [#assoc("JPN")], [?], [?], [?], [*2108*], [#delta(-21)],
      [196], [#name("托米斯拉夫 科拉雷克")], [#age(19)], [#assoc("CRO")], [#right], [#shakehand], [#attack], [*2108*], [#delta(5)],
      [197], [#name("CHRIST Nico")], [#age(26)], [#assoc("GER")], [?], [?], [?], [*2105*], [#delta(5)],
      [198], [#name("陈建安")], [#age(16)], [#assoc("TPE")], [#left], [#shakehand], [#attack], [*2104*], [#delta(-35)],
      [199], [#name("SANGUANSIN Phakpoom")], [#age(24)], [#assoc("THA")], [#right], [#shakehand], [#attack], [*2103*], [#delta(4)],
      [200], [#name("亚历山大 迪杜赫")], [#age(25)], [#assoc("UKR")], [#right], [#shakehand], [#attack], [*2103*], [#delta(4)],
    )
  )
