/* web/app.js — Table Tennis ELO Rankings (static, no dependencies)
 * Data bundles (generated by post_crawl.jl → src/web_export.jl):
 *   data/index.json            {months:["2004-01",...], generated, players}
 *   data/latest.json           {MS:[[rank,id,rating,delta,age,assoc,hand,grip,style],...], WS:[...]}
 *   data/rankings/MS-YYYY-MM.json   monthly top-200 rows (same shape)
 *   data/history/shard-XX.json {id:{m:[name,cn,sex,yob,hand,grip,style,assoc,peak,final], s:[[monthIdx,rating],...]}}
 *     (series ends with the final-rating point when it differs from the last monthly snapshot)
 *   data/search.json           [[id, name, cnName], ...]
 */
"use strict";

// ---------------------------------------------------------------- i18n
const I18N = {
  zh: {
    title: "乒乓球 ELO 积分排名",
    men: "男子单打", women: "女子单打", latest: "最新",
    rank: "#", player: "运动员", age: "年龄", assoc: "协会",
    hand: "手", grip: "握拍", style: "打法", rating: "积分", delta: "Δ",
    searchPh: "搜索球员…",
    left: "左手", right: "右手", shakehand: "横拍", penhold: "直板",
    attack: "进攻", defence: "防守", unknown: "?",
    peak: "历史最高积分", curRating: "当前积分", curRank: "当前排名",
    sex: "性别", male: "男", female: "女",
    ratingHistory: "积分历史",
    back: "← 返回排名",
    loadFail: "数据加载失败",
    notFound: "未找到该球员",
    notRanked: "—",
    newMark: "NEW",
    footer: (d, n) => `数据更新于 ${d} · ${n} 名有积分球员 · 月度快照自 2004-01 · 校正版 ELO 算法`,
  },
  en: {
    title: "Table Tennis ELO Rankings",
    men: "Men's Singles", women: "Women's Singles", latest: "Latest",
    rank: "#", player: "Player", age: "Age", assoc: "Assoc.",
    hand: "Hand", grip: "Grip", style: "Style", rating: "Rating", delta: "Δ",
    searchPh: "Search players…",
    left: "Left", right: "Right", shakehand: "Shakehand", penhold: "Penhold",
    attack: "Attack", defence: "Defence", unknown: "?",
    peak: "Peak rating", curRating: "Current rating", curRank: "Current rank",
    sex: "Sex", male: "M", female: "W",
    ratingHistory: "Rating history",
    back: "← Back to rankings",
    loadFail: "Failed to load data",
    notFound: "Player not found",
    notRanked: "—",
    newMark: "NEW",
    footer: (d, n) => `Updated ${d} · ${n} rated players · monthly snapshots since 2004-01 · modified ELO`,
  },
};
let lang = localStorage.getItem("ttr-lang") || "zh";
const t = (k) => I18N[lang][k];

const el = (id) => document.getElementById(id);
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

// ---------------------------------------------------------------- data
const cache = {};
function fetchJSON(url) {
  if (!cache[url]) {
    cache[url] = fetch(url).then((r) => {
      if (!r.ok) throw new Error(`${r.status} ${url}`);
      return r.json();
    });
  }
  return cache[url];
}
const monthIdx = (ym) => {
  const [y, m] = ym.split("-").map(Number);
  return (y - 2004) * 12 + m - 1;
};
const idxMonth = (i) => `${2004 + Math.floor(i / 12)}-${String((i % 12) + 1).padStart(2, "0")}`;

let nameMapP = null;
function nameMap() {
  if (!nameMapP) {
    nameMapP = fetchJSON("data/search.json").then(
      (rows) => new Map(rows.map(([id, en, cn]) => [id, { en, cn }]))
    );
  }
  return nameMapP;
}
const playerName = (nm, id) => {
  const rec = nm.get(id);
  if (!rec) return `#${id}`;
  return lang === "zh" ? rec.cn : rec.en;
};
const altName = (rec) => (lang === "zh" ? rec.en : rec.cn);

function attrClass(v) {
  switch (v) {
    case "Left-Hand": case "L": return "c-left";
    case "Right-Hand": case "R": return "c-right";
    case "ShakeHand": case "S": return "c-shake";
    case "Penhold": case "P": return "c-pen";
    case "Attack": case "A": return "c-attack";
    case "Defence": case "D": return "c-defense";
    default: return "";
  }
}
function localizedAttr(v) {
  let txt;
  switch (v) {
    case "Left-Hand": case "L": txt = t("left"); break;
    case "Right-Hand": case "R": txt = t("right"); break;
    case "ShakeHand": case "S": txt = t("shakehand"); break;
    case "Penhold": case "P": txt = t("penhold"); break;
    case "Attack": case "A": txt = t("attack"); break;
    case "Defence": case "D": txt = t("defence"); break;
    default: return t("unknown");
  }
  return `<span class="${attrClass(v)}">${txt}</span>`;
}
// Age color gradient from template.typ: green (young) → yellow → red (old).
function ageColor(n) {
  if (typeof n !== "number") return "";
  let r, g;
  if (n <= 12) { r = 0x40; g = 0xb0 + 4 * (12 - n); }
  else if (n <= 26) { r = 0x40 + 8 * (n - 12); g = 0xb0; }
  else if (n <= 40) { r = 0xb0; g = 0xb0 - 8 * (n - 26); }
  else { r = 0xb0 + 2 * (n - 40); g = 0x40 - 2 * (n - 40); }
  r = Math.max(0, Math.min(255, r));
  g = Math.max(0, Math.min(255, g));
  return `rgb(${r},${g},0)`;
}
function deltaHTML(d) {
  if (d === "NEW") return `<span class="delta-new">${t("newMark")}</span>`;
  if (typeof d !== "number" || d === 0) return `<span class="delta-flat">-</span>`;
  return d > 0
    ? `<span class="delta-up">▲${d}</span>`
    : `<span class="delta-down">▼${-d}</span>`;
}
function flagImg(assoc) {
  return `<img class="flag" src="data/flags/${esc(assoc)}.png" alt="" onerror="this.style.visibility='hidden'">`;
}

// ---------------------------------------------------------------- router
function parseRoute() {
  const parts = location.hash.replace(/^#\/?/, "").split("/").filter(Boolean);
  if (parts[0] === "player" && parts[1]) return { view: "player", id: parts[1] };
  if (parts[0] === "MS" || parts[0] === "WS")
    return { view: "ranking", gender: parts[0], month: parts[1] || "latest" };
  return { view: "ranking", gender: "MS", month: "latest" };
}

async function render() {
  closeSearch();
  const r = parseRoute();
  try {
    if (r.view === "player") await renderPlayer(r.id);
    else await renderRanking(r.gender, r.month);
  } catch (e) {
    console.error(e);
    el("app").innerHTML = `<div class="error">${t("loadFail")}</div>`;
  }
  renderFooter();
}

// ---------------------------------------------------------------- ranking
async function renderRanking(gender, month) {
  const app = el("app");
  app.innerHTML = `<div class="loading">Loading…</div>`;

  const idx = await fetchJSON("data/index.json");
  const months = idx.months; // ascending
  const isLatest = month === "latest" || !months.includes(month);
  const curMonth = isLatest ? "latest" : month;

  let rows;
  if (isLatest) rows = (await fetchJSON("data/latest.json"))[gender];
  else rows = await fetchJSON(`data/rankings/${gender}-${curMonth}.json`);

  const nm = await nameMap();

  // month navigation (timeline slider + big side buttons)
  const mi = isLatest ? months.length : months.indexOf(curMonth); // virtual index
  const prevTarget = mi > 0 ? months[mi - 1] : null;
  const nextTarget = !isLatest && mi < months.length - 1 ? months[mi + 1] : (!isLatest ? "latest" : null);
  const lastMonth = months[months.length - 1];
  const monthLabel = (v) => v >= months.length ? `${t("latest")} (${lastMonth})` : months[v];

  // remember where "back to rankings" should return to
  sessionStorage.setItem("ttr-back", `#/${gender}/${curMonth}`);

  const tableRows = rows.map((r) => {
    const [rank, id, rating, delta, age, assoc, hand, grip, style] = r;
    return `<tr>
      <td class="num">${rank}</td>
      <td><a class="player-link" href="#/player/${id}">${esc(playerName(nm, id))}</a></td>
      <td class="num age"${typeof age === "number" ? ` style="color:${ageColor(age)}"` : ""}>${age || "?"}</td>
      <td>${flagImg(assoc)}<span class="assoc">${esc(assoc)}</span></td>
      <td>${localizedAttr(hand)}</td>
      <td>${localizedAttr(grip)}</td>
      <td>${localizedAttr(style)}</td>
      <td class="num rating">${rating}</td>
      <td class="num">${deltaHTML(delta)}</td>
    </tr>`;
  }).join("");

  app.innerHTML = `
    <div class="card toolbar">
      <div class="tabs">
        <button class="tab${gender === "MS" ? " active" : ""}" data-g="MS">${t("men")}</button>
        <button class="tab${gender === "WS" ? " active" : ""}" data-g="WS">${t("women")}</button>
      </div>
      <div class="timeline">
        <input type="range" id="month-range" min="0" max="${months.length}" step="1" value="${mi}">
        <div class="timeline-scale">
          <span>${months[0]}</span>
          <span class="tl-cur" id="tl-cur">${monthLabel(mi)}</span>
          <span>${t("latest")}</span>
        </div>
      </div>
    </div>
    <div class="ranking-wrap">
      <button class="side-nav" id="prev-month" ${prevTarget ? "" : "disabled"} title="${prevTarget || ""}"><span>‹</span></button>
      <div class="card table-card">
        <table class="ranking">
          <thead><tr>
            <th class="num">${t("rank")}</th><th>${t("player")}</th><th class="num">${t("age")}</th>
            <th>${t("assoc")}</th><th>${t("hand")}</th><th>${t("grip")}</th><th>${t("style")}</th>
            <th class="num">${t("rating")}</th><th class="num">${t("delta")}</th>
          </tr></thead>
          <tbody>${tableRows}</tbody>
        </table>
      </div>
      <button class="side-nav" id="next-month" ${nextTarget ? "" : "disabled"} title="${nextTarget === "latest" ? t("latest") : (nextTarget || "")}"><span>›</span></button>
    </div>`;

  app.querySelectorAll(".tab").forEach((b) =>
    b.addEventListener("click", () => { location.hash = `#/${b.dataset.g}/${curMonth}`; }));
  const range = el("month-range"), tlCur = el("tl-cur");
  range.addEventListener("input", () => { tlCur.textContent = monthLabel(Number(range.value)); });
  range.addEventListener("change", () => {
    const v = Number(range.value);
    const target = v >= months.length ? "latest" : months[v];
    if (target !== curMonth) location.hash = `#/${gender}/${target}`;
  });
  if (prevTarget) el("prev-month").addEventListener("click", () => { location.hash = `#/${gender}/${prevTarget}`; });
  if (nextTarget) el("next-month").addEventListener("click", () => { location.hash = `#/${gender}/${nextTarget}`; });
}

// ---------------------------------------------------------------- player
async function renderPlayer(id) {
  const app = el("app");
  app.innerHTML = `<div class="loading">Loading…</div>`;

  const shard = String(Number(id) % 64).padStart(2, "0");
  const data = await fetchJSON(`data/history/shard-${shard}.json`);
  const p = data[id];
  if (!p) { app.innerHTML = `<div class="error">${t("notFound")}</div>`; return; }

  const [name, cn, sex, yob, hand, grip, style, assoc, peak, final] = p.m;
  const series = p.s;
  const rec = { en: name, cn };

  // current rating & rank (from latest full ranking; retired players fall back
  // to their final rating from the shard meta)
  let curRating = t("notRanked"), curRank = t("notRanked");
  try {
    const latest = await fetchJSON("data/latest.json");
    const hit = latest[sex === "M" ? "MS" : "WS"].find((r) => r[1] === Number(id));
    if (hit) { curRank = hit[0]; curRating = hit[2]; }
    else if (typeof final === "number") { curRating = final; }
  } catch (_) { /* offline tolerance */ }

  const idx = await fetchJSON("data/index.json");
  const latestMi = monthIdx(idx.months[idx.months.length - 1]);
  const age = yob ? new Date().getFullYear() - yob : "?";
  const ageStyle = typeof age === "number" ? ` style="color:${ageColor(age)}"` : "";

  app.innerHTML = `
    <div class="card">
      <a class="back-link" href="${sessionStorage.getItem("ttr-back") || "#/"}">${t("back")}</a>
      <div class="player-head" style="margin-top:8px">
        <h2>${esc(lang === "zh" ? cn : name)}</h2>
        <span class="alt-name">${esc(altName(rec))}</span>
        <span>${flagImg(assoc)}<span class="assoc">${esc(assoc)}</span></span>
      </div>
      <div class="meta-grid">
        <div class="meta-item"><div class="k">${t("sex")}</div><div class="v">${sex === "M" ? t("male") : t("female")}</div></div>
        <div class="meta-item"><div class="k">${t("age")}</div><div class="v"${ageStyle}>${age}</div></div>
        <div class="meta-item"><div class="k">${t("hand")}</div><div class="v">${localizedAttr(hand)}</div></div>
        <div class="meta-item"><div class="k">${t("grip")}</div><div class="v">${localizedAttr(grip)}</div></div>
        <div class="meta-item"><div class="k">${t("style")}</div><div class="v">${localizedAttr(style)}</div></div>
        <div class="meta-item"><div class="k">${t("curRating")}</div><div class="v">${curRating}</div></div>
        <div class="meta-item"><div class="k">${t("curRank")}</div><div class="v">${curRank}</div></div>
        <div class="meta-item"><div class="k">${t("peak")}</div><div class="v">${peak}</div></div>
      </div>
    </div>
    <div class="card">
      <div class="chart-title">${t("ratingHistory")}</div>
      <div id="chart-container"></div>
    </div>`;

  drawChart(el("chart-container"), series, latestMi);
}

// ---------------------------------------------------------------- chart
function drawChart(container, series, latestMi) {
  if (!series.length) { container.innerHTML = ""; return; }
  const W = 920, H = 320, padL = 52, padR = 16, padT = 14, padB = 32;
  const xs = series.map((p) => p[0]);
  const ys = series.map((p) => p[1]);
  const x0 = Math.min(...xs);
  const x1 = Math.max(latestMi, Math.max(...xs));
  const yMin = Math.min(...ys), yMax = Math.max(...ys);
  const y0 = Math.floor((yMin - 60) / 100) * 100;
  const y1 = Math.ceil((yMax + 60) / 100) * 100;
  const X = (mi) => padL + ((W - padL - padR) * (mi - x0)) / Math.max(1, x1 - x0);
  const Y = (r) => padT + (H - padT - padB) * (1 - (r - y0) / (y1 - y0));

  let s = `<svg width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" font-family="inherit">`;

  // y grid every 200
  for (let r = Math.ceil(y0 / 200) * 200; r <= y1; r += 200) {
    s += `<line x1="${padL}" y1="${Y(r)}" x2="${W - padR}" y2="${Y(r)}" stroke="#e5e7eb"/>`;
    s += `<text x="${padL - 6}" y="${Y(r) + 4}" text-anchor="end" font-size="11" fill="#6b7280">${r}</text>`;
  }
  // x ticks every 24 months
  for (let mi = Math.ceil(x0 / 24) * 24; mi <= x1; mi += 24) {
    s += `<line x1="${X(mi)}" y1="${H - padB}" x2="${X(mi)}" y2="${H - padB + 4}" stroke="#9ca3af"/>`;
    s += `<text x="${X(mi)}" y="${H - padB + 16}" text-anchor="middle" font-size="11" fill="#6b7280">${2004 + Math.floor(mi / 12)}</text>`;
  }
  // axes
  s += `<line x1="${padL}" y1="${padT}" x2="${padL}" y2="${H - padB}" stroke="#9ca3af"/>`;
  s += `<line x1="${padL}" y1="${H - padB}" x2="${W - padR}" y2="${H - padB}" stroke="#9ca3af"/>`;

  // series polyline
  const pts = series.map(([mi, r]) => `${X(mi).toFixed(1)},${Y(r).toFixed(1)}`).join(" ");
  s += `<polyline points="${pts}" fill="none" stroke="#1a5fb4" stroke-width="2"/>`;

  // dashed flat extension to latest month
  const [lastMi, lastR] = series[series.length - 1];
  if (lastMi < x1) {
    s += `<line x1="${X(lastMi)}" y1="${Y(lastR)}" x2="${X(x1)}" y2="${Y(lastR)}" stroke="#1a5fb4" stroke-width="1.5" stroke-dasharray="4 3" opacity=".6"/>`;
  }
  // last point marker
  s += `<circle cx="${X(lastMi)}" cy="${Y(lastR)}" r="3.5" fill="#1a5fb4"/>`;
  s += `<text x="${Math.min(X(lastMi) + 6, W - padR - 40)}" y="${Y(lastR) - 6}" font-size="12" fill="#1a5fb4" font-weight="600">${lastR}</text>`;

  s += `</svg>`;
  container.innerHTML = s;
}

// ---------------------------------------------------------------- search
const si = el("search-input"), sr = el("search-results");
function closeSearch() { sr.classList.add("hidden"); }

async function onSearch() {
  const q = si.value.trim().toLowerCase();
  if (!q) { closeSearch(); return; }
  const rows = await fetchJSON("data/search.json");
  const hits = rows
    .filter(([, en, cn]) => en.toLowerCase().includes(q) || cn.toLowerCase().includes(q))
    .slice(0, 15);
  sr.innerHTML = hits.length
    ? hits.map(([id, en, cn]) =>
        `<div class="search-item" data-id="${id}"><span>${esc(en)}</span><span class="cn">${esc(cn)}</span></div>`).join("")
    : `<div class="search-item">—</div>`;
  sr.classList.remove("hidden");
  sr.querySelectorAll(".search-item[data-id]").forEach((d) =>
    d.addEventListener("mousedown", () => {
      location.hash = `#/player/${d.dataset.id}`;
      si.value = "";
      closeSearch();
    }));
}
si.addEventListener("input", onSearch);
si.addEventListener("focus", onSearch);
document.addEventListener("click", (e) => {
  if (!e.target.closest(".search-box")) closeSearch();
});

// ---------------------------------------------------------------- chrome
function applyLang() {
  document.documentElement.lang = lang === "zh" ? "zh-CN" : "en";
  el("ui-title").textContent = t("title");
  el("lang-toggle").textContent = lang === "zh" ? "EN" : "中文";
  si.placeholder = t("searchPh");
  document.title = lang === "zh"
    ? "乒乓球 ELO 积分排名"
    : "Table Tennis ELO Rankings";
}
el("lang-toggle").addEventListener("click", () => {
  lang = lang === "zh" ? "en" : "zh";
  localStorage.setItem("ttr-lang", lang);
  applyLang();
  render();
});

async function renderFooter() {
  try {
    const idx = await fetchJSON("data/index.json");
    el("footer").textContent = t("footer")(idx.generated, idx.players);
  } catch (_) { /* ignore */ }
}

applyLang();
window.addEventListener("hashchange", render);
render();
