/* web/app.js — Table Tennis ELO Rankings (static, no dependencies)
 * Data bundles (generated by post_crawl.jl → src/web_export.jl):
 *   data/index.json            {months:["2004-01",...], generated, players}
 *   data/latest.json           {MS:[[rank,id,rating,delta,age,assoc,hand,grip,style],...], WS:[...]}
 *   data/rankings/MS-YYYY-MM.json   monthly top-200 rows (same shape)
 *   data/history/shard-XX.json {id:{m:[name,cn,sex,yob,hand,grip,style,assoc,peak,final], s:[[monthIdx,rating],...]}}
 *     (series ends with the final-rating point when it differs from the last monthly snapshot)
 *   data/search.json           [[id, name, cnName], ...]
 */
"use strict";

// ---------------------------------------------------------------- i18n
const I18N = {
  zh: {
    title: "乒乓球 ELO 积分排名",
    men: "男子单打", women: "女子单打", latest: "最新",
    rank: "#", player: "运动员", age: "年龄", assoc: "协会",
    hand: "手", grip: "握拍", style: "打法", rating: "积分", delta: "Δ",
    searchPh: "搜索球员…",
    left: "左手", right: "右手", shakehand: "横拍", penhold: "直板",
    attack: "进攻", defence: "防守", unknown: "?",
    peak: "历史最高积分", curRating: "当前积分", curRank: "当前排名",
    sex: "性别", male: "男", female: "女",
    ratingHistory: "积分历史",
    back: "← 返回排名",
    loadFail: "数据加载失败",
    notFound: "未找到该球员",
    notRanked: "—",
    newMark: "NEW",
    events: "赛事", backEvents: "← 返回赛事列表", backPlayer: "← 返回球员",
    tierMajor: "大赛", tierHigh: "高级别", tierRegular: "常规赛", tierOther: "其他",
    allTiers: "全部级别",
    podiumSF: "四强", qualList: "资格赛 / 预赛赛果", groupList: "赛果（非单败赛制）",
    eventResults: "赛事成绩", showAll: "展开全部", collapse: "收起", wo: "W/O",
    bronzeMatch: "铜牌赛", finalStage: "决赛阶段", quarter: (i) => `${i}/4区`,
    otherMatches: "其他场次（排位赛等）",
    footer: (d, n) => `数据更新于 ${d} · ${n} 名有积分球员 · 月度快照自 2004-01 · 校正版 ELO 算法`,
  },
  en: {
    title: "Table Tennis ELO Rankings",
    men: "Men's Singles", women: "Women's Singles", latest: "Latest",
    rank: "#", player: "Player", age: "Age", assoc: "Assoc.",
    hand: "Hand", grip: "Grip", style: "Style", rating: "Rating", delta: "Δ",
    searchPh: "Search players…",
    left: "Left", right: "Right", shakehand: "Shakehand", penhold: "Penhold",
    attack: "Attack", defence: "Defence", unknown: "?",
    peak: "Peak rating", curRating: "Current rating", curRank: "Current rank",
    sex: "Sex", male: "M", female: "W",
    ratingHistory: "Rating history",
    back: "← Back to rankings",
    loadFail: "Failed to load data",
    notFound: "Player not found",
    notRanked: "—",
    newMark: "NEW",
    events: "Events", backEvents: "← Back to events", backPlayer: "← Back to player",
    tierMajor: "Majors", tierHigh: "Top tier", tierRegular: "Regular", tierOther: "Other",
    allTiers: "All tiers",
    podiumSF: "SF", qualList: "Qualification / preliminary results", groupList: "Results (non-knockout format)",
    eventResults: "Event results", showAll: "Show all", collapse: "Collapse", wo: "W/O",
    bronzeMatch: "Bronze match", finalStage: "Final rounds", quarter: (i) => `Quarter ${i}`,
    otherMatches: "Other matches (placement etc.)",
    footer: (d, n) => `Updated ${d} · ${n} rated players · monthly snapshots since 2004-01 · modified ELO`,
  },
};
let lang = localStorage.getItem("ttr-lang") || "zh";
const t = (k) => I18N[lang][k];

const el = (id) => document.getElementById(id);
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

// ---------------------------------------------------------------- data
const cache = {};
function fetchJSON(url) {
  if (!cache[url]) {
    cache[url] = fetch(url).then((r) => {
      if (!r.ok) throw new Error(`${r.status} ${url}`);
      return r.json();
    });
  }
  return cache[url];
}
const monthIdx = (ym) => {
  const [y, m] = ym.split("-").map(Number);
  return (y - 2004) * 12 + m - 1;
};
const idxMonth = (i) => `${2004 + Math.floor(i / 12)}-${String((i % 12) + 1).padStart(2, "0")}`;

let nameMapP = null;
function nameMap() {
  if (!nameMapP) {
    nameMapP = fetchJSON("data/search.json").then(
      (rows) => new Map(rows.map(([id, en, cn]) => [id, { en, cn }]))
    );
  }
  return nameMapP;
}
const playerName = (nm, id) => {
  const rec = nm.get(id);
  if (!rec) return `#${id}`;
  return lang === "zh" ? rec.cn : rec.en;
};
const altName = (rec) => (lang === "zh" ? rec.en : rec.cn);

function attrClass(v) {
  switch (v) {
    case "Left-Hand": case "L": return "c-left";
    case "Right-Hand": case "R": return "c-right";
    case "ShakeHand": case "S": return "c-shake";
    case "Penhold": case "P": return "c-pen";
    case "Attack": case "A": return "c-attack";
    case "Defence": case "D": return "c-defense";
    default: return "";
  }
}
function localizedAttr(v) {
  let txt;
  switch (v) {
    case "Left-Hand": case "L": txt = t("left"); break;
    case "Right-Hand": case "R": txt = t("right"); break;
    case "ShakeHand": case "S": txt = t("shakehand"); break;
    case "Penhold": case "P": txt = t("penhold"); break;
    case "Attack": case "A": txt = t("attack"); break;
    case "Defence": case "D": txt = t("defence"); break;
    default: return t("unknown");
  }
  return `<span class="${attrClass(v)}">${txt}</span>`;
}
// Age color gradient from template.typ: green (young) → yellow → red (old).
function ageColor(n) {
  if (typeof n !== "number") return "";
  let r, g;
  if (n <= 12) { r = 0x40; g = 0xb0 + 4 * (12 - n); }
  else if (n <= 26) { r = 0x40 + 8 * (n - 12); g = 0xb0; }
  else if (n <= 40) { r = 0xb0; g = 0xb0 - 8 * (n - 26); }
  else { r = 0xb0 + 2 * (n - 40); g = 0x40 - 2 * (n - 40); }
  r = Math.max(0, Math.min(255, r));
  g = Math.max(0, Math.min(255, g));
  return `rgb(${r},${g},0)`;
}
function deltaHTML(d) {
  if (d === "NEW") return `<span class="delta-new">${t("newMark")}</span>`;
  if (typeof d !== "number" || d === 0) return `<span class="delta-flat">-</span>`;
  return d > 0
    ? `<span class="delta-up">▲${d}</span>`
    : `<span class="delta-down">▼${-d}</span>`;
}
function flagImg(assoc) {
  return `<img class="flag" src="data/flags/${esc(assoc)}.png" alt="" onerror="this.style.visibility='hidden'">`;
}

// ---------------------------------------------------------------- router
function parseRoute() {
  const parts = location.hash.replace(/^#\/?/, "").split("/").filter(Boolean);
  if (parts[0] === "player" && parts[1]) return { view: "player", id: parts[1] };
  if (parts[0] === "events") return { view: "events" };
  if (parts[0] === "event" && parts[1]) return { view: "event", id: parts[1] };
  if (parts[0] === "MS" || parts[0] === "WS")
    return { view: "ranking", gender: parts[0], month: parts[1] || "latest" };
  return { view: "ranking", gender: "MS", month: "latest" };
}

async function render() {
  closeSearch();
  const r = parseRoute();
  try {
    if (r.view === "player") await renderPlayer(r.id);
    else if (r.view === "events") await renderEvents();
    else if (r.view === "event") await renderEvent(r.id);
    else await renderRanking(r.gender, r.month);
  } catch (e) {
    console.error(e);
    el("app").innerHTML = `<div class="error">${t("loadFail")}</div>`;
  }
  renderFooter();
}

// ---------------------------------------------------------------- ranking
async function renderRanking(gender, month) {
  const app = el("app");
  app.innerHTML = `<div class="loading">Loading…</div>`;
  sessionStorage.removeItem("ttr-event-back");

  const idx = await fetchJSON("data/index.json");
  const months = idx.months; // ascending
  const isLatest = month === "latest" || !months.includes(month);
  const curMonth = isLatest ? "latest" : month;

  let rows;
  if (isLatest) rows = (await fetchJSON("data/latest.json"))[gender];
  else rows = await fetchJSON(`data/rankings/${gender}-${curMonth}.json`);

  const nm = await nameMap();

  // month navigation (timeline slider + big side buttons)
  const mi = isLatest ? months.length : months.indexOf(curMonth); // virtual index
  const prevTarget = mi > 0 ? months[mi - 1] : null;
  const nextTarget = !isLatest && mi < months.length - 1 ? months[mi + 1] : (!isLatest ? "latest" : null);
  const lastMonth = months[months.length - 1];
  const monthLabel = (v) => v >= months.length ? `${t("latest")} (${lastMonth})` : months[v];

  // remember where "back to rankings" should return to
  sessionStorage.setItem("ttr-back", `#/${gender}/${curMonth}`);

  const tableRows = rows.map((r) => {
    const [rank, id, rating, delta, age, assoc, hand, grip, style] = r;
    return `<tr>
      <td class="num">${rank}</td>
      <td><a class="player-link" href="#/player/${id}">${esc(playerName(nm, id))}</a></td>
      <td class="num age"${typeof age === "number" ? ` style="color:${ageColor(age)}"` : ""}>${age || "?"}</td>
      <td>${flagImg(assoc)}<span class="assoc">${esc(assoc)}</span></td>
      <td>${localizedAttr(hand)}</td>
      <td>${localizedAttr(grip)}</td>
      <td>${localizedAttr(style)}</td>
      <td class="num rating">${rating}</td>
      <td class="num">${deltaHTML(delta)}</td>
    </tr>`;
  }).join("");

  app.innerHTML = `
    <div class="card toolbar">
      <div class="tabs">
        <button class="tab${gender === "MS" ? " active" : ""}" data-g="MS">${t("men")}</button>
        <button class="tab${gender === "WS" ? " active" : ""}" data-g="WS">${t("women")}</button>
      </div>
      <div class="timeline">
        <input type="range" id="month-range" min="0" max="${months.length}" step="1" value="${mi}">
        <div class="timeline-scale">
          <span>${months[0]}</span>
          <span class="tl-cur" id="tl-cur">${monthLabel(mi)}</span>
          <span>${t("latest")}</span>
        </div>
      </div>
    </div>
    <div class="ranking-wrap">
      <button class="side-nav" id="prev-month" ${prevTarget ? "" : "disabled"} title="${prevTarget || ""}"><span>‹</span></button>
      <div class="card table-card">
        <table class="ranking">
          <thead><tr>
            <th class="num">${t("rank")}</th><th>${t("player")}</th><th class="num">${t("age")}</th>
            <th>${t("assoc")}</th><th>${t("hand")}</th><th>${t("grip")}</th><th>${t("style")}</th>
            <th class="num">${t("rating")}</th><th class="num">${t("delta")}</th>
          </tr></thead>
          <tbody>${tableRows}</tbody>
        </table>
      </div>
      <button class="side-nav" id="next-month" ${nextTarget ? "" : "disabled"} title="${nextTarget === "latest" ? t("latest") : (nextTarget || "")}"><span>›</span></button>
    </div>`;

  app.querySelectorAll(".tab").forEach((b) =>
    b.addEventListener("click", () => { location.hash = `#/${b.dataset.g}/${curMonth}`; }));
  const range = el("month-range"), tlCur = el("tl-cur");
  range.addEventListener("input", () => { tlCur.textContent = monthLabel(Number(range.value)); });
  range.addEventListener("change", () => {
    const v = Number(range.value);
    const target = v >= months.length ? "latest" : months[v];
    if (target !== curMonth) location.hash = `#/${gender}/${target}`;
  });
  if (prevTarget) el("prev-month").addEventListener("click", () => { location.hash = `#/${gender}/${prevTarget}`; });
  if (nextTarget) el("next-month").addEventListener("click", () => { location.hash = `#/${gender}/${nextTarget}`; });
}

// ---------------------------------------------------------------- player
async function renderPlayer(id) {
  const app = el("app");
  app.innerHTML = `<div class="loading">Loading…</div>`;
  // event pages opened from here link back to this player
  sessionStorage.setItem("ttr-event-back", `#/player/${id}`);

  const shard = String(Number(id) % 64).padStart(2, "0");
  const data = await fetchJSON(`data/history/shard-${shard}.json`);
  const p = data[id];
  if (!p) { app.innerHTML = `<div class="error">${t("notFound")}</div>`; return; }

  const [name, cn, sex, yob, hand, grip, style, assoc, peak, final] = p.m;
  const series = p.s;
  const rec = { en: name, cn };

  // current rating & rank (from latest full ranking; retired players fall back
  // to their final rating from the shard meta)
  let curRating = t("notRanked"), curRank = t("notRanked");
  try {
    const latest = await fetchJSON("data/latest.json");
    const hit = latest[sex === "M" ? "MS" : "WS"].find((r) => r[1] === Number(id));
    if (hit) { curRank = hit[0]; curRating = hit[2]; }
    else if (typeof final === "number") { curRating = final; }
  } catch (_) { /* offline tolerance */ }

  const idx = await fetchJSON("data/index.json");
  const latestMi = monthIdx(idx.months[idx.months.length - 1]);
  const age = yob ? new Date().getFullYear() - yob : "?";
  const ageStyle = typeof age === "number" ? ` style="color:${ageColor(age)}"` : "";

  // event results (shard "e": [[tid,cat,resCode],...])
  let resultsHTML = "", resRows = null;
  const RES_CAP = 15;
  if (p.e && p.e.length) {
    const evIdx = await eventsIndex();
    const evMap = new Map(evIdx.map((r) => [r[0], r]));
    const endOf = (tid) => { const ev = evMap.get(tid); return ev ? ev[3] : ""; };
    resRows = p.e.slice()
      .sort((a, b) => endOf(b[0]).localeCompare(endOf(a[0])))
      .map(([tid, cat, res]) => {
      const ev = evMap.get(tid);
      if (!ev) return "";
      return `<tr><td class="muted">${ev[3].slice(0, 7)}</td>` +
        `<td><a class="player-link" href="#/event/${tid}">${esc(ev[1])}</a></td>` +
        `<td>${cat === 0 ? "MS" : "WS"}</td>` +
        `<td><span class="res-badge res-${res}">${resLabel(res)}</span></td></tr>`;
    });
    resultsHTML = `<div class="card">
      <div class="chart-title">${t("eventResults")} (${p.e.length})</div>
      <table class="matches results"><tbody id="results-body">${resRows.slice(0, RES_CAP).join("")}</tbody></table>
      ${resRows.length > RES_CAP ? `<button class="chip" id="results-toggle" data-exp="0">${t("showAll")}</button>` : ""}
    </div>`;
  }

  app.innerHTML = `
    <div class="card">
      <a class="back-link" href="${sessionStorage.getItem("ttr-back") || "#/"}">${t("back")}</a>
      <div class="player-head" style="margin-top:8px">
        <h2>${esc(lang === "zh" ? cn : name)}</h2>
        <span class="alt-name">${esc(altName(rec))}</span>
        <span>${flagImg(assoc)}<span class="assoc">${esc(assoc)}</span></span>
      </div>
      <div class="meta-grid">
        <div class="meta-item"><div class="k">${t("sex")}</div><div class="v">${sex === "M" ? t("male") : t("female")}</div></div>
        <div class="meta-item"><div class="k">${t("age")}</div><div class="v"${ageStyle}>${age}</div></div>
        <div class="meta-item"><div class="k">${t("hand")}</div><div class="v">${localizedAttr(hand)}</div></div>
        <div class="meta-item"><div class="k">${t("grip")}</div><div class="v">${localizedAttr(grip)}</div></div>
        <div class="meta-item"><div class="k">${t("style")}</div><div class="v">${localizedAttr(style)}</div></div>
        <div class="meta-item"><div class="k">${t("curRating")}</div><div class="v">${curRating}</div></div>
        <div class="meta-item"><div class="k">${t("curRank")}</div><div class="v">${curRank}</div></div>
        <div class="meta-item"><div class="k">${t("peak")}</div><div class="v">${peak}</div></div>
      </div>
    </div>
    <div class="card">
      <div class="chart-title">${t("ratingHistory")}</div>
      <div id="chart-container"></div>
    </div>
    ${resultsHTML}`;

  const rt = document.getElementById("results-toggle");
  if (rt && resRows) rt.addEventListener("click", () => {
    const expanded = rt.dataset.exp === "1";
    el("results-body").innerHTML = expanded ? resRows.slice(0, RES_CAP).join("") : resRows.join("");
    rt.textContent = expanded ? t("showAll") : t("collapse");
    rt.dataset.exp = expanded ? "0" : "1";
  });

  drawChart(el("chart-container"), series, latestMi);
}

// ---------------------------------------------------------------- chart
function drawChart(container, series, latestMi) {
  if (!series.length) { container.innerHTML = ""; return; }
  const W = 920, H = 320, padL = 52, padR = 16, padT = 14, padB = 32;
  const xs = series.map((p) => p[0]);
  const ys = series.map((p) => p[1]);
  const x0 = Math.min(...xs);
  const x1 = Math.max(latestMi, Math.max(...xs));
  const yMin = Math.min(...ys), yMax = Math.max(...ys);
  const y0 = Math.floor((yMin - 60) / 100) * 100;
  const y1 = Math.ceil((yMax + 60) / 100) * 100;
  const X = (mi) => padL + ((W - padL - padR) * (mi - x0)) / Math.max(1, x1 - x0);
  const Y = (r) => padT + (H - padT - padB) * (1 - (r - y0) / (y1 - y0));

  let s = `<svg width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" font-family="inherit">`;

  // y grid every 200
  for (let r = Math.ceil(y0 / 200) * 200; r <= y1; r += 200) {
    s += `<line x1="${padL}" y1="${Y(r)}" x2="${W - padR}" y2="${Y(r)}" stroke="#e5e7eb"/>`;
    s += `<text x="${padL - 6}" y="${Y(r) + 4}" text-anchor="end" font-size="11" fill="#6b7280">${r}</text>`;
  }
  // x ticks every 24 months
  for (let mi = Math.ceil(x0 / 24) * 24; mi <= x1; mi += 24) {
    s += `<line x1="${X(mi)}" y1="${H - padB}" x2="${X(mi)}" y2="${H - padB + 4}" stroke="#9ca3af"/>`;
    s += `<text x="${X(mi)}" y="${H - padB + 16}" text-anchor="middle" font-size="11" fill="#6b7280">${2004 + Math.floor(mi / 12)}</text>`;
  }
  // axes
  s += `<line x1="${padL}" y1="${padT}" x2="${padL}" y2="${H - padB}" stroke="#9ca3af"/>`;
  s += `<line x1="${padL}" y1="${H - padB}" x2="${W - padR}" y2="${H - padB}" stroke="#9ca3af"/>`;

  // series polyline
  const pts = series.map(([mi, r]) => `${X(mi).toFixed(1)},${Y(r).toFixed(1)}`).join(" ");
  s += `<polyline points="${pts}" fill="none" stroke="#1a5fb4" stroke-width="2"/>`;

  // dashed flat extension to latest month
  const [lastMi, lastR] = series[series.length - 1];
  if (lastMi < x1) {
    s += `<line x1="${X(lastMi)}" y1="${Y(lastR)}" x2="${X(x1)}" y2="${Y(lastR)}" stroke="#1a5fb4" stroke-width="1.5" stroke-dasharray="4 3" opacity=".6"/>`;
  }
  // last point marker
  s += `<circle cx="${X(lastMi)}" cy="${Y(lastR)}" r="3.5" fill="#1a5fb4"/>`;
  s += `<text x="${Math.min(X(lastMi) + 6, W - padR - 40)}" y="${Y(lastR) - 6}" font-size="12" fill="#1a5fb4" font-weight="600">${lastR}</text>`;

  s += `</svg>`;
  container.innerHTML = s;
}

// ---------------------------------------------------------------- events
// events-index.json rows: [tid, name, start, end, org, weight, [ms podium], [ws podium]]
// events/<tid>.json: {n,s,e,o,w,pa:{pid:assoc},MS:{t|b|x|r|q},WS:{...}}
//   t = bracket tree [a,x,res,w,feederA,feederX,games,wo] (feeder null = entered here)
//   b = bronze match [a,x,res,w,games,wo]
//   x = leftover (placement/unlinked) matches, same shape as r
//   r = rounds fallback [[roundCode,[[a,x,res,w,games,wo],...]],...]
//   q = qualification list [[a,x,res,w,roundCode,games,wo],...]
// shard "e": [[tid,cat,resCode],...]; cat 0=MS 1=WS
const RES_LABEL = { 0: ["冠军", "Champion"], 1: ["亚军", "Runner-up"], 2: ["四强", "Semifinalist"],
  3: ["八强", "Quarterfinalist"], 4: ["16强", "R16"], 5: ["32强", "R32"], 6: ["64强", "R64"],
  7: ["128强", "R128"], 8: ["资格赛", "Qual."] };
const ROUND_LABEL = { 0: ["决赛", "Final"], 1: ["半决赛", "Semifinals"], 2: ["1/4决赛", "Quarterfinals"],
  3: ["R16", "R16"], 4: ["R32", "R32"], 5: ["R64", "R64"], 6: ["R128", "R128"], 7: ["R256", "R256"],
  "-1": ["小组赛/其他", "Groups/other"] };
const QUAL_LABEL = { 12: "QR4", 13: "QR8", 14: "QR16", 15: "QR32", 16: "QR64", "-1": "-" };
const resLabel = (c) => (RES_LABEL[c] || ["?", "?"])[lang === "zh" ? 0 : 1];
const roundLabel = (c) => (ROUND_LABEL[c] || ["?", "?"])[lang === "zh" ? 0 : 1];
const qualLabel = (c) => QUAL_LABEL[c] || "-";

function tierOf(w) {
  w = Math.round(w * 100) / 100;   // stored as Float32 (1.3 → 1.29999995)
  if (w >= 2.0) return ["tier-major", t("tierMajor")];
  if (w >= 1.3) return ["tier-high", t("tierHigh")];
  if (w >= 1.0) return ["tier-regular", t("tierRegular")];
  return ["tier-other", t("tierOther")];
}

let eventsIndexP = null;
function eventsIndex() {
  if (!eventsIndexP) eventsIndexP = fetchJSON("data/events-index.json");
  return eventsIndexP;
}

const podiumName = (nm, id, cls) => id
  ? `<a class="player-link ${cls}" href="#/player/${id}">${esc(playerName(nm, id))}</a>` : "";

function podiumLine(cat, pod, nm) {
  if (!pod || !pod[0]) return "";
  const sf = pod[2] || pod[3]
    ? `<span class="ev-sf">${t("podiumSF")}: ${podiumName(nm, pod[2], "")}${pod[3] ? " · " + podiumName(nm, pod[3], "") : ""}</span>` : "";
  return `<div class="ev-podium"><span class="ev-cat">${cat}</span>` +
    `<span>🥇${podiumName(nm, pod[0], "ev-champ")}</span>` +
    `<span>🥈${podiumName(nm, pod[1], "")}</span>${sf}</div>`;
}

let evYear = null, evTier = -1;   // filter state (null year = latest, -1 tier = all)

async function renderEvents() {
  const app = el("app");
  app.innerHTML = `<div class="loading">Loading…</div>`;
  sessionStorage.removeItem("ttr-event-back");   // list → event has no player context
  const rows = await eventsIndex();
  const nm = await nameMap();

  const years = [...new Set(rows.map((r) => r[3].slice(0, 4)))];
  if (!evYear || !years.includes(evYear)) evYear = years[0];
  const tiers = [2.0, 1.3, 1.0, 0.0];
  const tierNames = [t("tierMajor"), t("tierHigh"), t("tierRegular"), t("tierOther")];

  const yearChips = years.map((y) =>
    `<button class="chip${y === evYear ? " active" : ""}" data-y="${y}">${y}</button>`).join("");
  const tierChips = [`<button class="chip${evTier === -1 ? " active" : ""}" data-t="-1">${t("allTiers")}</button>`]
    .concat(tiers.map((w, i) =>
      `<button class="chip${evTier === i ? " active" : ""}" data-t="${i}">${tierNames[i]}</button>`)).join("");

  const shown = rows.filter((r) => {
    if (!r[3].startsWith(evYear)) return false;
    if (evTier === -1) return true;
    const w = Math.round(r[5] * 100) / 100;
    return w >= tiers[evTier] && (evTier === 0 || w < tiers[evTier - 1]);
  });

  const cards = shown.map((r) => {
    const [tid, name, start, end, org, w, msPod, wsPod] = r;
    const [tierCls, tierName] = tierOf(w);
    return `<div class="event-card card">
      <div class="ev-head"><a class="ev-name player-link" href="#/event/${tid}">${esc(name)}</a><span class="tier ${tierCls}">${tierName}</span></div>
      <div class="ev-meta">${start} ~ ${end}${org && org !== "?" ? ` · ${flagImg(org)}${esc(org)}` : ""}</div>
      ${podiumLine("MS", msPod, nm)}${podiumLine("WS", wsPod, nm)}
    </div>`;
  }).join("");

  app.innerHTML = `
    <div class="card toolbar">
      <div class="chips years">${yearChips}</div>
      <div class="chips">${tierChips}</div>
    </div>
    <div class="events-grid">${cards || `<div class="loading">—</div>`}</div>`;

  app.querySelectorAll(".chip[data-y]").forEach((b) =>
    b.addEventListener("click", () => { evYear = b.dataset.y; renderEvents(); }));
  app.querySelectorAll(".chip[data-t]").forEach((b) =>
    b.addEventListener("click", () => { evTier = Number(b.dataset.t); renderEvents(); }));
}

// ---- bracket rendering: absolutely-positioned player boxes over an SVG layer
const BK = { ROW: 28, COL: 196, BOXW: 176, BOXH: 22, HEAD: 26 };

// walkover/retirement marker: wo flag, or every set 11:0 (a "score" that in
// practice means the match was never really played)
const isWoMatch = (games, wo) => {
  if (String(wo) === "1") return true;
  const sets = String(games || "").trim().split(/\s+/).filter(Boolean);
  return sets.length >= 2 && sets.every((s) => s === "11:0" || s === "0:11");
};

function bkBox(item, side, nm, pa) {
  const pid = side === "a" ? item.n[0] : item.n[1];
  const w = item.n[3];
  const games = item.n[6], wo = item.n[7];
  const won = pid === w;
  const isWo = isWoMatch(games, wo);
  // score shown next to the winner, always in "winner:loser" form
  let score = item.n[2] || "";
  if (score && w === item.n[1]) {
    const p = score.split(":");
    if (p.length === 2) score = `${p[1]}:${p[0]}`;
  }
  const x = (item.maxDepth - item.depth) * BK.COL;
  const y = BK.HEAD + (side === "a" ? item.yA : item.yX) * BK.ROW;
  const assoc = pa && pa[pid] ? pa[pid] : null;
  const title = `${games || ""}${isWo ? " " + t("wo") : ""}`.trim();
  return `<a class="bk-box${won ? " won" : ""}${isWo ? " wo" : ""}" style="left:${x}px;top:${y}px" ` +
    `href="#/player/${pid}" title="${esc(title)}">` +
    `${assoc ? `<img class="flag" src="data/flags/${esc(assoc)}.png" alt="" onerror="this.style.visibility='hidden'">` : ""}` +
    `<span class="bk-name">${esc(playerName(nm, pid))}</span>` +
    `${won ? (isWo ? `<span class="bk-score bk-wo">${t("wo")}</span>` : (score ? `<span class="bk-score">${esc(score)}</span>` : "")) : ""}</a>`;
}

function bracketHTML(tree, nm, pa, opts) {
  opts = opts || {};
  const base = opts.base || 0;      // round-code offset (quarter charts start at QF)
  const bronze = opts.bronze || null;
  // Classic match-centric layout: the two players of a match always sit in
  // adjacent rows, and row spacing doubles with each round. A match at depth d
  // (0 = final) spans 2^(maxDepth-d+1) slot rows; its two slots are the
  // adjacent rows at the center of that span, and its two feeder matches tile
  // the upper/lower halves. Byes simply leave their half empty.
  let maxDepth = 0;
  (function md(n, d) {
    maxDepth = Math.max(maxDepth, d);
    if (n[4]) md(n[4], d + 1);
    if (n[5]) md(n[5], d + 1);
  })(tree, 0);

  const items = [];
  function place(n, d, top, parent) {
    const span = Math.pow(2, maxDepth - d + 1);
    const mid = top + span / 2;
    const item = { n, depth: d, maxDepth, parent, yA: mid - 1, yX: mid };
    item.ca = n[4] ? place(n[4], d + 1, top, item) : null;
    item.cx = n[5] ? place(n[5], d + 1, mid, item) : null;
    items.push(item);
    return item;
  }
  place(tree, 0, 0, null);

  const W = (maxDepth + 1) * BK.COL + 8;
  let H = BK.HEAD + Math.pow(2, maxDepth + 1) * BK.ROW + 8;
  const slotY = (ry) => BK.HEAD + ry * BK.ROW + BK.BOXH / 2;

  // connectors: each match gets the classic pair-merge (two stubs + vertical
  // join) on its right, then an elbow from the merge point into the slot it
  // feeds in the next round
  const L = (pts) => `<polyline points="${pts}" fill="none" stroke="#c9ced6" stroke-width="1.2"/>`;
  let lines = "";
  for (const it of items) {
    if (!it.parent) continue;
    const p = it.parent;
    const x1 = (maxDepth - it.depth) * BK.COL + BK.BOXW;
    const x2 = (maxDepth - p.depth) * BK.COL;
    const xm = (x1 + x2) / 2, xj = (x1 + xm) / 2;
    const yA = slotY(it.yA), yX = slotY(it.yX), ym = (yA + yX) / 2;
    const py = slotY(p.ca === it ? p.yA : p.yX);
    lines += L(`${x1},${yA} ${xj},${yA}`) + L(`${x1},${yX} ${xj},${yX}`) +
             L(`${xj},${yA} ${xj},${yX}`) +
             L(`${xj},${ym} ${xm},${ym} ${xm},${py} ${x2},${py}`);
  }

  let heads = "";
  for (let d = 0; d <= maxDepth; d++) {
    heads += `<div class="bk-head" style="left:${(maxDepth - d) * BK.COL}px">${roundLabel(base + d)}</div>`;
  }

  let boxes = "";
  for (const it of items) boxes += bkBox(it, "a", nm, pa) + bkBox(it, "x", nm, pa);

  // bronze (3rd-place) match: drawn below the final column, clearly labeled
  if (bronze) {
    const f = items[items.length - 1];   // the final (depth 0, placed last)
    const bit = { n: bronze, depth: 0, maxDepth, yA: f.yX + 2, yX: f.yX + 3 };
    heads += `<div class="bk-head bk-bronze-head" style="left:${maxDepth * BK.COL}px;top:${BK.HEAD + (f.yX + 1) * BK.ROW + 3}px">${t("bronzeMatch")}</div>`;
    boxes += bkBox(bit, "a", nm, pa) + bkBox(bit, "x", nm, pa);
    H = Math.max(H, BK.HEAD + (f.yX + 4) * BK.ROW + 8);
  }

  return `<div class="bracket" style="width:${W}px;height:${H}px">` +
    `<svg class="bk-lines" width="${W}" height="${H}">${lines}</svg>${heads}${boxes}</div>`;
}

// Split big draws into several page-flow charts instead of one scrolled one:
// the top chart holds the final rounds (SF + F, i.e. 4-2-1), then each quarter
// of the draw gets its own chart (QF subtree). Draws of ≤5 rounds stay single.
function treeCharts(tree, nm, pa, bronze) {
  let maxDepth = 0;
  (function md(n, d) {
    maxDepth = Math.max(maxDepth, d);
    if (n[4]) md(n[4], d + 1);
    if (n[5]) md(n[5], d + 1);
  })(tree, 0);
  const wrap = (html) => `<div class="bk-scroll">${html}</div>`;
  if (maxDepth + 1 <= 5 || !tree[4] || !tree[5]) {
    return wrap(bracketHTML(tree, nm, pa, { bronze }));
  }
  const strip = (n) => [n[0], n[1], n[2], n[3], null, null, n[6], n[7]];
  const topTree = [tree[0], tree[1], tree[2], tree[3], strip(tree[4]), strip(tree[5]), tree[6], tree[7]];
  const section = (label) => `<div class="bk-section"><span>${label}</span></div>`;
  let out = section(t("finalStage")) + wrap(bracketHTML(topTree, nm, pa, { bronze }));
  const qfs = [tree[4][4], tree[4][5], tree[5][4], tree[5][5]];
  let qi = 0;
  for (const q of qfs) {
    if (!q) continue;
    qi += 1;
    out += section(t("quarter")(qi)) + wrap(bracketHTML(q, nm, pa, { base: 2 }));
  }
  return out;
}

function matchRowHTML(a, x, res, w, nm, extra, games, wo) {
  const cls = (pid) => pid === w ? " class=\"player-link m-won\"" : " class=\"player-link\"";
  const woTag = isWoMatch(games, wo) ? ` <span class="wo-tag">${t("wo")}</span>` : "";
  return `<tr><td><a${cls(a)} href="#/player/${a}">${esc(playerName(nm, a))}</a></td>` +
    `<td class="num">${esc(res)}${woTag}</td>` +
    `<td><a${cls(x)} href="#/player/${x}">${esc(playerName(nm, x))}</a></td>${extra || ""}</tr>`;
}

let evCat = 0;   // event page tab state: 0=MS 1=WS

async function renderEvent(tid) {
  const app = el("app");
  app.innerHTML = `<div class="loading">Loading…</div>`;
  const d = await fetchJSON(`data/events/${tid}.json`);
  const nm = await nameMap();
  const [tierCls, tierName] = tierOf(d.w);

  const cats = [];
  if (d.MS) cats.push(0);
  if (d.WS) cats.push(1);
  if (!cats.includes(evCat)) evCat = cats[0];
  const catKey = evCat === 0 ? "MS" : "WS";
  const p = d[catKey] || {};

  let body = "";
  if (p.t) {
    body = treeCharts(p.t, nm, d.pa, p.b || null);
  } else if (p.r) {
    body = `<div class="chart-title">${t("groupList")}</div>` + p.r.map(([code, rows]) =>
      `<div class="round-block"><div class="round-name">${roundLabel(code)}</div>
       <table class="matches">${rows.map((m) => matchRowHTML(m[0], m[1], m[2], m[3], nm, null, m[4], m[5])).join("")}</table></div>`
    ).join("");
    if (p.b) {
      body += `<div class="round-block"><div class="round-name">${t("bronzeMatch")}</div>
        <table class="matches">${matchRowHTML(p.b[0], p.b[1], p.b[2], p.b[3], nm, null, p.b[4], p.b[5])}</table></div>`;
    }
  }
  if (p.x) {
    const nx = p.x.reduce((s, [, rows]) => s + rows.length, 0);
    body += `<details class="qual"><summary>${t("otherMatches")} (${nx})</summary>` + p.x.map(([code, rows]) =>
      `<div class="round-block"><div class="round-name">${roundLabel(code)}</div>
       <table class="matches">${rows.map((m) => matchRowHTML(m[0], m[1], m[2], m[3], nm, null, m[4], m[5])).join("")}</table></div>`
    ).join("") + `</details>`;
  }
  if (p.q) {
    body += `<details class="qual"><summary>${t("qualList")} (${p.q.length})</summary>
      <table class="matches">${p.q.map((m) =>
        matchRowHTML(m[0], m[1], m[2], m[3], nm, `<td class="num muted">${qualLabel(m[4])}</td>`, m[5], m[6])).join("")}</table></details>`;
  }

  // back link: when the event page was reached from a player page, offer a
  // direct way back to that player (kept across MS/WS tab switches)
  const backPlayer = sessionStorage.getItem("ttr-event-back");
  const backHTML = backPlayer
    ? `<a class="back-link" href="${backPlayer}">${t("backPlayer")}</a>
       <a class="back-link muted" href="#/events">${t("backEvents")}</a>`
    : `<a class="back-link" href="#/events">${t("backEvents")}</a>`;

  app.innerHTML = `
    <div class="card">
      ${backHTML}
      <div class="player-head" style="margin-top:8px">
        <h2>${esc(d.n)}</h2><span class="tier ${tierCls}">${tierName}</span>
      </div>
      <div class="ev-meta">${d.s} ~ ${d.e}${d.o && d.o !== "?" ? ` · ${flagImg(d.o)}${esc(d.o)}` : ""}</div>
    </div>
    <div class="card toolbar">
      <div class="tabs">
        ${cats.map((c) => `<button class="tab${c === evCat ? " active" : ""}" data-c="${c}">${c === 0 ? t("men") : t("women")}</button>`).join("")}
      </div>
    </div>
    <div class="card">${body || `<div class="loading">—</div>`}</div>`;

  app.querySelectorAll(".tab[data-c]").forEach((b) =>
    b.addEventListener("click", () => { evCat = Number(b.dataset.c); renderEvent(tid); }));
}

// ---------------------------------------------------------------- search
const si = el("search-input"), sr = el("search-results");
function closeSearch() { sr.classList.add("hidden"); }

async function onSearch() {
  const q = si.value.trim().toLowerCase();
  if (!q) { closeSearch(); return; }
  const rows = await fetchJSON("data/search.json");
  const hits = rows
    .filter(([, en, cn]) => en.toLowerCase().includes(q) || cn.toLowerCase().includes(q))
    .slice(0, 15);
  sr.innerHTML = hits.length
    ? hits.map(([id, en, cn]) =>
        `<div class="search-item" data-id="${id}"><span>${esc(en)}</span><span class="cn">${esc(cn)}</span></div>`).join("")
    : `<div class="search-item">—</div>`;
  sr.classList.remove("hidden");
  sr.querySelectorAll(".search-item[data-id]").forEach((d) =>
    d.addEventListener("mousedown", () => {
      location.hash = `#/player/${d.dataset.id}`;
      si.value = "";
      closeSearch();
    }));
}
si.addEventListener("input", onSearch);
si.addEventListener("focus", onSearch);
document.addEventListener("click", (e) => {
  if (!e.target.closest(".search-box")) closeSearch();
});

// ---------------------------------------------------------------- chrome
function applyLang() {
  document.documentElement.lang = lang === "zh" ? "zh-CN" : "en";
  el("ui-title").textContent = t("title");
  el("nav-events").textContent = t("events");
  el("lang-toggle").textContent = lang === "zh" ? "EN" : "中文";
  si.placeholder = t("searchPh");
  document.title = lang === "zh"
    ? "乒乓球 ELO 积分排名"
    : "Table Tennis ELO Rankings";
}
el("lang-toggle").addEventListener("click", () => {
  lang = lang === "zh" ? "en" : "zh";
  localStorage.setItem("ttr-lang", lang);
  applyLang();
  render();
});

async function renderFooter() {
  try {
    const idx = await fetchJSON("data/index.json");
    el("footer").textContent = t("footer")(idx.generated, idx.players);
  } catch (_) { /* ignore */ }
}

applyLang();
window.addEventListener("hashchange", render);
render();
